### ISSUE TITLE
Weird overlay bug on new windows update

### ISSUE THREAD

**Issue by Moonixiali** [rocksdanister/lively#100]
**Describe the bug**
Wallpaper overlays the desktop making icons/taskbar disappear

**To Reproduce**
1. Start up OS with lively opening on start-up
2. Set any background with lively
3. Click on the desktop
4. The video overlays the desktop icons and anything else

**Expected behavior**
Expected the desktop to have the video underneath the icons and taskbar.

**Screenshots/Video**
None, might update if needed

**Desktop (please complete the following information):**
 - OS: Windows 10 home 2004 OS build 19041.450
- Which wallpaper was running at the time if any. (Any wallpaper works with recreating)

**Additional context**
Updated to latest windows build last night, found lively breaks when you have it on start-up. Restarting the program fixes it though

**Log file**
There's no crash and no log file from what I'm seeing.

**Comment by rocksdanister** [comment]
I'm running the same version of windows 10 with no issue, so the cause is something else.
Have you tried restarting windows?
Even if the application did not crash, log is created - share the logfile.txt file instead.

**Comment by Moonixiali** [comment]
> I'm running the same version of windows 10 with no issue, so the cause is something else.
> Have you tried restarting windows?
> Even if the application did not crash, log is created - share the logfile.txt file instead.

[20200814_091540.txt](https://github.com/rocksdanister/lively/files/5081441/20200814_091540.txt)
The latest one is from 2 days ago, but here you go.

**Comment by rocksdanister** [comment]
No, what I mean is logfile.txt file is created in `Documents/Lively Wallpaper` everytime lively is run regardless of crash.
Can you send that file after trying to set a wallpaper?
