### ISSUE TITLE
4K WEBM Videos use 10x more memory than 1080p mp4

### ISSUE THREAD

**Issue by ufukbakan** [rocksdanister/lively#1000]
**To Reproduce**
1. Download same video in two different formats : 1080p Mp4 and 4K Webm (I've used https://loader.to/en47/4k-video-downloader.html)
2. Open LivelyWallpeper set .Mp4 video as background
3. Open Task Manager and check mpv.exe memory usage
4. Open LivelyWallpeper set .Webm video as background
5. Open Task Manager and check mpv.exe memory usage

**Expected behavior**
.Webm video uses 10 times more memory than .mp4 video

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/44516872/148690571-f230e8ba-4d22-41ea-8103-e0565be6e54a.png)

**Log file (Important)**
[lively_log_20220109_191156.zip](https://github.com/rocksdanister/lively/files/7835401/lively_log_20220109_191156.zip)

**Comment by rocksdanister** [comment]
1080/720p x264 video format is recommended, webm memory usage can be due to many reasons such as lack of decoding support in the gpu and the higher resolution (4k) of the clip.

Further read:
https://github.com/rocksdanister/lively/wiki/Performance
