### ISSUE TITLE
Application is already running message

### ISSUE THREAD

**Issue by babygabby** [rocksdanister/lively#101]
Double clicking on the Lively desktop icon gives me a "process is already running. If not responding, please stop in the task manager". Can't seem to uninstall the app as well.

**Comment by babygabby** [comment]
Could you please advise me on how to remove the entire program from my computer?

**Comment by rocksdanister** [comment]
Lively is running in the tray.
![Annotation 2020-07-21 081704](https://user-images.githubusercontent.com/17554161/90503022-6676ca00-e16c-11ea-83f6-e0d1e470433f.jpg)

Just rightclick the lively icon in [system-tray](https://www.tutorialspoint.com/windows10/windows10_system_tray.htm) to access traymenu -> select "Open lively" to relaunch lively.
To exit/uninstall select "Exit" option in traymenu and then run the Uninstaller.

The beginning tutorials video have shown this.
