### ISSUE TITLE
Per Desktop Wallpapers

### ISSUE THREAD

**Issue by KaiCodesWithGithub** [rocksdanister/lively#1010]
**Main Idea**
My idea is per desktop wallpapers
(
![image](https://user-images.githubusercontent.com/70831065/149845256-40f27d19-f753-4c81-b85c-27238dea5710.png)
)

**Reasoning**
I believe this would be an awesome feature for people who fully take advantage of these desktops and allow for different workspace themes(one for home use, another for coding for example and another for work maybe)
I would think this would be a flagship feature for your application and would significantly put you on top of the other competitors in this field of applications
I believe this feature is in both Windows 10 and 11

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/488

Thanks for the feedback.
