### ISSUE TITLE
Screensaver timer should be paused when the Desktop is not in focus

### ISSUE THREAD

**Issue by Stick1000** [rocksdanister/lively#1014]
**Describe the bug**
^ Title. Every time I watch a movie or go afk in a game, the screensaver activates, interrupting the movie or my gameplay.

**To Reproduce**
1. Enable Screensaver.
2. Go afk.
3. Screensaver activates after set time.

**Expected behavior**
This should not happen, or at least allow the user to set the context of being "inactive".

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/732

Windows screensaver method does not have this problem:
https://github.com/rocksdanister/lively/wiki/Screen-Saver#2-windows-screensaver-file
