### ISSUE TITLE
lively crashes when I try to turn up/down or mute audio using laptops audio buttons 

### ISSUE THREAD

**Issue by FabulousBastard** [rocksdanister/lively#1019]
**To Reproduce**

1. Press one of the audio buttons on the function row on laptop
2. Wallpaper disappears and then reappears
3. If you press one of the audio buttons 2 times quickly a error window appears:

![lively crashes when I try to turn up_down or mute audio using laptops audio buttons · Issue #1019 · rocksdanister_lively and 3 more pages - Profile 1 - Microsoft​ Edge 1_22_2022 3_19_00 PM](https://user-images.githubusercontent.com/81468379/150642085-cd5befd5-f70d-450f-a6a8-4d180be4fc10.png)

**Expected behavior**
I expected the audio to change but that doesn't work ether 

**Desktop:**
OS: Windows 11 Home Insider Preview. Build 22533.rs_prerelease.220107-2122
I had a picture wallpaper runing at the time

**Additional context**
I only started experiencing this problem after my last windows update.
Before that everything was alright

**Log file**
[20220122_093220.txt](https://github.com/rocksdanister/lively/files/7918525/20220122_093220.txt)

**Comment by rocksdanister** [comment]
```2022-01-22 09:47:48.9293|INFO|livelywpf.Views.WndProcMsgWindow|WM_TASKBARCREATED: New taskbar created.
2022-01-22 09:47:48.9293|INFO|livelywpf.Views.WndProcMsgWindow|Explorer crashed, pid mismatch: 9000 != 48
2022-01-22 09:47:48.9293|INFO|livelywpf.Core.WinDesktopCore|Restarting wallpaper service..
2022-01-22 10:06:37.2615|INFO|livelywpf.Views.WndProcMsgWindow|WM_TASKBARCREATED: New taskbar created.
2022-01-22 10:06:37.2615|INFO|livelywpf.Views.WndProcMsgWindow|Explorer crashed, pid mismatch: 48 != 2248
2022-01-22 10:06:37.2615|INFO|livelywpf.Core.WinDesktopCore|Restarting wallpaper service..
```

New taskbar and explorer process is being created, if it happens too many times in 30s that's when you get that error message from Lively.

Does this only happen when volume is changed? have you tried just letting it run for sometime and see if it crash.

**Comment by FabulousBastard** [comment]
I will try to let it run for a while, will talk to you after a while

**Comment by FabulousBastard** [comment]
After waiting for a while nothing happened so it probably only crashes when I try to change the audio volume

**Comment by rocksdanister** [comment]
I wonder if this has anything to do with the new audio flyout..
<img width="600" alt="Windows-11-proper-volume-CMS-primary" src="https://user-images.githubusercontent.com/17554161/150663592-d60d819a-25c4-4839-b02a-b562c773b62f.png">

**Comment by rocksdanister** [comment]
>I wonder if this has anything to do with the new audio flyout..

Yup... updated your Windows 11 insider build to 22538 or newer:
https://blogs.windows.com/windows-insider/2022/01/19/announcing-windows-11-insider-preview-build-22538/

>In addition to a good set of changes and improvements, this build includes some good fixes too. Pressing the hardware buttons for volume up/down should no longer cause explorer.exe to crash for some Insiders.

**Comment by FabulousBastard** [comment]
Thanks a lot
