### ISSUE TITLE
Clear Taskbar Bug

### ISSUE THREAD

**Issue by YannisRavasopoulos** [rocksdanister/lively#1020]
Description:
I have selected the Clear Taskbar Option on the panel but once my pc sleeps and i reopen it, the taskbar appears colored and defnately not transparent. The thing is the taskbar remains clear as long as my computer doesnt sleep. Once it sleeps i must reapply the clear taskbar option on the panel manually.

1. Go to "System"
2. Click on Taskbar theme
3. Scroll down to Clear
4.  Put pc to sleep
5.  May experience same bug as me...

 - OS: Windows 10
 - PC: Asus X570ZD (Laptop)

**Comment by 93khuang** [comment]
+1 to this issue, or at least a similar/tangential issue. 
I have 2 monitors. Upon initial selection of a Taskbar Theme option, the 2nd monitor's Taskbar receives the updated style. 
If I have a full-screen app or perhaps simply after some time and usage, the 2nd monitor's Taskbar loses its updated style ("Clear") and reverts to its default state.
