### ISSUE TITLE
Lively buffering speed does not match browser

### ISSUE THREAD

**Issue by tellmewhy12** [rocksdanister/lively#1021]
**Describe the bug**
My internet connection isn't super fast and video wallpapers in Lively appear stuttery and pause like they are buffering. The issue disappears when selecting a very low video quality.

I can watch youtube videos on 1080p without any issue but in lively from 720p videos start stuttering.

I can of course download the wallpaper and then it works without problems.

![GIF 22 01 2022 23-29-36](https://user-images.githubusercontent.com/71931749/150657460-2ee00d14-aaad-47e4-8011-0530de0a5ea3.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909] 
![image](https://user-images.githubusercontent.com/71931749/150657497-42f2b31a-031a-4244-b834-745601e5b422.png)

- [Which wallpaper was running at the time if any.](https://www.youtube.com/watch?v=ImBa01ahRb4)

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20220122_233010.zip](https://github.com/rocksdanister/lively/files/7919412/lively_log_20220122_233010.zip)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/837
