### ISSUE TITLE
Volume button causes crash

### ISSUE THREAD

**Issue by hoii5rfgfvbvh** [rocksdanister/lively#1022]
Whenever I press the volume button my screen glitches out for a second, and then it returns to normal, but if I press it again, it boots me out of lively wallpapers and stops the wallpaper, please help

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/1019
