### ISSUE TITLE
not working on start

### ISSUE THREAD

**Issue by Restrated** [rocksdanister/lively#1023]
when i turn on my pc lively turns on but the wallpaper doesn't apply. After a day or two it gave me a this error pop up saying i need to turn this thing on in SystemPropertiesPerformance.exe so i followed all the steps and it didn't work. after a few days the same error showed up tried the same thing again didn't work. The wallpaper still works but i have to turn it on by meself

**Comment by rocksdanister** [comment]
1. Share the log.zip file: `Goto Lively settings (Gear icon) -> Misc. -> Log File`
2. Can you give me a list of running programs on your machine, anything that modifies or adds features to Windows desktop like Stardock Fences etc?

**Comment by Restrated** [comment]
> 1. Share the log.zip file: `Goto Lively settings (Gear icon) -> Misc. -> Log File`
> 2. Can you give me a list of running programs on your machine, anything that modifies or adds features to Windows desktop like Stardock Fences etc?

i have clear TB (taskbar)  thats the only one
heres the log btw
[lively_log_20220125_144137.zip](https://github.com/rocksdanister/lively/files/7937693/lively_log_20220125_144137.zip)

**Comment by rocksdanister** [comment]
>2022-01-25 08:00:57.0955|ERROR|livelywpf.Core.WinDesktopCore|Failed to setup core, WorkerW handle not found!

Yeah its failing, this is unusual - did you run any system optimizer scripts/apps that reduce the Windows shutdown delay?

**Comment by Restrated** [comment]
one, all it does it turns off v sync on  some games also it worked today
