### ISSUE TITLE
Youtube livestream wallpaper freezes after 6 hours

### ISSUE THREAD

**Issue by Mikemikemike14** [rocksdanister/lively#1024]
As the title says, any Youtube livestream wallpaper stops working after running for about 6 hours. When this happens, it results in huge CPU use, presumably because the program starts to write new lines into the log file at an extremely fast rate.

Windows 10 Home version 19043.1466
Most recent wallpaper in use: https://www.youtube.com/watch?v=coYw-eVU0Ks

Log file:
[20220126_003851.zip](https://github.com/rocksdanister/lively/files/7939294/20220126_003851.zip)

I looked into this a bit more and it seems like it's ultimately an issue with how Youtube itself works.
Perhaps the quickest and easiest workaround would be to make the program automatically refresh the stream every five hours or so.
https://github.com/ytdl-org/youtube-dl/issues/20516
https://github.com/mpv-player/mpv/issues/7499

**Comment by rocksdanister** [comment]
Logfile size will be restricted in the future https://github.com/rocksdanister/lively/issues/968

For the stream, moving forward going to use WebView2 and open the embed player so closing this issue for now.
also Thanks for sharing that big logfile!
