### ISSUE TITLE
No Sample Wallpapers

### ISSUE THREAD

**Issue by importF** [rocksdanister/lively#104]
so basicly i ran the setup and i choose to download the sample wallpapers 
after the download was done i had nowallpapers inside lively 

and i think everyone would like it if i could download the lively sample wallpapers myself

thanks for your time

**Comment by rocksdanister** [comment]
The included sample wallpapers are outdated anyway.
All the sample wallpapers and more are uploaded to lively deviantart group:
https://www.deviantart.com/livelywallpaper/gallery/
(need free account to see download button.)
