### ISSUE TITLE
Live wallpaper not working when resuming from sleep

### ISSUE THREAD

**Issue by Gautam-ask** [rocksdanister/lively#1045]
![Screenshot (33)](https://user-images.githubusercontent.com/99290811/153070085-cad80631-d019-4740-8c51-40286248f40f.png)
![Screenshot (34)](https://user-images.githubusercontent.com/99290811/153070096-3f18a614-dd25-4e4f-91d5-366d84c6bc54.png)
[lively_log_20220209_002831.zip](https://github.com/rocksdanister/lively/files/8027247/lively_log_20220209_002831.zip)
Hi, 

I have attached two screenshots and a log file. I installed lively wallpaper and selected wallpaper from lively, Once I logged out and logged in my dell XPS 13. Wallpaper went back to the old and I tried selecting the wallpapers from the lively app, it's not respondingg. Kindly help.

**Comment by rocksdanister** [comment]
Turn off picture slideshow for now https://github.com/rocksdanister/lively/issues/802
