### ISSUE TITLE
can't set web pages as wallpaper after system restart

### ISSUE THREAD

**Issue by akkuz** [rocksdanister/lively#1046]
**Describe the bug**
After I restarted my system i can't apply web page wallpapers like the cyberpunk one or audio visualizer. I can apply all wallpapers except web pages, and this after I restarted my computer.

**To Reproduce**
I click on my wallpaper and after it loads for a while it shows an error (only on web pages) and it turns back to the previous background

**Expected behavior**
I expect that web page wallpapers work like before restarting my computer.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/57033875/153216445-44e04d82-2cf6-4d5e-b4e2-bffa7ea28ed5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 19044.1466
 - wallpaper: goku (goku + parallax)

**Log file (Important)**
[20220209_134741.txt](https://github.com/rocksdanister/lively/files/8033255/20220209_134741.txt)
I tried to apply my wallpaper different times, like in lines: 176 and 161 (same error). It says: 
livelywpf.Core.WinDesktopCore|Failed launching wallpaper: Process exited before giving HWND.
(I already have latest Visual C++ Redistributable for web page wallpapers).

**Comment by rocksdanister** [comment]
Do you have any anti-virus software? maybe it deleted it.
Try reinstalling Lively.

**Comment by akkuz** [comment]
> Do you have any anti-virus software? maybe it deleted it. Try reinstalling Lively.

I will try to reinstall lively, but all files are present in their respective folders (if I click "show in folder" it opens normally). I don't know if the antivirus (I'm using avast) is interfering in other ways.

**Comment by rocksdanister** [comment]
Yup, its Avast.. everything except Windows Defender interferes with Lively x_x

Closing this as duplicate.
