### ISSUE TITLE
folder icons not showing

### ISSUE THREAD

**Issue by notevenayaan** [rocksdanister/lively#1052]
i was messing around with my settings, and suddenly all of my icons on my desktop disappeared. I was only able to access them through file manager.I returned my settings to normal, restarted it but they are still not there. Please Help

**Comment by roxxel** [comment]
> i was messing around with my settings, and suddenly all of my icons on my desktop disappeared. I was only able to access them through file manager.I returned my settings to normal, restarted it but they are still not there. Please Help

Right click on desktop -> View -> Show desktop Icons
Hope it helps

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/946
