### ISSUE TITLE
When opening Lively it shows "System Error" /  "The system detected an overrun of a stack-based buffer.."

### ISSUE THREAD

**Issue by THEBOSS619** [rocksdanister/lively#1060]
**Describe the bug**
When opening Lively it shows "System Error"

**To Reproduce**
1. Opening Lively Beta program

**Expected behavior**
To be opened the app without issues 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32247935/153972288-acc58c2c-ddcf-47c5-8cc3-4acb1904595d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 21H1 - OS Build - 19044.1561]
- The matrix wallpaper.

**Additional context**
Non

**Log file (Important)**
[logs.zip](https://github.com/rocksdanister/lively/files/8064941/logs.zip)

**Comment by THEBOSS619** [comment]
I managed to find the real cause behind this problem... it was due to UAC was disabled. So once I enabled back UAC everything is going good 👍 and it runs without any problems.

Consider to add a note if this happens to others so they at least know that it was just UAC disabled and needs to be enabled for it to function.

**Comment by rocksdanister** [comment]
I am not sure if that was the cause, I tested with UAC turned off on my system and everything works..

1. Does the error return if you turn off UAC?

3. By UAC you mean User Account Control right?

<img width="513" alt="Untitled" src="https://user-images.githubusercontent.com/17554161/154690251-b8147d8b-83b4-4392-a190-d6d97590263c.png">

**Comment by THEBOSS619** [comment]
> I am not sure if that was the cause, I tested with UAC turned off on my system and everything works..
> 
> 1. Does the error return if you turn off UAC?
> 
> 3. By UAC you mean User Account Control right?
> 
> <img width="513" alt="Untitled" src="https://user-images.githubusercontent.com/17554161/154690251-b8147d8b-83b4-4392-a190-d6d97590263c.png">
> 

1- Yes

2- Yes

Your way doesn't disable the UAC completely... In order to disable UAC completely (UAC driver doesn't load) you must do this...

Open the Windows Control Panel.

Click Administrative Tools > Local Security Policy > Security Settings > Local Policies > Security Options.

Double-click User Account Control: Run all administrators in Admin Approval Mode and select disable. Changing this setting requires a system restart.

After doing that Lively beta will have problems opening up.

**Comment by rocksdanister** [comment]
Ah I see.. so what is happening is you are disabling limited user account so everything runs as admin.
Windows App SDK does not support running as admin yet:
![unknown](https://user-images.githubusercontent.com/17554161/154748163-a43165c3-c21f-48df-b6c8-77cce54e95f5.png)

**Comment by THEBOSS619** [comment]
Exactly, thank you for your reply and time.... really appreciate it. I didn't even know that it was a limitation from the SDK itself... so thank you for pointing that out.
