### ISSUE TITLE
using 50% of my gpu

### ISSUE THREAD

**Issue by epicyeeto** [rocksdanister/lively#1062]
**Describe the bug**Livly wallpaper is using 50% of my GPU and I don't know wgy

**To Reproduce**
use livly with a wallpaper

**Expected behavior**
to not use all my gpu

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/73504007/154378295-91ca2066-b9b7-4d4d-b353-281c5b9bda98.png)

**Desktop (please complete the following information):**
 - OS: windows 11
- a wallpaper

**Additional context**

**Log file (Important)**

[lively_log_20220216_190352.zip](https://github.com/rocksdanister/lively/files/8084438/lively_log_20220216_190352.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance
