### ISSUE TITLE
Lively crashes every time I try to open it

### ISSUE THREAD

**Issue by Hudinec** [rocksdanister/lively#107]
Was told to put my crash log here - so here it is!
[20200827_174307.txt](https://github.com/rocksdanister/lively/files/5137442/20200827_174307.txt)

**Comment by blaslee** [comment]
same

**Comment by rocksdanister** [comment]
@blaslee are you getting the same error log message? otherwise its most likely caused by fps monitor tools like riva tunes statistis server - if its installed then turn detection to low and add exception to livelywpf.exe

**Comment by blaslee** [comment]
@rocksdanister I just get a message saying "Application already running". For some reason, one of my monitors reverted to my old static background and I can't get lively open to amend it.

**Comment by rocksdanister** [comment]
@blaslee https://github.com/rocksdanister/lively/issues/101
