### ISSUE TITLE
Default Video Player keeps changing / wallpaper plugin missing notification

### ISSUE THREAD

**Issue by XIAIX-code** [rocksdanister/lively#1071]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings -> Wallpaper -> Video -> Video Player'
2. Click on 'Video Player drop-down'
3. Scroll down to 'vlc'
4. Go back to the video library and pick a wallpaper that you downloaded by navigating to a YouTube URL, making that wallpaper active
5. Right-Click on the wallpaper and choose "Customize"
6. Receive error "Property file not found! (Mpv player is required.)"
7. Go back to 'Settings -> Wallpaper -> Video -> Video Player' and notice that the default video player has switched back to Mpv!!!

**Expected behavior**
I would expect to not have to install "Mpv player" since I chose "Vlc" in the settings.
I would also expect that when I choose "Vlc" as my default video player, it would stay that way!

**Screenshots/Video**

![livelywpf_8x9hR98AlF](https://user-images.githubusercontent.com/72950409/154783847-75625cef-086f-4323-ad4c-7cc1d03b3107.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro 64bit Version 21H2 (OS Build 22000.527)]
- Which wallpaper was running at the time if any.
-              https://www.youtube.com/watch?v=5g1RexNGEms

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

[lively_log_20220218_221313.zip](https://github.com/rocksdanister/lively/files/8101353/lively_log_20220218_221313.zip)

**Comment by rocksdanister** [comment]
Only mpv player is bundled with the program, when the select wallpaper plugin is not found then Lively picks the next available plugin (in this case mpv)

**Comment by rocksdanister** [comment]
I guess showing a notification plugin is missing is a good idea
