### ISSUE TITLE
Lively BETA UI Won't open

### ISSUE THREAD

**Issue by ryi3r** [rocksdanister/lively#1076]
**Describe the bug**
The Lively Beta UI won't start at all, probably because Windows Security or something.

**To Reproduce**
It happened after installing it, i did absolutely nothing more than trying to open it.

**Expected behavior**
The UI (GUI) from opening.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/50798713/155225641-6523561e-2547-4ead-bcfe-87391b88805e.png)
(Debugged Lively.UI.WinUI with Process Hacker.)

**Desktop (please complete the following information):**
Windows 10 21H2 (OS Build 19044.1526.)

**Additional context**

**Log file (Important)**
[20220222_164219.txt](https://github.com/rocksdanister/lively/files/8120409/20220222_164219.txt)
[20220222_164413.txt](https://github.com/rocksdanister/lively/files/8120410/20220222_164413.txt)

**Comment by rocksdanister** [comment]
Related https://github.com/rocksdanister/lively/issues/1060 ?

**Comment by ryi3r** [comment]
Updated and started the app without admin; still not working.

**Comment by rocksdanister** [comment]
To confirm, 
1. Were you originally doing that UAC thing and if so did this error go away after changing?
2. Check Windows Event viewer for Lively crash reason.

**Comment by ryi3r** [comment]
1. I already have UAC enabled so, yeah.
2. 

```
Faulting application name: Lively.UI.WinUI.exe, version: 1.0.0.0, time stamp: 0x619336dd
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2111, time stamp: 0x4fea8043
Exception code: 0xc000027b
Fault offset: 0x00237fd9
Faulting process id: 0x41a0
Faulting application start time: 0x01d829cacfcc71e9
Faulting application path: C:\Users\Zorro\AppData\Local\Programs\Lively Wallpaper\plugins\UI\Lively.UI.WinUI.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.0_0.319.455.0_x86__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: ba64690f-ad4d-4379-8934-f7047dd6509e
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by rocksdanister** [comment]
Can you try the latest beta:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.9.4.0

**Comment by ryi3r** [comment]
Tried it out, didn't work.

**Comment by rocksdanister** [comment]
maybe related https://github.com/rocksdanister/lively/issues/1088#issuecomment-1055889687 ?

**Comment by ryi3r** [comment]
Nope, still not working. (this is sad)

**Comment by rocksdanister** [comment]
At this point try the Windows store version of Lively (Its packaged WinUI and should work.).. as long as you don't delete the appdata folder it should pickup the current wallpaper and settings.

**Comment by ryi3r** [comment]
So... i installed the store version, it didn't, but after a restart it actually opened, so i'm guessing i had to restart my computer after installing it.
Even though the normal version is still not working, the store version is.
Thanks anyways.

**Comment by rocksdanister** [comment]
Restart is not required, I think in your case it was some unexpected interaction with the installer version being installed.

**Comment by ryi3r** [comment]
Oh, Alright!

**Comment by rocksdanister** [comment]
I would uninstall the installer version just in case, also keeping the issue open since its still a problem for installer.

**Comment by ryi3r** [comment]
Ok!

**Comment by rocksdanister** [comment]
Looks like there is a new patch that addresses some runtime installation issue: 
https://docs.microsoft.com/en-gb/windows/apps/windows-app-sdk/stable-channel#version-101

I'll update beta to v1.0.1 soon then we can test again 👍

**Comment by ryi3r** [comment]
Oh! Alright!

**Comment by rocksdanister** [comment]
@ZorroMundoYT Can you try this:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.9.5.0

**Comment by ryi3r** [comment]
Sure!

**Comment by ryi3r** [comment]
Still works as it has worked until now.
Oh yeah, btw, it worked before going into the beta branch.

**Comment by rocksdanister** [comment]
>Still works as it has worked until now.

Sorry I don't follow, you are saying it does not open?

**Comment by ryi3r** [comment]
Yes.

**Comment by ChaitanyaTejaswi** [comment]
Had similar issues with Lively.UI.WinUI.exe.
It doesn't open but the wallpaper works just fine.
What's different is I don't see no logs at C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs

This log is from the event viewer.
[Logs.zip](https://github.com/rocksdanister/lively/files/8776829/Logs.zip)

Tried installing https://aka.ms/windowsappsdk/1.0/1.0.1/windowsappruntimeinstall-1.0.1-x86.exe as mentioned here https://github.com/rocksdanister/lively/issues/1139#issuecomment-1073238696
It said a higher version of the package is already installed.
I checked my UAC too, it was set to default.

**Comment by rocksdanister** [comment]
@METACRYPT12 
1. Do you have MSI afterburner installed?
https://github.com/microsoft/PowerToys/issues/18015#issuecomment-1123061673
2. When you installed appsruntime what did the console output say? screenshot.

Wallpapers work because Lively core is separate program from UI and written in different framework.

**Comment by ChaitanyaTejaswi** [comment]
Nope I don't have MSI afterburner installed.
This is what the console says.
![image](https://user-images.githubusercontent.com/82610170/170437229-3b177ced-fd17-458d-b060-c53af2eedfe9.png)

**Comment by rocksdanister** [comment]
This is the latest version of runtime required v1.0.3:
https://aka.ms/windowsappsdk/1.0/1.0.3/windowsappruntimeinstall-1.0.3-x86.exe

Try this and screenshot; if that does not work can you also try the Windows store version of Lively?

**Comment by METACRYPT12** [comment]
This is what it says.

![image](https://user-images.githubusercontent.com/82610170/170438882-af63fcd0-7a88-482d-9cf5-7a60b526d23d.png)

Also I have the Windows store version of Lively installed.

**Comment by ChaitanyaTejaswi** [comment]
My apologies I didn't close lively before installation.
![image](https://user-images.githubusercontent.com/82610170/170439452-97866217-3096-4fba-8901-c75c9e949901.png)

The UI still doesn't show up.
Also I have Windows store version of Lively installed.

**Comment by rocksdanister** [comment]
>Also I have Windows store version of Lively installed.

So the problem is with store version of Lively? can you explain in details the steps you did like which version of Lively did you install first etc..

**Comment by ChaitanyaTejaswi** [comment]
No you got me wrong, I have been using the store version of Lively installed ever since.
All I did is I tried to launch the UI.
Also I didn't see any log in the AppData folder, the log I mentioned in the comment https://github.com/rocksdanister/lively/issues/1076#issuecomment-1138223598 is from the event viewer

**Comment by rocksdanister** [comment]
For the store version logs are located here:
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper`

**Comment by ChaitanyaTejaswi** [comment]
These are the logs I retrieved.
[20220525_125548.txt](https://github.com/rocksdanister/lively/files/8777293/20220525_125548.txt)
[20220526_131809.txt](https://github.com/rocksdanister/lively/files/8777286/20220526_131809.txt)

**Comment by ChaitanyaTejaswi** [comment]
My other device with Lively 1.0.116.0 installed from MS store works as expected.
I'm facing this issue with Lively version 1.0.117.0

**Comment by ryi3r** [comment]
> @METACRYPT12 
> 1. Do you have MSI afterburner installed?
> https://github.com/microsoft/PowerToys/issues/18015#issuecomment-1123061673
> 2. When you installed appsruntime what did the console output say? screenshot.
> 
> Wallpapers work because Lively core is separate program from UI and written in different framework.

Huh.
I actually had MSI Afterburner installed.
I'll try to use it without MSI Afterburner.

**Comment by ryi3r** [comment]
Funnily enough, it now DOES work.
Even though I like had my pc back to 0 because I installed Windows 11 (and it sucks in my opinion.)

**Comment by rocksdanister** [comment]
Can you guys try the latest beta release and see if it works:
https://github.com/rocksdanister/lively-beta/releases

**Comment by ChaitanyaTejaswi** [comment]
Updated it to 1.0.119.0 from MS store.
The GUI still doesn't work
[20220607_152933.txt](https://github.com/rocksdanister/lively/files/8852214/20220607_152933.txt)

**Comment by rocksdanister** [comment]
@METACRYPT12 uninstall the store, and try the the latest beta installer:
https://github.com/rocksdanister/lively-beta/releases

**Comment by ChaitanyaTejaswi** [comment]
This works for me.
Interestingly, the store version works after a reinstall.

**Comment by ryi3r** [comment]
Will the installer version be fixed? because outside of the MS Store it's still buggy (the background doesn't appear at all)
