### ISSUE TITLE
CTD following change of Windows default audio device

### ISSUE THREAD

**Issue by Aethandor** [rocksdanister/lively#1078]
I have two audio devices enabled on my Windows desktop pc.  
The primary one, which is usually active, is a SoundblasterX G6, which is a USB external DAC and headphone amplifier, but also I have the Realtek ALC887-based onboard audio of my Gigabyte Z390 UD which I use via S/PDIF optical output when I have Dolby Digital or DTS content to play through my 5.1 home theatre type system.
I have observed that changes which happen to the audio device usually result in Lively Wallpaper seeming to crash to desktop, a crash dump gets created by Windows and then Lively restarts itself but the animated wallpaper no longer shows.
It's reasonably reproducible.

**Comment by rocksdanister** [comment]
Can you share the logfiles ? (Settings -> Misc -> Logfile)

**Comment by Aethandor** [comment]
hi, no problem. 
I generally delete them but next time it happens I'll forward them to you.
Best regards
Ethan

⁣Sent from my Galaxy Note​
