### ISSUE TITLE
Lively won't open on startup

### ISSUE THREAD

**Issue by haminnhtri5555** [rocksdanister/lively#1079]
So, I installed Lively a few weeks ago via the MS Store. it started normally on startup, but then a few days ago, it won't run on startup at all, I checked the Task Manager, it was disabled but I didn't touch the startup tab in TM for a long time, I enabled it, restarted the computer but it keeps disable. So I decided to uninstall it and replace it with the Github version but still doesn't work, still doesn't run on startup, although it is still enabled in the Task Manager. Can someone help me? Thank you
![Task Manager Startup](https://user-images.githubusercontent.com/95166226/155538560-69877973-50fd-4836-a3e8-374f1e9139bf.png)

Note: there are two lively there because I also put one in the startup folder while trying to fix it. And still not working of course

**Comment by rocksdanister** [comment]
I would start by removing the Lively you added in startup folder and then uninstalling both store and github version.

Then do a store version install and see if its working? I think something must be interfering and editing Lively startup..

**Comment by haminnhtri5555** [comment]
> I would start by removing the Lively you added in startup folder and then uninstalling both store and github version.
> 
> Then do a store version install and see if its working? I think something must be interfering and editing Lively startup..

Well, I did it, I removed the file from the folder, uninstall all lively wallpaper then install the MS store version. But it didn't work, its status in the startup tab in Task Manager is disable, I re-enabled it then restart my computer but it still now work, and its status is also disable, again! It keep disable it self after restart, can you help me?

**Comment by rocksdanister** [comment]
That's weird, something else must be disabling it🤔
In the windows store version Lively adds startup entry as long as the settings state is true:
https://github.com/rocksdanister/lively/blob/ac82e061d3cdbab176f67c7e20c49c42739b0362/src/livelywpf/livelywpf/ViewModels/SettingsViewModel.cs#L105

Can you share the logfile.. ?

**Comment by haminnhtri5555** [comment]
> That's weird, something else must be disabling it🤔 In the windows store version Lively adds startup entry as long as the settings state is true:
> 
> https://github.com/rocksdanister/lively/blob/ac82e061d3cdbab176f67c7e20c49c42739b0362/src/livelywpf/livelywpf/ViewModels/SettingsViewModel.cs#L105
> 
> Can you share the logfile.. ?

Of course, here it is:
[lively_log_20220228_170633.zip](https://github.com/rocksdanister/lively/files/8152429/lively_log_20220228_170633.zip)
 I forgot to say, I'm in Windows 11 btw

**Comment by ElToroDM** [comment]
Same problem here. Windows 11 fresh install. I will try reinstalling via github version.

**Comment by Cokalml** [comment]
> > That's weird, something else must be disabling it🤔 In the windows store version Lively adds startup entry as long as the settings state is true:
> > https://github.com/rocksdanister/lively/blob/ac82e061d3cdbab176f67c7e20c49c42739b0362/src/livelywpf/livelywpf/ViewModels/SettingsViewModel.cs#L105
> > 
> > Can you share the logfile.. ?
> 
> Of course, here it is: [lively_log_20220228_170633.zip](https://github.com/rocksdanister/lively/files/8152429/lively_log_20220228_170633.zip) I forgot to say, I'm in Windows 11 btw

Did you find any solution? I have the same issue

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#lively-does-not-start-with-windows-startup-is-getting-disabled
