### ISSUE TITLE
Taskbar effects not working in Windows 11 DEV build 22563.1

### ISSUE THREAD

**Issue by greatsudoku** [rocksdanister/lively#1084]
**Describe the bug**
Taskbar effects (clear, blur, fluent, etc.) are no longer working in Windows 11 DEV channel build 22563.1

**To Reproduce**
1. Install Windows 11 Dev channel build 22563.1
2. The new taskbar is currently in A/B testing. The new taskbar and can be force-enabled by downloading & installing [vivetool](https://github.com/thebookisclosed/ViVe/releases), then issuing the following command in an Admin Power Shell or an Admin Command Prompt: `vivetool addconfig 26008830 2` 
3. Once this new taskbar is enabled, none of the taskbar effects in Lively Wallpaper work

**Expected behavior**
Expected behavior would be for the taskbar effects to work as they did previously. 
From what I understand Microsoft rewrote/is-rewriting the taskbar code . I tried updating to the DEV version of Lively Wallpaper to see if the DEV version worked with the new taskbar, however it still didn't work.

**Screenshots/Video**
Here's a [screenshot](https://imgur.com/a/h9j6WAd) showing taskbar setting as "clear" but taskbar remains opaque.

**Desktop (please complete the following information):**
 - OS: Windows 11 DEV channel build 22563.1 (new taskbar enabled via vivetool)

**Additional context**
- Wallpapers work fine, it's only the taskbar effects that are not working.

**Log file (Important)**
[lively_log_20220226_134437.zip](https://github.com/rocksdanister/lively/files/8147336/lively_log_20220226_134437.zip)

**Comment by rocksdanister** [comment]
Related: https://github.com/TranslucentTB/TranslucentTB/issues/537
