### ISSUE TITLE
(Lively Beta) GUI window size & position not stored/recalled

### ISSUE THREAD

**Issue by niknak101** [rocksdanister/lively#1086]
First, thanks for all the work on this awesome tool!

Using Lively Beta v1.9.3.5, under Windows 11 Pro (21H2).

I wanted to report a minor nuisance: the **windows size** (after resizing from default) **and position are not saved** when closing & reopening the GUI.
In my case, Lively GUI opens partially outside of the monitor area, and I need to move it around & resize it manually each time.

Just my 2 cents. Thanks again & cheers.

**Comment by rocksdanister** [comment]
For v2.0 beta you can check if the issue is already listed https://github.com/rocksdanister/lively/issues/1080

` (winui) Restore position and size when relaunching the UI.`

For now as a fix turn on `Fast startup` in settings.

**Comment by niknak101** [comment]
My bad. Thanks for the info. Cheers.

**Comment by niknak101** [comment]
Thanks for the gift today 😉🎁 (seen the issue fixed on the latest beta)
