### ISSUE TITLE
Lively Beta won't open in newest Dev build

### ISSUE THREAD

**Issue by laracroftonline** [rocksdanister/lively#1088]
After installing the last beta of lively it won't open anymore.
I use [Windows 11 Insider Preview Build 22563](https://blogs.windows.com/windows-insider/2022/02/24/announcing-windows-11-insider-preview-build-22563/)
I attached my log

[20220301_001232.txt](https://github.com/rocksdanister/lively/files/8157552/20220301_001232.txt)

**Comment by rocksdanister** [comment]
Which version of Lively last worked for you?

**Comment by laracroftonline** [comment]
1.7.5.1

**Comment by rocksdanister** [comment]
Share the exported logfile: Lively settings -> Misc. -> Log File

**Comment by laracroftonline** [comment]
This is the logfile from 1.7.5.1
[lively_log_20220301_191254.zip](https://github.com/rocksdanister/lively/files/8163833/lively_log_20220301_191254.zip)

**Comment by rocksdanister** [comment]
Does it still crash if you switch system language to English?

**Comment by laracroftonline** [comment]
I upgraded to 1.9.3.6 and put the system in english language and still no interface.
[Lively Wallpaper 20220301_195207.zip](https://github.com/rocksdanister/lively/files/8164081/Lively.Wallpaper.20220301_195207.zip)

**Comment by rocksdanister** [comment]
Why are you keep getting the file not found error 🤔
It should go away after running it once.. I will take a look at the core again..

In the Windows Event Viewer under Windows logs -> Application there should be Lively UI crash logs see what that says.

**Comment by laracroftonline** [comment]
[lively application error.txt](https://github.com/rocksdanister/lively/files/8164188/lively.application.error.txt)
[lively .net error.txt](https://github.com/rocksdanister/lively/files/8164189/lively.net.error.txt)

**Comment by rocksdanister** [comment]
1. Can you try this version of Lively:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.9.2.0
2. Can you install the x86 and `Installer and MSIX Packages` from here:
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

**Comment by laracroftonline** [comment]
To get it to work on the dev build i needed to install the ddlm, main and singleton packages.

**Comment by laracroftonline** [comment]
performed the upgrade to the build that was released today and can confirm 1.9.3.6b still to be working.

**Comment by rocksdanister** [comment]
> To get it to work on the dev build i needed to install the ddlm, main and singleton packages.

The installer should install silently `WindowsAppRuntimeInstall.exe` with all the dependencies so I am not sure why it was not already installed in your system.

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps

>Installing the Windows App SDK system-wide: System-wide install alters the machine for all users, including new users that are added in the future. If the app is running elevated and the user doing the installation has admin privileges, then WindowsAppRuntimeInstall.exe will register the Windows App SDK packages system-wide by calling the [ProvisionPackageForAllUsersAsync](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.provisionpackageforallusersasync). If system-wide registration is not successful, the installation will be performed for the current user doing the installation only. In a managed Enterprise environment, the IT admin should be able to provision for everyone as usual.

>Architectures redistributed by the Windows App SDK installer: The Windows App SDK installer is available in the x86, x64 and ARM64 architectures. Each version of the installer also includes the MSIX packages for all architectures. For example, if you run the x86 WindowsAppRuntimeInstall.exe on an x64 or ARM64 device, the installer will deploy the packages for that device architecture.

I tested this working on a fresh Windows10 Virtual Machine:
![image](https://user-images.githubusercontent.com/17554161/156613231-fdab05d5-3789-4284-906c-83fd944bc4ba.png)

**Comment by laracroftonline** [comment]
it's not fully working on the dev build of windows 11. tested it on 2 clean systems. so you might want to run 11 in a vm and try it out.

**Comment by rocksdanister** [comment]
Just checked on Windows 11 21H2 clean install and it worked.

**Comment by rocksdanister** [comment]
Can you try latest beta:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.9.5.0
