### ISSUE TITLE
Incompatability with stardock fences.

### ISSUE THREAD

**Issue by MarcelCapeTown** [rocksdanister/lively#109]
Hi, 
First of all I'd like to say that your software is absolutely amazing. Yet I'm having the problem that the set lively wallpaper disappears as soon as I move the mouse cursor. I've tried the different video players, different wallpapers and the settings are all on "do nothing".
I've read through your trouble shooting guide but right now I'm lost...
Almost like I'm missing a simple tweak somewhere.
I'm running windows 10, using rainmeter and stardocks fences.
Closing rainmeter didn't help either...
Not sure if this is helpful but when trying to use the fractal clock, sometimes nothing happens and the UI seems to flash once.
Please help
Regards 
Marcel
![lively](https://user-images.githubusercontent.com/70465648/91654005-dad33680-eaa5-11ea-97f2-77d768313fed.JPG)

**Comment by rocksdanister** [comment]
I don't know if fences is making some desktop modifications or if its simply an overlay.
Try disabling fences from starting with windows, restart and see if lively is working?

**Comment by MarcelCapeTown** [comment]
It seems fences was the problem. I wasn't aware of the fact that windows 10 got a built-in option to hide the desktop icons.
Now I know and uninstalled fences as I don't need it any longer. Did a restart and lively started nicely with the fractal clock.
Thank you so much for your speedy response and spot on solution.
You have no idea what I have been through yesterday trying to get a live wallpaper working behind icons and rainmeter. I ended up doing a system restore and the works....
So now I have certainly found the best software for what I wanted. Thanks to you...
I'm going to check on deviantart if your lively is known there. If not I'd like to share my experience with your lively software...
Thanks again
Marcel from Cape Town South Africa

**Comment by MarcelCapeTown** [comment]
Okay. I've checked deviantart and lively is there but man.....
This Fluid V2 is beyond what I was trying to achieve in the first place.
Can't wait to get v1.0 on my computer.
What an excellent piece of software you have created. A must have software on any computer.

**Comment by rocksdanister** [comment]
Thank you.
