### ISSUE TITLE
Resource management

### ISSUE THREAD

**Issue by Sol4rOnGitHub** [rocksdanister/lively#1090]
When you have two screens (like I do) and you are working on one, since I don't have a powerful pc I have to be aware of resources. When I'm working on one screen, the video background on the other screen keeps working on! Problems with this:
- It's resource intensive
- Who is going to look at the other screen!?? (Which is literally only the taskbar if you are using clear like me)
BUT it would be a nice touch if the other wallpaper continues running the VIDEO on the other screen if the user can still see the background.

**To Reproduce**
1. Have 2 screens
2. Use the same/diferent anything background. 
3. Have clear taskbar
4. See that if you are working on someting on one tab, the other taskbar background will still be animated.

**Expected behavior**
I would want the wallpaper to stop rendering the video

**Desktop (please complete the following information):**
 - OS: Latest windows 11 (checked)
- An MP4 video

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

^i dont htink the log file applies here

**Comment by rocksdanister** [comment]
This is default behavior.
Setting `Display Pause Rule` to `All Screen` will pause wallpaper on all monitors:
![image](https://user-images.githubusercontent.com/17554161/156435181-9aaeca53-7636-4b8b-9163-4724db131bf4.png)

Further read on optimizing performance:
https://github.com/rocksdanister/lively/wiki/Performance
