### ISSUE TITLE
Lively crashes when I drag my video file into it (tried with mp4 and WMV)

### ISSUE THREAD

**Issue by Metacomet7** [rocksdanister/lively#1092]
**Describe the bug**

When I drag my video into the spot where it tells me to, the app crashes.

Open the app, click plus icon, and drag video into the intended spot, application crashes.

I expect it to not crash and accept the wallpaper or at least give an error message but there is nothing

Windows 10 Version 2004 OS build 19041.1415

**Additional context**
This is my first time using the app I downloaded it today.

I attached the video I want to use as a wallpaper as well as the log info

[removed]

[lively_log_20220303_125216.zip](https://github.com/rocksdanister/lively/files/8180377/lively_log_20220303_125216.zip)

**Comment by rocksdanister** [comment]
I see that you are using Education version of Windows - can you try installing the Windows Media coded pack:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by Metacomet7** [comment]
> I see that you are using Education version of Windows - can you try installing the Windows Media coded pack: https://github.com/rocksdanister/lively/wiki/Video-Guide

This worked, Thank you so much!
