### ISSUE TITLE
Different Wallpaper for Desktop & Screen Saver

### ISSUE THREAD

**Issue by tieb62** [rocksdanister/lively#1093]
**Is your feature request related to a problem? Please describe.**
Well, I love the Fluids background but in screensaver it becomes useless because if we move the mouse it exits screensaver

**Describe the solution you'd like**
We could choose which background we want for desktop and choose another for screensaver

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/587
