### ISSUE TITLE
Gives me an error if I change auto-hide taskbar via powershell

### ISSUE THREAD

**Issue by semyon0101** [rocksdanister/lively#1099]
Sorry for my English.

Command: "&{$p='HKCU:SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3';$v=(Get-ItemProperty -Path $p).Settings;$v[8]=2;&Set-ItemProperty -Path $p -Name Settings -Value $v;&Stop-Process -f -ProcessName explorer}"
May be is: "&{$p='HKCU:SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3';$v=(Get-ItemProperty -Path $p).Settings;$v[8]=3;&Set-ItemProperty -Path $p -Name Settings -Value $v;&Stop-Process -f -ProcessName explorer}"

Error is: "Lively has encountered a fatal error. Windows Explorer restarted twice in the last 30 seconds! This may be a conflict between Lively and other desktop customization software or Windows. To avoid further issues, all wallpapers are terminated"

Error in: https://user-images.githubusercontent.com/79764144/156917020-b7536969-78d1-4e61-8258-292604feb7d8.png

Debugging in: https://user-images.githubusercontent.com/79764144/156917117-c30b86e2-6884-4653-94f8-617ede019b9f.png

**Comment by kirsemen** [comment]
please help me

**Comment by rocksdanister** [comment]
Yeah I am listening for WM_TASKBAR created message and checking explorer pid:
https://github.com/rocksdanister/lively/blob/1627b6d4dd76993e7971d1f9c25abd0071f5a91b/src/Lively/Lively/Views/WindowMsg/WndProcMsgWindow.xaml.cs#L43-L67

`Stop-Process -f -ProcessName explorer}`
Find a way to auto-hide taskbar without stopping it?

tagging @sylveon

**Comment by semyon0101** [comment]
Thank you
