### ISSUE TITLE
Custom Path for CEF

### ISSUE THREAD

**Issue by gerhardamegg** [rocksdanister/lively#11]
As I am using Onedrive, every folder in `%Documents%` gets synchronized, including the wallpapers and CEF. I only have the free version of 1drive, so I would really like to use those >220MB in a better way. How can I change the path to CEF and the other stuff to something like `%APPDATA%\Local\Programs\Lively Wallpaper\external\cef`?

**Comment by rocksdanister** [comment]
I'll probably do a portable build for the latest version in the future, for now you can use the old portable builds: https://github.com/rocksdanister/lively/releases/tag/v0.6.0.0

**Comment by gerhardamegg** [comment]
Ok, I downgraded. Works like a charm.

**Comment by rocksdanister** [comment]
Latest portable release is out: https://github.com/rocksdanister/lively/releases
