### ISSUE TITLE
Wallpaper not working correctly

### ISSUE THREAD

**Issue by jefthegod** [rocksdanister/lively#1105]
**Describe the bug**
The wallpaper fills only half of the desktop on 2560x1440p

**To Reproduce**
Steps to reproduce the behavior in windows 11:
1. Go to settings
2. Click on Display
3. Set the display resolution to 2560 x 1440

**Expected behavior**
I expected it to fill the entire desktop background like on 1920 x 1080
**Screenshots/Video**
![image](https://user-images.githubusercontent.com/83766025/157036686-5e3d1578-c6ba-4b3d-9c37-db0e4a76b27d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 OS Build 22000,493
- Eternal Light was the wallpaper running

**Log file (Important)**
[lively_log_20220307_144101.zip](https://github.com/rocksdanister/lively/files/8197734/lively_log_20220307_144101.zip)

**Comment by rocksdanister** [comment]
I am trying to understand how to recreate this error, is it like this: 
`Set wallpaper on 1080p resolution -> change display resolution to 1440p -> Error`
If that is the case and your monitor is 1440p then I am also curious why set it to 1080p initially?
