### ISSUE TITLE
Release Notification - v1.0

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#111]
## Milestone Release v1.0
Lively v1.0 REQUIRES Windows 10 1903 or above.  
This update has been several months in the work and a major milestone for lively, the user interface and the code have been rewritten from the ground up.

So what's new? Everything!
### Windows 10 UI - Fluent Design
Lively v1.0 has a complete UI makeover; there are no dials and buttons - everything is much more simpler and minimal!
<img src="https://user-images.githubusercontent.com/17554161/91752670-54713e80-ebe4-11ea-9d21-4f2661124516.gif" width="600" height="338"/>
<img src="https://user-images.githubusercontent.com/17554161/91752785-7a96de80-ebe4-11ea-8386-f711025f943f.gif" width="600" height="338"/>

Several of the core features have been improved, for example lively's screen capture when importing new wallpaper now shows a live preview as you edit the wallpaper metadata
<img src="https://user-images.githubusercontent.com/17554161/91753924-2db40780-ebe6-11ea-94f5-c6521c4e356f.gif" width="600" height="338"/>

The customise wallpaper menu has two variants, one that appears in-app when you access it through rightclick contextmenu and another when you accesss it through the system-tray menu for quick change.

and there are new features like the ability to convert any wallpaper type to video type (screen record.)
### Better wallpaper playback
For video wallpapers, lively supports libvlc, libmpv. 
Both videoplayers supports online stream wallpapers by default without any user configuration.
<img src="https://user-images.githubusercontent.com/17554161/91752728-6652e180-ebe4-11ea-81d7-d936a6ceb165.gif" width="600" height="338"/>

For gif wallpapers, lively uses windows 10 image control which is lighter on the cpu side as it uses a mix of cpu and gpu resources.
Cefsharp has been updated to 84.4.10
All the players now have grey background color, so that you won't see the white color when switching wallpapers.

Both the videoplayer and the chromium engine cefsharp have been made separate projects and behave like plugins; lively starts them up and communicates through ipc for pausing, exiting etc..
This has some pros and cons, namely it becomes easier to manage and add new wallpaper players to lively independent of the main app.

The wallpaper play/pause monitor system has also been improved, now it takes into account window class names to detect Windows elements like startmenu, app switcher, taskview and even checks for rainmeter widgets.
### .Net Core 3.1 & Better code
Lively v1.0 is now .net 3.1 from .net framework 4.7, this comes with some pros and cons.

Windows does not come with .net core installed so I have to bundle it with the installer (~50mb) and some existing functions has some bugs like process variable not updating mainwindow handle on time -  so for the initial release application type wallpapers such as Unity, Godot, Programs are disabled.

On the Plus side its modern and will be easy to port to .Net 5 when it releases. 
Also the UI logic is mostly decoupled using mvvm pattern, so changing the underlying UI framework should be relatively easy now.
### Better Installation (No more portable version)
<img src="https://user-images.githubusercontent.com/17554161/91754112-82578280-ebe6-11ea-946f-d25386289022.gif" width="600" height="338"/>

One of the main issue or reason for portable build was in Windows 10 some have Onedrive sync enabled for Documents folder and lively was writing its wallpapers and save to Documents (also some av software did not like writing to documents folder.) 

In v1.0 Lively settings are written to Local Appdata and the wallpaper install location can be changed (default is Local Appdata) through the in app menu.

I don't think I will do portable version in the future as .net core is not installed in windows by default If I make a portable version I will get flooded with email asking why its not working; I can add a text next to download button but many won't read it and the Microsoft dialogue that opens up telling to install .net core opens a webpage containing .net runtime, asp .net and sdk all in one page and will be confusing for most.

### & More
- Windows screensaver and display turn off now works when video wallpapers are running.
- Video stuttering issue fixed.
- If lively is already running and you try clicking the icon the already existing instance of lively is opened from tray.
- New sharpziplib is used for lively file creation/extraction, it is now possible to move to a higher compression algorithm (currently still zip to keep backward compatability.)
- The livelyproperties window is now rendered by the main application, so the ui is more consistant with the rest of the application.
- Fixed an issue where screen parameter change causes the wallpapers to resize incorrectly in multiple screen systems; now the wallpapers are detached and added again.
- Memory improvements, the new app takes about the same memory as the old while rendering high quality preview clips in the new library page.
- Different UI modes, "light" if you want to disable some of the fancy stuff like only exiting exiting currently running wallpaper during new wallpaper import process (gif capture.) and animated tiles in library. 
- Dynamic theme, lively adapts to Windows 10 theme settings (Color and Accent) and as you switch the theme lively also changes.
- Cef browser debugging port is enabled, so that you can debug web type wallpapers.
- Stream wallpapers is integrated with libmpv and libvlc so that you don't have to configure anything.
- Added an option to hide the system-tray icon if it annoys anyone. (to exit the applicaiton you will have to re-enable to get access to traymenu... not intuitive I know.)
- New wallpaper control panel to see and manage running wallpapers on different display devices and also there is a indicator near the topright menu showing number of running wallpapers.
- The new add wallpaper page is made more minimal and simpler to navigate; there is a single browse file dialogue.

**Comment by colz3** [comment]
It says that I need .net core to run Lively. But after downloading I still couldnt use lively and its still saying the same thing. Is thre a way to solve this problem?
