### ISSUE TITLE
Whenever laptop goes to sleep (closed the lid) the app stops working.  

### ISSUE THREAD

**Issue by crookedreader** [rocksdanister/lively#1113]
Whenever laptop goes to sleep (closed the lid) the app stops working. I opened the app again and clicked the file, the the working screen on the upper side which was showing 1 suddenly changed to 0.This issue has ocurred more than 10 times. I have uninstalled and installed but the problem still prevails
[lively_log_20220309_235244.zip](https://github.com/rocksdanister/lively/files/8217162/lively_log_20220309_235244.zip)
.

**Comment by rocksdanister** [comment]
Can you try the beta version of Lively and see if the problem still exists:
https://github.com/rocksdanister/lively-beta/releases
