### ISSUE TITLE
livelyAudioListener only called if wallpaper is added as .zip

### ISSUE THREAD

**Issue by Meph1sto666** [rocksdanister/lively#1114]
If I add the HTML file of my wallpaper from a folder to the libary the livelyAudioListener is not called.
But if i add the folder as .zip it works.
At first I thought it was because I can't program, but I also tried Fluids v2 and it was the same problem.

**Expected behavior**
Working audio visualizing if I only add the .html file

 - Lively v1.7.4.2
 - OS: Windows 10
 - Wallpapers: [Wordclock](https://github.com/Meph1sto666/Wordclock) and Fluids v2

Sorry but there weren't any log files

**Comment by rocksdanister** [comment]
When you add html, video..etc files only the path of the file is stored and a new LivelyInfo.json is generated, when you install .zip the files are extracted to AppData folder and the LivelyInfo.json file inside the .zip is used instead.

Open as Website Audio (*.html) wallpaper in add wallpaper page to to generate LivelyInfo.json with audio enabled:
https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data
