### ISSUE TITLE
Cannot open from taskbar (Microsoft store)

### ISSUE THREAD

**Issue by Takiyomie** [rocksdanister/lively#1115]
Hello, I would like to report a bug that does not appear on my brother's computer...

In fact when I open Lively Wallpaper it comes in the taskbar but I can't open it no matter how I try!

So I would like to know if it's me who is doing it wrong or if it's a bug of the application :d

I hope to have your answer as soon as possible !

**Comment by roxxel** [comment]
Send log file

**Comment by roxxel** [comment]
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/1112

Patch v1.0.103.0 should be out in the store soon, check for update.
![image](https://user-images.githubusercontent.com/17554161/157697946-916f6388-9ad2-412d-aa52-2c21704727fe.png)
