### ISSUE TITLE
change wallpaper needed 

### ISSUE THREAD

**Issue by its-bash33r-here** [rocksdanister/lively#1117]
change wallpaper in taskbar icon needed 
it was so useful to put random wallpapers 
daily 
thankyou

**Comment by rocksdanister** [comment]
Lively v2.0 is a full rewrite so some old features are still under development, hope you understand.

Closing this, I added it to the list https://github.com/rocksdanister/lively/issues/1080

**Comment by rocksdanister** [comment]
Its done.. expect the update this monday 😊

**Comment by its-bash33r-here** [comment]
tq dude
