### ISSUE TITLE
Switching wallpapers only shows black wallpaper

### ISSUE THREAD

**Issue by ThatOneGal** [rocksdanister/lively#1118]
**Describe the bug**
After using the Windows Store version of Lively, I copied my Library folder to keep my wallpapers. Proceeded to uninstall this version, and installed the GitHub version instead. Moved the Library folder back to where it should be. All wallpapers are displayed as selectable options in the menu. When I select a wallpaper however, it will take a long time to load this wallpaper, but once it finishes the wallpaper displayed is a black screen. This doesn't happen every time, but there is no pattern I have been able to see. I need to restart windows for the last selected wallpaper to display but I am still unable to change wallpapers.

**To Reproduce**
1. Copy Library folder, move it to desktop
2. Uninstall Windows Store version of Lively
3. Install GitHub Version of Lively using the provided launcher
4. Delete existing Library folder
5. Move the Library folder from Desktop into Lively files where the original one was.
6. Restart Lively to refresh wallpaper library screen
7. Choose a wallpaper
8. Wallpaper comes up black.

**Expected behavior**
When switching wallpaper, after short load time the wallpaper changes to desired.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![20220312_100053](https://user-images.githubusercontent.com/69178031/157999511-f2c2ca58-de85-4a95-a8a3-749df56ebc7b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 19044
- No wallpaper running

**Log file (Important)**
Share the diagnostic files by:
[lively_log_20220312_100442.zip](https://github.com/rocksdanister/lively/files/8236828/lively_log_20220312_100442.zip)

**Comment by rocksdanister** [comment]
1. What reason made you switch from Windows store to Installer version of Lively?
2. For changing the wallpaper directory from within the app settings uncheck -
"Move existing wallpapers to new folder" then click on the directory path button:
![Screenshot 2022-03-12 090820](https://user-images.githubusercontent.com/17554161/158002281-404392bb-1158-4f72-a546-5fdc93ecc4a0.png)

The installer version is actually pretty old now, try the store version again which is more up to date.

**Comment by ThatOneGal** [comment]
I'll definitely try switching back to the Windows Store version, thank you for getting back to me so quickly!

The reason why I moved over to the installer version was because under my GPU settings, I had the entire Lively Wallpaper app to use my dedicated GPU rather than an integrated GPU. This made weird lines spread out from images and text in the Lively app itself. I looked on the Common Problems thread on this GitHub page, you recommended only changing specific processes and executables to use the dedicated GPU but I couldn't access them in the Windows Store version. So I switched to the installer to be able to access those processes.

I hope that made sense!

**Comment by ThatOneGal** [comment]
The "strange lines" I mentioned look something like this:
![image](https://user-images.githubusercontent.com/69178031/158003157-6d2542b0-cf56-430d-9af2-2b4966c52938.png)

**Comment by rocksdanister** [comment]
The lines are caused by **Nvidia Image Sharpening** being turned on. Turn it off in your Nvidia drivers or do a clean reinstallation of your Nvidia drivers by uninstalling your current one first.

**Comment by ThatOneGal** [comment]
And everything was all good. Thankyou so much!
