### ISSUE TITLE
some taskbar options not working

### ISSUE THREAD

**Issue by kvayz** [rocksdanister/lively#1119]
The taskbar options "off", "fluent" and "wallpaper fluent" all show the exact same black slightly translucent taskbar. The rest of the options work fine. What's interesting to note is that they were working just fine yesterday.

**Comment by rocksdanister** [comment]
I am guessing you are using Windows store version of Lively? I missed some features while rewriting everything to Lively 2.0 .. new update has been pushed with the fix but it is taking time for Microsoft to approve it (holiday).

Full Lively v2.0 todo https://github.com/rocksdanister/lively/issues/1080
