### ISSUE TITLE
Wallpaper applies for a second and goes back to a photo

### ISSUE THREAD

**Issue by En-To** [rocksdanister/lively#1122]
[lively_log_20220313_124227.zip](https://github.com/rocksdanister/lively/files/8239436/lively_log_20220313_124227.zip)
When I try to set a wallpaper from lively (either built-in or one i uploaded) it applies for a second and then goes back to the wallpaper I had before the lively wallpaper. So let's say I have wallpaper A which is just a photo, when i try to apply lively wallpaper B is there for a second and then returns to wallpaper A.

**Comment by rocksdanister** [comment]
System gpu seems very old:
```
CPU: AMD A10-5750M APU with Radeon(tm) HD Graphics
GPU: AMD Radeon HD 8650G
GPU: AMD Radeon HD 8600M Series
```
Try turning off Hardware acceleration in Lively (Settings -> Wallpaper -> Video player)
