### ISSUE TITLE
Can't add multiple wallpapers or edit their metadata after import after updating to Lively 2.0

### ISSUE THREAD

**Issue by St1nGxD** [rocksdanister/lively#1127]
ever since we got the 2.0 LivelyWallpaper update i haven't been able to:1: add multiple wallpapers, i can add just one, but i can't add like 20 wallpapers with one click.2: i can't edit the wallpapers, for example i want to change their titles so they're not just randomly around everywhere so when i click on the 3 dots on a certain wallpaper, and i try to edit, i can't because for some reason the edit option is grayed out, i can't select it.thats pretty much it, i hope there's some fix to this and thanks in advance!

Uploading Desktop 2022.03.16 - 07.55.49.11.DVR_Trim.mp4…

![Screenshot 2022-03-16 073812](https://user-images.githubusercontent.com/95598517/158526184-c420a36e-b271-4592-a87f-7eb479c2d95a.png)

**Comment by rocksdanister** [comment]
Lively 2.0 is a complete rewrite so unfortunately some existing features are still under development.

List of features can be tracked here https://github.com/rocksdanister/lively/issues/1080

Some important features were prioritized to get the release out and over the coming weeks remaining features will be updated. 
Hope you understand.

**Comment by rocksdanister** [comment]
Its done.. update pushed to store and installer beta🎉

https://user-images.githubusercontent.com/17554161/161590190-9aa3bc8c-0a82-448f-9a94-5a53eb02bdd5.mp4

**Comment by St1nGxD** [comment]
i just noticed you guys added this, thanks so much but its still not working for me, how do i update it or??

**Comment by rocksdanister** [comment]
Update the app from windows store, latest is Lively v2.0.0.7

If you are experiencing a bug file a new issue.
