### ISSUE TITLE
Files are not loading / Webpage wallpaper not working (MS Edge)

### ISSUE THREAD

**Issue by MrWater1** [rocksdanister/lively#1129]
If I start Lively wallpaper, its just a white screen with an error that the file wasnt found. Happened recently

Wanted to select another wallpaper but stopped working
![image](https://user-images.githubusercontent.com/76536710/159111982-580e8a83-d7ae-4c96-94c5-47395b37a759.png)

OS: Windows 10 1904
Fluid Wallpaper V2

Log:
[20220319_075729.txt](https://github.com/rocksdanister/lively/files/8308782/20220319_075729.txt)

**Comment by MrWater1** [comment]
The screenshot is german

**Comment by rocksdanister** [comment]
~I have no idea where that screenshot is from, share the full image without cropping .~  Change webbrowser from Edge to CefSharp in Settings -> Wallpaper.

Check for update in windows store, you are using a old version of Lively.

**Comment by MrWater1** [comment]
Thanks, the webbrowser change helped.
