### ISSUE TITLE
Lively Wallpaper Vs Avast : CefSharp.BrowserSubprocess.exe "infected iwth IDP.Generic"

### ISSUE THREAD

**Issue by Aethandor** [rocksdanister/lively#1130]
Having just installed the latest update as advised by Lively Wallpaper today, my AV (Avast) popped up the following warning - it has blocked CefSharp.BrowserSubprocess.exe because it is infected with IDP.Generic.

From past experience, IDP.Generic is Avast language for "we don't know exactly what it is, but it looks kinda fishy to me".

The only steps needed to reproduce this are 1) Have Avast Anti-virus installed, 2) Intsall or update to the latest version of Lively Wallpaper as of 19-3-2022.

Screenshot of the warning attached.

![Capture](https://user-images.githubusercontent.com/95346879/159117093-fb30d783-4b41-4c3b-bd7f-1450dab5acdf.JPG)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/358
