### ISSUE TITLE
Set devicePixelRatio to 1

### ISSUE THREAD

**Issue by Eason0729** [rocksdanister/lively#1131]
**Is your feature request related to a problem? Please describe.**
When I updated Lively to 2.0, and I found that my ``Window.devicePixelRatio``(in browser) was 1.25

**Describe the solution you'd like**
Set devicePixelRatio to 1

**Describe alternatives you've considered**
Allow user to set it in setting.

**Comment by rocksdanister** [comment]
Just to confirm your system scaling is set to 125%?

In certain dpi systems webpage wallpaper was having issue and this was patched by making browser program dpi aware: https://github.com/rocksdanister/lively-cef/blob/6fb5c49b23062ef5478b0329498457edf4153728/src/Lively.PlayerCefSharp/App.config#L12

Looks like CefSharp can be configured with custom dpi:
https://github.com/cefsharp/CefSharp/wiki/General-Usage#high-dpi-additional-info

**Comment by Eason0729** [comment]
Yes, My system scaling is set to 125%.
I think might be better for web developer not caring about devicePixelRatio, but sometimes there are fonts in wallpaper.
I will fix the problems of my wallpaper by adding support for devicePixelRatio.
Thank for your help.
