### ISSUE TITLE
Regarding Elevated/Admin mode not supported Lively v2.0

### ISSUE THREAD

**Issue by yofukashino** [rocksdanister/lively#1132]
**Is your feature request related to a problem? Please describe.**
well kind of, it is what it is that i know updating will break things, because i use a elevated account so everything will be elevated and lively wouldnt run so i wouldnt update but its annoying to get notification for it everytime i update my pc
**Describe the solution you'd like**
well it would be great if something like "skip this version" so that it will give notification when next version comes out.
**Describe alternatives you've considered**
just option to not check for update
**Additional context**
Add any other context or screenshots/mockups about the feature request here.
![image](https://user-images.githubusercontent.com/73281112/159128724-4628a504-a4c6-4d4c-8415-268119b48ad1.png)

**Comment by rocksdanister** [comment]
>because i use a elevated account 

You misunderstood, if you run Lively executable as "Run as administrator" then it will fail, user account can be admin and you can still run Lively without admin privilege (default behaviour.)

I removed that from update note, its worded poorly and hard to convey properly in small sentence.

**Comment by rocksdanister** [comment]
Original issue for reference: https://github.com/rocksdanister/lively/issues/1060

Its only a problem if you disable UAC driver from  Local Security Policy and force all apps to run elevated.

**Comment by yofukashino** [comment]
i want a  option to skip the version of update or stop checking for update, IDC about UAC here, its just a problem and i want that option because of it but would be handy later too.

**Comment by yofukashino** [comment]
![image](https://user-images.githubusercontent.com/73281112/159136605-e496624f-6cec-4a3e-a52b-d59bd27d7fb5.png)
and this is what i get when i run the update.

**Comment by yofukashino** [comment]
@rocksdanister so i want to pause or skip updates. thats the feature, i asked for

**Comment by rocksdanister** [comment]
I pushed an update without the elevation checking but if you are running it elevated nothing much can be done since the sdk don't support it right now.

>so i want to pause or skip updates. thats the feature, i asked for

I don't have plans to implement this feature at the moment.

**Comment by yofukashino** [comment]
anyways thx
