### ISSUE TITLE
Creating wallpaper with URL - not working like it used to

### ISSUE THREAD

**Issue by notroni** [rocksdanister/lively#1134]
**Describe the bug**
When trying to create a new wallpaper using a URL (for instance, a URL of a YouTube video) on the newer verison (2.0), the link appears too long for the link box, and the arrow next to it 'slides away' from the tab and eventually prevents from creating the wallpaper (And it did work on the older version of Lively).
* [It does appear to work for shorter URLs - the problem is relevant for the longer ones, like YouTube ones.]

**To Reproduce**
1. Go to 'Open Lively'
2. Click on the '+ Add Wallpaper' button
3. Enter a URL in the link box
4. See that it wont let you continue creating the wallpaper

**Expected behavior**
The expectation was simply to be able to press the '-->' button next to the link box, and setting up the wallpaper.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
SHORT URL: ('-->' button is visible)
![image](https://user-images.githubusercontent.com/101950162/159137862-474fce21-eede-4590-993c-42ab2deaea7f.png)

WITH LONGER URL:  ('-->' button isn't visible anymore)
![image](https://user-images.githubusercontent.com/101950162/159137835-d539e055-4818-414b-8dd2-2c5450fbbaae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909

**Additional context**
-

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20220319_224436.zip](https://github.com/rocksdanister/lively/files/8310094/lively_log_20220319_224436.zip)

**Comment by rocksdanister** [comment]
Can't believe I missed that 😅

For now you can:
Press Enter
or
drag'and'drop links directly into Window.

I just pushed an update with the patch, will take time for winstore users.
