### ISSUE TITLE
Lively Wallpaper doesn't work

### ISSUE THREAD

**Issue by Videogamesmauro** [rocksdanister/lively#1135]
**Describe the bug**
When I open Live Wallpaper an error screen open. I followed various guides, did everything they said. I have reinstalled all the necessary programs but it still doesn't work.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro 10.0.19043
 - CPU: AMD Ryzen 3 1200 Quad-Core Processor
 - GPU: NVIDIA GeForce GTX 1660 SUPER

Log : 
[20220319_214607.txt](https://github.com/rocksdanister/lively/files/8310128/20220319_214607.txt)

ScreenShot error : 
![unknown](https://user-images.githubusercontent.com/65708578/159138423-7edd204b-095b-4410-bd7a-225959d550fd.png)

**Comment by Tharki-God** [comment]
same

**Comment by Tharki-God** [comment]
but your is probaby other reason than mine

**Comment by Videogamesmauro** [comment]
btw until a few weeks ago it worked

**Comment by Tharki-God** [comment]
> btw until a few weeks ago it worked

sir its the new update, go back to last version and dont update it for some time i would suggest

**Comment by Tharki-God** [comment]
https://github.com/rocksdanister/lively/issues/1132

**Comment by Videogamesmauro** [comment]
I updated it but still doesn't work

**Comment by Videogamesmauro** [comment]
I don't updated it.

**Comment by Tharki-God** [comment]
> I don't updated it.

https://github.com/rocksdanister/lively/releases/download/v1.7.4.2/lively_setup_x86_full_v1742.exe
try this version once

**Comment by Videogamesmauro** [comment]
Thank you. Now the app work

**Comment by Tharki-God** [comment]
> Thank you. I fixed it

its not fix
