### ISSUE TITLE
Control utility | livelycu setwp path requiring ""

### ISSUE THREAD

**Issue by yofukashino** [rocksdanister/lively#1137]
**Describe the bug**
well when do `livelycu.exe setwp --file C:\Users\Administrator\AppData\Local\Lively WallpaperLibrary\SaveData\wptmp\pafccjtj.lnh`
its obvious it wouldnt work because the path is not valid because of the space, but i use `livelycu.exe setwp --file C:\Users\Administrator\AppData\Local\LIVELY~1\Library\SaveData\wptmp\pafccjtj.lnh` this still dont work, even though the path is valid. i have tried copying files to different location and it works fine there if no space in directory name. well you shall say use "" but 
the application i use (auto dark mode) pass the arguement as `"cmd" "/c" "livelycu.exe setwp --file "dir""` if i use the double quote making the command invalid so i need to use it without space but then even on being valid lively dont consider it valid
 **To Reproduce**
use livelycu with a directory having space its name and one which dont.

**Expected behavior**
should work fluently with the path without space.
**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![image](https://user-images.githubusercontent.com/73281112/159142223-7af4fd78-b838-482c-adb0-838ff73da541.png)
pretty working directory according to me
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
 - Edition	Windows 10 Pro
Version	21H2
Installed on	‎15-‎07-‎2021
OS build	19044.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0
Device name	DESKTOP-LTCIIDM
Processor	AMD Ryzen 3 3200G with Radeon Vega Graphics       3.60 GHz
Installed RAM	16.0 GB (13.9 GB usable)
Device ID	DCDC5CBD-7C24-4083-81A4-E16382A6A063
Product ID	00330-80000-00000-AA389
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

- Which wallpaper was running at the time if any.
a video
**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20220320_052157.zip](https://github.com/rocksdanister/lively/files/8310326/lively_log_20220320_052157.zip)

**Comment by rocksdanister** [comment]
Support is only provided for latest version of Lively, the code for automation is different and it will be very difficult to test and maintain multiple versions of the code.

On a related note:
https://stackoverflow.com/questions/20484428/command-line-passing-quotes-within-quotes
