### ISSUE TITLE
UI doesn't pop up after v2.0.

### ISSUE THREAD

**Issue by Altair47** [rocksdanister/lively#1139]
UI doesn't pop up after v2.0. Used to work before that. If you double click on the taskbar it won't do anything and mouse shows busy.  Tried resinstalling, restarting, installing for current user ,as well as for all users. Did clean install as well by removing every lively folder on system that might be left behind.
- OS: Windows 11 21H1 22000.556

**To Reproduce**
Install and try to run it.

**Here is video showcasing the problem**
https://user-images.githubusercontent.com/22926929/159155781-6c21e278-6fec-4c0e-ab58-81ae7a52dc24.mp4

**Log file:**
[20220319_221433.txt](https://github.com/rocksdanister/lively/files/8310910/20220319_221433.txt)

**Comment by rocksdanister** [comment]
Looks like a SDK runtime installation issue, easiest way to check is try running the Windows store version:
https://www.microsoft.com/store/apps/9NTM2QC6QWS7

**Comment by hadilodhi** [comment]
Ill add my logs see if they help. I upgraded to V2.0 which caused the GUI to not open anymore. I saw that V2.0.0.1 had also been uploaded so I updated to it but still no luck with the GUI. I tried a clean install and it still didn't help. I have not tried the windows store version yet but will do later.

OS is Windows 11 Pro 21H2 22000.556.

[20220320_181214.txt](https://github.com/rocksdanister/lively/files/8311006/20220320_181214.txt)
[20220320_181809.txt](https://github.com/rocksdanister/lively/files/8311007/20220320_181809.txt)

**Comment by Altair47** [comment]
Tried V2.0.0.1 from installer and updater, had the same problem.
Can confirm that the windows store version works fine though.

**Comment by rocksdanister** [comment]
@hadilodhi try running this in powershell and share the screenshot:
https://aka.ms/windowsappsdk/1.0/1.0.1/windowsappruntimeinstall-1.0.1-x86.exe

**Comment by turibiusrozario** [comment]
I had the same issue. However, after running the WindowsAppRuntimeInstall.exe (from above), the UI now opens. Thank you.

**Comment by rocksdanister** [comment]
@TiberiusDreadnought Did you run it as admin or just simply opened it?

**Comment by yofukashino** [comment]
well i am having the same issue and i certainly run it directly, open it simply.
well the wallpaper is working and its in tray, it started at startup but now when i try to open it from tray ui wouldnt pop up. can change wallpaper with command line though.

**Comment by turibiusrozario** [comment]
@rocksdanister I simply opened it.

**Comment by yofukashino** [comment]
i had the same issue but installing the new version from ms store works for me

**Comment by rocksdanister** [comment]
Can you guys try the latest beta release and see if it works:
https://github.com/rocksdanister/lively-beta/releases

**Comment by yofukashino** [comment]
sure,
update: it works with elevated privilages

**Comment by rocksdanister** [comment]
Looks like I need to write workaround for the filepicker if running elevated @Tharki-God 
https://github.com/microsoft/WindowsAppSDK/issues/2504

**Comment by yofukashino** [comment]
> Looks like I need to write workaround for the filepicker if running elevated @Tharki-God [microsoft/WindowsAppSDK#2504](https://github.com/microsoft/WindowsAppSDK/issues/2504)
its working fine for me.

**Comment by rocksdanister** [comment]
Does your logfile show before first opening UI?
`2022-06-07 23:27:30.0405|WARN|Lively.Services.RunnerService|Process is running elevated, winui may not work...`

**Comment by yofukashino** [comment]
![image](https://user-images.githubusercontent.com/73281112/172498104-dd63f151-fd5d-4115-b030-71ff63faaeb0.png)
when i try to open the logs i save

**Comment by rocksdanister** [comment]
Just open the file in:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs\`

The logfile zip correction is a recent bug and will be fixed in the next update.

**Comment by yofukashino** [comment]
`2022-06-07 21:10:52.6724|WARN|Lively.Services.RunnerService|Process is running elevated, winui may not work...
` found this in logs but its working fine
