### ISSUE TITLE
Lively not open

### ISSUE THREAD

**Issue by aftercares0** [rocksdanister/lively#1140]
**Describe the bug**
I was install lively from github, and everything fine, but i cant setting ( open lively, change wallpaper ) even change graphic setting.

**To Reproduce**
1. install lively
2. done, lively broken

**Screenshots/Video**
https://imgur.com/a/JqDzsnx

**Desktop (please complete the following information):**
-OS : Windows 10 1903
- 2 graphic card, intel hd 4000, nvdia gefore gt 740m
- also i use some regedit tweak to disable windows update and UAC

**Log file (Important)**
https://icedrive.net/s/Qy3TVP6F6YRDND6Bxg543C9uDD62)

**Comment by aftercares0** [comment]
also this why i not install on store 
![image](https://user-images.githubusercontent.com/94881672/159156065-fcbe4db9-1d6e-484b-b63c-df6a04b8bca6.png)

**Comment by aftercares0** [comment]
oh lively working after i enable uac

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/1060#issuecomment-1045055080
