### ISSUE TITLE
webview2 not working Lively 2.0

### ISSUE THREAD

**Issue by ecr-oha-lime** [rocksdanister/lively#1141]
**Can't use webview2 in the latest version**
I have no way to use webview2 when I use the latest version of lively[My English isn't good. :(]

**To Reproduce**
1. Go to 'settings'
2. Click on 'wallpapers'
3. Scroll down to 'web browser'
4. choose ‘WebView2’
5. return to home
6. set wallpaper
7. See error

**Expected behavior**
In the webview2 state, my web page will display Chinese in the upper left corner instead of English.(When my system is set to Chinese.)

**Screenshots/Video**
![wrong look](https://user-images.githubusercontent.com/71540187/159163508-dbfc994d-0221-48c2-89ef-13c46fb1e275.jpg)

![right look](https://user-images.githubusercontent.com/71540187/159163501-8eda08ac-8ab3-4c79-bb17-971c38f3da4a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows11 build 22563
- https://limestart.cn

**Additional context**
None

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[20220320_205147.txt](https://github.com/rocksdanister/lively/files/8311319/20220320_205147.txt)
[20220320_210610.txt](https://github.com/rocksdanister/lively/files/8311320/20220320_210610.txt)

**Comment by rocksdanister** [comment]
In Lively 2.0 WebView2 is a separate program rather than being part of core:
https://github.com/rocksdanister/lively/tree/core-separation/src/Lively/Lively.PlayerWebView2

Need to build the plugin and add it to Lively install folder; a plugin installation system feels like a much needed feature.

Please wait, I will provide a WebView2 plugin in 2~3 days time.

**Comment by rocksdanister** [comment]
I halted v2.0 installer release, you can revert back to old version if you prefer:
https://github.com/rocksdanister/lively/releases/tag/v1.7.4.2

**Comment by ecr-oha-lime** [comment]
> 
插件发布了吗

**Comment by rocksdanister** [comment]
No, there are still some bugs.

Switch to v1.7.4.2 for now:
https://github.com/rocksdanister/lively/releases/download/v1.7.4.2/lively_setup_x86_full_v1742.exe

Lively 2.0 installer release is temporarily stopped, v1.7.4.2 is the latest installer version of Lively.

**Comment by ElDavoo** [comment]
having this issue too: both with 1.9 (upgrade from 1.7) and 2.0 changing the option just does nothing

**Comment by ecr-oha-lime** [comment]
兄弟，三个月了，还没好么？(催更催更)

**Comment by rocksdanister** [comment]
Still has some bugs, released:
https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef#webview2-microsoft-edge
