### ISSUE TITLE
Screen Saver on Three Monitors not working

### ISSUE THREAD

**Issue by BarbellDwarf** [rocksdanister/lively#1145]
So whenever i have three monitors connected and i have the LivelyWallpaper set to be the screen saver, my third monitor just gets a frozen picture of the screensaver while the other two actually continue to play the animated wallpaper. Is there something that i need to do to fix this?

Awesome job on this program though.

**Comment by rocksdanister** [comment]
Next time it happens share the logfile:
Goto Lively settings (Gear icon) -> Misc. -> Log File
