### ISSUE TITLE
sound off  while i go off on right screen on my monitor and click with mouse pointer during own created Livewallpaper with sounds every time repair reset and uninstal not help before everything its ok

### ISSUE THREAD

**Issue by whiterspon** [rocksdanister/lively#1147]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Uncheck this:
![image](https://user-images.githubusercontent.com/17554161/159889292-35a403e6-c0ee-44aa-a2b3-fac1adcf1839.png)

**Comment by whiterspon** [comment]
oh man thank you :) by the way any chance for starting this awesome app
like windows on exact time? i use winstep nexus too and yes Nexus have
chance called Fast Boot  and start exactly like windows on same time
without problems

čt 24. 3. 2022 v 10:48 odesílatel Dani John ***@***.***>
napsal:
