### ISSUE TITLE
Building issue: plugins folder isn't populated with executables.

### ISSUE THREAD

**Issue by deadlocklogic** [rocksdanister/lively#1155]
Hi,

I am trying to build Lively with visual studio 2022.
I am building the entire solution (installing dependencies etc...)

I am selecting Lively as the startup project.
When launching the project I am getting a tray app, and when selecting `Open Lively` I am getting `Oops... Looks like something went wrong :(` ... the error states that it can't find `Plugins/UI/Lively.UI.WinUI.exe` which isn't in the plugins folder anyway.
Do I need to manually copy all the plugins into the `plugins` folder, is there a way to automate it other than creating an installer?

By the way the `Lively.UI.Wpf` module is missing a `using` statement, which is generating an error (but luckily with no effect because the project is modular and WinUI is the default backend).

Thanks.

**Comment by rocksdanister** [comment]
Things can definitely be done better.. 
For now what is being done is you build the plugins and copy it to Plugins folder inside (create it) Lively project.
The Lively project copies it to output during build when file(s) changes:
https://github.com/rocksdanister/lively/blob/460798fe5adbbc03c3d20b5d473b937950a58d2f/src/Lively/Lively/Lively.csproj#L22-L24

The Wpf UI project has not been touched for a while, better to just unload it.

Also just so you know the microsoft store project is structured a little bit differently.

**Comment by deadlocklogic** [comment]
Thanks!
I created a `plugins` folder and copied everything there and now everything works fine.
The modular design with IPC communication is ideal for such project. But the subprocess spawning should be maybe a little bit enhanced. Perhaps adding a helper which returns the path for each `exe` if we are running in `dev` mode or complete installation separately, so no more need for extra copy/paste (which is daunting if not automated).
I will close this for now.

**Comment by rocksdanister** [comment]
One easy way to do this would be to change the output build folder for the plugins to be `Lively/bin/../Plugins/<plugin_name>`

or 

Copy to that folder automatically after building.

**Comment by rocksdanister** [comment]
Updated docs with more details: https://github.com/rocksdanister/lively/wiki/Building
