### ISSUE TITLE
Desktop icons disappear even when closing Lively

### ISSUE THREAD

**Issue by SepiaPages** [rocksdanister/lively#1156]
**Describe the bug**
After installing Lively, it worked fine for a few minutes, but then at some point my desktop icons (program shortcuts, recycle bin, etc.) disappeared. Even when I close Lively and go back to my static desktop, they don't reappear. Even after a computer restart.

**To Reproduce**
1. Install Lively through the Microsoft Store
2. Upload [removed]
and select as wallpaper.
3. Fast startup is off, volume is 0, wallpaper scaling is set to "Fill," video player is mpv
4. Open and fullscreen some applications. After a while, minimize them and see the desktop icons have disappeared. Can't even click and drag a selection square.

**Expected behavior**
The desktop icons would still be present.

**Screenshots/Video**
<img width="960" alt="lively-desktopicons-gone" src="https://user-images.githubusercontent.com/83984041/160914309-101a50b1-73db-4e7c-b7e3-422c8490f4b9.png">
<img width="960" alt="lively-desktopicons-original-gone" src="https://user-images.githubusercontent.com/83984041/160914987-5a09dc0b-4f50-48c9-9fbe-8b03ebd1bed3.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19044
- Wallpaper: manually uploaded mp4 file

**Log file (Important)**
[lively_log_20220330_151131.zip](https://github.com/rocksdanister/lively/files/8383519/lively_log_20220330_151131.zip)

**Comment by rocksdanister** [comment]
You may have turned on keyboard input at some point: https://github.com/rocksdanister/lively/issues/946#issuecomment-999224973
Just right-click desktop -> View -> Show desktop icons.

Lively makes no permanent system change, if you exit it or uninstall it then everything will be back to as it was.

**Comment by SepiaPages** [comment]
AH... yes, that fixed it. Whoops. Thank you!
