### ISSUE TITLE
MP4 video not working in html / 选择本地项目为网页时，不加载html内video标签指定的MP4

### ISSUE THREAD

**Issue by killking686** [rocksdanister/lively#1157]
选择本地项目为网页时，不加载html内video标签指定的MP4文件
如下图所示
![image](https://user-images.githubusercontent.com/66211208/161034523-984e99ab-aaed-4436-a3c9-6ce98800c011.png)
![image](https://user-images.githubusercontent.com/66211208/161035230-d98fd29a-2e07-4516-bc4e-7361882f6c05.png)
使用chrome浏览器却可以显示
![image](https://user-images.githubusercontent.com/66211208/161035737-bbdd29ea-2818-475a-8758-58d7aa5b144c.png)

**Comment by rocksdanister** [comment]
Cefsharp do not support x264 due to licensing reasons.
Convert video to vp9 codec:
https://github.com/rocksdanister/lively/wiki/Web-Guide-VI-:-Webpage-Video-Support#converting-existing-videos-to-webm
