### ISSUE TITLE
The periodic table of elements and some other wallpapers (Parallax.js, Medusae, Ripples and The Hill) are all off-centered in my screen.

### ISSUE THREAD

**Issue by Solemn-Wolf** [rocksdanister/lively#1159]
Steps to reproduce: Select the periodic table of elements. Some of the elements on the right hand side are not visible.
Expected behaviour: The whole periodic table should be visible on the screen.
System specifications:
Intel i5 10300H
8GB RAM
Intel (R) UHD Graphics + Nividia Geforce GTX 1650 Ti
512GB SSD
Running Lively v2.0 from Microsoft store
![image](https://user-images.githubusercontent.com/63059818/161366427-4a930568-b3d9-4aff-887d-7ceb729e923a.png)
[20220323_192117.txt](https://github.com/rocksdanister/lively/files/8401822/20220323_192117.txt)
[20220324_150038.txt](https://github.com/rocksdanister/lively/files/8401823/20220324_150038.txt)
[20220402_072652.txt](https://github.com/rocksdanister/lively/files/8401824/20220402_072652.txt)
[20220402_072915.txt](https://github.com/rocksdanister/lively/files/8401825/20220402_072915.txt)
[20220402_075117.txt](https://github.com/rocksdanister/lively/files/8401826/20220402_075117.txt)

**Comment by ghost** [comment]
Go to the lively application
click on active screen(top right side)
click selected screen only
*if that doesent work
go to lively settings
go to wallpaper section
click on choose a fit 
select the fit which fixes your problem.
![image_2022-04-03_104059](https://user-images.githubusercontent.com/76844531/161412616-46c1ba9e-45d1-4784-8f82-6ec7de67541b.png)

**Comment by rocksdanister** [comment]
`Choose a fit` is only for video wallpapers; html wallpapers handle scaling by its own code.

**Comment by Solemn-Wolf** [comment]
I'm sorry, but your solutions did not work.
However, I downloaded a previous version of Lively (v1742).
I then opted for the beta channel which installed Lively v2, where the scaling fits perfectly. Thanks anyway!

**Comment by rocksdanister** [comment]
The new version the browser is dpi aware.. I guess that was the problem.

You can switch to the Windows store version of Lively 2.0 if you don't prefer unstable beta builds:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions

**Comment by Solemn-Wolf** [comment]
The problem persisted in Store. :( I uninstalled it and downloaded the beta channel via github. The beta channel fixed the problem.
