### ISSUE TITLE
Redundancy cleanup + code improvement

### ISSUE THREAD

**Issue by deadlocklogic** [rocksdanister/lively#1170]
Been using `Lively` for about a month with few problems whatsoever.

**Is your feature request related to a problem? Please describe.**
Looking through the sources I noticed too much redundancies which could be refactored into a much cleaner code.

**Describe the solution you'd like**
Consider `ILibraryModel`, `ILivelyInfoModel` and `LibraryPreviewViewModel` they contain too much similar/exact data floating around which could be refactored into a cleaner code/design.

**Comment by deadlocklogic** [comment]
`ObservableObject` functionality isn't used at all (no handler is subscribed to the event `PropertyChanged`), so getting rid of it will simplify the related models even more.

**Comment by rocksdanister** [comment]
`ILivelyInfoModel` is for the wallpaper metadata `LivelyInfo.json` file and it is load as is.
`ILibraryModel` is for the library item, filepath validation and other checks are done here... maybe Title and Desc can be removed and cleanup `ILivelyInfoModel` of string done on xaml instead.
`LibraryPreviewViewModel` is for the wallpaper import window, data needs to be backed up here because of `Edit` feature.

`ObservableObject` its used everywhere for xaml databinding: `OnPropertyChanged()` .. one thing that needs to be done is replace it with `Microsoft.Toolkit.Mvvm` version since that is what is being used for `RelayCommand` in WinUI project.

**Comment by deadlocklogic** [comment]
~~But in `ObservableObject` nothing is subscribed to `PropertyChanged` (I made sure to search for any subscribers using `Find All references` and even with find in files), so `OnPropertyChanged()` is doing nothing because `PropertyChanged` is always null.
Or am I missing something there?~~
(I think I am missing something for sure)
**Edit:**
I was searching in `*.cs` files, excluding `*.xaml` which implement this functionality.

For the other models, I thought some kind of cleanup must be possible, especially in `LibraryPreviewViewModel`.
Is there any problems in introducing  `ValidatedFilePath etc...` getters instead of creating a whole new model? Even a virtual validating method defaulting to the original value?
Dunno maybe it is a matter of taste, but IMO the more compact things are the cleaner they become.

**Comment by deadlocklogic** [comment]
Now I see what is going on, the fact that `Lively` module still contains views was confusing. I thought the Winforms/WPF modules where responsible for UI solely, which should separate the data between modules clearly. Which isn't the case because the main module still needs to manage the preview interface.
Anyway, I think this is a design choice and it doesn't matter, but I was looking for refactoring into much simpler design.
Thanks.

**Comment by rocksdanister** [comment]
>But in ObservableObject nothing is subscribed to PropertyChanged (I made sure to search for any subscribers using Find All references and even with find in files), so OnPropertyChanged() is doing nothing because PropertyChanged is always null.
Or am I missing something there?

I don't know if xaml bindings show in debugger or maybe you were debugging core but WinUI was using different dll.

All these xaml bindings are using PropertyChanged:
https://github.com/rocksdanister/lively/blob/94b94313133db53db7c6f2a1498b778833d3b02f/src/Lively/Lively/Views/LibraryPreview.xaml#L58

>Now I see what is going on, the fact that Lively module still contains views was confusing. I thought the Winforms/WPF modules where responsible for UI solely, which should separate the data between modules clearly. Which isn't the case because the main module still needs to manage the preview interface.

Yes, the import and preview is also handled by core https://github.com/rocksdanister/lively/issues/1148
This is a design decision the way Lively creates preview gif for library is screen capturing the small region during import.. and wallpaper players are separate programs so they are injected into the wpf core window and this is not possible with WinUI: https://github.com/microsoft/microsoft-ui-xaml/issues/4501

Even in the future if it did become possible with WinUI this code is a lot of trial and error and each framework will require its own implementation so its better to just have the wpf core deal with it and theme the core to match the new UI framework.

So its UI program requests new wallpaper import -> Core launches import window infront of UI program -> Wallpaper .exe resized, titlebar etc removed and embedded in import window -> Screen record the embedded region to create animated gif -> Core talks to UI program and coordinate things (dim background, update and capture thumbnail every 3s etc..) using ipc.

Its a bit overengineered but makes sense in my head and the end user experience is still straightforward and simple :D

**Comment by deadlocklogic** [comment]
Ah I see, didn't even noticed that the previews are embedding `exe` into the view, lol. My first impression is that it must be a simple preview implementation but the fact displaying a foreign `exe` is even more complex.

**Comment by rocksdanister** [comment]
Yeah.. I made it look simple to the end user - the code is all hacks XD

Its one piece of code that works with everything even third party programs:

https://user-images.githubusercontent.com/17554161/162573901-6e122882-500d-4743-ac5e-53fd5d2d30ea.mp4

**Comment by deadlocklogic** [comment]
Yeah, `WpfUtil.SetProgramToFramework` is the magic I didn't knew about.
