### ISSUE TITLE
BSOD KERNELBASE.dll

### ISSUE THREAD

**Issue by Frndrmn** [rocksdanister/lively#1174]
**Describe the bug**
About 2 minutes before the BSoD lively will stop responding. Evidence:
`The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly.`
Timestamp: `2022-04-11 7:30:56 PM`
Additional evidence:
`Faulting application name: Lively.exe, version: 2.0.0.2, time stamp: 0x619549d5
Faulting module name: KERNELBASE.dll, version: 10.0.22000.593, time stamp: 0xa3444f9c
Exception code: 0xe0434352
Fault offset: 0x0013ecb2
Faulting process id: 0x14c0
Faulting application start time: 0x01d84dfc259e6214
Faulting application path: C:\Program Files\WindowsApps\12030rocksdanister.LivelyWallpaper_1.0.111.0_x86__97hta09mmv6hy\Build\Lively.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 71cc1d94-c5b4-45d0-8c73-6224c614dd5d
Faulting package full name: 12030rocksdanister.LivelyWallpaper_1.0.111.0_x86__97hta09mmv6hy
Faulting package-relative application ID: App`
Timestamp: `2022-04-11 7:28:47 PM`

**To Reproduce**
Unknown.

**Expected behavior**
Not have a BSoD.

**Screenshots/Video**
None

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2 (OS Build 22000.593)
- Matrix HTML.

**Additional context**
The two minute difference between the BSoD and the lively crash seem strange, or long but I assure you, this happens every time the system crashes.
This is the windows store version as well.

**Log file (Important)**
Gone since I uninstalled lively.

**Comment by rocksdanister** [comment]
Lively is simply running a browser/video player and not making any permanent system modification.

Crashes like this usually indicate either faulty hardware/driver or corrupted operating system files because the browser/video player uses hardware acceleration (gpu) for performance.

Things to try:
1. Reinstall drivers.
2. Run System File Checker (SFC) tool.
3. Stability test.

Not much else I can do here, closing this as it is unrelated.

**Comment by Frndrmn** [comment]
> Lively is simply running a browser/video player and not making any permanent system modification.
> 
> Crashes like this usually indicate either faulty hardware/driver or corrupted operating system files because the browser/video player uses hardware acceleration (gpu) for performance.
> 
> Things to try:
> 
>     1. Reinstall drivers.
> 
>     2. Run System File Checker (SFC) tool.
> 
>     3. Stability test.
> 
> 
> Not much else I can do here, closing this as it is unrelated.

I would like to reply to your comment, with a question. If lively isn't the issue, than how come I have not experienced a BSoD since I uninstalled it. When prior to uninstalling it would crash almost every few minutes?

**Comment by rocksdanister** [comment]
I have already explained:
>Crashes like this usually indicate either faulty hardware/driver or corrupted operating system files because the browser/video player uses hardware acceleration (gpu) for performance.

Correlation does not imply causation.
