### ISSUE TITLE
taskbar theme are not changing in windows 11 new update 'Windows 11 Insider Preview 22598.1 (ni_release)'

### ISSUE THREAD

**Issue by bhavdip1** [rocksdanister/lively#1175]
I am reporting this bug to inform you that after windows 11 new update ' Windows 11 Insider Preview 22598.1 (ni_release) '
taskbar themes are not changing. this update is released in last month.
so we are facing this problem.
please do something about this.

and let me know after done.

and this is not as similar to 'windows 11 dev update'

**Comment by rocksdanister** [comment]
Duplicate issue: https://github.com/rocksdanister/lively/issues/1084
