### ISSUE TITLE
http forced to https

### ISSUE THREAD

**Issue by HowardPautz** [rocksdanister/lively#1176]
Actually, this is both a bug report and a feature request.

Ala the old Windows "active desktop," for those who would like to use their machine-local or internal-network **IIS** for retrieving anything web, without having to purchase and add an SSL certificate to your own _internal_ site - if you can't trust yourself or your own admin, then ... 

"Setting up a server" for internal use is easy in Windows Pro - just turn on the IIS feature and find the website root.  Maybe post some CAUTIONS about potential security and let the users decide if they want to blow themselves up. This would permit the desktop to become a real GUI interface all on its own - say for a control system, a list of references via dropdowns, etc. etc. [I did see at least on other user here from China asking about something similar.]

**BUG** / trivial oversight with those big consequences:

However, use of http://localhost is overridden in the **_linkhandler.cs_** file. [Obviously the result is page view blockage.]

Note the comment implies either https **OR** http is ok, but the code does not actually differentiate, just sets it to https ...
``` CS
Line 46:
   catch (UriFormatException)
            {
                **//if user did not input https/http assume https connection.**
                uri = new UriBuilder(address)
                {
                    Scheme = "https",     // <-----------------
                    Port = -1,
                }.Uri;
            }
            return uri;
```

thanks for all your efforts! -H

**Comment by dabjulmaros** [comment]
>This would permit the desktop to become a real GUI interface all on its own - say for a control system, a list of references via dropdowns, etc. etc.

You are already able to do this. It takes some setting up between a local rest server (or your prefered method), that is called from the web wallpaper.
It may not be perfect, but is more flexible and anyone can do it.

**Comment by HowardPautz** [comment]
Thanks for the prompt reply. Does that get around the https problem? I assume the rest call would also fire 
``` CS
 catch (UriFormatException) 
```

**Comment by rocksdanister** [comment]
>Thanks for the prompt reply. Does that get around the https problem? I assume the rest call would also fire

That's for cleaning up url input from the user:
https://github.com/rocksdanister/lively/blob/9e11be133f8f6ec1009d6c9b5c9641979b9ba058/src/Lively/Lively.Common/Helpers/LinkHandler.cs#L34-L56

It should not fire for localhost provided http/https is included.. its not expected, at the time this was the quickest way to verify url but may need to look into it again.

https://docs.microsoft.com/en-us/dotnet/api/system.uriformatexception?view=net-6.0
>The [UriFormatException](https://docs.microsoft.com/en-us/dotnet/api/system.uriformatexception?view=net-6.0) is thrown by the Uri class constructor if the supplied URI could not be correctly parsed. The format for a valid URI is defined in RFC 2396.

**Comment by dabjulmaros** [comment]
well no if your web wallpaper is using https doing a http request will be blocked at least on chrome tho.
Personally I havent tested that on lively so I cant give you concrete answer, but I assueme it would also fail.
Also have you tried setting the webwallpaper selecting the index file?
I did some quick testing and I have verified that lively does not support ports.
So something like http://localhost:5000 will be converted to http://localhost if you try to add the wallpaper as a web address.

**Comment by rocksdanister** [comment]
>I did some quick testing and I have verified that lively does not support ports.

~If you make a Lively .zip file it will work since the verification is only done during user input 🙃~

**Comment by rocksdanister** [comment]
Its not throwing `UriFormatException` exception:
https://dotnetfiddle.net/QboiQ6

http and port should work, its getting changed somewhere else.. will take a look.

**Comment by HowardPautz** [comment]
Here's what I did:
1.fresh install
2.create new wallpaper by putting this into web address:
http://localhost
3. Got denial page for a wallpaper (kinda funny on some level :)
4. hacked the lively~.json file, changing https to http for contact and filename (no idea which one did the trick - just hackin':
{
  "AppVersion": "1.7.4.2",
  "Title": "localhost",
  "Thumbnail": "C:\\Users\\Howard\\AppData\\Local\\Lively Wallpaper\\Library\\SaveData\\wptmp\\1l4d1p41.fun\\fe4d2urt.jpg",
  "Preview": "C:\\Users\\Howard\\AppData\\Local\\Lively Wallpaper\\Library\\SaveData\\wptmp\\1l4d1p41.fun\\n5sbrf10.gif",
  "Desc": null,
  "Author": null,
  "License": null,
  "Contact": "http://localhost",
  "Type": 3,
  "FileName": "http://localhost",
  "Arguments": null,
  "IsAbsolutePath": true
}
5. restarted lively
6. got my local IIS homepage 

If this is a bug that really is a feature, please don't fix it :))

**Comment by rocksdanister** [comment]
@HowardPautz but as you can see in this example its not changing http to https:
https://dotnetfiddle.net/MsTOYB

In the error message its also showing http top-right right?
