### ISSUE TITLE
Typingmistake (german) "Desktop" is wrong typed

### ISSUE THREAD

**Issue by rtdietrich** [rocksdanister/lively#1179]
![Typingmistake](https://user-images.githubusercontent.com/13079745/163541850-63e931e7-72f1-4c1c-8a36-94b385935583.png)

**Comment by rocksdanister** [comment]
Thank you, did get a pr for it https://github.com/rocksdanister/lively-translations/pull/146
Translation is on hold because currently in the process of migrating to new service.
