### ISSUE TITLE
Screensaver showing while watching video

### ISSUE THREAD

**Issue by menonkrishna57** [rocksdanister/lively#1180]
**Is your feature request related to a problem? Please describe.**
Its annoying when you are watching a video and screensaver pops up

**Describe the solution you'd like**
Can you make it so that it doesnt trigger screensaver while playing a video

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by rocksdanister** [comment]
If you used the Lively menu to enable screensaver then turn it off and set it via .scr file instead:
https://github.com/rocksdanister/lively/wiki/Screen-Saver

Duplicate: https://github.com/rocksdanister/lively/issues/732
