### ISSUE TITLE
Screen saver misaligned in multiple monitor

### ISSUE THREAD

**Issue by frank-pian** [rocksdanister/lively#1183]
**Describe the bug**
Screen saver dosen't work on win11.

**To Reproduce**
1. Download scr file in 'windows/system32/' 
https://github.com/rocksdanister/lively-beta/releases/download/v1.9.5.0/lively_screen_saver.zip

2. Setting screen saver

**Screenshots/Video**
![screenshot-20220418-101923](https://user-images.githubusercontent.com/8214804/163744280-5c295b3b-9e3e-4820-be2c-14e60415dfac.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 21H2]
- Which wallpaper was running at the time if any.

**Comment by rocksdanister** [comment]
Can you test the .scr file? does this work:

https://user-images.githubusercontent.com/17554161/163751392-17c1e8e3-826f-4405-9f62-07b19b43a76b.mp4

**Comment by frank-pian** [comment]
> Can you test the .scr file? does this work:
> ezgif.com-gif-maker.1.mp4

Running it directly is ok. Dual-screen displays can be a bit of a problem
![微信图片_20220418133229](https://user-images.githubusercontent.com/8214804/163759787-acc0d9b0-3169-48ec-bb0e-aa984f6d76cf.jpg)
.

**Comment by rocksdanister** [comment]
1. Share the logfile after screensaver:
![image](https://user-images.githubusercontent.com/17554161/163760609-2de82e2a-8628-48a0-b33a-68631f174a89.png)

2. What is your display configuration?
Example: Monitor1 (left) : 1920x1080, 100% scaling

3. Share a screenshot of display settings

![image](https://user-images.githubusercontent.com/17554161/163761120-68ebbc16-78f8-4cd3-8770-79fa6b7147c6.png)

**Comment by frank-pian** [comment]
[lively_log_20220418_150208.zip](https://github.com/rocksdanister/lively/files/8504161/lively_log_20220418_150208.zip)

![screenshot-20220418-150408](https://user-images.githubusercontent.com/8214804/163769896-c46c7424-0c70-4b8a-9207-114d4e37ab6f.png)

![screenshot-20220418-150428](https://user-images.githubusercontent.com/8214804/163769907-0c73cf11-ae9b-43b4-b5ad-61bb1615d01b.png)

left screen 1920*1080 125% scaling
right screen 1920*1080 100% scaling

**Comment by rocksdanister** [comment]
Thank you, will take a look.
Possibly related https://github.com/rocksdanister/lively/issues/357
