### ISSUE TITLE
White screen when the app started

### ISSUE THREAD

**Issue by Koncek123** [rocksdanister/lively#1184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
[lively_log_20220418_202728.zip](https://github.com/rocksdanister/lively/files/8505953/lively_log_20220418_202728.zip)
![Screenshot 2022-04-18 202832](https://user-images.githubusercontent.com/103942622/163816199-88d3eb72-b5db-4866-9386-00259f70997a.jpg)

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Update the application from windows store.

**Comment by Koncek123** [comment]
Ok. Thanks for solution...
