### ISSUE TITLE
The wallpaper appears in the foreground in full screen after idle 

### ISSUE THREAD

**Issue by Krowne** [rocksdanister/lively#1190]
**Describe the bug**
I have a video as a custom wallpaper, and I have the option to pause it when I have a program in full screen, but when I'm watching youtube in full screen, and some time passes (several minutes), the video of the custom wallpaper, appears in the foreground, so it does not let me see the content of the YouTube player (This happens even if Lively Wallpaper was previously paused).

**To Reproduce**
1. Go to: Chrome > YouTube > Video
2. Click on: Fullscreen video

**Expected behavior**
The custom wallpaper video should not appear in the foreground, while I am watching a video on YouTube.

**Desktop (please complete the following information):**
 - OS: Windows 11 - 21H1 - version 10.0.22000.613
- A custom wallpaper by adding a video, but it has also happened to me with the default ones.

**Additional context**
Right now I don't remember if it also happens without putting the YouTube videos in full screen. I think it also activates the wallpaper in the foreground, when I'm watching a long video on YouTube even if it's not full screen, the pc is idle and only with the YouTube video.

**Log file (Important)**
[lively_log_20220422_114333.zip](https://github.com/rocksdanister/lively/files/8539647/lively_log_20220422_114333.zip)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/1180

Its the screensaver 😅

**Comment by Krowne** [comment]
> Duplicate: #1180
> 
> Its the screensaver 😅

No, I don't have the screensaver active.

**Comment by rocksdanister** [comment]
> No, I don't have the screensaver active.

I disagree based on the logfile shared there are several instances of:
```
2022-04-21 22:30:14.6542|INFO|livelywpf.Services.ScreensaverService|Starting screensaver..
2022-04-21 22:30:20.7670|INFO|livelywpf.Services.ScreensaverService|Stopping screensaver..
```

This is the in-app menu under `Lively Settings -> System -> Screensaver` and not the .scr file.

**Comment by Krowne** [comment]
> > No, I don't have the screensaver active.
> 
> I disagree based on the logfile shared there are several instances of:
> 
> ```
> 2022-04-21 22:30:14.6542|INFO|livelywpf.Services.ScreensaverService|Starting screensaver..
> 2022-04-21 22:30:20.7670|INFO|livelywpf.Services.ScreensaverService|Stopping screensaver..
> ```
> 
> This is the in-app menu under `Lively Settings -> System -> Screensaver` and not the .scr file.

The Windows screensaver is disabled, and the Lively screensaver was without any time, the empty tab appeared, now I have selected it off, tonight I will check if that was the problem, thank you very much for your quick responses.

It's an amazing program, keep it up :)
