### ISSUE TITLE
Program wallpaper on MSIX package not allowed when importing an Application

### ISSUE THREAD

**Issue by RafaelDee** [rocksdanister/lively#1195]
Lively not accepting any .exe file and will throw an error

Lively.Common.Errors+WallpaperPluginNotFoundException: Program wallpaper on MSIX package not allowed
the installer version will just work fine, but mouse input is not working on Application

**To Reproduce**
1. Install the windows store version of the app
2. drag and drop or add any .exe file

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/69748293/165070283-fe0b7305-fdaa-4651-ac62-474e4ceb1df2.png)

**Desktop**
 - OS Version	10.0.19044 Build 19044

- Which wallpaper was running at the time if any.
Custom Unity Game (followed all requirements like fullscreen, run in background)
tried any exe

**Log file**
[lively_log_20220425_182240.zip](https://github.com/rocksdanister/lively/files/8553692/lively_log_20220425_182240.zip)

**Comment by rocksdanister** [comment]
Currently application wallpapers are disabled in store version:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions
