### ISSUE TITLE
Unable to play/start any wallpaper other than the default ones

### ISSUE THREAD

**Issue by TannujhGhosh** [rocksdanister/lively#1197]
**Describe the bug**
None of the added wallpaper are usable after the recent updates

**To Reproduce**
1. Go to 'Lively Wallpaper app'
2. Click on 'Add wallpaper'
3.  Click on ' Browse' or Drag the file needed
4. Click on ' Set as wallpaper'
5. Error shown in the ss appears

**Expected behavior**
I wanted my wallpaper that I added to be displayed on the desktop.

**Screenshots/Video**
![Screenshot (579)](https://user-images.githubusercontent.com/104486135/165455100-3a52d3ac-71b4-4103-986b-bd3710f56d40.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19043

**Additional context**
I have been using the said app for the past 1 year or so and was able to add most of the wallpapers to my desktop.
Past few days none of the wallpapers that I add is not getting added to the desktop. Even pics such as screenshots, videos, gifs from giphy more one.

**Log file (Important)**
Share the diagnostic files by:
[lively_log_20220427_115500.zip](https://github.com/rocksdanister/lively/files/8569364/lively_log_20220427_115500.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/358

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/439
