### ISSUE TITLE
CefSharp won't store any data for website wallpapers

### ISSUE THREAD

**Issue by qinlili23333** [rocksdanister/lively#1199]
**Describe the bug**
CefSharp won't store any data for website wallpapers, including cookies, service worker, local storage and etc.

**To Reproduce**
1. Add a website which use local storage or service worker as wallpaper
2. Exit and relaunch Lively
3. The website appears to be the same as a new visitor, no login data, no service worker installed detected.

**Expected behavior**
Site's data should be stored like any regular browsers.

**Screenshots/Video**

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider 22598.200
- Wallpaper site: I used my own site ( https://545.qinlili.bid/ ) to found this problem, any other site needs store info like twitter or github can also used.

**Additional context**

**Log file (Important)**
[lively_log_20220430_142827.zip](https://github.com/rocksdanister/lively/files/8596262/lively_log_20220430_142827.zip)

**Comment by rocksdanister** [comment]
For websites:
![image](https://user-images.githubusercontent.com/17554161/166094638-0bec24ce-d2e9-4f8e-89f6-d240db8b00ca.png)

For local html file:
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction

**Comment by qinlili23333** [comment]
> For websites: ![image](https://user-images.githubusercontent.com/17554161/166094638-0bec24ce-d2e9-4f8e-89f6-d240db8b00ca.png)
> 
> For local html file: https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction

Nice it works! thanks bro
