### ISSUE TITLE
Duplicate Screen wallpaper layout.

### ISSUE THREAD

**Issue by LuciusMercier** [rocksdanister/lively#120]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**
Duplicate screens not working, cannot be selected.

**To Reproduce**
Click the screens in the lively menu and duplicate screens grayed out

**Expected behavior**
I expected to be able to select duplicate screens

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![image](https://user-images.githubusercontent.com/47582344/91979372-aa80d780-ecf3-11ea-8a98-b07ee622ab52.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file**
First launch lively again - this will create the necessary error information files for you to share, you will be prompted with a message asking weather to restore previously running wallpaper, best to choose No if you are unsure what caused the crash.

For every crash, the error information log file will be found under folder:

`Documents/Lively Wallpaper/ErrorLogs` or inside lively `ErrorLogs` folder if portable build.

**Comment by rocksdanister** [comment]
Duplicate is work in progress, it is not implemented yet.
