### ISSUE TITLE
discrete and integrated gpu usage

### ISSUE THREAD

**Issue by bodthesoap** [rocksdanister/lively#1200]
im using a laptop with an discrete and integrated graphics , and noticed that lively is using mainly the discrete gpu , which will drain faster the battery , even though there's an option to pause the wallpaper on battery life.

would it be possible to make an option to use/prioritize one one gpu over the other as a main one for lively?

basically a button to make lively use one gpu mainly ,(for example in my case , the integrated graphics only).

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/24

**Comment by rocksdanister** [comment]
You can change it in Windows settings:
https://github.com/rocksdanister/lively/wiki/Common-Problems#laptopssystems-with-multiple-gpu

But depending how the laptop hardware is (MUXED or not) the dgpu output maybe wired through the igpu and in that case its probably better to keep things the way it is.
