### ISSUE TITLE
.Net Core install prompt

### ISSUE THREAD

**Issue by MADNESS-iTTi** [rocksdanister/lively#1203]
I am using Windows 11, when I run the Lively Wallpaper , an icon appears asking me to install another program, and the Lively Wallpaper 
![lively](https://user-images.githubusercontent.com/104666809/166177494-2650eb31-5177-4406-84c5-736ff4405088.jpg)
does not work

**Comment by rocksdanister** [comment]
From where did you download Lively?

Install .Net Core x86 Desktop Runtime:
https://github.com/rocksdanister/lively/wiki/Common-Problems#net-core-required-message

**Comment by MADNESS-iTTi** [comment]
from this site : https://rocksdanister.github.io/lively/

But now I will download it from the Microsoft Store

**Comment by MADNESS-iTTi** [comment]
Thank you, the program is now working after I downloaded from Microsoft Store 👍
