### ISSUE TITLE
Screensaver settings not working

### ISSUE THREAD

**Issue by smoothnobody** [rocksdanister/lively#1206]
when trying the Microsoft store v2.0 version, right click and install, when microsoft screensaver window opens i click settings, but nothing happens, so i am unable to configure anything.

when trying the Lively installer v1.7.4.2 version, right click and install, when microsoft screensaver window opens i click settings, a window pops up and says to run this application i must install .NET core. i installed it, when i hit settings again the same window pops up telling me to install .NET core.

**Comment by rocksdanister** [comment]
>when trying the Microsoft store v2.0 version, right click and install, when microsoft screensaver window opens i click settings, but nothing happens, so i am unable to configure anything.

At the moment currently running wallpaper is run as screensaver when idle so just select the wallpaper in Lively as usual; the setting won't do anything.
