### ISSUE TITLE
[Suggestion] Add profiles feature

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [rocksdanister/lively#1207]
**Is your feature request related to a problem? Please describe.**
I listen to music pretty regularly, and I also code. since I have dual screen, it is annoying to switch the wallpaper again and again.

**Describe the solution you'd like**
Profiles. Add custom profiles, and some pre-made ones like one pre-made profile could be called "Gaming" and other could be called "Coding" etc...

**Comment by rocksdanister** [comment]
1. What is a profile?
Is it a wallpaper or is it a collection of wallpapers that cycle one after the other.
An example would help.
2. How do you switch profile? 
Manually by the user `System-traymenu -> Profiles -> Gaming ?` or Automatically when detecting some system events like `some_application.exe` opened.

**Comment by Ujjwal-Rohilla** [comment]
1. Profile, kind of like if you have multiple screens, or even the Collection of wallpaper that cycle one after other (Duration can be defined, like 30 minutes, or even an option for user custom time)

2. Switch Profile you could have an Hotkey that works only if the desktop is focused (configurable) and/or a Button in the application in the top. Going to the System Tray, Right clicking and then selecting profile will be cool too
[See Image] P.S. I am not good in editing :/
![image](https://user-images.githubusercontent.com/74773615/166679876-09b411ec-bc56-4145-96d0-c44856534a02.png)
Double Clicking the profile button will allow person to edit the name, or perhaps right clicking would do that, as well as adding option to delete it

Clicking the +Profile button will allow user to create new profile.

As there is more profiles, less space will be there, so you could either make like a scroll bar, or a drop down menu, or perhaps Just add the ... thing at the end while reducing the name, kind of like this "Gaming" --> "Gam..."

And yes, the system event option is also good

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/137
