### ISSUE TITLE
"The program does not support the version of Windows your computer is running"

### ISSUE THREAD

**Issue by ItzRevandra** [rocksdanister/lively#121]
please help idk what to do
im 64 bit
![unknown](https://user-images.githubusercontent.com/70645676/91989214-7391dc80-ed5a-11ea-8a85-f8a742e9a0d9.png)

**Comment by rocksdanister** [comment]
Need windows 10 [1903](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1903_(May_2019_Update)) or above.
