### ISSUE TITLE
.NET core install prompt while .NET Desktop Runtime has been installed when Program files location changed

### ISSUE THREAD

**Issue by Lehmaning** [rocksdanister/lively#1212]
**Describe the bug**
I modified the registry key ```ProgramFilesDir(x86)``` under ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion``` changing the value ```C:\Program Files (x86)``` to  ```D:\Program Files (x86)```, and placed the folder ```dotnet``` in both directory for compatibility. But the livelywpf.exe still couldn't start until I modify the registry key back.

**To Reproduce**
1. Change the registry key
2. Install dotnet desktop runtime x86
3. Start livelywpf.exe
4. The prompt pops up

**Expected behavior**
The livelywpf.exe finds the dotnet runtime in the D:\Program Files (x86) and normally starts.

**Desktop**
 - OS: Windows 21H2

**Additional context**
The version of lively: 1.7.5.2

**Comment by rocksdanister** [comment]
Switch to Windows store version, the runtime is embedded:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions

The .NET core install prompt is not made by me as it is part of runtime; once Lively 2.0 installer releases the runtime will be embedded similar to Windows store version so separate runtime installation will not be required on system.
