### ISSUE TITLE
Random wallpapers at every startup

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#1213]
**Is your feature request related to a problem? Please describe.**
I like all the wallpapers included in this app, but I want them to be random at every startup

**Describe the solution you'd like**
Once I login to my profile, the app will start with a random wallpaper.

**Describe alternatives you've considered**
I tried to create a batch file for this, but then I realized it was too much work

**Additional context**
`[nothing]`

**Comment by digaopk** [comment]
randomizar os papeis de aprede quando tem mais de um monitor também ficaria legal

**Comment by tellmewhy12** [comment]
https://github.com/rocksdanister/lively/issues/137

**Comment by willysfueguino** [comment]
Any way of randomizing wallpapers given X minutes? Maybe a script or something?

**Comment by rocksdanister** [comment]
you can write commandline scripts:
https://www.youtube.com/watch?v=iEb5DVMz3Ds

**Comment by willysfueguino** [comment]
Great thanks
