### ISSUE TITLE
Wallpapers are not added

### ISSUE THREAD

**Issue by xXDeathAbyssXx** [rocksdanister/lively#1215]
**Describe the bug**
`I have tried to place wallpapers in all ways and nothing happens, and when I drag the wallpapers I get an error alert, I downloaded the app from the Microsoft Store and already tried to delete the app and reinstall and still the same error.`

**To Reproduce**
`1. I drag a png/mp4 file to lively`
`2. Then I drop it`

**Expected behavior**
`I need to add wallpapers of png and mp4 format`

**Screenshots/Video**
![Lively UI WinUI_oFdy2o9cCc](https://user-images.githubusercontent.com/97713025/167473067-63c8f805-d24f-41f6-866b-634f37b19150.png)

**Desktop (please complete the following information):**
 - OS: `Windows 10 Pro`
- Which wallpaper was running at the time if any: `none`

**Additional context**
`I don't know if it has anything to do with it, but before placing my first wallper, I tried to drag many wallpers at the same time and when I placed them an error occurred that was immediately removed and then I'm trying 1 by 1 and all this happens.`

**Log file (Important)**
Share the diagnostic files by:
`My Log ZIP is empty`

**Comment by rocksdanister** [comment]
Share the file:
Settings -> System -> Log File

**Comment by xXDeathAbyssXx** [comment]
> Share the file: Settings -> System -> Log File

Is empty the zip, i can't share it cuz it say i can't share empy files

**Comment by rocksdanister** [comment]
First by rightclicking Lively icon in startmenu more -> Settings and 'Reset' the app.

Then in-app Settings -> System -> Debug and try setting a wallpaper and share screenshot like this:
![image](https://user-images.githubusercontent.com/17554161/167502840-a5de6038-e1a1-494d-99dd-8c0d93351ad1.png)

**Comment by xXDeathAbyssXx** [comment]
> First by rightclicking Lively icon in startmenu more -> Settings and 'Reset' the app.
> 
> Then in-app Settings -> System -> Debug and try setting a wallpaper and share screenshot like this: ![image](https://user-images.githubusercontent.com/17554161/167502840-a5de6038-e1a1-494d-99dd-8c0d93351ad1.png)
![Lively_5ID7R2yQhO](https://user-images.githubusercontent.com/97713025/167510773-e3d0a240-f8a2-45e4-a297-e4a659235775.png)

**Comment by rocksdanister** [comment]
Looks like there is some issue creating the directory, can you show the full-path in the error message without the red marking?

You could try the installer version to see if this is a desktop-bridge related issue:
https://github.com/rocksdanister/lively/releases

**Comment by xXDeathAbyssXx** [comment]
> Looks like there is some issue creating the directory, can you show the full-path in the error message without the red marking?
> 
> You could try the installer version to see if this is a desktop-bridge related issue: https://github.com/rocksdanister/lively/releases

The red marking is my user of windows, like `C:\Users\<myuser>\AppData`

and i need to install a old version?

**Comment by rocksdanister** [comment]
>The red marking is my user of windows, like C:\Users\<myuser>\AppData

Does your username contain some unusual characters?

>and i need to install a old version?

Yes

**Comment by xXDeathAbyssXx** [comment]
> Does your username contain some unusual characters?

Uh rly rly my username in microsoft have numbers but no unusual characters, but in the path my user is in the middle of my microsoft name for example

this is my microsoft name: `someuser123`

and this one in my path: `someuser`

and the truth is very rare, for example I can not install discord, the support tried to help me and all the solutions did not work for me and I reset my pc and still the same without being able to download discord, lively also had problems but it was fixed when I updated windows after reset it but discord still the same.

**Comment by xXDeathAbyssXx** [comment]
> and i need to install a old version?
> Yes

and ok

**Comment by rocksdanister** [comment]
Verify if this folder exists:
`C:\Users\<username>\AppData\Local\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper`

**Comment by xXDeathAbyssXx** [comment]
yes exist

**Comment by xXDeathAbyssXx** [comment]
you need the log file of that dir?

**Comment by rocksdanister** [comment]
Yes; `logs`,  `UI` folders and `Settings.json` file.

**Comment by xXDeathAbyssXx** [comment]
`Log`:
![notepad_9CzTkeuanx](https://user-images.githubusercontent.com/97713025/167515851-23f51a3e-464c-44d1-ab42-1e1124bdeead.png)

`Settings`:

![notepad_MATYVFj8DO](https://user-images.githubusercontent.com/97713025/167516133-c0bbcb36-6a36-477f-9eb4-32d19fa4fd1a.png)

![notepad_LKImtfz0RR](https://user-images.githubusercontent.com/97713025/167516146-682024b2-131c-4b04-8f06-0318f0fb0c91.png)

**Comment by rocksdanister** [comment]
Zip those folders and files **without editing** them and mail it to me instead if you don't want to share the username.

I can't help you like this.

**Comment by xXDeathAbyssXx** [comment]
okay! i send it to [awoo.git@gmail.com](mailto:awoo.git@gmail.com) ?

**Comment by rocksdanister** [comment]
Yes

**Comment by xXDeathAbyssXx** [comment]
already i send it. check your gmail

**Comment by rocksdanister** [comment]
I'll take a look, in the meantime have you tried the installer version of Lively?

**Comment by xXDeathAbyssXx** [comment]
rly rly idk how to install it, i can use this?

![opera_K2SztSmqJ8](https://user-images.githubusercontent.com/97713025/167517056-b7acd6ff-971a-4580-8658-ba332538d09c.png)

**Comment by rocksdanister** [comment]
Yes, Uninstall the store version and run the .exe installer.

**Comment by xXDeathAbyssXx** [comment]
ok

**Comment by xXDeathAbyssXx** [comment]
working with the old version ty

**Comment by ghost** [comment]
Did you change the path where the wallpapers are stored?

**Comment by rocksdanister** [comment]
No, as per the logs everything is default.
Lively core is also setup to warn and shutdown if appdata directory creation fails.. this looks like some unusual desktop-bridge / operating system bug.

I am closing this since its resolved and very rare; will re-open if more people report this.

**Comment by programer-123** [comment]
I have the same problem can you pls send me the download link for the older version

**Comment by rocksdanister** [comment]
"Old" version here just means installer:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions
