### ISSUE TITLE
Option to use classic UI

### ISSUE THREAD

**Issue by Lehmaning** [rocksdanister/lively#1216]
**Is your feature request related to a problem? Please describe.**
The appearence of version 2.0.0 looks awsome, such as the rounded conrner and compact view. However, the old look before version 1.7.4.2 is better for me because of its succinct but not simple design style and the more clean color. I tried to use old versions, but I met the issue about the runtime (#1212 )

**Describe the solution you'd like**
Could you add a option to use classic UI like version 1.7.4.2 in the settings? That might be very nice. 😄 

**Describe alternatives you've considered**
Maybe supplying a more customizable UI settings? But that sounds a waste of time...... Sorry, I have no idea🤔

**Comment by rocksdanister** [comment]
Lively 2.0 is not a reskin, its a complete rewrite using a different UI framework (WinUI) compared to old (wpf)

>Could you add a option to use classic UI like version 1.7.4.2 in the settings? That might be very nice.

Maintaining multiple UI without reason is not practical from a development point of view.
