### ISSUE TITLE
Lively has been nominated for the Microsoft Store Awards and I need your help!

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#1218]
Lively has been nominated for the Microsoft Store App Awards! 
https://twitter.com/gisardo/status/1524781463366795264

If you like Lively, I would hugely appreciate if you could give it a vote!

You can vote for it by filling this form (no login required): 
https://aka.ms/StoreAppAwardsVote

**Comment by madnuttah** [comment]
Done 🤞

**Comment by xFGhoul** [comment]
voted :)

**Comment by dreaddr** [comment]
Voted. Hope you re-pin issue #220 after this ends haha.

**Comment by Parv005** [comment]
Done👍👍

**Comment by rocksdanister** [comment]
Thanks for all the support guys 😁, hoping for the best.
