### ISSUE TITLE
(very minor bug) Wallpaper config rendering over the wallpaper title.

### ISSUE THREAD

**Issue by MoltenCoreDev** [rocksdanister/lively#122]
On wallpaper config screen when scrolling up the wallpaper settings are rendered above the wallpaper title this is a very minor bug.

Screenshot: 
![image](https://user-images.githubusercontent.com/54597045/91990048-8ba13600-ed31-11ea-963c-9b8dcc70cc40.png)

**Comment by rocksdanister** [comment]
Yeah the slider and combobox are uwp controls where as the rest is wpf.
I'm guessing dynamically generating them through code is not playing nice.
I will just create a full uwp usercontrol, that should fix it.

Also `aimbot.ahk` 🙄

**Comment by rocksdanister** [comment]
This issue is resolved in windows store version.
