### ISSUE TITLE
Screensaver does not work during login/lock-screen

### ISSUE THREAD

**Issue by digaopk** [rocksdanister/lively#1225]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by digaopk** [comment]
ola lively não funciona protetor de tela quando está tela login e tela de bloqueio, deveria funcionar proteção de tela qualquer hora desde tenha dado o tempo sem mexer em nada

**Comment by rocksdanister** [comment]
Lively screensaver is just waiting for Windows to tell it when to start https://github.com/rocksdanister/lively/issues/204 
Which means the operating system does not want screensavers to run in this case also as far as I am aware it is not possible to draw on-top of lockscreen (security reasons.) without some difficulty:
 https://blog.adeltax.com/window-z-order-in-windows-10/

This feature will not be worked on for the above two reasons.

Regarding screen protection, the display should turn off shortly after lockscreen starts right?
