### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by JerryXu-code** [rocksdanister/lively#1228]
**Describe the bug**
Crash

**To Reproduce**
1. Double click on the taskbar icon
2. See error

**Expected behavior**

**Screenshots/Video**
![Snipaste_2022-05-20_13-19-52](https://user-images.githubusercontent.com/67638117/169456052-1fc6f002-8666-4ca7-95f8-f5682bb5b5a6.png)

[crash report.txt](https://github.com/rocksdanister/lively/files/8736150/crash.report.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
- Which wallpaper was running at the time if any:None

**Additional context**

**Log file (Important)**
[20220520_131649.txt](https://github.com/rocksdanister/lively/files/8736121/20220520_131649.txt)

Sorry about that there's Chinese in the file

**Comment by JerryXu-code** [comment]
seems it's likely to issue#669

**Comment by rocksdanister** [comment]
![image](https://user-images.githubusercontent.com/17554161/169456796-c2a9e896-0c58-49d0-bd66-df90b4752227.png)

What does this say? can you translate.

**Comment by rocksdanister** [comment]
Can you try Windows store version of Lively:
https://www.microsoft.com/store/apps/9NTM2QC6QWS7

**Comment by JerryXu-code** [comment]
> 

Unhandled exception has occured in a component in your application.If you click continu,the application will ignore this error and attempt to continue.
The specified module could not be found.
The specified module could not be found.

**Comment by JerryXu-code** [comment]
r

> ![image](https://user-images.githubusercontent.com/17554161/169456796-c2a9e896-0c58-49d0-bd66-df90b4752227.png)
> 
> What does this say? can you translate.

Unhandled exception has occured in a component in your application.If you click continue,the application will ignore this error and attempt to continue.
The specified module could not be found.
The specified module could not be found.

**Comment by rocksdanister** [comment]
Looks like xaml island bug, have you tried:
https://www.microsoft.com/store/apps/9NTM2QC6QWS7
