### ISSUE TITLE
Desktop Icon Hiding automatically

### ISSUE THREAD

**Issue by Enigma1309** [rocksdanister/lively#1230]
whenever i click on the openlively option from the taskbar overflow, my desktop icon automatically hides themselves

**Comment by rocksdanister** [comment]
Provide the following information:
**Screenshots/Video**
If applicable a video to help explain your problem.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File

**Comment by Enigma1309** [comment]
> Provide the following information: **Screenshots/Video** If applicable a video to help explain your problem.
> 
> **Log file (Important)** Share the diagnostic files by: Open Lively settings (Gear icon) -> Misc. -> Log File

see this video i have posted

https://i.imgur.com/w6PaxNL.mp4

hope u are able to understand my issue

**Comment by rocksdanister** [comment]
Without the logfile I am guessing here, disable keyboard input in wallpaper settings -> Wallpaper input -> Mouse

Duplicate issue: https://github.com/rocksdanister/lively/issues/1156
