### ISSUE TITLE
Screensaver script unavailable.- runtime download at..

### ISSUE THREAD

**Issue by ItsDragonaire** [rocksdanister/lively#1234]
The bug happens again and again to me... when i went to set individual screen savers it just shows that the plugin isnt installed and i installed it 5 times and then it showd `.net/core/runtime- script unavailable.- runtime download at:` 

**To Reproduce**
1. Go to 'Windows settings'
2. Click on 'Screen saver'
3. Scroll down to 'Lively'
4. Click on 'Settings'
5. The whole thing crashes and shows error

**Expected behavior**
to show the individual screensaver settings menu 

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 2016]
- Matrix AND Periodic Table.

**Additional context**
pls fix asap

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
`.net/core/runtime- script unavailable.- runtime download at:`

**Comment by rocksdanister** [comment]
Download the `Lively Microsoft store v2.0` file:
https://github.com/rocksdanister/lively/wiki/Screen-Saver

Also settings won't do anything, just keep Lively running and when idle running wallpaper will run as screensaver.

**Comment by rocksdanister** [comment]
`Plugin required` message won't go away, its just to inform the user.. if you did the setup then ignore it.
Once Lively is selected in Windows screensaver settings after the delay the currently running wallpaper will turn into screensaver.
(also comment here, no need to create new issue for same problem.)
![image](https://user-images.githubusercontent.com/17554161/170260078-b74ea71e-6841-4c45-a1da-4e2b954b04ac.png)

**Comment by ItsDragonaire** [comment]
What if wanted to install a separate screensaver?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by rocksdanister** [comment]
Not possible currently, its under development https://github.com/rocksdanister/lively/issues/587

**Comment by ItsDragonaire** [comment]
Ok cool thank you for helping me appreciated from the core of my heart

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
