### ISSUE TITLE
Retrieve user language from javascript

### ISSUE THREAD

**Issue by JulienMaille** [rocksdanister/lively#1236]
Is it possible to tell which language is in use from javascript?
I'm trying to localize the weather widget "Ripples", unfortunately `window.navigator.language` doesn't work.
Thanks

**Comment by rocksdanister** [comment]
>I'm trying to localize the weather widget "Ripples", unfortunately window.navigator.language doesn't work.

What's the value its showing?

This is likely due to the program set to Invariantculture:
https://github.com/rocksdanister/lively-cef/blob/91826cee732eda4358e338a99a586c822443c4c0/src/Lively.PlayerCefSharp/Program.cs#L30-L32

its time to fix that part.

**Comment by JulienMaille** [comment]
> What's the value its showing?

en_US
