### ISSUE TITLE
Website is cropped by taskbar

### ISSUE THREAD

**Issue by ElDavoo** [rocksdanister/lively#1241]
**Is your feature request related to a problem? Please describe.**
I added a custom website as a wallpaper and it also gets rendered below the taskbat.

**Describe the solution you'd like**
I'd like to have an option to limit the website space up to the taskbar, not including it. You should than have the option to put something else below the taskbar (for example a flat color, manual or auto, etc)

**Describe alternatives you've considered**
Tried wallpaper modes, but i guess it only applies to static wallpapers.

**Additional context**
Using https://app.studytogether.com/solo as a custom URL.  
Using MS Edge engine with cache enabled.  
(the chromium engine won't let the discord QR load so i'm unable to login)
This is how it appears:
![image](https://user-images.githubusercontent.com/7345120/170883052-698485f4-fba0-49c1-91bb-a4563a4202dd.png)
This is how it should be (using a web browser):
![image](https://user-images.githubusercontent.com/7345120/170883095-7c1d8912-68ea-4e2b-92bd-34e755f735f7.png)

Thank you

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/311
