### ISSUE TITLE
System tray randomly gets squared in Windows 11

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#1247]
Am I the only one who's getting this? I'm susing Windows 11 22000.708 and sometimes the system tray gets squared, but if I exit Lively Wallpaper and then restart it, the issue seems to be gone. Not always though. I wonder if any of you can reproduce the problem. Thanks.
![Immagine 2022-06-03 173423](https://user-images.githubusercontent.com/61087558/171890139-6f3db693-a582-430b-add2-ab36bf075266.png)

**Comment by rocksdanister** [comment]
What does `squared` mean? blurry?

**Comment by ghost** [comment]
I mean it doesn't have the rounded corner it is supposed to show
![Windows-11-system-tray](https://user-images.githubusercontent.com/61087558/171994416-5ddb5d49-60a7-4c1c-8be5-e1decbad1f08.jpg)
.

**Comment by rocksdanister** [comment]
@sylveon any idea what's happening 👀?

**Comment by sylveon** [comment]
This is a bug in the OS. It happens even without lively.
