### ISSUE TITLE
Error trying to build project

### ISSUE THREAD

**Issue by babakmdi** [rocksdanister/lively#1248]
![image](https://user-images.githubusercontent.com/65450661/171957280-f46b022d-6090-4125-8731-a08f27a8ab75.png)
I get this error when I try to run the project

**Comment by rocksdanister** [comment]
Copy the built UI program to the shown location:
https://github.com/rocksdanister/lively/wiki/Building

**Comment by babakmdi** [comment]
i didnt get it! how ?

**Comment by rocksdanister** [comment]
> Create a Plugins folder inside the Core project and copy the required plugin (for basic functioning Cef, Mpv, UI and Watchdog is recommended) builds there - the core project will copy it to output during build.

Build the `Lively.UI.WinUI` project and copy the output onto `../Plugins/UI`
