### ISSUE TITLE
Running this app blocks update Microsoft.WindowsAppRuntime

### ISSUE THREAD

**Issue by Jay-o-Way** [rocksdanister/lively#1251]
**Describe the bug**
According to [messages in "our" PowerToys repo](https://github.com/microsoft/PowerToys/issues/18110#issuecomment-1120236424), some users find that they could not update to a new version. Turns out that running this app is blocking update to Microsoft.WindowsAppRuntime. Hope you can look into this and fix this.

Cheers, Jay

**To Reproduce**
Install PowerToys (v. 0.58)
Fails with error code `0x80073d02`.

**Expected behavior**
Succesful installation

See issue https://github.com/microsoft/PowerToys/issues/18110 for more info.

CC: @jaimecbernardo

**Comment by rocksdanister** [comment]
Winstore version of Lively is using WindowsAppSDK (frame-work depedendent MSIX-packaged) for the UI program.

Could this be an WindowsAppSDK related issue?
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deployment-architecture
The SDK package update without issue in the store while Lively is running and uses new one on relaunch as noted.

**Comment by sylveon** [comment]
This is intentional behavior from Windows. Any app using the WASDK will block the update because framework packages cannot be updated while an app is using it. Running the WinUI 3 gallery app, for example, will also block the update.

**Comment by rocksdanister** [comment]
I am closing this since everything is working as intended (runtime update if app is running only works via store update(?)) and powertoys is bundling the runtime so not a problem anymore.
