### ISSUE TITLE
Screensaver  cannot be configured separately 

### ISSUE THREAD

**Issue by NeoMihai** [rocksdanister/lively#1254]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
This feature is not implemented yet.

dup: https://github.com/rocksdanister/lively/issues/587

**Comment by NeoMihai** [comment]
> This feature is not implemented yet.
> 
> dup: #587

Any idea when it will be implemented?

**Comment by rocksdanister** [comment]
Don't have exact timeframe, it will be launched along with Lively 2.1 or earlier if I get free time.

**Comment by Cris--** [comment]
I would use Lively as screensaver only also!
