### ISSUE TITLE
Allow renaming, tagging or otherwise identify Wallpapers in Library

### ISSUE THREAD

**Issue by Beguiled** [rocksdanister/lively#1259]
**Is your feature request related to a problem? Please describe.**
I prefer the "Triangles & Light" wallpaper for my background. However, I do not like the default color settings so I duplicated the wallpaper and modified my own version of it. The problem I have with the current UI is that I have no way to identify which version is my modified version and which is the original as they both show up looking the same in the Library list.

**Describe the solution you'd like**
I would appreciate a way to either rename, tag or otherwise identify modified wallpapers, giving me a way to indicate what modification of the wallpaper is present.

**Describe alternatives you've considered**
Perhaps a way to filter for "default" or "modified" items in the Library would be another way to go about this.

**Additional context**
As you can see, both of these Triangles & Light appear exactly the same but render differently on the desktop when in use.
![image](https://user-images.githubusercontent.com/7060159/173054937-8456697c-1021-4489-83ac-c8fa1f5d2635.png)

**Comment by rocksdanister** [comment]
Maybe the UI is not clear - `edit` is rename/modify library item (it will also generate new preview image):

https://user-images.githubusercontent.com/17554161/173132846-88bd0236-100f-41d0-858a-7e7a622e1fbe.mp4

**Comment by rocksdanister** [comment]
`tagging` is definitely a must, will be needed once gallery launches.

**Comment by Beguiled** [comment]
Okay, well, that is silly. I must have missed that option in the drop down. I look forward to tags, but **edit** does the trick!
