### ISSUE TITLE
Fluids v2 on v1.0.1.0 don't work like before

### ISSUE THREAD

**Issue by LeoSko** [rocksdanister/lively#126]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.
I tried, doesn't seem to be reported yet.

**Describe the bug**
My dual screen setup was working perfectly before the update - both screens had focus for wallpaper and my lovely fluids v2 were forking as expected. Here is how it worked in v0.9.6.0: https://www.youtube.com/watch?v=9W2C0ppEuQc
Now, there is a weird behavior: it is either focusing the second screen with strange behavior on the main screen: https://youtu.be/CgNr6AoNh2E
Or it doesn't transfer focus to the second screen at all: https://youtu.be/HCBLZ33j3aA

**To Reproduce**
I dunno, just use fluids v2 on dual monitor setup in v1.0.1.0?

**Expected behavior**
Behavior like in v.0.9.6.0

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 19041.450
- fluids v2

**Log file**
Share the crashlog file logfile.txt from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs with detailed information (The file gets overwritten each time lively starts, so make sure its from when lively crashed.)
No crash and no useful info I guess, but here they are:
From 0.9.6.0: https://pastebin.com/GRjrwqg9
From 1.0.1.0: https://pastebin.com/HXSTJYQs

**Comment by rocksdanister** [comment]
Missing an OR statement for span arrangement
https://github.com/rocksdanister/lively/blob/3f7d83ba3c274972f625d065e44357730074a464/src/livelywpf/livelywpf/Core/InputForwarding/RawInputDX.xaml.cs#L190
```csharp
if (ScreenHelper.ScreenCompare(display, x.GetScreen(), DisplayIdentificationMode.screenLayout) || 
        Program.SettingsVM.Settings.WallpaperArrangement == WallpaperArrangement.span))
```
