### ISSUE TITLE
Lively uses much GPU resources (bad performance in games)

### ISSUE THREAD

**Issue by vld-b** [rocksdanister/lively#1263]
I'm on Windows 11 on a laptop and Lively is using a lot of system resources. When playing Valorant, I get around 90 fps, if Lively is running, as soon as I close Lively, I get around 170 fps.

**Comment by rocksdanister** [comment]
Stick to simple video wallpapers if system video memory is low:
https://github.com/rocksdanister/lively/wiki/Performance
without logfile its hard to say if there is any configuration issue, make sure under performance settings it is set to pause wallpaper when fullscreen apps are running.
