### ISSUE TITLE
Right-click context menu from task bar goes off screen for taskbars aligned to side of screen

### ISSUE THREAD

**Issue by Beguiled** [rocksdanister/lively#127]
**Describe the bug**
I run Windows with my task bar aligned to the left side of my screen. When I right-click the Lively taskbar icon to see the context menu, it is not present due to it rendering up and to the left of the icon (thereby presenting it off the side of the screen)

**To Reproduce**
1. Adjust Windows taskbar to align to the left side of your screen
2. Right-click the Lively taskbar icon to display the context menu

**Expected behavior**
The context menu should present itself properly on the screen when right-clicking the taskbar icon.

**Screenshots/Video**
Please see the screenshot. It shows the context menu is being rendered, but on the left, as evidenced by the blurred grey element to the left of the Rainmeter and volume icons. 
![lively-flyout-leftalign](https://user-images.githubusercontent.com/7060159/92379545-a5e26780-f0d5-11ea-9cfd-20a429a51b5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 2004 (19041.450)
- Wallpaper: Triangles & Light

**Additional context**
This is present in 1.0.5.0 and in the last version, possibly longer.

**Log file**
N/A

**Comment by rocksdanister** [comment]
Can't reproduce, this should be handled automatically by the winforms library.
(also just so you know you can double click the trayicon/clicking on lively shortcut in startmenu to open lively)
![Annotation 2020-09-07 182912](https://user-images.githubusercontent.com/17554161/92390290-32be0d00-f138-11ea-9642-7cd63051fdb5.jpg)

Can you try settings windows to hide lively's icon and try accessing it from the '>' menu?
Also have you verified if the traymenu is rendering properly when taskbar is at bottom?

**Comment by Beguiled** [comment]
I can see you do not have the issue. Can you try when the tray is 3 small icons wide? I’ll attempt further validation soon.

**Comment by rocksdanister** [comment]
Yes I tried 3 and 4

**Comment by Beguiled** [comment]
Ahh, and with a second screen to the left? My primary is on the right.

**Comment by rocksdanister** [comment]
hmm its appearing on my leftscreen, is that what is happening with you also?

Looks like its possible to change the behaviour:
https://stackoverflow.com/questions/20311927/contextmenustrip-defaultdropdowndirection-not-working

Setting it to ToolStripDropDownDirection.Default (Right-to-left) fixed it, but then similar issue when taskbar is on rightside with second screen on right 😅

**Comment by Beguiled** [comment]
Yes, that's how it manifests on mine as well - it displays on the wrong screen. As an example, Rainmeter does not:
![image](https://user-images.githubusercontent.com/7060159/92400131-6463b380-f0f9-11ea-8e0e-d4ae4cdd63b1.png)

When looking over Rainmeters' code, it's not readily apparent as to how they do it, but perhaps this is a good place to start:
https://github.com/rainmeter/rainmeter/blob/7225d4081d17ffef118e04e016c4f2237485dc73/Library/ContextMenu.cpp
```c++
	// Show context menu
	TrackPopupMenu(
		menu,
		TPM_RIGHTBUTTON | TPM_LEFTALIGN | (*GetString(ID_STR_ISRTL) == L'1' ? TPM_LAYOUTRTL : 0),
		pos.x,
		pos.y,
		0,
		parentWindow,
		nullptr);
```

TrackPopupMenu is described here:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackpopupmenu

And as that documentation states, the second value (`uFlags`) determines how to align the menu - it looks like they're adding some logic around the correct way to align it? Alternatively, perhaps it is the fact they call out `parentWindow` that helps Windows display it appropriately?

**Comment by rocksdanister** [comment]
I tried something simple, identified the screen in which cursor is on and then just set left/right depending on the cursor position w.r.t that screen.

```csharp
private void ContextMenuStrip_Opening(object sender, System.ComponentModel.CancelEventArgs e)
{
    ContextMenuStrip menuStrip = (sender as ContextMenuStrip);
    //Finding screen in which cursor is present.
    var screen = Screen.FromPoint(Cursor.Position);
    //Converting global cursor pos. to given screen pos.
    var mousePos = Cursor.Position;
    mousePos.X += mousePos.X < 0 ? 
        SystemInformation.VirtualScreen.Width - Screen.PrimaryScreen.Bounds.Width : - Math.Abs(screen.Bounds.X);
    //Checks if cursor is 50% of its screen width to guess taskbar position.
    var menuPos = mousePos.X < screen.Bounds.Width * .5 ? 
        ToolStripDropDownDirection.Right : ToolStripDropDownDirection.Left;
    menuStrip.Show(Cursor.Position, menuPos);
}
```
worked when the main taskbar is in primary screen.

**Comment by rocksdanister** [comment]
Covering all cases:
```csharp
private void ContextMenuStrip_Opening(object sender, System.ComponentModel.CancelEventArgs e)
{
    ContextMenuStrip menuStrip = (sender as ContextMenuStrip);
    //Finding screen in which cursor is present.
    var screen = Screen.FromPoint(Cursor.Position);

    var mousePos = Cursor.Position;
    //Converting global cursor pos. to given screen pos.
    mousePos.X += mousePos.X < 0 ? 
        SystemInformation.VirtualScreen.Width - Screen.PrimaryScreen.Bounds.Width : - Math.Abs(screen.Bounds.X);
    mousePos.Y += mousePos.Y < 0 ?
        SystemInformation.VirtualScreen.Height - Screen.PrimaryScreen.Bounds.Height : - Math.Abs(screen.Bounds.Y);

    //guessing taskbar pos. based on cursor pos. on display.
    bool isLeft = mousePos.X < screen.Bounds.Width * .5;
    bool isTop = mousePos.Y < screen.Bounds.Height * .5;

    //menu popup pos. rule.
    if(isLeft && isTop)
    {
        //not possible?
        menuStrip.Show(Cursor.Position, ToolStripDropDownDirection.Default);
    }
    if (isLeft && !isTop)
    {
        menuStrip.Show(Cursor.Position, ToolStripDropDownDirection.AboveRight);
    }
    else if (!isLeft && isTop)
    {
        menuStrip.Show(Cursor.Position, ToolStripDropDownDirection.BelowLeft);
    }
    else if(!isLeft && !isTop)
    {
        menuStrip.Show(Cursor.Position, ToolStripDropDownDirection.AboveLeft);
    }
}

**Comment by Beguiled** [comment]
That looks like it would work! Do you have that available in a branch at this time or just targeting for a future release?

**Comment by rocksdanister** [comment]
Just wait a bit, coming in next release today.

**Comment by Beguiled** [comment]
It works! Thanks for the quick solution on that one!
![image](https://user-images.githubusercontent.com/7060159/92617425-44fd8f80-f28d-11ea-9c50-3df0b02c5cec.png)
