### ISSUE TITLE
Option to change or apply an wallpaper in the Windows settings gone

### ISSUE THREAD

**Issue by p6thos** [rocksdanister/lively#1274]
How to reproduce:
I have no clue, but maybe the cause is the "Desktop picture" setting in lively.

Expected behaviour:
I can change my wallaper without lively.

Actual behaviour:
I can't change anything at all, because the option in the Windows Settings is gone.

Screenshots:
![image](https://user-images.githubusercontent.com/77694883/175405201-336cdf6d-71b2-44d1-b6d4-660c43991e04.png)

Desktop: Windows 11 22000.739
Log file:
None, i dont know exactly when it happened and i cant reproduce it. Restarting didn't help.

**Comment by rocksdanister** [comment]
I can't reproduce the problem on my systems.
For those interested Lively is using [IDesktopWallpaper](https://github.com/rocksdanister/lively/blob/core-separation/src/Lively/Lively.Common/Helpers/DesktopWallpaper.cs) which is a documented way to change picture wallpaper.

Searching online shows similar problem so could be windows update related.. try the repair solution listed here:
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-background-disappeared/3a54b035-465a-4d13-b779-5ff703f03176

**Comment by p6thos** [comment]
Thank you, i already tried multiple guides online, but it got fixed randomly on its own after i uninstalled it and let it be for 1 month :)
