### ISSUE TITLE
Lively Wallpaper App pixelating screen bug

### ISSUE THREAD

**Issue by OwlofNorth** [rocksdanister/lively#1278]
I installed Lively Wallpaper from the microsoft store a few days ago. I managed to get it working without any problem but suddenly, after switching my graphic settings, the app began experiencing visual issues. This only occures in the app when its opened. The main issue is that the UI starts pixelating with white pixels leaving it this way:
![image](https://user-images.githubusercontent.com/108250670/175857795-fce60137-2c29-41ee-80ec-9b18626e4019.png)

While the app continues running as well as the wallpaper, I find this very annoying. After that I uninstalled it but the issue persisted. Theres any solution to this?
[lively_log_20220626_230801.zip](https://github.com/rocksdanister/lively/files/8988607/lively_log_20220626_230801.zip)

**Comment by rocksdanister** [comment]
Turn off **Nvidia Image Sharpening** in driver control panel.

**Comment by OwlofNorth** [comment]
> Turn off **Nvidia Image Sharpening** in driver control panel.

Thank You for your help
