### ISSUE TITLE
Wallpaper lags when Lively is in focus

### ISSUE THREAD

**Issue by dsjfjskldjsdf** [rocksdanister/lively#128]
When the Lively application is in focus the wallpaper starts lagging.
This dosn't happen with any other application.

Video: https://streamable.com/60xqln

(If I stop moving my cursor for a few seconds it stops lagging, even with Lively still in focus. When I start moving again it starts lagging again.)
(If the Lively application is visible on screen but not focused, the wallpaper does not lag.)
(GPU usage goes down when the lag happens - wallpaper throttled on purpose?)

Tested with "Particle Stream" and "Fluids v2".
CPU/GPU usage both at <20%.
"Applications Focused" setting set to "Nothing".
Browser Engine: CEF.

- Windows 10 2004
- Lively v1.0.5.0
- Latest Drivers

**Comment by rocksdanister** [comment]
Looks like its just downclocking the gpu(can't tell for sure since taskmanager don't show gpu clocks.. just guessing based on increased usage.)
Have you tried with 30fps lock disabled in Customise wallpaper menu for "Particle Stream" wallpaper?

**Comment by dsjfjskldjsdf** [comment]
The GPU clocks don't change.
The FPS lock doesn't change anything. (Doesn't seem to be wallpaper-specific. Tried it with multiple other wallpapers with the same result.)
Did some testing and found that any OpenGL application (that I tested) shows the same effect. (But not because it uses too much resources; CPU/GPU were still below 40%.)

**Comment by rocksdanister** [comment]
Can you try testing with different gpu power management mode in nvidia control panel?

**Comment by rocksdanister** [comment]
Closing due to no reply.
