### ISSUE TITLE
Too much CPU usage

### ISSUE THREAD

**Issue by colinxu2020** [rocksdanister/lively#1282]
**Describe the bug**
CefSharp.BrowserSubproces uses a lot of CPU.

**To Reproduce**
1. Switch to Waves background
2. See error

**Expected behavior**

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/63941938/176636346-66d0dccf-6554-4d8a-afc6-a01bb87f641c.png)

**Desktop (please complete the following information):**
 - OS: Windows10 20H2
-  Background: Waves

**Additional context**
I don't have multiple monitors.

**Log file (Important)**
[lively_log_20220630_165821.zip](https://github.com/rocksdanister/lively/files/9018482/lively_log_20220630_165821.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance
