### ISSUE TITLE
i have two screans and my own wallpapers are like in the middle of both the screans  and the rest of the screans is black

### ISSUE THREAD

**Issue by kire113** [rocksdanister/lively#1283]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Just making a guess here:

If you don't want single wallpaper spanning all screens then change `Placement Method` from `Span` to anything else
<img width="538" alt="image" src="https://user-images.githubusercontent.com/17554161/176881822-242c3e17-d085-4b81-a228-694b0a78eedc.png">

If you want video wallpapers to stretch then select `Fill` for scaling
<img width="638" alt="image" src="https://user-images.githubusercontent.com/17554161/176881928-6f65fb72-3c40-4366-9c91-8d515fc1b954.png">
