### ISSUE TITLE
can't use own video

### ISSUE THREAD

**Issue by BuChiXiangCai-AvA** [rocksdanister/lively#1291]
[lively_log_20220707_102341.zip](https://github.com/rocksdanister/lively/files/9060023/lively_log_20220707_102341.zip)
![image](https://user-images.githubusercontent.com/92437412/177681400-a5e474a1-4574-48bb-8841-29c401add868.png)

**Comment by rocksdanister** [comment]
Can you try playing the video file in your system using the latest or older mpv player build from here:
https://sourceforge.net/projects/mpv-player-windows/files/32bit/

If it works then replace `<install_location>/Plugins/Mpv` with the latest or older mpv build (installer version of Lively only.)

**Comment by ArviXDev** [comment]
I downloaded the latest, replaced in the folder and it still won't work

**Comment by rocksdanister** [comment]
>Can you try playing the video file in your system using the latest mpv player build from here

Have you tried playing the video file using mpv (without Lively.)?

**Comment by ArviXDev** [comment]
yes, nothing shows up
I drag the file then the window closes and nothing more happens

**Comment by rocksdanister** [comment]
Some audio hardware issue with mpv player, you can try disabling audio https://github.com/rocksdanister/lively/issues/1109#issuecomment-1066088998

If that also does not work then report the problem directly here:
https://github.com/mpv-player/mpv/issues

You have to create mpv logfile and NOT lively file (follow the instructions on the mpv windows issue template.)

**Comment by ArviXDev** [comment]
I think it's a windows problem, because it appeared just after the update and now even the windows media player won't play the video file

**Comment by rocksdanister** [comment]
Try reinstalling Media foundation codecs.
VLC player is also an option:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by joykispotta** [comment]
I ran into issue https://github.com/rocksdanister/lively/issues/1776 when I had "exclusive audio mode" switched ON on windows audio settings and playing audio using Foobar "WASAPI(event)" mode through USB speakers. I couldn't change wallpapers and "No process..." error would show up.

I closed Foobar and restarted LivelyWallpaper. Problem resolved for me.

**Comment by kin30528** [comment]
> 我遇到了問題 [#1776 ](https://github.com/rocksdanister/lively/issues/1776)當我在 Windows 音訊設定上開啟「獨佔音訊模式」並透過 USB 揚聲器使用 Foobar「WASAPI（事件）」模式播放音訊時， 。 我無法更改壁紙，並且會出現“無進程...”錯誤。
> 
> 我關閉了 Foobar 並重新啟動了 LivelyWallpaper。 問題為我解決了。

Yo are right. I found that use WSAPI Device form foobar2000 too, and restart the computer, then Everything's going back to normal.
<img width="554" alt="Snipaste_2023-12-19_17-04-41" src="https://github.com/rocksdanister/lively/assets/121107652/406d7ada-39b1-4a24-8ebe-a1e296b853ad">
