### ISSUE TITLE
install dotnet, and it never installs

### ISSUE THREAD

**Issue by kbdevs** [rocksdanister/lively#1294]
Every Time I try to open Lively it asks if I want to install dotnet now, and it never installs

I'd expect it to just install but it will not install or work even if I try to install in manually

![image](https://user-images.githubusercontent.com/86767129/178086944-2b629020-9a19-461b-b763-178848f96301.png)

 - OS: Windows 11

It used to work but now will not open

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

Log file not there or anywhere I could find it

**Comment by rocksdanister** [comment]
>Every Time I try to open Lively it asks if I want to install dotnet now, and it never installs

Describe in detail the steps you did.

>It used to work but now will not open

When did the problem start happening?

**Comment by kbdevs** [comment]
> 

Opened the newest installer,
Installed only for me
Hit ok on english
Hit next
Accepted the terms
sent install to C:\Users\------\AppData\Local\Programs\Lively Wallpaper
hit install
![image](https://user-images.githubusercontent.com/86767129/178087278-0fcb4dfc-bc72-4fcb-9023-7887e5901c73.png)
![image](https://user-images.githubusercontent.com/86767129/178087288-0d3487c7-ddd8-4df3-954c-f5a6e0f05e4e.png)

and thats where ive been stuck


and then when I try to launch it asks if I want to install dotnet and then closes and never happens

**Comment by rocksdanister** [comment]
Try installing directly:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.6-windows-x86-installer

**Comment by kbdevs** [comment]
> Try installing directly: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.6-windows-x86-installer

![image](https://user-images.githubusercontent.com/86767129/178087676-49989312-abe7-41ea-aa10-2b9b1cdfaf74.png)
![image](https://user-images.githubusercontent.com/86767129/178087677-3b974b27-cea6-4841-b191-ba026a1a838c.png)

**Comment by rocksdanister** [comment]
Can you file a bug report here:
https://github.com/dotnet/runtime/issues

**Comment by kbdevs** [comment]
> Can you file a bug report here: https://github.com/dotnet/runtime/issues

I've filed it, any reason why randomly now it would stop working?

**Comment by rocksdanister** [comment]
No clue, could be some issue with your system.

Can try installing older runtime temporarily:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.5-windows-x86-installer

**Comment by kbdevs** [comment]
> Try installing directly: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.6-windows-x86-installer

Yes install worked but Lively Newest Release wants 6.06 and it installed 6.05 shall I try any specific older releases?

**Comment by rocksdanister** [comment]
https://github.com/dotnet/runtime/issues/71869#issuecomment-1179464579
