### ISSUE TITLE
An error occurred trying to start process Lively.PlayerCefSharp.exe

### ISSUE THREAD

**Issue by HereticToXa** [rocksdanister/lively#1296]
After update to version 2.0.2.4 I started to have this error:
![image](https://user-images.githubusercontent.com/74841908/178135811-6f2b0565-ea04-432d-a338-e6f6922f4f48.png)
Before this update I had no any issues.
[20220710_192256.txt](https://github.com/rocksdanister/lively/files/9078667/20220710_192256.txt)

**Comment by HereticToXa** [comment]
Sorry, that was just my Avast Antivirus)

**Comment by rocksdanister** [comment]
False detection can be reported here:
https://www.autohotkey.com/boards/viewtopic.php?t=62266

Thank you.

**Comment by Ivrobot7** [comment]
> False detection can be reported here: https://www.autohotkey.com/boards/viewtopic.php?t=62266
> 
> Thank you.

I reported the false positive, but how can I fix this issue?

**Comment by rocksdanister** [comment]
Restore the file from quarantine and add exception to Lively folder in Avast or just uninstall Avast and stick to 
Microsoft Security/Defender (tested on Lively.)

I am locking this issue since its unrelated and outside the scope of Lively.

**Comment by rocksdanister** [comment]
This should be resolved, update the Avast virus database.
