### ISSUE TITLE
WallpaperPluginNotFoundException when selecting a wallpaper

### ISSUE THREAD

**Issue by Ivrobot7** [rocksdanister/lively#1298]
**Describe the bug**
When I try selecting a wallpaper a error message pops up after restarting my computer and the app it still doesn't work.

**To Reproduce**
1. Go to 'library'
2. Click on 'any wallpaper'
3. See error

**Expected behavior**
When I click on a wallpaper I expect the wallpaper to activate.

**Screenshots/Video**
![image_2022-07-11_115314436](https://user-images.githubusercontent.com/109072579/178238564-0558a79d-993a-4f7f-b411-5c7850223101.png)

**Desktop (please complete the following information):**
 - OS: Windows 10* 64-bit
- I don't have any wallpapers running.

**Log file (Important)**
[20220711_110410.txt](https://github.com/rocksdanister/lively/files/9082885/20220711_110410.txt)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1296

**Comment by Ivrobot7** [comment]
@rocksdanister I reported this false positive, but how can I fix this issue?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/1296#issuecomment-1180206563
