### ISSUE TITLE
Failed to load stream on v0.8.0.0

### ISSUE THREAD

**Issue by twosheep0603** [rocksdanister/lively#13]
mpv and youtube-dl are installed correctly, but still show this error message box immediately.
I'd tried restart the system but nothing helps.
Try to follow the instruction but there's hardly to find the method about adjusting waiting time in wiki.

Screenshot for the message box :
![The wallpaper is taking too long to start](https://i.imgur.com/VqQOtbD.png)

logfile.txt (surprisingly there's empty in the Documents\Lively Wallpaper\ErrorLogs) :
```
2020-02-09 18:12:45.6824|INFO|livelywpf.MainWindow|Setting up wallpaper:-https://www.youtube.com/watch?v=VgXwSdJNks8
2020-02-09 18:12:45.7685|INFO|livelywpf.SetupDesktop|Error: could not get windowhandle after waiting..
2020-02-09 18:12:45.7685|INFO|livelywpf.SetupDesktop|Error: could not get windowhandle after waiting..
2020-02-09 18:12:45.7685|ERROR|livelywpf.SetupDesktop|System.InvalidOperationException: Cannot process request because the process (13504) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
```

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Youtube-Wallpaper

> youtube-dl requires [Microsoft Visual C++ 2010 ](https://www.microsoft.com/en-US/download/details.aspx?id=5555) to run, install it if its not working.
Open mpv, try dropping a youtube video link, if it does not work then youtube-dl is failing to start.

**Comment by twosheep0603** [comment]
> Open mpv.exe - try dropping a youtube video link, if it does not work then youtube-dl is failing to start & hence mpv is exiting.

Sorry for the low-resolution gif and I think mpv.exe worked correctly.
![Video_2020-02-09_193205](https://user-images.githubusercontent.com/5379993/74101368-15aa6700-4b74-11ea-8a90-4e6ff02786ca.gif)

**Comment by rocksdanister** [comment]
are you trying a youtube link? try setting stream quality to Best.

also try opening mpv in Type page as Other app then for arguments give :

> https://www.youtube.com/watch?v=ojhjBrzmNjo  --force-window=yes --loop-file --keep-open --hwdec=yes  --ytdl-format bestvideo[height<=720]+bestaudio/best[height<=720]

**Comment by twosheep0603** [comment]
I tried opening mpv.exe as Other app with -log-file argument but nothing happend, so I wondered if there're some issues with the newest version of mpv player.
Then I reinstall the stable version (mpv-0.32.0-x86_64.7z) instead of the new one (mpv-x86_64-20200202) and it works perfectly now.
Thank you!

**Comment by rocksdanister** [comment]
Something must have changed for the arguments syntax, will update it.
For the time being recommends older version of mpv in wiki.
