### ISSUE TITLE
cant open orginal wallpapers

### ISSUE THREAD

**Issue by ibbyyyyy** [rocksdanister/lively#1300]
![Screenshot 2022-07-12 213212](https://user-images.githubusercontent.com/109179369/178589930-a4fe30bd-fc34-475e-9574-2d2de0dea45f.png)
<!-- 
every since the update last week i cant open some of 11/12 original wallpapers that come with the app

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1296
