### ISSUE TITLE
Wallpaper Plugin Exception

### ISSUE THREAD

**Issue by akp1984** [rocksdanister/lively#1302]
It does not work when applying the animated background, an error comes out indicating that the plugin fails
![plugin exception](https://user-images.githubusercontent.com/109235163/178783551-0413ab8c-22d1-41d0-9e67-9b25aa191601.jpg)
[lively_log_20220713_110751.zip](https://github.com/rocksdanister/lively/files/9104182/lively_log_20220713_110751.zip)

.

**Comment by akp1984** [comment]
Windows 10 pro 64 bits
ver: 21H2

**Comment by rocksdanister** [comment]
logfile zip is corrupt can't open.

Do you use Avast antivirus? https://github.com/rocksdanister/lively/issues/1296

**Comment by akp1984** [comment]
yes

**Comment by akp1984** [comment]
> logfile zip is corrupt can't open.
> 
> Do you use Avast antivirus? #1296

yes
I've already tried it by disabling the antivirus, and if it works now, the situation is which file should I put in exceptions so that it doesn't fail again.

**Comment by rocksdanister** [comment]
Its already deleted the file, you will have to restore it reinstall Lively after updating Avast https://github.com/rocksdanister/lively/issues/1296#issuecomment-1181383952

I recommend just removing third party AV software and stick with Microsoft Defender/security (Lively is tested working.)
