### ISSUE TITLE
Mouse wheel doesn't work in Lively.  鼠标滚轮不能使用在Lively使用

### ISSUE THREAD

**Issue by ecr-oha-lime** [rocksdanister/lively#1303]
**Mouse wheel doesn't work in Lively.  鼠标滚轮不能使用在Lively使用**
在任意一个网页中，不能正常使用鼠标滚轮，也无法拖动网页滚动条。
======translate========
In any webpage, the mouse wheel cannot be used normally, and the webpage scroll bar cannot be dragged.

**To Reproduce**
看视频
as shown in the video

**Expected behavior**
我在网页中可以通过鼠标滚轮翻页，而不是键盘或点击滚动条

**Screenshots/Video**
The video is too big, I put it on https://airportal.cn
Receive Code  754529

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2  22622.290
- Website: https://limestart.cn

**Additional context**
Webview2插件给老子gkd。说好的2-3天呢？
======translate======
When will the Webview2 plugin be available? I remember saying it would be 2-3 days.😂
![image](https://user-images.githubusercontent.com/71540187/178958881-64bd65f8-7f17-41a7-9cda-05bed5803d40.png)

**Log file (Important)**
按理来说，在这并不重要。
======translate======
Logically, it doesn't matter here.

**Comment by ecr-oha-lime** [comment]
这似乎有人发过了。
This seems to have been posted by someone.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/853

**Comment by rocksdanister** [comment]
WebView2 control has unresolved bugs, CefSharp is still the recommended default for now.
