### ISSUE TITLE
Use Squirrel for updates

### ISSUE THREAD

**Issue by qinlili23333** [rocksdanister/lively#1307]
Currently Lively's installer is more than 200M since it contains several Redists (including .NET Core and VC Runtime) and some demo wallpapers.
However for users who need to just update, they have all already installed Redists and demo wallpapers. But now they still have to download an over 200M large installer and waste time on install these duplicate things again.

I think it's time to switch to [Squirrel](https://github.com/Squirrel/Squirrel.Windows) that can avoid these problems. Squirrel can do a delta update for users silently so users will not notice updates and less network activity or disk usage will be needed.

**Comment by rocksdanister** [comment]
I like to keep using my implementation to have full control over the process.

Discussion on reducing installer size: https://github.com/rocksdanister/lively/issues/1171
(Inno script can be written to download VC Runtime and Core when required.)

In the meantime Windows store version of Lively does delta update using latest MSIX packaging technology.
