### ISSUE TITLE
Youtube links = Video Unavailable 

### ISSUE THREAD

**Issue by RarriTaka** [rocksdanister/lively#1308]
Hello, so I think that was a problem that was already on the older version and is still present on the 2.0
The problem is that the youtube links don't work, every time I put a youtube link it says "video unavailable watch on youtube" 
Here's a picture of what happened to me:
![Screenshot_24](https://user-images.githubusercontent.com/109470954/179402579-066b4d32-5f84-42f5-becb-089ce73462d5.png)

And this is happening to every link I put and I don't know if it's a problem with the program or with my settings but I appreciate any help
Thank you

**Comment by rocksdanister** [comment]
When video uploaders disable embedding on video this error shows as Lively is just loading the embed page.
