### ISSUE TITLE
l can`t launch setup

### ISSUE THREAD

**Issue by powershot-go** [rocksdanister/lively#131]
when i launch setup, it doesn`t open.

windows 10 OS 2004(19041.508) 
https://youtu.be/KxwkF9zubwk

**Comment by rocksdanister** [comment]
I think it might be Valorant anti-cheat or something else killing it? 
(I also see very high idle cpu usage... seems unusual)

**Comment by powershot-go** [comment]
it think my cpu is too old

**Comment by powershot-go** [comment]
cpu: i3-4130

**Comment by rocksdanister** [comment]
@powershot-go Can you try the Windows Store version?
https://www.microsoft.com/store/apps/9NTM2QC6QWS7

**Comment by powershot-go** [comment]
OH, l launched setup and perfectly installed. Thank you!
