### ISSUE TITLE
Lively UI not displaying what so ever

### ISSUE THREAD

**Issue by knightryry** [rocksdanister/lively#1314]
No matter what I do like reinstalling or even trying the installer not on the Microsoft store it just wont display.

**Comment by knightryry** [comment]
I have installed the .net framework as the installer comes with

**Comment by rocksdanister** [comment]
Fill the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by knightryry** [comment]
Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Just right clicking on Lively and click "Open Lively" Buffers For A bit but refuses to launch

Screenshots/Video

https://user-images.githubusercontent.com/78123850/180614943-11ffa720-f381-438e-95a4-9a106273e2a3.mp4



Desktop (please complete the following information):

OS: Windows 10 Pro Version 21H2 Build 19044.1826
Which wallpaper was running at the time if any.
None.
Add any other context about the problem here.
I think it might be a missing dependency because other people I know can launch it just fine.  
Log file (Important)
N/A / The lively folder is not there. (Might Be The Issue?)

**Comment by rocksdanister** [comment]
1. Do you have MSI Afterburner running? 
https://github.com/rocksdanister/lively/wiki/Common-Problems#lively-keeps-crashing-on-startperformance-overlay-visible
2. Check system `Event Viewer` Application crashlog for Lively.UI.WinUI?
3. Can you list the names of running programs on your system?

**Comment by knightryry** [comment]
1. Dont have it running. Dont have any overlays but Nvidia shadowplay
2. Here's The logs I found
`Faulting application name: Lively.UI.WinUI.exe, version: 1.0.0.0, time stamp: 0x6283df13
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2206, time stamp: 0xb4fa5b7c
Exception code: 0xc000027b
Fault offset: 0x00240d29
Faulting process id: 0x7ed8
Faulting application start time: 0x01d89ec447244f5e
Faulting application path: C:\Program Files\WindowsApps\12030rocksdanister.LivelyWallpaper_1.0.123.0_x86__97hta09mmv6hy\Lively.UI.WinUI.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1002.543.1943.0_x86__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: cb1f0c14-c568-4c4e-b727-4e85c19a4b93
Faulting package full name: 12030rocksdanister.LivelyWallpaper_1.0.123.0_x86__97hta09mmv6hy
Faulting package-relative application ID: App`
3. Its really just Steam and/or Ubisoft connect, Opera GX, Bitdefender and Nvidia Experience.

**Comment by rocksdanister** [comment]
The logfiles for Windows store version of Lively is located here:
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper`

**Comment by knightryry** [comment]
Heres The Logs You Need! 
[20220722_121216.txt](https://github.com/rocksdanister/lively/files/9174616/20220722_121216.txt)

**Comment by rocksdanister** [comment]
>2022-07-22 12:12:17.5738|WARN|Lively.Services.RunnerService|Process is running elevated, winui may not work...

Re-enable UAC driver if disabled: https://github.com/rocksdanister/lively/issues/1060#issuecomment-1044970174

**Comment by rocksdanister** [comment]
or check to make sure these Windows 10 updates are installed:
https://docs.microsoft.com/en-gb/windows/apps/windows-app-sdk/stable-channel#elevation

**Comment by knightryry** [comment]
Nope! Still not lauching.
In the NEW log file the "Process is running elevated" is gone BUT the error `2022-07-23 17:10:20.5114|ERROR|Lively.Services.RunnerService|Failed to restore windowrect: WaitForInputIdle failed.  This could be because the process does not have a graphical interface.` Seems to be the problem.

**Comment by rocksdanister** [comment]
1. So the initial error was due to UAC driver being disabled? if so did you do any other modifications to Windows (optimizer apps, registry edits etc..)
2. What does the `Event Viewer` say this time?
3. Try uninstalling and reinstalling Store version of Lively?

**Comment by knightryry** [comment]
1. Nope! Dont really trust editing my registry and i dont have any optimizer apps
2. Event View says `Faulting application name: Lively.UI.WinUI.exe, version: 1.0.0.0, time stamp: 0x6283df13
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2206, time stamp: 0xb4fa5b7c
Exception code: 0xc000027b
Fault offset: 0x00240d29
Faulting process id: 0x6f70
Faulting application start time: 0x01d89ed85ea5444e
Faulting application path: C:\Program Files\WindowsApps\12030rocksdanister.LivelyWallpaper_1.0.123.0_x86__97hta09mmv6hy\Lively.UI.WinUI.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1002.543.1943.0_x86__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: be7665c8-dcc1-46bf-8cc9-7dfa9be2c42d
Faulting package full name: 12030rocksdanister.LivelyWallpaper_1.0.123.0_x86__97hta09mmv6hy
Faulting package-relative application ID: App`
3. Cant reinstall the store version because windows store is acting weird.

**Comment by knightryry** [comment]
Was able to reinstall the using the installer though heres the logs from this
[20220723_183221.txt](https://github.com/rocksdanister/lively/files/9174813/20220723_183221.txt)

.

**Comment by knightryry** [comment]
Still Nothing After a full restart
