### ISSUE TITLE
Ripples wallpaper not showing weather data in inner box

### ISSUE THREAD

**Issue by sagerg** [rocksdanister/lively#1315]
**Describe the bug**
Ripples wallpaper does not display correct inner box weather data. Instead shows an error message "Please open openweathermap.org api/city information correctly."

**To Reproduce**
1. Go to 'Ripples' wallpaper on main page and click to set as desktop wallpaper

**Expected behavior**
Weather data being showed correctly with animations in the inner box

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/63772260/180592990-edb9070e-b45d-468e-958e-f28c202b9a4a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Ver. 21H2
- Ripples wallpaper currently running

**Log file (Important)**
[lively_log_20220723_021535.zip](https://github.com/rocksdanister/lively/files/9173207/lively_log_20220723_021535.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/discussions/1295
