### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by vuejshub** [rocksdanister/lively#132]
![image](https://user-images.githubusercontent.com/58390198/92848444-d0595b00-f41c-11ea-80cc-563e3f7a1e45.png)

windows 10 v1809 x64

**Comment by FrontendStack** [comment]
windows 10 x64

**Comment by rocksdanister** [comment]
Need windows 10 [1903](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1903_(May_2019_Update)) or above.
