### ISSUE TITLE
Lively Wallpaper black screen

### ISSUE THREAD

**Issue by Gleteur** [rocksdanister/lively#1320]
**Describe the bug**
I can't see anything on the Lively Wallpaper is just black

**To Reproduce**
I don't know I reinstalled and still didn't work.

**Expected behavior**
To work.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/101505751/180656782-a52e9ed8-906f-422e-8b3d-068675c5821f.png)
This is setting 
![image](https://user-images.githubusercontent.com/101505751/180656830-0657b2e2-2e45-44f6-9f66-7196e7acdeeb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Which wallpaper was running at the time if any. None

**Log file (Important)**
I can't go in setting.

**Comment by rocksdanister** [comment]
moved to https://github.com/rocksdanister/lively/issues/1369 since its related.
