### ISSUE TITLE
Suggestion: Heartbeat for dynamic wallpapers, disabled by default

### ISSUE THREAD

**Issue by Ju1-js** [rocksdanister/lively#1323]
**Is your feature request related to a problem? Please describe.**
I made a dynamic wallpaper that uses a crap-ton of GPU, so I set it to only play when the desktop or background is focused. Sadly this means that the wallpaper (which is a 24-hour adaptation of a 60-second animation) will not follow the time.

**Describe the solution you'd like**
A heartbeat style feature where you can set the wallpaper to unpause for a set time every (another set time) so it can somewhat follow the time. Ex. Unpauses for 1 second every 5 minutes. Or 1.5 seconds every 1 minute, etc.
1. Preferably with an option for milliseconds or decimals for the timings.
2. Should be disabled by default.
3. Setting per wallpaper
4. Option to apply to all wallpapers with confirmation.

**Describe alternatives you've considered**
I've been using a different wallpaper so as to not get a too large jump from say the 3 pm version of the wallpaper to the 8 pm version.

**Comment by rocksdanister** [comment]
>so I set it to only play when the desktop or background is focused.

Lively setting correct? Lively is only pausing the rendering Chromium process, Javascript code can continue run in the background so you can use that to keep track of time and adjust the animation within Javascript.

You can also subscribe to pause event in an experimental build of Lively browser: https://github.com/rocksdanister/lively/issues/974#issuecomment-1150147675

**Comment by Ju1-js** [comment]
When unpausing the animation jumps to the right time, if that's what you mean. It's just when paused for a long time, it can jump from say mid-day to midnight. Which can be pretty jarring.

![image](https://user-images.githubusercontent.com/40339350/180885919-2f8d167f-a941-486d-a8dc-ca4592407c34.png)
![image](https://user-images.githubusercontent.com/40339350/180885968-521b95c4-32d6-497a-acaf-9d7c3acda53f.png)

I am proposing a feature that unpauses the rendering process every so often, for a set time so the wallpaper can "change to the correct time" which would happen if it starts rendering again when you click on the desktop.

**Comment by Ju1-js** [comment]
Yes, the lively setting.
![image](https://user-images.githubusercontent.com/40339350/180887929-db525c3d-9607-4613-bee7-2591cae41b58.png)

**Comment by rocksdanister** [comment]
>A heartbeat style feature where you can set the wallpaper to unpause for a set time every (another set time) so it can somewhat follow the time. Ex. Unpauses for 1 second every 5 minutes. Or 1.5 seconds every 1 minute, etc.

I am closing this because its very specific and not worth spending time on developing and maintaining; this should be handled by the webpage developer by writing javascript code https://github.com/rocksdanister/lively/issues/1323#issuecomment-1194712121

**Comment by Ju1-js** [comment]
Is there a way that I can start and pause the wallpaper renderer via the command line?

**Comment by rocksdanister** [comment]
Not possible, pause rules take affect at the very end.

That's a wrong way to go a about this and not the use case for commandline control.
I am suggesting to subscribe to wallpaper pause/unpaused event and see what time it is when wallpaper is unpaused and adjust the position of the animation based on that.
