### ISSUE TITLE
The screen flickers during looping

### ISSUE THREAD

**Issue by zincnode** [rocksdanister/lively#133]
**Bug :**

I set a video as wallpaper. But when the video is played, the entire screen will flicker briefly, and then the video will play in a loop.
I tried to switch all the provided video players, but none of them worked and the screen still flickered.

**Desktop :**

_OS : Windows10 2004_
_Lively : v1.0.7.0_

**Comment by rocksdanister** [comment]
libVLC player is removed temporarily.

So this happens everytime it loops? Are you sure this is not the issue with video file itself? 

I can't recreate this issue on my end.

**Comment by zincnode** [comment]
> libVLC player is removed temporarily.
> 
> So this happens everytime it loops? Are you sure this is not the issue with video file itself?
> 
> I can't recreate this issue on my end.

Wow, thank you for your reminder, it is indeed a problem with the video file I used.

When I used video editing software to view the video, I found that a few frames at the end of the video were pure black.
