### ISSUE TITLE
Canonical Naming Request  规范命名请求

### ISSUE THREAD

**Issue by ecr-oha-lime** [rocksdanister/lively#1330]
咳咳，说简短点，就不按格式了……
特么的这是什么寄吧，老子TMD看火星文么？能不能用正常点的名字命名文件夹啊，比如壁纸名称什么的，不然我TNND怎么找对应的壁纸文件啊。
========translate==========
[Cough] Say simple, I won't press the format ...
Can the folder naming here use the corresponding wallpaper name? This looks a bit messy, and it is not convenient to find the corresponding wallpaper files.

**Comment by ecr-oha-lime** [comment]
![image](https://user-images.githubusercontent.com/71540187/181919808-612031ac-7e9a-481e-af92-17d1569ad1ad.png)

**Comment by rocksdanister** [comment]
No, the folder name is random and unique and is not for users to browse directly.

If its an `installed` wallpaper `Rigth-click in gallery -> Open File location` to open the folder:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/17554161/181919977-ca1afa80-67fc-4332-9f23-8b51a2d953a6.png">
