### ISSUE TITLE
Whenever computer goes to sleep the wallpapers close and I can't put them back without restarting PC

### ISSUE THREAD

**Issue by MrIHadToDoIt** [rocksdanister/lively#134]
When I try to put them back in the wallpaper is zoomed in and bleeds into the other monitor. I can place wallpapers on monitor again after I restart my PC. 

Sorry for no video or image.

**Comment by rocksdanister** [comment]
You need to give me more details, follow the issue template.

I can't recreate this bug.

**Comment by rocksdanister** [comment]
Closing due to no reply.
