### ISSUE TITLE
Fluids Wallpaper doesn't work after switching audio output device.

### ISSUE THREAD

**Issue by CoderKarsh** [rocksdanister/lively#1342]
I love the Fluids wallpaper. However, when I switch the output audio device, say, from my laptop speaker to my headphones, the wallpaper doesnt react to the new system sound (which is the headphone in this example). The only workaround that is if I go to the app again, and set  Fluids as the wallpaper again. I'd prefer to not have to do this again and again when I switch audio devices.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/276
