### ISSUE TITLE
Wallpaper not being paused when Discord fullscreen

### ISSUE THREAD

**Issue by danieldodi** [rocksdanister/lively#1351]
**Describe the bug**
The wallpaper is not pausing when Discord is on fullscreen, either with the per screen or the all screen option selected in the screen pause rule.
In my case I have 2 monitors so I don't know if this happens with 1 monitor only.

**To Reproduce**
1. Select any wallpaper
2. Put discord on fullscreen

**Expected behavior**
The wallpaper should pause.

**Desktop (please complete the following information):**
- OS: Windows 10 Pro 21H2
- Tested with all wallpapers

**Log file**
[lively_log_20220814_171152.zip](https://github.com/rocksdanister/lively/files/9333592/lively_log_20220814_171152.zip)

**Comment by rocksdanister** [comment]
duplicate https://github.com/rocksdanister/lively/issues/789#issuecomment-940591918 https://github.com/rocksdanister/lively/issues/829#issuecomment-949573275
