### ISSUE TITLE
This program does not support the version of windows your computer is running

### ISSUE THREAD

**Issue by kaimuzx78** [rocksdanister/lively#1352]
**Describe the bug**
This program does not support the version of windows your computer is running

**Expected behavior**
Help me to fix this error. when i was try to run this program this error is hapnning. agin and agin
**Screenshots/Video**
![image](https://i.ibb.co/8rBPCG5/Error.png)
**Desktop (please complete the following information):**
 - OS: Windows 8.1 9600
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
>OS: Windows 8.1 9600

Lively require Windows 10 version 1903 or above.
