### ISSUE TITLE
Inability to configure more than one instance of a wallpaper through the UI

### ISSUE THREAD

**Issue by ZzZombo** [rocksdanister/lively#1358]
**Describe the bug**
Currently separate wallpapers running on more than one screen means you can only configure only one copy of it.

**To Reproduce**
1. Run a wallpaper on more than one screen at a time while separate wallpapers on different screens are enabled.
2. Attempt to configure it. Only one copy of the wallpaper will update.
3. Attempt to configure it for a different copy, realize there is no clean way to do so.

**Expected behavior**
A selector of sorts is present so that you can 1) see the screen you configure the WP for, and 2) choose another screen for configuration.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19044.1889.
- N/A.

**Additional context**
I have two screens and plan on getting another. I already loathe having to work around this issue once this happens, you know.

**Comment by rocksdanister** [comment]
Only in duplicate mode all copies update same time, in separate mode the selected screen wallpaper if present else running wallpaper is customized.

For separate configuration you can do it from the active dialog itself:

https://user-images.githubusercontent.com/17554161/185577000-fa4c69ab-6c45-40cf-bcb3-ab56f2edac53.mp4
