### ISSUE TITLE
Blank white wallpaper on startup

### ISSUE THREAD

**Issue by Aldwew** [rocksdanister/lively#136]
[logfile.txt](https://github.com/rocksdanister/lively/files/5214052/logfile.txt)
Every time I start up my pc my wallpaper is just full white. I have to manually set the wallpaper every time. Any fixes for this? I'm using 1.0.70. I've used Ribbon, rain v2 and triangles & light.

**Comment by rocksdanister** [comment]
Don't see anything unusual in the log, white screen in web wallpaper means the web browser is still loading the page/stopped.
Can you check if this same behavior happens with video wallpapers?

**Comment by rocksdanister** [comment]
Closing due to no reply.
