### ISSUE TITLE
mpv

### ISSUE THREAD

**Issue by gnsilence** [rocksdanister/lively#1362]
![image](https://user-images.githubusercontent.com/18021366/186872868-f5cb77d3-dc8e-46b9-9adb-4a33d40c611f.png)
The above error message appears when I run the project.
Do I need to configure anything extra?

**Comment by rocksdanister** [comment]
Not required, if you want customization create the [LivelyProperties.json](https://github.com/rocksdanister/lively/wiki/Video-Guide#mpv) file [here](https://github.com/rocksdanister/lively/blob/29016c245406cbacf9865e4503d29299ad5b6191/src/Lively/Lively.Common/Constants.cs#L20)
