### ISSUE TITLE
Customize menu glitched when app is not fullscreen

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#1364]
[lively_log_20220828_100813.zip](https://github.com/rocksdanister/lively/files/9439090/lively_log_20220828_100813.zip)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by ghost** [comment]
When the app is not fullscreen and the we try to customize the wallpaper the enter button is not accessible and stays hidden even when we do fullscreen

**Comment by rocksdanister** [comment]
Upload a screen recording showing the issue.
