### ISSUE TITLE
Minor issue w/ Fluid simulation wallpaper - stops reacting to audio

### ISSUE THREAD

**Issue by red-chocolate** [rocksdanister/lively#1365]
First of all, thank you so much for this incredible tool, which also has a fantastic design!

My problem consists of the included Fluid simulation wallpaper occasionally still reacting to the mouse cursor, but it won't sync to the music that is playing. You have to open Lively and re-apply it as the wallpaper to fix the issue, which is a tad annoying. Would it instead be possible, to have "reload wallpaper" option when right-clicking the Lively icon in the taskbar? I think that would be the best solution, seeing as it will be a lot harder to fix the actual issue, so offering a fast remedy seems like a good alternative.

I don't think it's relevant, but I'm running the latest version of Windows 11 Home (64-bit) on a laptop.

**Comment by rocksdanister** [comment]
>My problem consists of the included Fluid simulation wallpaper occasionally still reacting to the mouse cursor, but it won't sync to the music that is playing. 

I don't understand what you mean by this.

**Comment by red-chocolate** [comment]
You don't understand the problem or the solution?

**Comment by rocksdanister** [comment]
problem

**Comment by red-chocolate** [comment]
Every now and then, the "fluids" wallpaper, which comes included with the app, will only half work: it still reacts to the cursor's movement, but not with system audio. To fix this, you have to open the Lively app and apply the same wallpaper again. Therefore, to make this process a lot faster, you could add the "reload" option when you right-click the lively icon in the taskbar.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1194

**Comment by rocksdanister** [comment]
The issue is already fixed and available in beta build:
https://github.com/rocksdanister/lively-beta/releases

**Comment by red-chocolate** [comment]
Sorry for the disturbance in that case, and thank you for the help!

That being said, I don't remember switching audio devices, but perhaps the solution still works.
