### ISSUE TITLE
Wallpaper playlist, xbox support 

### ISSUE THREAD

**Issue by Digitalbil** [rocksdanister/lively#1376]
Hello,
Fantastic job on this software, I too do programming but not so much with WPF, i do more of windows forms and web based applications. I pulled the code because i wanted to go in and create a new feature which I do not mind doing the work but you have quite a bit going on so i figured that maybe i should ask first since I am not sure what direction you plan on taking this project in. I was hoping for the ability to create a playlist and to be able to set the wallpapers to randomly change at specific intervals like 10 minutes and then it would shuffle whats in the playlist and then change. I usually do that with my desktop backgrounds and i have 6 screens. Not sure if you can give me a little direction on my idea so that i could try and make it happen or if this is something you would rather do. In another place where I could be of help is have you considered putting up a paid version for xbox console and or tv web apps? I believe that people would pay to have these wallpapers displayed on theiir tv and or consoles. I have some familiarity with xbox and believe we could make that happen. I think you could easily charge 19.99 bucks or 15.00. I am not sure what would be a fair price for tv web os. I also dont know how much they could handle since most of them are some kind of arm processor running android or similar based software. Even if nothing comes of this message just know that i really dig what you have done. I was thinking of putting up a page to help promote it and to give some direction for people creating wallpapers to help them with things like the videos should be a seemless loop when possible. Not every idea will fit that mold but it makes a difference for sure. 
Thank you 

Digital Bill Lennox

**Comment by rocksdanister** [comment]
>Fantastic job on this software, I too do programming but not so much with WPF

Lively is actually using WinUI3 for the UI and Wpf for the core, you can read more here:
https://github.com/rocksdanister/lively/wiki/Building

>I pulled the code because i wanted to go in and create a new feature which I do not mind doing the work but you have quite a bit going on so i figured that maybe i should ask first since I am not sure what direction you plan on taking this project in. I was hoping for the ability to create a playlist and to be able to set the wallpapers to randomly change at specific intervals like 10 minutes and then it would shuffle whats in the playlist and then change.

The feature you are looking for is playlist https://github.com/rocksdanister/lively/issues/137
I plan to do it at some point but Its been under backlog for a while.

> In another place where I could be of help is have you considered putting up a paid version for xbox console and or tv web apps? I believe that people would pay to have these wallpapers displayed on theiir tv and or consoles. I have some familiarity with xbox 

I am not familiar with xbox, I believe its a locked down system so is there any microsoft approved api for creating live wallpaper?

> I was thinking of putting up a page to help promote it and to give some direction for people creating wallpapers to help them with things like the videos should be a seemless loop when possible.

I have written a wiki entry:
https://github.com/rocksdanister/lively/wiki
Feedback is welcome.
