### ISSUE TITLE
Ok i feel silly now for sure

### ISSUE THREAD

**Issue by Digitalbil** [rocksdanister/lively#1377]
I dont use Github as much as i probably should and just saw the feature request area and also found the discussions area. I looked over some of them and now i do see things that i could contribute with like fixing some of the errors that are mentioned regarding the elements table and stuff like that. Let me know if that helps or if you have a team that does that for you.,

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by rocksdanister** [comment]
duplicate https://github.com/rocksdanister/lively/issues/1376

**Comment by rocksdanister** [comment]
You can edit the original messaging by pressing '...' instead of creating new issue😁
