### ISSUE TITLE
Crashing when choose a file is clicked

### ISSUE THREAD

**Issue by SupBro5** [rocksdanister/lively#1381]
Whenever I want to add wallpaper and press the open option the app closes from the taskbar!!

https://user-images.githubusercontent.com/112799505/189339529-7e3a6a17-5efa-444e-8cdf-b3d673f40a69.mp4

**Comment by rocksdanister** [comment]
Attach the logfile: Lively settings (Gear icon) -> Misc. -> Log File

**Comment by SupBro5** [comment]
> Attach the logfile: Lively settings (Gear icon) -> Misc. -> Log File

can u send a video..

**Comment by SupBro5** [comment]
> Attach the logfile: Lively settings (Gear icon) -> Misc. -> Log File

i dont get any "misc." option

**Comment by SupBro5** [comment]
![image](https://user-images.githubusercontent.com/112799505/189340340-a0df4586-4c81-4fee-861b-678d8f71d80f.png)
is this is the one?

**Comment by SupBro5** [comment]
> Attach the logfile: Lively settings (Gear icon) -> Misc. -> Log File

![image](https://user-images.githubusercontent.com/112799505/189340410-9c60fa2c-93a0-477e-a92e-36825a1ba88f.png)
Is this the one

**Comment by SupBro5** [comment]
> Attach the logfile: Lively settings (Gear icon) -> Misc. -> Log File

[20220909_022001.txt](https://github.com/rocksdanister/lively/files/9535013/20220909_022001.txt)
[20220909_023345.txt](https://github.com/rocksdanister/lively/files/9535014/20220909_023345.txt)
[20220909_111849.txt](https://github.com/rocksdanister/lively/files/9535015/20220909_111849.txt)
[20220909_141401.txt](https://github.com/rocksdanister/lively/files/9535016/20220909_141401.txt)

i found it!

**Comment by SupBro5** [comment]
> Attach the logfile: Lively settings (Gear icon) -> Misc. -> Log File

Sir please help!

**Comment by rocksdanister** [comment]
Attach the zip file generated by following these steps:
` Lively settings (Gear icon) -> Misc. -> Log File`

**Comment by SupBro5** [comment]
> Attach the zip file generated by following these steps: ` Lively settings (Gear icon) -> Misc. -> Log File`

I cant find any .zip file

**Comment by rocksdanister** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/17554161/189345560-0d0fec40-50ac-4662-9817-98a28f7e44b8.png">

**Comment by SupBro5** [comment]
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/17554161/189345560-0d0fec40-50ac-4662-9817-98a28f7e44b8.png">

Ok I did...Next step Please

**Comment by rocksdanister** [comment]
If clicking Save did not generate the file then create a zip and share the AppData folder:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

(skip 'Library' and 'temp' folders while creating zip.)

**Comment by SupBro5** [comment]
> If clicking Save did not generate the file then create a zip and share the AppData folder: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
> 
> (skip 'Library' and 'temp' folders while creating zip.)

[logs.zip](https://github.com/rocksdanister/lively/files/9538195/logs.zip)

**Comment by SupBro5** [comment]
> If clicking Save did not generate the file then create a zip and share the AppData folder: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
> 
> (skip 'Library' and 'temp' folders while creating zip.)

[Uploading Lively Wallpaper.zip…]()

**Comment by SupBro5** [comment]
> If clicking Save did not generate the file then create a zip and share the AppData folder: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
> 
> (skip 'Library' and 'temp' folders while creating zip.)

[Lively Wallpaper.zip](https://github.com/rocksdanister/lively/files/9538207/Lively.Wallpaper.zip)

Here it is!

**Comment by SupBro5** [comment]
> If clicking Save did not generate the file then create a zip and share the AppData folder: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
> 
> (skip 'Library' and 'temp' folders while creating zip.)

Hello!!!

**Comment by SupBro5** [comment]
> If clicking Save did not generate the file then create a zip and share the AppData folder: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
> 
> (skip 'Library' and 'temp' folders while creating zip.)

Sir I tried to reinstall the application and try again.. But it still caused the same problem!

**Comment by rocksdanister** [comment]
I saw your message no need to spam, this looks like an issue with the framework so will take time to fix since its not on my hands.

**Comment by rocksdanister** [comment]
Oh wait.. I know what is happening!
`2022-09-09 11:18:52.2077|WARN|Lively.Services.RunnerService|Process is running elevated, winui may not work...`

its because Lively is running as admin application, enable UAC service following this instruction https://github.com/rocksdanister/lively/issues/1060#issuecomment-1044970174

**Comment by SupBro5** [comment]
> Oh wait.. I know what is happening! `2022-09-09 11:18:52.2077|WARN|Lively.Services.RunnerService|Process is running elevated, winui may not work...`
> 
> its because Lively is running as admin application, enable UAC service following this instruction [#1060 (comment)](https://github.com/rocksdanister/lively/issues/1060#issuecomment-1044970174)

So should I not run the program as admin...I made that change intentionally from the compatibility tab.. Because it was x86 version...I didn't found x64 version

**Comment by SupBro5** [comment]
> Oh wait.. I know what is happening! `2022-09-09 11:18:52.2077|WARN|Lively.Services.RunnerService|Process is running elevated, winui may not work...`
> 
> its because Lively is running as admin application, enable UAC service following this instruction [#1060 (comment)](https://github.com/rocksdanister/lively/issues/1060#issuecomment-1044970174)

Thank you very much sir. It is working after i ran the program as non-admin. I'd like to suggest to create the same app for x64 bit computers. Thank you once again.
