### ISSUE TITLE
When Photoshop is opened and is the focused Window, desktop background will turn black

### ISSUE THREAD

**Issue by spencermacca** [rocksdanister/lively#139]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**
When Photoshop is opened and is the focused Window, the desktop background will turn black until you click on it.

**To Reproduce**
1. Open Adobe Photoshop CC 21.2.2

**Expected behavior**
The wallpaper would not be black and would instead display as normal.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: 
Windows 10 Version 1909 (Build 18363.1082)
- Which wallpaper was running at the time if any: https://www.reddit.com/r/LivelyWallpaper/comments/hkvsn1/sunset_birds_wallpaper/

**Comment by rocksdanister** [comment]
There is a custom application pause rule for photoshop, remove it.

Settings - > Performance - > Application Rules.

**Comment by spencermacca** [comment]
> There is a custom application pause rule for photoshop, remove it.
> 
> Settings - > Performance - > Application Rules.

This is not an option. 
![Photoshop_BzltSmxpIU](https://user-images.githubusercontent.com/35679480/93421996-1ec39980-f8f6-11ea-8e6d-c74bfdfccff8.png)

**Comment by rocksdanister** [comment]
I mean lively settings.
![Screenshot 2020-09-17 103452](https://user-images.githubusercontent.com/17554161/93422469-77347000-f8d1-11ea-9182-80d913735035.jpg)
