### ISSUE TITLE
unable to separate between wallpaper and screen saver.. help?

### ISSUE THREAD

**Issue by GCS08** [rocksdanister/lively#1393]
need some help (inclouding images if able) to make the screen saver different from the wallpaper... any advices?

**Comment by rocksdanister** [comment]
This feature is still under development https://github.com/rocksdanister/lively/issues/587

**Comment by GCS08** [comment]
> This feature is still under development #587

When do you think it'll be ready to use? and, am I upgrading lively that I downloaded from Microsoft store from Microsoft as well?
thank you so much for replying so fast

**Comment by rocksdanister** [comment]
Lively does not have a strict schedule, so I can't give you any date.

You can subscribe to the issue linked and will get a email notification when its ready:
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/17554161/190863488-25652b28-2d59-48dd-8ca1-ba6885620c40.png">
