### ISSUE TITLE
Different Screensaver

### ISSUE THREAD

**Issue by nvrdsky** [rocksdanister/lively#1399]
**Is your feature request related to a problem? Please describe.**
No problem, just wondering about the possibility of being able choose a different screensaver, as opposed to it defaulting to the currently selected wallpaper.

**Describe the solution you'd like**
In (Active Wallpaper), under Screensaver, it has an option for "same as wallpaper" but you can't unselect that.

**Describe alternatives you've considered**
Unselecting that option, and then being able to select a unique wallpaper for the screensaver

**Additional context**
Thanks for your hard work, cheers!

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/587
