### ISSUE TITLE
Using the Wallpaper "Ripples" please enter the Api/city correctly

### ISSUE THREAD

**Issue by TheGiantPolarBear000** [rocksdanister/lively#140]
Hello,

I am new to using this program and I am trying to use the "Ripples" wallpaper, but it isn't loading and it says "Please enter openweathermap.org api/city information correctly." I don't know to do that/ is this an known issue with it installing.
Please help. 

Thank you for reading.

**Comment by rocksdanister** [comment]
https://www.deviantart.com/rocksdanister/art/The-Great-Wave-850391980

**Comment by TheGiantPolarBear000** [comment]
Thank you
