### ISSUE TITLE
Web Wallpaper:Could I execute a local EXE file via the <a> tag?

### ISSUE THREAD

**Issue by ZUXING** [rocksdanister/lively#1406]
I want to make a wallpaper that could open a folder or execute an EXE file, just look like a very very old wallpaper called "Windows 98".
For example, "Windows 98" contains a Windows 98 Logo with a hyperlink, if I click the logo on the Desktop, the IE with Microsoft website will be shown on the screen.

Although I can use Node.js to do the same thing, I just want to try to use fewer EXEs to solve.
Poor English.

**Comment by rocksdanister** [comment]
Are you trying to create a launcher? Node.js is only way to do it currently.

**Comment by ZUXING** [comment]
Okay, I got it.
