### ISSUE TITLE
I can't change my app language.

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#1416]
### Discussed in https://github.com/rocksdanister/lively/discussions/1415

<div type='discussions-op-text'>

<sup>Originally posted by **DJMakerMusician** October 10, 2022</sup>
My app language is set to English, but it for some reason only shows in japanese, and I can't change it (?)
![image](https://user-images.githubusercontent.com/73738591/194897600-f881323f-6776-4970-ae30-3aad54eaf668.png)
</div>

**Comment by rocksdanister** [comment]
@DJMakerMusician

Share the logfile (zip):
`Lively settings (Gear icon) -> System -> Log File`

**Comment by rocksdanister** [comment]
![image](https://user-images.githubusercontent.com/17554161/194914638-496af3aa-3880-4926-b036-092360d6baba.png)

**Comment by Moe23333** [comment]
I also have this problem.

**Comment by rocksdanister** [comment]
Lively is set to use system language and manual language selection is currently not possible currently.

If your issue is Lively using different language from system language then create a new issue with log file to avoid opening this old issue.
