### ISSUE TITLE
Pause wallpaper when desktop is covered by side by side windows

### ISSUE THREAD

**Issue by rollercoaster** [rocksdanister/lively#1417]
**Is your feature request related to a problem? Please describe.**
Lively pauses the wallpaper fine when I have a single full screen window but when I am using windows snap features and have, say, two windows taking two halves of the screen, lively continues to run even though it cant be seen. 

**Describe the solution you'd like**
Lively should pause when the desktop is covered so that it doesn't use system resources

**Describe alternatives you've considered**
I have to manually pause the wallpaper and then manually start it.

**Additional context**
![image](https://user-images.githubusercontent.com/578962/195001199-a237aa9f-3bc0-4817-9a66-92c7732ad970.png)

**Comment by rocksdanister** [comment]
duplicate https://github.com/rocksdanister/lively/issues/474
