### ISSUE TITLE
LTSC support

### ISSUE THREAD

**Issue by olsonperrensen** [rocksdanister/lively#1418]
**Is your feature request related to a problem? Please describe.**
Build 17763 (Windows LTSC 2019) is not being supported at the moment.
**Describe the solution you'd like**
I would like to bring this version to the list of supported OSes.
**Describe alternatives you've considered**
None since next major upgrade will be around 2026. 
**Additional context**
Add any other context or screenshots/mockups about the feature request here.
Thanks for the effort.

**Comment by rocksdanister** [comment]
Store version supports Windows 10 version1809: https://github.com/rocksdanister/lively/issues/361

You can install using powershell (instructions in the linked issue.) if Appinstaller and store not present (or better just install the store itself, there are instructions online.)

**Comment by olsonperrensen** [comment]
Indeed, working now!
