### ISSUE TITLE
Silent install via command prompt

### ISSUE THREAD

**Issue by EnhancedJax** [rocksdanister/lively#1419]
I am currently working on a project to allow users to import multiple themes of different aspects of the system easily, and I wanted to include Lively as the main animated wallpaper choice, hence it will be great to allow Lively to be installed silently (no UI during / after installation) via running the installer executable with a parameter!

**Comment by rocksdanister** [comment]
>I am currently working on a project to allow users to import multiple themes of different aspects of the system easily

Oh.. I am curious, tell me more o_O

>hence it will be great to allow Lively to be installed silently 

https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

`/VERYSILENT` should work, there will be UAC prompt for installing dependencies if missing unless `/NODEPENDENCIES` custom flag is specified.

**Comment by EnhancedJax** [comment]
> Oh.. I am curious, tell me more o_O

Check out https://jaxcore.app/s-hub 👀 

> https://jrsoftware.org/ishelp/index.php?topic=setupcmdline
> /VERYSILENT should work, there will be UAC prompt for installing dependencies if missing unless /NODEPENDENCIES custom flag is specified.

Thank you! Exactly what I am looking for 😄 

I'll close this as it's resolved 👍
