### ISSUE TITLE
GUI Black Screen (Windows 10)

### ISSUE THREAD

**Issue by IAMSPYS** [rocksdanister/lively#1425]
**Describe the bug**
The gui always be black and not responding

**To Reproduce**
Open up the gui

**Expected behavior**
It's supposed to show contents

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![image](https://user-images.githubusercontent.com/77228351/195833522-9d47b04a-6c94-47ba-9691-e14a7a066f78.png)
![image](https://user-images.githubusercontent.com/77228351/195833464-5a8a56ef-1671-470a-a0cb-3d769b3f73db.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Build 19044.2006
- Which wallpaper was running at the time if any: None

**Additional context**
It's been like this for many days now and doesn't even seem to be working

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[20221014_180248.txt](https://github.com/rocksdanister/lively/files/9785506/20221014_180248.txt)

**Comment by rocksdanister** [comment]
duplicate https://github.com/rocksdanister/lively/issues/1369

**Comment by IAMSPYS** [comment]
The log says it couldn't find three json files but those files are all there. I don't know what to do now.

**Comment by rocksdanister** [comment]
>The log says it couldn't find three json files but those files are all there.

That's normal when starting for first time.

This issue is still under investigation, there is no solution at the moment.
