### ISSUE TITLE
cannot work with Tencent's deskgo

### ISSUE THREAD

**Issue by Eminem-lamar** [rocksdanister/lively#1429]
f you open both software, but only the DeskGo wallpaper is displayed, it is useless to keep it running！
![image](https://user-images.githubusercontent.com/115933628/196037920-d2a26e36-9f54-47dc-bbdf-149bc156f660.png)

**Comment by ecr-oha-lime** [comment]
嗯，奇怪，试试Coodesker有没有这个问题。
=======translate========
Hmm, weird, try Coodesker to see if it has this problem.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/173

**Comment by Eminem-lamar** [comment]
> duplicate

我试过#173的办法，但还是不能用

**Comment by Eminem-lamar** [comment]
> 嗯，奇怪，试试Coodesker有没有这个问题。 =======translate======== Hmm, weird, try Coodesker to see if it has this problem.

我试试
