### ISSUE TITLE
The program does not work properly, after it is set to "pause" when another application is in progress.

### ISSUE THREAD

**Issue by NinjaSinistro** [rocksdanister/lively#1430]
The program does not work properly, after it has been configured to "pause" when another application is in use, to save GPU and memory.

**Comment by rocksdanister** [comment]
I don't understand the problem, can you describe what "The program does not work properly" means?

**Comment by NinjaSinistro** [comment]
Bom dia Dani,

O programa tem a opção de pausar quando ele não está em foco, poupando o
computador de trabalhar em segundo plano. O problema é que, o programa não
está pausando quando está em segundo plano, ele continua executando o plano
de fundo, mesmo configurando o programa.

Att, / Best regards,

*Marlan Guimarães*
*021 99768-1130*



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
17/10/22
10:31:56

Em seg., 17 de out. de 2022 às 01:37, Dani John ***@***.***>
escreveu:

**Comment by rocksdanister** [comment]
duplicate https://github.com/rocksdanister/lively/issues/1445
