### ISSUE TITLE
For laptops, Make an option to launch when plugged in and stop if unplugged.

### ISSUE THREAD

**Issue by sakshambhattrai** [rocksdanister/lively#1431]
If not a Realtime checking for whether device if plugged in or not maybe you can make it do a one-time check on startup if the device if plugged in it launches normally and if not then it does not launch

**Comment by sakshambhattrai** [comment]
I dont want the app wasting my battery when i use it. I found this on the internet: 


Const execApp1 = "application string goes here"
Const execApp2 = "example:   "c:\full\path\to.exe /arg1 /arg2"
Const execApp3 = "Use double quotes around things with spaces ""like so""."

Dim objShell :Set objShell = CreateObject("WScript.Shell")
Dim objWMI :Set objWMI = GetObject("winmgmts:\\.\root\CIMV2")
Dim objBatteries :Set objBatteries = objWMI.ExecQuery("SELECT * FROM Win32_Battery",,48)
Dim objBattery :Set objBattery = Nothing

Dim onACPower :onACPower = False

For Each objBattery in objBatteries
    If objItem.BatteryStatus = 2 Then   '2 is the value I got on a full battery. You may need to experiment with this.
        onACPower = True
    End If
Next

'Here's where you decide if you're on battery or AC and what to run in each case.
If onACPower = True Then objShell.Run execApp1, 0, False
If onACPower = False Then objShell.Run execApp2, 0, False
If onACPower = True Then objShell.Run execApp3, 0, False



mabye it can somehow be incorparated into the software

**Comment by rocksdanister** [comment]
>I dont want the app wasting my battery when i use it.

Wallpapers can be set to pause automatically based on AC power and Windows battery saver mode.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/17554161/196088790-462bea42-4e9d-405a-bb25-4efbee3f0028.png">

Will stay in memory but that should be negligible, If that is not enough you can write your [own script.](https://github.com/rocksdanister/lively/wiki/Command-Line-Controls)
