### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by sugarylettuce49** [rocksdanister/lively#1437]
**Describe the bug**
The app crashes upon opening the settings and customization

**To Reproduce**
Open the app's settings page and instant crash

**Expected behavior**
I wish to see a settings page

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS:  Windows 10 2009

**Additional context**

**Log file (Important)**
none was generated

**Comment by rocksdanister** [comment]
moved here https://github.com/rocksdanister/lively/issues/1448
