### ISSUE TITLE
Wallpapers don't show when Lively is downloaded from Microsoft Store

### ISSUE THREAD

**Issue by wvmonson** [rocksdanister/lively#1438]
**Describe the bug**
When downloaded from the Microsoft Store, the app doesn't play wallpapers.

**To Reproduce**
Clicking on any of the pre-loaded wallpapers does nothing, and trying the one I loaded didn't either.
Clicking the ... menu beside any of them and hitting Set Wallpaper doesn't work either.

**Expected behavior**
I expected the wallpapers to play on my Add any other context about the problem here..

**Desktop (please complete the following information):**
 - OS: Win 11
- No Wallpapers would play
- 
**Additional context**
I got this program through the Microsoft Store, as I was following a YouTube video to learn how to use Lively to make my taskbar transparent. It worked. I then got the idea for how to use the app for a wallpaper since I was using a still of a video. I got the video and added it and it wouldn't work. I tried using any of the other pre-loaded wallpapers in Lively and they didn't work either. I uninstalled and attempted to use the regular installer (I learned of it through another YouTube video I was watching trying to fix my issues.) I can now run wallpapers but I am having new bugs. Will Make a different report for those.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
(Me trying to do the above is causing the same issue I'm wanting to write another report about, where the window just goes away. The app is still running, as its in the sys tray and wallpaper is still running.)
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
(I don't think the above will be useful now as I have uninstalled the original one through the Microsoft Store and reinstalled through the installer.)

**Comment by rocksdanister** [comment]
lets just keep the discussion to one place https://github.com/rocksdanister/lively/issues/1439
