### ISSUE TITLE
Could we get the ability to make a slideshow?

### ISSUE THREAD

**Issue by Ferynix** [rocksdanister/lively#1441]
**Is your feature request related to a problem? Please describe.**
Windows 11 frustratingly doesnt support slideshows per monitor like previous windows versions, so they stretch into a low res image across all monitors (which is ugly as hell)

**Describe the solution you'd like**
I simply want the ability to make per-monitor slideshows

**Describe alternatives you've considered**
Ive looked around for a while, and I cant find much honestly. Microsoft never responded to my support request, neither did anyone in the official microsoft discord.

**Additional context**
An example of a stretched slideshow running: I dont want this:
![image](https://user-images.githubusercontent.com/44554976/197500810-a4cb3193-d428-48a1-ba42-5e7caad7c7c4.png)
Not a slideshow but its the effect I want:
![image](https://user-images.githubusercontent.com/44554976/197500868-567a60e1-785a-408c-8198-047f08a6b041.png)

**Comment by rocksdanister** [comment]
Based on the screenshot do you mean "slideshow (pictures changing at regular intervals)" per monitor or "picture" per monitor?

**Comment by rocksdanister** [comment]
closing as dup https://github.com/rocksdanister/lively/issues/137
