### ISSUE TITLE
Lively doesn't pause de wallpaper when I have a window maximized and a non-maximized window over it

### ISSUE THREAD

**Issue by oacoello** [rocksdanister/lively#1444]
**Describe the bug**
I make sure that "pause wallpaper when maximized" is enable on settings.
When I maximized a window, the wallpaper stops, but when I open another window and I focus it (while the another window is maximized, the wallpaper start running in the background again, I notice it because I use taskbar clear option and also the Task Manager shows me Lively using a percentage of GPU.

**To Reproduce**
1. Open an app and maximized its window.
2. Open Task Manager while the window of another app stays maximized.
3. Check process using GPU
4. You will see Lively using the GPU (like a 15% because Intel UHD)

**Expected behavior**
The Task Manager should show me Lively stop running the wallpaper when I maximized an app windows, even if I have another window over it, because I have an app Maximized, the wallpaper shouldn't be running.

**Screenshots/Video**
[Demonstration video]
(https://drive.google.com/file/d/1_xDxuzwiQlhIdjNIapwxvaR_zdsJ6vpW/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 Build: 19043.2130
- Wallpaper: Custom mp4 file.

**Log file (Important)**
Share the diagnostic files by:
[lively_log_20221028_133848.zip](https://github.com/rocksdanister/lively/files/9891296/lively_log_20221028_133848.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/474
