### ISSUE TITLE
Problem with performance while there is a window over the full screen app

### ISSUE THREAD

**Issue by nrb-dev** [rocksdanister/lively#1445]
**What and when is happening**
I have the 'pause' option turned on when the full screen application is displayed and the 'no change' option when there is a window. However, recently I've noticed that when i play any game (in fullscreen or borderless mode) and i press ctrl+tab to move e.g. to Discord, sometimes I have a huge drop of fps (if the game is more demanding).

So, basically, when you have a full screen or borderless application open and there is another application in window mode on it, the wallpaper is no longer paused and it uses the GPU.

Screenshot when there is a full screen app running (wallpaper is paused):

![fs-app-open](https://user-images.githubusercontent.com/90916274/198735181-f8f189d7-cd9e-404b-9e23-268f966b4617.png)

Screenshot when there is a window over the full screen app (wallpaper is no longer paused):

![while-hovering-fs-app](https://user-images.githubusercontent.com/90916274/198735298-a59cb1f0-d2a8-42c5-9fb9-6c8962b078a7.png)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/474 https://github.com/rocksdanister/lively/issues/789#issuecomment-940591918

Set `Application Focused -> Pause` then remove Discord from the exception or alternatively try [Direct3D](https://github.com/rocksdanister/lively/wiki/Performance#pause-algorithms) pause algorithm which detects games only.
