### ISSUE TITLE
Screen "Turn off" setting not working (Windows Power & Sleep)

### ISSUE THREAD

**Issue by JimmyFanClone** [rocksdanister/lively#1446]
**Describe the bug**
After setting the monitor "Power & sleep" option to turn off after certain time period, running dynamic background prevents monitor from ever turning off.

**To Reproduce**
1) Go to windows settings for "Power & sleep".
2) Select under Screen option "When plugged in, turn of after" and choose dropdown value like 15 or 30 minutes.
3) Make sure lively is running with some dynamic background active.
4)  Wait for chosen time duration to elapse.
5) Observe that monitor does not turn off.

**Expected behavior**
The monitor should power off to save energy.

**Screenshots/Video**
This is a screenshot of the "Power & sleep" settings:
![image](https://user-images.githubusercontent.com/117056712/198926333-8014722e-2559-4116-a26c-e712048d8a61.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro, version 10.0.19044 Build 19044
- Which wallpaper was running at the time if any:  https://youtu.be/wTK7gd9RzME

**Additional context**
Same issue occurs with or without screensaver (including lively screensaver).
Also note that I have reviewed the Wiki "common problems section" and confirmed that my lively video player is set to mpv.  But the issue still persists.  Screenshot of my Wallpaper settings:
![image](https://user-images.githubusercontent.com/117056712/198927108-eb9c44fd-c9db-4e0e-94f7-157c06a1c2fc.png)

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20221030_234427.zip](https://github.com/rocksdanister/lively/files/9897865/lively_log_20221030_234427.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/1109

**Comment by rocksdanister** [comment]
There is a workaround listed here: https://github.com/rocksdanister/lively/issues/1109#issuecomment-1066088998

**Comment by JimmyFanClone** [comment]
Hi how's it going?

Thanks for the info.  I've tried out the mpv.conf file change and this is what my powercfg command returns.  Does this look right?  What's not clear is if your fix is supposed to make turning off the audio unnecessary or do I have to both turn off the audio from Lively settings and deploy the conf file fix...  Thanks!

![image](https://user-images.githubusercontent.com/117056712/199169175-d7ddaa73-cebc-494f-af47-159660a6116c.png)

**Comment by rocksdanister** [comment]
Try downloading the yt video (there are tools online.) and loading that downloaded file as wallpaper instead.

**Comment by JimmyFanClone** [comment]
Ok, i've downloaded the video and now the customize popup show the mute option.  I've muted it but still no cigar.  The screensaver (same video) kicks in.  But monitor never turns off.  I've noticed that powercfg returns different requests as compared to my previous screenshot:
![image](https://user-images.githubusercontent.com/117056712/199392707-225aaf02-6377-4200-8255-633d566b217b.png)

And here is my customize option popup:
![image](https://user-images.githubusercontent.com/117056712/199392758-674d9262-e364-4538-aebb-b5547d5a6ca7.png)

Here is my Wallpaper settings with the player plugin settings:
![image](https://user-images.githubusercontent.com/117056712/199393366-b9b69424-9d97-43eb-b991-eb9408cae367.png)

And here is the mpv.conf details.  Where it is saved and the contents:
![image](https://user-images.githubusercontent.com/117056712/199393121-4ad3aad1-b814-4cdd-a934-8e99c0a805b5.png)

Here are my lively logs again.  I've rebooted my machine since to see if that helps but nope.  I can see the zip contains logs from prior days, so hopefully it will contain my earlier test that failed (on 11/01):
[lively_log_20221102_000239.zip](https://github.com/rocksdanister/lively/files/9915860/lively_log_20221102_000239.zip)

Thanks!

Regards,
Jimmy

**Comment by rocksdanister** [comment]
Create the folder `portable_config` like shown:
`<Lively install location>\plugins\mpv\portable_config\mpv.conf`

**Comment by JimmyFanClone** [comment]
ok, that definitely did something.  Didn't fix it but seems to be step in the right direction.  powercfg now shows this:
![image](https://user-images.githubusercontent.com/117056712/200154652-43663cad-a92c-4d65-9ad8-e13dfb86d41a.png)

*FYI I have a soundblaster video card and an external headphone amp connected to the video card that outputs to headphones or desktop speakers.

My last attempt configuration:
screensaver (lively) in 15 minutes
Monitor off in 30 minutes

So it went to screensaver after 15 minutes.  But it stayed on that and monitor never went into sleep mode.

I've attached the logs:
[lively_log_20221106_004525.zip](https://github.com/rocksdanister/lively/files/9945173/lively_log_20221106_004525.zip)

Thanks,
Jimmy
