### ISSUE TITLE
Write Lively logs to the Windows Event Viewer

### ISSUE THREAD

**Issue by Beguiled** [rocksdanister/lively#145]
**Is your feature request related to a problem? Please describe.**
Whenever Lively starts, the logfile.txt file is overwritten. This is not useful if you're attempting to understand what happened prior to restarting the application to see if it will help recover some unwanted behavior.

**Describe the solution you'd like**
Write log file data (or perhaps just start up and errors/exceptions) to the Windows event viewer.

**Describe alternatives you've considered**
An alternative would be to create a new log file every time Lively starts, with a clean up process to remove old ones after a time.

**Additional context**
N/A

**Comment by rocksdanister** [comment]
I have a built in log viewer along with backups of previous logs planned for next release!
![new debugger lively](https://user-images.githubusercontent.com/17554161/93686633-16758500-fad5-11ea-86ed-52e1b1413722.jpg)

**Comment by Beguiled** [comment]
Of course you do. Awesome!

**Comment by Beguiled** [comment]
Typo found: `wen’t` should be `went`.

**Comment by rocksdanister** [comment]
Weird no translator has mentioned that typo lol
