### ISSUE TITLE
Access Customize menu of current wallpaper from tray context menu

### ISSUE THREAD

**Issue by cassist** [rocksdanister/lively#1451]
I recall being able to access the customize window of the current wallpaper from the tray icon's context menu back in lively 1.x, appears that this functionality was not ported to 2.0.

I suspect that this request has some added complexity with how the new customize pop-up is no longer a separate window but some kind of inset of the main UI.

**Comment by rocksdanister** [comment]
>I suspect that this request has some added complexity with how the new customize pop-up is no longer a separate window but some kind of inset of the main UI.

Yes, its because UI is separate program now so the process needs to start before it can display the customize window.

Should be possible to implement for next release, let me see.

**Comment by rocksdanister** [comment]
Next update will have this:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/17554161/200802538-ddfd3d52-65ae-4435-8893-1dd9f6a3fc0d.png">

If the UI program is not cached in memory then initial startup time will be a bit slow.
