### ISSUE TITLE
White wallpaper

### ISSUE THREAD

**Issue by lhr081124** [rocksdanister/lively#1453]
Sometimes when I return to the desktop, I will find that the wallpaper turns white, and reset the wallpaper to reply.
And this is my log file.

[lively_log_20221111_145524.zip](https://github.com/rocksdanister/lively/files/9987195/lively_log_20221111_145524.zip)
Thanks :-)

**Comment by XERKC** [comment]
The same problem, white wallpaper, appeared only today, did not exist before
[20221112_234518.txt](https://github.com/rocksdanister/lively/files/9995665/20221112_234518.txt)

**Comment by rocksdanister** [comment]
This should be already fixed on the beta channel, you can check:
https://github.com/rocksdanister/lively-beta/releases
(Do not install beta if you are using Microsoft store version of Lively since only installer is supported.)

**Comment by lhr081124** [comment]
Thanks a lot:-)
