### ISSUE TITLE
Weather indication not working

### ISSUE THREAD

**Issue by Dominiquini** [rocksdanister/lively#1457]
**Describe the bug**

**To Reproduce**
1. Open Lively
2. Select "Ripples"
3. Customize the wallpaper to show the weather
4. Insert the city code and OpenWeather API
5. View message to enter api/city information

**Expected behavior**
I should see the weather displaying on the background

**Screenshots/Video**
![yOcwA30Qau](https://user-images.githubusercontent.com/1180808/201953202-0c9d056d-9c41-4c8b-a105-6c22a90704dc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 19045.2251
 - Lively: 2.0.5.0
 - "Ripples"

**Additional context**
I tried this wallpaper too (https://github.com/rocksdanister/weather-fetch-wallpaper) and the same problem occurs!

**Log file (Important)**
[20221115_130603.txt](https://github.com/rocksdanister/lively/files/10014261/20221115_130603.txt)

**Comment by rocksdanister** [comment]
If you recently created the API key then it takes time to activate on openweathermap side.

**Comment by Dominiquini** [comment]
> If you recently created the API key then it takes time to activate on openweathermap side.

I tried my old API key bedore! When it not worked, I created a new one... None of then worked!

Thanks.
