### ISSUE TITLE
Pause When on Battery Power doesn't work

### ISSUE THREAD

**Issue by Klbgr** [rocksdanister/lively#146]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**
When i disconnect ac power, it continues to play the wallpaper. Same behavior when i'm starting Windows without ac power plugged in.

**To Reproduce**
Always

**Expected behavior**
Pause wallpaper when ac power is disconnected.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/43754408/93690186-db278600-fad5-11ea-9010-24b9a944e9d3.png)
![image](https://user-images.githubusercontent.com/43754408/93690187-e24e9400-fad5-11ea-8f4a-649854044605.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 64 bit
- Occuring with every wallpapers

**Additional context**
It's an Asus laptop with a second HDMI monitor pluged in.

**Log file**
[logfile.txt](https://github.com/rocksdanister/lively/files/5250755/logfile.txt)

**Comment by rocksdanister** [comment]
Yeah looks like I forgot to add the code from pre v1.0, should work from next update onwards.
