### ISSUE TITLE
Black Wallpaper upon restarting the screen

### ISSUE THREAD

**Issue by azurexxxx** [rocksdanister/lively#1460]
**I don't really know when this happens because it usually happens once in a while, but I eventually see a black screen with a blank rectangle on the top left. **

**To Reproduce**
1. Turn your screen off (make sure your PC doesn't go to sleep)
2. (probably) wait for a few minutes (30-40)
3. Turn your screen back on.

**Expected behavior**
Wallpaper continues animating as usual

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![image](https://user-images.githubusercontent.com/71032889/202019935-df029faf-4f9b-48e7-aafa-65d520d78ab2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
- Which wallpaper was running at the time if any: The Hill

**Additional context**
Rebooting Lively does not fix it. Neither does pausing/resumin and closing the wallpaper.

**Log file (Important)**
[lively_log_20221115_213509.zip](https://github.com/rocksdanister/lively/files/10016029/lively_log_20221115_213509.zip)

**Comment by rocksdanister** [comment]
Can you check if it happens with the latest v2.0.5.0 release?

**Comment by MonyetKeselek** [comment]
> Can you check if it happens with the latest v2.0.5.0 release?

still happens in 2.0.6.1, mine is the same issue

**Comment by rocksdanister** [comment]
moved here: https://github.com/rocksdanister/lively/issues/2178#issuecomment-2111804461
