### ISSUE TITLE
JSON Schemas for LivelyProperties and LivelyInfo

### ISSUE THREAD

**Issue by dejohansson** [rocksdanister/lively#1468]
**Is your feature request related to a problem? Please describe.**

It can be frustrating to define `LivelyProperties.json` and `LivelyInfo.json` without any validation or IntelliSense pointing you in the right direction.

**Describe the solution you'd like**

1. Define [JSON Schemas](https://json-schema.org/) for `LivelyProperties.json` and/or `LivelyInfo.json`.
2. (Optional) Add entries for the schemas in the [JSON Schema Store](https://github.com/schemastore/schemastore/).

**Additional context**
IntelliSense example using a draft [JSON Schema](https://json-schema.org/).
![IntelliSense Demo](https://i.imgur.com/UadPKDr.gif)

**Comment by rocksdanister** [comment]
Are you interested in implementing it?

(Ignore `LivelyInfo.json` as its use is internal only with the argument field being the only exception.)

**Comment by dejohansson** [comment]
> Are you interested in implementing it?

Yes, I would like to have a go at implementing it. 

So far I have been using this [wiki page](https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#controls) to figure out the schema definition. Which part of the source code should I start looking at if I want to reverse engineer the types and constraints for `LivelyProperties.json`?

**Comment by rocksdanister** [comment]
The wiki is up-to-date and complete, there is an upcoming [change](https://github.com/rocksdanister/lively/issues/229) but that only affects the receiving JS code so no issue.

This is the [source](https://github.com/rocksdanister/lively/blob/55d0caf2aa483731cf163215b7e1e9a81ee59e63/src/Lively/Lively.UI.WinUI/Views/LivelyProperty/LivelyPropertiesView.xaml.cs#L148), controls are wrappers around native [WinUI 3 controls.](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls?view=winrt-22621)
