### ISSUE TITLE
Load image files (.png/.jpg ...)

### ISSUE THREAD

**Issue by tellmewhy12** [rocksdanister/lively#147]
### **Is your feature request related to a problem? Please describe.**
I like switching Wallpapers and I also like having everything in one place.
Currently if I want to alternate between a live wallpaper and an image wallpaper I have to ditch Lively and choose an other method of setting my desktop wallpaper

### **Describe the solution you'd like**
In the "+ Wallpaper" Section:
- _( a way of circumventing image-ratio-blackbars for images added via URL ), see alternatives_
- via the "Browse" - button

![Image files](https://user-images.githubusercontent.com/71931749/94341907-a2276e00-000d-11eb-8b97-520a61569576.png)

>File types: _Native Wallpaper Selection Window_
![Windows native add Wallpaper](https://user-images.githubusercontent.com/71931749/94342008-68a33280-000e-11eb-8db6-e3e57d160c44.png)
Windows supported file types seem to be **.jpg/.jpeg**, **.png**, .bmp, .gif, .tif/.tiff, .dib, .jfif, .jpe, .wdp

### **Describe alternatives you've considered**
Adding images via URL does almost work, but if the aspect ratio of the image differentiates from the monitor's you get black borders. Using a separate .html file does not seem like an appropriate option in this case.

**Comment by rocksdanister** [comment]
Why not just make a webpage that display image fullscreen and use lively's folder dropdown api: https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#folder-dropdown

Just write a custom html page and you can set any aspect ratio scaling you want in code.
Take a look at this video project for example:
https://github.com/rocksdanister/lively/wiki/Web-Guide-VI-:-Webpage-Video-Support

Its not really hard to implement.. infact if you just rename the image file extension to .gif lively will use the uwp image control:
https://github.com/rocksdanister/lively/wiki/GIF-Guide
and will work like you want and the scaling algorithm can be set in Settings -> Wallpaper -> Choose a fit

**Comment by rocksdanister** [comment]
Picture wallpaper type will be available in next update.
