### ISSUE TITLE
The ability to select multiple but not all screens 

### ISSUE THREAD

**Issue by techguyone** [rocksdanister/lively#1471]
Now I have 2 main monitors and a sensor panel I find I can have either ONE screen themed or ALL screens themed, this isn't ideal for the sensor panel screen.

I'd like the ability to pick which screens are themed, for example Monitor 1 & 3

Could this be implemented please?

**Comment by rocksdanister** [comment]
Active Wallpaper(s) -> select screen 1 -> back to library -> select wallpaper.
Active Wallpaper(s) -> select screen 3 -> back to library -> select wallpaper.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/17554161/203815719-7d362e07-0f35-43e8-bf21-88b0685cdd65.png">

**Comment by techguyone** [comment]
Yea that's great, now try it with THREE screens and get it to do screen 1 & 3 only.
Pretty sure I mentioned 3 screens in the initial post. I'm aware that TWO screens is catered for.

This isn't completed.

--

Edited to add, it appears I'm an idiot, and I've got it to work, thank you.
