### ISSUE TITLE
Return from the screensaver to my desktop I get an error.

### ISSUE THREAD

**Issue by Stixz** [rocksdanister/lively#1472]
When I return from the screensaver to my desktop I get an error.

I am attaching log files.
[lively_log_20221124_084825.zip](https://github.com/rocksdanister/lively/files/10085091/lively_log_20221124_084825.zip)

**Comment by rocksdanister** [comment]
How did the error message look? was it a dialog?.. if so what did it say?

**Comment by Stixz** [comment]
No, it was a pop-up at the top of the app. I can't recall exactly what it
stated—something about being unable to load wallpaper due to an exception
error. I m running dual monitors, it was the secondary that failed to load.

**Comment by rocksdanister** [comment]
Try to see if you can reproduce (create the same error again.)
