### ISSUE TITLE
Any m3u8 support?

### ISSUE THREAD

**Issue by Not-a-Tyler** [rocksdanister/lively#1473]
Ive tried the solution in issue #341 but it doesn't seem to work and just gives me a white screen. The best solution i have found is using an online m3u8 player like [this player](https://bharadwajpro.github.io/m3u8-player/) but it seems to have its own issues because the live stream doesn't load in CefSharp and in WebView2 it loads but audio doesn't automatically cut off when another application is focused.

**Comment by rocksdanister** [comment]
Add youtube-dlp:
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper
