### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by BozaPng** [rocksdanister/lively#1474]
Describe the bug
Cant open,Not Responding

Screenshots/Video
![image](https://user-images.githubusercontent.com/94171769/204118461-9501c5ce-c174-4c7b-a148-c2a110118826.png)

Desktop (please complete the following information):

OS: . Windows 11 22H2
Graphic card: Nvidia 1660 Super
CPU: Intel Corei5-9400F
Ram : 16GB

Log file (Important)
Share the diagnostic files by:
[20221127_105118.txt](https://github.com/rocksdanister/lively/files/10097482/20221127_105118.txt)

**Comment by BozaPng** [comment]
[20221127_105118.txt](https://github.com/rocksdanister/lively/files/10097482/20221127_105118.txt)

**Comment by BozaPng** [comment]
![image](https://user-images.githubusercontent.com/94171769/204118461-9501c5ce-c174-4c7b-a148-c2a110118826.png)

**Comment by BozaPng** [comment]
Describe the bug
Cant open,Not Responding

Screenshots/Video
![image](https://user-images.githubusercontent.com/94171769/204118461-9501c5ce-c174-4c7b-a148-c2a110118826.png)


Desktop (please complete the following information):

OS: . Windows 11 22H2
Graphic card: Nvidia 1660 Super
CPU: Intel Corei5-9400F
Ram : 16GB

Log file (Important)
Share the diagnostic files by:
[20221127_105118.txt](https://github.com/rocksdanister/lively/files/10097482/20221127_105118.txt)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1369

**Comment by BozaPng** [comment]
![image](https://user-images.githubusercontent.com/94171769/204120277-e18e5049-5be3-4447-be81-36f2250085ca.png)

**Comment by BozaPng** [comment]
[20221127_105118.txt](https://github.com/rocksdanister/lively/files/10097570/20221127_105118.txt)
[20221127_111723.txt](https://github.com/rocksdanister/lively/files/10097571/20221127_111723.txt)
[20221127_112133.txt](https://github.com/rocksdanister/lively/files/10097572/20221127_112133.txt)
[20221127_121054.txt](https://github.com/rocksdanister/lively/files/10097573/20221127_121054.txt)

**Comment by rocksdanister** [comment]
I see that you where using v2.0.4.0 before updating to v2.0.5.0.. did it work before the update?

**Comment by BozaPng** [comment]
> I see that you where using v2.0.4.0 before updating to v2.0.5.0.. did it work before the update?

nah ,I just try to use older version to see will it fix. And didnt work :<

**Comment by rocksdanister** [comment]
Ah ok, try providing the dmp:
https://github.com/microsoft/WindowsAppSDK/issues/3037#issuecomment-1281612519

**Comment by BozaPng** [comment]
Microsoft (R) Windows Debugger Version 10.0.25200.1003 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Users\WIN10\AppData\Local\Programs\Lively Wallpaper\Plugins\UI\Lively.UI.WinUI.exe]

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00400000 00455000   C:\Users\WIN10\AppData\Local\Programs\Lively Wallpaper\Plugins\UI\Lively.UI.WinUI.exe
*** WARNING: Unable to verify checksum for Lively.UI.WinUI.exe
eax=00000000 ebx=00000000 ecx=00000000 edx=00000000 esi=00000000 edi=00000000
eip=00410440 esp=00000000 ebp=00000000 iopl=0         nv up di pl nz na po nc
cs=0000  ss=0000  ds=0000  es=0000  fs=0000  gs=0000             efl=00000000
Lively_UI_WinUI!__scrt_common_main [inlined in Lively_UI_WinUI!wmainCRTStartup]:
00410440 e80d060000      call    Lively_UI_WinUI!__security_init_cookie (00410a52)

**Comment by rocksdanister** [comment]
Upload the dmp file here https://github.com/microsoft/WindowsAppSDK/issues/3037

I am locking this as duplicate, can continue discussion https://github.com/rocksdanister/lively/issues/1369
