### ISSUE TITLE
不能幻灯片播放

### ISSUE THREAD

**Issue by xwzj14** [rocksdanister/lively#1475]
不能以幻灯片的形式播放壁纸，或许你们可以尝试设计一个与静态壁纸混用的方法，相信这可以使这个软件变得更受欢迎
Instead of playing wallpaper in slideshow, perhaps you can try to design a way to mix with static wallpaper，It is believed that this can make this software more popular

**Comment by rocksdanister** [comment]
Hi thanks for the suggestion, this feature is planned for 2.1 release and called playlist https://github.com/rocksdanister/lively/issues/137
