### ISSUE TITLE
Allow for more dynamic configuration of Web Wallpapers, including multiple CEF/WebView instances in a grid.

### ISSUE THREAD

**Issue by surfrock66** [rocksdanister/lively#1476]
My organization is seeking to create an "ActiveDesktop" style experience with multiple resources available on the desktop.  These are essentially websites such as Email, Calendar, Chat, etc., in a grid.  Lively Wallpaper is very close to this; we attempted to accomplish this by creating a web page with 4 iframes hosting the content.  Lively's piece works fantastic, however the targeted sites (in our case, Outlook 365 and Teams) prohibit embedding in frames.

Would it be possible to create a wallpaper/config where we could lay out multiple CEF rendering instances in a grid?  I don't think this needs to have a UI to configure; it's esoteric enough that delegating it to manually edited config files would be enough.

We have been perusing the source code to see if it's something we could patch it ourselves, but I think it's over our heads; we're not set up to compile C#.  This wouldn't need to be a core featured, but if it's something that could be implemented like a manual folder pasted into the "Library/wallpapers" folder with manually edited config files, that would be more than fine.

Mockup:
![image](https://user-images.githubusercontent.com/1345467/205398331-5ee5f3d5-571f-4618-879d-63819170efda.png)

**Comment by rocksdanister** [comment]
>My organization is seeking to create an "ActiveDesktop" style experience with multiple resources available on the desktop. These are essentially websites such as Email, Calendar, Chat, etc., in a grid. Lively Wallpaper is very close to this; we attempted to accomplish this by creating a web page with 4 iframes hosting the content. Lively's piece works fantastic, however the targeted sites (in our case, Outlook 365 and Teams) prohibit embedding in frames.

Is there any reason why this has to be wallpaper? making a bottom-most layered application is the easiest approach and will stay behind everything except desktop icons.

>Would it be possible to create a wallpaper/config where we could lay out multiple CEF rendering instances in a grid? I don't think this needs to have a UI to configure; it's esoteric enough that delegating it to manually edited config files would be enough.

Lively is not designed for this use and implementing it will be heavy work - adding 4 instances of chromium on same desktop, handling display settings changed event, forwarding mouse/keyboard input to each instance etc..

Easiest approach other than bottom-most layered would be to make an [application wallpaper](https://github.com/rocksdanister/lively/wiki/Application-Wallpaper) with that loads the 4 webpages and this will require no modification to Lively.

**Comment by surfrock66** [comment]
We've raised objections, but this is the desired experience by an executive at our org; he has fond memories of an ActiveDesktop type experience and wants that.  We brought up the premise that no one really sits looking at their desktop when doing productivity work...this is still the desired goal: a grid with Microsoft Teams, Outlook, a calendar, and a task tracker.  Given desktop widgets are poorly supported even barely at all again on Windows 11, we're just looking for anything here.

It's gonna be a performance nightmare.  But the exec gets what the exec wants.

I think I might be able to make the application wallpaper thing work; I hadn't seen that.  I'll play with it a bit tomorrow; my experience with lively is about 3 days old, so I'm sure I'll have some more questions; We don't have SCCM or anything, so even if we got this to work, I can't imagine installing it by doing it manually on ~300 computers, we'll need to come up with some sort of file tattooing of the profile; I figured out the structure (I think) for copying the wallpaper to user Local folders.

**Comment by surfrock66** [comment]
So for making an application wallpaper, I don't fully understand the syntax of the file, can it handle a grid, or would we need to find another application that supports opening laying out windows in a grid?

**Comment by rocksdanister** [comment]
Create an application that runs 4 WebView instance.

**Comment by surfrock66** [comment]
I've created an application with the 4 CEF instances, it's working well enough (with a lot of complications around popups for basic auth, etc.  This project is a mess).  I am having trouble though after I package it up for Lively, I seem to be able to get either the mouse working on the application, or the keyboard, but not both.  There isn't much debug info that's been helpful, do you have any recommendations for configurations in Lively that may help?
