### ISSUE TITLE
Windows 10 Enterprise LTSC 1809 not supported?

### ISSUE THREAD

**Issue by ebjordi** [rocksdanister/lively#148]
**Describe the bug**
Upon running the installer I get the error: "This program does not support the version of Windows your computer is running"

**To Reproduce**
Run the installer on a version of Windows 10 Enterprise LTSC 2019, either selecting english or spanish, and for either "this user" or "all users" 

What's missing in this version of windows for the program to work?

On an unrelated note, I can help with the Spanish translation if it is not finished.

**Expected behavior**
The program should install

**Comment by rocksdanister** [comment]
What is the windows build version? Lively require  [1903](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1903_(May_2019_Update)) or above.

Press the Win + R keys to open Run, type winver into Run, click on "OK" , it will show you the windows build version.

**Comment by ebjordi** [comment]
1809, that must be it

**Comment by rocksdanister** [comment]
Can you check if latest beta is working in 1809:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.9.4.6
