### ISSUE TITLE
Fluids V2 error message and not working

### ISSUE THREAD

**Issue by Synergy73** [rocksdanister/lively#149]
When I click on Fluids V2 it pops up with this error message:
![image](https://user-images.githubusercontent.com/51109901/94386158-53531300-018a-11eb-824f-c5fcf7d4eaa9.png)
this is the file thing:
![image](https://user-images.githubusercontent.com/51109901/94386259-87c6cf00-018a-11eb-9ff0-f8cef714fd77.png)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/32
https://github.com/rocksdanister/lively/wiki/Common-Problems
```
Web Audio Reactive wallpapers not working?
Open sound output properties
Open Advanced tab
In Signal Enhancements, uncheck Enable audio enhancements & apply.
```

Also I noticed you have multiple gpu, you may have to set lively plugins like livelycefsharp.exe to use dgpu instead of igpu.
