### ISSUE TITLE
Open new web windows in system browser 

### ISSUE THREAD

**Issue by ranmacar** [rocksdanister/lively#1491]
**Is your feature request related to a problem? Please describe.**
When links are configured to target a new window, it would be nice to open them in the default system browser

**Describe the solution you'd like**
Adding a new handler for webView.CoreWebView2.NewWindowRequested seems to work nicely, I've successfully built a version of the WV2 plugin.

**Comment by ranmacar** [comment]
Cool, thanks 😊

Is there also an example of how to build a custom installer somewhere? Didn't find it in the docs.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Building

https://github.com/rocksdanister/lively/issues/1271#issuecomment-1262170942

also CefSharp browser plugin(default) will behave same as WebView2 for parity reasons from next releases onwards.
