### ISSUE TITLE
NameNetCard

### ISSUE THREAD

**Issue by mrbreil** [rocksdanister/lively#1494]
Thank you very much for your lovely software. i have one qustion.
can you please tell how to change "NameNetCard" to a specific interface. I have wifi and lan in my pc.
Lovely show me wifi but i want lan.

**Comment by rocksdanister** [comment]
This is not possible currently, its set to read from the first card.

**Comment by rocksdanister** [comment]
discussion moved here: https://github.com/rocksdanister/lively/issues/1508
