### ISSUE TITLE
[FEATURE] Webpage Interaction adding a PlayPause Listener 

### ISSUE THREAD

**Issue by EnricoBaivo** [rocksdanister/lively#1499]
**Is your feature request related to a problem? Please describe.**
I wanted to make a enhanced web HTML Video player background player, but as i tryed to test the start stop functionalaty i spotted a bug.
After changing the focus to another window the draw engine prozess stops rendering the browser, but the video is actualy still playing and the sound is continuing. I have a few solutions in mind, but seedly they arent ready to use by lively. I tryed to figure out how to implement a fix, but i failed due to low knowlege in c# and missing documentations about the implementation of the csharp javascript function trigger

**Describe the solution you'd like**
provide a additonal javscript function trigger to control the webpage accordingly to the c# Play and Pause states.

Similar to:
function livelyPropertyListener(name, val)
{
    // or switch-case...
    if(name =="property1Class")
    {
      console.log(val); //43
    }
    else if(name =="color1Class")
    {
      console.log(val); //#C0C0C0
    }
}
Example Naming:
function livelyPlayingListener(isPlaying){}" 

**Additional context**
I could try to fix it on my own and then create a pull request, but i definitly need additional information how and where the 
function livelyPropertyListener(name, val) for the CefSharp prozess is implemented.

**Comment by rocksdanister** [comment]
There is no standard way to pause browser so currently the Chromium rendering process is stopped as a workaround (js script functions and other background tasks will still continue run.)

You can subscribe to pause event and handle additional scenarios:
https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data#--pause-event

**Comment by EnricoBaivo** [comment]
Hello Rocksdanister, 

im sorry that i diddnt saw that detail, that was the function i meant. 
Thanks for youre fast reply.

When i use the --system-nowplaying flag, lively shows a error msg. You can close the ticket afterwards.
..."Arguments": "--nowplaying"
Thanks for youre fast reply.

**For everyone else:**

it is nessesary to provide a LivelyProperties.json file in the src folder of the Webpage.
It needs following values:
"AppVersion"
"Title"
"Thumbnail"
"Preview"
"Desc"
"Author"
"License"
"Contact"
"Type"
"FileName"
"Arguments"
"IsAbsolutePath"
"Id"
"Tags"
"Version"

In the Arguments you need to set up the flags spezified in: https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data

**Comment by rocksdanister** [comment]
`--nowplaying` is not officialy released and will only work with WebView for now:
https://github.com/rocksdanister/lively/wiki/Web-Player#webview2-microsoft-edge

Don't create a new LivelyInfo.json, just download and install one of the sample projects and modify it instead.
