### ISSUE TITLE
Make Lively to change the static pc wallpaper for a better transision

### ISSUE THREAD

**Issue by Kronos2308** [rocksdanister/lively#150]
Make lively set the pc wallpaper to the first frame of the video
This way, a smooth transition is obtained when the pc is started or if it closes lively
a small function that should be included as optional in lively as a check box

this is a video that shows that function

- https://youtu.be/sidH2gNau0w

**Comment by rocksdanister** [comment]
What method did you use in the demo?
While using ffmpeg to extract the frame is easy, I want a single method that works with all types of wallpapers like Unity, webpages etc..

In the past when I tried to Screen capture non foreground window it did not workout:
https://github.com/rocksdanister/lively/blob/082bd13ac1286cbe094d6d84379e3bc408a9d676/src/livelywpf/livelywpf/Helpers/ScreenRecord/CaptureScreen.cs#L65

Suggestions are welcome.

**Comment by Kronos2308** [comment]
sorry i d'not touch the lively code,
 i am changing the wallpaper with a script and a key combo to make the video 

> 
> 
> What method did you use in the demo?
> While using ffmpeg to extract the frame is easy, I want a single method that works with all types of wallpapers like Unity, webpages etc..
> 
> In the past when I tried to Screen capture non foreground window it did not workout:
> 
> https://github.com/rocksdanister/lively/blob/082bd13ac1286cbe094d6d84379e3bc408a9d676/src/livelywpf/livelywpf/Helpers/ScreenRecord/CaptureScreen.cs#L65
> 
> Suggestions are welcome.

**Comment by Kronos2308** [comment]
wend lively create the preview on create a live-wallpaper can also create a image and store that in the live-wallpaper folder 
and  set that has pc-wallpaper on select that live-wallpaper ?

**Comment by rocksdanister** [comment]
Preview size is small ~384x216

**Comment by Kronos2308** [comment]
is posible to make a single shoot on 1280x720
an then make the preview?
or make the preview in 1280x720 save to folder-wallpaper and then scale that to 384x216 for preview ?
> 
> 
> Preview size is small ~384x216

**Comment by rocksdanister** [comment]
It is possible after creating preview to just move the wallpaper window outside of screen region, resize from 384x216 -> 1280x720 -> capture thumbnail -> set as wallpaper.

Not pretty though, If I could capture non-foreground window, I can just do the screen capture after setting it as wallpaper.
I have seen option to capture non-foreground window in OBS application, maybe should have a look.

**Comment by camblomquist** [comment]
If you haven't looked yet, OBS is using GDI to blit the content of an arbitrary window. GDI exposes this fairly easily and painlessly but this feature does not exist at all in DXGI. I apologize that I do not remember anything more specific.

The other route that OBS takes with window capture is through [screen capture API](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture) introduced as part of UWP. When recording video, this has a side effect of outlining the captured window with a horrendously ugly yellow border. For screenshots though, I do not know if this is the case or if it would be an issue since it would only happen for a single frame.

My only concern with the whole idea is when wallpapers use randomness, there's no? control over the seed which would mean that the static would look very different. This is still preferable to the empty void though.

**Comment by rocksdanister** [comment]
>My only concern with the whole idea is when wallpapers use randomness, there's no? control over the seed which would mean that the static would look very different. This is still preferable to the empty void though.

I think you are confusing this one with the blackscreen when browser is minimized https://github.com/rocksdanister/lively/issues/20

**Comment by rocksdanister** [comment]
Managed to capture non foreground window: 
```cs
        const int SRCCOPY = 0x00CC0020;
        const int CAPTUREBLT = 0x40000000;

        public static Bitmap CaptureWindow(IntPtr hWnd)
        {
            GetWindowRect(hWnd, out RECT rect);
            var region = Rectangle.FromLTRB(rect.Left, rect.Top, rect.Right, rect.Bottom);

            IntPtr winDc;
            IntPtr memoryDc;
            IntPtr bitmap;
            IntPtr oldBitmap;
            bool success;
            Bitmap result;

            winDc = GetWindowDC(hWnd);
            memoryDc = CreateCompatibleDC(winDc);
            bitmap = CreateCompatibleBitmap(winDc, region.Width, region.Height);
            oldBitmap = SelectObject(memoryDc, bitmap);

            success = BitBlt(memoryDc, 0, 0, region.Width, region.Height, winDc, region.Left, region.Top, SRCCOPY | CAPTUREBLT);

            try
            {
                if (!success)
                {
                    throw new Win32Exception();
                }

                result = Image.FromHbitmap(bitmap);
            }
            finally
            {
                SelectObject(memoryDc, oldBitmap);
                DeleteObject(bitmap);
                DeleteDC(memoryDc);
                ReleaseDC(hWnd, winDc);
            }
            return result;
        }
```
~~but not working for intended use case - when given the handle of the wallpaper window its capturing the original desktop wallpaper in a distorted manner instead; need to look into it.~~
Capture works for wmf videoplayer, but not for libmpv.

**Comment by rocksdanister** [comment]
Doing custom implementation for each wallpaper plugin, mpv player and uwp gif player will be supported initially next update.

https://user-images.githubusercontent.com/17554161/117567668-b7ec2e00-b0da-11eb-9231-db1a14eaede2.mp4

**Comment by Kronos2308** [comment]
nice
