### ISSUE TITLE
Black Screen and not responding

### ISSUE THREAD

**Issue by skymissblueboy** [rocksdanister/lively#1505]
**Describe the bug**
When opening its just a black screen and not responding.

**To Reproduce**
Open the program.

**Picture**

![image](https://user-images.githubusercontent.com/73062671/209425464-fe9477b7-b03f-4f32-99e0-b64399586d2c.png)

Desktop
Windows 21H2

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1369
