### ISSUE TITLE
Exception: WallpaperPluginException

### ISSUE THREAD

**Issue by bouissou** [rocksdanister/lively#1506]
I can't apply any wallpaper, not even the default ones. It's a shame cause it used to work neat in both default and custom wallpapers. 

When I select any wallpaper the following message prompts: 

![Untitled](https://user-images.githubusercontent.com/113589148/209581435-563628e0-0f6b-4371-9eb8-926431420f0e.png)

I tried both reinstalling and reinstalling after disabling my antivirus, and it didn't work either case.

Log file:

[lively_log_20221226_170644.zip](https://github.com/rocksdanister/lively/files/10304723/lively_log_20221226_170644.zip)

Windows 10 Pro, 22H2

**Comment by rocksdanister** [comment]
What anti-virus software do you use? if its some third party tool I would check its quarantine for Lively files.

**Comment by bouissou** [comment]
>What anti-virus software do you use?
windows defender
>if its some third party tool I would check its quarantine for Lively files.
there's no file quarantined

**Comment by rocksdanister** [comment]
Check the browsers log:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Cef\logfile.txt`

If it was working before and stopped working now then it has to be some external factor🤔

**Comment by orrinpants** [comment]
> Check the browsers log: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Cef\logfile.txt`
> 
> If it was working before and stopped working now then it has to be some external factor🤔

There's no folder named "Lively Wallpaper" that's **DIRECTLY** in the Local folder
