### ISSUE TITLE
Livelycu.exe Command Line Utility flagged for malware

### ISSUE THREAD

**Issue by Akinus** [rocksdanister/lively#1507]
I am trying to download and use the lively command line utility but it keeps getting flagged as Malware. I ran an online analysis of it:

https://www.hybrid-analysis.com/sample/39b74812b6c736a45eb7ab5037aa953930ba34413e7f2d730e73068bc9b5763d

I am almost positive that this is simply because it recognizes the .exe as a command line utility, but I wanted to write this in here to make sure that your file has not been compromised. 

If you can confirm it has not, I look very much forward to using the command line utility, because sending the commands to the program reacts slower than I'd like (as you mentioned in the wiki).

**Comment by rocksdanister** [comment]
Its mostly heuristics false detection, I check with Windows defender only and have reported to Microsoft in the past:
https://www.virustotal.com/gui/file/39b74812b6c736a45eb7ab5037aa953930ba34413e7f2d730e73068bc9b5763d

There is no centralized way of submitting files to all AV vendors, you can submit:
https://www.autohotkey.com/boards/viewtopic.php?t=62266

**Comment by Akinus** [comment]
You rock, and I LOVE your program.  Thank you for the quick response!
