### ISSUE TITLE
Lively library showing up blank when opened

### ISSUE THREAD

**Issue by ArtLvl5** [rocksdanister/lively#1513]
**Describe the bug**
When I open the app, the gallery is showing blank. I have restarted the app, as well as the pc multiple times to no avail.

**To Reproduce**
1. Go to 'file location'
2. Click on 'Lively Wallpaper app'

**Expected behavior**
Upon opening the app, the gallery with default and added wallpapers should pop up.

**Screenshots/Video**
![Lively Wallpaper 12_31_2022 5_56_41 AM](https://user-images.githubusercontent.com/121716557/210134243-2e98d4d9-9f8b-4949-8eea-1e0c1f68b3aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Running Wallpaper: Cloud Girl HD Live Wallpaper

**Additional context**

**Log file (Important)**
[lively_log_20221231_060055.zip](https://github.com/rocksdanister/lively/files/10327202/lively_log_20221231_060055.zip)

**Comment by rocksdanister** [comment]
Logs don't say much here.. maybe you installed both the installer and store version of Lively by mistake?

**Comment by ArtLvl5** [comment]
Thanks for responding. Unistalling and reinstalling via Microsoft store seems to have fixed the issue. it may have been caused by a driver update or somesuch, since I had a lot of those recently.
