### ISSUE TITLE
Error initializing device: AUDCLNT_E_DEVICE_IN_USE (0x8889000a) (MPV)

### ISSUE THREAD

**Issue by Nova1ite** [rocksdanister/lively#1514]
**Describe the bug**
Cannot load wallpaper due to "WallpaperPluginException"
There's two other reports about this, but no one sent a log yet.

**To Reproduce**
1. Open Lively and Selected Wallpaper

**Expected behavior**
Wallpaper should apply to desktop

**Screenshots/Video**
![Screenshot_20221231_025735](https://user-images.githubusercontent.com/115776661/210157115-5766753c-b6fa-4fae-8408-e928a47cdecd.png)
![Screenshot_20221231_025742](https://user-images.githubusercontent.com/115776661/210157116-3b60fcfc-fa8c-4bdc-929c-a40e0793439f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 10.0.22621
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Looks like mpv is failing to initialize audio, try disabling audio by following these steps:
Create the file mpv.conf in any of the following location:

`<Lively install location>\plugins\mpv\portable_config\mpv.conf`

OR

Installer: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Mpv\portable_config\`

Windows store: `%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Mpv\portable_config\`

mpv.conf:
```
--aid=no
```

**Comment by Nova1ite** [comment]
Thanks, works fine now
