### ISSUE TITLE
Web wallpaper defaulting to resolution of primary screen, not filling multi-screen area

### ISSUE THREAD

**Issue by HaLo2FrEeEk** [rocksdanister/lively#1518]
**Describe the bug**
I have 3 screens. 2 are 1080p and 1 is a 4K TV, they're oriented with the 1080p monitors centered under the 4K TV, so the total resolution is 3840x3240. The primary screen is one of the 1080p ones. When I first start Lively, my custom web wallpaper spans across the screens as it should, but it seems if I change the screen settings, and occasionally on initial boot, the wallpaper only fills a 1920x1080 area, in the top corner of the 4K TV. Screenshots below.

When this happens, it seems to be only for this wallpaper. Changing to a different one correctly displays full screens, but changing back, this particular one is still wrong. The only way I can fix it is to close Lively and restart it.

**To Reproduce**
(You'll need to have multiple screens to reproduce)

1. Have Lively open, set to display wallpapers spanning across screens.
2. Download the "Starfield.zip" file and import it into Lively.
[Starfield.zip](https://github.com/rocksdanister/lively/files/10333844/Starfield.zip)
 (this is a custom javascript animation that I wrote, it's terrible, don't judge me it's a work in progress)
3. Select the newly-imported Starfield animation
4. It *should* only appear on one, or a portion, of the screens.
5. Right click the taskbar icon and exit Lively.
6. Wait a few seconds, then start Lively again, the animation *should* span across all screens.

Once you've restarted and the animation spans the screens, if you change the screen settings to "selected screen only" then back to "span across screens", for me at least this also produces the issue.

**Expected behavior**
I feel like since the wallpaper spans the screens most of the time (and on program start) it should do it all the time.

**Screenshots/Video**
Incorrect:
![incorrect](https://user-images.githubusercontent.com/2855829/210286130-98e6ac2b-9368-4aca-a260-1f024bb062c2.png)

Expected:
![correct](https://user-images.githubusercontent.com/2855829/210286131-b3d775db-bf32-4157-b6b1-da52e5f4b297.png)

**Desktop:**
 - OS: Windows 10 Enterprise 22H2 (19045.2364)
 - Starfield (custom web wallpaper)

**Additional context**
I really hope it's not just something in my code...in the meantime I'll have a look at the code and see if there's anything I can do to make this not happen. I don't see it with other web wallpapers (like the WebGL demo). If it does end up being my fault, you can just close the issue and I'll get the message and sorry for having wasted your time :/

**Log file (Important)**
[lively_log_20230102_154901.zip](https://github.com/rocksdanister/lively/files/10333854/lively_log_20230102_154901.zip)

**Comment by rocksdanister** [comment]
Try reloading the page when Lively resizes the page:
```js
window.onresize=()=>{
    location.reload();
}
```

**Comment by HaLo2FrEeEk** [comment]
I'm using the p5.js framework, there's a function called "windowResized" that resizes the canvas, that should have caught it.

I weighed the options and figured that in most cases I'm not going to be resizing the page much, so I did like you suggested and that seems to have fixed it. Still weird that the existing code didn't catch it.

**Comment by HaLo2FrEeEk** [comment]
I guess that didn't actually fix it. It works most of the time, but not every time. It seems now that if I load the wallpaper and it *doesn't* work, I wait for 5 seconds or so and load it again and it usually works.

Update: I even changed it to this:

`window.setTimeout(() => location.reload(), 2000);`

And it still sizes incorrectly sometimes, and never reloads. The canvas is sized to windowWidth and windowHeight on setup, so it seems like Lively isn't sending or setting the correct width and height values.

**Comment by HaLo2FrEeEk** [comment]
I figured it out. For whatever reason the p5.js shorthands windowWidth/windowHeight were the culprit. If I use window.innerWidth/innerHeight then it worked, so....
