### ISSUE TITLE
The taskbar disappears

### ISSUE THREAD

**Issue by qdesjo** [rocksdanister/lively#1519]
I have instaled lively and activated the dev option, in settings.

But after the update, my taskbar constantly disappears and the icons apears juste when I passe the mouse on it.

So if you have a solution or questions, I'm here ! I precise I'm on dev canal on Windows Insiders Program.
You have some screenshots of the pins applications that aren'nt here and of my Windows version, just up of the date/hour.

![Uploading Capture d’écran (757).png…]()
![Capture d’écran (758)](https://user-images.githubusercontent.com/76106684/210400879-a85157b8-50a2-4178-95c2-c3b45c636444.png)

**Comment by qdesjo** [comment]
![Capture d’écran (757)](https://user-images.githubusercontent.com/76106684/210401370-fe8c0fce-69d9-415e-9f37-b89b055046f5.png)
And the second screenshot

**Comment by rocksdanister** [comment]
I don't understand the problem from seeing the screenshot, if you taskbar theme turned ON in Lively then try turning it OFF?

**Comment by qdesjo** [comment]
I have no more problems, I don't know what hapenned, but everything is clean now !
