### ISSUE TITLE
Hardware monitoring wallpaper api

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#152]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/17554161/96139664-b2e84700-0f1c-11eb-9472-748af14cb279.gif)

**Is your feature request related to a problem? Please describe.**
It would be nice to have system information such as cpu, gpu, memory usage and name available to website wallpapers.
This can allow developers to create more dynamic website wallpapers.

**Describe the solution you'd like**
Using C# Performance Counters it is possible to retrieve resource usage real-time.

**Describe alternatives you've considered**
Program wallpapers (.exe) can have their own implementation.
Website wallpapers don't have access to such information.

**Additional context**
Only information that does not require administrator rights to access are considered.
Only turned on if specified by the wallpaper maker.
No information that can be used to identify the user is collected.

**API documentation**
https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data

**Early working demo**
https://youtu.be/B-9g92ixmm0

**Sample wallpaper project**
https://github.com/rocksdanister/system-stats-wallpaper

**Comment by rocksdanister** [comment]
Discussion is up https://github.com/rocksdanister/lively/discussions/233
(Why didn't I just post it here instead? no idea..)

**Comment by vinod-unny** [comment]
How do I change/select a different network card to display data out of? Currently it seems to take the first or Wifi card only. I have a 1Gbps connection via Ethernet and would like to show that instead.

**Comment by rocksdanister** [comment]
Its something planned, currently only 1 gpu, cpu , network card is available.

**Comment by vinod-unny** [comment]
Thanks. Excellent app btw. Learning its API to make some custom backgrounds. Will look forward for this update.

**Comment by Simplygamedeveloper** [comment]
I was having some problem with the functioning and I saw many people in this problem that the zip file they download and open through lively wallpapers was not working but I found this simple solution to just restart the pc and it'll work nicely.

**Comment by SLEEPD2** [comment]
Any news on additions to the render? Such as personalizing the gpu and such?

**Comment by rocksdanister** [comment]
@SLEEPD2 What do you mean by personalizing gpu?
