### ISSUE TITLE
Lively wallpaper in taskbar option clear, blur etc. options are not working in my laptop window 11 

### ISSUE THREAD

**Issue by AdityaHACK123** [rocksdanister/lively#1526]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Yes, Windows 11 changed the taskbar recently and will require an update for it.

Closing this for now.

**Comment by AdityaHACK123** [comment]
ok
