### ISSUE TITLE
Wallpaper is not pausing while using discord in maximized window

### ISSUE THREAD

**Issue by Naaveen-Kumar** [rocksdanister/lively#1527]
**Describe the bug**
Wallpaper is not pausing while using discord in maximized window, even though I have the settings enabled and discord being added to the application list.

**To Reproduce**
1. Go to 'Settings -> Performance'
2. Click on 'Application fullscreen -> Pause' 'Application focused -> Pause'
3. Click on 'Application rules -> + -> add Discord'
4. Open discord and maximize the wondow.

**Expected behavior**
Wallpaper should pause.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
- Which wallpaper was running at the time if any. - Fluids

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20230112_132832.zip](https://github.com/rocksdanister/lively/files/10399334/lively_log_20230112_132832.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/789#issuecomment-1148548562

**Comment by Naaveen-Kumar** [comment]
Thank you, the fix provided in the old issue worked.
