### ISSUE TITLE
Stdin write fail: Cannot access a disposed object. Object name: 'System.Diagnostics.Process'.

### ISSUE THREAD

**Issue by Overnox** [rocksdanister/lively#1529]
Can u help please, its only on the Fluids with Lively Wallpaper will not working on Windows 11. Thanks

[lively_log_20230112_142128.zip](https://github.com/PavelDoGreat/WebGL-Fluid-Simulation/files/10403236/lively_log_20230112_142128.zip)

**Comment by rocksdanister** [comment]
What anti-virus software do you use? check the quarantine because looks like something is killing the browser.

**Comment by Overnox** [comment]
Hi Dani John,
I use Eset Internet Security. The funny thing is that the other wallpapers work. the fluid wallpaper also worked once in the beginning. Unfortunately, after I tried all the others, the fluid no longer worked. I think that's the prettiest one.

**Comment by rocksdanister** [comment]
>The funny thing is that the other wallpapers work. the fluid wallpaper also worked once in the beginning.

Yes because Eset's behaviour analysis likely flagged it, check its quarantine and report it as false positive or mail them:
https://www.autohotkey.com/boards/viewtopic.php?t=62266

& add exception/uninstall the av software and reinstall Lively.

**Comment by Overnox** [comment]
After i delete ESET for trying. I have the same Problem. Can u help? Do u have any other idea?

**Comment by rocksdanister** [comment]
Uninstall and reinstall Lively after deleting ESET?
