### ISSUE TITLE
Fluids v2 failing to launch

### ISSUE THREAD

**Issue by rosegayming** [rocksdanister/lively#153]
**Describe the bug**
Fluids v2 fails to load when selected in lively

**To Reproduce**
Attempt to set the Fluids v2 default wallpaper in Lively

**Expected behavior**
Fluids v2 is set as wallpaper

**Desktop (please complete the following information):**
 - OS: Windows 1909
- Which wallpaper was running at the time if any: Does not affect issue

**Log file**
[20201003_154309.txt](https://hastebin.com/uhuxowitac.rb)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/149
https://github.com/rocksdanister/lively/issues/32
