### ISSUE TITLE
i have glitch in live wallpaper on the right side corner

### ISSUE THREAD

**Issue by hideandseekstheorder** [rocksdanister/lively#1531]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/24226435/212540053-2b6d23fd-e37e-4e23-8e3c-df217361f6b6.png">

on 2560x1440 laptop

**Comment by hideandseekstheorder** [comment]
it is the red light
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/24226435/212540135-d0f64d25-6488-4750-a040-ed42cd1185fc.png">

**Comment by rocksdanister** [comment]
Share the logfile zip (settings - system - log)

Why is it red? Is your desktop wallpaper red on the right side?
