### ISSUE TITLE
AudiOrbits Wallpaper Not Working With WebView2

### ISSUE THREAD

**Issue by y0himba** [rocksdanister/lively#1532]
**Describe the bug**
AudiOrbits works with Cefsharp but produces a white screen with WebView2, others work without issue. 

**To Reproduce**
1. Install `AudiOrbits Wallpaper`
2. Go to '`Main Page`'
3. Click on '`AudiOrbits`'
4. Wallpaper doesn't start, crashes instantly.

**Expected behavior**
AudiOrbits should work as if using CefSharp

**Screenshots/Video**
Attached video shows issue.  `WebView2` is selected. 

**Desktop (please complete the following information):**
 -Microsoft Windows [Version 10.0.19045.2486]
- Only applies to `AudiOrbits
`
**Additional context**
AudiOrbits works swimmingly once I switch back to CefSharp

**Log file (Important)**

https://user-images.githubusercontent.com/11462603/212604067-7576ecd0-db5a-4b98-8493-31541b85889a.mp4

[20230116_000227.txt](https://github.com/rocksdanister/lively/files/10422728/20230116_000227.txt)
[20230116_000923.txt](https://github.com/rocksdanister/lively/files/10422729/20230116_000923.txt)
[20230115_235719.txt](https://github.com/rocksdanister/lively/files/10422730/20230115_235719.txt)

**Comment by rocksdanister** [comment]
Its a CORS issue, closing as duplicate: https://github.com/rocksdanister/lively/issues/1160

Is there any reason you are using WebView instead of default CefSharp?

**Comment by y0himba** [comment]
> Its a CORS issue, closing as duplicate: #1160
> 
> Is there any reason you are using WebView instead of default CefSharp?

I have a lot of Cefsharp instances, trying to eliminate a many as I can for resources. I guess it from the old days of computing when multitaking was a chore and running processes in the background slowed a PC considerably. Or OCD. Or old age....

Thanks for the information.
