### ISSUE TITLE
Lock Screen Customisation

### ISSUE THREAD

**Issue by YellowMouse07** [rocksdanister/lively#1533]
**Is your feature request related to a problem? Please describe.**
I don't like that the lock screen customization was removed in the update
**Describe the solution you'd like**
Please bring back lock screen live wallpaper enable toggle
**Describe alternatives you've considered**
Nope
**Additional context**
Add any other context or screenshots/mockups about the feature request here.
Nope

**Comment by rocksdanister** [comment]
closing as duplicate: https://github.com/rocksdanister/lively/issues/537
