### ISSUE TITLE
Lively can't set .mp4 wallpaper

### ISSUE THREAD

**Issue by MalyshkinMike** [rocksdanister/lively#1539]
**Describe the bug**
WallpaperPluginExeption appears while i try to set an .mp4 file as a wallpaper

**To Reproduce**
1. Go to add wallpaper
2. Add an mp4 file (or select any added mp4 wallpaper)
3. Try to set it as your wallpaper (or just wait if you just added some fiile)

**Expected behavior**
Changing my desktop wallpaper to selected

**Desktop (please complete the following information):**
 - OS: Windows 19045.2486
- no wallpaper was set

[lively_log_20230124_212229.zip](https://github.com/rocksdanister/lively/files/10492638/lively_log_20230124_212229.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1514
