### ISSUE TITLE
"WallpaperPluginException" when trying to apply any wallpaper

### ISSUE THREAD

**Issue by defautluser0** [rocksdanister/lively#1546]
**Describe the bug**
I try to set the wallpaper and it gives me exception "wallpaperpluginexception", I try to preview and it doesn't load. it happens with simulation wallpapers.

**To Reproduce**
1. Go to the wallpaper section
2. Click on any simulation wallpaper
3. See error above

**Expected behavior**
I Expected it to apply the wallpaper.

**Screenshots/Video**
![asdf](https://user-images.githubusercontent.com/108409246/215285468-e9969e6c-aee7-44e9-b22f-313b30df9913.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 1903]

**Log file**
[log.txt](https://github.com/rocksdanister/lively/files/10528021/log.txt)

**Comment by rocksdanister** [comment]
The log is saying the webbrowser used for rendering the wallpaper is just crashing.. do you use any third party antivirus software which may have deleted the files?

**Comment by defautluser0** [comment]
> The log is saying the webbrowser used for rendering the wallpaper is just crashing.. do you use any third party antivirus software which may have deleted the files?

no, but just downloading vcredist newest it worked again

**Comment by rocksdanister** [comment]
weird.. the installer should deal with installing vcredist.

**Comment by defautluser0** [comment]
it did install but not the newest...?

**Comment by rocksdanister** [comment]
It's Installing (provided you don't cancel the UAC prompt.) 2019 which is whats needed:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/17554161/219511291-d1fd25b1-7643-4074-b7fc-1c2eb5d85c60.png">

https://github.com/cefsharp/CefSharp/issues/3636

Did you by chance install from Chocolatey?

**Comment by rocksdanister** [comment]
I removed the dependency skipping just in case https://github.com/rocksdanister/lively/commit/01077e1fa5994ffff2527cfd9da6aa7606bc28d5

**Comment by defautluser0** [comment]
> It's Installing (provided you don't cancel the UAC prompt.) 2019 which is whats needed: <img alt="image" width="241" src="https://user-images.githubusercontent.com/17554161/219511291-d1fd25b1-7643-4074-b7fc-1c2eb5d85c60.png">
> 
> [cefsharp/CefSharp#3636](https://github.com/cefsharp/CefSharp/issues/3636)
> 
> Did you by chance install from Chocolatey?

i didnt cancel the uac prompt and what is chocolatey
