### ISSUE TITLE
Selecting Clear Taskbar problem.

### ISSUE THREAD

**Issue by jvhellraiser** [rocksdanister/lively#1549]
**Describe the bug**
In settings once you have select transparencies for Taskbar to be clear
even know it is enable in windows 11 when you click on start button
you can still see the color taskbar for a few seconds after it goes back 
being clear.

**To Reproduce**
1. select any Live wallpaper 
2. go to configure/System/Taskbar Theme
3. Select Clear as the main theme for the Taskbar
4. once you have select it the Taskbar to be clear click
start button a couple of times and stay looking at the taskbar
you will see sometimes is fully clear and other you can see windows 11 taskbar pop-up

**Expected behavior**
you will see that even know the clear taskbar is select you can still see windows 11 taskbar from time to time.

**Screenshots/Video**
https://user-images.githubusercontent.com/16488761/216631882-cfbcbd4c-5dfc-4fd0-94ea-19cbbc3486f3.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Build 22621
- you can try with fluids live wallpaper but it happens on any live wallpaper.

**Additional context**
this happens not only  on clear in the others too.

**Log file (Important)**
[lively_log_20230203_104949.zip](https://github.com/rocksdanister/lively/files/10579967/lively_log_20230203_104949.zip)
not sure how the log will help since there no crash but you guys know more than me.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1041
