### ISSUE TITLE
Lively will not open or uninstall

### ISSUE THREAD

**Issue by Aisanuchiha** [rocksdanister/lively#155]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file**
Share the crashlog file logfile.txt from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs with detailed information (The file gets overwritten each time lively starts, so make sure its from when lively crashed.)

**Comment by rocksdanister** [comment]
Nice template.
What exactly happened when you tried running the Uninstaller?
