### ISSUE TITLE
IPFS URL Support

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#1551]
**Is your feature request related to a problem? Please describe.**
Currently IPFS links are unable to load related images. An error message displays instead of the attached image's preview.
Displayed error: "Unable to load webpage: ERR_UNKNOWN_URL_SCHEME"

**Describe the solution you'd like**
Images/gifs defined at an IPFS URL location should work the same as HTTP/S locations.

**Comment by ghost** [comment]
Example
This url will redirect (assuming a browser with IPFS)
ipfs://QmVYZmbY45xSKoUBSuVSo3nnjkQmHbrarbwsxiVR4MeB9C

To the image .png location found here:
https://bafybeidlb4yvkhjepeb426pqspyger67cmtf2ocx4wmykq2r37a2j7igfm.ipfs.dweb.link/

**Comment by ghost** [comment]
Seems like this would require detecting the ipfs prefix, and then modifying the URL to begin with `https://ipfs.io/ipfs/` instead of `ipfs://`

IE:
https://ipfs.io/ipfs/QmVYZmbY45xSKoUBSuVSo3nnjkQmHbrarbwsxiVR4MeB9C


https://docs.ipfs.tech/how-to/address-ipfs-on-web/#dweb-addressing-in-brief

**Comment by rocksdanister** [comment]
Can you give me a use case for this or what will you use this for?

**Comment by ghost** [comment]
It would make it easier to display a bunch of dynamic NFTs as backgrounds.
Though, being honest the work around or updating the ipfs link is easy
enough where it may not be worth the dev effort

**Comment by rocksdanister** [comment]
Yeah I think that's for the best, personally I don't like NFTs and don't want Lively associated with it.
