### ISSUE TITLE
Screen saver without wallpaper setting (or, for example, a different wallpaper) and without starting Lively

### ISSUE THREAD

**Issue by TesterEU** [rocksdanister/lively#1554]
Hi,
I found the screen saver functionality in Lively on the site: https://github.com/rocksdanister/lively/wiki/Screen-Saver
The add-on has limited features (was that the goal?). I'd like to use a static pic on desktop (family photo) and video in screen saver. My reason is simple. I wouldn't to separate with my live Wallpaper (video). I'm not a programmer and I don't have IT skills (can't determine the difficulty), so I decided to write here. Is there someone who can program this screensaver function in Lively?

I also have a weak integrated GPU and just only screensaver itself consumes my resources at 40% of the GPU (thankfully screen saver run sometimes)

ps. I lost a lot of time looking for an alternative program and found something like this: https://sourceforge.net/projects/videosaver/
Unfortunately but my live wallpaper looks awful when it isn't full screen ("videosaver" add bar at the top and bottom).

I would appreciate your response and interest
Thanks :)

**Comment by rocksdanister** [comment]
Lively started as a live wallpaper application and add-on was developed on user request, so yes its currently limited.

There is plan in the future to have screensaver separate from wallpaper https://github.com/rocksdanister/lively/issues/587

Closing this as duplicate since an issue already exists.
