### ISSUE TITLE
Wallpapers are not working for me 

### ISSUE THREAD

**Issue by Ofkd637** [rocksdanister/lively#1559]
hey , i have an issue with lively wallpaper, when i open any wallpapers on this app its not working on my desktop unless i put go to the windows setting and change the wallpaper type from pictures to solid color and then it starts working , like the animated pictures works but it doesnt work at any other times and i dont know why i have to turn on the set  a picture of animated wallpaper as desktop wallpaper then i have to go to windows setting and do what i told you , i would be greatful if you guys help me thanks

**Comment by rocksdanister** [comment]
Do you have any desktop modification software installed like Stardock Fences etc?

**Comment by Ofkd637** [comment]
Hey Yes I do have fences installed to arrange my application's icon

**Comment by rocksdanister** [comment]
Its a compatibility issue, should work with Fences closed.
