### ISSUE TITLE
Live Youtube videos - not working.

### ISSUE THREAD

**Issue by dshort99** [rocksdanister/lively#1564]
Hi,

Great program, you guys are brilliant. 

Live Youtube videos do not work with Lively anymore, they just throw back 'unknown error'; works perfectly fine with non live videos. 

Please fix! Thanks!

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#updating-youtube-dl

**Comment by dshort99** [comment]
Thanks mate! Working!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
