### ISSUE TITLE
Wallpapers overlapping when exiting screensaver

### ISSUE THREAD

**Issue by Shodwriter** [rocksdanister/lively#1566]
**The bug:**
For context, I have 3 monitors: two 1080p monitors of the same brand and one 1440p monitor in the middle (the main monitor) of a different brand to the 1080p monitors. When the screensaver is turned on after 15 minutes, waking the computer up from the screensaver glitches out the lively wallpapers as one of the lively wallpapers is placed onto the main monitor, overlapping them. To fix the issue, I have to reapply the lively wallpapers to each screen.

**To reproduce:**
With two 1080p monitors of the same brand and one 1440p monitor of a different brand:
1. Set the two 1080p monitors to have a lively wallpaper
2. Set the 1440p monitor to have a different lively wallpaper
3. Wait for screensaver to turn on
4. Exit screensaver
5. The issue occurs

**Expected behaviour:**
The lively wallpapers should be placed onto the correct screens instead of overlapping.

**Desktop:**
OS: Windows 10 Home 22H2 Build 19045.2486
The wallpapers running were the matrix wallpapers and a Ryzen wallpaper which I imported from deviant art, but the issue happens with other wallpapers as well.

**Screenshot:**
![image](https://user-images.githubusercontent.com/93199403/218335930-6d3b6948-d8d2-4ca7-8673-c22a34638e68.png)

**Additional Context:**
I think the reason this is happening is because the main monitor (the 1440p one) is of a different brand to the two 1080p monitors, and it takes longer for the monitor to turn on from screensaver. Additionally, I tested the issue when the screensaver was set to 1 minute, and the issue did not occur. In fact, the screensaver was set to the lively wallpapers that time; but when it is set to 15 minutes, the screensaver is black.

**Log file:**
[lively_log_20230212_204021.zip](https://github.com/rocksdanister/lively/files/10717237/lively_log_20230212_204021.zip)

**Comment by rocksdanister** [comment]
1. What are the resolution scales of the monitors? can you try reproducing the bug when its all set to 100%
2. What display connectors the monitors are using? if any are using displayport can you try switching to hdmi and try to reproduce.
3. Can you reproduce this bug with 2 monitors?

**Comment by Shodwriter** [comment]
> 1. What are the resolution scales of the monitors? can you try reproducing the bug when its all set to 100%
> 2. What display connectors the monitors are using? if any are using displayport can you try switching to hdmi and try to reproduce.
> 3. Can you reproduce this bug with 2 monitors?

1. The resolution scales of the monitors are 100%
2. I am using display port but I unfortunately can't try and reproduce the issue using HDMI because my GPU only has one HDMI port.
3. This issue does not happen with 2 monitors, at least from what I've tested. I will note that turning on the main 1440p monitor after the test also glitched out the wallpapers again, as seen below:
![image](https://user-images.githubusercontent.com/93199403/219182623-1436d41c-2563-4e98-86aa-809e92b16c19.png)
