### ISSUE TITLE
It does not work lively with W10 20H2

### ISSUE THREAD

**Issue by Manantonio0** [rocksdanister/lively#157]
Hi.
A few days ago my Windows 10 was updated to version 20H2 compilation of OS 19042.546 and since then it has not worked for me lively.
I get a message in which it tells me to configure a series of things that I already have configured and it also tells me that in some compilations of W10 insider it might not work, but in the previous compilation, before the update I was already an insider and if it works and very good also.
I have looked for solutions on github and I have not found anything similar to this problem, that's why I write to you from here.
Could there be any solution on that issue?
I am attaching a screenshot where the message can be seen and that I have everything it asks for well configured and the latest log files of the program..
If you need anything else, do not hesitate to ask me.
Regards, and thank you very much.

![lively](https://user-images.githubusercontent.com/72508571/95344714-38834b80-08ba-11eb-81b4-d9c590bd1f78.png)
[20201007_031125.txt](https://github.com/rocksdanister/lively/files/5341459/20201007_031125.txt)
[20201007_031324.txt](https://github.com/rocksdanister/lively/files/5341460/20201007_031324.txt)
[20201007_031403.txt](https://github.com/rocksdanister/lively/files/5341461/20201007_031403.txt)
[20201007_032600.txt](https://github.com/rocksdanister/lively/files/5341462/20201007_032600.txt)

**Comment by rocksdanister** [comment]
Can you follow this instruction instead under "Windows settings" section:
https://github.com/rocksdanister/lively/wiki/Getting-Started

**Comment by Manantonio0** [comment]
Hello again.
I am attaching a report of the hardware of my computer, in addition to a screenshot of my desktop, which I have been using as you see it for about 5 months and everything was perfect until 3 days ago that windows were updated.
And I already uninstalled the application and reinstalled it, I already modified all the windows performance settings in several possible ways, and that message box continues to appear and it is clear that it is from the last windows update, because besides I I'm an insider, which is probably for that reason.
[Desktop.zip](https://github.com/rocksdanister/lively/files/5342995/Desktop.zip)
[DxDiag.txt](https://github.com/rocksdanister/lively/files/5342998/DxDiag.txt)

**Comment by rocksdanister** [comment]
Insider builds are very different from final and  in the past it stopped working in certain build. 

You can verify this by seeing if there is transition animation when changing wallpaper in windows. 

I'm just going to wait and see how this turns out for now. 

Sadly your options are to downgrade/let Microsoft know of this issue directly through feedback hub.

**Comment by Manantonio0** [comment]
OK thank you very much.
Yes, I had just thought that, speak directly with Microsoft and explain the problem to see what they can do.

Well, I repeat, thank you very much.

**Comment by rocksdanister** [comment]
Just tested on my system, working fine Windows 10 20H2 stable release.
