### ISSUE TITLE
WallpaperPluginException for stream wallpaper

### ISSUE THREAD

**Issue by nshirogane** [rocksdanister/lively#1572]
Despite having an updated version of youtube-dl, Lively Wallpaper refuses to load any video or live stream of any sort. However, pre-existing wallpapers such as the fluid simulation work as intended. Reinstalling both youtube-dl and Lively Wallpaper don't seem to be doing anything either.
OS: Windows 10 22H2
Log file: [lively_log_20230217_184100.zip](https://github.com/rocksdanister/lively/files/10772400/lively_log_20230217_184100.zip)
![image](https://user-images.githubusercontent.com/118144036/219816913-5f6c566b-241d-4c87-9d20-614560ca4e95.png)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/1570#issuecomment-1434535226
