### ISSUE TITLE
Installer setup not closing, stuck on installing .Net Core 7.0.0

### ISSUE THREAD

**Issue by mwa2** [rocksdanister/lively#1574]
I downloaded lively wallpaper yesterday. It was working fine until this thing popped up saying setup, I was setting it up fine then I went through it, and it said extracting files and such. It stopped at the end and said "Installing  ".Net Core 7.0.0" and it has been like that for the past 24 hours and I do not know what to do!!!

![2023-02-20](https://user-images.githubusercontent.com/125856758/220033439-d03008e4-dac9-4a94-903e-5b7ffe5d2c88.png)

**Comment by rocksdanister** [comment]
From which website did you download lively wallpaper?

**Comment by mwa2** [comment]
https://downloads.digitaltrends.com/lively-wallpaper/windows/post-download

**Comment by mwa2** [comment]
i try to click the X and delete the file but it just won't work.

**Comment by rocksdanister** [comment]
> https://downloads.digitaltrends.com/lively-wallpaper/windows/post-download

This is very old version, Lively official website is: https://www.rocksdanister.com/lively/

> i try to click the X and delete the file but it just won't work.

Try this method:
https://www.howtogeek.com/700000/how-to-end-a-task-using-windows-10s-task-manager/

Its stuck for some reason, regardless ending the task linked above or restarting the system will close it.
