### ISSUE TITLE
taskbar theming bug

### ISSUE THREAD

**Issue by sidd1908** [rocksdanister/lively#1578]
taskbar not working in windows 11 latest insider build 2263.1325
I'm from India , i don't know whether its because of the time zone or the bug on the app

![bug rep](https://user-images.githubusercontent.com/67094540/220409327-ad99d2b0-892f-4f66-ac7c-106dd51ba601.png)

**Comment by Sachinanand99** [comment]
Same here, with insider build, this option is not working properly.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/1440
