### ISSUE TITLE
Web wallpapers dont work

### ISSUE THREAD

**Issue by yaboisid** [rocksdanister/lively#1579]
**Describe the bug**
I'm trying to use the new audio visualiser wallpapers, but they won't work. Editing the wallpaper makes the Lively app crash.

**Expected behavior**
Expected to see the wallpaper working.

**Screenshots/Video**

https://user-images.githubusercontent.com/17554161/220537308-8f827584-5f74-4b20-8eb9-32d0565167ab.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Log file (Important)**
[lively_log_20230222_111814.zip](https://github.com/rocksdanister/lively/files/10800474/lively_log_20230222_111814.zip)

**Comment by rocksdanister** [comment]
Do other web wallpapers work? (Example matrix)

**Comment by yaboisid** [comment]
> Do other web wallpapers work? (Example matrix)

Nope. Not working

**Comment by rocksdanister** [comment]
Which anti-virus program do you use? check its quarantine to see if it deleted any Lively files.

**Comment by rocksdanister** [comment]
Also try installing this:
https://github.com/rocksdanister/lively/wiki/Common-Problems#web-wallpapers-not-working

**Comment by yaboisid** [comment]
> Which anti-virus program do you use? check its quarantine to see if it deleted any Lively files.

I use Microsoft Defender, and no quarantined files.

> Also try installing this: https://github.com/rocksdanister/lively/wiki/Common-Problems#web-wallpapers-not-working

I have that already installed

**Comment by rocksdanister** [comment]
Try updating to latest visual c++:
https://aka.ms/vs/17/release/vc_redist.x86.exe

Also share the logfile.txt located at:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Cef`

**Comment by yaboisid** [comment]
> 

I have the latest version of C++ already installed. Log file are attached with the reply.
[lively_log_20230222_120106.zip](https://github.com/rocksdanister/lively/files/10800681/lively_log_20230222_120106.zip)

**Comment by rocksdanister** [comment]
It won't include browsers log, its located at: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Cef`

**Comment by yaboisid** [comment]
[logfile.txt](https://github.com/rocksdanister/lively/files/10800721/logfile.txt)

**Comment by rocksdanister** [comment]
Not much to see, can you check your `System Event Viewer` for `LivelyCefSharp` and `CefSharp.BrowserSubProcess` application error messages? what does it say.

**Comment by yaboisid** [comment]
Yes, there are some errors.
Faulting application name: Lively.PlayerCefSharp.exe, version: 1.0.0.0, time stamp: 0xace5bcfb
Faulting module name: libcef.dll, version: 108.4.13.0, time stamp: 0x63976dec
Exception code: 0xc0000005
Fault offset: 0x01974c00
Faulting process ID: 0x0x2880
Faulting application start time: 0x0x1D94684247105B9
Faulting application path: C:\Program Files (x86)\Lively Wallpaper\plugins\cef\Lively.PlayerCefSharp.exe
Faulting module path: C:\Program Files (x86)\Lively Wallpaper\plugins\cef\libcef.dll
Report ID: de0ad3c1-d060-4b51-8996-d63f89d408a3
Faulting package full name:

**Comment by rocksdanister** [comment]
Can you try replacing the contents of this folder: 

`<Lively install location>\plugins\cef\`

With each of these releases, then try running the wallpaper each time:
1. https://github.com/rocksdanister/lively-cef/releases/tag/v1.6.0.0
2. https://github.com/rocksdanister/lively-cef/releases/tag/v1.7.0.0
3. https://github.com/rocksdanister/lively-cef/releases/tag/v1.5.5.0

**Comment by yaboisid** [comment]
Works now with v1.7.0.0 version. Thanks!

**Comment by rocksdanister** [comment]
Hi can you check (1) and (3) also?

**Comment by yaboisid** [comment]
1 and 3 doesn't wok for me.

**Comment by rocksdanister** [comment]
@amaitland any clue whats happening? looks like older builds of CefSharp are failing for some users.

**Comment by CrippledAxis** [comment]
Works fine now! Thanks!
I used [v1.7.0.0]

**Comment by amaitland** [comment]
> [0222/113855.197:WARNING:alloy_constrained_window_views_client.cc(63)] No likely focused browser

This was a [known bug](https://bitbucket.org/chromiumembedded/cef/issues/3434/cef-108-creates-web-data-and-web-data) in `108` when no cache path was specified and application was installed in readonly folder. See https://magpcss.org/ceforum/viewtopic.php?f=6&t=19318 for related discussion

Should be fixed in [v109.1.110](https://github.com/cefsharp/CefSharp/releases/tag/v109.1.110) or greater. 

`109` is the last version to run on `Windows 7/8/8.1`.

**Comment by rocksdanister** [comment]
Ah that makes sense, I did not do admin install tests.. all my tests were on AppData and not program files!

~Weird the Windows store version did not have this issue though (packaged using msix)~ Nevermind.. its using older version before the issue.
