### ISSUE TITLE
Wallpaper Not Working

### ISSUE THREAD

**Issue by CrippledAxis** [rocksdanister/lively#1581]
[lively_log_20230222_210011.zip](https://github.com/rocksdanister/lively/files/10804012/lively_log_20230222_210011.zip)

**Describe the bug**
Doesn't work at all after the update. It says "Oops.. Looks like something went wrong :( In order to better understand this error and fix the issue, share the log file with the developer.

ExceptionL WallpaperPluginException

**To Reproduce**

**Expected behavior**
Just at least work upon loggin in

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/126079519/220627262-cfdeaad0-a10f-43b2-a8d2-0adab6ab3ebf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
- Which wallpaper was running at the time if any. ALL

**Log file (Important)**
Share the diagnostic files by:
[lively_log_20230222_210011.zip](https://github.com/rocksdanister/lively/files/10804029/lively_log_20230222_210011.zip)

**Comment by rocksdanister** [comment]
maybe https://github.com/rocksdanister/lively/issues/1579#issuecomment-1439625263
