### ISSUE TITLE
Cannot Set Wallpaper

### ISSUE THREAD

**Issue by PeriyaThala09** [rocksdanister/lively#1582]
**Describe the bug**
I can't set any wallpaper via Lively Wallpaper app

**To Reproduce**
1. Open Lively Wallpaper
2. Select any wallpaper and click set as wallpaper
3. See error

**Expected behavior**
Should set as wallpaper

**Desktop (please complete the following information):**
 - OS: [Windows 10 22H2]

**Additional context**
Actually i wanted to set music tv wallpaper as desktop wallpaper but i can't set and the app is respond abit slow rather than old version

**Log file (Important)**
[lively_log_20230222_220917.zip](https://github.com/rocksdanister/lively/files/10805036/lively_log_20230222_220917.zip)

**Comment by rocksdanister** [comment]
maybe https://github.com/rocksdanister/lively/issues/1579#issuecomment-1439625263

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/releases/tag/v2.0.6.1
