### ISSUE TITLE
Too tall/long wallpaper interface

### ISSUE THREAD

**Issue by Pomper29** [rocksdanister/lively#1587]
When i use a customized wallpaper its too long... probably its because my pc but, if its posible, can you guys try to help on that issue?

**Comment by rocksdanister** [comment]
I don't understand, maybe show a screenshot with steps to reproduce the issue?

**Comment by Pomper29** [comment]
ok. this is an animation of a guy spining. its too long
![Captura de pantalla 2023-02-24 161408](https://user-images.githubusercontent.com/126208343/221215044-58db3bd8-96a5-4948-bf05-263481082a5d.png)

**Comment by rocksdanister** [comment]
Try changing the video scaler: Lively settings -> Wallpaper -> Choose a fit
