### ISSUE TITLE
Audio fades when not focusing on wallpaper

### ISSUE THREAD

**Issue by RanzerScore90** [rocksdanister/lively#1589]
I don't like it how the audio turns off immediately as soon as you stop focusing on the wallpaper, I would like it if the audio would fade as you switch to a window or stop focusing on the wallpaper, and maybe even have a slider that changes how slow/fast the audio fades when you stop focusing.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/661
