### ISSUE TITLE
Dangerous Fake Repo found.

### ISSUE THREAD

**Issue by CatWithCode** [rocksdanister/lively#1591]
There is an GitHub Repo by another user that seems to be a virus.

It is the first thing showing up when searching for lively wallpaper on DuckDuckGo and Google sometimes.

(The "-" are for safety so no ones exadently clicks it and downloads the wrong thing by accident).
h-t-t-p-s:-/-/-g-i-t-h-u-b-.-c-o-m-/-L-i-v-e-l-y-W-a-l-l-p-a-p-e-r-/-l-i-v-e-l-y-

There seems to be a chain of scripts downloading a virus:
h-t-t-p-s-:-/-/-g-i-t-h-u-b-.-c-o-m-/-L-i-v-e-l-y-W-a-l-l-p-a-p-e-r-/-l-i-v-e-l-y-/-i-s-s-u-e-s-/-4

If I'm wrong or misinterpreted something please just delete this.

**Comment by rocksdanister** [comment]
I am aware, you can try reporting the profile (using any github name like LivelyWallpaper is allowed but you can't distribute malware.)

Looking at the numbers almost 500 people downloaded from there:
https://tooomm.github.io/github-release-stats/?username=livelywallpaper&repository=lively
