### ISSUE TITLE
Video Unavailable when using YT video as Wallpaper

### ISSUE THREAD

**Issue by SlimBones** [rocksdanister/lively#1596]
**Describe the bug**
**It's been awhile since I've used Lively, was attempting to make a YT video my background, when I paste link, it responds with Video Unavailable. The background is blank/black with no sound. I have read threads and tried a few different things, but they have not worked.** 
**To Reproduce**
**Add wallpaper>Enter url>Unavailable**
**Expected behavior**
**The YouTube video I selected to be my desktop wallpaper**
**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![Library 2_26_2023 9_58_24 PM](https://user-images.githubusercontent.com/126437415/221471128-76ba321c-3645-4c73-b6af-9f6c160d3544.png)
![Screenshot 2_26_2023 9_57_44 PM](https://user-images.githubusercontent.com/126437415/221471153-6f9aefa1-58eb-4657-ad0b-47ab3cc10d95.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.
**OS: Windows 10**
**Additional context**
**N/A**
**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20230226_215543.zip](https://github.com/rocksdanister/lively/files/10835912/lively_log_20230226_215543.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#updating-youtube-dl

**Comment by SlimBones** [comment]
I actually cannot find Lively file location at all. Would the steps be different if I downloaded from Microsoft store? Thank you for quick reply btw

**Comment by SlimBones** [comment]
Followed steps, now seeing this

![Lively Wallpaper 2_26_2023 10_42_58 PM](https://user-images.githubusercontent.com/126437415/221476206-87e533b5-c679-47b5-8c20-6dd631edb356.png)


> https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#updating-youtube-dl

**Comment by rocksdanister** [comment]
The original error means the uploader disabled embedded, the new error means the player is crashing.. probably yt-dlp related issue.

If it's not a live stream it's better to just download the file using third party tools and add the file as wallpaper.

**Comment by SlimBones** [comment]
> The original error means the uploader disabled embedded, the new error means the player is crashing.. probably yt-dlp related issue.
> 
> If it's not a live stream it's better to just download the file using third party tools and add the file as wallpaper.

Sounds good, I appreciate the assistance and the timely responses.
