### ISSUE TITLE
Avast flagging CefSharp as IDP.Generic

### ISSUE THREAD

**Issue by mine-rp** [rocksdanister/lively#1601]
![image](https://user-images.githubusercontent.com/72818301/222427223-1325536e-79ec-490a-8485-ca7cdd45adae.png)
????????????????????????

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/358

When creating a github issue the basic decency is to give it a proper title and description; I take my personal time to help the community for free..
