### ISSUE TITLE
app crashes when trying to customize wallpaper

### ISSUE THREAD

**Issue by thaynos** [rocksdanister/lively#1607]
**Describe the bug**
when trying to customize a wallpaper the app just crashes randomly, i even reinstalled the program to no avail....

**To Reproduce**
click on customize button in context menu

**Expected behavior**
open customize menu

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
20h2

[lively_log_20230304_004212.zip](https://github.com/rocksdanister/lively/files/10885950/lively_log_20230304_004212.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1496
