### ISSUE TITLE
Update did a clean installation

### ISSUE THREAD

**Issue by marinosGR** [rocksdanister/lively#1608]
**Describe the bug**
I was using the version 2.0.5.0 and today I saw a message for a new update (2.0.6.1). I clicked the link for more info that led me to github. I downloaded and run the update and a message appeared that I should close the program and then click ok. I misread it and I thought that it would close the program, so I just clicked ok. It reappeared so I closed the program and after the installation finished, all my settings were reset. No active wallpaper was set anymore, neither the taskbar theme, and the list of wallpapers had only the default ones. I clicked to check the default themes' directory, since I had them there, and everything I added was gone.

**To Reproduce**
1. Update (?)

**Expected behavior**
The program to update without deleting settings and etc.

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
- Which wallpaper was running at the time if any: a video file

**Additional context**

**Log file (Important)**

> 2023-03-04 14:10:46.4354|INFO|Lively.App|
> 
> Lively v2.0.6.1 x64 desktop-native en-US
> OS: Microsoft Windows 11 Education 10.0.22000
> CPU: AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx
> GPU: AMD Radeon(TM) RX Vega 10 Graphics
> GPU: NVIDIA GeForce GTX 1050
> 
> 2023-03-04 14:10:47.0763|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\[my user folder]\AppData\Local\Lively Wallpaper\Settings.json'.
> File name: 'C:\Users\[my user folder]\AppData\Local\Lively Wallpaper\Settings.json'
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
>    at System.IO.File.OpenText(String path)
>    at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
>    at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 109
> 2023-03-04 14:10:47.6015|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\[my user folder]\AppData\Local\Lively Wallpaper\AppRules.json'.
> File name: 'C:\Users\[my user folder]\AppData\Local\Lively Wallpaper\AppRules.json'
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
>    at System.IO.File.OpenText(String path)
>    at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
>    at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 123
> 2023-03-04 14:10:47.6241|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\[my user folder]\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
> File name: 'C:\Users\[my user folder]\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
>    at System.IO.File.OpenText(String path)
>    at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
>    at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 140
> 2023-03-04 14:11:40.3674|INFO|Lively.App|AppUpdate status: uptodate
>

**Comment by CMoltedo** [comment]
I think this may be related to installations not in the default directory.  When I did the update, it prompted for install for just my user or all users, I chose all users, and it didn't ask where the folder was, it just automatically started installing to C:\Program Files\.    Is there a way to do the update and have it use the existing installation folder?

**Comment by rocksdanister** [comment]
Closing this issue since the old version of software no longer supported.

@CMoltedo
The prompt during update is only due to switching to x64 and its a one time thing.
If you select the correct current install mode (admin or not) then it will uninstall the old version correctly.
`Program Files` is the admin install location for Windows.

Lively settings and wallpapers are in Local AppData and install location has no effect on this:
https://github.com/rocksdanister/lively/wiki/Getting-Started#storage
