### ISSUE TITLE
Process exited before giving HWND

### ISSUE THREAD

**Issue by RoyceNeon** [rocksdanister/lively#1614]
[20230309_223141.txt](https://github.com/rocksdanister/lively/files/10934184/20230309_223141.txt)

**Comment by rocksdanister** [comment]
Browser for webpage wallpaper is crashing, possible causes and solution:
1. Missing Visual C++ Redistributable runtime, try installing: https://github.com/rocksdanister/lively/wiki/Common-Problems#web-wallpapers-not-working
2. If you use any third party Anti-virus software, check its quarantine to see if it deleted any Lively files.. if so report it as false positive and remove from quarantine: https://www.autohotkey.com/boards/viewtopic.php?t=62266

**Comment by pareta2** [comment]
Another reason could be you are not placing Release mode compiled plugins in Plugin folder.
Follow the link below and use release mode all files....
https://github.com/rocksdanister/lively/wiki/Building
