### ISSUE TITLE
Access to the path is denied

### ISSUE THREAD

**Issue by lesterlloyd** [rocksdanister/lively#1615]
**Describe the bug**
I have tried to place wallpapers in all ways and nothing happens, and when I drag the wallpapers I get an error alert, I downloaded the app from the Microsoft Store and already tried to delete the app and reinstall and still the same error.

**To Reproduce**
1. I cant drop or open to upload a file

**Expected behavior**
I want to upload a wallpaper

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/31058115/224129060-17cfc5bc-64fd-4ab9-83bd-ed246acf59e9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
- Which wallpaper was running at the time if any. none

**Additional context**
After installing the .exe and the app from Microsoft still cannot drop or upload any file on it

**Log file (Important)**
Share the diagnostic files by: My Log ZIP is empty

**Comment by rocksdanister** [comment]
The error message is saying Lively is not able to write to TEMP folder in your system, I do not know why this is happening as it is unusual.

Few reasons I could think of:
1. Third party Anti-virus or software is blocking (Lively is only tested with Microsoft Security.)
2. Corrupted or modified Windows installation.
3. Lack of free space on TEMP folder.

What I am confused here is after that error message Lively will exit and stop launching, so how are you able to access the UI to try adding wallpaper?

**Comment by lesterlloyd** [comment]
> 
I've already tried installing and uninstalling the app into the older version v2.0.6.0 but the same error occurred. If I run the Lively as admin it will bring me to the UI but can't add wallpapers
![image](https://user-images.githubusercontent.com/31058115/224309347-83b7f6aa-9ab0-4800-956d-617042d2662a.png)
![image](https://user-images.githubusercontent.com/31058115/224309429-7ebe2ff9-7361-4714-b5e8-cddbb548eb73.png)

**Comment by rocksdanister** [comment]
Yes Dialogs don't work in admin mode, that's a separate issue.

So this is a permission issue..
Are you running it as TITS user? as far as I am aware TEMP folder don't need admin rights.. what happens when you try creating a folder in TEMP using file explorer?

**Comment by lesterlloyd** [comment]
> Yes Dialogs don't work in admin mode, that's a separate issue.
> 
> So this is a permission issue.. Are you running it as TITS user? as far as I am aware TEMP folder don't need admin rights.. what happens when you try creating a folder in TEMP using file explorer?

It's working now. I just open the TEMP folder created by Lively. It just required permission and needed to confirm on it. Thank you!
