### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by Oofin77** [rocksdanister/lively#162]
Greetings,
I have searched in the "Issues" founded nothing :/

I am getting an error saying that the "Application haven't succesfully started" :(
Edit: Error Code saying: (0xc00000e5)

Lively Wallpaper is started automaticly in startup.
After it started I am getting a black screen then I see a message saying "Application haven't succesfully started"

Normally it would work like always. (Seeing my nice animated wallpaper :D 

 - OS: 2004
- Fluids v2 (Don't work with all except the one I made)

[20201015_192101.txt](https://github.com/rocksdanister/lively/files/5388382/20201015_192101.txt)

Thanks for you quick reply ( Please :c )

**Comment by rocksdanister** [comment]
So the issue is only with "Fluid v2"?
Could be this https://github.com/rocksdanister/lively/issues/153
