### ISSUE TITLE
my lively wallpaper is not responding 

### ISSUE THREAD

**Issue by limentix** [rocksdanister/lively#1620]
my lively wallpaper is not responding 
![image](https://user-images.githubusercontent.com/127653862/224532506-3768949a-4c23-4ed2-95fb-228f470d3137.png)
[20230312_144958.txt](https://github.com/rocksdanister/lively/files/10950287/20230312_144958.txt)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1369

**Comment by limentix** [comment]
> duplicate: #1369 
this my viewer log i don't know how to coutinue
![image](https://user-images.githubusercontent.com/127653862/224538296-15af7238-58ba-4859-99d8-d9747f7ed6f6.png)

**Comment by limentix** [comment]
i'm newcomer for this website , i confuse what should i do fix the problem as told in the other mention

**Comment by rocksdanister** [comment]
Unfortunately there is no fix at the moment.

**Comment by limentix** [comment]
> Unfortunately there is no fix at the moment.

thank you

**Comment by limentix** [comment]
uptdate i try back to old version. it's work !!

**Comment by rocksdanister** [comment]
Which version?

**Comment by limentix** [comment]
it v 2.0.2.2
