### ISSUE TITLE
Wallpaper plugin exception

### ISSUE THREAD

**Issue by BigStank11** [rocksdanister/lively#1622]
**Describe the bug**
Unable to use any wallpapers, selecting any of them results in a "WallpaperPluginException", photo attached. 

**To Reproduce**
1. Open Lively wallpaper
2. Click on a wallpaper
3. See error

**Expected behavior**
A wallpaper should be applied

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/36094681/224873976-59a5a8af-b3c9-4c73-a906-e99a0f1c40d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2

**Additional context**
Only using Windows Defender, tried disabling real time protection anyway, no change.

**Log file (Important)**

[20230314_145835.txt](https://github.com/rocksdanister/lively/files/10963516/20230314_145835.txt)

**Comment by rocksdanister** [comment]
```
2023-03-14 14:58:35.4867|INFO|Lively.App|
Lively v2.0.6.1 x64 desktop-native en-US
OS: Microsoft Windows 11 Home 10.0.22621
CPU: 12th Gen Intel(R) Core(TM) i7-12700H
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
GPU: Intel(R) Iris(R) Xe Graphics
```

Try installing [Visual C++ Redistributable](https://github.com/rocksdanister/lively/wiki/Common-Problems#web-wallpapers-not-working)

**Comment by rocksdanister** [comment]
Share the CefSharp logfile from this folder: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Cef`

**Comment by BigStank11** [comment]
> Try installing [Visual C++ Redistributable](https://github.com/rocksdanister/lively/wiki/Common-Problems#web-wallpapers-not-working)

That fixed it, thank you!
