### ISSUE TITLE
Duplicating wallpaper across two screens

### ISSUE THREAD

**Issue by AndrewTu11** [rocksdanister/lively#1623]
**Describe the bug**
When trying to select two different wallpapers for two different screens, duplicated wallpaper across both screens even when "Selected screen only" is selected.

**To Reproduce**
Unsure

**Expected behavior**
When selecting a screen for a certain wallpaper, that wallpaper being assigned to that screen only

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2

**Additional context**
There seems to be broad issues specifically when trying to use moving/video wallpapers with two screens

**Log file (Important)**
[lively_log_20230313_204339.zip](https://github.com/rocksdanister/lively/files/10964011/lively_log_20230313_204339.zip)

**Comment by rocksdanister** [comment]
I dont understand, share a step by step video reproducing/showing the issue.
