### ISSUE TITLE
Wallpaper FPS Drop

### ISSUE THREAD

**Issue by PickleLikesPizza** [rocksdanister/lively#1624]
**Describe the bug**
My computer had to get a reset (So I lost all of my stuff except for anything in my OneDrive), and I wanted to reinstall Lively (Since it's cool and all)
Everything went well until I tried to open a wallpaper. I added a wallpaper called 25th Hour (You can find it at https://louie.co.nz/25th_hour/), which opened, but it appeared to lag. I think I got around 1.5 FPS, and at first I thought it might be a problem with the wallpaper I inserted. So I tried using the TV wallpaper, and it also lagged! I tried just closing the app and trying to reopen it, but the same thing happened. Looking at Task Manager, everything appeared to be fine with the running of the computer.
Everything else seems to be working, so it appears to be concentrated within Lively itself.
**To reproduce**
Honestly, I'm not fully sure, since it my just be my app specifically.
**Expected behavior**
It should run smoothly, and shouldn't lag out.
**Desktop**
OS: Windows 11
Medusae (Was trying the other wallpapers to see if any of them worked)
**Log file (Important)**
[lively_log_20230313_211017.zip](https://github.com/rocksdanister/lively/files/10964035/lively_log_20230313_211017.zip)
If anybody has any ideas, please let me know.
This 1 FPS is slightly painful.

**Comment by rocksdanister** [comment]
25th hour does some calculation initially and its normal.

Music TV may require a dedicated GPU for smooth functioning.

Its best to stick with video wallpapers for intel igpu systems, further read:
https://github.com/rocksdanister/lively/wiki/Performance
