### ISSUE TITLE
An error occurred while trying to debug the program

### ISSUE THREAD

**Issue by CookingWine** [rocksdanister/lively#1625]
https://github.com/rocksdanister/lively/wiki
EXCEPTION:
An error occurred trying to start process
D:\NETProject\C#\lively-core-separation\src\Lively\Lively\bbin\Debug\n
et7.0-windows10.0.18362\plugins\UI\Lively.UI.WinUI.exe' wiith working
directory
ID:\NETProject\C#\lively-core-separation\'src\Lively\Lively\bin/Debug\n
et7.0-windows10.0.18362\plugins\UI'.系统找不到指定的文件。

This error was displayed as soon as I started the program

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Building
