### ISSUE TITLE
Screensaver not stopping on touch input

### ISSUE THREAD

**Issue by csar8594** [rocksdanister/lively#1636]
When ussing the Lively Screensaver on a touchscreen only device, it does not stop when touching the screen.

Only way to stop it on a touch only device is to swipe from the right into the middle of the screen to open the Notification Center on Windows 10 and then click in the middle of the screen.

For me it seems like a keyboard/mouse is necessary - maybe this can get fixed.

**Comment by rocksdanister** [comment]
Eh.. Yes I am only listening for mouse/keyboard inputs to exit screensaver.

Will need to look into adding touch support, have you tried accessing the on screen keyboard?

**Comment by csar8594** [comment]
Would be nice if you add the touch screen support -- unfortunately, the on screen keyboard is not accessible iin the time during showing the screensaver.
