### ISSUE TITLE
Screensaver blackscreen every minute for half a second

### ISSUE THREAD

**Issue by csar8594** [rocksdanister/lively#1637]
I came a across another bug where the screensaver turns into a black screen for about half a second exactly every minute.

On my screensaver I'm showing a website with live elements which are all working perfectly (I thought it might be a website error) but the whole screen turns black.

**Comment by rocksdanister** [comment]
Share the logs and steps to reproduce the issue:

https://github.com/rocksdanister/lively/wiki/Common-Problems#having-a-problem-how-do-i-get-help--how-to-retrieve-log-files

**Comment by csar8594** [comment]
**Of course, the log file:**
[lively_log_20230321_170947.zip](https://github.com/rocksdanister/lively/files/11030905/lively_log_20230321_170947.zip)

**The steps to reproduce:**
Basically i have just set a website i host internally as a wallpaper and also as a screensaver. When the screen switches over to the screensaver after 1 min, it keeps displaying the content for exactly 1 minute and then turns into a black screen for half a second and it keeps on going in this loop.
