### ISSUE TITLE
Use on dual monitors?

### ISSUE THREAD

**Issue by BreezeDog420** [rocksdanister/lively#1639]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by BreezeDog420** [comment]
Can this be extended onto dual monitors or am I stuck with it on just one?

**Comment by rocksdanister** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/17554161/227066480-ed49ee29-343b-4ce4-9334-dabfc593a32f.png">

**Comment by BreezeDog420** [comment]
Nice job with this software and thanks for the help with my overlooked dual screen button lol.
