### ISSUE TITLE
Contributing file

### ISSUE THREAD

**Issue by nithssh** [rocksdanister/lively#164]
I understand that this is kind of a personal project for you, but have you considered adding a contributing file to the repo, and direct potential contributors to the issues page or telling them what sort of contributions are needed right now.

This is a great project and you've done a fantastic job btw!

**Comment by rocksdanister** [comment]
Why did you close it?

I did write it briefly in the wiki:
https://github.com/rocksdanister/lively/wiki/Contributing-Guidelines

I don't have any particular requirements, any PR are welcome as long as its commented and explained properly.

**Comment by nithssh** [comment]
Oh yes, I discovered that you had a active wiki with a section about contributing in your readme linking to it, that's why I closed it as I realized I was being blind 😅
