### ISSUE TITLE
Changing between live wallpapers

### ISSUE THREAD

**Issue by vansmack** [rocksdanister/lively#1643]
I would love to have a feature to where Lively Wallpaper would be able to automatically change between different live wallpapers similar to how slide shows can be done with static wallpapers if this is possible. If it can be implemented then being able to choose which wallpapers to have in the changing wallpaper list and for how long each would run before change would be great.

I am not a programmer, so a big thanks to all the programmers that bring us these open source programs.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/137
