### ISSUE TITLE
Rain wallpaper has bugs after a time

### ISSUE THREAD

**Issue by perroboc** [rocksdanister/lively#1644]
**Describe the bug**
The rain desktop wallpaper appears to show some artifacts after quite some time (a day or two?). A "refresh" by changing the wallpaper and back seems to fix the issue.

**To Reproduce**
1. Set the rain wallpaper
2. Wait a day or two?
3. See error

**Expected behavior**
No artifacts should appear, rain drops should be consistent

**Screenshots/Video**

https://user-images.githubusercontent.com/2722773/227958500-84952a82-782d-4ab0-83c8-e7367d3e02ee.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 (10.0.22621 Build 22621)
- Which wallpaper was running at the time if any: Rain

**Additional context**
AMD Radeon 7900 XTX, latest drivers (23.3.2)

**Log file (Important)**
[lively_log_20230327_105218.zip](https://github.com/rocksdanister/lively/files/11079345/lively_log_20230327_105218.zip)

**Comment by rocksdanister** [comment]
Try the latest release:
https://github.com/rocksdanister/rain/releases/tag/v3

I believe its because of the time variable value becoming large, should be fixed in this release (its reset every 6hr.)
