### ISSUE TITLE
Lively always uninstalls the latest update

### ISSUE THREAD

**Issue by hacshacdgacs** [rocksdanister/lively#1647]
**Describe the bug**
Every system startup Lively is having to reinstall the latest update.

**To Reproduce**
1. Install the latest update.
2. Restart System
3. Lively will no longer be up to date and will need to install the latest update again

**Expected behavior**
Lively to stay up to date

**Desktop (please complete the following information):**
 - OS: Windows 10 19045
- Parallax & Media Parallax

**Log file (Important)**
[lively_log_20230328_114422.zip](https://github.com/rocksdanister/lively/files/11083566/lively_log_20230328_114422.zip)

**Comment by rocksdanister** [comment]
First time hearing of this.. somethings off here.

For the time being you can try the Microsoft store version:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions

Will reopen if issue also happens with store version.

**Comment by hacshacdgacs** [comment]
Issue persists on the store version also
[lively_log_20230405_122840.zip](https://github.com/rocksdanister/lively/files/11154130/lively_log_20230405_122840.zip)

**Comment by rocksdanister** [comment]
The store is using Microsoft's latest updating methods (msix).. this is likely due to something on your system, can't help much here.

@sylveon any idea?

**Comment by rocksdanister** [comment]
The store version of Lively does not prompt for updates, its done via the Microsoft Store app.. if you are getting the update prompt then need to uninstall the installer version of Lively first.
