### ISSUE TITLE
Many wallpapers do not work properly with WebView2.

### ISSUE THREAD

**Issue by Gopro3010** [rocksdanister/lively#1649]
**Describe the bug**
Using WebView2, many wallpapers like Music TV or Waves do not work. The screen is blank.

**To Reproduce**
1. Using the Github version, install WebView2 plugin.
2. Go to settings --> Wallpapers --> Web Browser.
3. Select "WebView2" option.
4. Select a wallpaper like MusicTV or Waves.
5. See error

**Expected behavior**
The background is supposed to have been reproduced normally, as with CefSharp.

**Additional:**
The error only sometimes happens, and with different wallpapers. It does not always happen with the same background.

**Desktop:**
 - OS: Windows 11 22H2
- In different wallpapers; Music TV, Waves, Ferrari 458, etc...

**Log file**
[20230328_185109.txt](https://github.com/rocksdanister/lively/files/11092509/20230328_185109.txt)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1160
