### ISSUE TITLE
The application does not want to fire up its own wallpapers or even unpack them

### ISSUE THREAD

**Issue by Iwo2002** [rocksdanister/lively#165]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file**
Share the log file(s) from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs

**Comment by rocksdanister** [comment]
Share the log file(s) from Local Appdata folder: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
