### ISSUE TITLE
Libvlc and Libvlc(external) result in errors or fail to render video wallpapers

### ISSUE THREAD

**Issue by dragonloverlord** [rocksdanister/lively#166]
I have installed lively v1.1.2.0 and when I use the video player libvlc all video wallpapers stop working and display solid grey.  The log file corresponding with this scenario ends in 110300

If I instead use libvlc(external) then attempt to view any video wallpaper an actual error message pops up asking me to report an issue.  after I press ok the video wallpaper I was trying to use in not applied.  The log file corresponding with this scenario ends in 110533

1. Go to 'settings > wallpaper'
2. Click on 'Video Player'
3. Select 'libvlc or libvlc(external)'
4. See error when trying to apply any video wallpaper

**Expected behavior**
I would expect the video to become my wallpaper as advertised.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 2004

- Which wallpaper was running at the time if any.
I tested the provided Eternal Light wallpaper as well as multiple mp4 files with Libvlc and Libvlc(external) results were always the same.

**Additional context**
I tested Libmpv, Libmpv(external), and wmf all of which worked as expected with no errors generated.  I made sure to test all the same files I used with Libvlc and Libvlc(external) all of them worked for the other options.

[20201017_110300.txt](https://github.com/rocksdanister/lively/files/5395904/20201017_110300.txt)
[20201017_110533.txt](https://github.com/rocksdanister/lively/files/5395905/20201017_110533.txt)

**Comment by rocksdanister** [comment]
libvlc plugin is not bundled with the program currently.
You can download it separately if you want:
https://github.com/rocksdanister/lively/releases/tag/v1.1.0.0 

I suggest to stick with libmpv(external), the default player instead.
