### ISSUE TITLE
Automatically Move Wallpaper to the new main display when main display is set to another screen

### ISSUE THREAD

**Issue by ManuelGPz** [rocksdanister/lively#1664]
**Is your feature request related to a problem? Please describe.**
I have a setup with several screens and sometimes I am forced to make changes on them and move swap in between what will be my main display. The "problem" is the animated wallpaper always stays original screen it was set.

**Describe the solution you'd like**
It would be great if within the settings there will be an option to push the wallpaper to target the screen set as a main screen.
I understand that some people or situations might require to keep the Wallpaper where it was. That is the reason it would be great if this was just an optional feature that can be turned on/off

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by rocksdanister** [comment]
Lively keeps track of display id and update wallpaper position based on it.. so wallpapers are tied to monitor.

>It would be great if within the settings there will be an option to push the wallpaper to target the screen set as a main screen.

Since this is a niche scenario developing, maintaining and adding a new UI entry for this feature is not practical.. so I am closing this request.
