### ISSUE TITLE
Application ignores ALT+F4 to close

### ISSUE THREAD

**Issue by churusaa** [rocksdanister/lively#1665]
Found while closing other items. Lively was displaying a prompt, something along the lines of indicating that the application was minimized to the task tray and to continue there, with a single button to acknowledge. No other inputs are possible and app doesn't respond to alt+f4, the acknowledge button is the only possible interaction.

**Comment by rocksdanister** [comment]
I get too many support mails related to the system-tray so I only close the app after 4 seconds during the first run when the tutorial prompt is shown.

Don't see it as an issue, the application can still be terminated through taskmanager if required.
