### ISSUE TITLE
AMD error message

### ISSUE THREAD

**Issue by Comi001** [rocksdanister/lively#1668]
Helle,

I have a problem with my graphics card driver AMD it keeps writing error logs with the application MPV.exe Orginal Text
it seems to be due to the Lively Wallpaper because the MPV.exe is included.
Maybe you can fix the error the AMD file writes me my system full. 
I have Windows 11 22H2 and the latest graphics driver from AMD. 

[fehler.txt](https://github.com/rocksdanister/lively/files/11200820/fehler.txt)
[lively_log_20230411_150200.zip](https://github.com/rocksdanister/lively/files/11200825/lively_log_20230411_150200.zip)

Otherwise this is a great work.

**Comment by rocksdanister** [comment]
Uncheck "GPU Decode" which will revert back to using CPU for video playback:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/17554161/230737512-17d37326-7888-4c3b-8d7e-a19d3f215ee5.png">

Mpv is a video player, its not developed by me.
