### ISSUE TITLE
strange behavior when ajax local files

### ISSUE THREAD

**Issue by KAIYOHUGO** [rocksdanister/lively#167]
**Describe**
when live2d web sdk try to load model.json happend (read log below

**To Reproduce**
1. use live2d web sdk demo
2. set as wallpaper
3. and nothing happen

**Expected behavior**
when it load model.json throw a error
`2020-10-19 15:59:41.6720|INFO|livelywpf.Core.WebProcess|CEF:Fetch API cannot load localfolder://index.html/models/lingbo//lingbo.model3.json. URL scheme "localfolder" is not supported.`

**Screenshots/Video**
- set as a files
![image](https://user-images.githubusercontent.com/41114603/96420368-02ce5300-1228-11eb-9849-2a8ae2a3cf91.png)
---
- set as a web
![image](https://user-images.githubusercontent.com/41114603/96420801-85571280-1228-11eb-8854-70b53b492fb0.png)

**Desktop (please complete the following information):**
 - [ Windows 10 1909] _18363.1082_
-  live2d web sdk demo

**Additional context**
if u set live2d web sdk demo as a web not a local files everything is ok

**Log file**
```
2020-10-19 15:59:39.5322|INFO|livelywpf.SetupDesktop|Core: Setting Wallpaper=>index.html
2020-10-19 15:59:40.5434|INFO|livelywpf.SetupDesktop|Sending wallpaper(Per Screen)=>\\.\DISPLAY1 {X=0,Y=0,Width=1920,Height=1080}
2020-10-19 15:59:40.6156|DEBUG|livelywpf.SetupDesktop|Relative Coordinates of WP=>0 1920 1920 1080
2020-10-19 15:59:40.7158|DEBUG|livelywpf.SetupDesktop|Coordinate wrt to screen=>0 0 1920 1080
2020-10-19 15:59:41.6035|INFO|livelywpf.Core.WebProcess|CEF:[CSM][I]Live2D Cubism Core version: 04.00.0000 (67108864)
2020-10-19 15:59:41.6233|INFO|livelywpf.Core.WebProcess|CEF:[CSM][I]CubismFramework.startUp() is complete.
2020-10-19 15:59:41.6397|INFO|livelywpf.Core.WebProcess|CEF:[CSM][I]CubismFramework.initialize() is complete.
2020-10-19 15:59:41.6554|INFO|livelywpf.Core.WebProcess|CEF:[APP]model index: 0
2020-10-19 15:59:41.6720|INFO|livelywpf.Core.WebProcess|CEF:Fetch API cannot load localfolder://index.html/models/lingbo//lingbo.model3.json. URL scheme "localfolder" is not supported.
2020-10-19 15:59:41.6720|INFO|livelywpf.Core.WebProcess|CEF:Uncaught (in promise) TypeError: Failed to fetch
2020-10-19 16:00:55.0286|INFO|livelywpf.Core.Playback|Getting processname failure/handle null, resuming playback!
```

**Comment by rocksdanister** [comment]
File access is blocked on browser for security reasons
`if u set live2d web sdk demo as a web not a local files everything is ok`
By web you mean localhost? if so yes that's how its normally done to get around this.

In cef I'm using its Schemehandler instead of a localhost server:
https://github.com/rocksdanister/lively-cef/blob/a3a5fe81d8e4fd89e1cbc516d486830345fee657/src/cefsharptest/Form1.cs#L446

Looks like its not working correctly in this case 🤔, will need to look over it again.

Is it possible for you to share the wallpaper?

**Comment by KAIYOHUGO** [comment]
> By web you mean localhost? if so yes that's how its normally done to get around this.
- yes
> Is it possible for you to share the wallpaper?
- here u are  🤔
  [lingbo2dlbg.zip](https://github.com/rocksdanister/lively/files/5405781/lingbo2dlbg.zip)
   + **p.s.** pls unzip before use it

_ALL LIVE2D MODEL ©️  AZUE LANE_
_LIVE2D WEB SDK ©️ LIVE2D_

**Comment by rocksdanister** [comment]
Ok, I'll have a look.
(I deleted the comment since the license of the file(s) is not clear.)

**Comment by KAIYOHUGO** [comment]
after testing, i found that error only happen on `fetch api` 🤔 
`XMLHttpRequest` is OK
and on `fetch api` u remove protocol (`document.location.protocol`) not working because it will add itself

i think.....may be add a polyfill that set `fetch api` to `XMLHttpRequest` 🤔 💻 

---
**test log**
```js
fetch("models/lingbo//lingbo.model3.json").then(alert("hi"));
   >>>VM221:1 Fetch API cannot load localfolder://index.html/models/lingbo//lingbo.model3.json. URL scheme "localfolder" is not supported.
```

**Comment by rocksdanister** [comment]
>i think.....may be add a polyfill that set fetch api to XMLHttpRequest

I'm not very familiar with web technologies, let me know if it works.

I'll check the scheme handler code again when I get the time.

In the future, I do plan to add support for Webview2 (Edge) https://github.com/rocksdanister/lively/issues/160 with localhost server when it hits stable(.net version), that should resolve this automatically.

**Comment by KAIYOHUGO** [comment]
After testing , it work!🤔
- [Github fetch](https://github.com/github/fetch)
- and add some code to overriding `fetch api ` 

---
```js
fetch=WHATWGFetch.fetch;
```

---
**!❗it not the best way to fix it,but it's work❗ !**

**Comment by rocksdanister** [comment]
Nah keep it open, this workaround won't be required in the future.

**Comment by amaitland** [comment]
Try registered your scheme with IsFetchEnabled set to true.

http://cefsharp.github.io/api/86.0.x/html/P_CefSharp_CefCustomScheme_IsFetchEnabled.htm

**Comment by rocksdanister** [comment]
Thanks, it works now!
Is there any downside having it enabled, seeing how by default its turned off?

**Comment by amaitland** [comment]
Great 😄 

The built in https scheme has fetch enabled,  it's a standard feature. Generally speaking it's fine to enable. 

It's not so much as it's deliberately disabled by default,  it's more the default wasn't updated when fetch support was added.

**Comment by rocksdanister** [comment]
Got it, appreciate the help.

**Comment by rocksdanister** [comment]
@KAIYOHUGO  Beta build is up, you can check if it works:
https://github.com/rocksdanister/lively-beta/releases

**Comment by KAIYOHUGO** [comment]
its ok now, tks guys👏👏
