### ISSUE TITLE
Can't change lively language if system language is not on English

### ISSUE THREAD

**Issue by whocaresaboutmyusername** [rocksdanister/lively#1674]
My system language is Portuguese by default. I noticed that Lively's language was also stuck on Portuguese so i went to change it but it doesn't let me...
![image](https://user-images.githubusercontent.com/130843706/232225566-409e6896-e0a7-43c2-9c5e-0276634e47cd.png)

What to I do? I'm more comfortable with English.

Specs:
Device name	-----
Processor	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	-----
Product ID -----
System type	64-bit operating system, x64-based processor
Pen and touch	 Pen support

Edition	Windows 11 Pro
Version	22H2
Installed on	‎05/‎11/‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by rocksdanister** [comment]
Currently not possible https://github.com/rocksdanister/lively/issues/1383
