### ISSUE TITLE
Lilvely Wallpaper is not spread across all screens

### ISSUE THREAD

**Issue by livewallpaperlover** [rocksdanister/lively#1677]
I have used Lively for a while now, and it has worked peacefully, but now that I changed the wallpaper to a newly created one by me, my screen and background have become glitchy. I have it spammed across all my screens, but it's only my main screen that is playing the wallpaper. And now my screen is entirely all white; because of the wallpaper not playing.

**Comment by rocksdanister** [comment]
Generate logfile and share:
https://github.com/rocksdanister/lively/wiki/Common-Problems
