### ISSUE TITLE
libVLC player not working.

### ISSUE THREAD

**Issue by seiwayy** [rocksdanister/lively#168]
**Before proceeding**
[20201020_133550.txt](https://github.com/rocksdanister/lively/files/5408462/20201020_133550.txt)
[20201020_133638.txt](https://github.com/rocksdanister/lively/files/5408463/20201020_133638.txt)

**Describe the bug**
When I double click to open the Eternal Light wallpaper, or when I try to add a downloaded video as a wallpaper, a message appears saying "Oops... Looks like something went wrong:(". The app doesn't crash, but I've tried to restart the program and it still doesn't work.

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
![2020 10 20-14 03 (2)](https://user-images.githubusercontent.com/73173876/96583534-26070a00-12dd-11eb-9bf3-837d9dbfb67b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro N (2004)

- Which wallpaper was running at the time if any.
- 
![he88e51s1dv31](https://user-images.githubusercontent.com/73173876/96584885-230d1900-12df-11eb-8c36-f9d0dcf4855d.jpg)

**Log file**
Share the log file(s) from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs

**Comment by rocksdanister** [comment]
libVLC videoplayer is no longer being included with lively, in `Lively settings -> Wallpaper -> Video -> Video Player`  change the videoplayer to libMPV (External)
