### ISSUE TITLE
Youtube video not working

### ISSUE THREAD

**Issue by high-on-catnip** [rocksdanister/lively#1683]
I tried to set Linkin Park - Fighting Myself's music video as my wallpaper, however when i try to use it i get "Video unavailable" then a link: "watch on youtube"

1. In a new wallpaper, paste https://www.youtube.com/watch?v=iKBCVZqqooY (Although I can confirm this affects a few other videos)
2. Set it as your wallpaper
3. It shows the "Video Unavailable" message

**Expected behavior**
I was expecting the video to play on loop.

**Desktop (please complete the following information):**
 - OS: Windows 11 22h2
- The video was running as a wallpaper.

I have attached the log file below.

[lively_log_20230419_140241.zip](https://github.com/rocksdanister/lively/files/11276688/lively_log_20230419_140241.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper
