### ISSUE TITLE
A restart button

### ISSUE THREAD

**Issue by orpa71** [rocksdanister/lively#1689]
The restart button will help because my problem is because when i open a browser in my html, it will not come back to my original state or worse yet, softlock itself because it doesn't have tabs.

The solutions i have is to add the restart wallpaper button in the lively wallpaper app or even on the wallpaper

**It will save time**

**The screenshot's here:**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/132128075/235289752-bd8f2a92-fdfe-42da-a77b-8fafcd13ab7c.png">

**Comment by rocksdanister** [comment]
The "Set as Wallpaper" as contextmenu reloads the wallpaper:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/17554161/235291337-9a631d98-8423-47d3-9dbc-fe79b2403afa.png">
