### ISSUE TITLE
Fluids V2 error message

### ISSUE THREAD

**Issue by Crypt1cYT** [rocksdanister/lively#169]
When i click on  fluids v2 it gives me an error message and tells me to go to the wiki but theres nothing there to help me

![Screenshot (1)](https://user-images.githubusercontent.com/73211839/96672986-10b8cc80-132b-11eb-9fea-dde4def46674.png)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/153

**Comment by Crypt1cYT** [comment]
where do i find sound output properties i am very slow when it comes to coding and stuff like that

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/WebGL-Fluid-Simulation/releases/tag/v2

Just downloads and install(drag and drop the file into lively library) the `Fluids_v2_no_audio.zip` wallpaper.
(this wallpaper version won't react to the audio playing on system.)
