### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by bobosolomon** [rocksdanister/lively#1698]
plash for mac 这个软件对于 notion 等账号有 Edit 这个选项，能够直接登陆账号，而 lively wallpaper 在桌面登陆时，光标有时无法定位到输入框（即无法输入账号）。
===translate===
Plash for Mac software has the option Edit for accounts such as notion and can directly log in to the account, while Lively Wallpaper sometimes cannot be positioned in the input box (that is, the account cannot be entered) when logging in on the desktop.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#mouse--keyboard
