### ISSUE TITLE
cef video support

### ISSUE THREAD

**Issue by BatteryBird** [rocksdanister/lively#17]
I would like to be able to overlay the Rain effect on my own imported video wallpapers and images if at all possible.

**Comment by rocksdanister** [comment]
video support is currently broken in cef.

for adding custom picture, did you try following this tutorial:
https://www.reddit.com/r/LivelyWallpaper/comments/f21a8d/how_do_i_upload_a_custom_background_to_the_rain/

**Comment by rocksdanister** [comment]
Future versions of cef will likely have the fix: https://stackoverflow.com/questions/59840194/cefsharp-75-1-143-local-webm-video-not-loading

Otherwise I will have to make a localhost server as a fix probably.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2873/streamreaderurlloader-doesnt-correctly has been resolved. If you upgrade to version `81.3.x` of `CefSharp` you will be able to load `webm` files using a `ResourceHandler`.

**Comment by rocksdanister** [comment]
Didn't expect to see a cefsharp dev reply damn...
Thanks for letting me know, I'll wait for the final stable nuget release.

While you are here if you don't mind can you have a look at this also :D : https://github.com/rocksdanister/lively/issues/20

**Comment by amaitland** [comment]
> hanks for letting me know, I'll wait for the final stable nuget release.

The [81.3.20-pre](https://github.com/cefsharp/CefSharp/releases/tag/v81.3.20-pre) release is on `Nuget.org` for testing purposes should you wish to test it out.

**Comment by rocksdanister** [comment]
Latest version of lively with cef 81.3.100 supports video:
https://github.com/rocksdanister/lively/wiki/Web-Guide-VI-:-Webpage-Video-Support

I will update the original rain wallpaper with video support in the future.
