### ISSUE TITLE
Setting "wallpaper input" to OFF still forwards mouse position/movement to exe wallpaper

### ISSUE THREAD

**Issue by santarl** [rocksdanister/lively#1700]
**Describe the bug**
Setting "wallpaper input" to OFF still forwards mouse position/movement to exe wallpaper

**To Reproduce**
1. Set a exe wallpaper
2. Go to wallpaper tab in settings
3. Set wallpaper input dropdown to OFF
4. Mouse movement is still forwarded to the wallpaper

**Expected behavior**
Prevent any kind of interactivity. If the current behaviour is intended, add seperate option which completely prevents all interactivity

**Comment by rocksdanister** [comment]
Application wallpapers can create their own global hooks:
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#mouse--keyboard
https://learn.microsoft.com/en-us/windows/win32/winmsg/about-hooks

Since its part of the application code, don't think it can be blocked.

**Comment by santarl** [comment]
Ah. that sucks. Thanks for clarifying. I am closing this issue if nothing reliable can be done about it.
