### ISSUE TITLE
Lively not opening

### ISSUE THREAD

**Issue by AzazelHD** [rocksdanister/lively#1703]
Hello. I dont know whats going on, but when lively minimizes to the navigation bar, as a tray icon (i guess this is the name), and i right click on it to attempt to "open lively", it doesnt open. I cant change my backgrounds etc.
[lively_log_20230509_152022.zip](https://github.com/rocksdanister/lively/files/11431532/lively_log_20230509_152022.zip)

https://gyazo.com/aea4d5130fd319c6c6669c52c11b2a10

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1691
