### ISSUE TITLE
Too much GPU load.

### ISSUE THREAD

**Issue by INST1NCT00** [rocksdanister/lively#1706]
**Describe the bug:**
The bug happened a week ago when I was messing around with OBS in order to get good quality on my screen recording. I changed OBS software's graphics setting from Windows. Then, when I opened up the Task Manager, I noticed an unusually high load on the GPU. I initially thought it was the recording software, but it is actually Lively. Also, I noticed this after Lively got a new update.

Here is what I found:
1. Reinstalling Lively Wallpaper, reinstalling the graphics drivers(both integrated and dedicated) did nothing.
2. The problem only started recently, before this it was completely fine.
3. The GPU usage depends on the wallpaper I am using.
4. The process using the cpu is named: "CefSharp.BrowserSubprocess.exe".
5. This happened after I updated lively to the second latest version.

**To Reproduce:**
Not reproduceable.

**Expected behavior:**
Lively to not use this much GPU, it even causes the fans to ramp up to 80%.

**Screenshots/Video:**
While using Fluids:

![image](https://github.com/rocksdanister/lively/assets/125669213/d8595bb6-7328-4db2-ab7a-6eb973fb31b8)

![image](https://github.com/rocksdanister/lively/assets/125669213/e1a73967-5eff-4e4a-a71b-b0a8321013cd)

While using rain:

![image](https://github.com/rocksdanister/lively/assets/125669213/015a3dd1-cccd-42d4-9e96-9fb6496e6dd7)

![image](https://github.com/rocksdanister/lively/assets/125669213/57942259-dbea-469c-b05c-a40e9eb5337e)

**Laptop:**
 - Windows 10 22H2
- A custom CyberPunk wallpaper, but the default ones reproduce the same issue.

**Log file:**
[lively_log_20230513_172357.zip](https://github.com/rocksdanister/lively/files/11469598/lively_log_20230513_172357.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance
