### ISSUE TITLE
[Bug] Taskbar item for Lively Wallpaper on Windows Startup

### ISSUE THREAD

**Issue by fourteen-1** [rocksdanister/lively#1708]
Wallpaper is an mp4 file running on mpv video player

![image](https://github.com/rocksdanister/lively/assets/73333396/6f39081a-7385-4f13-824f-ff11f1e5f5a6)

ps: clicking on the taskbar item does not bring up any windows. Closing it by Right click>close window stops the live wallpaper from playing.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/598
