### ISSUE TITLE
support 'mpv.conf'?

### ISSUE THREAD

**Issue by hooke007** [rocksdanister/lively#171]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A perfect software if it support "mpv.conf". For I usually write some words in that file to make the video performance better. 
And for example, "icc-profile-auto" would make it show the correct color in my wide-color-range monitor.

What's more, if it can support scripts...would be best.

**Describe alternatives you've considered**

**Additional context**

**Comment by rocksdanister** [comment]
Update v1.1.3.0 onwards will have support for custom mpv config file:
https://github.com/rocksdanister/lively/wiki/Video-Guide

If you have any suggestions for the default configuration of mpv let me know:
https://github.com/rocksdanister/lively/blob/cca241b192bb3724e0bc3d1fd6dc0754134b231e/src/livelywpf/libMPVPlayer/MainWindow.xaml.cs#L76

**Comment by rocksdanister** [comment]
Related: https://github.com/rocksdanister/lively/issues/195
