### ISSUE TITLE
Browser is too old version message when trying to load live cam website

### ISSUE THREAD

**Issue by 3shadow7** [rocksdanister/lively#1713]
i try to put url live cam , but it say my browser need update , and i think he talk about your app browser : 
.
.
![Screenshot 2023-05-15 031008](https://github.com/rocksdanister/lively/assets/79174609/903c9d7b-6db0-49c6-98c3-00c3cc2dbc1f)
.
i used this link for live cam : 
.
https://www.skylinewebcams.com/en/webcam/israel/jerusalem-district/jerusalem/western-wall.html
.
and the link work good in my chrome and opera browsers

**Comment by rocksdanister** [comment]
The default browser (CefSharp) does not support x264 video codec due to licensing, WebView2 should work but it is under development I do not recommend at the moment.

Further read:
https://github.com/rocksdanister/lively/wiki/Web-Player
