### ISSUE TITLE
Music TV (LQ) detecting wrong song from the same album

### ISSUE THREAD

**Issue by Nalshik** [rocksdanister/lively#1716]
so I have a playlist with a lot of songs some from the same album for example Metallica's "Fade To Black" and "For Whom The Bell Tolls" those are two songs coming from the same album called "Ride The Lightning" so on the TV when the first song is played its correct with no issues but when  the other song from the same album as i said plays it doesn't change the song playing it keeps on showing me that I'm playing the original song 
![1](https://github.com/rocksdanister/lively/assets/133867513/e51fe160-4a30-4851-8cfa-02878e55c58d)
![2](https://github.com/rocksdanister/lively/assets/133867513/8d6683f5-84fa-4843-8012-4de6ce2cc633)

**Comment by Nalshik** [comment]
I forgot to add that it becomes normal again after I play another song from another album but this issue still happens even if i played 3 songs from the same album :)

**Comment by rocksdanister** [comment]
My mistake, it should be OR here:
https://github.com/rocksdanister/lively/blob/cdcfc3009e988022f440886a856eb24d2f3e4014/src/Lively/Lively.PlayerWebView2/Services/NpsmNowPlayingService.cs#L91
