### ISSUE TITLE
Lively says it can run because im missing NET Core but i have it installed

### ISSUE THREAD

**Issue by MyZelFlol** [rocksdanister/lively#172]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**
Lively wont open because it thinks i dont have NET Core installed, but i do.

**To Reproduce**
1. Open Lively
2. issue pops up

**Expected behavior**
I expected the app to launch and run properly.

**Screenshots/Video**
https://youtu.be/kfZrF_GbBZk

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903
- i just have a picture there

**Additional context**
i hope someone can help
**Log file**
Share the log file(s) from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs
cant find that folder

**Comment by rocksdanister** [comment]
Install the correct x86 version from the link and then restart windows:
https://github.com/rocksdanister/lively/wiki/Getting-Started
