### ISSUE TITLE
A refresh wallpaper button in the icon tray menu

### ISSUE THREAD

**Issue by lluminate** [rocksdanister/lively#1720]
Sometimes my desktop bugs like this 
![image](https://github.com/rocksdanister/lively/assets/89876647/3965ed70-21ce-4d23-b352-3cc692701133)
So I would like a refresh wallpaper button in this menu instead of having to open lively everytime and switch to a different wallpaper and back
![image](https://github.com/rocksdanister/lively/assets/89876647/8519dbb8-7e36-4e5a-a67d-7339b8a02ada)

**Comment by rocksdanister** [comment]
This will not be worked on, instead I would like to fix the root cause of the problem.

Create a bug report with the logfiles when this problem happens.
