### ISSUE TITLE
Actually at first there is no problem loading .mp4 file but after along of using suddenly this happen (WallpaperPluginException)

### ISSUE THREAD

**Issue by KurammaKurotsuchi** [rocksdanister/lively#1722]
**Describe the bug**

![image](https://github.com/rocksdanister/lively/assets/98173515/2c6a293e-b152-46a1-a787-e144e310b701)

then when i add more .mp4 file this happens
![image](https://github.com/rocksdanister/lively/assets/98173515/6ed30c16-03a3-491b-93e5-d2571e845863)

this is what happen when I load on lively debugger
![image](https://github.com/rocksdanister/lively/assets/98173515/c5951e41-5fb0-4190-895b-19de384e3786)

this my report .zip file
[lively_log_20230521_165737.zip](https://github.com/rocksdanister/lively/files/11524216/lively_log_20230521_165737.zip)

**Comment by rocksdanister** [comment]
Looks like some audio driver related issue, disabling audio should fix it:

Create the file mpv.conf as follows:
`<Lively install location>\plugins\mpv\portable_config\mpv.conf`

mpv.conf:
```
--aid=no
```

For more information:
https://github.com/rocksdanister/lively/wiki/Video-Guide#mpv
https://mpv.io/manual/master/#options-aid

**Comment by KurammaKurotsuchi** [comment]
My problem has been fixed, with this solution with audio mute for the drawback but its ok since I use it just to play video background only.
thank you
