### ISSUE TITLE
Add a tooltip to the livelyProperties items

### ISSUE THREAD

**Issue by Gabrz** [rocksdanister/lively#1723]
Is it possible to add tooltips to the items in the livelyProperties / customize screen.
(add a new field "tooltip" to the objects in the livelyProperties.json and show that value when you hover over the customisabe property)

That way one could give some extra information what the property does.

The "Restore default" button has a tooltip, so why not add them to the items as well.

**Comment by rocksdanister** [comment]
Not possible in the current version, tooltip can be implemented in a future update.
