### ISSUE TITLE
Crash when customizing color of wallpaper

### ISSUE THREAD

**Issue by julausrie** [rocksdanister/lively#1724]
[lively_log_20230522_171156.zip](https://github.com/rocksdanister/lively/files/11532971/lively_log_20230522_171156.zip)

https://github.com/rocksdanister/lively/assets/72754642/79221ba3-80dc-43df-8e6c-4314438cd810

**Comment by rocksdanister** [comment]
What's strange is I can no longer recreate this bug, it used to crash for me also a week back but now stopped🤔

**Comment by rocksdanister** [comment]
@julausrie Does the issue still happen for you?

**Comment by Ryanjiang2009** [comment]
The same thing happeed to me when I'm doing the same thing, but it won't show up after I uninstalled it and installed it back.



在 2023-06-02 13:03:33，"Dani John" ***@***.***> 写道：

@julausrie Does the issue still happen for you?

**Comment by julausrie** [comment]
> @julausrie Does the issue still happen for you?

Yes it still happens for me

**Comment by rocksdanister** [comment]
Can you try beta, I switched to a new colorpicker: 
https://github.com/rocksdanister/lively-beta

**Comment by julausrie** [comment]
> Can you try beta, I switched to a new colorpicker: https://github.com/rocksdanister/lively-beta

I installed the newest version but it still crashes for me when pressing on the colorpicker

**Comment by rocksdanister** [comment]
What is the version number?

**Comment by julausrie** [comment]
> What is the version number?

I installed the newest version from github but I just noticed that its still 2.0.6.6 (because I already had it installed probably). I'm going to reinstall it completly

**Comment by rocksdanister** [comment]
The beta branch is different, its for testing early releases.

Download the installer from here:
https://github.com/rocksdanister/lively-beta/releases

The version should show v2.0.6.9b in the app. Once done you can just run the regular installer to return back to normal release.

**Edit**
Latest stable release has the patch.
