### ISSUE TITLE
Wallpaper bugs when putting computer to sleep

### ISSUE THREAD

**Issue by lluminate** [rocksdanister/lively#1726]
**Describe the bug**
The wallpaper glitches and only displays on one monitor while also cropping wrong.

**To Reproduce**
1. Put the computer to sleep
2. Wait some time, I don't know how long but it has happened every time for me when it has been more than an hour. It doesn't happen if you just put the computer to sleep and wake it immediately.
3. Boot the computer back up
4. See the error

**Expected behavior**
The wallpaper should display on both monitors

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/89876647/94419855-78ee-49f5-9bf7-0f90f3788c65)

**Desktop (please complete the following information):**
 - OS: 
Edition	Windows 10 Pro
Version	22H2
Installed on	‎2021-‎01-‎26
OS build	19045.2311
Experience	Windows Feature Experience Pack 120.2212.4190.0

- Video wallpaper was running

**Additional context**

**Log file (Important)**
[lively_log_20230524_172751.zip](https://github.com/rocksdanister/lively/files/11560085/lively_log_20230524_172751.zip)

**Comment by lluminate** [comment]
https://github.com/rocksdanister/lively/issues/1720#issuecomment-1556007291

**Comment by rocksdanister** [comment]
moved here: https://github.com/rocksdanister/lively/issues/2178#issuecomment-2111804461
