### ISSUE TITLE
won't open on startup

### ISSUE THREAD

**Issue by Shubh088** [rocksdanister/lively#1729]
It wont startup on start and when i went to the startup tab in task manager its like [this](https://www.dropbox.com/s/x1w5qjej7ksg7q0/Capture.JPG?dl=0) and when i enable it and reopen task manager it gets disabled again also its path is kinda weird and there is no start up type mentioned

**Comment by Shubh088** [comment]
im using windows 10 22H2 and i have installed lively from ms store

**Comment by rocksdanister** [comment]
![-xUb-ACQ](https://github.com/rocksdanister/lively/assets/17554161/bd180292-6396-4c33-9581-d7df0107c4dc)

What does it say in Lively app?
<img width="648" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/9a2e2265-a8fa-41d7-ae0a-72d3eb0338b3">

If its enabled in Lively app or you did not disable it in taskmgr then something else did.. I know some optimizing software that mess with startup like this.

**Comment by rocksdanister** [comment]
relevant: https://github.com/TranslucentTB/TranslucentTB/issues/729

> This is often caused by debloating utilities changing registry keys. Try importing the following reg file in your system and rebooting afterwards:
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
> "EnableFullTrustStartupTasks"=dword:00000002
> "EnableUwpStartupTasks"=dword:00000002
> "SupportFullTrustStartupTasks"=dword:00000001
> "SupportUwpStartupTasks"=dword:00000001
> ```

**Comment by Shubh088** [comment]
I think It was the wise ram optimizer

**Comment by Shubh088** [comment]
Thankfully i found a fix yesterday It's the same registry keys you sent. Still Thank You for replying
