### ISSUE TITLE
lockscreen wallpaper

### ISSUE THREAD

**Issue by Yochuu** [rocksdanister/lively#1731]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by rocksdanister** [comment]
Its picture of live wallpaper, not live wallpaper on lockscreen.

The feature is removed for the time being due to issue https://github.com/rocksdanister/lively/issues/537
