### ISSUE TITLE
Music Wallpapers never show spotify album art, only youtube video thumbnails

### ISSUE THREAD

**Issue by tanishr07** [rocksdanister/lively#1732]
**Describe the bug**
Everytime I try to use one of the wallpapers which shows the album art and audio visualizer, it never shows my album art but only the thumbnail of the youtube video I am watching, which I dont want it to show.

**To Reproduce**
1. Go to wallpapers
2. Click on "Living Room"/"Music TV HQ/LQ"
3. Play music on spotify
4. Watch a Youtube Video

**Expected behavior**
Wallpaper shows album art with proper audio visualizer
**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![image](https://github.com/rocksdanister/lively/assets/55037202/d8d68e19-ec92-4f06-8a99-f5602c8361d1)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home Insider Preview;22H2;23440.1000
- Living Room

**Log file (Important)**
[lively_log_20230529_144241.zip](https://github.com/rocksdanister/lively/files/11594298/lively_log_20230529_144241.zip)

**Comment by rocksdanister** [comment]
So does it show spotify albumart and details when no youtube video is playing?

**Comment by tanishr07** [comment]
Nope, either no signal, a black screen with only the audio visualizer when no youtube tab is opened or the thumbnail of a youtube video.

**Comment by rocksdanister** [comment]
Which Spotify player are you using?

This is what I tested on.. I think its from the Microsoft Store.
<img width="342" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/265ea281-71e8-466c-933f-6c33b4e4a00b">

**Comment by tanishr07** [comment]
Oh maybe it's because I'm using the one downloaded from the web?

**Comment by rocksdanister** [comment]
Does the albumart etc show up on Windows volumebar?
<img width="302" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/c2677e62-dbdb-4338-9c29-32ad9c598691">

**Comment by tanishr07** [comment]
It doesn't. Is there way to toggle that?

**Comment by tanishr07** [comment]
Ok I think I got it to work now, by making it so that the action center shows what spotify's playing. Thanks!

**Comment by tanishr07** [comment]
New issue: the album art doesn't change on its own

**Comment by rocksdanister** [comment]
> Ok I think I got it to work now, by making it so that the action center shows what spotify's playing. Thanks!

What was the cause of the problem and how did you make action center show?

**Comment by tanishr07** [comment]
The setting in spotify under display wasn't clicked:
![image](https://github.com/rocksdanister/lively/assets/55037202/73003658-3688-433c-8271-4a47cae4a763)
And then I also had to click on the place on the task bar where it shows wifi, etc. and then switched the source on the audio controls.

**Comment by rocksdanister** [comment]
> New issue: the album art doesn't change on its own

Did it work after maybe a spotify restart?

Possibly related https://github.com/rocksdanister/lively/issues/1716
