### ISSUE TITLE
Lively screensaver not working

### ISSUE THREAD

**Issue by alexsteveking** [rocksdanister/lively#1734]
I've recently reset my computer to windows 11 and the lively screensaver isn't working no matter how long I wait.
I am pretty new to this so I'd like it to be fixed but I don't really know what to do 
Here is the log file v
[lively_log_20230530_234912.zip](https://github.com/rocksdanister/lively/files/11609601/lively_log_20230530_234912.zip)

**Comment by rocksdanister** [comment]
Try this:
https://github.com/rocksdanister/lively/wiki/Common-Problems#display-sleepscreensaver-not-working
