### ISSUE TITLE
WallpaperPluginException

### ISSUE THREAD

**Issue by bronig** [rocksdanister/lively#1737]
hello! i started using lively wallpaper but when i click a wallpaper an error shows i don't know how to fix it said that i need to go to github i searched but no answer to this issue
[lively_log_20230601_031330.zip](https://github.com/rocksdanister/lively/files/11624042/lively_log_20230601_031330.zip)
here is the log hope it helps error name(WallpaperPluginException)

**Comment by rocksdanister** [comment]
1. Do you run any desktop modification software? for example Stardock Fences.
2. Do you use a third party anti-virus software? if so check its quarantine to see if it deleted any Lively files.

**Comment by bronig** [comment]
i only use round tb

**Comment by LiveEkansh** [comment]
I am having the same error. Please help rockdanister :(

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#web-wallpapers-not-working

https://github.com/rocksdanister/lively/wiki/Common-Problems#wallpaperpluginnotfoundexceptionantivirus-warning-when-selecting-wallpaper

Its usually either of the two above or some third party software like Fences compatibility issue.
