### ISSUE TITLE
Unable to select the file on the desktop / 无法选中桌面上的文件

### ISSUE THREAD

**Issue by lyolve** [rocksdanister/lively#174]
- 操作系统: Windows 10 1909 内部版本18363.1139
- 遇到问题: 无法拖拽、选中桌面上的文件/图标
- 其他状况: 切换到一个窗口后，第一次点击桌面文件/图标，是正常的，之后就不行了
- Eternal Light 是唯一没有遇到这个问题的背景

---
- Operating system: Windows 10 1909 (Internal version 18363.1139)
- Problems encountered: Unable to drag or select files/icons on desktop
- Other conditions: After switching to a window, the first time I click on a desktop file/icon, it works, then it doesn't work.
- Eternal Light was the only background that didn't have this problem.

**Comment by rocksdanister** [comment]
Can you record a video of the problem?

**Comment by lyolve** [comment]
https://youtu.be/uV1EqFudPN4

**Comment by rocksdanister** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/17554161/97130712-259cc200-1768-11eb-9010-d710877e605d.gif)

Working fine on my system.

1. Can you give me a list of all the background programs running in your system.
2. Does this still happen when `Lively settings -> Wallpaper -> Interaction -> Wallpaper Input` is set to `OFF`?
![Screenshot 2020-10-26 085703](https://user-images.githubusercontent.com/17554161/97131096-3ef23e00-1769-11eb-9750-7429ba3c411f.jpg)

**Comment by lyolve** [comment]
I used the method of shutting down the running software one by one to debug it, and found that closing [Quicker](https://getquicker.net/) made things better, but the software had no features related to changing the desktop.

And there is still some lag after closing Quicker, when  Wallpaper Input is set to OFF， this problem is no longer present and there is no lag anymore.

**Comment by lyolve** [comment]
- 我用的“卡顿”一词，我的意思是非常快速的创建选框时偶尔不出现蓝色框的现象，我不确定这是否属于可接受的正常情况

- The word ’lag‘ means very quick creation of selection boxes with occasional missing of the blue boxes, I'm not sure if that's an acceptable normal situation.
---
![1.gif](https://i.loli.net/2020/10/26/Dg3LbSp2ozhkCGI.gif)

**Comment by rocksdanister** [comment]
Using this to track https://github.com/rocksdanister/lively/issues/683
