### ISSUE TITLE
Select network adaptor for systeminformation api

### ISSUE THREAD

**Issue by 42willow** [rocksdanister/lively#1741]
**Describe the bug**
For some reason the wrong network adapter is being picked for the livelySystemInformation (I'm trying to make my own theme) - even after disabling the mobile network adapter - it still picks that over the wifi one.

**Comment by rocksdanister** [comment]
Currently there is no selector, soon https://github.com/rocksdanister/lively/issues/1508

**Comment by rocksdanister** [comment]
This is the current implementation, I am picking the first network card from the list:
https://github.com/rocksdanister/lively/blob/core-separation/src/Lively/Lively.Common.Services/PerfCounterUsageService.cs

not sure how to change that in the system settings.
