### ISSUE TITLE
[NowPlaying Bug] Title doesn't change in album

### ISSUE THREAD

**Issue by 42willow** [rocksdanister/lively#1745]
**Describe the bug**
When the next song in an album is played, the title doesn't update and the livelyCurrentTrack listener isn't called.

**To Reproduce**
1. Download a sample theme that uses Lively NowPlaying https://github.com/rocksdanister/audio-visualizer-wallpaper (media parallax)
2. Play an album (on spotify or something) and see.

**Expected behavior**
The title of the album should change.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1716

**Comment by rocksdanister** [comment]
You can try the fix on installer version of Lively:
https://github.com/rocksdanister/lively-cef/releases/tag/v1.7.0.1

Replace <install_location>/Plugins/Cef/
