### ISSUE TITLE
Lively running but can't open the app / Customize

### ISSUE THREAD

**Issue by Avyren** [rocksdanister/lively#1747]
When I open the "Show hidden icons" button on Windows 10, right click Lively Wallpaper then click "Open Lively" or "Customize Wallpaper" nothing happens. All the other options seems to work just fine.

This happens with various wallpapers which I can still switch out using the "Change Wallpapers" option.

[lively_log_20230606_100601.zip](https://github.com/rocksdanister/lively/files/11661874/lively_log_20230606_100601.zip)

**Comment by Sobble2546** [comment]
same problem my log 
[lively_log_20230606_205953.zip](https://github.com/rocksdanister/lively/files/11666450/lively_log_20230606_205953.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1691
