### ISSUE TITLE
Cant open lively

### ISSUE THREAD

**Issue by defautluser0** [rocksdanister/lively#1757]
**Describe the bug**
Open lively doesnt do anything on right click taskbar menu

**To Reproduce**
1. Go to the taskbar
2. Right Click on the lively icon
3. Click "Open Lively
4. Nothing happens

**Expected behavior**
I expected to open Lively

**Screenshots/Video**
idk how

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903]

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[20230610_215845.txt](https://github.com/rocksdanister/lively/files/11713230/20230610_215845.txt)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1691

**Comment by defautluser0** [comment]
> duplicate: #1691

no, it doesnt even appear anything, i read that one. it completely refuses to open lively ui. he said it was a window that crashed. mine doesnt do nothing

**Comment by rocksdanister** [comment]
Its same framework issue.

**Comment by defautluser0** [comment]
https://github.com/rocksdanister/lively/assets/108409246/08ac3b40-380f-4eba-89c1-c5dd389955e0

**Comment by defautluser0** [comment]
weird, it played before for me

**Comment by defautluser0** [comment]
https://github.com/rocksdanister/lively/assets/108409246/cf4b4438-4c2d-4ef1-89c4-4b01f4072511

ok it plays

**Comment by rocksdanister** [comment]
Crashing or briefly opening then crashing, its the same issue with the framework.

**Comment by defautluser0** [comment]
will u release an update to fix it soon?

**Comment by rocksdanister** [comment]
My hands are tied, its upto Microsoft to fix.

I will release an update with an older version of the framework as a temporary fix.

Locking since its duplicate.
