### ISSUE TITLE
[bug]video cannot be played

### ISSUE THREAD

**Issue by StarDreamAndFeng** [rocksdanister/lively#1758]
**Describe the bug**
I have two screens. When the window is maximized on one of the screen, the video cannot be played. the video plays only when you click on the Desktop.

**To Reproduce**
none

**Expected behavior**
none

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/87743227/2d2e25a1-b0f6-403e-a213-f615aea9d222)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by StarDreamAndFeng** [comment]
设置中选择其他应用程序全屏：保持运行，即可解决
closed #1758

**Comment by rocksdanister** [comment]
![Screenshot 2023-06-12 190332](https://github.com/rocksdanister/lively/assets/17554161/12c37981-e2db-4e83-9972-9aa146f1be52)

Set `Display pause rule -> Per screen`

**Comment by StarDreamAndFeng** [comment]
> ![Screenshot 2023-06-12 190332](https://user-images.githubusercontent.com/17554161/245159951-12c37981-e2db-4e83-9972-9aa146f1be52.jpg)
> 
> Set `Display pause rule -> Per screen`

Thanks! friend. I have found it.
