### ISSUE TITLE
Different color schema on different monitors

### ISSUE THREAD

**Issue by valfrid-ly** [rocksdanister/lively#1762]
If lively wallpapper starts with some other foregroud app already opened, the monitor where is this application using matrix wallpaper starts with rainbow configuration instead of the selected configuration

1. Be sure to have at least 2 monitors
2. Configure matrix lively wallpaper with standard green color
3. Set lively to start with windows
4. Restart the PC 
5. Open an maximized application before lively wallpaper is loaded (automatic loading, not manual)
6. After loading (check on 2nd monitor) minimize your screen and check the color scheme
7. See the monitor with the opened app having rainbow color scheme

**Expected behavior**
Have all monitors using same color scheme on the wallpaper.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro  Version: 22H2 Build: 22631.1900 with Windows Feature Experience Pack 1000.22646.1000.0
- Matrix

**Log file (Important)**
Share the diagnostic files by:
[lively_log_20230620_131613.zip](https://github.com/rocksdanister/lively/files/11803251/lively_log_20230620_131613.zip)

**Comment by rocksdanister** [comment]
I think this is a wallpaper issue https://github.com/rocksdanister/lively/discussions/1749

**Comment by valfrid-ly** [comment]
I'm applying the fix in that but you sent. If it works I'll close it

**Comment by valfrid-ly** [comment]
It seems the fix for issue #1749 is a perfect solution.
