### ISSUE TITLE
Taskbar theme resets after full screen application

### ISSUE THREAD

**Issue by AzazelHD** [rocksdanister/lively#1764]
First of all, say that i am in version 6.1, since the 6.6 wasnt letting me open lively anymore.

Issue is as tittle says: after entering full screen mode, the main menu bar theme gets reseted to default (blue from windows) even if i had it as "wallpaper"

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1569
