### ISSUE TITLE
Music TV (LQ & HQ) used to be able to show thumbnails and change songs. Not anymore.

### ISSUE THREAD

**Issue by Celtr1k** [rocksdanister/lively#1770]
**Describe the bug**

**To Reproduce**
1. Use "Music TV (LQ)" or "Music TV (HQ)"
2. Observe if it all works correctly
3. Restart computer

**Expected behavior**
It should work, just like when I used it for the first time some hours ago

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/109984392/c9d8ed1e-038f-4df1-b375-209a110616e7)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Music TV (LQ)

**Additional context**
It not only can't change the image, but it also cannot change song. The name of the song is the one that was playing when I activated the wallpaper, and when the next song plays, the name doesn't change either.

**Log file (Important)**
[lively_log_20230625_185644.zip](https://github.com/rocksdanister/lively/files/11860301/lively_log_20230625_185644.zip)

**Comment by rocksdanister** [comment]
Does it still happen with latest release v2.0.7.0 ?
