### ISSUE TITLE
Kaspersky believed that the living wallpaper was infected with computer virus

### ISSUE THREAD

**Issue by hehellooedas** [rocksdanister/lively#1774]
![image](https://github.com/rocksdanister/lively/assets/96963528/c996f344-99ba-4dc4-b1de-fb28aaa4814a)
Before updating the new version of lively wallpaper, Kaspersky didn't think it was a virus.
kaspersky still think it's a virus after reinstalling it.Did Kaspersky kill it by mistake?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/358#issuecomment-800762567
