### ISSUE TITLE
One or more error occurred. (No process is accociated with this object.)

### ISSUE THREAD

**Issue by DarKnight51** [rocksdanister/lively#1776]
I can no longer use a custom video for my wallpaper, it worked before but now it won't even let me try to.
![image_2023-06-30_193720368](https://github.com/rocksdanister/lively/assets/59962421/69677d85-d805-49cf-8507-bd4423d03b30)

Here's the log and the video if you want to try it yourself.
[lively_log_20230630_193021.zip](https://github.com/rocksdanister/lively/files/11919215/lively_log_20230630_193021.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/1291#issuecomment-1179157571
