### ISSUE TITLE
MPV player in Taskbar

### ISSUE THREAD

**Issue by Sunghyogun2** [rocksdanister/lively#1777]
ok , here is a player Icon in my taskbar looping video

Log File: 
[lively_log_20230701_195955.zip](https://github.com/rocksdanister/lively/files/11926659/lively_log_20230701_195955.zip)

Video:
https://github.com/rocksdanister/lively/assets/106765140/9ab28248-e7a6-4f48-a0a8-e893932bf756

It will never hide as long as I go to settings and replace another video player then back to MPV 👎 
I should do it everytime I reset my PC

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/598
