### ISSUE TITLE
High CPU Usage with 2 monitors

### ISSUE THREAD

**Issue by Rajdave69** [rocksdanister/lively#1778]
**Describe the bug**
I have very high CPU usage (30-40%) on a Ryzen 7 5800x. This is very abnormal.

I have hardware acceleration enabled too. so it should? use GPU 

**To Reproduce**
1. Use the Living room and TV wallpapers
2. Watch CPU usage go up

**Expected behavior**
The program to not use this much of the CPU

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/86198810/bbc268f2-35fe-487f-8912-b524ce9039ce)
![image](https://github.com/rocksdanister/lively/assets/86198810/a04d9fc0-d037-43a4-93ad-8c2330e880ac)

**Desktop (please complete the following information):**
 - OS: Windows 11 build 22622
- Living room, TV (2 monitors)

**Additional context**

**Log file (Important)**
[lively_log_20230701_222548.zip](https://github.com/rocksdanister/lively/files/11926955/lively_log_20230701_222548.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance
