### ISSUE TITLE
The edit wallpaper dialog does not move or close with the main window

### ISSUE THREAD

**Issue by Jingbing1030** [rocksdanister/lively#1782]
- With automatic translation, the content may not be accurate
The bug is shown on the image below.I used the system's built-in PSR .exe documented how I reproduced the bug (The .mht file is in 错误.zip)
![捕获1](https://github.com/rocksdanister/lively/assets/129979803/515dbdb4-aca9-4bcd-a770-82d448705a31)
[错误.zip](https://github.com/rocksdanister/lively/files/11981313/default.zip)

[lively_log_20230707_190418.zip](https://github.com/rocksdanister/lively/files/11981819/lively_log_20230707_190418.zip)

**Comment by rocksdanister** [comment]
Try capturing a video of the issue, better than screenshot.

**Comment by Jingbing1030** [comment]
https://github.com/rocksdanister/lively/assets/17554161/1038f87f-8180-439c-9c76-a00879b33c2b

**Comment by rocksdanister** [comment]
Its a separate dialog from the user interface, this is by design and useful for other purposes ( [commandline](https://github.com/rocksdanister/lively/wiki/Command-Line-Controls) importing, hosting another window ontop etc..)

**Comment by rocksdanister** [comment]
The not moving part is weird yes, should look into making it better but its not easy because that dialog is from a separate application (core) and not part of UI application.
