### ISSUE TITLE
Screensaver shows mpv window

### ISSUE THREAD

**Issue by Kelopy** [rocksdanister/lively#1795]
Shows up like this after the screensaver turns off (the screensaver also has the same issue)
Windows 11 Home 22H2
![obVlZolwmi](https://github.com/rocksdanister/lively/assets/104870520/79324281-635d-4a01-8dc6-0c39351a6e7f)

**Comment by Panikk11503** [comment]
I also have this issue.  I don't see the border for the mpv player but the screensaver on my 3rd monitor will play the wallpaper in what appears to be a 720p window from the top left corner.  Not a huge deal, but I wasn't sure about opening my own issue report when this one is here. 
![Screenshot 2023-07-31 010412](https://github.com/rocksdanister/lively/assets/22116474/65b166e8-1dc8-4857-bc09-b631bb1a1dc4)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1727
