### ISSUE TITLE
wallpaper plugin exception

### ISSUE THREAD

**Issue by BestScripts420** [rocksdanister/lively#1800]
when i trying upload video/gift this i got error "wallpaperpluginexception"
[logs.txt](https://github.com/rocksdanister/lively/files/12123242/logs.txt)

**Comment by rocksdanister** [comment]
Try turning OFF `GPU decode`
<img width="650" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/f09323f8-22cb-45a9-85ce-2a42c3b9be59">

**Comment by imaa4** [comment]
i cant upload vidio always like this "wallpaperpluginexception". i was turn off the gpu decode but its still same
[lively_log_20231014_014832.zip](https://github.com/rocksdanister/lively/files/12897638/lively_log_20231014_014832.zip)
