### ISSUE TITLE
wallpaper issue

### ISSUE THREAD

**Issue by syb3rYT** [rocksdanister/lively#1803]
whenever i try to use my own live wallpapers, it always says "one or more errors has occured ( no process is associated with this object )

exception : wallpaperpluginexception

![image](https://github.com/rocksdanister/lively/assets/140216766/a5167505-5966-4bf7-85be-7b6fb1521a43)

 - OS: windows 11]
- Which wallpaper was running at the time if any : my custom wallpaper

**Log file (Important)**

[lively_log_20230722_051152.zip](https://github.com/rocksdanister/lively/files/12135188/lively_log_20230722_051152.zip)

**Comment by rocksdanister** [comment]
try this https://github.com/rocksdanister/lively/issues/1800#issuecomment-1645482712

**Comment by syb3rYT** [comment]
> try this [#1800 (comment)](https://github.com/rocksdanister/lively/issues/1800#issuecomment-1645482712)

bro it still doesnt work i get the same error

**Comment by rocksdanister** [comment]
Download mpv video player (32bit):
https://sourceforge.net/projects/mpv-player-windows/files/

Reproduce the crash and make a bug report here with the mpv log files (NOT lively log files):
https://github.com/mpv-player/mpv

(Its a project by different developers, make sure to follow the bug report template which has instructions to create log mpv log file.)

**Comment by syb3rYT** [comment]
> Download mpv video player (32bit): https://sourceforge.net/projects/mpv-player-windows/files/
> 
> Reproduce the crash and make a bug report here with the mpv log files (NOT lively log files): https://github.com/mpv-player/mpv
> 
> (Its a project by different developers, make sure to follow the bug report template which has instructions to create log mpv log file.)

just a quick doubt bro, to disable hyper v i disabled some files. could those files be the cause of this problem ?

**Comment by rocksdanister** [comment]
Hard to say, `Media Feature Pack` is required.. rest I dont know.

**Comment by syb3rYT** [comment]
> Hard to say, `Media Feature Pack` is required.. rest I dont know.

![image](https://github.com/rocksdanister/lively/assets/140216766/19d60b86-2a98-4480-9e39-53c8b2a48553)

could you check if the files which are needed is on or not pls

**Comment by rocksdanister** [comment]
Should be fine.

**Comment by syb3rYT** [comment]
> Should be fine.

i tried everything recommended and it doesnt work bro, can this be resolved with a reinstall or an update ?

**Comment by rocksdanister** [comment]
I already suggested what to do: https://github.com/rocksdanister/lively/issues/1803#issuecomment-1646352514

If you must avoid mpv you can use wmf player: 
https://github.com/rocksdanister/lively/wiki/Video-Guide#windows-media-foundation-wmf
