### ISSUE TITLE
Fluids turns to full white when switching from fullscreen app

### ISSUE THREAD

**Issue by SunnyMoo** [rocksdanister/lively#1805]
**Describe the bug**
After a while, switching from fullscreen app, fluid wallpaper goes to full white.
Pretty nasty on OLED monitor with dark theme.

**To Reproduce**
1. Set fluids as wallpaper
2. Disable audio visualizer, enable random splats, disable bloom and sunrays, bg color black, whatever the other options
3. Open something fullscreen, eg firefox
4. Wait a while then minimize
5. Enjoy the flashbang

**Expected behavior**
Suspended Fluids should have reset to full black.

**Desktop (please complete the following information):**
 - OS: Win11 v10.0.22621
- Fluids

**Additional context**
Lively is set to suspend on fullscreen, battery, energy saving, remote desktop.
Pause by display
Algorithm foreground process
Note: Dual monitor setup with lively set only on main hdr oled monitor.

**Log file (Important)**
[lively_log_20230722_234116.zip](https://github.com/rocksdanister/lively/files/12137271/lively_log_20230722_234116.zip)

**Comment by rocksdanister** [comment]
Does the issue still happen in latest version of Lively v2.0.7.4?

**Comment by SunnyMoo** [comment]
Hi,
sorry can't tell as I switched to Walllpaper Engine.
Best regards.
