### ISSUE TITLE
Requests NET framework 4.7.2 to be downloaded

### ISSUE THREAD

**Issue by SophisticatedMarshmallow** [rocksdanister/lively#1806]
![image](https://github.com/rocksdanister/lively/assets/140411038/3f9b33bd-b170-4070-bc43-51d08effb6ae)
[lively_log_20230724_192859.zip](https://github.com/rocksdanister/lively/files/12146674/lively_log_20230724_192859.zip)
I have NET FRAMEWORK 4.8.1 installed and if i downgrade it it might afftct performance of other apps pls suggest a good solution to this hope this reaches you.
Thank You.

**Comment by rocksdanister** [comment]
Multiple framework packages can be installed same time, it will not downgrade.

Are you using some modified version of Windows? framework v4.7.2 should be included with Windows.

**Comment by SophisticatedMarshmallow** [comment]
@rocksdanister sorry for the ping but it doesnt seem to install the application and i do have original windows 11..

**Comment by rocksdanister** [comment]
Not sure why this is happening, can be installed manually:
https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net472-web-installer
