### ISSUE TITLE
add support for windows 10 LTSC

### ISSUE THREAD

**Issue by kusanaginico** [rocksdanister/lively#1808]
Is your feature request related to a problem? : lively can't be installed in "win10 ltsc" even with backward comp.
so it would be nice to get support to this version of windows.
thanks in advance.
![livelyerror](https://github.com/rocksdanister/lively/assets/44915901/c41f0be3-d13f-4113-9fb3-40557fa7d76f)

**Comment by rocksdanister** [comment]
Installer require Windows 10 version 1903 or above.

ltsc is probably still at 1809, store version supports this:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions
