### ISSUE TITLE
Rains V2 With Duplicate on All Screens Doesn't Change BG Image on Non-Primary Screens

### ISSUE THREAD

**Issue by roblarky** [rocksdanister/lively#181]
**Describe the bug**
When using multiple screens configured with **Duplicate same wallpaper**, the Rain v2 **Image** (from Customize menu) is not honored on non-primary display(s).

**To Reproduce**
Select Rain v2 wallpaper, right-click and select Customize. Change the **Image** dropdown. The wallpaper's background image is not changed on non-primary screen(s).

**Expected behavior**
The background image should change on all screens when changing the **Image** dropdown selections.

**Screenshots/Video**
Below shows a portion of the desktop with red squares indicating the left, center (primary), and right screens. The selected image is only shown on the primary screen.

![image](https://user-images.githubusercontent.com/8843573/97781392-55c9d380-1b61-11eb-87ea-635070441356.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - 10.0.19042.572
- Which wallpaper was running at the time if any: Rain v2

**Additional context**
Prior to 1.1.2.1, the image wouldn't change at all, not even on the primary screen. But that now works, it just doesn't update on secondary screens.

**Log file**
[20201031_100008.txt](https://github.com/rocksdanister/lively/files/5469212/20201031_100008.txt)

**Comment by rocksdanister** [comment]
Its currently separate, you have to select the screen in Control Panel.
The reason I haven't made it change all at once is it requires a bit more testing, each value change writes to a separate livelyproperties.json file; if for example there are 8 screens or more could be a problem.

**Comment by roblarky** [comment]
Ah okay, does that also apply to the Random Splatter in Fluids V2? I notice that only affects the primary screen as well.

**Comment by rocksdanister** [comment]
Duplicate is just separate instances of the wallpaper launched sequentially by lively, so each wallpaper will behave independently yeah.

The customise menu in-app will be for the currently selected screen in Control Panel.

If you select Customise Wallpaper in system-tray you will get the Control Panel if more than one customisable wallpaper is running and from there you can select the screen to customise.

**Comment by roblarky** [comment]
Okay, so it's really just a UX issue, it doesn't seem intuitive in that regard so I assumed it must not be working right. I followed selecting and setting each screen and it works as expected.

I appreciate the ability to configure different things on each screen, as that was not also apparent. Also seems like perhaps on selecting a wallpaper, a modal could pop up asking the user which screens they want to apply it to. Just one thought, anyway.

That aside, now that I know how this works, the app is even better!  :)

**Comment by roblarky** [comment]
...also, I say this as user who doesn't bother to read a single thing about an app or how to use it  :-P

Of course, that's always the best perspective, in my experience, when working on UX.
