### ISSUE TITLE
lively esta com tela escura e informa erro na comunicação com servidor / lively has a dark screen and information error in communication with the server

### ISSUE THREAD

**Issue by pshigorlins** [rocksdanister/lively#1810]
on 07/25/2023, lively stopped working showing a black screen and a server error message when starting windows 11, when i went to reinstall the problem continues

no dia 25/07/2023 o lively parou de funcionar  mostrando tela preta e uma mensagem de erro de servidor ao iniciar o windows 11, quando fui reinstalar o problema continua
![Screenshot_1](https://github.com/rocksdanister/lively/assets/140566699/5972fb0f-c66d-49f8-9002-5641e596a203)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1691
