### ISSUE TITLE
Blurring other applications

### ISSUE THREAD

**Issue by caster110** [rocksdanister/lively#1813]
**Describe the bug**
This and another application blurring github desktop, Unity Hub.

**To Reproduce**
Just open Lively and another app, wait some time.

**Expected behavior**
I didn't expect problems

**Desktop (please complete the following information):**
- OS: [e.g. Windows 10 Home 22H2, OC 19045.3208]
- my self-created gif it too big to upload here name: "Delta_Green_1". I corrected gamma, brightness and other in settings of Lively
[lively_log_20230728_220535.zip](https://github.com/rocksdanister/lively/files/12195256/lively_log_20230728_220535.zip)

https://github.com/rocksdanister/lively/assets/70638491/935c891c-7649-4e19-b469-95148453da23

**Comment by rocksdanister** [comment]
Does this happen still when the Lively UI is closed but wallpaper running?
