### ISSUE TITLE
clock / time problem

### ISSUE THREAD

**Issue by ali291384** [rocksdanister/lively#1824]
**Describe the bug**
Whenever I use a clock-type wallpaper (it doesn't matter which type of clock), it displays the time incorrectly, showing it one hour ahead of the actual time. I have tried different clock-type wallpapers, but they all have the same issue.

**Expected behavior**
Showing time correctly instead of showing it one hour ahead of the actual time

**Screenshots/Video**
<img width="1036" alt="Screenshot_1" src="https://github.com/rocksdanister/lively/assets/99997635/98e44e91-1dea-4116-b1b9-855a98e497c3">
<img width="978" alt="Screenshot_2" src="https://github.com/rocksdanister/lively/assets/99997635/8edb5c51-73c5-4721-b1e2-1550dc72d6a5">
<img width="726" alt="Screenshot_3" src="https://github.com/rocksdanister/lively/assets/99997635/be7125e0-ccee-4ec9-ad0c-1f9a33c0eeda">

**Desktop (please complete the following information):**
 - OS: Edition	Windows 10 Pro
   Version	        21H2
   OS build	19044.2075
   Experience	Windows Feature Experience Pack 120.2212.4180.0

- Which wallpaper was running at the time if any: Any clock-type wallpapers.

**Log file (Important)**
[20230804_110243.txt](https://github.com/rocksdanister/lively/files/12258940/20230804_110243.txt)

**Comment by rocksdanister** [comment]
Make sure your system timezone is correct

https://forums.tomshardware.com/threads/google-chrome-time-not-matching-computer-time.2724682/

**Comment by ali291384** [comment]
> Make sure your system timezone is correct
> 
> https://forums.tomshardware.com/threads/google-chrome-time-not-matching-computer-time.2724682/

I have checked all clock settings and they are correct :
<img width="713" alt="Screenshot_1" src="https://github.com/rocksdanister/lively/assets/99997635/219306e3-cff9-44ca-8321-d4b0a9d4f8e1">

but when I open them in my browser every thing is ok :
<img width="1250" alt="Screenshot_2" src="https://github.com/rocksdanister/lively/assets/99997635/ef607bd3-2ec3-4ed1-bb03-5ea850e96b6f">
<img width="1250" alt="Screenshot_3" src="https://github.com/rocksdanister/lively/assets/99997635/fadea48d-2ffe-45e0-977c-6349d4b4a51f">
<img width="1248" alt="Screenshot_4" src="https://github.com/rocksdanister/lively/assets/99997635/7b4a634f-be6a-4141-b2a4-7be435f2fa5c">

 so strange!!!!!!!!!!!!!!!!!!!!

**Comment by rocksdanister** [comment]
@amaitland any idea whats happening?😅

**Comment by ali291384** [comment]
bro I solved the bug . just by reinstalling app :)
I'm sorry for taken time from you.

just a recommendation for app enhancement: pls add fade audio pause/play for wallpapers when focus changed between desktop and other app. It get on nerves when the sound of wallpapers suddenly stop.

tnx . be success :)
