### ISSUE TITLE
Error al iniciar

### ISSUE THREAD

**Issue by elro76** [rocksdanister/lively#1825]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by elro76** [comment]
Al iniciar la aaplicaion y seleccionar un fondo, aparece un error que dice:
"Establezca la clave
HKLM\Software\Microsoft\.NETFramework\InstallRoot del Registro para que apunte a la ubicacion de .NET Framework"

Como lo soluciono?
Gracias.
![error](https://github.com/rocksdanister/lively/assets/141502619/a5c002c4-f97a-4389-bad8-975415065628)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1806
