### ISSUE TITLE
Can I redefine the size of the video? (choose a fit) 

### ISSUE THREAD

**Issue by lukelifer** [rocksdanister/lively#1827]
Hey friends,

I was looking for a app that could play a video in my desktop but with a choose a fit with a center option. 

I like the black frame to put my icons.

If you guys could some day implement this feature will be awesome! Any way, thanks for the great work. 

Just like the left screen in this photo:

![fit](https://github.com/rocksdanister/lively/assets/39797798/881afc44-5758-4cd1-9840-e3aeab1bce18)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/334

This should be possible using mpv, need to figure out from the manual:
https://mpv.io/manual/master/
