### ISSUE TITLE
After suspend, videos are not restored, or are frozen

### ISSUE THREAD

**Issue by TerminatedProcess** [rocksdanister/lively#1828]
**Describe the bug**
I use Lively to play home movies on my desktop. I have two monitors (vertical, horizontal). After a suspend, video is often either gone or frozen. Quitting and restarting lively does not correct the issue. This has been happening a lot lately. It's possibly related to my backup software running (Macrium Reflect). The software does a suspend when done. I can also manually suspend and on restart, no videos or frozen or just one monitor has a video.  Change Wallpaper option in Lively dropdown menu does not start any new screensavers.

**To Reproduce**
1. Suspend

**Expected behavior**
Movies do not freeze or go way. At a minimum, would like a Lively menu bar option to reload videos as if I was manually selecting them again. Just quitting and restarting Lively doesn't seem to do this.

**Desktop (please complete the following information):**
 - OS: 
   Windows 11 Pro Insider Preview Build 25921.rs_prerelease_230728-1521

- Which wallpaper was running at the time if any. 
   MPG Video files on both monitors.

**Additional context**
Some ideas about this. My vertical monitor is connected via a usb to hdmi. Possible this is a wakeup timing issue and lively is looking for the 2nd monitor but not finding it. But the 1st monitor shouldn't be freezing the video. It's a straight HDMI connection. 

**Log file (Important)**
Share the diagnostic files by:
https://drive.google.com/file/d/1czBYd_y3li6416fGXFQk0M8kx1zsf5Lt/view?usp=sharing
[lively_log_20230806_140910.zip](https://github.com/rocksdanister/lively/files/12270173/lively_log_20230806_140910.zip)

**Comment by rocksdanister** [comment]
Could be graphics driver related, try turning off `GPU decode`
<img width="702" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/656177c7-62c6-4b39-9726-b2c4e9c6e4c6">

```
GPU: Insignia USB3.0 to dual HDMI
GPU: Intel(R) UHD Graphics 630
GPU: NVIDIA GeForce GTX 1060
```

The virtual gpu could be also the cause, I see a lot of screen disconnecting events.

**Comment by TerminatedProcess** [comment]
Hmm, did this and suspended. It restored normally when I woke it up. I'll let you know if it comes back. Thanks Dani!

**Comment by TerminatedProcess** [comment]
Hey Dan,
Just in case this is of interest to  you, I saw on the windows store that there's more than one version of Lively.  There is one called Lively Wallpaper Metro which is based on your Lively. I installed it and when I first opened it, it immediately opened a popup offering to get me a PDF software. It also opened a website (without prompting). The website was flagged by Malwarebytes (I pay for the realtime protection). Your product doesn't do this. I left a review for the other product in the store stating what happened. The website is "xwww.winappcenter.com"  (remove the x)

Thanks
Mark Ryan

**Comment by TerminatedProcess** [comment]
Hi Dan,

I fully uninstalled Lively and re-installed it. I then imported my videos I like to play. But when I try to set a desktop (I have two), nothing happens. I'm seeing this when I attempt it.. The blue entries move up and eventually disappear. I'm fully updated. I have the latest NVIDA driver, Intel drivers, and run in a Windows 11 Dev (maybe Canary now, not sure). I tried setting the GPU Decode on and off, but it has no impact. Any ideas? If you need me too, ask me to file a proper bug through the software. I just wanted to show you the screenshots.

***@***.***

**Comment by rocksdanister** [comment]
>Windows 11 Dev

There is a new Windows HDR wallpaper feature, its likely causing issue.

I don't update for preview versions of Windows because things are prone to change on Microsoft side.

If your display has HDR support you can try turning it OFF in Windows settings and restart Lively.

**Comment by TerminatedProcess** [comment]
Ok so I'll just try it from time to time and hope it works again someday.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TerminatedProcess** [comment]
Hey man!

I never noticed you had a patreon channel. I just joined. Hope you get some beers out of it.

Mark Ryan (terminatedprocess)

**Comment by TerminatedProcess** [comment]
I set the Settings/Wallpaper/Plugins/GPU Decode option off. I also received a new update from M$. Wallpapers are now working as expected. Thanks!
