### ISSUE TITLE
Music Wallpapers Not Working

### ISSUE THREAD

**Issue by RepsFrl** [rocksdanister/lively#1831]
"No Signal" is displayed while a song is playing on a supported app like Spotify. This happens with any of the music apps. Audio visualizers do work. 

1. Just start up Lively
2. Play a song via Spotify

**Expected behavior**
To see the album/song cover/image displayed and additional information

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/141696154/5f7b25c4-80d8-45cf-8acc-e92df0128cb8)

**Log file**
[lively_log_20230808_052237.zip](https://github.com/rocksdanister/lively/files/12286936/lively_log_20230808_052237.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#music-wallpapers-dont-show-albumart-or-track-information

**Comment by RepsFrl** [comment]
Thanks It solved the issue
