### ISSUE TITLE
Music visualizer 

### ISSUE THREAD

**Issue by Dubstop26789** [rocksdanister/lively#1835]
It would be cool if the there were more live music visualizers like in the Music TV. I personally would love a visualizer in the style of either Simple System or The Hill

**Comment by Paulchemouni** [comment]
I would also love if there was a visualizer who would just put the album art without anything else as a wallpaper, with a blur around, like the GNS app does for android ([https://play.google.com/store/apps/details?id=com.mejmun.goodnightspotify&hl=fr&gl=US](url))
