### ISSUE TITLE
Integer/Nearest neighbor scaling for gif wallpaper.

### ISSUE THREAD

**Issue by nonounen** [rocksdanister/lively#184]
I don't know if Bitmap Scaling is the right term for it, but basically if i use a low res .gif (in this case 500x374) to fill the entire screen, it looks blurry.
This is a lively wallpaper screenshot from my desktop
https://imgur.com/gBOdbjU

This is screenshot from image viewer (Zoom 400%)
https://imgur.com/s0eNJCO

it'd be great if there's an option to choose the scaling mode

**Comment by rocksdanister** [comment]
Yeah integer/Nearest neighbor scaling makes sense for pixel art style images.
I just had a look, it seems like its not that simple to do this in the new uwp image control unlike the old wpf one.

**Comment by rocksdanister** [comment]
I added gif playback through libMPV(External) player and switches to integer scaling automatically.
Next update (v1.1.4.0) will have gif player selection option in settings.
