### ISSUE TITLE
Application quits whenever "Open Lively" selected from Taskbar

### ISSUE THREAD

**Issue by AC1DFOX** [rocksdanister/lively#1841]
**Describe the bug**
When Right clicking the app in the system tray, and selecting to open it, the app pops up as a black screen before quitting. 

**To Reproduce**
1. Go to 'Taskbar'
2. Click on 'Lively Icon'
3. Select 'Open Lively'

**Expected behavior**
When performing this action, the application SHOULD open. 

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2, 22621.2134

- Which wallpaper was running at the time if any.
- 

**Additional context**

**Log file (Important)**

[lively_log_20230814_082308.zip](https://github.com/rocksdanister/lively/files/12335067/lively_log_20230814_082308.zip)
![Lively Error](https://github.com/rocksdanister/lively/assets/75289053/34cb4999-18b5-4d61-9dc0-7c012891b61c)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1691
