### ISSUE TITLE
When I set wallpaper via command line, it stops screensaver mode

### ISSUE THREAD

**Issue by Gus1994** [rocksdanister/lively#1848]
Hello, thanks a lot for this amazing app !
I have a question/issue, I am randomizing my wallpaper via a powershell script and the command line:
`setwp --file <file-path> --monitor <screen-id>`
I also use the screensaver to display beautiful videos.
Whenever ma "randomize wall paper screen" changes, it goes out of screen saver mode but there hasn't been any user actions on windows (mouse mouvement or keyboard press).
I don't know if lively was designed for my use case but i was wandering if there is any solutions for that :)
Thansk again

**Comment by rocksdanister** [comment]
Wallpaper change will turn off screensaver.

You can trigger the screensaver again using commandline.

**Comment by Gus1994** [comment]
Yes, this is the approach I have, there seems to be a 5-10 seconds delay for lively to accept new commands, is this normal?

**Comment by rocksdanister** [comment]
As long as you are using command utility there should not be a delay, commands are not queued so when you change wallpaper it will take some seconds.. so wait a few seconds before sending screensaver command.
