### ISSUE TITLE
One or more errors occurred (no process is associated with this object) when selecting video wallpaper

### ISSUE THREAD

**Issue by ALMEXCZ** [rocksdanister/lively#1850]
**Describe the bug**
cant load any wallpaper

**To Reproduce**
Steps to reproduce
no idea

**Expected behavior**
it tirs but then error

**Screenshots/Video**
![Snímek obrazovky (4)](https://github.com/rocksdanister/lively/assets/142801485/52ae0d8e-c5e1-40ed-afe0-28b55ea139cb)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
- Which wallpaper was running at the time if any.

**Log file (Important)**
[20230821_134937.txt](https://github.com/rocksdanister/lively/files/12395631/20230821_134937.txt)

**Comment by rocksdanister** [comment]
Turn OFF `GPU Decode` in Settings -> Wallpaper -> Video player.
