### ISSUE TITLE
Lively wallpaper stops working when my screen turns off.

### ISSUE THREAD

**Issue by Alexiouss76** [rocksdanister/lively#1856]
For some time I have noticed that simply turning off my screen after a period of inactivity on the computer (and not going to sleep) causes the animated wallpaper to stop when I move the mouse to turn it on again (tried with several wallpapers and several options). Any idea of the reason? I'm on windows 11.

**Comment by Alexiouss76** [comment]
This bug disappears when the taskbar is programmed to be automatically hidden.

**Comment by cldylan** [comment]
i have the same problem!

**Comment by rocksdanister** [comment]
This should be fixed in the latest update v7.0.4.0

If the bug happens again then create a log report file and share here: Right-click tray-icon -> Report Bug -> Create log report file.
