### ISSUE TITLE
Slowly pan across image and/or pick a random portion of image to display.

### ISSUE THREAD

**Issue by duckduckdog** [rocksdanister/lively#1857]
I love the app, it's amazing something so powerful is also free. The depth tool is super neat as well.

I have hundreds of images which are either wider or taller than my monitor's resolution & would love an option to slowly pan across ( a panorama could look great across a whole day & could even be designed to fade to nigh time colors or emulate the temperature of daylight). 

Failing that I'd enjoy an option to simply pick a random selection of the image to display as my wallpaper. I have enjoy having my wallpapers cycle regularly & a different starting point would add a lot of variety.
 
I've looked at a half dozen different wallpaper managers & none provide more options than windows (tile, center, fit, span). I appreciate this might be a little limited for Lively Wallpaper, but no one else is in your wheel house. Thank you for your consideration! and thank you for donating so many manhours. 

To say it all another way, my monitor is 2560 x 1440. I have a bunch of wallpapers that are either 4000 x 1440 or 2560 x 4000. I'd like to pan across them or failing that display a random portion.

**Comment by rocksdanister** [comment]
> I have hundreds of images which are either wider or taller than my monitor's resolution & would love an option to slowly pan across ( a panorama could look great across a whole day & could even be designed to fade to nigh time colors or emulate the temperature of daylight).

This is best done by creating a custom html wallpaper with animation and not be part of the application itself, so closing this.

> Failing that I'd enjoy an option to simply pick a random selection of the image to display as my wallpaper. I have enjoy having my wallpapers cycle regularly & a different starting point would add a lot of variety.

Random selection is coming in a future update.
