### ISSUE TITLE
Current wallpaper breaks when changing resolutions (Windows 11 insider)

### ISSUE THREAD

**Issue by Tiger-I-Yang** [rocksdanister/lively#1860]
**Describe the bug**
Current wallpaper breaks when changing resolutions on windows 11 insider dev 23531.1001 ni_prerelease build, and any new wallpapers fail immediately too, until closing and restarting lively

**To Reproduce**
put on a lively wallpaper
change resolutions using settings or via a script
observe that the wallpaper stops, and trying to relaunch it and any other wallpaper fails
exit lively via the system tray and restart it
set your wallpaper again and observe that it works again

**Expected behavior**
put on a lively wallpaper
change resolutions using settings or via a script
observe that the wallpaper doesn't stop and adapts to the new resolution

**Screenshots/Video**
https://github.com/rocksdanister/lively/assets/117319831/c16527be-9c26-409c-ac48-673e52c3e0c0

**Desktop (please complete the following information):**
 - OS: windows 11 insider dev 23531.1001 ni_prerelease build
- video wallpaper

**Additional context**
I also have rainmeter if that helps

**Log file (Important)**
[lively_log_20230826_210621.zip](https://github.com/rocksdanister/lively/files/12447214/lively_log_20230826_210621.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/1814

Insider channel changes things frequently, will have to wait and see.

**Comment by DigitalAge3000** [comment]
Noticed that bug too. Same OS. Lively also stops working when I turn on or switch off my 2nd monitor. Need to close and restart Lively to make it work again.
