### ISSUE TITLE
Disability after starting up everytime

### ISSUE THREAD

**Issue by faiz010101** [rocksdanister/lively#1862]
**Describe the bug**
I have put a live wallpaper through the lively but it is getting disabled overtime when I start up my pc again I find the default wallpaper everyday and I have to open lively to show my selected wallpaper on the screen.

**To Reproduce**

**Expected behavior**
I expect that I don't have to open lively everytime to get my wallpaper live and I want it to be running in the background so I would not have to open the software repeatedly.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 2022
- Which wallpaper "Chillhop White Oak"
[lively_log_20230827_121720.zip](https://github.com/rocksdanister/lively/files/12447420/lively_log_20230827_121720.zip)
.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Did you try waiting for lively to start? During this time you will see the regular desktop background.
