### ISSUE TITLE
The UI doesn't show, but app is running in background !

### ISSUE THREAD

**Issue by FA-TAAA** [rocksdanister/lively#1863]
The app is working, but I cannot configure it whatsoever because of Lively's window not showing

1. Go to taskbar
2. Click on Lively Wallpaper system tray icon
3. Right Click on Lively Wallpaper
4. Click on open lively
5. The app UI doesn't show but still runs in background

**Expected behavior**
The UI/Window to show up.

**Screenshots/Video**

https://github.com/rocksdanister/lively/assets/95973966/19edcc65-db40-4d4e-b517-9bb8bdf67e15

**Desktop (please complete the following information):**
 - Windows 11 22H2
- Idk, I just installed

**Additional context**

**Log file (Important)**
[logs.zip](https://github.com/rocksdanister/lively/files/12447434/logs.zip)

**Comment by Yincognyto** [comment]
I have the same problem, this time on Windows 10 version 2009 (10.0.19043.1202) and a laptop with an integrated AMD Radeon RX Vega 6 and a dedicated NVIDIA GeForce GTX 1650 graphic card. This, coupled with the program being added at startup despite specifically told not to at installation, don't make it exactly reliable, to put it gently...

[lively_log_20231005_185328.zip](https://github.com/rocksdanister/lively/files/12831919/lively_log_20231005_185328.zip)

**Comment by Takeoff0518** [comment]
I have the same problem, too. When I start Lively, the UI disappears after a brief appearance but it runs normally in the background (and the tray is okay). It's on Windows 11 22H2(22621.2715), and GPU is NVIDIA GeForce RTX 3050 Laptop.

**Comment by ZacharyChiu** [comment]
I got the same bug. Did you guys solve the issue? 
The Wallpaper worked, but I could not open the main Window (to configure some settings). When I try to open the main window, a black window appear, and disappear in seconds.
My system is Win11 23H2.

**Comment by rocksdanister** [comment]
This is a duplicate issue (can be found under the label framework.)
I originally reported to Microsoft with my understanding this as a WinUI3 framework bug.. since the last update there has been many updates to WinUI and this issue may be fixed but you will have to wait for the next release to check (this month) or build the project and check yourself.
