### ISSUE TITLE
I can't use the latest lively wallpaper. system not responding

### ISSUE THREAD

**Issue by SPRINTER2499** [rocksdanister/lively#1865]
**Describe the bug**
I can use lively version 2.0.2.4

But I can't use higher version.  

**To Reproduce**
1. Install lively wallpapers in the Microsoft Store and older versions through a web browser.
2. Click on the lively program.
3. Then the program says Not Responding.

**Expected behavior**
Want to use lively in version 2.0.6.0 or latest version.

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Additional context**
![lively](https://github.com/rocksdanister/lively/assets/143374206/9d5c1587-b7db-4738-b470-4ecc2482133e)

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System 
-> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20230829_074656.zip](https://github.com/rocksdanister/lively/files/12459157/lively_log_20230829_074656.zip)

**Comment by SPRINTER2499** [comment]
**_help me !!!!_**

**Comment by TIKTOKKER2539** [comment]
### **i am like you**
@SPRINTER2499 

@rocksdanister
 PLS'
