### ISSUE TITLE
Request to add Live2D SDK

### ISSUE THREAD

**Issue by QuickerStudio** [rocksdanister/lively#1869]
** request cross-platform support **

Request support for Apple mobile phone and Android mobile system.

** add live2d **
Live2D SDK Download here: https://www.live2d.com/en/download/cubism-sdk/

**Comment by rocksdanister** [comment]
I can't see the license for the SDK, since Lively is GPL license linking will require some work  based on its license.

**Comment by QuickerStudio** [comment]
Live SDK Licence here:
https://www.live2d.com/en/download/cubism-sdk/release-license/

**Comment by rocksdanister** [comment]
Commercial license, not compatible with GPLv3.
