### ISSUE TITLE
The wallpaper stops acting like a desktop screen 

### ISSUE THREAD

**Issue by Tumbuleweed** [rocksdanister/lively#187]
The wallpaper that i chose opens up a separate tab and isn't apart of the desktop at all, it happened after i accidentally set a solid color as my desktop background after dong that i reopened the lively application and clicked on the wallpaper i wanted but the aforementioned problem occurred 

![Screenshot_4](https://user-images.githubusercontent.com/74076496/98417276-e27f0080-203d-11eb-9df1-7798948a8b5d.png)
![Screenshot_5](https://user-images.githubusercontent.com/74076496/98417302-f0348600-203d-11eb-8183-2defd5664b2c.png)

**Comment by rocksdanister** [comment]
1. Does it still happen after you exit lively (traymenu -> exit) and reopen it?
2. Does it still happen after Windows restart?

I can't recreate this error.

**Comment by FakeSkipper101** [comment]
When I tried to change my wallpaper into the Fluidv2, the Fluidv2 doesn't appear. I also tried downloading a GIF and setting it as my wallpaper but it comes out as a "GIFViewUWP". I tried to download another GIF but it comes out as "MainWindow". So far I don't know how to fix it.

**Comment by rocksdanister** [comment]
1. Does any of the included wallpaper work fine? if so which ones?
2. Have you tried restarting windows?
3. For GIFs try changing gifplayer to libmpv(Ext) in Lively settings -> Wallpaper

**Comment by rocksdanister** [comment]
Resolved:
https://github.com/rocksdanister/lively/releases/tag/v1.1.9.2
