### ISSUE TITLE
将背景设置为网址时，不会刷新网页内容

### ISSUE THREAD

**Issue by githublife** [rocksdanister/lively#1870]
如果设置网址为壁纸后，能定时刷新就太棒了。

**Comment by ecr-oha-lime** [comment]
这个不是bug
这就相当于将一个浏览器页面
所以没有刷新是正常的啊
可以添加个定时刷新的功能

**Comment by ecr-oha-lime** [comment]
应该把标签改成增强而不是bug

整个自动刷新，但是间隔必须得大于2分钟，不然可能会被当成ddos。
或者可能打死网站的服务器，如果网站的服务器配置不高而有比较多的人作为壁纸并打开了自动刷新的话。
rock 还得记得是重新请求壁纸链接而不是简单的刷新网页，否则如果作为壁纸的网页是API将不会刷新内容。例如这个
‘’‘
https://bing.shangzhenyang.com/api/1080p
’‘’
单纯刷新不会向API请求而是刷新图片

**Comment by Ryanjiang2009** [comment]
或者整个局部刷新，亦或缓存静态内容到本地然后ajax等动态转发至服务器



在 2023-10-01 20:40:16，"ecr-lime" ***@***.***> 写道：

应该把标签改成增强

整个自动刷新，但是间隔必须得大于2分钟，不然可能会被当成ddos。
或者可能打死网站的服务器，如果网站的服务器配置不高而有比较多的人作为壁纸并打开了自动刷新的话。
rock 还得记得是重新请求壁纸链接而不是简单的刷新网页，否则如果作为壁纸的网页是API将不会刷新内容。例如这个
‘’‘
https://bing.shangzhenyang.com/api/1080p
’‘’
单纯刷新不会向API请求而是刷新图片

**Comment by Ryanjiang2009** [comment]
新想法：桌面漏出来就刷，桌面可见就每隔一段时间刷一次，不可见就保持



在 2023-10-01 20:40:16，"ecr-lime" ***@***.***> 写道：

应该把标签改成增强

整个自动刷新，但是间隔必须得大于2分钟，不然可能会被当成ddos。
或者可能打死网站的服务器，如果网站的服务器配置不高而有比较多的人作为壁纸并打开了自动刷新的话。
rock 还得记得是重新请求壁纸链接而不是简单的刷新网页，否则如果作为壁纸的网页是API将不会刷新内容。例如这个
‘’‘
https://bing.shangzhenyang.com/api/1080p
’‘’
单纯刷新不会向API请求而是刷新图片

**Comment by githublife** [comment]
不知道标签要怎么才能改内呢。

**Comment by githublife** [comment]
新版本有实现这个吗
