### ISSUE TITLE
[Feature Request] Allow toggling keyboard input for web wallpaper

### ISSUE THREAD

**Issue by linuzzx** [rocksdanister/lively#1873]
**Is your feature request related to a problem? Please describe.**
I want to use relaxingclock.com as my wallpaper and need keyboard access for signing into spotify for example.

**Describe the solution you'd like**
A toggle in the wallpaper settings for allowing keyboard and/or mouse.

**Describe alternatives you've considered**
allow manually setting cookies?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#can-i-login-to-websites

<img width="647" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/4042feb4-5344-4b46-b281-4980196541f4">

**Comment by linuzzx** [comment]
oh sorry, thanks so much, I love this program

Dani John ***@***.***> schrieb am Fr., 1. Sept. 2023, 01:06:
