### ISSUE TITLE
wallpaper not pause when focus on discord

### ISSUE THREAD

**Issue by haniframadhani** [rocksdanister/lively#1875]
**Describe the bug**
the wallpaper keep playing when the window focus on discord window. wallpaper pause on another app. I have set wallpaper to pause when open full screen app or focus on a app window.

**To Reproduce**
1. Go to setting
2. set wallpaper playback on application fullscreen to pause
3. set wallpaper playback on application focused to pause

**Expected behavior**
wallpaper pause everytime focus to a window or a fullscreen app

**Screenshots/Video**
[wallpaper not pause when focus on discord](https://github-production-user-asset-6210df.s3.amazonaws.com/69223521/265016527-857c2985-2c7a-4cb9-b175-c998bb167f1c.mp4)
https://cdn.discordapp.com/attachments/736056645355962391/1147143747314913342/lively-bug-report.mp4
https://github.com/rocksdanister/lively/assets/69223521/857c2985-2c7a-4cb9-b175-c998bb167f1c

**Desktop (please complete the following information):**
 - OS: windows 11 22h2 22621.2134
- Which wallpaper was running at the time if any.

**Log file (Important)**
Share the diagnostic files by:
[lively_log_20230901_184824.zip](https://github.com/rocksdanister/lively/files/12497717/lively_log_20230901_184824.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/789#issuecomment-1148548562
