### ISSUE TITLE
Add quality management software, to the final output!

### ISSUE THREAD

**Issue by QuickerStudio** [rocksdanister/lively#1877]
Codeformer, Final2x, Handbrake 

  Add some of these software's codes to the final image output, always get the best background image.and finally read the screen resolution to match the display mode to correct the distortion problem! Add quality management software, to the final output!
Check here:

Codeformer: https://github.com/sczhou/CodeFormer

Final2x: https://github.com/Tohrusky/Final2x-core

Handbrake: https://github.com/HandBrake/HandBrake

Program steps:
Video input final2x frame enlargement > codeformer noise reduction > handbrake compression volume.

Image input > read screen resolution > calculate magnification value > final2x zoom frame > match display mode.

The work is tough, but the end result will be impressive!

**Comment by rocksdanister** [comment]
This cannot be added as the license is incompatible.
