### ISSUE TITLE
Unable to call GPU to play 4K video

### ISSUE THREAD

**Issue by QuickerStudio** [rocksdanister/lively#1881]
![image](https://github.com/rocksdanister/lively/assets/26364832/8402decd-09f5-4df2-86bb-a77728007ccb)

CPU Running on 100% 
GPU No Work on 4K

**Comment by rocksdanister** [comment]
For wallpaper 1080p x264 format is recommended:
https://github.com/rocksdanister/lively/wiki/Performance
