### ISSUE TITLE
Both display options only showing on one monitor

### ISSUE THREAD

**Issue by BLACKDEATH6540** [rocksdanister/lively#1886]
### _Describe the bug_

So when I choose the option "Selected screen only" and select a screen to put my wallpaper on , both buttons "Screen 1" and "Screen 2" applies the wallpaper to the same monitor. On interactive wallpapers like "Fluids" it picks up the mouse movements from both displays and interacts with the wallpaper on the one display. The option "Duplicate same wallpaper" does the same thing but "span across screens" works fine. I can't find a fix for it anywhere. 

When I first got Lively years ago it never did this.

Sorry for low quality this is all I could upload.

https://github.com/rocksdanister/lively/assets/54505474/e337baf4-a30d-4261-9fa5-0dec144aca08

Sorry for low quality this is all I could upload.

![DevLog](https://github.com/rocksdanister/lively/assets/54505474/2e0ca1a7-1b83-474f-bd7a-4759246837b9)

**Log file (Important)**
[20230909_183734.txt](https://github.com/rocksdanister/lively/files/12566964/20230909_183734.txt)

**Comment by rocksdanister** [comment]
Share the generated logfile (I need to see the monitor data.)

Right click trayicon -> Create log report file.

**Comment by BLACKDEATH6540** [comment]
[lively_log_20231015_115632.zip](https://github.com/rocksdanister/lively/files/12910166/lively_log_20231015_115632.zip)

**Comment by rocksdanister** [comment]
Where you running both wallpapers at the time the log is created because I only see one screen in the wallpaper list.

Are the displays standard monitors or are they special kind of device like portable laptop display etc?

**Comment by BLACKDEATH6540** [comment]
[lively_log_20231015_135832.zip](https://github.com/rocksdanister/lively/files/12910436/lively_log_20231015_135832.zip)

Here is another log file, I equipped the wallpaper to both screens then created the log file.

I'm using a Desktop pc with a RTX 2060 Super, I am using a LG Ultragear 27" (1920 x 1080, 144 Hz) for my main monitor, and a Samsung 32" (set to 2560 x 1440, 60 Hz).
