### ISSUE TITLE
App not starting / 双击启动图标后，不显示界面，无法启动

### ISSUE THREAD

**Issue by haolive** [rocksdanister/lively#189]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**
双击启动图标后，不显示界面，无法启动，任务栏显示desktopwindow....后自动关闭。
**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file**
Share the log file(s) from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs
[20201108_181553.txt](https://github.com/rocksdanister/lively/files/5506150/20201108_181553.txt)

**Comment by rocksdanister** [comment]
I think this is some issue with xaml island itself!
1. Can you try running any [Microsoft windows store](https://www.microsoft.com/en-in/store/apps/windows) application and see it works?
2. Have you ran any Windows 10 optimization scripts/programs from the internet?
3. Can you try running [Powertoys](https://github.com/microsoft/PowerToys/releases), it uses similar technology as Lively.

**Comment by haolive** [comment]
> I think this is some issue with xaml island itself!
> 
> 1. Can you try running any [Microsoft windows store](https://www.microsoft.com/en-in/store/apps/windows) application and see it works?
> 2. Have you ran any Windows 10 optimization scripts/programs from the internet?
> 3. Can you try running [Powertoys](https://github.com/microsoft/PowerToys/releases), it uses similar technology as Lively.

1、首先，我可以打开微软商店，也可以在里面安装应用
2、我应该没有运行win10优化脚本，系统是别人精简过的，上次也是同一个人精简的，但是可以打开lively wallpaper
3、我刚刚安装了Powertoys，也打开了Powertoys，版本号是0.25

1. First of all, I can open the Microsoft Store and install apps in it

2. I should not have run the win10 optimization script. The system has been simplified by someone else. Last time, the same person simplified it, but you can open the live wallpaper

3. I just installed PowerToys and opened PowerToys. The version number is 0.25

[20201109_200752.txt](https://github.com/rocksdanister/lively/files/5510476/20201109_200752.txt)
[20201109_201752.txt](https://github.com/rocksdanister/lively/files/5510477/20201109_201752.txt)

**Comment by rocksdanister** [comment]
Did you install the Visual C++ Redistributable that comes with the setup: 
[vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe)

One of the requirement of xaml island:
`If your application is not packaged in an MSIX package for deployment, the computer must have the Visual C++ Runtime installed.`

**Comment by haolive** [comment]
> Did you install the Visual C++ Redistributable that comes with the setup:
> [vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe)
> 
> One of the requirement of xaml island:
> `If your application is not packaged in an MSIX package for deployment, the computer must have the Visual C++ Runtime installed.`


1、谢谢，我重装系统后已经安装了所有的Visual C++运行库，如下
Microsoft Visual C 旧版运行库
Microsoft Visual C++ 2005 SP1(8.0.61187)
Microsoft Visual C++ 2008 SP1(9.0.30729.7523)
Microsoft Visual C++ 2010 SP1(10.0.40219.473)
Microsoft Visual C++ 2012 up4(11.0.61135)
Microsoft Visual C++ 2013(12.0.40664)
Microsoft Visual C++ 2015-2019(14.28.29515.1)
2、遗憾的是，我刚刚下载并安装了你提供的Visual C++，重启后还是不能打开lively wallpaper

1. Thank you. I have installed all the visual c++ runtime after I re installed the system, as follows

Microsoft Visual C legacy runtime

Microsoft Visual C++ 2005 SP1(8.0.61187)

Microsoft Visual C++ 2008 SP1(9.0.30729.7523)

Microsoft Visual C++ 2010 SP1(10.0.40219.473)

Microsoft Visual C++ 2012 up4(11.0.61135)

Microsoft Visual C++ 2013(12.0.40664)

Microsoft Visual C++ 2015-2019(14.28.29515.1)

2. Unfortunately, I just downloaded and installed the visual c++ provided by you. After restart, I still can't open the level wallpper
3、logs
[20201111_191513.txt](https://github.com/rocksdanister/lively/files/5523755/20201111_191513.txt)
[20201111_185935.txt](https://github.com/rocksdanister/lively/files/5523751/20201111_185935.txt)
[20201111_190301.txt](https://github.com/rocksdanister/lively/files/5523752/20201111_190301.txt)
[20201111_190348.txt](https://github.com/rocksdanister/lively/files/5523753/20201111_190348.txt)
[20201111_190559.txt](https://github.com/rocksdanister/lively/files/5523754/20201111_190559.txt)

**Comment by rocksdanister** [comment]
Can you try the latest beta build:
https://github.com/rocksdanister/lively-beta/releases

**Comment by haolive** [comment]
> Can you try the latest beta build:
> https://github.com/rocksdanister/lively-beta/releases

1. I downloaded and installed lively_ setup_ x86_ full_ V1131.exe, still can't open

2. Uninstall all VC + + libraries and re install lively_ setup_ x86_ full_ V1131.exe, unable to open

3. Re install all VC + + runtime libraries, and then install lively again_ setup_ x86_ full_ v1131.exe

, unable to open

Here are the logs of these times:
[20201115_165107.txt](https://github.com/rocksdanister/lively/files/5542054/20201115_165107.txt)
[20201115_165256.txt](https://github.com/rocksdanister/lively/files/5542055/20201115_165256.txt)
[20201115_165529.txt](https://github.com/rocksdanister/lively/files/5542056/20201115_165529.txt)
[20201115_165932.txt](https://github.com/rocksdanister/lively/files/5542057/20201115_165932.txt)
[20201115_170033.txt](https://github.com/rocksdanister/lively/files/5542058/20201115_170033.txt)
[20201115_170210.txt](https://github.com/rocksdanister/lively/files/5542059/20201115_170210.txt)

**Comment by haolive** [comment]
I don't have the path C: users / rocks / source / repos / liveywpf / liveywpf / views in my computer. Is this normal?

**Comment by haolive** [comment]
Just now, I re installed the system, and then installed the live wallpaper for the first time. I found that it could not be opened. I think it is the reason for my computer system.

**Comment by rocksdanister** [comment]
>I don't have the path C: users / rocks / source / repos / liveywpf / liveywpf / views in my computer. Is this normal?

I don't think that's a problem.
I am making a simpler version of Lively for other distributing platforms which should not give these errors, just wait a bit.

**Comment by rocksdanister** [comment]
@haolive Can you try the Windows Store version?
https://www.microsoft.com/store/apps/9NTM2QC6QWS7

**Comment by haolive** [comment]
> @haolive Can you try the Windows Store version?
> https://www.microsoft.com/store/apps/9NTM2QC6QWS7

I just installed it from the store. I tried to open it. Thank you.

**Comment by yiuwacheng** [comment]
写中文他们也能看懂🐎

**Comment by rocksdanister** [comment]
I just use [Google translate.](https://translate.google.co.in/)
