### ISSUE TITLE
电脑重启后，动态壁纸是静止的

### ISSUE THREAD

**Issue by xing403** [rocksdanister/lively#1893]
当在使用这个app时，重启之前是正常的，但是在重启之后，虽然app启动了，但是动态壁纸是静态的，进入app中再次将该壁纸设为桌面壁纸时又可以动态显示了
![image](https://github.com/rocksdanister/lively/assets/74746021/44a4f69b-6566-4dc0-bade-bd21115e4820)

**Comment by rocksdanister** [comment]
Are you using Windows 11 beta/dev version? there is a breaking change in Windows side (HDR wallpaper support.)

**Comment by xing403** [comment]
version: [lively_setup_x86_full_v2070.exe](https://github.com/rocksdanister/lively/releases/download/v2.0.7.0/lively_setup_x86_full_v2070.exe)
system: Windows 11

**Comment by rocksdanister** [comment]
Attach the log .zip file:
<img width="647" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/2b43707b-92f3-4b64-b9de-4ba95b059310">

**Comment by xing403** [comment]
[lively_log_20230912_160259.zip](https://github.com/rocksdanister/lively/files/12583921/lively_log_20230912_160259.zip)

**Comment by rocksdanister** [comment]
Can you verify with the latest v2.0.7.4 if the issue is fixed?
