### ISSUE TITLE
Multiple video loop.

### ISSUE THREAD

**Issue by Masterpiece-K** [rocksdanister/lively#190]
I hope you can add a feature that let it play multiple videos in a loop.

**Comment by rocksdanister** [comment]
Duplicate of this ?: https://github.com/rocksdanister/lively/issues/137

**Comment by Masterpiece-K** [comment]
I mean I can put multiple wallpapers and have them looping around the desktop.

**Comment by rocksdanister** [comment]
Yes, this will be possible in [Wallpaper Playlist](https://github.com/rocksdanister/lively/issues/137) once implemented.

Marking it as duplicate.

**Comment by Masterpiece-K** [comment]
OK，thank u
