### ISSUE TITLE
The app becomes unresponsive after some time

### ISSUE THREAD

**Issue by Kunvar-Singh** [rocksdanister/lively#1901]
A few minutes after booting up, the app freezes and stops responding. I can't open the app or change the wallpaper; even my current wallpaper freezes and stops playing. When this happens, I have no choice but to kill the app and restart it every time.
What's worse is that if the app freezes before I shutdown, it will be frozen the next time I startup my laptop.
[lively_log_20230918_160408.zip](https://github.com/rocksdanister/lively/files/12657403/lively_log_20230918_160408.zip)

**Comment by rocksdanister** [comment]
Did this start happening after 22H2 update?

**Comment by Kunvar-Singh** [comment]
> Did this start happening after 22H2 update?

It started quite some time after that like at least a few months later

**Comment by rocksdanister** [comment]
Can you verify with the latest v2.0.7.4 if the issue is fixed?

**Comment by Kunvar-Singh** [comment]
Yes, the issue has been fixed. I've been noticing it for some days now. Thank you!
