### ISSUE TITLE
When I used fences, it always showed the color palette of the original desktop Wallpaper instead of Lively Wallpaper

### ISSUE THREAD

**Issue by xiaodeme-aha** [rocksdanister/lively#1902]
When I used fences, it always showed the color palette of the original desktop Wallpaper instead of Lively Wallpaper
![image](https://github.com/rocksdanister/lively/assets/62629091/f91ec1b8-1027-4d1c-afcd-f7991674e190)

**Comment by rocksdanister** [comment]
Turning on desktop picture should work:

<img width="647" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/17d5fbc3-af52-4b23-a0d1-98e44971f56d">

Fences does have other compatibility issues with Lively though.
