### ISSUE TITLE
It can be handle keyboard event?

### ISSUE THREAD

**Issue by wangxiaoyan369** [rocksdanister/lively#1903]
When I set a web url wallpaper, the mouse click work, but keydown not response

**Comment by rocksdanister** [comment]
English will work once enabled in settings:
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#mouse--keyboard

**Comment by wangxiaoyan369** [comment]
> English will work once enabled in settings: https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#mouse--keyboard

working
