### ISSUE TITLE
Wallpaper Cycling 

### ISSUE THREAD

**Issue by Cahoolio** [rocksdanister/lively#1905]
You need to add a feature that allows your wallpapers to cycle at a rate selected by the user. The Nvidia wallpaper service has this feature, but I find it annoying on there because you have to cycle their wallpapers. If you had this feature on Lively it would be awesome!!! Let me know what you think.

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/137
