### ISSUE TITLE
Reddesign Website

### ISSUE THREAD

**Issue by Ericdom** [rocksdanister/lively#1909]
I have redesigned the Website.
 Check the whole case study here - 

https://www.behance.net/gallery/180448601/Lively-Wallpaper-Site-Redesign

In the same case study, you can find the Live Prototype, 
you can experience the prototype and also watch the site in action in video.

**Comment by rocksdanister** [comment]
@dabjulmaros have a look.

**Comment by dabjulmaros** [comment]
The site is your design, why do i need to look at it?

**Comment by rocksdanister** [comment]
Thanks for the feedback but the style doesn't match my vision for lively, and at the moment I have no plans for a site refresh.
