### ISSUE TITLE
add option to adjust Brightness for video wallpaper

### ISSUE THREAD

**Issue by anwar-alsilwy** [rocksdanister/lively#191]
Could you please add option to adjust Brightness for video wallpaper.
Because sometimes desktop icons not appear clearly while playing video wallpaper

**Comment by rocksdanister** [comment]
You can make a custom mpv player config file:

https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by anwar-alsilwy** [comment]
Is it possible to make this option in settings ( User friendly),
If not, could you please write an example lines how to increase/decrease brightness,
I will add it to config file:
C:\Users\<UserName>\AppData\Local\Lively Wallpaper\mpv\mpv.conf

Cheers.

**Comment by rocksdanister** [comment]
>Is it possible to make this option in settings ( User friendly),

I thought about it, I don't think there is much demand for this feature and its not worth the effort to implement.
Figuring out how to do this in all 3 of the videoplayers, adding the new language strings for the UI and translating them, adding the arguments to pass to the external videoplayer program, testing and maintaining this feature in future releases of Lively etc.. its a bit of work and I also feel it will clutter the UI with too many options.

>If not, could you please write an example lines how to increase/decrease brightness,

Looking at the mpv player documentation: https://mpv.io/manual/stable/
`--brightness=<-100-100>` worked on my system.

Here are the configuration Lively uses for references:
https://github.com/rocksdanister/lively/blob/8daac6780fb789808be1a3deec0838a0a86645ef/src/livelywpf/libMPVPlayer/MainWindow.xaml.cs#L74-L108

Example mpv.conf:
```
# gpu acceleration.
hwdec = auto

# allow Windows screensaver/display sleep.
stop-screensaver = no

# scaler
keepaspect = no

# brightness: -100 - 100
brightness= -5
```
If you use yt-dl then you are going to have to do that also.

**Comment by rocksdanister** [comment]
Related: https://github.com/rocksdanister/lively/issues/195
