### ISSUE TITLE
ADD WALLPAPER YOUTUBE URL

### ISSUE THREAD

**Issue by a11mark** [rocksdanister/lively#1912]
**Describe the bug**
When I enter the youtube link and press the arrow button. it starts to process but then I get a Pop up with

"Oops...Looks like something went wrong :(

**To Reproduce**
1. Go to 'add wallpaper, enter https://www.youtube.com/watch?v=fgt9NfZnfjs into the URL field'
2. Click on 'the arrow button next to the URL field'
3. See "Oops...Looks like something went wrong :( error

**Expected behavior**
Youtube video should show and appear

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro ver 22H2]
- Which wallpaper was running at the time if any? Always in My soul.

**Log file (Important)**
[lively_log_20230928_085838.zip](https://github.com/rocksdanister/lively/files/12747154/lively_log_20230928_085838.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper
