### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by thp1923** [rocksdanister/lively#1913]
[lively_log_20230928_175102.zip](https://github.com/rocksdanister/lively/files/12748608/lively_log_20230928_175102.zip)
When I opened Microsoft Copilot, it got bugged.

**Comment by gmknowles** [comment]
same here and when I reboot also.  App stops responding and need to close and reopen to work.
[lively_log_20230928_171809.zip](https://github.com/rocksdanister/lively/files/12754326/lively_log_20230928_171809.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1915
