### ISSUE TITLE
Bug: Windows 11 Copilot Widget Deactivates Wallpaper Service 

### ISSUE THREAD

**Issue by SyCoREAPER** [rocksdanister/lively#1916]
First, thank you for the incredible app and great work.

**To Reproduce**
Current Windows 11 Stable Build, if you click on the Copilot Preview Button, Copilot opens and the video wallpaper immediately stops. The Only way to get it back is close all Lively related tasks and reopen and reapply. 

**Expected behavior**
When configured to always be running, Windows Widget should not be able to deactivate it.  

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 (22621.2361)
- Which wallpaper was running at the time if any: Locally saved *.webm video

**Additional context**
Above covers it, single use case that terminated the Wallpaper.

**Log file (Important)**
Share the diagnostic files by:

[lively_log_20230930_015221.zip](https://github.com/rocksdanister/lively/files/12774085/lively_log_20230930_015221.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1915
