### ISSUE TITLE
YT wallpapers have the YouTube bar across

### ISSUE THREAD

**Issue by OofMon** [rocksdanister/lively#192]
They have this bar across the top of the screen, and it can go out of quality, 144p or something like that.
![Capture](https://user-images.githubusercontent.com/74296140/98796581-46972f80-2457-11eb-9d1b-819924cb1388.PNG)

**Comment by OofMon** [comment]
This only happened after an update a day or two ago.

**Comment by rocksdanister** [comment]
Follow the mpv player setup instructions:
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper

**Comment by OofMon** [comment]
Where do you find (plugins/libMPVPlayer/lib)? I can't seem to find it.
