### ISSUE TITLE
Lively crashes when a volume is mounted with rclone; Windows 11; ERROR|Cannot access a disposed object

### ISSUE THREAD

**Issue by jeffrey-lebowski** [rocksdanister/lively#1920]
**Describe the bug**

Lively crashes for me consistently whenever I mount a volume with rclone. It might crash under other circumstances as well, but this is one scenario that I was able to consistently replicate so far.

This issue might be related to #1846, considering that it's the same error (`ERROR|Lively.Core.Wallpapers.WebCefSharpProcess|Stdin write fail: Cannot access a disposed object.`), same OS (Windows 11) and a recent report.
 
**To Reproduce**
1. Start Lively, load Matrix wallpaper;
2. Mount a volume with rclone; e.g. `rclone mount remote: y:`;
3. Despair; the wallpaper animation stops working; static wallpaper is loaded instead; the only fix is to restart Lively;

**Expected behavior**

I expected to have a nice animated wallpaper that doesn't crash all the time.

**Desktop (please complete the following information):**
- OS: Windows 11 22H2
- Matrix wallpaper
- I installed Lively from the MS Store

**Log file (Important)**
[lively_log_20231003_120952.zip](https://github.com/rocksdanister/lively/files/12794135/lively_log_20231003_120952.zip)

**Comment by rocksdanister** [comment]
Not sure what change rclone is doing, is it modifying the hardware (is new hardware appearing on device manager?)

**Comment by jeffrey-lebowski** [comment]
> Not sure what change rclone is doing, is it modifying the hardware (is new hardware appearing on device manager?)

As far as I can see, volumes mounted with rclone don't appear in Device Manager; instead, they appear under "devices and drives" in "This PC"/"My Computer". I'm mounting (google) workspace cloud storage as a virtual drive here.

This might not be something specific to rclone; it might've become an issue after an Nvidia or Windows update; I only mentioned rclone, because I can consistently replicate the issue when I mount drives with it;

EDIT: I read through the recent issues and it possible that this is also related to the recent Windows update; I do have the preview version installed;
