### ISSUE TITLE
Report for Lively Wallpaper crashed after connected to external hard disk

### ISSUE THREAD

**Issue by NikEz-03** [rocksdanister/lively#1922]
**Describe the bug**
Crash or force exit

**To Reproduce**
1. Connect with external hard disk
2. Live wallpaper on desktop just crash 
3. Disconnected with external hard disk but it still happened until restart

**Expected behavior**
Software

**Screenshots/Video**
![Screenshot 2023-10-05 120505](https://github.com/rocksdanister/lively/assets/147019887/3a5a25d0-daf7-46fd-949a-86d312eb668d)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
- Just windows 11 background only

**Additional context**
Nothing just when connected to external hard disk it crashed.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
[lively_log_20231005_115114.zip](https://github.com/rocksdanister/lively/files/12812136/lively_log_20231005_115114.zip)

Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by pcorbit** [comment]
I have the exact same problem!

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/1926

**Comment by userdata60** [comment]
me too i have the problem
