### ISSUE TITLE
wallpaper not applying 

### ISSUE THREAD

**Issue by JASWINCKS** [rocksdanister/lively#1923]
As the lively application was working correctly before a week , and now it just not working on applying the wallpaper at all ..
it just give the prompt that the application is not working 

[lively_log_20231005_203025.zip](https://github.com/rocksdanister/lively/files/12820021/lively_log_20231005_203025.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1911
