### ISSUE TITLE
Changing any display settings (resolution, refresh rate, HDR) causes to Lively stop working (blank screen)

### ISSUE THREAD

**Issue by TuncTaylan** [rocksdanister/lively#1925]
**Describe the bug**
After a recent Windows Update, Lively Wallpaper stops working, after activating or deactivating HDR or changing resolution or refresh rate. Reactivating the wallpaper doesn't work, only way is to kill all Lively processes and restart Lively again.
Deactivating GPU Decoder doesn't have any effect.
Attached are the logs before and after activating HDR.

Windows Edition is Windows 11 Pro
Version 22H2 (22621.2361)
Nvidia Driver 537.42 (tried one older driver as well)

**To Reproduce**
1. Activate a wallpaper (rain in my case)
2. Change the resolution in settings or change the refresh rate in settings or activate (or deactivate) HDR in settings
3. See error (blank screen)

**Expected behavior**
As before the latest windows update, the expected behaviour is, that the Lively wallpaper is continouing working.

**Screenshots/Video**
If this help, I can try to capture this.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 (22621.2361)
- Rain was running

**Log file (Important)**
Logs of before activating HDR - [lively_log_20231006_190704.zip](https://github.com/rocksdanister/lively/files/12833718/lively_log_20231006_190704.zip)
Logs of after activating HDR - [lively_log_20231006_190717.zip](https://github.com/rocksdanister/lively/files/12833730/lively_log_20231006_190717.zip)

Edit: Just wanted to mention, I reinstalled Windows and still have the issue.

**Comment by TuncTaylan** [comment]
![Debugger](https://github.com/rocksdanister/lively/assets/1934825/ce26f157-cc94-4548-adcf-3adb636f331e)
At log ID 13 I activated HDR and the Lively has gone blank and at log ID 30 I deactivated the HDR.

**Comment by diyorjonswitch** [comment]
![Screenshot 2023-10-08 000905](https://github.com/rocksdanister/lively/assets/118802469/c655764b-52f7-4c70-979c-7c10820b56d5)

**Comment by TuncTaylan** [comment]
I can confirm, that Lively starts up again, after changing any display settings.

Thank you!
