### ISSUE TITLE
Windows 11 22H2 Update Problems

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#1926]
Newest Windows update changed some things and having incompatibility with Lively.

Tracking all the problems with Lively after Windows 11 22H2 Build 22621.2361 update:

- Opening Copilot crashes wallpaper
https://github.com/rocksdanister/lively/issues/1911
- Connecting external hard disk/USB device crashes wallpaper
https://github.com/rocksdanister/lively/issues/1922
https://github.com/rocksdanister/lively/issues/1920
- https://github.com/rocksdanister/lively/issues/1925
- Fullscreen games crashing wallpaper
https://github.com/rocksdanister/lively/issues/1911#issuecomment-1741273929
- When toggling Windows Automatically Hide taskbar setting wallpaper disappear.
- https://github.com/rocksdanister/lively/issues/1947

If I missed any problem let me know.

I am working on a fix which will basically restart the wallpaper when it happens, need some time to test the fix.

Early beta release can be downloaded from here:
https://github.com/rocksdanister/lively-beta/releases

**Comment by TuncTaylan** [comment]
Thanks for working on a fix. About the issue #1925, previous behaviour was, that Lively has continued to work when changing display settings.

**Comment by Styphoryte** [comment]
I am testing how long Lively will work after disabling Copilot through ViVeTool. More info here: [https://pureinfotech.com/disable-copilot-windows-11/](https://pureinfotech.com/disable-copilot-windows-11/) I've tried disabling it through gpedit.msc (group policy editor) method as well as through the Registry but nothing worked until I remember about the Vivetool method... See what happens I guess. 🥱

**Comment by rocksdanister** [comment]
This is how the patch will behave:

https://github.com/rocksdanister/lively/assets/17554161/7815b38c-659f-4086-8ecc-91549fb9bc9d

Desktop is changing everytime Copilot is opened, I have to relaunch the wallpaper unfortuantely.

**Comment by jeffrey-lebowski** [comment]
BTW mounting volumes with VeraCrypt also crashes Lively. Same error as in #1920.

**Comment by TuncTaylan** [comment]
> This is how the patch will behave:
> copilot.mp4
> 
> Desktop is changing everytime Copilot is opened, I have to relaunch the wallpaper unfortuantely.

Do you need testers? When will you release it?

**Comment by rocksdanister** [comment]
Yes I will need help testing, will post update here when beta is released.

**Comment by Styphoryte** [comment]
What's interesting is on the newest stable version after disabling copilot through Vivetool I relaunched Lively in Admin mode and reapplied my live wallpaper and left it over night and it's still going to my surprise! I think something will crash it tho, since I did that it has crashed once but I couldn't pin point when or what caused it to crash yet. Maybe somehow copilot is still interfering with it / another MS service?

**Comment by rocksdanister** [comment]
[More Copilot changes](https://www.windowslatest.com/2023/10/09/windows-copilot-on-windows-11-is-getting-an-improved-modular-interface/) 🤔

**Comment by EnergyKrolik** [comment]
UPD:
Wallpaper stops when use some full windowed apps AND connect or disconnect USB devices (in my case USB flash connecting or disabling cause stop)

UPD UPD: changing screen mode also stop work

**Comment by Panikk11503** [comment]
Not sure if this is helpful but I used the vivetool to remove copilot and at first my lively wasn't working (it wouldn't start back up properly after exiting a game).  I was able to solve this by reinstalling lively and then checking Run As Administrator on Lively.exe for All Users.

**Comment by Styphoryte** [comment]
It will crash eventually... I did the same thing you mentioned along with
running as admin but it still does. Takes a lot longer though.

**Comment by TuncTaylan** [comment]
@rocksdanister Any updates?

**Comment by rocksdanister** [comment]
First **beta installer v2.0.7.2** is out:
https://github.com/rocksdanister/lively-beta/releases

I recommend running fullscreen games Windowed for the time which avoids the issue.

**Comment by Styphoryte** [comment]
In the stable version I just disabled GPU encode in settings under wallpaper I believe it was. Once I did that I think I restarted Lively for some reason made sure it starts up with windows as admin too. It's been a day and a half so fingers crossed it doesn't crash / stop. I think it was a full screen program or something that was crashing it but I'm uncertain couldn't pinpoint exactly when it would crash. 

Edit: Gave up on this, it eventually crashed. The new update seems to be working for me so far!! Thanks so much, we all appreciate your work. 💯

**Comment by TuncTaylan** [comment]
> First **beta installer v2.0.7.2** is out: https://github.com/rocksdanister/lively-beta/releases

I'm sorry, but the binary gives a virus warning (probably false positive), but the source code is just readme file.
Can you provide the source or tell us in which branch is the new code?

**Comment by rocksdanister** [comment]
>I'm sorry, but the binary gives a virus warning (probably false positive), but the source code is just readme file.

https://www.virustotal.com/gui/file/40491ac7c609247d661969c209e48c6b00bdd6c18c5624b22c09c54b9ffa5f03

I don't see any virus warning? Trapmine one is false positive and my attempts at contacting them failed (they don't answer email nor do they have a file submit website.)
Unless you are talking about Windows SmartScreen warning which is not a virus detection and it is due to low download count.

>Can you provide the source or tell us in which branch is the new code?

You are commenting on the repo.

**Comment by TuncTaylan** [comment]
> > I'm sorry, but the binary gives a virus warning (probably false positive), but the source code is just readme file.
> 
> https://www.virustotal.com/gui/file/40491ac7c609247d661969c209e48c6b00bdd6c18c5624b22c09c54b9ffa5f03
> 
> I don't see any virus warning? Trapmine one is false positive and my attempts at contacting them failed (they don't answer email nor do they have a file submit website.) Unless you are talking about Windows SmartScreen warning which is not a virus detection and it is due to low download count.
> 
> > Can you provide the source or tell us in which branch is the new code?
> 
> You are commenting on the repo.

When will you release the store version?

**Comment by rocksdanister** [comment]
Have anyone tried beta with 23H2?

**Comment by TuncTaylan** [comment]
> Have anyone tried beta with 23H2?

23H2 is not released to everyone. Can you release it for the 22H2?

**Comment by rocksdanister** [comment]
Fixes are not complete and it will released on stable when ready, this thread is for keeping track of the issues and testing beta.

I suggest subscribing to github release notification instead.

**Comment by yofukashino** [comment]
I tried installing latest beta on windows os build 22621.2428 but even that doesn't work for me

**Comment by rocksdanister** [comment]
> I tried installing latest beta on windows os build 22621.2428 but even that doesn't work for me

Isn't your original issue UI not opening and not about the wallpaper? It's unrelated to 22H2.

**Comment by yofukashino** [comment]
> > I tried installing latest beta on windows os build 22621.2428 but even that doesn't work for me
> 
> Isn't your original issue UI not opening and not about the wallpaper? It's unrelated to 22H2.

I think it's related because since I updated my windows, lively doesn't even show up in the tray. it crashes but I will trust the dev's word for this

**Comment by djdoolky76** [comment]
Windows pushed a new update recently that fixed major bugs that occur in lively wallpaper in the past few days

**Comment by rocksdanister** [comment]
Is it build 22621.2506? some of the issues are fixed but some like entering fullscreen mode still exists.

The patches I made are not specific to any Windows build but instead made the wallpaper more resilient to crashes and recover when crashed, this should make it better for future versions of Windows.
