### ISSUE TITLE
wallpaper keeps crashing, the lively app stays open but the wallpaper doesnt run, or shows a white background. I have tried switching plugins but it still doesnt work.

### ISSUE THREAD

**Issue by BiggieNuggz** [rocksdanister/lively#1928]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by BiggieNuggz** [comment]
[lively_log_20231007_190910.zip](https://github.com/rocksdanister/lively/files/12839480/lively_log_20231007_190910.zip)
[lively_log_20231007_190940.zip](https://github.com/rocksdanister/lively/files/12839481/lively_log_20231007_190940.zip)

**Comment by sitenzo** [comment]
@BiggieNuggz Can you please update your issue.

Short clear title
Description with all the information that you have, like what windows version, which wallpaper. how to reproduce the error.

Thanks for your helpt!

**Comment by Code-prodigal** [comment]
![image](https://github.com/rocksdanister/lively/assets/32701259/08dae689-cc63-40b9-8b0c-e5d774e7b94b)
I am also unable to open the software lively

版本	Windows 10 专业版
版本号	22H2
操作系统内部版本	19045.2965
