### ISSUE TITLE
The background doesn't show but the app still works.

### ISSUE THREAD

**Issue by llingy** [rocksdanister/lively#1929]
**Describe the bug**
The background doesn't show but the app still works.

**To Reproduce**
1.Open the app.
2.Stay for a while.
3.See the error

**Expected behavior**
The background continues to show.

**Desktop (please complete the following information):**
Windows 11 22H2 22621.2361

**Log file (Important)**
[lively_log_20231008_154905.zip](https://github.com/rocksdanister/lively/files/12840085/lively_log_20231008_154905.zip)

**Comment by llingy** [comment]
I find that connecting to USB devices may cause that.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1926 https://github.com/rocksdanister/lively/issues/1922
