### ISSUE TITLE
Windows 8.1 : This app can't run on your pc.

### ISSUE THREAD

**Issue by EngrishGuysTaig** [rocksdanister/lively#193]
I have (In 2020) a 32-bits copy of windows 8.1 and i do want Lively Wallpaper in my laptop but cause of 32-bits windows, This appers   
![K](https://user-images.githubusercontent.com/73356571/98802278-5ee55b00-2413-11eb-875d-b698328686a5.png)
So it will be AWESOME to make a 32-Bits version 
Bye

**Comment by rocksdanister** [comment]
Lively require Windows 10 versions 1903 (32 or 64bit) or above.
