### ISSUE TITLE
NO Lively after wake from sleep.

### ISSUE THREAD

**Issue by keshka** [rocksdanister/lively#1930]
[lively_log_20231009_072929.zip](https://github.com/rocksdanister/lively/files/12847391/lively_log_20231009_072929.zip)

Runing windows 11 Pro prerelease.230923-1633 and have the background set to "slide show". On starting Lively, all works well and is quite fun. Putting the computer to sleep and then on wake it's back to the slide show. Lively is still running as shown bottom right, hidden Icons. Clicking on the Lively icon allows me to open Lively and all appears fine, I can set any of the stock lively wallpapers but they do not display. Exit, restart Lively and selecting a lively wallpaper then works as expected....until wake from sleep breaks it again.

**Comment by keshka** [comment]
Update, after looking at the log file several errors about "Stdin write fail: Cannot access a disposed object." 
I restarted Lively as administrator and it appears to have resolved the issue. I put the pc to sleep and upon wake, Lively was still working fine. Yay!

**Comment by rocksdanister** [comment]
Pre release has too many frequent changes, so won't be supported.

Right now I am working on adding support for 22H2.
