### ISSUE TITLE
Wallpapers stops after some time and app cant change on another one 

### ISSUE THREAD

**Issue by EnergyKrolik** [rocksdanister/lively#1934]
Describe the bug
Animation stops suddenly and nothing works until restart the app. I thought that problem was in full-screen apps wchich broke app (TF2 on Source engine), made it in borderless window, and it stopped crashing. But when i surfed internet i`ve noticed that app stopped anyway. Tried to switch all settings, hothing helped. How i understood, problem consist of new windows updates, right?
What can i do to prevent this bug?

Screenshots/Video
No sense, cause appear black or static background.
 - OS: Win 11 22h2 22621.2361
- Any wallpaper

[lively_log_20231012_161356.zip](https://github.com/rocksdanister/lively/files/12882780/lively_log_20231012_161356.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/1926

**Comment by EnergyKrolik** [comment]
> dup: #1926

didnt see, sorry. so does this mean that not my fault that app works badly with new updates?

**Comment by rocksdanister** [comment]
yes, need to update it on my side.
