### ISSUE TITLE
Lively not showing the wallpaper after a while...

### ISSUE THREAD

**Issue by pickonedev** [rocksdanister/lively#1935]
**Describe the bug**
Sometimes the lively wallpaper does not show the wallpaper, instead I only see the background wallpaper of windows.
I need to close the app completely and open it again.

**To Reproduce**
1. Working on the computer and waiting
2. Sometimes the background set by Lively dissapear
3. After the app reopen, it will work for a while

**Expected behavior**
...

**Screenshots/Video**
Now the Lively Wallpaper it is not showing
![image](https://github.com/rocksdanister/lively/assets/34201387/258bf77c-fd38-4fcb-adbf-3e9e62164e21)
After app restart, it is ok
![image](https://github.com/rocksdanister/lively/assets/34201387/286b7ee9-f880-4bdb-bb67-1975c33723a9)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 - 22621.2428
- I am always using the website type of wallpaper. Wallpaper with Home Assistant dashboard display

**Additional context**
The only workaround is to restart the app. Even if I just change the wallpaper type, it won't help.

**Log file (Important)**
[lively_log_20231012_232207.zip](https://github.com/rocksdanister/lively/files/12886820/lively_log_20231012_232207.zip)
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/1926
