### ISSUE TITLE
Cannot add Fluid v2 as a wallpaper

### ISSUE THREAD

**Issue by s33k3r-virus** [rocksdanister/lively#194]
When i try to add Fluids v2 as a wallpaper it loads and after a while pops up with an error message:

Oops... Looks like something went wrong :(
In order to better understand this error and fix the issue, share the log file with the developer.
Instructions for sharing log file:
https://github.com/rocksdanister/lively/wiki

[20201111_220552.txt](https://github.com/rocksdanister/lively/files/5526590/20201111_220552.txt)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/153

or

Install the non audio version Fluid
https://github.com/rocksdanister/WebGL-Fluid-Simulation/releases
