### ISSUE TITLE
Turning On/Off Bluetooth

### ISSUE THREAD

**Issue by LAWPEET** [rocksdanister/lively#1947]
Turning On/Off Bluetooth always results in removing the selected MPV file/s and will not show until the app restart

Please see the attached link:
https://www.loom.com/share/2cacfafbeee1445196e6ddde3821f87e

Lively v2.0.7.0 x64 desktop-bridge en-US
OS: Microsoft Windows 11 Enterprise 10.0.22621
CPU: AMD Ryzen 7 5700G with Radeon Graphics
GPU: AMD Radeon RX 6600 XT

/[Turning On Bluetooth Issue.zip](https://github.com/rocksdanister/lively/files/13057263/Turning.On.Bluetooth.Issue.zip)
<!--

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/1926
