### ISSUE TITLE
Lively unresponsive and black wallpaper

### ISSUE THREAD

**Issue by Salehin18** [rocksdanister/lively#1948]
**Describe the bug**
When ever i open valorant or any game sometimes any software the wallpaper goes black even though lively is still running.
Changing the wallpaper or pause and unpause the wallpaper does not help. Manually reselecting the wallpaper doesn't help either
To get lively working again you need to quit it from taskbar or icon tray and open it again
another way is a system restart for lively to properly function again

**To Reproduce**
1. Open valorant sometimes any software and the wallpaper will go black

**Desktop (please complete the following information):**
 - OS: Windows 11 pro
- Rain effect and a custom wallpaper
- tried using the other wallpapers available on lively but got the same bug

**Log file **
[lively_log_20231021_000138.zip](https://github.com/rocksdanister/lively/files/13057713/lively_log_20231021_000138.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1926
