### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by h-y-p-e** [rocksdanister/lively#1952]
**Describe the bug**
Every time I connect a device it crashes.

**To Reproduce**
1. Go to 'Library.'
2. Click on 'any wallpaper.'
3. Scroll down to 'run a wallpaper.'
4. It crashes and only works until I terminate the application

**Expected behavior**
crashes every time I connect a device.
**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home Single Language 22621.2428
- 

>  #Fluids
[lively_log_20231022_114506.zip](https://github.com/rocksdanister/lively/files/13062897/lively_log_20231022_114506.zip)
.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1926
