### ISSUE TITLE
Lively stops working when PC is charging

### ISSUE THREAD

**Issue by ImDxni** [rocksdanister/lively#1954]
**Describe the bug**
As described in the title, when i charge my pc, the wallpaper broke and it freezes

**To Reproduce**
I just set a wallpaper and then put the pc in charge;

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/39953274/8c726ad3-e7aa-4388-b7bc-cec86738a0c4)

**Desktop (please complete the following information):**
 - OS: Windows 11
- it happens with all wallpapers

**Log file (Important)**
[lively_log_20231022_172031.zip](https://github.com/rocksdanister/lively/files/13063774/lively_log_20231022_172031.zip)

**Comment by Jxacx** [comment]
It is also happening to me, every time I charge my laptop or stop charging it my wallpapers pause. To fix this I have to close Lively Wallpaper and then re-open it so as to get the animations back.

**Comment by rocksdanister** [comment]
Can you check if wallpaper is restored in beta version: https://github.com/rocksdanister/lively/issues/1926
