### ISSUE TITLE
the application opens 2 blank windows of it self upon startup 

### ISSUE THREAD

**Issue by Stroov** [rocksdanister/lively#1955]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by: 
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
[lively_log_20231024_135941.zip](https://github.com/rocksdanister/lively/files/13112396/lively_log_20231024_135941.zip)

Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

windows starts your aplication starts it loads the wallpaper but also loads 2 small windows of your aplication which are blank 
![Screenshot (259)](https://github.com/rocksdanister/lively/assets/108878153/b4df7be5-aab7-43c8-b61e-48f711bf8baa)
screenshot and log file attached please see

**Comment by rocksdanister** [comment]
These window are used for receiving Windows messages, its set to open outside monitor region.. usually this happen when some software is trying to inject into window or change program launch behavior. I noticed you have fences, maybe its some Stardock utility?

**Comment by Stroov** [comment]
yes i use fences tago fences for the desktop mgmt
