### ISSUE TITLE
Haven't been able to get Lively to start up with Windows in the past few versions

### ISSUE THREAD

**Issue by Panikk11503** [rocksdanister/lively#1956]
Windows 11 22H2 Build 22621.2428
Lively v2073 beta (happened on last 2 versions as well)

I checked the Startup Apps to ensure Lively was not being blocked there.  I've blown away all Lively folders inside Appdata subfolders and the Program Files dir and reinstalled each version per attempt to get it working.  My workaround has been to use Task Scheduler to start the program after login (either with reattempts or with a 30 second delay on the task).  When updating from the previous version to this 2073 version from within Lively, it began having errors upon startup of Lively and I applied the suggested solution (said in Lively) via SystemPropertiesPerformance.exe but that did not make the error go away.  As described previously, I then uninstalled and deleted every trace of Lively I could find and reinstalled 2073.  Lively works now without an error being displayed in the UI, but it still doesn't start with Windows as it should.  I am using the Parralax wallpaper on my main monitor and the Matrix Rain on my second monitor.  No issues once Lively is actually running, but it's just an issue of getting it to actually start when I start my computer that is the problem.

[20231024_082332.txt](https://github.com/rocksdanister/lively/files/13114569/20231024_082332.txt)

**Comment by Panikk11503** [comment]
I just realized that log wasn't the latest one.  This is my latest log 
[20231024_083053.txt](https://github.com/rocksdanister/lively/files/13114605/20231024_083053.txt)

**Comment by rocksdanister** [comment]
Is your Windows HDR enabled? looks like Lively is failing to initialize for some reason 🤔

Why is your Lively running elevated by the way?

**Comment by Panikk11503** [comment]
It has administrative privilege on Lively.exe for all users and I am not running any HDR display.  I am running a CRT display as my second monitor but that has never caused issue before. 

EDIT: Oh, "why" does it have admin privilege? When I installed for All Users, that's how Lively.exe was set by the installer.

**Comment by rocksdanister** [comment]
Running elevated is not the same as All Users install which simply installs in Program files folder instead of AppData.

You have UAC driver disabled (which makes all apps run elevated.) or made some system modification (maybe tweaking utility?)

**Comment by Panikk11503** [comment]
I don't have the UAC warning when starting up applications but having that disabled does not run every application as administrator.  There are many applications I have that require me to right click them and then Run as Administrator for certain aspects to work correctly.  As for system tweaks I am running Rectify11 and StartAllBack but I have been running them since May of this year on Win 11 and have not had these issues until the recent month (roughly).

**Comment by rocksdanister** [comment]
I was referring to Local security policy method https://github.com/rocksdanister/lively/issues/1060#issuecomment-1044970174

This may not be the cause of the issue directly but having Lively detect elevation is weird and could be related.

Share the complete logfile.zip: traymenu ->Report bug -> Create log report file.

**Comment by Panikk11503** [comment]
I did a full reinstall in the way I had described earlier and had deleted the task that was my workaround.  Lively failed to automatically start upon reboot still and here are my two logs. I do not believe I did any sort of weird tweak to the way UAC works in the way that your link had described.  I'm not sure how that would have benefitted me so I don't think I ever did anything like that to my system.
[20231025_125638.txt](https://github.com/rocksdanister/lively/files/13168703/20231025_125638.txt)
[20231025_125430.txt](https://github.com/rocksdanister/lively/files/13168704/20231025_125430.txt)

**Comment by Panikk11503** [comment]
Oh I'm sorry, here is the full .zip you requested 
[lively_log_20231025_130103.zip](https://github.com/rocksdanister/lively/files/13168720/lively_log_20231025_130103.zip)

**Comment by Panikk11503** [comment]
so after installing update KB5031455 i restarted to see if anything changed and if lively would start.  nothing changed so i uninstalled lively and then reinstalled as "just for me" (not All Users like i had been).  once installation had finished i
had it open lively after the installer was closing and lively had an error trying to launch.  it read Unable to execute file:
PATHTOLIVELY.EXE
CreateProcess failed; code 740.
The requested operation requires elevation. 
![error](https://github.com/rocksdanister/lively/assets/22116474/01d5eb5a-8305-4cf2-8c2c-f8cdc789e01a)
after closing that attempt and just double clicking the new shortcut on the desktop to lively, the program launched without issue.  here are a couple logs from a couple restarts after reinstalling latest lively beta (still not launching on its own after a reboot)

[lively_log_20231029_023231.zip](https://github.com/rocksdanister/lively/files/13197352/lively_log_20231029_023231.zip)
[lively_log_20231029_023046.zip](https://github.com/rocksdanister/lively/files/13197353/lively_log_20231029_023046.zip)

**Comment by rocksdanister** [comment]
Lively does not request elevation to run, the installation mode just changes the install location.

Something in your system is forcing Lively (and possibly other apps) to run elevated, this is a security risk and I recommend you find out the cause.

Searching online seems to suggest ownership issue, corrupted system registry.. :
https://www.reddit.com/r/apexlegends/comments/cztkly/pc_need_help_launch_issue_required_operation/

I am closing this for now because this appears to be unrelated to Lively code, if more number of users report this issue then will look into it but so far this is the first time I am getting this report.
