### ISSUE TITLE
60fps youtube vids not displaying ?

### ISSUE THREAD

**Issue by aquuamon** [rocksdanister/lively#1957]
I get an issue creating a new wallpaper using embed method for a youtube video (https://www.youtube.com/watch?v=RIynivZldrc), it ends up as "video unavailable" by lively. If I try with a lower framerate (https://www.youtube.com/watch?v=JJV_mLcwknQ) it works as it should.

I'm using v.2.0.7.0 on Win10 and tried with both CefSharp and WebView2.

**Comment by rocksdanister** [comment]
Its because the uploader or youtube disabled embedding for that video.

Best to just download the video using third party tools and set the downloaded video file as wallpaper.

**Comment by aquuamon** [comment]
Hi, thanks for the update! I did some more testing, it appears to be youtube who limits embeds containing copyrighted music in this case (I'm the uploader + embed was on) and 60fps was just a coincidence.
