### ISSUE TITLE
The Lively wallpaper stop when usb is plug in/out

### ISSUE THREAD

**Issue by Xuehua-Meaw** [rocksdanister/lively#1960]
**Describe the bug**
When Any usb device plug in / out. The lively wallpaper stops.

**To Reproduce**
1. Plug in / out a usb device

**Expected behavior**
The lively wallpaper should not stops when usb plug in / out.

**Screenshots/Video**
Plug in usb
![image](https://github.com/rocksdanister/lively/assets/58870474/da8ab410-83bc-4be5-b34a-2af59280deee)
![image](https://github.com/rocksdanister/lively/assets/58870474/3e4204a4-6321-492b-b49b-6832166ff2c1)

Restart lively wallpaper
![image](https://github.com/rocksdanister/lively/assets/58870474/065d4740-5baf-4954-98ae-4e977a498929)

Remove usb
![image](https://github.com/rocksdanister/lively/assets/58870474/0e407803-3d89-4601-be95-d592529c220c)
![image](https://github.com/rocksdanister/lively/assets/58870474/f4764a13-d016-42bd-9278-a5dd89dc7a58)

**Desktop (please complete the following information):**
 - OS: Window 11 22H2
- Which wallpaper was running at the time if any.
- Summer Nights

**Log file (Important)**
[lively_log_20231026_002605.zip](https://github.com/rocksdanister/lively/files/13168539/lively_log_20231026_002605.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1926

Beta has the fix, stable release coming soon.
