### ISSUE TITLE
Portable version of Lively Wallpaper

### ISSUE THREAD

**Issue by Bunnnyface** [rocksdanister/lively#1965]
**Describe the solution you'd like**
► A portable version of Lively Wallpaper would be an awesome versatile option.

**Describe alternatives you've considered**
► Portable version like Keepass, OBS Studio, ScreenToGif or Rainmeter.
Apps that don't need an installation and can be runned on a USB stick.

**Comment by rocksdanister** [comment]
There is no plan for portable version at the moment.

Lively already has installer and msix setup, adding a new portable system ontop will increase the workload in maintaining the project.
