### ISSUE TITLE
A fix for lively crashing when power is plugged in:

### ISSUE THREAD

**Issue by suy0x1** [rocksdanister/lively#1967]
### For me it ended up with an easy fix that's as follows:

Step 1: Open Control panel

Step 2: go to system and security

Step 3: go to power options

Step 4: in selected plans click on "change plan settings"
![Screenshot 2023-10-27 155115](https://github.com/rocksdanister/lively/assets/73711602/4bfe5eeb-367c-4655-9493-2061998b2c68)

Step 5: now, click on "change advance power settings"
![Screenshot 2023-10-27 155332](https://github.com/rocksdanister/lively/assets/73711602/f3f22c64-af8f-48a5-833b-6c4fac7685c0)

Step 6: In the new pop-up click on "desktop background management"
![Screenshot 2023-10-27 155508](https://github.com/rocksdanister/lively/assets/73711602/1d916729-01be-45be-a2e8-d68e2db02e21)

Step 7: click on "slide show"
![Screenshot 2023-10-27 155638](https://github.com/rocksdanister/lively/assets/73711602/51b5cd41-2087-42b1-a04f-5e22c0659727)

Step 8: click on "paused" and change it to "available"
![Screenshot 2023-10-27 155745](https://github.com/rocksdanister/lively/assets/73711602/62c0ac0d-7943-4327-b14d-efa68c5c5855)

And that's pretty much it, in my case that ended up solving my problem i tested it by plugging in and removing the charger and although first it seemed it crashed but then it loaded right after that

## System information
Using windows 11 as an OS 
and lively 1.0.137.0 (as shown on microsoft store)

**Comment by rocksdanister** [comment]
I don't have a laptop to test.

Can others verify this step is required? I was under the impression the latest **Lively v7.0.4.0 update** fixed this already.

**Comment by suy0x1** [comment]
i've not updated the app since a long time so it was still there for me

**Comment by rocksdanister** [comment]
> i tested it by plugging in and removing the charger and although first it seemed it crashed but then it loaded right after that

It actually did crash but with the latest update v7.0.4.0 wallpaper is reloaded automatically https://github.com/rocksdanister/lively/issues/1926

**Comment by suy0x1** [comment]
since the new version is already out there i don't think so this issue will reproduce for other people
