### ISSUE TITLE
Wallpaper stopped accidentally

### ISSUE THREAD

**Issue by prounlocks** [rocksdanister/lively#1968]
Wallpaper suddenly stopped and returned to default windows wallpaper.
Any switching to another theme - not working.\

Only restart app fix the problem.

debug screen exception.

Periodic : Random even in PC idle

https://prnt.sc/J8XBcVyxu40U

System.Exception: Failed to set window parent.
System.Exception: Failed to set window parent.
   at Lively.Core.WinDesktopCore.SetParentWorkerW(IntPtr windowHandle)
   at Lively.Core.WinDesktopCore.SetWallpaperPerScreen(IntPtr handle, IDisplayMonitor targetDisplay)
   at Lively.Core.WinDesktopCore.WallpaperInitialized(Object sender, WindowInitializedArgs e)

**Comment by rocksdanister** [comment]
Share the zip file: Right-click tray-icon -> Report Bug -> Create log report file.

**Comment by prounlocks** [comment]
here it is
[lively_log_20231027_153054.zip](https://github.com/rocksdanister/lively/files/13189015/lively_log_20231027_153054.zip)

**Comment by rocksdanister** [comment]
Update the software v7.0.4.0.

**Comment by prounlocks** [comment]
Okay John will let you know how it feels
