### ISSUE TITLE
Gif isnt animating on either monitor (Highcontrast mode.)

### ISSUE THREAD

**Issue by Scorchmaster101** [rocksdanister/lively#1972]
When i use one of the animations within the library, it isnt being animated on either monitor. Im currently trying to use a new Gif ive created with Giphy and when i preview the gif it works fine but doesnt work either from clicking on the image in the library nor from right clicking and setting as wallpaper. 
1. I go to my library
2. Select my animated image or as right clicking
3. it loads the image just not as animated on both monitors
Im expecting the image to be animated like the preview is.
OS: Windows 11 version 22H2
Ive tried all wallpapers and the one ive made
[lively_log_20231028_002205.zip](https://github.com/rocksdanister/lively/files/13194777/lively_log_20231028_002205.zip)

**Comment by rocksdanister** [comment]
Update the software to latest v2.0.7.4

**Comment by rocksdanister** [comment]
> I go and click on the image to animate as the wallpaper and it doesnt animate and instead loads the still image same goes with right clicking and selecting set as wallpaper. Steps to reproduce the behavior:
> 
> 1. click or right click the image to set as wallpaper
> 2. it loads either partially or not at all as a still image
>    It loads just as a still image when its should be animated.
> 
> Screenshots: ![Screenshot (1)](https://user-images.githubusercontent.com/149228444/278799230-faec6800-22bc-4ba4-8bbb-c7c73d1e0ee8.png) ![Screenshot (4)](https://user-images.githubusercontent.com/149228444/278799246-4b10afa4-c9ae-4653-805a-d06af97f3077.png)
> 
> OS: Windows 11 version 22H2 I am using the matrix and the jelly fish animations
> 
> Share the diagnostic files by: [lively_log_20231028_002205.zip](https://github.com/rocksdanister/lively/files/13194876/lively_log_20231028_002205.zip)
> 
> Recently updated to new version and i still have the problem
> 
> Thanks for the help

**Comment by rocksdanister** [comment]
Share the new diagnostic files after update.

**Comment by Scorchmaster101** [comment]
________________________________

**Comment by Scorchmaster101** [comment]
should i send the log via email or from github.
thanks
________________________________

**Comment by rocksdanister** [comment]
github please.

**Comment by Scorchmaster101** [comment]
Do I create a new log report or is there a simpler way of sending it



Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone



-------- Original message --------
From: Dani John ***@***.***>
Date: 10/28/23 1:54 PM (GMT-08:00)
To: rocksdanister/lively ***@***.***>
Cc: Scorchmaster101 ***@***.***>, Author ***@***.***>
Subject: Re: [rocksdanister/lively] Gif isnt animating on either monitor (Issue #1972)


github please.

**Comment by rocksdanister** [comment]
just drag and drop the file in the website?

<img width="985" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/1d330891-5802-45f5-949a-6a728e15dfea">

**Comment by Scorchmaster101** [comment]
[lively_log_20231028_030820 number 2.zip](https://github.com/rocksdanister/lively/files/13196725/lively_log_20231028_030820.number.2.zip)

**Comment by Scorchmaster101** [comment]
Im wondering if it could be a hrtz problem as i dont have the most advanced monitors as they cap at 60hrtz but im no wiz in the computer world. 
And thanks for the help too btw

**Comment by rocksdanister** [comment]
Can you turn OFF Windows high contrast mode, restart system and try again.

**Comment by Scorchmaster101** [comment]
Doing this saved the wallpapers being animated. But if i were to switch to a darker contrast theme will it bug it out again? 
And thanks for the help too

**Comment by rocksdanister** [comment]
> But if i were to switch to a darker contrast theme will it bug it out again?

See if it fails when switching to high contrast mode to verify.
