### ISSUE TITLE
Gif isnt animated but the preview works fine

### ISSUE THREAD

**Issue by Scorchmaster101** [rocksdanister/lively#1973]
I go and click on the image to animate as the wallpaper and it doesnt animate and instead loads the still image same goes with right clicking and selecting set as wallpaper.
1. click or right click the image to set as wallpaper
2. it loads either partially or not at all as a still image
It loads just as a still image when its should be animated.

Screenshots: 
![Screenshot (1)](https://github.com/rocksdanister/lively/assets/149228444/faec6800-22bc-4ba4-8bbb-c7c73d1e0ee8)
![Screenshot (4)](https://github.com/rocksdanister/lively/assets/149228444/4b10afa4-c9ae-4653-805a-d06af97f3077)

OS: Windows 11 version 22H2
I am using the matrix and the jelly fish animations

Share the diagnostic files by:
[lively_log_20231028_002205.zip](https://github.com/rocksdanister/lively/files/13194876/lively_log_20231028_002205.zip)

Recently updated to new version and i still have the problem

Thanks for the help

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/1972

**Comment by rocksdanister** [comment]
Uploaded the new logfile after updating in the original issue.
