### ISSUE TITLE
Lively doesnt even open

### ISSUE THREAD

**Issue by yofukashino** [rocksdanister/lively#1975]
**Describe the bug**
Since I updated my windows to build no 22621.2506 I am unable to even get lively to open. (windows 11 btw)

**To Reproduce**
1. Update windows to os build number 22621.2506
2. Restart
3. Try to open lively

**Expected behavior**
lively to appear in tray and maybe play the wallpaper

**Screenshots/Video**

https://github.com/rocksdanister/lively/assets/73281112/ed25fe87-9019-44da-a861-c03a950e0b76

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
the Lively folder in Local dir doesn't exist and cant get the logs through tray icon as it doesn't exist

**Comment by rocksdanister** [comment]
If its store version the appdata folder is:
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\logs`

Also check the event viewer for Lively.exe crashes.

**Comment by yofukashino** [comment]
![image](https://github.com/rocksdanister/lively/assets/73281112/51d137c2-1b87-4f95-a72d-e662a721c421)
it gives this and its exe version

**Comment by yofukashino** [comment]
thanks for the help. I reinstalled my .NET Runtimes and it works now. apparently windows update fricked up my runtimes
