### ISSUE TITLE
Video wallpaper blue

### ISSUE THREAD

**Issue by rubywastaken** [rocksdanister/lively#1979]
My wallpaper should be the bottom left. The app just updated and all I can see in my desktop is a solid blue color, and not the wallpaper I applied.

![image](https://github.com/rocksdanister/lively/assets/143356421/a47a8eae-1af6-423f-a384-13c31003c71d)

**Comment by rocksdanister** [comment]
Share the .zip logfile here:
Right-click tray-icon -> Report Bug -> Create log report file.

**Comment by rubywastaken** [comment]
> Share the .zip logfile here: Right-click tray-icon -> Report Bug -> Create log report file.

[lively_log_20231030_124725.zip](https://github.com/rocksdanister/lively/files/13200911/lively_log_20231030_124725.zip)

**Comment by rocksdanister** [comment]
Try turning off GPU decode in wallpaper -> Video player settings.

If that did not work, uninstall store version of Lively and install the github version and try to change the mpv video player as suggested here:
https://www.reddit.com/r/LivelyWallpaper/comments/x4m06u/comment/k6xa89w/?utm_source=share&utm_medium=web2x&context=3

> If you are using installer version of Lively I would try replacing Plugins/mpv folder with different versions of the player and see if any of them work:
https://sourceforge.net/projects/mpv-player-windows/files/32bit/
The one being used right now is mpv-i686-20231015-git-78d4374.7z so skip that.

Report back if it fixes the issue and the mpv player version.

**Comment by rubywastaken** [comment]
> Try turning off GPU decode in wallpaper -> Video player settings.
> 
> If that did not work, uninstall store version of Lively and install the github version and try to change the mpv video player as suggested here: https://www.reddit.com/r/LivelyWallpaper/comments/x4m06u/comment/k6xa89w/?utm_source=share&utm_medium=web2x&context=3
> 
> > If you are using installer version of Lively I would try replacing Plugins/mpv folder with different versions of the player and see if any of them work:
> > https://sourceforge.net/projects/mpv-player-windows/files/32bit/
> > The one being used right now is mpv-i686-20231015-git-78d4374.7z so skip that.
> 
> Report back if it fixes the issue and the mpv player version.

- Turning off GPU decode doesn't work.
- Uninstalled the store version and switched to the Github version
- Downloaded and replaced the mpv plugins to latest (a57bd8e7z, tried 32-bit and 64-bit.) Doesn't work.
- Also tried updating GPU drivers in case it needs new version, doesn't work.

**Comment by rocksdanister** [comment]
> Downloaded and replaced the mpv plugins to latest (a57bd8e7z, tried 32-bit and 64-bit.) Doesn't work.

1. Also try a few older versions of mpv player.
2. Is it also blue when you try playing the file directly in mpv player (open mpv.exe and drag'n'drop the file.)

**Comment by rubywastaken** [comment]
> 1. Also try a few older versions of mpv player.
> 2. Is it also blue when you try playing the file directly in mpv player (open mpv.exe and drag'n'drop the file.)

- Tried the 20231001 build, it works now.
- No, it plays fine.

Thanks.

**Comment by rocksdanister** [comment]
I need some help submitting bug report to mpv team (mpv player log.)

Steps to generate mpv player log:
1. Revert back to `mpv-i686-20231015-git-78d4374.7z` version of mpv player (copy to plugin folder.)
2. Create directory in `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Mpv\portable_config`
3. Create file mpv.conf with the content
```
--log-file="D:\\output.txt"
```
Change `D:\\` to different driver letter as required.
4. Play a video wallpaper in Lively and make sure its blue and let the log file generate.
5. Attach the output.txt file here.
