### ISSUE TITLE
How to remove screensaver

### ISSUE THREAD

**Issue by 13gears13** [rocksdanister/lively#1980]
**Describe the bug**
Game freezes, NOT RESPONDING, necessitating END TASK

**To Reproduce**
Install the Lively.scr 

**Desktop (please complete the following information):**
Win10x64

**Additional context**
I uninstalled LIVELYWALLPAPER, but the Lively.scr remains in the system, so now I don't know how to uninstall it and I'm hooped.  Someone help.  The screensaver now glitches when it attempts to come on.  I'll try to disable screen saver in the meantime.  But I'd like a method of how to remove the Lively.scr keys from registry fully and completely.  Thanks.

**Log file (Important)**
deleted not found

**Comment by rocksdanister** [comment]
1. Select a different screensaver in [Windows settings](https://www.windowscentral.com/how-enable-screen-savers-windows-10)
2. [Delete the .scr file from C:\Windows](https://github.com/rocksdanister/lively/wiki/Screen-Saver#1-windows-screensaver-file) 

The .scr is just a simple console command and it should not result in game crashing.
