### ISSUE TITLE
After a few moments, video webpage is not playing

### ISSUE THREAD

**Issue by bhlox** [rocksdanister/lively#1984]
**Describe the bug**
Video is not being played despite the debugger logs showing it is played / playing.  Playback works initially both pause and play controls but after a few minutes or switches depening on foreground app, video is just paused forever.

**Screenshots/Video**
Code snippet to handle video playback
![code](https://github.com/rocksdanister/lively/assets/86870447/47e0efa9-534d-444e-b2fe-1db1b94add2e)

video webpage screen recording

https://github.com/rocksdanister/lively/assets/86870447/30206ee2-de62-496b-81a4-331854364295

**Desktop (please complete the following information):**
 - OS: windows 11 Version 22H2 (OS build 22621)
 
 **Additional info**
 When I haven't implemented the code snippet above, I encountered a different issue. when it was paused for a few seconds then playback resumes, playback would fast forward then return normal speed depending on how long video playback was paused.

**Log file (Important)**
[lively_log_20231031_131037.zip](https://github.com/rocksdanister/lively/files/13212266/lively_log_20231031_131037.zip)

**Comment by rocksdanister** [comment]
What is the video codec used? if its VP9 try with VP8 for compatibility.

**Comment by bhlox** [comment]
![image](https://github.com/rocksdanister/lively/assets/86870447/306f8dff-7ba6-405a-a891-84a16b301e65)

Not sure how do determine if it's VP8 or VP9.
Also, any recommendations to converting video types?

**Comment by bhlox** [comment]
So I've converted the VP9 to 2 VP8 video files. One was high quality and other was just standard quality.

high quality VP8 showed same issues with the VP9 / original.
Standard quality VP8 showed different issue. After a few moments of just regular use, it would loop the first 5 seconds of the video non stop BUT pause and play playback is perfectly working.

**Comment by rocksdanister** [comment]
Does the issue still happen after sometime with wallpaper pause disabled in Lively settings?

<img width="647" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/55e72546-89b6-429b-9c0c-1d507115659b">

**Comment by bhlox** [comment]
I haven't tried that setup but will try it.

Currently this is my setup. When application fullscreen was set to nothing, encountering the issue made it less frequent.
![image](https://github.com/rocksdanister/lively/assets/86870447/aa9beb7e-b59f-4eab-8ea8-54e5385a741a)

**Comment by bhlox** [comment]
Even with wallpaper paused disabled in settings, issue still happens. Frequency of encountering issue is same with my previous setup (screenshot above)

**Comment by rocksdanister** [comment]
What does the CefSharp logfile say?

`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Cef\logfile.txt`

File gets overwritten each time, may have to run again.

**Comment by bhlox** [comment]
Here you go. (Just encountered issue again compared to few days ago)

[logfile.txt](https://github.com/rocksdanister/lively/files/13371126/logfile.txt)

**Comment by rocksdanister** [comment]
@amaitland Any idea what's happening? Issue seems to be appearing even with Lively options disabled.

**Comment by bhlox** [comment]
Repo: https://github.com/bhlox/lively-test

**Comment by amaitland** [comment]
> [1116/064721.022:ERROR:gpu_init.cc(525)] Passthrough is not supported, GL is disabled, ANGLE is 

What is the `GPU`? Does it have `Hybrid Graphics`? Does the problem reproduce on different distinct hardware?

**Comment by rocksdanister** [comment]
From the applogs:

OS: Microsoft Windows 11 Home 10.0.22621
CPU: AMD Ryzen 5 7645HX with Radeon Graphics
GPU: NVIDIA GeForce RTX 4050 Laptop GPU
GPU: AMD Radeon(TM) 610M

**Comment by bhlox** [comment]
<img width="859" alt="image" src="https://github.com/rocksdanister/lively/assets/86870447/e7837bc2-85ff-463f-a81b-641ee700ac5b">

My main screen is my 2nd monitor not my laptop screen. So mainly using the dGPU which is the nvidia.
Not sure if issues exists when using iGPU since I rarely use my iGPU

**Comment by amaitland** [comment]
Screenshot suggest that your machine is using Hybrid auto. 

For a test either switch to using your dedicated GPU always or have `CefSharp.BrowserSubProcess.exe` run on your dedicated GPU.

`CefSharp.BrowserSubProcess.exe` will be spawned multiple times, one of those will be the GPU process.
