### ISSUE TITLE
Right Click Does not Open up desktop options

### ISSUE THREAD

**Issue by JL1172** [rocksdanister/lively#1995]
**Describe the bug**
I am on a windows 10 os and when I right click on the desktop, the whole screen and computer freezes for 30s to a min. Sometimes the wallpaper changes. I wanted to create a new shortcut, so I right clicked on my desktop, and that is when I noticed the issue. I believe when I first got this app, it did not do that. 

**To Reproduce**
1. Right click on desktop
2. this is the only step

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS : windows 10
- rain wallpaper

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Share log report .zip file:
<img width="285" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/52426712-1d97-445b-9900-a38c8dfeed62">

**Comment by kaiquebr** [comment]
the same here, and i cant see files on desktop when livelly begins to run and sometimes the taskbar dont show up
