### ISSUE TITLE
Audio visualizer not working (Fluid)

### ISSUE THREAD

**Issue by JDM222012** [rocksdanister/lively#1997]
Exactly the title

1. Go to Spotify/YouTube
2. Play Any Song/Video
3. Apply Fluids Wallpaper

It should show bursts of fluid

**Screenshots/Video**
https://github.com/rocksdanister/lively/assets/134944308/26cb3306-9c2d-4e49-bb84-5625c44ec999

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
- Fluids/Music TV (LQ)

**Additional context**

**Log file (Important)**
[20231110_185425.txt](https://github.com/rocksdanister/lively/files/13323888/20231110_185425.txt)

**Comment by rocksdanister** [comment]
>But it is showing on Music TV (LQ)

What do you mean by this exactly? a video showing it would help.

**Comment by JDM222012** [comment]
just added it to the issue

**Comment by rocksdanister** [comment]
The NAudio library I am using is not receiving audio output, this usually happens due to incompatibility with the audio playback device (Virtual sound device etc..)

Try changing the primary audio device, turning off any enhancements in Realtek/audio control panel.
