### ISSUE TITLE
Wallpaper not changing.

### ISSUE THREAD

**Issue by LEADERS22** [rocksdanister/lively#2]
When even i try to change the wallpaper it just doesn't work and goes back to normal desktop unless it has audio which will start playing. The only solution i found is to load the wallpaper i want then reboot or log out then start the app again and it will loud up fine.

**Comment by rocksdanister** [comment]
share the logfile

**Comment by LEADERS22** [comment]
[logfile.txt](https://github.com/rocksdanister/lively/files/3935173/logfile.txt)

**Comment by rocksdanister** [comment]
Can't really do much unless I get a win7 system & win7 is reaching End-of-Life soon, I marked it as a bug for now.

**Comment by rocksdanister** [comment]
Can you try again, I did try fixing the windows 7 issue.

**Comment by LEADERS22** [comment]
I would love to test it but idk whats wrong with my computer all of a sudden lively keeps crashing on startup with all versions.
[20200317_235014.txt](https://github.com/rocksdanister/lively/files/4346249/20200317_235014.txt)

**Comment by rocksdanister** [comment]
Looks like its having trouble finding the registry key to add to windows startup.

**Comment by LEADERS22** [comment]
Do you know a way to fix it?

**Comment by rocksdanister** [comment]
Not sure, I did not get this error on my windows 7 virtual machine.

**Comment by LEADERS22** [comment]
Both problems fixed.

**Comment by Axolotl-King2** [comment]
i have the same problem and i got the app today on my pc what do i do
