### ISSUE TITLE
Automatic wallpaper change

### ISSUE THREAD

**Issue by Enigma1309** [rocksdanister/lively#2007]
Add a option to choose a random wallpaper either based on timing or multiple option like:- Random at boot then switch automatically after a given fixed interval of time.
Also make this option more flexible by adding user selected shuffle
say i have 5 wallpaper  
1.mp4 , 2.mp4, 3.mp4, 4.mp4, 5.mp4  (or any other extension)
but i only wanted 1.mp4 , 3.mp4, 4.mp4 to be chosen at random (basically like user favorite's wallpaper)

i hope you got the idea, thanks ❤️

**Comment by rocksdanister** [comment]
This is planned for future update :D

**Comment by Enigma1309** [comment]
okay thanks
