### ISSUE TITLE
Exception: Exception

### ISSUE THREAD

**Issue by itzlxkshxn** [rocksdanister/lively#2009]
Hey, whenever i try to keep a Wallpaper it is not coming, The app is opening but I'm not able to keep the wallpaper.. Instead it is coming

Error
Oops... Looks like something went wrong :(
In Order to better understand this error and fix the issue, share the log file with developer.
Instructions for sharing log file:

Exception:
Exception

[lively_log_20231115_175236.zip](https://github.com/rocksdanister/lively/files/13365526/lively_log_20231115_175236.zip)
![Screenshot (126)](https://github.com/rocksdanister/lively/assets/150927863/cead8f9e-d274-4c8c-957b-bdc28965e48b)
](url)

I've attached the log file as well as a screenshot, please do the needful,
Thank you! [

**Comment by rocksdanister** [comment]
Log is not much helpful here, do you have any third party Anti-virus program that may have deleted some Lively files?

I'll also try installing Visual C++ runtime incase the installer missed it:
https://github.com/rocksdanister/lively/wiki/Common-Problems#web-wallpapers-not-working

**Comment by itzlxkshxn** [comment]
I only have Proton VPN in my computer, nothing else!

**Comment by rocksdanister** [comment]
Did you try installing Visual C++ runtime?
