### ISSUE TITLE
Can't build & run because 'Plugins' is not part of the repository

### ISSUE THREAD

**Issue by Dannotech** [rocksdanister/lively#2011]
**Describe the bug**
The project cannot be built & run from Visual Studio because 'plugins' is missing.

**To Reproduce**
1. Sync the repository on a fresh computer.
3. Open the solution file with VS2022 community.
4. Notice 'Lively/Plugins' failed to load
5. Build & Run the project.
6. Observe exception indicating that 'Lively.UI.WinUI.exe' cannot be loaded.

"Lively.Services.RunnerService::System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Code\External\Lively-Wallpaper\src\Lively\Lively\bin\Debug\net7.0-windows10.0.18362\plugins\UI\Lively.UI.WinUI.exe' with working directory 'C:\Code\External\Lively-Wallpaper\src\Lively\Lively\bin\Debug\net7.0-windows10.0.18362\plugins\UI'. The system cannot find the file specified."

**Expected behavior**
Build and run should "just work" or there should be documentation about what other setup steps are needed to ensure that it compiles.

**Comment by Dannotech** [comment]
Specifically, there doesn't appear to be any source code in Lively/Plugins, as this directory does not exist on the Github repo.  An oversight, perhaps?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Building
