### ISSUE TITLE
Walpaper not working

### ISSUE THREAD

**Issue by faishalaqib** [rocksdanister/lively#2012]
When i want to using the walpaper the app wont play it ,and there some alert appear on my screen laptop? Please Solve it
![Lively Log](https://github.com/rocksdanister/lively/assets/67756096/e286ed62-8025-4364-8763-59e0e8d4acc8)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#having-a-problem-how-do-i-get-help--how-to-retrieve-log-files
