### ISSUE TITLE
Animated background progessively delayed on second monitor

### ISSUE THREAD

**Issue by ValePanzer** [rocksdanister/lively#2016]
Lively takes longer to load on one monitor than the other when choosing a video or any other kind of animated medium to duplicate on both screens. It can have around two seconds of delay and is a bit off-putting when having a video run with sound.
I remember it being more on point some versions ago but I can't tell when the last time was.

I tried reinstalling/repairing and setting everything to default via Windows settings, what options could i try to minimize the delay?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#having-a-problem-how-do-i-get-help--how-to-retrieve-log-files

**Comment by rocksdanister** [comment]
Logfile is no longer needed, I figured out the issue and changed things. 
Next update will have the fix.

**Comment by ValePanzer** [comment]
Thank you!
