### ISSUE TITLE
Lively Starts with Windows, Does Not Load Wallpaper, Cannot Open App

### ISSUE THREAD

**Issue by McJorgan** [rocksdanister/lively#2020]
I have a log file as soon as I figure out how to upload it.

It is in the comment

**Comment by McJorgan** [comment]
[lively_log_20231127_082309.zip](https://github.com/rocksdanister/lively/files/13474807/lively_log_20231127_082309.zip)

**Comment by McJorgan** [comment]
I'm reinstalling. This is the only fix I know of at this time.

**Comment by McJorgan** [comment]
Redownloaded and reinstalled from *Microsoft Store*. I now remember why there may be a problem. Windows Updated recently. Is there another place I can try to get it from?

**Comment by rocksdanister** [comment]
There are two versions of Lively.

Usually app UI not opening is an issue with the framework (WinUI3), I reported the issue to the repo but there seems to be no update on it so far.
