### ISSUE TITLE
[Feat. Req] Fullscreen/Game Mode. 

### ISSUE THREAD

**Issue by momoe** [rocksdanister/lively#2027]
When detecting any full-screen window, or game launched from a set of directories, it would be useful to have the live wallpapers go into a 'game mode' where the process priority drops, and limits itself to a setting enabled FPS. Or if it can even go into a suspended state until the viewable desk-space is restored?

**Comment by rocksdanister** [comment]
>Or if it can even go into a suspended state until the viewable desk-space is restored?

Lively already pauses wallpaper (0% usage) when running fullscreen games.

Can you explain why you want this different behaviour of fps drop and process priority?

As far as I am aware its not recommended to change process priority, can cause stability issue.
For the fps control last I checked CEF (Web wallpapers) don't have this option so my hands are tied, it maybe possible for Mpv (video wallpapers.)
