### ISSUE TITLE
Shell restart prevents Lively wallpapers from displaying

### ISSUE THREAD

**Issue by TechniKris** [rocksdanister/lively#203]
**Description**
After restarting the Windows shell wallpapers stop displaying. I can't switch to a different wallpaper either (with an exception, see _Additional context_). Restarting Lively by hand fixes the issue.

**To Reproduce**
1. Start up Lively
2. Open a file explorer window
3. Open the task manager
4. Restart shell by closing/"restarting" the file explorer window using the task manager
5. (optionally) Try opening Lively window and switching to a different wallpaper

**Expected behavior**
Lively wallpaper doesn't get influenced by the shell restart, or it automatically refreshes itself upon shell restart so it becomes visible again.

**Screenshots/Video**
-------

**Desktop:**
 - OS: Windows 10 20H2
- Wallpaper: any (I didn't test static image wallpapers in Lively though)

**Additional context**
Eternal Light (I think it was bundled with Lively by default) seems to be the only wallpaper that can be selected/reselected after a shell restart without restarting the entire program. However a weird side effect is that after selecting it it shows up on the taskbar and task manager as libMPVPlayer and becomes vulnerable to shortcuts like e.g. Alt+Tab, Win+D and others.

**Log file**
[20201122_132023.txt](https://github.com/rocksdanister/lively/files/5579461/20201122_132023.txt)
Here I started it up with _Ribbon_ wallpaper selected selected, then restarted shell, then tried switching to _Fluids v2_, to _Eternal Light_ and to _Fluids v2_ again to provide more potentially useful logs.

**Comment by TechniKris** [comment]
I forgot to mention: I'm using the most recent version of Lively as of now, that is v1.1.4.0

**Comment by rocksdanister** [comment]
Thanks for the detailed issue report.
Yes I am aware of this, currently the setup is only done once when initial wallpaper is set:
https://github.com/rocksdanister/lively/blob/d4972447531a0a670ad8f8c4724c7faf7c619d8b/src/livelywpf/livelywpf/Core/SetupDesktop.cs#L54

Will need to make two changes:
1. Every time wallpaper is set check if things are setup properly.
2. Detect shell restart, set things up again and then close and reapply currently running wallpapers.

(1) is straightforward.
(2) need to look into detecting shell restart.

**Comment by Dipanshu6** [comment]
oh ok thanks
