### ISSUE TITLE
High GPU usage after Lively Update (Windows 11 23H2)

### ISSUE THREAD

**Issue by KhaledFelfal** [rocksdanister/lively#2031]
**Describe the bug**
After updating Lively to the latest update + updating to 23H2, GPU usage got very high on idle (+95%). With the laptop fan moving so quick.

**To Reproduce**
Nothing, just normally running Lively.

**Expected behavior**
Normal GPU usage without the laptop fan even running.

**Screenshots/Video**
![Screenshot 2023-12-04 233432](https://github.com/rocksdanister/lively/assets/62517244/ce1eef45-ff98-471c-82f8-f515c2c695a0)
![Screenshot 2023-12-04 235335](https://github.com/rocksdanister/lively/assets/62517244/411851ac-6009-4d30-8847-bcd1d89f7d8a)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
- Video Wallpaper mpv player

**Additional context**
I used Lively for a year normally but suddenly after doing Windows update + Lively update from Microsoft Store this issue appeared.

**Log file (Important)**

[lively_log_20231204_233638.zip](https://github.com/rocksdanister/lively/files/13551501/lively_log_20231204_233638.zip)

**Comment by rocksdanister** [comment]
That usage is not overall, but should be video rendering engine only.. that too at lower clocks:
https://github.com/rocksdanister/lively/wiki/Performance

If you prefer can turn off GPU Decode in Settings -> Wallpaper -> Video Player.

**Comment by KhaledFelfal** [comment]
Hello again, even with GPU decode OFF, the gpu usage is still very high. 
![image](https://github.com/rocksdanister/lively/assets/62517244/ecc08b26-dd12-49e3-8cea-90927ab36bde)

**Comment by rocksdanister** [comment]
You can update/change Mpv player yourself by copying it to `<Lively install location>\plugins\Mpv`

Mpv player builds can be found here:
https://sourceforge.net/projects/mpv-player-windows/files/32bit/
The one being used currently is 20231008.

But this will require changing from Store version to installer since msix don't allow changing installed files.
This should get fixed automatically when I update the build myself in the next update, you can try different builds and let me know which works if possible.

**Comment by sliceanddice9** [comment]
> You can update/change Mpv player yourself by copying it to `<Lively install location>\plugins\Mpv`
> 
> Mpv player builds can be found here: https://sourceforge.net/projects/mpv-player-windows/files/32bit/ The one being used currently is 20231008.
> 
> But this will require changing from Store version to installer since msix don't allow changing installed files. This should get fixed automatically when I update the build myself in the next update, you can try different builds and let me know which works if possible.

Has the update since been released on the Microsoft Store? Because I'm using a video wallpaper with mpv (which came built-in to the Lively Wallpaper by default), and my GPU goes from 98% to even 100% when using the video wallpaper.

**Comment by rocksdanister** [comment]
Next update (this month) will have updated mpv player.
