### ISSUE TITLE
Some options not translated to Dutch.

### ISSUE THREAD

**Issue by CeelB-2055440** [rocksdanister/lively#2032]
**Describe the bug**
Inside the settings of the app there is a tab background (the third tab).
The first option is "Desktop Picture" with the description "Set a picture of animated wallpaper as desktop wallpaper".
This is not translated to Dutch while it is marked as 100% translated on the site: https://crowdin.com/project/lively-wallpaper/nl .

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Achtergrond' ('Background' in English)
3. Scroll down to 'Uiterlijk & gedag' ('Appearance & behavior' in English)
4. See the first option 'Desktop Picture'.

**Expected behavior**
I expect that this says: 'Bureaublad achtergrond' with the explanation saying: 'Stel een afbeelding uit de geanimeerde achtergrond in als bureaublad achtergrond. '

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/71815809/af4472cd-d39f-4125-b6a0-9662b2e0753b)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 23H2
- Which wallpaper was running at the time if any.
Personal wallpaper (not relevant).

**Additional context**
App installed from Microsoft store.

**Log file (Important)**
[lively_log_20231205_004645.zip](https://github.com/rocksdanister/lively/files/13552549/lively_log_20231205_004645.zip)

**Comment by CeelB-2055440** [comment]
I found a second error in translation also under te tab Background:

![image](https://github.com/rocksdanister/lively/assets/71815809/c876ed8b-a30a-4d30-84d8-cf4f36f192b4)

Here it says: 'GPU Decode', this should be: 'GPU-decodering'. 
The description says: 'Use hardware acceleration when possible.', this should be translated to: 'Gebruik hardwareversnelling indien mogelijk.'

**Comment by rocksdanister** [comment]
Don't create issues for translation, Lively is community translated.. submit correction directly: https://crowdin.com/project/lively-wallpaper
