### ISSUE TITLE
Screen Saver Request

### ISSUE THREAD

**Issue by anhjuku** [rocksdanister/lively#2036]
**Is your feature request related to a problem? Please describe.**
-------------------------------------------------------------------------------------------------------
I want the desktop and the screen protector screen to be set differently.
-------------------------------------------------------------------------------------------------------
**Describe the solution you'd like**
-------------------------------------------------------------------------------------------------------
The main screen and the main screen protector are usually screens
Set the second screen wallpaper and screen saver separately
-------------------------------------------------------------------------------------------------------
**Describe alternatives you've considered**
-------------------------------------------------------------------------------------------------------
I'm currently using a second monitor, but if I set the background picture, the screen protector is only possible with the same picture, so I hope there is a function to set the background screen and screen protector differently
-------------------------------------------------------------------------------------------------------

**Additional context**
Add any other context or screenshots/mockups about the feature request here.
-------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/587
