### ISSUE TITLE
Resize image to desired screensize before launching as window

### ISSUE THREAD

**Issue by 0qln** [rocksdanister/lively#2037]
Problem
---
Images that are bigger than they need to be to show in desired quality for the screen take up a lot of memory. 
The way I have been doing things until now, is resizing the images externally for the resolution I need. But this get's annoying to do when having to repeat this for every image. Additionaly, this process has to be done multiple times for each image, when one has monitors of different resolution or alignment.

Solution Proposal
---
Before lauching the image as a window for the wallpaper, the image should automatically be resized (and or cropped) to the minimum size needed. 

Additinal Information
---
I have currently not found the time to search for and install all needed dependecies to build and debug Lively. I will notify when I can take on the implementation of this feature.

**Comment by rocksdanister** [comment]
You are talking about using pictures as wallpaper?
Lively is just using the MPV video player which has limitations and high memory usage.

The most efficient solution is to simply set the image as Windows wallpaper, there is already an implementation for this but not used since I can't reset the wallpaper when closing and screensaver requires window.

> Before lauching the image as a window for the wallpaper, the image should automatically be resized (and or cropped) to the minimum size needed.

This won't be necessary, since I do plan to just switch to setting as Windows wallpaper in the future.

**Comment by 0qln** [comment]
>The most efficient solution is to simply set the image as Windows wallpaper, there is already an implementation for this but not used since I can't reset the wallpaper when closing and screensaver requires window.

Using windows only does not give the customizability that Lively can offer. Just setting different wallpapers for different screens is not really possible with vanilla windows. If windows offered customizability options like Lively, there wouldn't be a point for it.

> You are talking about using pictures as wallpaper?
Lively is just using the MPV video player which has limitations and high memory usage.

Yes, and also videos, but for now I was just focusing on pictures as the resizing would be a quick implementation and if the goal is performance, you would generaly stray away from videos as wallpapers anyway. 

> This won't be necessary, since I do plan to just switch to setting as Windows wallpaper in the future.

I am not known with the details of the Lively backend, but I assume implementing this for pictures would set a first step to implement this for videos as well, for which memory usage is an even more important aspect. 
If it doesn't matter, do you plan on implementing it such that a single big image (composed of the different images the client selects monitor-wise) which then spans across monitors? I suppose that would be quite reasonable approach which will implement the feature in question indirectly. 

Considering you are probably busy with more important changes, I can offer to implement this and create a PR?

**Comment by rocksdanister** [comment]
> Using windows only does not give the customizability that Lively can offer. Just setting different wallpapers for different screens is not really possible with vanilla windows. If windows offered customizability options like Lively, there wouldn't be a point for it.

This is possible and already implemented.

No third party software is even needed, can be done directly from Windows:
<img width="308" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/04ba333e-aef5-4fb8-a2cf-e93d815c165a">

**Comment by 0qln** [comment]
I have seen claims like that online but (atleast for me) I can only set different backgrounds for desktops and not monitors. 
![image](https://github.com/rocksdanister/lively/assets/129159411/6c685cb2-a6f6-46ea-8e19-887a59305a45)

**Comment by rocksdanister** [comment]
Because the Windows UI is not great.

When you have virtual desktops open the menu changes to desktop, close them:

<img width="814" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/3c13a9be-3fd2-4dd1-bf1b-3bf5774c9df0">

Once it looks like this that menu should update to monitor:

<img width="663" alt="image" src="https://github.com/rocksdanister/lively/assets/17554161/1946e97c-b737-4ffc-97be-17a6e3c2a6dd">

**Comment by 0qln** [comment]
I cant help but laugh at his 😂Who even is resonsible for the UI at microsoft??

Anyway, thanks for your patience with me... 

That being said, I will continue to use Lively so I wont have to get headaches from interacting with the windows settings... 
when the time comes that I found the time to set up a fork of Lively and havn't switched to Linux already,  I will just implement this for me, cause having a 500mb wallpaper really triggers my undiagnosed ocd... 

thanks for creating this tool :)
