### ISSUE TITLE
Issue with Playing H.264 and H.265 Encoded Videos in HTML

### ISSUE THREAD

**Issue by wzn2009** [rocksdanister/lively#2039]
Hello, Lively Wallpaper Development Team,

I'm experiencing issues while trying to use H.264 and H.265 encoded videos embedded within HTML as backgrounds with Lively Wallpaper. I've found that these videos are not playing correctly, although they work fine in other regular video players.

I have tried various solutions including using alternative video formats, converting codecs, etc., but have been unable to resolve the issue. It seems that Lively Wallpaper is unable to load and play these specific encoded videos.

Is there any update, fix, or alternative solution available to support playback of H.264 and H.265 encoded videos? I'm looking to use these videos as backgrounds within Lively Wallpaper.

Thank you very much for your assistance and support!!!!!

您好，Lively Wallpaper 开发团队，

我在尝试将 HTML 中插入的 H.264 和 H.265 编码视频作为 Lively Wallpaper 的背景时遇到了问题。我发现这些视频无法正常播放，尽管它们在其他常规的播放器中能够正常播放。

我已经尝试了多种解决方法，包括使用其他视频格式、转换编解码器等，但无法解决这个问题。在 Lively Wallpaper 中似乎无法加载并播放这些特定格式的视频。

请问是否有任何支持 H.264 和 H.265 编码视频播放的更新、修复措施或其他解决方案？我希望能够在 Lively Wallpaper 中正常播放这些视频作为背景。

非常感谢您的帮助和支持！！！！！
![image](https://github.com/rocksdanister/lively/assets/84257514/a241ab8f-0679-4e91-95b1-99a3d3dac0bb)

**Comment by wzn2009** [comment]
I am Chinese and my English is not very good, so the above text was translated using translation software. I apologize for any inconvenience caused in reading, and I appreciate your understanding :)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Web-Guide-VI-:-Webpage-Video-Support
