### ISSUE TITLE
Run Lively as Screensaver

### ISSUE THREAD

**Issue by jean3x7** [rocksdanister/lively#204]
I want to use same animated wallpaper when my computer is idle as screensaver too.

![image](https://user-images.githubusercontent.com/32421544/99915778-7b6f7600-2ce4-11eb-9cc1-860f936570fb.png)

Thanks

**Comment by rocksdanister** [comment]
`A screensaver in Windows® is simply an executable file with the extension .scr.`
Did not know that 🤔, I think one way to do it would be to make a LivelyScreenSaver.scr program and this will message Lively to set the currently running wallpaper as a fullscreen window when windows calls it.

References:
https://www.codeproject.com/Articles/4809/How-to-develop-a-screen-saver-in-C
https://www.codeproject.com/Articles/31376/Making-a-C-screensaver
https://sites.harding.edu/fmccown/screensaver/screensaver.html

**Comment by bemoty** [comment]
hey, any news on this? i'm very interested in setting lively's dynamic wallpapers as screensaver

**Comment by rocksdanister** [comment]
Things turned a bit complicated now:
https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-removed-features

I will also have to write a fallback method and be ready to push it... in the event the official windows method stop working after a windows update - to stop people from flooding the issue xD

**Comment by Myles2** [comment]
Gotta say recently found this software and absolutely love it! I was actually looking for a way to make a .scr file from an mp4. Turns out there's no easy way and the only way I could find used .swf files, but with adobe flash being phased out it's no longer feasible.

Lively seems to be the best option for the future!
I would suggest that you make the LivelyScreenSaver.scr to have the option of choosing or being it's own display.
Currently I have two screens using different wallpapers, so having that option of choosing which wallpaper to use or even a totally different one would be nice. 
Thank you for this amazing program 😆

**Comment by rocksdanister** [comment]
I noticed a increased traffic recently, not sure what happened.. not that I mind 😁

>Lively seems to be the best option for the future!

Yeah..  videos, webpages, unity games, applications... there won't be a format Lively won't support as screensaver 😎

>I would suggest that you make the LivelyScreenSaver.scr to have the option of choosing or being it's own display.
Currently I have two screens using different wallpapers, so having that option of choosing which wallpaper to use or even a totally different one would be nice.

To keep things simple and code easy to maintain I will set the currently running wallpaper on the display(s) as screensaver(s) either by opening a new preview window fullscreen or using the already running wallpaper.

**Comment by Myles2** [comment]
That totally makes sense, I look forward to this feature! 
Also I would hope concerning the wallpapers that require some form of interaction to display that there could be a solution.

**Comment by rocksdanister** [comment]
>Also I would hope concerning the wallpapers that require some form of interaction to display that there could be a solution.

If you move mouse, screen saver should exit.. so no.

**Comment by rocksdanister** [comment]
https://user-images.githubusercontent.com/17554161/107903413-310e3600-6f6f-11eb-8d90-14b17ce8bc5c.mp4

**Comment by rocksdanister** [comment]
Beta is up:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.1.9.5
