### ISSUE TITLE
There seems to be some typographical errors in Chinese

### ISSUE THREAD

**Issue by s-j-y-m** [rocksdanister/lively#2041]
I'm not sure if it's a translation issue or a rendering issue
In Chinese, the meaning of this word is obviously not what this function should have
![{8F64FEE8-7BE8-4a7d-925D-1208BAB36AAE}](https://github.com/rocksdanister/lively/assets/152769561/7151fd1c-a393-4be1-a44c-4bdaefa56c65)
Here is a screenshot
This kind of error shouldn't need logs

我不确定这是翻译问题还是渲染问题
在中文中，这个词的意思显然不是这个功能应该有的
截图在上
这种错误应该不需要日志吧

**Comment by s-j-y-m** [comment]
在英文中,我标记的地方似乎是"..."
In English, the place I marked seems to be "..."

**Comment by rocksdanister** [comment]
It's suppose to be E712 or More which is font included with Windows:
https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font

What does the chinese text say?

**Comment by s-j-y-m** [comment]
I also have a rendering error in the search bar at the top, can you let me see the Chinese translation of the current version?
在顶部的搜索栏我也有渲染错误,能让我看看目前版本的中文翻译吗?

**Comment by rocksdanister** [comment]
https://crowdin.com/project/lively-wallpaper

**Comment by s-j-y-m** [comment]
似乎是我的渲染错误,我标记的地方不需要翻译成中文,并且应该是渲染为"..."
Seems to be a rendering error on my part, the places I marked do not need to be translated into Chinese, and should be rendered as "..."

**Comment by rocksdanister** [comment]
Does not reproduce in any of my system, closing this since the issue with the specific system.. could be corrupted Windows files/configuration.

**Comment by s-j-y-m** [comment]
em,my system does have a bit of bugs

**Comment by CescMessi** [comment]
> Does not reproduce in any of my system, closing this since the issue with the specific system.. could be corrupted Windows files/configuration.

I met the same question though I have checked `segoe ui symbol` font in my Windows 10. I've seen a same question in the [PowerToys issue](https://github.com/microsoft/PowerToys/issues/18055), which shows the same wrong Chinese search icon like lively wallpaper. I installed the `segoe fluent icons` font according to the [comment](https://github.com/microsoft/PowerToys/issues/18055#issuecomment-1151765308) and that solved the problem with lively wallpaper. 

I also read the [Microsoft doc](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#how-do-i-get-this-font), it said **Segoe Fluent Icons is not included by default on Windows 10.**, so maybe lively wallpaper need to do some other works for Windows 10 like PowerToys (they don't need to install the font now).

**Comment by rocksdanister** [comment]
If Segoe Fluent Icons is not present it should fallback to Segoe MDL2 🤔

**Comment by s-j-y-m** [comment]
After reinstalling the system, there will be no problem

**Comment by s-j-y-m** [comment]
Perhaps you should check if your Windows is a castrated version
