### ISSUE TITLE
Music Wallpaper Issues

### ISSUE THREAD

**Issue by LuciferWayne** [rocksdanister/lively#2043]
Music wallpaper has side and bottom scrolls which were not there before this update(i.e. v2.0.7.4)
 
 
![image](https://github.com/rocksdanister/lively/assets/128677614/16137799-a781-451b-8cc8-b752ce7941fc)

[lively_log_20231214_202235.zip](https://github.com/rocksdanister/lively/files/13674818/lively_log_20231214_202235.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/1996
