### ISSUE TITLE
Discord not being detected as a application and not pauzing the background.

### ISSUE THREAD

**Issue by Basgamer999** [rocksdanister/lively#2046]
**Describe the bug**
I got lively running with a video. If i switch to any application it pauzes the background. This is the intended behaivor and is what i want. However if i switch to discord my video doesnt pause. The sound of the video does mute but the video keeps playing.

**To Reproduce**
1. Go to 'settings to enable to always pause'
2. Click on 'discord'
3. go back to the desktop and see that your video isnt where you left it.

**Expected behavior**
Pause the video when discord is focused

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
Windows 10
Just a youtube video
[lively_log_20231217_145127.zip](https://github.com/rocksdanister/lively/files/13696324/lively_log_20231217_145127.zip)

**Additional context**

**Log file (Important)**
See attachments

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/789
