### ISSUE TITLE
When Lively Wallpaper is active, it hides all desktop symbols (WIndows insider.)

### ISSUE THREAD

**Issue by Surferdbeere** [rocksdanister/lively#2047]
When Lively Wallpaper is active, all desktop symbols are hidden. It also tells me that there is an issue but after I change the settings it tells me to change, nothing changes. This issue suddenly came up without me changing any setting the only thing I did is I downloaded the latest version of the Windows 11 Insider Preview.

**Comment by rocksdanister** [comment]
I don't support insider builds because things rapidly changes.
