### ISSUE TITLE
Compatibility with other overlays (rePaper)

### ISSUE THREAD

**Issue by Error45687** [rocksdanister/lively#205]
One thing I loved about rePaper was the beautiful clock options on top of your wallpaper. I know rePaper is no longer supported, but I am asking for a way to preserve this overlay of clock and weather atop lively wallpapers. Is this already possible? if so, let me know! Thanks.

**Comment by rocksdanister** [comment]
Actually rePaper is not a overlay, its doing the same thing as Lively - full screen application set as desktop wallpaper.

Currently this is not possible, however I do have plan to do widget support, you can follow the progress here https://github.com/rocksdanister/lively/issues/161
