### ISSUE TITLE
White wallpaper till I switch between two wallpapers (WebView2)

### ISSUE THREAD

**Issue by pickonedev** [rocksdanister/lively#2051]
**Describe the bug**
When the computer starts, the wallpaper it is already white/blank

**To Reproduce**
1. I used the installer app (not the windows store)
2. Then I have installed/configured VLC and WebView2 plugins
3. And I created a new website wallpaper with the link of my Home Assistant

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2 22000.2538 (I don't have any new update do make)
- The one with Home Assistant

**Additional context**
As far as I tested, seems that the problem it is from the WebView2 Plugin... If I use CefSharp, all good, no blank/white wallpaper, but I can't use Home Assistant with this plugin, because everytime I use Preview, in order to cache the login, when I set the wallpaper, it will ask me to login again, so... this is no use for me... Any solution to use the app with the WebView2 plugin? 
Thanks

**Comment by rocksdanister** [comment]
Webview2 is under development, do not create bug reports.

This should work login with CefSharp:
https://github.com/rocksdanister/lively/wiki/Common-Problems#can-i-login-to-websites

**Comment by pickonedev** [comment]
Yes, but as I already said, CefSharp it is not working for me...

**Comment by rocksdanister** [comment]
> Any solution to use the app with the WebView2 plugin?

It is under development so I am not taking any bug reports, there is no immediate plan to finish its development since its not readily modifiable like CefSharp.

Quick workaround would be to switch the wallpaper using commandline control.

**Comment by pickonedev** [comment]
I think it is not about switching the wallpaper, because I can switch it... The problem is that I cannot login to the webpage... And using preview to try and login, will not record any cache for the website to work logged in, as wallpaper. After I login with preview, still ask me to login in the wallpaper

**Comment by rocksdanister** [comment]
> White wallpaper till I switch between two wallpapers

You can switch/set the same wallpaper again (WebView2) using commandline-control.

**Comment by pickonedev** [comment]
Yes, but this means to run that command everytime I login to my computer... Even if is automatically... It is not the ideal workaround. Can I do somenthing in order to work with the CefSharp?

**Comment by rocksdanister** [comment]
Windows task scheduler and .bat script with a start delay should do it automatically.

I don't use home assistant, so not exactly sure why disk cache is failing here.
