### ISSUE TITLE
Switching to keyboard mode for a long time makes background buttons vanish permanently

### ISSUE THREAD

**Issue by IReportDumBugsOnDisAccount** [rocksdanister/lively#2053]
I acknowledged
**Describe the bug**
When switching to keyboard mode for a long time going back to the normal background switching to mouse breaks the buttons in the background permanently
**To Reproduce**
1. Open Lively Wallpaper
2. Click on 'Any Wallpaper'
3. Click on 'Settings'
4. Click on 'Wallpaper'
5. Scroll and Dropdown to 'Keyboard'
6. Wait for a long time
7. Click on 'Display'
8. Click on the 'x'
9. Click on 'Settings'
10. Click on 'Wallpaper'
11. Scroll and Dropdown to 'Mouse'

**Expected behavior**
I expected the background buttons are going to be back

**Screenshots/Video**
None

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 22H2 (build 22621)
- A wallpaper was running

**Additional context**
None

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 

Navigate to Appdata folder [lively_log_20231229_123829.zip](https://github.com/rocksdanister/lively/files/13795479/lively_log_20231229_123829.zip)

**Comment by rocksdanister** [comment]
I am not able to follow "background buttons vanish permanently", can you share a screenshot of the problem?
