### ISSUE TITLE
Bug: No process is associated with this object,

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#2056]
**Describe the bug**
The wallpaper works for a while then stops. The error is 'No process is associated with this object. Exception: Exception'.

**Desktop**
Windows 11 23H2
I was using a wallpaper for Windows.
[lively_log_20231230_104333.zip](https://github.com/rocksdanister/lively/files/13797722/lively_log_20231230_104333.zip)
![Screenshot 2023-12-30 110642](https://github.com/rocksdanister/lively/assets/143900952/669b72c1-3afe-49a0-9b99-3e89d93d20ed)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/2040
