### ISSUE TITLE
2 monitors

### ISSUE THREAD

**Issue by Lebanese3Arab** [rocksdanister/lively#2058]
I have 2 monitors and it doesn't show up on my other monitor. Im hoping you will add a feature where it shows on both monitors that would be great. Thanks

**Comment by rocksdanister** [comment]
To change selected monitor click the monitor button top-right:
https://github.com/rocksdanister/lively/wiki/Getting-Started

**Comment by Lebanese3Arab** [comment]
Oh thanks so much i love your app btw
