### ISSUE TITLE
Pause when in Remote Desktop session

### ISSUE THREAD

**Issue by peterneave** [rocksdanister/lively#207]
**Problem**
Running Lively with Fluids V2 and I remoted into my computer from another computer on the same network. The remote desktop session was difficult to use until I paused Lively.

**Suggestion**
Please detect remote desktop connections and pause automatically. Allow the user to toggle this behavior.

**Comment by rocksdanister** [comment]
Is it VNC or RDP?

**Comment by peterneave** [comment]
It was a RDP session. Technically I was using Remmina from a Ubuntu machine to RDP into a Windows 10 Machine.

**Comment by rocksdanister** [comment]
>The remote desktop session was difficult to use until I paused Lively.

Just to clarify, by pause you mean "Pause wallpapers" option in system-tray menu.

**Comment by rocksdanister** [comment]
I implemented it in beta build:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.1.5.1
If you have time try testing and let me know if it works.

**Comment by rocksdanister** [comment]
I just tested, working fine on my end.

**Comment by ghost** [comment]
Would it be possible with VNC?

**Comment by rocksdanister** [comment]
Maybe, its not so straightforward it seems:
https://stackoverflow.com/questions/973802/detecting-remote-desktop-connection

**Comment by xpusostomos** [comment]
Also chiming in here that this works terribly with Windows Remote Desktop. It wouldn't be so bad if it didn't work, if it at least could fall back to something better than black screen, because when you're trying to remote in and get a black screen, you think the whole connection is dead, and you can't tell when you have established the connection. For that reason, I can't use Lively.

**Comment by rocksdanister** [comment]
@xpusostomos Which version of Lively are you on? blackscreen pausing has been resolved for a while now.. it should show static wallpaper frame.

>It wouldn't be so bad if it didn't work.

Option to turn it off is also available in performance settings provided you are using latest version of Lively:

Installer:
![image](https://user-images.githubusercontent.com/17554161/164979926-fd66131d-aaa2-43b5-a4d8-3247d727e569.png)

Store:
![image](https://user-images.githubusercontent.com/17554161/164979995-1cfa3cd0-5c55-4276-8f39-bf3fa1caad36.png)

**Comment by xpusostomos** [comment]
I'm using the version provided in the Microsoft store.
