### ISSUE TITLE
Need help with making webpage wallpaper

### ISSUE THREAD

**Issue by SentientToast1** [rocksdanister/lively#2080]
I just wish to ask how i can make elements of the webpage wallpaper customizable in the app

Wallpaper: https://stoast1.vercel.app/shader.html

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction

https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data

**Comment by SentientToast1** [comment]
Thx
