### ISSUE TITLE
webview2 plugin cannot apply successful

### ISSUE THREAD

**Issue by hanson-reas** [rocksdanister/lively#2088]
I followed this tutorial exactly. 
https://github.com/rocksdanister/lively.wiki.git
![image](https://github.com/rocksdanister/lively/assets/55027818/0e640781-92e9-46c8-9a6c-b96111494a2f)
![image](https://github.com/rocksdanister/lively/assets/55027818/ac39f7af-f14a-47ce-b6c3-43e4180204f8)

But I still got this.
![image](https://github.com/rocksdanister/lively/assets/55027818/94fa701b-17c3-4976-baee-b63cce1e563f)

Want to know what the problem is?

**Comment by rocksdanister** [comment]
`Extract and copy Wv2 plugin folder to <install_location>/Plugins/`

It should be `Wv2` folder.
