### ISSUE TITLE
Wallpaper playlist / change daily / etc.

### ISSUE THREAD

**Issue by Fennecai** [rocksdanister/lively#209]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like a feature where the wallpapers can be set-up to change every X amount of time (every hour or day or 5 minutes etc.) automatically; and possibly include a way to choose what order they change in. It'd be a great feature to have because windows already has something similar with it's static wallpapers where they can be set to change every once-in-a-while by selecting multiple pictures. 

**Describe alternatives you've considered**
As an alternative, maybe lively should have a built-in "stitcher" for video wallpapers that allows you to combine multiple video wallpapers into one that cross-fades through them in a loop, along with the audio where applicable, though this wouldn't work for html5 and other non-video wallpapers

**Additional context**
I don't have any mock-ups of the idea

**Comment by rocksdanister** [comment]
deplicate: https://github.com/rocksdanister/lively/issues/137

**Comment by roboticsequalsfun** [comment]
I see I am a little late. But you can do this via [Lively’s Command Line Interface](https://github.com/rocksdanister/lively/wiki/Command-Line-Controls). You just need to make a script that manages when to change it. I also made a [program](https://github.com/RoboticsEqualsFun/lively-wallpaper-playlist) that does just that. It is still in alpha release, but will continue to gather more features.
