### ISSUE TITLE
Video wallpaper not working

### ISSUE THREAD

**Issue by OsinakiKun** [rocksdanister/lively#2090]
it said error. you shall report. It showed me code, My mind bogled, I report and I give you file
[lively_log_20240125_194421.zip](https://github.com/rocksdanister/lively/files/14053665/lively_log_20240125_194421.zip)
 Thank you

**Comment by rocksdanister** [comment]
This is a common issue, the current workaround is to disable audio https://github.com/rocksdanister/lively/issues/1514#issuecomment-1368348842
