### ISSUE TITLE
Application Fails to Detect Installed WebView2 Plugin

### ISSUE THREAD

**Issue by Fataff** [rocksdanister/lively#2095]
## Describe the bug
The application fails to detect the installed plugin despite successful installation.

## To Reproduce

Downloaded Lively Wallpaper on Microsoft store
Downloaded and extracted the WebView2 plugin as instructed.
Copied the extracted "Wv2" folder into the <install_location>/Plugins/.
Installed the WebView2 runtime using the provided Evergreen Standalone Installer x86.
Launched Lively application.
Enabled WebView2 in Lively settings under Wallpaper > Web Browser > Engine.

## Expected behavior
I expected the application to detect and utilize the installed WebView2 plugin for rendering web wallpapers.

## Desktop

OS: Windows 10
This website (https://burds.vercel.app/) was on wallpaper but I tried to switch to.

I followed all provided instructions carefully.
Despite the installation of the WebView2 plugin and enabling it in Lively settings, the application still fails to detect and use the plugin.
This issue persists even after restarting the application and the system and when opened as privileged.

[bug_report.txt](https://github.com/rocksdanister/lively/files/14098983/bug_report.txt)
![bug_reports_lively](https://github.com/rocksdanister/lively/assets/125413749/a2c4c747-7bea-4da0-a5a2-ddf6aa7f0bba)

**Comment by rocksdanister** [comment]
It is not possible to modify install location in Microsoft store version of Lively, Webview can only be installed in Installer version of Lively.

The folder you copied looks to be from a previous Installer version of Lively (unless you created yourself) but it's been uninstalled (empty.)
