### ISSUE TITLE
Video wallpaper pauses/stays paused when minimizing active window

### ISSUE THREAD

**Issue by Fennecai** [rocksdanister/lively#210]
**Describe the bug**
i have lively set to keep the wallpaper playing with certain applications running (via the performance menu, "do nothing" on specific apps)

when i minimize any of these window, the wallpaper pauses until i click on the desktop, despite the fact it was playing as intended when i was in the other app.

**To Reproduce**
1. configure settings to pause the wallpaper like this 
![image](https://user-images.githubusercontent.com/10889213/100560115-00710700-3272-11eb-895c-3cf9cfa4fd5d.png)
2.  set stuff up to not pause
![image](https://user-images.githubusercontent.com/10889213/100560136-1252aa00-3272-11eb-95c5-3c4e58b470ff.png)
3. open one of the apps you set up to not pause the wallpaper, then minimize to desktop by clicking it's icon in the taskbar (not by pressing the desktop button!)
4. the wallpaper is now paused for some reason.

**Expected behavior**
I expected the wallpaper to remain playing after minimizing to desktop from an app that doesn't pause the wallpaper

**Screenshots/Video**
not sure how to show this without a lot of work recording and uploading a clip to youtube

**Desktop (please complete the following information):**
 - OS: Windows 10
- Which wallpaper was running at the time if any: a custom video wallpaper I added to my library.

**Additional context**
I am not sure but maybe this is a conflict with Stardock's "Fences" program, which I use to organize everything on my desktop.

**Log file**
[20201129_181653.txt](https://github.com/rocksdanister/lively/files/5613373/20201129_181653.txt)

of particular note:
`
2020-11-29 18:37:52.7667|INFO|livelywpf.Core.Playback|Getting processname failure/handle null, resuming playback!
2020-11-29 18:42:04.2312|INFO|livelywpf.Core.Playback|Getting processname failure/handle null, resuming playback!
2020-11-29 18:42:08.2546|INFO|livelywpf.Core.Playback|Getting processname failure/handle null, resuming playback!
2020-11-29 18:42:14.2798|INFO|livelywpf.Core.Playback|Getting processname failure/handle null, resuming playback!
2020-11-29 18:42:15.3033|INFO|livelywpf.Core.Playback|Getting processname failure/handle null, resuming playback!
`

**Comment by rocksdanister** [comment]
Lively is not compatible with fences, fences is doing dll injection or something to overlay the icon and adding an exception to the fences exe wont do anything.
Also additional rules for system apps like explorer is not recommended, Lively already handles those.

**Comment by Da-mad-Gamer** [comment]
just make the first one (fullscreen app) as nothing :))
