### ISSUE TITLE
Lively Crashes when trying to add certain Games to "Application Rules"

### ISSUE THREAD

**Issue by pinksquared** [rocksdanister/lively#2104]
**Describe the bug**
Lively crashes when adding (in particular) Genshin Impact and Honkai Star Rail to the Application Rules. I assume this might be a mihoyo problem.

I have as of right now only tried with one other game (FFXIV) and there it worked as intended without crashing.

Something noteworthy is that the wallpaper background doesn't crash, only the interface seems to be affected.

**To Reproduce**
1. Have Genshin/Star Rail open
2. In Lively go to Settings > Performance > Application Rules
3. Try to add Genshin/Star Rail from the active applications
4. Lively Interface closes and doesn't add rule

**Expected behavior**
Adds the Application-pause Rule for Genshin/Star Rail and potentially other affected programs.

**Screenshots/Video**
![Animation-ezgif com-optimize](https://github.com/rocksdanister/lively/assets/50338543/cf11f3b8-d214-4e78-9954-8186a63c9a99)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home   Version	 10.0.22631 Build 22631
- Seems to be Wallpaper independent (Tried most included and some 3rd Party)

**Additional context**
In the common problems section of the wiki it said something about Riva Tuner & Afterburner, I have these installed right now, but the crash occurred even beforehand.

**Log file (Important)**
[lively_log_20240203_085105.zip](https://github.com/rocksdanister/lively/files/14150723/lively_log_20240203_085105.zip)

**Comment by rocksdanister** [comment]
> Lively crashes when adding (in particular) Genshin Impact and Honkai Star Rail to the Application Rules. I assume this might be a mihoyo problem.

Application rule is usually used for pausing when running non-fullscreen or windowed application/games that do not fill the whole screen, for the rest the default settings should work so I am not sure why you are trying to add games.

If you still want to add the games, can be done manually by editing:
**Installer**
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\AppRules.json`

**Microsoft Store**
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\AppRules.json`

```json
  {
    "AppName": "Discord",
    "Rule": 1
  },
  {
    "AppName": "Program name without .exe.",
    "Rule": 0
  }
```
where Rule 1 for ignore and 0 for pause.

> Something noteworthy is that the wallpaper background doesn't crash, only the interface seems to be affected.

The interface is a separate program from the wallpapers for stability, you can kill the interface without closing the wallpapers.

I don't see anything in the log (maybe I didn't write enough logging code for that section) the icon missing is maybe a hint.

**Comment by pinksquared** [comment]
Thank you for the help! 
Adding it manually to the JSON worked!

I am adding games to the rule because I run most of my games in windowed mode (my screen is ultra-wide and I like to use the extra space like a second monitor for stuff like Chrome).
