### ISSUE TITLE
Wallpaper do not pause when app is focused

### ISSUE THREAD

**Issue by syb3rYT** [rocksdanister/lively#2107]
**Describe the bug**
Lap resources are being used a lot quite recently and doesnt pause when an app is focused

To Reproduce**
1. open lively
2. Go to an app on fullscreen 
4. See that wallpaper still runs due to transparent taskbar

**Screenshots/Video**
(screen recording was not working so i had to use my phone)
![WhatsApp Image 2024-02-04 at 00 56 54_d0cdd6b0](https://github.com/rocksdanister/lively/assets/140216766/30c098b2-83c1-436b-a2dc-132ebbebb926)

![WhatsApp Image 2024-02-04 at 01 25 26_4e3a6cbe lively](https://github.com/rocksdanister/lively/assets/140216766/b2bf6bfa-cce9-44d2-a04d-cfca3eb1187c)

https://github.com/rocksdanister/lively/assets/140216766/479d93c5-edc2-442b-89ee-81cf31c46604

**Desktop (please complete the following information):**
 - OS: windows 11
 - cpu - intel i7 11th gen
 - gpu - intel iris xe graphics
 - storage - 512 gb
 - ram - 16 gb

- custom wallpaper (it was shortened as original file size was 35mb) : 

https://github.com/rocksdanister/lively/assets/140216766/6c23a881-9285-4a1f-876b-112e13b0dbbe

**Expected behavior**
drops in fps as wallpaper doesnt pause and uses a lot of resources

**Additional context**
this started maybe a week or two ago. 

**Log file (Important)**

[lively_log_20240204_005748.zip](https://github.com/rocksdanister/lively/files/14152688/lively_log_20240204_005748.zip)

**Comment by rocksdanister** [comment]
> Lap resources are being used a lot

https://github.com/rocksdanister/lively/wiki/Performance

>  doesnt pause when an app is focused

Change pause algorithm From "Direct3D" to "Foreground process" the default.
