### ISSUE TITLE
"WorkerWexception" Error i have changed my performace setting the steps it was telling me to do nothing happens, so basically what is happening i was selecting a wallpaper when i apply it works animates on desktop but the problem is makes my desktop icons taskbarrr hides everything just wallpaperr is showing.

### ISSUE THREAD

**Issue by tusharrajput001** [rocksdanister/lively#2116]
[lively_log_20240210_184102.zip](https://github.com/rocksdanister/lively/files/14229368/lively_log_20240210_184102.zip)

**Describe the bug**
when i was applying a wallpaper it works fine animates but my whole desktop icons and taskbar disappears only the live wallpaper is showing. and it sis showing me error WorkerWexception 

**Expected behavior**
i was nt able to use lively properley as it works before

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

https://github.com/rocksdanister/lively/assets/153857544/6a2d75b5-65ca-430b-b1f1-16e303533f0a

**Desktop (please complete the following information):**
 - OS: Windows 11

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Are you using windows 11 insider/dev version? What version number.

**Comment by tusharrajput001** [comment]
Yes i am using the Windows 11 insider version, But now i reinstalled my windows 11 and got out from insider program, its fine now working great...

and @rocksdanister what about the "Taskbar theme" it's still in development ??

**Comment by rocksdanister** [comment]
I recommend switching to [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) taskbar theme.

**Comment by iBlazeX** [comment]
> Are you using windows 11 insider/dev version? What version number.

This issue does seem to exist in current dev insider preview build. Because I'm facing the same issue recently.

![image](https://github.com/rocksdanister/lively/assets/85124169/6ee875ee-d329-4b3f-b9b0-c06f85177118)

Edition	Windows 11 Pro for Workstations
Version	24H2
Installed on	‎11-‎02-‎2024
OS build	26052.1100
Experience	Windows Feature Experience Pack 1000.26052.1100.0

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
