### ISSUE TITLE
Facing issue on Win 11 v26052

### ISSUE THREAD

**Issue by TarunDevPro** [rocksdanister/lively#2118]
Hi Dev Team,

I am using this but facing an error. I am unable to see my desktop.

Edition	Windows 11 Pro for Workstations
Version	24H2
Installed on	‎2/‎9/‎2024
OS build	26052.1000
Experience	Windows Feature Experience Pack 1000.26052.1000.0

[lively_log_20240212_102801.zip](https://github.com/rocksdanister/lively/files/14235277/lively_log_20240212_102801.zip)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
