### ISSUE TITLE
Windows update build 26052 interfering with Lively

### ISSUE THREAD

**Issue by keshka** [rocksdanister/lively#2120]
[lively_log_20240212_104103.zip](https://github.com/rocksdanister/lively/files/14248630/lively_log_20240212_104103.zip)

Last night Windows update applied 
Windows 11 Pro insider preview
Evaluation copy.Build 26052.ge_release.240202-1419
result:
Broke lively. Lively runs but no desktop icons show. I still run 8Gadgetpack and those gadget do appear once lively is started but no icons for items I have saved on my desktop.
Changing lively wallpapers does not help the problem.
Start/stop Lively does not help 
Lively indicates an error and suggested running systempropertiesperformance.exe and check/uncheck "Animate controls and elements inside windows". It was checked, toggling it had no effect even after restarting Explorer nor after restarting Windows.

Perhaps this will allow you to provide an update prior to Microsoft publishing this release to the general populous.

If I can provide any additional information or testing please let me know
Keshka Kotera

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
