### ISSUE TITLE
Desktop icons covered up by lively video - Control-D shows desktop but no video

### ISSUE THREAD

**Issue by TerminatedProcess** [rocksdanister/lively#2121]
**Describe the bug**
--> When I play a video for the lively desktop, it hides the icons on the desktop. It's just the video. I can get the taskbar. But to see the icons on the desktop, I have to hit Control-D. When I open the Lively app, I get a Error with instructions asking me to run SystemPropertiesPerformance.exe and toggle Animate Controls and elements inside Windows. This does not impact the error. 

**To Reproduce**
1. Start Lively. View error message and instructions.
2. Select a installed desktop such as "Periodic Table". Or import a video and select that.
3. Installs to desktop but no icons visible.
4. See attachments

**Expected behavior**
A clear and concise description of what you expected to happen. I should see icons on the desktop with lively under the desktop not over it.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![image_2024-02-13_115704359](https://github.com/rocksdanister/lively/assets/63432380/479d653d-1fe3-4c37-8486-91384cb8b380)
![image_2024-02-13_115716262](https://github.com/rocksdanister/lively/assets/63432380/80535fdd-8b7f-4829-941c-fb947d490d5f)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909] Windows 11 Dev branch
![aboutwindows](https://github.com/rocksdanister/lively/assets/63432380/988b1567-b1e3-4a6f-886b-82473318e8f4)

- Which wallpaper was running at the time if any.
I tried a few and also my home movies.

**Additional context**
Always displays the error with instructions when Lively app is opened.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
[lively_log_20240213_114002.zip](https://github.com/rocksdanister/lively/files/14269753/lively_log_20240213_114002.zip)

Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074

**Comment by TerminatedProcess** [comment]
Thanks!
