### ISSUE TITLE
Inaccessible Desktop

### ISSUE THREAD

**Issue by Black-Maniac** [rocksdanister/lively#2124]
**Renders user unable to access desktop**
To put it simply it doesn't let using desktop features such as task bar desktop files or desktop shortcuts. They still exists no doubt but to access them you have to close the app from running or access them through library. to simplify even further just think of it like a curtain over the windows of your room (i'm dumb best way i could put it). 

**To Reproduce**
1. Go to 'Lively wallpapers'
2. Click on 'any wallpaper'
3.See error

**Expected behavior**
You'll see all your desktop files and shortcuts vanish including the taskbar and only see the wallpaper

**Screenshots/Video**
![Screenshot 2024-02-16 141512](https://github.com/rocksdanister/lively/assets/160221253/2053b1a4-5576-4c65-aff4-501f4eec1834)

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2 (Home Single Language)
 - Build: 26058.1100
- Rain.

**Additional context**
I followed the correctional measures stated at the error pop up that appeared when i opened lively, but none of them worked.

**Log file (Important)**
[lively_log_20240216_135916.zip](https://github.com/rocksdanister/lively/files/14308625/lively_log_20240216_135916.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
