### ISSUE TITLE
Windows Store release

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#213]
![store_thumb](https://user-images.githubusercontent.com/17554161/100738303-650b9d80-33fb-11eb-852d-a16f44ef5eac.png)

A different version of Lively is now available in Windows Store.
**Github [release](https://github.com/rocksdanister/lively/releases) is still the better and recommended version of Lively to get.**
Store has some issue accepting xaml island application, so I had to remove some modern features.
If github version is working fine for you, then its best to continue using it.

If you like Lively don't forget to leave a rating/review to make it more discoverable :)

**Download:**
<a href='//www.microsoft.com/store/apps/9ntm2qc6qws7?cid=storebadge&ocid=badge'><img src='https://developer.microsoft.com/store/badges/images/English_get-it-from-MS.png' alt='English badge' width="142px" height="52px"/></a>

**Source code:**
https://github.com/rocksdanister/lively/tree/ms-store

**Differences between Store and Github version of Lively:**
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions

**Comment by Blackhawk95** [comment]
Wohoo 🎉🎉 no more smartscreen warnings
