### ISSUE TITLE
Lively wallpaper doesn't work anymore on Windows 11 Insider Dev Channel

### ISSUE THREAD

**Issue by TheTechWiz5305** [rocksdanister/lively#2133]
**Describe the bug**
The bug is that lively wallpaper doesn't work at all in the dev channel, instead when I open the app it shows this:
![image](https://github.com/rocksdanister/lively/assets/132825368/b17de495-eaae-42c2-8061-29ece8c799c3)

So, I did everything it said to do, and it still didn't work.
![image](https://github.com/rocksdanister/lively/assets/132825368/6eb82212-c4fa-4f76-9be6-dc5963151f0f)

I think it's a bug of some sort with the new Dev Channel updates, but logs will be attached!

**To Reproduce**
1. Start Computer
2. Log in
3. Open Lively
4. See Error

**Expected behavior**
I wanted my wallpaper to show up, but it didn't.

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/132825368/a82e50e5-68f7-438a-9652-12a55ad92e63)

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Preview 10.0.26052.1100 (ge_release)
- Rain was running at the time

**Log file (Important)**
[lively_log_20240224_075048.zip](https://github.com/rocksdanister/lively/files/14392883/lively_log_20240224_075048.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
