### ISSUE TITLE
Fatal Error when running scripts to hide/show Taskbar, W11

### ISSUE THREAD

**Issue by WandererTJ** [rocksdanister/lively#2136]
**Describe the bug**
I want to be able to toggle Autohide On and Off for the Taskbar (Windows 11) without having to go into settings every time to do it.
I found a good website that covers how to do that, and the shortcuts I made worked for what I wanted.
However, when clicking one and then the other, it causes Lively to crash.
https://www.makeuseof.com/windows-11-hide-taskbar-shortcuts/

Lively Wallpaper - Error
Lively has encountered a fatal error.
Windows Explorer restarted twice in the last 30 seconds! This may be a conflict between Lively and other desktop customization software or Windows. To avoid further issues, all wallpapers are terminated.

**To Reproduce**
1. Create shortcuts for both the Autohide on and Autohide off toggles per link above.
2. Double click one to apply (Hide Taskbar), then double click the other to apply (show taskbar).  Any combination works.
3. Lively will then crash.

**Expected behavior**
I just don't expect it to crash when doing this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 23H2]
- Custom Wallpaper based on a video created from layers in photoshop to cycle through the RGB Hue spectrum.

**Log file (Important)**
[lively_log_20240225_130732.zip](https://github.com/rocksdanister/lively/files/14397502/lively_log_20240225_130732.zip)

If there's a better way to achieve hiding/showing the taskbar that doesn't crash Lively, I would love to know what it is.

**Comment by rocksdanister** [comment]
The script is stopping the explorer process for taskbar which lively checks for detecting crash, there are better ways to hide the taskbar like using SW_HIDE or desktband.
