### ISSUE TITLE
WMF Video Player - Screen Fit will not change

### ISSUE THREAD

**Issue by WandererTJ** [rocksdanister/lively#2137]
**Describe the bug**

**To Reproduce**
1. Uninstall Microsoft Store Version
2. Download and Install the Github version for All Users
3. Download WMF plugin and place into the plugin folder
4. Set an MP4 Video to a monitor (Mine is 414MB, 2696 W x 2304 H, 30FPS, 13m10s, it's the same image cycling through RGB slowly)
5. Set Video Player to WMF in Settings
6. Try to change "Choose a fit" to any of the 4 options. Video will not be zoomed in at all, regardless of the choice. Only mpv is working.

**Expected behavior**
I expect to be able to set the fill just the same as I do with MPV

**Screenshots/Video**
Screenshots below
![Screenshot 2024-02-25 185917](https://github.com/rocksdanister/lively/assets/161246266/bef13903-289e-472f-a6fb-ed5142ad7c62)
![Screenshot 2024-02-25 185924](https://github.com/rocksdanister/lively/assets/161246266/7440f287-4aa9-4a1b-bce5-2211b22cd4af)

**Desktop (please complete the following information):**
- OS: [e.g. Windows 11 23H2]
- Custom Tron Wallpaper derived from a single image so that the Hue cycles through all RGB

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20240225_190058.zip](https://github.com/rocksdanister/lively/files/14398492/lively_log_20240225_190058.zip)

**Comment by rocksdanister** [comment]
Update wmf player to latest one from here:
https://github.com/rocksdanister/lively/releases/download/v2.0.7.0/lively_wmf.zip

**Comment by WandererTJ** [comment]
Now it's a new kind of messed up.....

![Screenshot 2024-02-25 221450](https://github.com/rocksdanister/lively/assets/161246266/30c5fe61-67c0-4919-a30f-36e639b78d75)
![Screenshot 2024-02-25 221457](https://github.com/rocksdanister/lively/assets/161246266/cd9c33b7-1add-4889-bea5-d234121251c7)
![Screenshot 2024-02-25 221506](https://github.com/rocksdanister/lively/assets/161246266/0c7d897b-50f8-4c53-b6de-33524ea2a601)
