### ISSUE TITLE
Music wallpaper not working

### ISSUE THREAD

**Issue by Hrobo776** [rocksdanister/lively#2143]
**The problem**
I have tried using windows media player to get it on with the Music TV (LQ) wallpaper, and despite having put the setting to WMF, it doesn't work, I have downloaded and installed the files correctly, I tried putting music with covers, different music, and even restarting WMP, but alas it still shows static and "NO SIGNAL"

**To Reproduce**
1.Do a fresh installation of Lively Wallpaper
2.Put in the wmf folder in the plugins folder
3.Put the wallpaper in Lively Wallpaper to Music TV (LQ)
4.Change the setting in wallpaper->video player to WMF
5.Launch WMP and play any music/song of choosing

**Expected behavior**
I expected the wallpaper to do one of the following: A.Show cover, title and the bars that represent the music audio. B.Show nothing but still show the title, and the bars that represent the audio
**Screenshots/Video**
Im playing music on WMP, despite having a cover, it doesn't show anything
![image](https://github.com/rocksdanister/lively/assets/154055859/c1e9b320-0143-4e1a-80ae-75578c4aea78)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
- Wallpaper: Music TV (LQ)

**Additional context**
Im new to this so I may be doing something wrong or Im misunderstanding something

**Log file**
[Uploading lively_log_20240302_102433.zip…]()

**Comment by rocksdanister** [comment]
> I have tried using windows media player to get it on with the Music TV (LQ) wallpaper, and despite having put the setting to WMF

This is unrelated to music wallpaper, this setting is for video wallpaper player Lively uses to show video wallpapers and I recommend setting it back to default mpv.

Music wallpapers works with most players out of the box, some will require additional plugin. For list of supported players and plugins check here:
https://github.com/rocksdanister/lively/wiki/Common-Problems#music-wallpapers-dont-show-albumart-or-track-information
