### ISSUE TITLE
Webpage wallpaper crash when running Eye Tracking exe

### ISSUE THREAD

**Issue by qualcunu** [rocksdanister/lively#2152]
**Bug description**
Upon using both UWP and installer Lively app, and launching the Eye Tracking exe file, the Fluids wallpaper will run for a brief time then crash with the code:
`Stdin write fail: Cannot access a disposed object.`
`Object name: 'System.Diagnostics.Process'.`

**Steps to reproduce the behavior:**
1. Import "Fluids & Eye" to Lively (Linked below)
2. Apply the wallpaper (Use Cefsharp)
3. In `"Fluids & Eye/js/"` launch `"GazeTrackWithTobii2.exe"`
4. Give the wallpaper 5 seconds to begin reacting to the eye tracker input 
(If nothing happens try re-applying the wallpaper, no need to restart the eye tracking file)

**Observed Behaviors**
Intended behaviors:
- The wallpaper should stop reacting to mouse inputs when receiving input from the eye tracker file
- The splats should appear random (but that is because I'm simulating someone's gaze moving around)
- If the exe file is closed, the wallpaper will remain unresponsive to mouse input (something I'm not worried about right now)

Unintended behaviors (The problem):
- The wallpaper stops reacting to input
- The wallpaper crashes
 

**Videos demonstrating the error:**
- In VSCode the wallpaper never crashes:
        [Lively with ET error demo pt1](https://github.com/rocksdanister/lively/assets/72537184/2dc3da80-f923-496e-9bf7-412949c5469a)

- In Lively the wallpaper always crashes:
        [Lively with ET error demo pt2](https://github.com/rocksdanister/lively/assets/72537184/1c4d74bd-8682-4f2b-b498-11353983b50c)

**Desktop**
 - OS: Windows 11 Home: 23H2
- Fluids & Eye (Modified Fluids wallpaper) (Linked below)

**Additional context**
I had an ambitious project to make my Tobii Eye Tracker function as an input for the Fluids wallpaper. Recently I was finally able to modify the wallpaper's code to do this, and works well in my vscode environment, but once I run it in Lively, it crashes.

(please note)
The actual program that sends the eye tracking information is `"GazeTrackWithTobii.exe"` but I created `"GazeTrackWithTobii2.exe"` because without an eye tracker you wouldn't be able to reproduce any results. It basically generates a random number in place of the gaze position. 

Unfortunately, I cannot access the chrome developer tools to investigate the issue, and while I have looked to see if other people had similar issues, there were no solutions or explanations presented. 

Also, while this isn't part of the issue, if you happen to know of an easy way for me to have the exe file launch with the wallpaper please let me know, I don't think there is, but it would make the wallpaper way more usable.

**Log file**
[lively_log_20240305_135530.zip](https://github.com/rocksdanister/lively/files/14500103/lively_log_20240305_135530.zip)

**Wallpaper file**
[Fluids & Eye.zip](https://github.com/rocksdanister/lively/files/14502403/Fluids.Eye.zip)

**Comment by rocksdanister** [comment]
I am not going to run the exe for safety reasons.

When it crashes what does the CefSharp logfile say?
**Installer**
`%LocalAppData%\Lively Wallpaper\Cef\logfile.txt`

**Microsoft Store**
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Cef\logfile.txt`

**Comment by qualcunu** [comment]
As for not running the exe, that's fine, totally get it! 
I've uploaded the original Cpp script to generate the exe file if that's at all helpful!
To set it up (Using Visual Studio):
1. Make a new project: `Windows Console Application (C++/WinRT)`
2. Move `main.cpp` to the project, which can replace the default main.cpp
3. go to the `project` tab, the last option `[project name] properties`, then under `configuration properties` -> `C/C++` -> `precompiled headers` change the `precompiled header` dropdown from `Use /Yu` to `Not Using Precompiled Headers`
4. Build the program, then copy to the `Fluids & Eye/js/` folder 
(On the line of code with the comment, changing the milliseconds() parameter sets the speed at which the numbers will generate.)
(Default is 500, Eye tracker's speed is 25)

**The cpp file I used to run the exe**
[Eye Tracker Sim.zip](https://github.com/rocksdanister/lively/files/14519667/Eye.Tracker.Sim.zip)

**CefSharp log**
Here is the log file from the windows version! The logs seem to stop outputting anything once the wallpaper crashes
[logfile.txt](https://github.com/rocksdanister/lively/files/14519579/logfile.txt)

Thanks for getting back to me so quick!

**Comment by rocksdanister** [comment]
I dont have time for this at the moment, too many open issues.

Try recreating this in minimal CefSharp project, if it still happens report to CefSharp directly.

Alternatively integrate the SDK in the Lively C# browser itself by modifying the project.
