### ISSUE TITLE
mpv high GPU usage when using video as live wallpaper

### ISSUE THREAD

**Issue by KannaSakura** [rocksdanister/lively#2157]
![image](https://github.com/rocksdanister/lively/assets/70749903/6c04b9a6-3ff2-452b-bc1a-8bf31996f38f)
![屏幕截图 2024-03-12 205032](https://github.com/rocksdanister/lively/assets/70749903/73997777-887c-4a07-bea2-39911f66daf1)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance

**Comment by yixiaojiu** [comment]
I also had this problem when using the latest version. When I rolled back to v2.0.6.5, the GPU usage dropped.

**Comment by rocksdanister** [comment]
How did you measure the readings? there will be differences in the usage based on the gpu clocks.. higher usage at lower clocks is better than low usage at high clocks for power usage.
