### ISSUE TITLE
App keeps crashing when opened

### ISSUE THREAD

**Issue by WXqwer** [rocksdanister/lively#2161]
I have looked up the wiki, and closed many apps. But it still keep crashing (90%) , but the fundamental features are good. Tks！
[lively_log_20240315_193539.zip](https://github.com/rocksdanister/lively/files/14615407/lively_log_20240315_193539.zip)

**Comment by rocksdanister** [comment]
moved: https://github.com/rocksdanister/lively/issues/2187
