### ISSUE TITLE
No explorer icons when lively is running a wallpaper

### ISSUE THREAD

**Issue by keshka** [rocksdanister/lively#2163]
**Describe the bug**

_**Explorer icons covered by lively wallpaper
lively displays error even after "animate controls and elements inside windows" has been dissabled/reenabled**_

**To Reproduce**

_**start lively and select any wallpaper. Wallpaper starts and explorer icons dissapear.**_

**Expected behavior**

_**work as lively has in the past with the ability to display explorer icons**_
_**Lively worked for many months until recient windows update**_

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
![Screenshot 2024-03-16 092710](https://github.com/rocksdanister/lively/assets/12778097/0e4d2718-0574-479d-b6ab-9bc737c8e22d)
![Screenshot 2024-03-16 092740](https://github.com/rocksdanister/lively/assets/12778097/863493c9-1617-493e-85b9-3c5ce789ed11)

 - OS: [e.g. Windows 10 1909]
 _**Windows 11 Pro**

- Which wallpaper was running at the time if any.
any lively wallpaper

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

[lively_log_20240316_093317.zip](https://github.com/rocksdanister/lively/files/14624528/lively_log_20240316_093317.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074

**Comment by keshka** [comment]
The test build referenced here did not solve the issue
https://mega.nz/file/dyUQiLjQ#TJykB0eWuVHVLdfwz7X_dniLDFszVN6TTuXhzI4FBgI
The issue persists on build 26080.ge_release.240308-1400
