### ISSUE TITLE
mpv using resources without any media running

### ISSUE THREAD

**Issue by HellGate94** [rocksdanister/lively#2168]
**Describe the bug**
mpv is using around 3% cpu in the background while no media is running and only displaying a simple image as wallpaper. while this is not much it still is wasted resources

**To Reproduce**
1. Create new Wallpaper from Image
2. Apply Wallpaper
3. Open Task Manager
4. Check Lively > mpv CPU usage

**Expected behavior**
mpv uses no resource at all

**Screenshots/Video**
![Taskmgr_2024-03-25_14-21-35](https://github.com/rocksdanister/lively/assets/8095602/8fd7745e-34c7-411c-b6b1-9b8ec06d1ee0)

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Home 10.0.19045
- CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
- GPU: NVIDIA GeForce GTX 1070

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/1412
