### ISSUE TITLE
Wallpaper Will Not Apply To Selected Monitor As Expected

### ISSUE THREAD

**Issue by preiner** [rocksdanister/lively#2169]
Summary:
My system has 3 monitors. 2 traditional displays with 3840x1920 and 2560x1440 and  a 1100x3840 screen that is built-in by Hyte to the case of the Hyte Y70 case.

OS: Win 11 x64 Pro (23H2)
Wallpaper: Any (that come with app by default)

Repro:
* Open App
*  Click on monitor icon in top right corner
* Choose 'Always pick screen when choosing wallpaper'
* Close this window
* At main window, right mouse click on ANY wallpaper and choose 'set as wallpaper'
* Notice wallpaper is set on monitor 1. IT NEVER PROMPTED OR OFFERED A CHOICE OF WHICH MONITOR TO SET
* Click monitor icon in top right corner
* Monitor 1 shows wallpaper (which is not what I wanted). I click monitor 3. Wallpaper doesnt move to monitor 3. There is no choice anywhere to move the wallpaper. You can delete the wallpaper but move choice is missing.

A found hack is to choose monitor 3, THEN goto main window and set wallpaper. This seems to force all future selections to monitor 3. Wallpaper selection can / should be selectable per monitor. This is very very unintuitive and completely different than windows wallpaper UI. It allows you to right mouse click and "set as monitor 1, set as monitor 2, set as monitor 3"

Thank you for this nice app. I hope you consider fixing this.

[lively_log_20240325_113832.zip](https://github.com/rocksdanister/lively/files/14748172/lively_log_20240325_113832.zip)

**Comment by rocksdanister** [comment]
`Always pick screen when choosing wallpaper` is left click selection of library item:

https://github.com/rocksdanister/lively/assets/17554161/82ab2da7-d974-42ea-bde1-c70c1d26b715
