### ISSUE TITLE
Wallpaper doesn't applies in the Background

### ISSUE THREAD

**Issue by athar-shabir** [rocksdanister/lively#2170]
**Issue:**

Wallpaper doesn't applies in the background as when applying the wallpaper it doesn't gets applied to the background, simply applies on the screen and one can do nothing, so needs to close the Application under Task manager forcefully. I am using Dell Inspiron 5410 2in1 laptop and 14" screen size, with display resolution (1920 X 1080).

**Occurrence:**

1. Open the Application.
2. Try to set any wallpaper.
3. The issue occurs.

**Expected Behavior**
All the icon's on desktop went away and can't do anything.

**System Details**

- OS: Windows 11 Build 26080.
- Happening with all the wallpapers.

[lively_log_20240326_023338.zip](https://github.com/rocksdanister/lively/files/14749551/lively_log_20240326_023338.zip)

**Comment by RaSan147** [comment]
thats probably a issue with that build of windows (I had similar issue, switched device, win 11, different build, working fine)
