### ISSUE TITLE
Cant get it to run keeps error message

### ISSUE THREAD

**Issue by Gira51** [rocksdanister/lively#2172]
Hello
I keep getting this error. I have downloaded the current version, and it keeps showing
I have followed the instructions with no luck.
see the attach screen shot and log
[lively_log_20240326_102641.zip](https://github.com/rocksdanister/lively/files/14759955/lively_log_20240326_102641.zip)
![Screenshot 2024-03-26 101919](https://github.com/rocksdanister/lively/assets/164902652/87c68bf6-1b7e-4122-ba8f-6113d239b716)

Please advise
gksc@verizon.net

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
