### ISSUE TITLE
app is accessing an disposed object. Stuck in a dead lock, not showing the wallpaper on screen but trying to dispose that object.

### ISSUE THREAD

**Issue by beingabdul0** [rocksdanister/lively#2173]
[lively_log_20240327_093254.zip](https://github.com/rocksdanister/lively/files/14767512/lively_log_20240327_093254.zip)

**Describe the bug**
I have wo monitor, one has the fluid wallper, second has the custom wallper. Suddenly they stoped working and when  I opend the app and tried to update the wallpaper it throwed an exception.  App is showing two active wallpaper but they are not there.

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/49483419/12533f4a-dce3-47af-9abc-7f2943610747)
![image](https://github.com/rocksdanister/lively/assets/49483419/7caf3886-aa2b-44da-a419-044af61cf76d)
![image](https://github.com/rocksdanister/lively/assets/49483419/ff57bea8-c112-43f9-a29d-a0098f05891b)

![image](https://github.com/rocksdanister/lively/assets/49483419/ff57bea8-c112-43f9-a29d-a0098f05891b)
**Desktop (please complete the following information):**
 - OS: Windows 10 latest as of date
- Fluid on promary screen, custom on extended

**Additional context**

**Log file (Important)**
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
![image](https://github.com/rocksdanister/lively/assets/49483419/ff57bea8-c112-43f9-a29d-a0098f05891b)

**Comment by rocksdanister** [comment]
It just means the browser crashed.

There are some CEF bugs with Iris graphics, I would start by updating the driver:
https://www.intel.com/content/www/us/en/support.html
