### ISSUE TITLE
No process is associated with this object,   after screen sleeps, but pc is still running. 

### ISSUE THREAD

**Issue by pir8radio** [rocksdanister/lively#2175]
**Describe the bug**
EVERY TIME after the screen shuts down from power settings, pc remains running, wiggle the mouse and screen fires back up, but lively has crashed.    two instances of logs attached. 

**Expected behavior**
Uh, not to crash..  lol  

**Screenshots/Video**
just trying to re-select animated wallpaper for # 2 produces this error, due to I assume whatever app/process crashed.
![image](https://github.com/rocksdanister/lively/assets/16748696/389f76d9-a12d-4465-9f48-18d29cc5a0c3)

**Desktop (please complete the following information):**
windows 11 pro,  animated desktop wallpaper on monitor # 2
Monitor 3 & 1 are 3440x1440, and monitor 2 is 515x1920
Must quit and restart app.
![image](https://github.com/rocksdanister/lively/assets/16748696/fa7a6bb4-c755-4fbf-a0c8-debfb43bed81)

**Log file (Important)**
[lively_log_20240329_184821.zip](https://github.com/rocksdanister/lively/files/14809743/lively_log_20240329_184821.zip)
[lively_log_20240329_210505.zip](https://github.com/rocksdanister/lively/files/14809744/lively_log_20240329_210505.zip)

**Comment by Coca0201** [comment]
fuck, this shit has no one ready to repair

**Comment by rocksdanister** [comment]
moved here: https://github.com/rocksdanister/lively/issues/2178#issuecomment-2111804461
