### ISSUE TITLE
Wallpaper over desktop.

### ISSUE THREAD

**Issue by fidgetsetc** [rocksdanister/lively#2177]
**Describe the bug**
The wallpaper goes over the desktop, icons are gone, when clicking "Show Desktop", and the desktop appears with the normal static wallpaper showing with my icons there.  This is an issue that bothers me as I use my desktop a lot, and my icons being gone annoys me.

**To Reproduce**
It just happened, idk how, sorry.

**Expected behavior**
For the desktop to actually show properly with the live wallpaper!

**Screenshots/Video**
![Screenshot 2024-03-31 163339](https://github.com/rocksdanister/lively/assets/141544274/0341dee2-9034-43c5-9bde-c7a24bc594b4)
![Screenshot 2024-03-31 163244](https://github.com/rocksdanister/lively/assets/141544274/8f538d7e-6d85-4a7f-98d9-548d0b0c4aeb)

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2 Insider Preview OS Build 26085.1
- Wallpaper: OpenGL Fluid Simulation

**Additional context**
When going to close or minimize a window, the taskbar hides for approximately half a second then shows again.

**Log file (Important)**
[lively_log_20240331_162910.zip](https://github.com/rocksdanister/lively/files/14817678/lively_log_20240331_162910.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
