### ISSUE TITLE
lively window not opening

### ISSUE THREAD

**Issue by asdbhasdnasd** [rocksdanister/lively#2180]
[lively_log_20240402_201216.zip](https://github.com/rocksdanister/lively/files/14841535/lively_log_20240402_201216.zip)

so i have used this app for a long time, and I recently wiped my windows installation and from then when I install and try to run it opens but the window for it doesn't open, I tried reinstalling and looking on Youtube and nothing
can you please help, it would mean a lot.

**Comment by iiissac233** [comment]
same as u, when I clicked "open lively" there was a dark windows and suddenly disappeared.

**Comment by Supurum** [comment]
If your problem is that the window is visible after installation, but when you close the window and try to show it again, it is not visible and closes, I may be able to help. 

It's easy. Change the Windows display language to "English (United States)". then window will then open.

refer to #2187
