### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Nitrowing** [rocksdanister/lively#2182]
**Describe the bug**
CPU usage at 20% when active and when other programs (tested with Task Manager and firefox) are maximized

**To Reproduce**
1. Lively running
2. Click on Maximize other program
3. See error

**Expected behavior**
CPU usage to drop

**Screenshots/Video**
![lively](https://github.com/rocksdanister/lively/assets/69222231/8943110b-3e25-4792-92d6-e2cb388067f9)

**Desktop (please complete the following information):**
 -Windows 11 22h2
![lively](https://github.com/rocksdanister/lively/assets/69222231/8943110b-3e25-4792-92d6-e2cb388067f9)

- fluids

**Additional context**

**Log file (Important)**

[lively_log_20240404_233509.zip](https://github.com/rocksdanister/lively/files/14877796/lively_log_20240404_233509.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance
