### ISSUE TITLE
Screensaver not on all monitors

### ISSUE THREAD

**Issue by Linux-Alchemy** [rocksdanister/lively#2184]
**Describe the bug**
Matrix Lively Desktop works great on all four monitors, no problem. But when it kicks over to the screen saver it only runs on two. 

**Expected behaviour**
Really expected it on all 4 monitors. Been using that ancient Matrix SS for ever that I'm sure many know. This Matrix rain effect is way better. Just need it on all the screens to complete the awesome. 

**Desktop (please complete the following information):**
Running Win 11Pro, plenty of power in the cpu/gpu to spare

**Log file (Important)**
[lively_log_20240405_220526.zip](https://github.com/rocksdanister/lively/files/14892007/lively_log_20240405_220526.zip)

**Comment by rocksdanister** [comment]
Screensaver function will have a change next update, should fix this.
