### ISSUE TITLE
Win+D hiding live wallpaper and hidden taskbar not being revealed when moving cursor to bottom of live wallpaper.

### ISSUE THREAD

**Issue by milan-tom** [rocksdanister/lively#2188]
**Describe the bug**
When I press Win+D to hide all apps, my old static wallpaper is shown.

**To Reproduce**
1. Press Win+D.
2. See old wallpaper.
4. Press Windows key.
5. See live wallpaper.
6. Move mouse to bottom of screen.
7. Observe taskbar not revealed.

NB: "Automatically hide the taskbar" setting should be on.

**Expected behavior**
When Win+D is pressed, the hidden taskbar should be shown when moving the mouse to the bottom of the screen.

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Dev
- Wallpaper running at the time: Rain

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
