### ISSUE TITLE
Missing Quotes prevent autostart when the path has spaces

### ISSUE THREAD

**Issue by SebbiUltimate** [rocksdanister/lively#219]
The autorun registry value under HKCU\Software\Microsoft\Windows\CurrentVersion\Run is missing quotes around the binary path, therefore Windows treats everything after the first space as arguments instead of a binary path and cannot find the executable when the path has spaces.

Fix: In  [src/installer/Script.iss Line 64](https://github.com/rocksdanister/lively/blob/ca264491091bcffb86ae8fed835262725b0b4e4d/src/installer/Script.iss#L64), replace
old:
`Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "livelywpf"; ValueData: "{app}\livelywpf.exe"; Flags: uninsdeletekey; Tasks:windowsstartup`
new:
`Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "livelywpf"; ValueData: """{app}\livelywpf.exe"""; Flags: uninsdeletekey; Tasks:windowsstartup`

**Comment by rocksdanister** [comment]
Nice catch! You are right:
https://jrsoftware.org/iskb.php?startwithwindows

But what I don't understand is why does it still work fine for many, the default install folder name is _Lively Wallpaper_ which has space; I also tested on a user account with space and its autostarting fine.

Todo: Will need to update the code in the main application also, not just the installer.
