### ISSUE TITLE
i clicked on keyboard mode on accident, then i switched back to mouse mode and the desktop icons are still not showing, i tried turning it off, restarting my computer, refreshing my desktop and still didnt work, please help

### ISSUE THREAD

**Issue by ItzDingle** [rocksdanister/lively#2190]
i clicked on keyboard mode on accident, then i switched back to mouse mode and the desktop icons are still not showing, i tried turning it off, restarting my computer, refreshing my desktop and still didnt work, please help

**Comment by Taiizor** [comment]
Please right-click on the desktop and enable the "Show desktop icons" option from the view options.

**Comment by ItzDingle** [comment]
thank you
