### ISSUE TITLE
Inconsistent tooltip display

### ISSUE THREAD

**Issue by IsaacHatton** [rocksdanister/lively#2208]
**Describe the bug**

Inconsistent tooltip display

**To Reproduce**

See video, hover over the icons in the main config window.

**Expected behavior**

Tooltips for all icons to explain them, was confused where the multi-monitor options were for a while.

**Screenshots/Video**

https://github.com/rocksdanister/lively/assets/74068072/50ed70d3-7d79-402f-b1f9-03f8031ba829

**Desktop (please complete the following information):**
Windows 11 23H2

**Comment by rocksdanister** [comment]
What should the tooltip for monitor dialog say?

**Comment by IsaacHatton** [comment]
I'm not particularly sure, as there's a distinction between the monitor/screensaver dialog and the rest of the settings in the UI.

Maybe "Choose Display" since that is the title of the dialog? 
Or "Display settings"?

**Comment by rocksdanister** [comment]
There is going to be more features in this dialog, Choose Display may not be a good choice anymore.

Internally it's called Control Panel, which I think fits.
