### ISSUE TITLE
When Windows Language is Korean, lively isn't working

### ISSUE THREAD

**Issue by donkrami** [rocksdanister/lively#2221]
**Describe the bug**
When Windows Language is Korean, lively isn't working

**Screenshots/Video**
When Windows language is Korean, 
![image](https://github.com/rocksdanister/lively/assets/149076005/7853abcf-0d3f-4d65-8170-3a02bf22e5f3)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 (19045.3570)
- Which wallpaper was running at the time if any.

**Additional context**
If, Windows Language isn't Korean (ex: Japanese) lively is working.

**Log file (Important)**
[20240504_113824.txt](https://github.com/rocksdanister/lively/files/15206427/20240504_113824.txt)

**Comment by WilsonBae** [comment]
It seems same problem with it.
https://github.com/rocksdanister/lively/issues/2187

**Comment by rocksdanister** [comment]
Can you try to reproduce the issue in beta build:
https://github.com/rocksdanister/lively-beta/releases/tag/v2.1.0.1

**Comment by WilsonBae** [comment]
latest beta Still not work

![image](https://github.com/rocksdanister/lively/assets/168512859/9f2a1aa1-c26e-47ad-8c35-28764be075ef)

[lively_log_20240517_144759.zip](https://github.com/rocksdanister/lively/files/15344188/lively_log_20240517_144759.zip)

**Comment by rocksdanister** [comment]
moving discussion to https://github.com/rocksdanister/lively/issues/2187 to avoid duplicate.
