### ISSUE TITLE
Lively Wallpaper running over the desktop Windows 24H2

### ISSUE THREAD

**Issue by Chickenkarim2009** [rocksdanister/lively#2223]
When Lively Wallpaper autostarts it somehow runs in foreground so you can't see your desktop icons or create a file on the desktop.
[lively_log_20240506_202309.zip](https://github.com/rocksdanister/lively/files/15224900/lively_log_20240506_202309.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074
