### ISSUE TITLE
Windows10 Store version use high CPU & GPU!!!

### ISSUE THREAD

**Issue by yiuwacheng** [rocksdanister/lively#223]
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**
**_Nice software without exe installation!
But a little high CPU ＆ GPU usage!
My operating system: Windows10 Professional 20H2.
My CPU: Intel(R) Core(TM) i7-9700KF, GPU: AMD 5700XT.
In the windwos10 task manager, lively wallpaper always uses about 16%CPU ＆ 26%GPU and 229MB memory, please check!_**

**To Reproduce**
1. Go to '...' **_→When running_**
2. Click on '....' **_→Nothing_**
3. Scroll down to '....' **_→Nothing_**
4. See error **_→Please have a look at the screenshots below!_**

**Expected behavior**
**_When the software is running, it uses hig CPU and GPU!_**

**Screenshots/Video**
If applicable, add screenshots/video to [help](url) explain your problem.
![屏幕截图 2020-12-09 020135](https://user-images.githubusercontent.com/14814188/101522722-94ee0e80-39c2-11eb-9133-9e0bd54535b2.png)

![屏幕截图 2020-12-09 014916](https://user-images.githubusercontent.com/14814188/101521416-c960cb00-39c0-11eb-8895-63846d089958.png)

**Desktop (please complete the following information):**
 - OS: →Windows 10 20H2
- Which wallpaper was running at the time if any. **_→Any wall papaer!_**

**Additional context**

**Log file**
Share the log file(s) from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs

**Comment by rocksdanister** [comment]
Resource usage depends on:
1. Wallpaper you run - livelywpf.exe is the main program and you can see in the screenshot its very minimal cpu and gpu.
LivelyCefSharp is the web browser used to run webpages as wallpaper, so without knowing what wallpaper you were running at the time hard to have any conclusion; regarding livelywpf.exe memory usage, it should drop after sometime idle.
2. Taskmanager reports usage % value is relative to clockspeed of the hardware, your GPU might be running at lower clocks. Use third party software like gpu-z to get the full picture.

Further read:
https://github.com/rocksdanister/lively/wiki/Performance

**Comment by yiuwacheng** [comment]
🆗
It seems that u are right, the usage is normal now, but i don't know why...
