### ISSUE TITLE
Check upgrade error&Crash

### ISSUE THREAD

**Issue by WXqwer** [rocksdanister/lively#2235]
**Describe the bug**
①Can't check upgrade properly.
②When i click the "Screen setting"button, the app will crash.（100%）

**To Reproduce**
1. Go to 'Home'
2. Click on 'Multi screen setting'
3. See error

**Screenshots/Video**
![{5A251644-9EF6-4EFC-B6BE-223548D98155}](https://github.com/rocksdanister/lively/assets/73450696/ed53851f-d353-4c78-b0ac-85514e47c6df)
![{87EDF56A-0F52-4840-8969-992CD5481C27}](https://github.com/rocksdanister/lively/assets/73450696/62c8adf9-bad2-4860-860d-af24ceba8824)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 23H2]
- AI wallpaper.

**Log file (Important)**
[lively_log_20240523_194052.zip](https://github.com/rocksdanister/lively/files/15416352/lively_log_20240523_194052.zip)
Thx.

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2234

**Comment by WXqwer** [comment]
> dup: #2234 Dup： #2234

![image](https://github.com/rocksdanister/lively/assets/73450696/ba29843c-679a-4f49-9246-834072914bd1)
Yes. 100% is good.

**Comment by WXqwer** [comment]
> dup: #2234 Dup： #2234

Check upgrade is my own internet problem?

**Comment by rocksdanister** [comment]
I think Github has issue in China, update checking code is not changed this update.
