### ISSUE TITLE
The main window automatically closes when trying to enter the "Choose Display" interface

### ISSUE THREAD

**Issue by E0x72-21** [rocksdanister/lively#2236]
**Describe the bug**
The main window automatically closes when I try to enter the "Choose Display" interface

**To Reproduce**
1.click on this:
![image](https://github.com/rocksdanister/lively/assets/85837864/bf7c3178-7fb9-4000-b368-81ccce75a1a1)
2.The main window automatically closes

**Expected behavior**
Successfully entered the "Choose Display" interface

**Screenshots/Video**

https://github.com/rocksdanister/lively/assets/85837864/7cf93d08-4194-41cf-9176-45a58600686f

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2

**Additional context**
none

**Log file (Important)**
[lively_log_20240523_091432.zip](https://github.com/rocksdanister/lively/files/15418294/lively_log_20240523_091432.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2235
