### ISSUE TITLE
Crashing with v2.1.0.4 update

### ISSUE THREAD

**Issue by Ssmokeess** [rocksdanister/lively#2237]
[lively_log_20240523_180117.zip](https://github.com/rocksdanister/lively/files/15418755/lively_log_20240523_180117.zip)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2234
