### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by andercard0** [rocksdanister/lively#2239]
**Describe the bug**
Can't change UI language 

**To Reproduce**
Open lively > General > language option is grey out

**Expected behavior**
Let me choose which language i want instead of based on my OS

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/43047877/7ce85f1d-51a3-4fc0-be41-fbd0c9a80af1)

**Desktop (please complete the following information):**
![image](https://github.com/rocksdanister/lively/assets/43047877/3bead274-897f-4529-80b1-042f813d4926)

**Additional context**
None

**Comment by rocksdanister** [comment]
Greyed out in Lively usually means its not available/implemented and not a bug.

dup: https://github.com/rocksdanister/lively/issues/1383
