### ISSUE TITLE
(Chocolatey) Install and uninstall not silent

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [rocksdanister/lively#224]
**Describe the bug**

Both the install and the uninstall do not respect the Inno setup parameters for silent install/uninstall. 

**To Reproduce**
Install:
1. Run `lively_setup_x86_full_v1160.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /ALLUSERS`
2. The VCRedist setup box will pop up (even though an up to date vcredist 2019 is installed)
3. After that is closed, the lively setup window will pop up.

Uninstall:
1. Run `"C:\Program Files (x86)\Lively Wallpaper\unins000.exe" /SILENT` (from `QuietUninstallString` registry key)
2. A message box will pop up: Application is running, do you want to close it?
3. After that is accepted, another message will pop up: Do you want to delete data folder?

**Expected behavior**

1. Running  `lively_setup_x86_full_v1160.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /ALLUSERS` should install Lively without any pop ups, and without running the setup afterward. 

It would be fine if it required a custom parameter, it just should be possible. Perhaps a custom parameter to disable launching after install, and another to disable the installation of dependencies. See `{param:ParamName|DefaultValue}` at https://jrsoftware.org/ishelp/index.php?topic=consts

2. Running the `QuietUninstallString` registry key should uninstall Lively without any pop-ups.

**Desktop (please complete the following information):**
 - OS: 
Win 10 20H2
- Which wallpaper was running at the time if any. 
N/A

**Additional context**

This would be required for creating a Chocolatey package.
https://github.com/rocksdanister/lively/issues/199

**Log file**
Share the log file(s) from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs
N/A

**Comment by rocksdanister** [comment]
So are you trying to publish it to Chocolatey? 
https://github.com/TheCakeIsNaOH/chocolatey-packages/tree/master/lively

If so I'm requesting you to stop.
Lively is still in heavy development and I would like to be able to control the distribution, I will publish to third party services in the future myself when I'm ready; Currently have no plans to publish on Chocolatey.

**Comment by TheCakeIsNaOH** [comment]
> So are you trying to publish it to Chocolatey?

Yes, I do want a Chocolatey package for my personal repository, and I might as well publish it to the Chocolatey.org repository as well for other people.

However, this bug is not exclusive to Chocolatey. There are other software management solutions on Windows (even down to the level of simple .bat files) where a silent install/uninstall would be useful.

> If so I'm requesting you to stop. Lively is still in heavy development and I would like to be able to control the distribution, I will publish to third party services in the future myself when I'm ready; Currently have no plans to publish on Chocolatey.

I take it then that even if I provided a PR to fix the Inno silent parameters it would not be merged at this point?

**Comment by rocksdanister** [comment]
>Yes, I do want a Chocolatey package for my personal repository, and I might as well publish it to the Chocolatey.org repository as well for other people.

For the time being I am not looking for too much publicity, I change/play with things too often on github release version of Lively and I rather avoid it for the time being (I am also not a big fan of people installing Lively on others/organizations computers.)

>I take it then that even if I provided a PR to fix the Inno silent parameters it would not be merged at this point?

If its only VCRedist fix then it will be merged, rest not right now.

**Comment by TheCakeIsNaOH** [comment]
> For the time being I am not looking for too much publicity, I change/play with things too often on github release version of Lively and I rather avoid it for the time being (I am also not a big fan of people installing Lively on others/organizations computers.)

Ok, I won't publish on Chocolatey.org.

> If its only VCRedist fix then it will be merged, rest not right now.

Kind of pointless then. Time to play with repackaging I guess.

**Comment by rocksdanister** [comment]
>Ok, I won't publish on Chocolatey.org.

Thanks, appreciate it.

>Kind of pointless then. Time to play with repackaging I guess.

Like you mentioned, if you make it a custom parameter that does not affect the regular installer then I'm fine; I just don't want to retest everything again right now.

**Comment by TheCakeIsNaOH** [comment]
I played around with it, and silent uninstall works if I pass it `/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-`, which is fine I guess, not as good as having the `QuietUninstallString` work, but fine.
