### ISSUE TITLE
the system can't find the specified file

### ISSUE THREAD

**Issue by adri2111** [rocksdanister/lively#2246]
![helpe](https://github.com/rocksdanister/lively/assets/170796863/9e846746-5d5f-437b-9f28-87217d7c699c)
i don't know how to fix the error :(

**Comment by rocksdanister** [comment]
Lively files got deleted, some Anti-Virus program heuristic algorithms may falsely flag Lively files so I would check its quarantine.

I only verify Lively with Microsoft Security, You can help out by reporting False-Positives directly to the software vendor:
https://www.autohotkey.com/boards/viewtopic.php?t=62266
