### ISSUE TITLE
Upgrading to v2.1 deletes media wallpaper settings

### ISSUE THREAD

**Issue by SpongebobSquamirez** [rocksdanister/lively#2247]
**Describe the bug**

- Upgrading on Windows 10 removes your "Customize" settings for all your wallpapers
- It also removed my set default desktop wallpaper for when Lively is not running
- It also did not want to even open up the Customize menu or the About menu the first time I ran Lively after upgrading

**To Reproduce**
Upgrade Lively from the previous release version

**Expected behavior**
I would like my settings to be preserved, or to be properly warned to save them before upgrading.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2

**Additional context**

- I saved this log file after reopening Lively and then attempting to tweak my Customize settings again. Unfortunately, I didn't try saving the log file when I was initially having problems (and I don't know if the program would have cooperated anyway).
- I have not restarted my computer since upgrading.

**Log file (Important)**
[lively_log_20240525_210310.zip](https://github.com/rocksdanister/lively/files/15443341/lively_log_20240525_210310.zip)

**Comment by rocksdanister** [comment]
It is listed in the full changelog:
https://github.com/rocksdanister/lively/releases/tag/v2.1.0.6

> For better flexibility and user control wallpaper scaler settings are now applied for individual media file and wallpaper layout like span and duplicate.
This feature is only available when Mpv video player is selected.
**Old media customization settings will be cleared to enable this feature.**

Default desktop wallpaper setting(s) cleared is not due to update, likely Windows related.
