### ISSUE TITLE
I have installed the. net runtime environment, but it pops up when compiling in vsstudio. How can I solve this problem

### ISSUE THREAD

**Issue by skyperZhang** [rocksdanister/lively#2249]
![Weixin Image_20240527111554](https://github.com/rocksdanister/lively/assets/158008823/f8fd645d-1b29-4bb2-aa41-5fddd7aa2be6)

**Comment by skyperZhang** [comment]
I am very certain that I have installed. net desktop runtime

**Comment by rocksdanister** [comment]
For compiling you need the .NET Desktop SDK, not runtime.

**Comment by skyperZhang** [comment]
yes,.Net desktop SDK is also installed

**Comment by rocksdanister** [comment]
This sounds like a tooling issue and I cant help you, look online for similar visual studio issues or report to visual studio team.
