### ISSUE TITLE
H264 <video>

### ISSUE THREAD

**Issue by Krosnoz** [rocksdanister/lively#225]
Hi, I would like to be able to play a video in an html tag so <video> but it doesn't seem to work. After some research, I understood that the H264 codecs are not copyright free for CEF. So it would be necessary to build a modified version of CEF accepting H264 support, I tried to work around but it seems that I'm missing tools because I can't do anything.

Is it possible to build a modified version to accept these codecs or is there another possibility?

I know I could just put in a video, but I need an html file to write text over it.

Thanks for your patience!

**Comment by rocksdanister** [comment]
You can use vp9 codec:
https://github.com/rocksdanister/lively/wiki/Web-Guide-VI-:-Webpage-Video-Support

**Comment by Krosnoz** [comment]
Works like a charm.

Sorry for the useless post, I should have looked better!

**Comment by rocksdanister** [comment]
When in doubt, check the docs!
