### ISSUE TITLE
When screen saver activates, there is a loading screen for a split second

### ISSUE THREAD

**Issue by IanDaBest** [rocksdanister/lively#2252]
**Describe the bug**
Probably not that important but when the screen saver activates, there is a loading screen with the lively logo and the words 'please wait', which was not there last version.

**To Reproduce**
1. Wait until the screen saver activates
2. See error

**Expected behavior**
The wallpaper will immediately start

**Desktop (please complete the following information):**
 - OS: Windows Version 23H2 (OS Build 22631.3593)
- Any wallpaper

**Log file (Important)**
[lively_log_20240528_183742.zip](https://github.com/rocksdanister/lively/files/15466444/lively_log_20240528_183742.zip)

**Comment by rocksdanister** [comment]
Yes, screensaver is a new running instance with the latest release.

The loading is there so that the user knows what's happening (especially on old systems.)
