### ISSUE TITLE
Wallpaper stops when click on taskbar up arrow

### ISSUE THREAD

**Issue by westor7** [rocksdanister/lively#226]
**Describe the bug**
- When you click on Taskbar up arrow to see the hidden icons the wallpaper stops playing.

**To Reproduce**
1. Set a wallpaper (e.g: **Matrix Rain**)
2. Set from the Settings the "Applications Focused" to "Paused"
2. Click on the Taskbar up arrow icon
3. See the error

**Expected behavior**
- It should not pause the wallpaper playing because the focus is still the Desktop

**Screenshots/Video**
- https://imgur.com/a/SFgDaJm

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise (Version 10.0 2009  Build 19042.685)

- Thanks!

**Comment by rocksdanister** [comment]
Next update will have the fix.
