### ISSUE TITLE
更新时的弹窗问题

### ISSUE THREAD

**Issue by SalicIce** [rocksdanister/lively#2262]
这个能不能软件能不能不要在有更新的时候直接弹出窗口占着前台了，我真的好难受啊，如果弹得时候我正有重要的事情不能离开呢

**Comment by rocksdanister** [comment]
https://www.rocksdanister.com/lively/changelog/

https://github.com/rocksdanister/lively/assets/17554161/8bbbc530-d387-4970-a814-3b7432a2ffcc
