### ISSUE TITLE
Problems with pop-ups when updating

### ISSUE THREAD

**Issue by SalicIce** [rocksdanister/lively#2263]
Problems with pop-ups when updating
Can this software not pop up in the foreground when there is an update? What if I have something important to do while using the computer that I can't be disturbed?

**Comment by rocksdanister** [comment]
Updater is changed in the latest version:
https://www.rocksdanister.com/lively/changelog/

https://github.com/rocksdanister/lively/assets/17554161/8bbbc530-d387-4970-a814-3b7432a2ffcc

**Comment by SalicIce** [comment]
Thank you so much for your help. I sincerely wish you all the best in everything you do.
