### ISSUE TITLE
"No process associated with this object" error and unable to apply wallpaper.

### ISSUE THREAD

**Issue by CyanOkami39** [rocksdanister/lively#2265]
[lively_log_20240605_141545.zip](https://github.com/user-attachments/files/15581564/lively_log_20240605_141545.zip)

> 
[lively_log_20240605_141545.zip](https://github.com/user-attachments/files/15582057/lively_log_20240605_141545.zip)
**

> Processor: 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz   2.61 GHz
> RAM: 16.0 GB (15.7 GB usable)
> System Type: 64-bit operating system, x64-based processor
> Edition: Windows 11 Home Single Language
> Version: 24H2
> OS Build: 26120.751

**

![image](https://github.com/rocksdanister/lively/assets/116418775/4b329f79-6acb-4600-a5c9-e43c18363bb7)

**Comment by AkshayByte** [comment]
This "No process associated with this object" error. Have you figured out any solutions since you posted? I'm dealing with the same problem and could really use some help.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues?q=+No+process+associated+with+this+object+

This issue is common and just means the wallpaper application crashed due to any number of reasons such as faulty drivers, audio related configuration.. try some of the solutions listed.
