### ISSUE TITLE
Error No process is associated with this project

### ISSUE THREAD

**Issue by Devsathome** [rocksdanister/lively#2266]
**Describe the bug**
lively not working it is unresponsive , inbuilt wallpaper or downloaded both are not working

"Error No process is associated with this project"
Exception:
Exception

**Screenshots/Video**
![Screenshot 2024-06-05 225603](https://github.com/rocksdanister/lively/assets/114944497/30c010a0-f72f-40af-b7cf-952cecdd450a)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
- Which wallpaper was running at the time if any.

**Additional context**
Happened to me after installing latest nvidia driver version 555.99 after restarting lap it shown this message "Error No process is associated with this project"

**Log file (Important)**
[lively_log_20240605_225514.zip](https://github.com/user-attachments/files/15594434/lively_log_20240605_225514.zip)

Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues?q=+No+process+associated+with+this+object+
