### ISSUE TITLE
Unable to add an .html file by Command Line Controls

### ISSUE THREAD

**Issue by AkkoYK** [rocksdanister/lively#2267]
**Describe the bug**
Unable to add an .html file or a directory containing LivelyInfo.json as a wallpaper through Command Line Controls.

**To Reproduce**

1. Open Command Line in the Lively directory.

2. Enter the command `lively.exe setwp --file "D:\YKload\test\C7-table\index.html"`.

3. Lively launches, but the .html file is not added as a wallpaper.

**Expected behavior**
Lively should launch and add the .html wallpaper to the library and set it as the wallpaper.

**Desktop (please complete the following information):**

OS: Windows 11 Pro 23H2 (22631.3672)
Lively: v2.1.0.8

**Additional context**
I tried adding a LivelyInfo.json in D:\YKload\test\C7-table, but it still didn't work.
However, using the command `lively.exe setwp --file "D:\Live\YKloading-Master.flv"` successfully added the .flv file as a wallpaper.
I saw in the documentation that "This command will auto import wallpaper outside library only if its media file.", but I also noticed mention of adding .html wallpapers in issue #1872 .

**Log file (Important)**
[20240606_173110.txt](https://github.com/user-attachments/files/15613343/20240606_173110.txt)

**Comment by rocksdanister** [comment]
Due to security reasons only media files (video, picture..) are allowed to be imported via commandline.
If the wallpaper is already is installed in Lively then wallpaper type does not matter (the issue you linked.)

https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#set-wallpaper

> This command will auto import wallpaper outside library only if its media file.
