### ISSUE TITLE
chore: quality of "Space Man" should be improved

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [rocksdanister/lively#2276]
I currently use the "Space Man" wallpaper on my 3 monitor setup

horizontal	horizontal	vertical

on the "duplicate" setting.

but on the vertical monitor the resolution is not so great. It's very blurred.

I'm running lively wallpaper on win11 23h2

**Comment by rocksdanister** [comment]
I think you have the wrong project, there is no "Space Man" wallpaper in Lively.
