### ISSUE TITLE
Wallpaper fails when dwm crash

### ISSUE THREAD

**Issue by Ishan-Sinha-5006** [rocksdanister/lively#2283]
Bug
After applying a wallpaper the wallpaper doesn't apply. However while switching between the desktop and a different program the wallpaper applies for a second or two before disappearing.

How To Reproduce
Please note these steps may not be accurate or correct as i myself aren't sure what i did to cause it, so think as this more as a timeline of events.
1.Windows hanged after attempting closing a high memory consumption application.
2.Opened task manager using ctrl+ shift+ esc. However it didn't come up because there was lack of ram. I later confirmed this
3.Using ctrl+alt+delete to bring up security options page
4.while holding ctrl i pressed the power button to bring up the emergency restart page
5. I closed the restart page and security options page
6. Task manager finally loads
7. I end the application which caused this mess.
8. The wallpaper overlays on top of everything
9. I exit the wallpaper thinking this is a glitch
10 I restart the wallpaper and it doesn't work

Expected behavior
If you do encounter this glitch it should not apply the lively wallpaper on the desktop, will show the lively wallpaper while switching between tabs.

Video
Sorry for the bad video. I had to record it with my phone and left hand without OIS 

https://github.com/rocksdanister/lively/assets/172957227/2cdae68b-5ad6-4d7e-ac46-b589b2205988

Desktop (please complete the following information):
 - OS: Windows 11
- Which wallpaper was running at the time if any.
While I was running fluids i could see that it affected all wallpapers

Log file (Important)
[20240616_180159.txt](https://github.com/user-attachments/files/15858166/20240616_180159.txt)

**Comment by Ishan-Sinha-5006** [comment]
ps. if this either a common issue( even though i didn't find other posts about this nor was it mentioned in the common issues page) or it is specific to me please tell me how to fix this. I am thankful toward anyone who helps

**Comment by rocksdanister** [comment]
Do you have any other software that modify desktop or system? stardock fences etc.

**Comment by Ishan-Sinha-5006** [comment]
no
But i did figure out what was causing it restarting DWM causes this

**Comment by rocksdanister** [comment]
When does your dwm restart?

**Comment by Ishan-Sinha-5006** [comment]
I restart dwm manually because of a memory leak in my graphics driver. it is an integrated driver which came pre installed

**Comment by Ishan-Sinha-5006** [comment]
i cant update the driver as while a newer version of the driver from intell exists, the oem(hp) has not updated the graphics driver to the latest version.

**Comment by rocksdanister** [comment]
Usually generic Intel/Amd drivers should work without problem, atleast that's what I use.

**Comment by Ishan-Sinha-5006** [comment]
Mine is also generic

**Comment by Ishan-Sinha-5006** [comment]
To be fair this problem only started when I updated lively to the newset version.

**Comment by Ishan-Sinha-5006** [comment]
Other factors I can think of that might cause this are:
The high strain use of the device( most of the times during use it is at 7.8/8 gb ram as i use for gaming)
 The fact that the device is a laptop and thus less powerful which might be causing lively to get suspended after a dwm restart(probably not)
The regular background itself is a scrolling background that cycles through multiple images so it might be that when I restart dwm I accidentally restart it at the exact moment it changes the background to a new image so that might break it.( This is very improbable as I have restarted dwm about 20 times for testing and I getting the timing on that is well not likely to say the least)

**Comment by rocksdanister** [comment]
Wallpaper program will crash if dwm crash, that is normal.. Lively only listens for explorer crash and restart wallpaper if its not too frequent.

At the moment I don't have plans to listen to dwm process crash since that means there is something critically wrong with the system like in this case faulty driver and it is better to fix the root of the issue.

Closing this as unrelated.
