### ISSUE TITLE
Screensaver doesn't show customized version of wallpaper

### ISSUE THREAD

**Issue by ggplayer0** [rocksdanister/lively#2285]
**Describe the bug**
When setting a wallpaper as the screensaver, customization options are not respected.

**To Reproduce**
1. Choose a customizable wallpaper, and change some of its settings
2. Go to Active Wallpapers -> Screensaver
3. Set a wallpaper as the screensaver
4. Screensaver shows default, uncustomized wallpaper

**Expected behavior**
When setting a customized wallpaper as the screensaver, the screensaver should retain any customization the user made.

**Desktop:**
 - OS: Windows 10

**Additional context**
I assume that this is intended to work, but if not, then I guess that would make this a feature request.

**Comment by rocksdanister** [comment]
Wallpaper customization are respected, it is tied to the selected wallpaper screen and its layout.

For example if Screensaver layout is Span then wallpaper customization for span configuration is used, ie To customize Screensaver set the same wallpaper as Span and then customize and now you can close it.

The same is true for selected screen of the wallpaper.
