### ISSUE TITLE
Screensaver plugin not detecting

### ISSUE THREAD

**Issue by doofus46290** [rocksdanister/lively#2289]
Even after i install the lively.scr file and follow the instructions lively keeps saying that i need to do the one time set up

1. Go to "Choose Display"
2. Click on "Screensaver"
3. Click on "One time setup is required to run screensaver"
4. Install "Lively.scr" and follow all the steps
5. Open Lively back up and it still says "One time setup is required to run screensaver"

Honestly i expecting it to run the screensaver after i did the "One time" setup

**Desktop (please complete the following information):**
 - OS: Windows 11?
- Was running "The hill" because i wanted it as the screensaver

I have tried to do the setup multiple times but it still isnt working

[lively_log_20240626_002923.zip](https://github.com/user-attachments/files/15982388/lively_log_20240626_002923.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/blob/96d535313768cf11ca2037a4a3d8342c72d6afb0/src/Lively/Lively.UI.WinUI/ViewModels/ControlPanel/ScreensaverLayoutViewModel.cs#L251-L264

Its checking the Windows folder for this, make sure it is copied and Lively is restarted.
The only other reason this can fail is if the user does not have required permission to check the folder.. in that case just use different method for launching screensaver as provided in the docs:
https://github.com/rocksdanister/lively/wiki/Screen-Saver#2-command-line--shortcut
