### ISSUE TITLE
Short freeze when maximizing/minimizing app/window in front of Windows desktop

### ISSUE THREAD

**Issue by LinguaOccultus** [rocksdanister/lively#2297]
**Describe the bug**
A very simple and small issue, but a bit annoying: when an application or window is maximized (not fullscreen) and it is minimized then so that the desktop appears behind it, the animation of the Lively wallpaper is frozen for but a second as if it is paused behind the maxmized window even though the corresponding setting is diabled (only enabled for fullscreen).

Might it be the settings is ingnored/broken currently?

Asides that, the application works like a flaw and is stunningly beautiful! VERY good work! =) It can even combined with Rainmeter without any problems.

**To Reproduce**
1. Setup an animated wallpaper with Lively
2. Maximize an application/window so the desktop is behind it
3. Minimize the application/window again and watch the animation (quite obvious)

**Expected behavior**
Onbvious.

**Screenshots/Video**
Can be done if really needed, but I guess this is more likely a known issue/limitation and really simple and obvious, so I do not do one for now ...

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2
- Wallpaper: »Rain« (default settings with a different picture, no parallax and no post processing)

**Additional context**
N/A.

**Log file (Important)**
Attached: [lively_log_20240629_162343.zip](https://github.com/user-attachments/files/16040816/lively_log_20240629_162343.zip)

**Comment by rocksdanister** [comment]
The algorithm checks both fullscreen and maximize even if the setting text say fullscreen only.

Typically for games its fullscreen mode and for application is maximize but since there is no reliable way to check if game or not (and games can be maximized and apps can also enter fullscreen) both are checked.

**Comment by LinguaOccultus** [comment]
Okay, thanks for the update. If possible, why not then offer at least two options for exclusive fullscreen (which normally is used by games if not set to borderless window) and maximized window?

I mean, when it is running behind a maximized window/app in normal desktop mode, there should be no performance or compatibility issues. If someone really sets his game to borderless window, with two controls he can decide which behaviour he prefers.

I would prefer a more fluent one when only doing normal stuff on my desktop (instead of the harsh stop/play when just minimizing/maximizig a window, for example) and would like to stop it when playing a game since I normally do this for a longer period where I do not see the wallpaper. This makes economical setting and efficieny a bit more flexible.

Just a suggestion.
