### ISSUE TITLE
为什么导入本地视频作为桌面壁纸，没有声音？

### ISSUE THREAD

**Issue by qingleizhang123** [rocksdanister/lively#230]
导入本地视频后，视频本身是有音乐的，但是作为壁纸后音频输出也开启了，但是就是没有声音，是软件不支持吗，还是啥原因？

**Comment by rocksdanister** [comment]
![Screenshot 2020-12-12 080345](https://user-images.githubusercontent.com/17554161/101970465-93d21100-3c50-11eb-844e-26c4da0d0f19.png)
Make sure volume slider is not at 0.

![Screenshot 2020-12-12 080526](https://user-images.githubusercontent.com/17554161/101970527-f6c3a800-3c50-11eb-9bee-0cf23d281201.png)
"Mute" is unchecked.

If the above steps does not fix it, share the log file:
https://github.com/rocksdanister/lively/wiki/Common-Problems
