### ISSUE TITLE
Unifi Protect camera share Only one link usage 

### ISSUE THREAD

**Issue by T4LLY-0** [rocksdanister/lively#2309]
Big ask I know.
The Unifi Protect link only allows one usage. When you try to use it, the link is being used by the template (you can see the image) therefore the main wallpaper fails. Can you null or freeze the template view so the main one shows? The link updates daily, so I can't just link here.

![image](https://github.com/rocksdanister/lively/assets/8620856/6d9877fb-ca19-4d70-a8e5-3f8fe5565ba6)
Showing in the template 
![image](https://github.com/rocksdanister/lively/assets/8620856/5e06a3fd-123a-4e9d-bba2-d71e02163c30)

![image](https://github.com/rocksdanister/lively/assets/8620856/cbafe555-d6eb-4ea7-bac2-dc14aee86d52)
The main wallpaper view

**Comment by rocksdanister** [comment]
The template is not a separate instance, its the wallpaper window resized and attached to Lively.

The error could be related to something else.
