### ISSUE TITLE
Не работает приложение (Требуется сделать единоразовую установку *плагин*)

### ISSUE THREAD

**Issue by EslessGvard** [rocksdanister/lively#2310]
![image](https://github.com/rocksdanister/lively/assets/175254284/ab5c9639-2217-4fd8-91ad-f4c717bead8c)
1. Выполнил все инструкции которые были указаны тут:
https://github.com/rocksdanister/lively/wiki/Screen-Saver
2. Далее выходила эта же ошибка.
3. Антивирусников у меня нету. Защита Win 10 - отключена. 
4. Перезапускал приложение (так же переустанавливал) 
5. Перезапускал ноутбук. Всё равн оне помогло

**Comment by rocksdanister** [comment]
moved here: https://github.com/rocksdanister/lively/issues/2311
