### ISSUE TITLE
Unable to use screensaver option

### ISSUE THREAD

**Issue by gimbobob** [rocksdanister/lively#2311]
**Describe the bug**
Tried installer version and store version and yet the screensaver option never works, always still says plugin required despite everything I tried- I followed all the steps. Copied 2.1 version of the screensaver scr file to C:\Windows and then pressed Install, selected it and pressed apply in windows screensaver settings yet it still says plugin required in lively. 

**Expected behavior**
The pop up to go away after I download the screen saver

**Screenshots/Video**
![Screenshot 2024-07-11 232124](https://github.com/user-attachments/assets/1e042757-3028-4f33-988d-72461d8cd00f)

**Desktop**
 - OS: Windows 10

**Comment by rocksdanister** [comment]
1. Attach the application logfile:
https://github.com/rocksdanister/lively/wiki/Common-Problems#having-a-problem-how-do-i-get-help--how-to-retrieve-log-files
2. Run this program and share the screenshot:
https://github.com/rocksdanister/lively-beta/releases/download/v2.1.0.7/lively_screensaver_checker.zip
