### ISSUE TITLE
WallpaperPluginIssue. The system cannot find the file specified.

### ISSUE THREAD

**Issue by Karthikcho83** [rocksdanister/lively#2317]
Describe the bug
When I attempt to set a wallpaper from the application, I receive an error message indicating that a file is missing from the specified path.

To Reproduce
1. Open the application and click on any wallpaper; regardless of which you choose, the same error is displayed.

Expected behavior
1. Wallpaper sets when we click without any errors.

Screenshots/Video
![Lively](https://github.com/user-attachments/assets/aa7d9269-e7ea-4569-932f-6618945af216)

Desktop (please complete the following information):
 - OS: Windows 10 Pro, 22H2, 19045.4651, Windows Feature Experience Pack 1000.19060.1000.0
- As I couldn't set the wallpaper from the application I've set a normal photo as a wallpaper at that moment.

Additional context
1. I've checked out the existing issues and found out that 'cef' is causing the issue and I was prompted to download webview2 from the same.
2. Even though this process is a failure I couldn't set any wallpaper from the application.
3. I've installed this application from the installer on your website.
4. when I attempt to just preview the wallpaper, it didn't work as expected.
5. GPU Decode is disabled; GPU is GTX 1060, driver version 466.18

Log file (Important)
Share the diagnostic files by:
[lively_log_20240720_133346.zip](https://github.com/user-attachments/files/16319406/lively_log_20240720_133346.zip)

**Comment by rocksdanister** [comment]
This is common issue.
Lively is divided into separate programs, the bowser program got deleted by something (typically an anti-virus program.), I only test with default programs.. you can report it to av for false positive directly:
https://www.autohotkey.com/boards/viewtopic.php?t=62266
