### ISSUE TITLE
使用核显播放时占用过高（Use highlight playback takes up too much time）

### ISSUE THREAD

**Issue by Nlu5E5Bl** [rocksdanister/lively#2320]
我用核显输出壁纸，165hz的显示器，核显占用80%，建议加一个帧率限制，强制背景以低刷新率运行。（英文由机器翻译生成）
I use nuclear display output wallpaper, 165hz monitor, nuclear display occupies 80%, it is recommended to add a frame rate limit, forcing the background to run at a low refresh rate. （English generated by machine translation）

**Comment by rocksdanister** [comment]
Task Manager reading is unreliable:
https://github.com/rocksdanister/lively/wiki/Performance

Webpages wallpapers that I make usually comes with its own frame limit code.
For video player there are methods to frame limit but you will have to experiment with custom configuration:
https://github.com/rocksdanister/lively/wiki/Video-Guide#mpv
https://mpv.io/manual/master/
