### ISSUE TITLE
The value cannot be an empty string. (Parameter 'path')

### ISSUE THREAD

**Issue by kotdoit** [rocksdanister/lively#2323]
![1](https://github.com/user-attachments/assets/e9189980-50f9-4006-b34f-7cc18c6631dc)
**Describe the bug**
1. I created a wallpaper using a link from YouTube.
2. When I click on the "Configure" button, an error pops up - The value cannot be an empty string. (Parameter 'path').

**To Reproduce**
1. Clicked "Add Wallpaper".
2. Entered the URL of the video.
3. Clicked on the arrow.
4. I wrote the name of the video and clicked OK.
5. Clicked three dots -> Configure.
6. An error appeared - The value cannot be an empty string. (Parameter 'path')

**Expected behavior**
I expected to see the setup interface and mute the video.

**Screenshots/Video**
https://github.com/user-attachments/assets/1a03e4f0-a6ce-4bae-962f-c71548c2d98b
![1](https://github.com/user-attachments/assets/3fa3e12d-e896-4a5e-b394-7f550e8ccfe9)

**Desktop (please complete the following information):**
 - OS: 
Выпуск Windows 11 Pro
Версия 23H2
Сборка ОС 22631.3880
Взаимодействие Windows Feature Experience Pack 1000.22700.1020.0
- The video wallpaper was launched via a link from YouTube.

**Additional context**
null

**Log file (Important)**
[20240722_164859.txt](https://github.com/user-attachments/files/16334516/20240722_164859.txt)

**Comment by rocksdanister** [comment]
It is using the browser to play the embed link, default Configure is not possible in this setup as it is for video files. 
If you want you can download the video using third party services and add the video file as wallpaper directly to get Configure.

**Comment by kotdoit** [comment]
I understand, then make a condition that this setting point in the program is inactive when adding videos via links from YouTube.

**Comment by rocksdanister** [comment]
That is not done because it is possible still possible to Configure with third party tools:
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper
