### ISSUE TITLE
Can't setup live streaming from Youtube as wallpaper

### ISSUE THREAD

**Issue by anhell** [rocksdanister/lively#2324]
Hello, I'm following the instructions from here https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper and I'm unable to make it work. 

I got the yt-dlp file, the one with 2.82 MB and no extension type, renamed it to youtube-dl and moved it to C:\Program Files\Lively Wallpaper\Plugins\Mpv, re-opened the program and the Lively Settings -> Wallpaper > Stream option is not showing for me. I can add normal videos, but not live streaming ones.

I have the latest version of Lively and I'm using the latest version of Windows 10

**Comment by rocksdanister** [comment]
> I got the yt-dlp file, the one with 2.82 MB and no extension type

Its yt-dlp.exe file that is needed, renamed to youtube-dl.exe (if you have Windows show file extension enabled.)

**Comment by anhell** [comment]
Perfect, thank you.
