### ISSUE TITLE
Wallpaper does not show when switching desktops

### ISSUE THREAD

**Issue by IanDaBest** [rocksdanister/lively#2329]
**Describe the bug**
When you switch desktops, the wallpaper does not show until the desktop is fully switched. Before that, it will show the default background image.

**To Reproduce**
1. Use the trackpad to swipe halfway to the next desktop
2. See error

**Expected behavior**
The live wallpaper is already there before the desktop is fully switched
**Screenshots/Video**
![image](https://github.com/user-attachments/assets/9f2de337-08cf-48cc-ba29-f5d356938c1d)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2
- Happens for all wallpapers

**Additional context**
None

**Log file (Important)**
[lively_log_20240726_165255.zip](https://github.com/user-attachments/files/16387607/lively_log_20240726_165255.zip)

**Comment by rocksdanister** [comment]
Windows limitation, a workaround would be to turn on desktop picture so that a still picture of the live wallpaper is also set as desktop wallpaper.

**Comment by IanDaBest** [comment]
I already have desktop picture turned on, however it is not doing anything. Are there any further steps required?

**Comment by rocksdanister** [comment]
Looks like its because each virtual desktop has different background, so you will have to set it for all manually
![image](https://github.com/user-attachments/assets/8b9e45ea-72ca-4570-b23d-1b5b56dc9af2)

This should get resolved once virtual desktop related features are implemented in future update.
