### ISSUE TITLE
Error: No prosses is associated with this object

### ISSUE THREAD

**Issue by SagiTheBoyyy** [rocksdanister/lively#2337]
**To Reproduce**
1. Go to 'Library'
2. Click on any walpaper
3. See error

**Expected behavior**
A error shows up that says:
'Error: No prosses is associated with this object
Exception: 
Excepton'

**Screenshot**
![Screenshot 2024-08-01 201525](https://github.com/user-attachments/assets/3f65610a-7599-4d5f-bed2-7b3793d936f2)

**Desktop**
 - OS: windows 11
- no wallpaper

**Additional context**
I just saw that the wallpaper I set wasnt there so I clicked on it to set it as the wallpaper and is showed me this error

**Log file**
[lively_log_20240801_201035.zip](https://github.com/user-attachments/files/16459868/lively_log_20240801_201035.zip)

**Comment by ayaangrover** [comment]
I get this too. Any fix found?

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2040
