### ISSUE TITLE
Problem after installing iTop Easy Desktop

### ISSUE THREAD

**Issue by shivaorion** [rocksdanister/lively#2338]
**Describe the bug**
After installing iTop Easy Desktop, Lively Wallpaper restarts chosen wallpaper in a loop, even after I closed iTop Easy Desktop. If close Lively Wallpaper with iTop Easy Desktop closed, it works normally again, but if iTop Easy Desktop is started, the bug comes back. Also, the Lively Wallpaper right-click tray-icon menu kept closing with each restart, making it harder to close it.

**To Reproduce**
1. Install Lively Wallpaper
2. Install iTop Easy Desktop

**Expected behavior**
Work normally with iTop Easy Desktop installed.

**Screenshots/Video**
![image](https://github.com/user-attachments/assets/fc96165e-cced-4ab8-bd0f-191b20e686c4)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 24H2
- Which wallpaper was running at the time if any: Fluids, then Living Room.  

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
[lively_log_20240802_083743.zip](https://github.com/user-attachments/files/16470023/lively_log_20240802_083743.zip)

**Comment by rocksdanister** [comment]
Looks like the software is using stolen opensource software code:
https://github.com/TranslucentTB/TranslucentTB/issues/1064#issuecomment-2339677374

I will not be supporting this.
