### ISSUE TITLE
Wallpapers are empty

### ISSUE THREAD

**Issue by shivaorion** [rocksdanister/lively#2345]
![Captura de tela 2024-08-06 105716](https://github.com/user-attachments/assets/a47094f1-57d7-404a-a7ba-454af3e64259)

**Describe the bug**
The wallpapers don't show um Lively Wallpaper window.

**To Reproduce**
1. Open Lively Wallpaper
2. See error

**Expected behavior**
The wallpaper option show normally.

**Screenshots/Video**
![image](https://github.com/user-attachments/assets/609cc1c1-6b22-4f25-955c-54554a3b3d25)

**Desktop:**
 - OS: Window 11 Professional 23H2
- No wallpaper was running.

**Log file (Important)**
[lively_log_20240806_105642.zip](https://github.com/user-attachments/files/16511375/lively_log_20240806_105642.zip)

**Comment by rocksdanister** [comment]
Something must have went wrong during initial setup.

You can find the default wallpapers inside `<Install_Location>/Bundle` folder.
Extract all the .zip folders into the `../Library/wallpapers` folder.
 https://github.com/rocksdanister/lively/wiki/Getting-Started#storage
 
and restart the app.

Closing this issue for now, will keep a lookout if it becomes frequent.
