### ISSUE TITLE
壁纸无法一直固定在桌面上

### ISSUE THREAD

**Issue by men9z** [rocksdanister/lively#235]
当我设置完壁纸之后，壁纸可以正常显示，但鼠标点击桌面，壁纸会变成黑色，正在使用的壁纸是Rain v2，所有的壁纸都是如此。
OS：Windows10  19042.630 20H2

video：
[20201214_081459.zip](https://github.com/rocksdanister/lively/files/5685872/20201214_081459.zip)

logs：
[20201214_071626.txt](https://github.com/rocksdanister/lively/files/5685875/20201214_071626.txt)
[20201214_074305.txt](https://github.com/rocksdanister/lively/files/5685876/20201214_074305.txt)

**Comment by rocksdanister** [comment]
You have some third party fullscreen application/overlay that is sitting on the desktop and stealing focus, Lively thinks some fullscreen application is focused when you click and pauses the wallpaper to reduce system resource usage.

There are two solutions:
1. Add process exception to it after you identify the program is causing the issue.
![Screenshot 2020-12-14 092824](https://user-images.githubusercontent.com/17554161/102039023-bc900d00-3dee-11eb-9423-d62d99df5010.png)
2. If (1) not possible, then Turn off wallpaper pause all together.
![Screenshot 2020-12-14 092946](https://user-images.githubusercontent.com/17554161/102039105-ed704200-3dee-11eb-9f92-16b1695f4f0e.png)
