### ISSUE TITLE
Problem with changing subtitles in the video or turning them off.

### ISSUE THREAD

**Issue by pawosik** [rocksdanister/lively#2353]
I have a regular mp4 file that does not contain any subtitles. When I upload a wallpaper, I cannot change or disable the subtitles, in the wallpaper preview I can change the subtitles and turn them off, but in fact I cannot turn them off in the active wallpaper that is displayed on the desktop.
![image](https://github.com/user-attachments/assets/26c09a06-986a-4715-b2cf-1b24f218ab18)
![image](https://github.com/user-attachments/assets/2b6229bb-534d-451c-9c72-d0613544b20f)
![image](https://github.com/user-attachments/assets/ab065d4c-6993-494a-95c0-18fa3ef30c06)

**Comment by rocksdanister** [comment]
Create `mpv.conf` file:
```
--sid=no
```
and place it in the relevant location:
https://github.com/rocksdanister/lively/wiki/Video-Guide#mpv
https://mpv.io/manual/master/#options-sid
