### ISSUE TITLE
GPU usage > 30% and no difference with/without GPU rendering!?

### ISSUE THREAD

**Issue by LinguaOccultus** [rocksdanister/lively#2363]
**Describe the bug**
First of all: yes, I have seen the wiki page about performance and the other post and tried around a bit. This case, however, is different and I cannot solve it myseld so far, so I hove it a try.

Lately, after using Lively Wallpaper for some weeks now without issues, I became aware that it uses my GPU by 30-40%! That first seems to be a VERY big GPU usage even though mine is not the fastest (NVidia GTX 1660 Super, 6 GB, PCIe 3.0) which can handle even the more demanding modern games at full details.

Further, switching GPU rendering on or off does NOT change a thing. I would expect GPU usage to get lower and maybe CPU usage to rise when disabled, but it still stays the same.

Next, I tried the suggested update from one of the other threads and updates MPV to the latest x64-v3 version, but that also did not change anything.

The main processes of Lively Wallpaper do not use much ressources; the main process which causes the above seems to be always ONE out of five »CefSharp.BrowserSubprocess« processes I could only identify as one of Lively Wallpaper because they dissappear when it is closed (or maybe it is a system process used by it; 25-30% GPU usage). The second one is the Desktop Window Manager which uses the GPU at around 5-10%.

All of that is immediately stopped when stopping the application. Changing settings also does not change anything.

In general, this is not a problem; but the GPU usage is much greater as with much more intense and demanding tasks the GPU handles easily and with less usage. Also, this is not a good value regarding energy efficiency.

Currently, I am using the Rain effect whith a custom background image and most of the additional settings like post processing disabled.

Any idea if this is normal or how to reduce this?

**To Reproduce**
(I guess, this special behaviour can only be reproduced on my system, maybe. But I can do tests and bring in more information if needed.)

**Expected behavior**
Obvious (see above).

**Screenshots/Video**
N/A (Can be made depending on what you want to see).

**Desktop (please complete the following information):**
- OS: Windows 11 Pro 23H2
- »Rain«

**Additional context**
None for now.

**Log file (Important)**
Share the diagnostic files by:
Attached.
[lively_log_20240816_224629.zip](https://github.com/user-attachments/files/16641580/lively_log_20240816_224629.zip)

**Comment by rocksdanister** [comment]
> switching GPU rendering on or off does NOT change a thing.

GPU Decoding setting is under Video Player which Rain is not (its dynamic webpage and not video.)

Webpage wallpapers sometime come with its own performance setting, for example there is a `Scaling` setting in Rain to reduce render resolution.

Rest is as explained in the wiki, please stop creating new issues:
https://github.com/rocksdanister/lively/wiki/Performance
