### ISSUE TITLE
Error using customize button for wallpapers linked to URL's

### ISSUE THREAD

**Issue by Fizzybubbler24** [rocksdanister/lively#2364]
**Describe the bug**
An Error message stating "The value cannot be an empty string. (Parameter 'path') appears when you try to customize any wallpaper added via a URL.

**To Reproduce**
1. Click the settings dots on wallpaper
2. Click on Customize
3. See Error

**Expected behavior**
I expected the customize options menu to appear instead of the error message

**Screenshots/Video**
![image_2024-08-17_163856572](https://github.com/user-attachments/assets/cfeaabef-67dd-4fc7-91a7-031cf40a3e7e)
[lively_log_20240817_162743.zip](https://github.com/user-attachments/files/16646449/lively_log_20240817_162743.zip)

**Desktop (please complete the following information):**
 - Windows 11
- https://www.youtube.com/watch?v=L3Dp4oGkn3k

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Customization is not possible for website urls.

**Comment by Fizzybubbler24** [comment]
It was before, why is it not now?

**Comment by Fizzybubbler24** [comment]
Specifically, I was formorally able to mute the URL video's so the music
wasn't playing on my desktop. Now I am unable to because of this error
message. Closing my ticket and then stating something false is
unacceptable. The error message indicates an error in your code, you
fucking nitwit.

**Comment by rocksdanister** [comment]
> Specifically, I was formorally able to mute the URL video's so the music
wasn't playing on my desktop. Now I am unable to because of this error
message. Closing my ticket and then stating something false is
unacceptable. The error message indicates an error in your code, you
fucking nitwit.

This is not acceptable.
