### ISSUE TITLE
Microsoft Store warning - "Your PC doesn't meet the minimum required memory."

### ISSUE THREAD

**Issue by Ironfist69** [rocksdanister/lively#2366]
**Describe the bug**

**To Reproduce**
1. Go to Microsoft Store, search for Lively Wallpaper
2. Click on the app
3. Scroll down to System Requirements
4. See error Memory 4GB Min, 8GB recommended

**Expected behavior**
Should detect exact amount of memory installed on the System

**Screenshots/Video**
![Screenshot 2024-08-18 104933](https://github.com/user-attachments/assets/a6872241-fe09-4653-9fba-88b8b6383c32)
![Screenshot 2024-08-18 104523](https://github.com/user-attachments/assets/b69a4ba1-1e87-44cf-bc9b-112f2ff58371)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2

**Comment by rocksdanister** [comment]
Looks like an issue with Microsoft Store, file a report on Feedback Hub.
