### ISSUE TITLE
[MS Store] Automatically restart application after update.

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#237]
**Is your feature request related to a problem? Please describe.**
For Microsoft store version of Lively application is terminated before update installation.
Automatically restart after software update, users might think its a crash otherwise.

**References**
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#updates

https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/b42729be5cc527b5041c2d54581367cafa5dce90/ModernFlyouts/FlyoutHandler.cs#L269

**Comment by ShankarBUS** [comment]
@rocksdanister,

I'm the developer of ModernFlyouts.

Unfortunately, the method you mentioned didn't work for us. I don't know if it was due to Mutex still being held or any other issue on our side. But it didn't work in our case.

Could you please let me know if it works or not for your app?

**Comment by rocksdanister** [comment]
I recognize you from the modernwpf project 😄
I'll let you know if it works; on a related note how do you test internal store builds? do you have a separate private listing of the app?

**Comment by ShankarBUS** [comment]
@rocksdanister,

> on a related note how do you test internal store builds? do you have a separate private listing of the app?

Oh my god! I completely forgot the internal channel exists.

I'll ping in my partner who knows about MS Store even more, @Samuel12321.

IIRC, you would need to add your MS account to the internal ring and Store would give you the internal builds that you publish into.

**Comment by Samuel12321** [comment]
hi @rocksdanister,
I did consider using a separate private listing, but ended up using package flights. 
We currently have 3 package flights. The internal beta flight, which i use to test updates, the beta ring which anyone can sign up for and the release ring. 

i have currently deactivated the internal ring, and with the new addition of azure pipelines am looking into new and better ways of managing updates.

**Comment by rocksdanister** [comment]
How did you get the signed Msix file from microsoft ? did you sign it with your own key instead ?

I found this article, he registered it at the start of the application and there was a tool for testing this:
https://www.codeproject.com/Articles/772868/Restart-Manager-Support-For-Windows-Application

**Comment by Samuel12321** [comment]
it is uploaded to partner centre with my developer key. The store signs it and releases it, then i use this tool [Here](https://store.rg-adguard.net/) to download the Microsoft Store signed .MSIX from the store.

**Comment by rocksdanister** [comment]
Thanks, appreciate it; this should help me release Lively on winget.

**Comment by rocksdanister** [comment]
@ShankarBUS @Samuel12321 I just tested a internal build in package flight and Lively restarted fine after update install.

**Comment by ShankarBUS** [comment]
Hmmm. Then our problem must be with mutexes. Could you show me the source code?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/blob/13006943b39412bfab14a570e520fa7c29edf6b6/src/livelywpf/livelywpf/Program.cs#L34-L53
Its probably because I'm skipping that exception, I added that wayback.. don't remember the exact reason.

**Comment by ShankarBUS** [comment]
This could be solved if we released the mutex on the `WM_ENDSESSION` message receival.

**Comment by ShankarBUS** [comment]
And @rocksdanister, why not use named pipes instead of window messages for IPC? Named pipes will be much more targeted and a large amount of information could be transferred between instances.

You could take a look at my helper https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/37bb061f8dfb486c4d8f76b1ec483e1e8d8e173d/ModernFlyouts/AppLifecycle/AppLifecycleManager.cs#L32

This would be unnecessary once ProjectRenuion's AppLifecycle API's are public.

**Comment by rocksdanister** [comment]
>This could be solved if we released the mutex on the WM_ENDSESSION message receival.

Correct me if I'm wrong, but even when that exception is thrown the mutex is still acquired .. so isn't it better to just to log the error and continue running the app (I'm talking about a general scenario like when the user ends the program in taskmanager or appcrash.)

>why not use named pipes instead of window messages for IPC? Named pipes will be much more targeted and a large amount of information could be transferred between instances.

True its pretty ugly since its broadcasting that msg, but namedpipe is no longer recommended since its not cross-platform? I was thinking of redoing that part when complete rewrite for Lively 2.0 is done using something like gRPC or something to separate the core and UI..

**Comment by ShankarBUS** [comment]
Oh ok good 😄.
