### ISSUE TITLE
my screensaver is just black

### ISSUE THREAD

**Issue by TCod3player0987** [rocksdanister/lively#2375]
Im new to lively and dont seem to see anyone else with this issue, when i originally set it up it worked with the install button but now it just completely is black and my screensaver is selected.

**Comment by rocksdanister** [comment]
Fill the log report file:

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
