### ISSUE TITLE
the youtube video wont play

### ISSUE THREAD

**Issue by SnipreSpray** [rocksdanister/lively#238]
i have a proble whit when i copy the link and past it to where you add a new wallpaper it wont play, i just get a grey screen
![Screenshot (19)](https://user-images.githubusercontent.com/76041716/102200740-e704c780-3ecd-11eb-8f04-54f49402d3f0.png)
![Screenshot (21)](https://user-images.githubusercontent.com/76041716/102200811-fc79f180-3ecd-11eb-8480-25e37003b083.png)

**Comment by rocksdanister** [comment]
Troubleshooting:
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper

Share the logfile next time:
https://github.com/rocksdanister/lively/wiki/Common-Problems

**Comment by rocksdanister** [comment]
This might be a proxy related issue? if so you will have to look at the official mpv player [discussions.](https://github.com/mpv-player/mpv/issues?q=is%3Aissue+proxy+is%3Aclosed)
