### ISSUE TITLE
Lively wallpaper not detecting I've installed the screensaver plugin

### ISSUE THREAD

**Issue by WrittenSkate** [rocksdanister/lively#2385]
**Describe the bug**
I want to use lively screensaver, but after installing the scr file, and restarting lively, it doesn't detect that I've already installed it.

**To Reproduce**
1. Open lively
2. open the active wallpapers screen
3. go to the screensaver tab
4. click the one time setup is required button
5. download the zip containing the scr
6. install it
7. restart lively

**Expected behavior**
Lively doesn't detect the screensaver I installed even after restarting the app.

**Screenshots/Video**
![Screenshot 2024-09-09 145305](https://github.com/user-attachments/assets/2e6f13ab-64ec-45c1-9387-07874dcd5c51)

**Desktop (please complete the following information):**
 - OS: Windows 11 23h2
- No active lively wallpapers

**Log file (Important)**

[20240909_143620.txt](https://github.com/user-attachments/files/16935229/20240909_143620.txt)

**Comment by rocksdanister** [comment]
Did you copy it to copy the .scr file to `C:\Windows\` before installing?

https://github.com/rocksdanister/lively/wiki/Screen-Saver

**Comment by WrittenSkate** [comment]
Oh I'm dumb I somehow completely missed that part of the guide now it works

**Comment by Martino-Pirone** [comment]
even copying it to windows/c and installing it after copying then lively wallpaper does not read the plug in

**Comment by rocksdanister** [comment]
The message can be dismissed in the next update.
