### ISSUE TITLE
Pause algorithm incompatibility with iTop Easy Desktop

### ISSUE THREAD

**Issue by Gr1ffC0d3** [rocksdanister/lively#2406]
**Describe the bug**
Lively Wallpaper recognizes a desktop organization app in it's foreground process algorithm and pauses wallpapers while the organization app is active.

**To Reproduce**
1. Download iTop Easy Desktop
2. Download Lively Wallpaper
3. Setup both apps
4. Set Lively to pause wallpapers when a window is in focus using the foreground process method
5. Turn on an interactive live wallpaper from Lively
6. Turn on boxes for iTop
7. Open the desktop

**Expected behavior**
I should get to use iTop's functionality as well as Lively's

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro 23H2]
- I tested this with both the Fluids and Periodic Table wallpapers.

**Additional context**
One way to solve this could possibly be to add an option to ignore certain apps when determining whether to pause the wallpaper.

[lively_log_20240928_200603.zip](https://github.com/user-attachments/files/17173678/lively_log_20240928_200603.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2338
