### ISSUE TITLE
Background app is minimizing on Win+D shortcut

### ISSUE THREAD

**Issue by Sunshine6low** [rocksdanister/lively#2408]
Hi!
I created an electron app to show it on my desktop background (showing only html is not my case, i need to use native features from node), but window is minimizing when I press Win+D. On Win+M it works normally, but Win+D minimizing to my native desktop background.

Tell me please, does it have workaround or i need to deal with this in my app?

**Comment by Sunshine6low** [comment]
Windows 22H2
[lively_log_20240928_171149.zip](https://github.com/user-attachments/files/17174680/lively_log_20240928_171149.zip)

**Comment by rocksdanister** [comment]
Apps have manage their own input hooks, I don't have control.
You will have to manage it on the app side.

**Comment by Sunshine6low** [comment]
Ok, thank you for the answer!
