### ISSUE TITLE
Keyboard input question/不能选择使用键盘与壁纸交互

### ISSUE THREAD

**Issue by caiweihan** [rocksdanister/lively#242]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki 
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
无法在设置中选择使用键盘与壁纸交互

**To Reproduce**
![image](https://user-images.githubusercontent.com/29276271/102630204-375a7e80-4187-11eb-8328-a87900921c4f.png)
选择用键盘与壁纸交互的选项是灰色的，无法选择

**Expected behavior**
我是从这篇文章中知道这个软件的 https://sspai.com/post/64008 。里面提到可以用键盘与壁纸交互，但没说具体方法
![image](https://user-images.githubusercontent.com/29276271/102630495-928c7100-4187-11eb-94a9-a5f48b2eb978.png)
底下也有评论说无法用键盘
![image](https://user-images.githubusercontent.com/29276271/102630525-9f10c980-4187-11eb-89f7-04ba75677202.png)

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: windows10 20H1
- Which wallpaper was running at the time if any.

**Additional context**

**Log file**
Share the log file(s) from Local Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
The article is wrong, keyboard function is not implemented https://github.com/rocksdanister/lively/issues/35
If options are greyed out, it means either the version of Lively does not have that feature (Example: Windows store version) or its not ready yet; in this case it is not ready yet.
