### ISSUE TITLE
Lively Uses Almost 70% Of My GPU's 3D Compute While Running

### ISSUE THREAD

**Issue by MaskRoblox** [rocksdanister/lively#2423]
![computer](https://github.com/user-attachments/assets/85e89910-62a2-4d0f-a46b-a52831c8c2ad)

**Describe the bug**
Lively uses almost 70% of my GPU's 3D compute when using the rain wallpaper.

**To Reproduce**
Choose the rain wallpaper? 

**Expected behavior**
Rain wallpaper shows fine but when opening task manager it causes my 3d compute to launch up.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserNa
[lively_log_20241007_170418.zip](https://github.com/user-attachments/files/17281452/lively_log_20241007_170418.zip)
me>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance#understanding-task-manager-readings
