### ISSUE TITLE
Mpv player's window is visible with dual monitor setting

### ISSUE THREAD

**Issue by mikinis111** [rocksdanister/lively#2429]
**Describe the bug**
The window of mpv player is visible on external monitor, as shown on the screenshot.

**To Reproduce**
I couldn't really reproduce it, it happened just once, but that's what I did before:
1. Started the laptop without additional monitor plugged and opened Lively
2. Put the laptop in sleep mode and waited for it to hibernate 
3. Plugged in an additional monitor
4. Turned the laptop on

**Expected behavior**
Just a regular live wallpaper duplicated on both monitors.

**Screenshots/Video**
![obraz](https://github.com/user-attachments/assets/2c43c46b-7cd6-47c8-9c3c-643084e45e8f)

**Desktop (please complete the following information):**
- OS: Windows 11 Pro 10.0.22631
- Wallpaper: My own mp4 wallpaper (Not my art, it was made by someone else)

**Additional context**
The issue is visible only on the laptop built-in monitor. The second monitor plays the wallpaper flawlessly. I understand this is not likely an important issue, especially because I'm not sure on how to reproduce it, but if you have any spare time and idea on what might have caused it, feel free to ask questions and answer. 

**Log file**
[lively_log_20241012_101756.zip](https://github.com/user-attachments/files/17349393/lively_log_20241012_101756.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2108#issuecomment-2146805795
Possibly dup: https://github.com/rocksdanister/lively/issues/2074#issuecomment-2146541025

Try the workaround.

**Comment by mikinis111** [comment]
> dup: [#2108 (comment)](https://github.com/rocksdanister/lively/issues/2108#issuecomment-2146805795) Possibly dup: [#2074 (comment)](https://github.com/rocksdanister/lively/issues/2074#issuecomment-2146541025)
> 
> Try the workaround.

Yeah that's the same issue, thanks. Sorry for making a duplicate.
