### ISSUE TITLE
"This browser or App may not be secure"

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#2436]
# Log

[lively_log_20241018_055902.zip](https://github.com/user-attachments/files/17427819/lively_log_20241018_055902.zip)

### Image

![meZQpmS1B2](https://github.com/user-attachments/assets/3f7a63bf-6311-4298-9812-b7380b6f06ad)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#can-i-login-to-websites
