### ISSUE TITLE
Mouse scroll issues

### ISSUE THREAD

**Issue by Portugalidade** [rocksdanister/lively#2439]
**Bug**
I have a custom wallpaper that I've been using for some time. It includes a parent div and a child div. The child div moves up and down within the parent div using the mouse wheel. This feature was working fine until recently, but it suddenly stopped. It works in all browsers (Chrome, Edge, Firefox), but in Lively, it just stopped working.

**OS**
 - OS: Windows 10 Pro 10.0.19045 and Windows 11 (all versions)

[20241022_131242.txt](https://github.com/user-attachments/files/17479915/20241022_131242.txt)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/853
