### ISSUE TITLE
Continute pausing wallpaper even if taskbar is clicked

### ISSUE THREAD

**Issue by UncodedHuman** [rocksdanister/lively#2440]
We all want to enjoy the lively wallpaper but we would like to try to pause it to save battery. I'm using the settings to pause the wallpaper while the application is focused. however, the wallpaper starts running whenever I click the taskbar to modify anything. It's slightly annoying since it slows down the PC and runs the wallpaper despite me having the applications opened and displayed.

I would love to somehow have a feature or a fix to continue pausing the wallpaper even when the taskbar is clicked (making the application no longer 'in focused'). Alternatively, an option to pause wallpaper when ANY application is opened and displayed. Or maybe a setting to run the wallpaper only on clicked (not on the taskbar). 

This would personally be a huge quality-of-life update for me. Since I love this project except that it drains too much of my battery.

**Comment by rocksdanister** [comment]
This is done because sometimes taskbar is in focus even though when on desktop, otherwise wallpaper will stay paused until user clicks on desktop.
