### ISSUE TITLE
Backgrounds will not load

### ISSUE THREAD

**Issue by CrashBurnsley** [rocksdanister/lively#2444]
All of a sudden without incident when I click on a background it does nothing nothing's changed it was working an hour ago now it's not working at all I'm going to try to uninstall and then reinstall see what happens but here's your bug report
[lively_log_20241027_114958.zip](https://github.com/user-attachments/files/17534900/lively_log_20241027_114958.zip)

**Comment by iman-mohamadi** [comment]
i have the same problem with it

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/discussions/2464
