### ISSUE TITLE
Wallpaper pause app exclusion / Seelen UI compatibility

### ISSUE THREAD

**Issue by Vehlore** [rocksdanister/lively#2445]
**Is your feature request related to a problem? Please describe.**

Some apps that are not full screen are detected by Lively as so, causing the wallpaper to pause. In my specific case this happens with Seelen UI.

**Describe the solution you'd like**

Having a section to exclude specific apps from pausing the wallpaper even when on full screen.

**Additional context**

https://private-user-images.githubusercontent.com/70699825/380632186-d60ddd4d-8191-4291-9258-3991f2701ba2.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTEwODUsIm5iZiI6MTczMDE5MDc4NSwicGF0aCI6Ii83MDY5OTgyNS8zODA2MzIxODYtZDYwZGRkNGQtODE5MS00MjkxLTkyNTgtMzk5MWYyNzAxYmEyLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNmY5MjQ5NjJlZjBmMDk2NzViMGU2ZGI1NDg4NjIxOGNmOTcwZGY1ZTU3NTI0YTQ2MTQ3MmM3ZDE4MThmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oJzo6JL-YTbW-d7kgT1bvkAbe7HobBOfLGx0T66zVZE

**Comment by rocksdanister** [comment]
Applications can be excluded manually: https://github.com/rocksdanister/lively/issues/789#issuecomment-1148548562

I also have a list of white listed classes for certain programs like Rainmeter but not sure if it help with something extensive like Seelen.. I don't have time to test and maintain it myself.
