### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by buglocker** [rocksdanister/lively#2446]
Hey.
I cant uninstall the app.
Windows , wise and geek uninstallers coudnt uninstall it ?
Any suggestions ?

I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
1. Issue may be deleted if it is not following the template
2. Only post one issue per one bug report
3. Try not to make duplicates issues, do a quick search before posting
4. Add a title that describes the issue clearly
5. Check the wiki to see if the question is already answered:
https://github.com/rocksdanister/lively/wiki/Common-Problems
--->

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
moved: https://github.com/rocksdanister/lively/discussions/251
