### ISSUE TITLE
bug with lively wallpaper my screen open a window with old window of windows apps

### ISSUE THREAD

**Issue by LiforxPro** [rocksdanister/lively#2447]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20241029_210947.zip](https://github.com/user-attachments/files/17564326/lively_log_20241029_210947.zip)

**Comment by Shiv-yaps** [comment]
well this is something new, can you explain more breifly

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415
