### ISSUE TITLE
Malfunction: Desktop video plays only under specific circumstances

### ISSUE THREAD

**Issue by DaividBowie** [rocksdanister/lively#2450]
When i click on my desktop it won't start playing the video or whatever i set as wallpaper. 
I tried every single config and nothing, either i let it playing non stop or it won't play at all, it will play just if i click on the taskbar. 
When i let it play non stop, when i switch to my desktop the video plays, but the sound won't play.
It will only play, sound and video/gif/parallax, when i click on the taskbar. 
Everytime i want to see my wallpaper working i must click on taskbar, if i click over any app an then directly on the desktop, it won't work.

The system just starts the like that, i tried to uninstall and nothing happened. It was working just fine, but i went back to w10 (working as expected) and after some days i reinstalled w11 (didn't realize if the issue started immediately, or if it took some time)

As it was before, i expected that, everytime i clicked over my desktop, sound and image, would be playing, i've never had to click over the taskbar so it could work.

https://youtu.be/LdLYnyB-8uU (Video Footage)

It happens to any kind of videos i try.

 - OS: Windows 11 Pro 24H2]

Log
https://ufile.io/u2hwxd7q
Or
https://drive.google.com/file/d/1sVjHjUumEgnyU6spGdjd6yMZzV8EsOzY/view?usp=drive_link

**Comment by rocksdanister** [comment]
Usually this happens because you have something else in the foreground, do you use any desktop modification tool besides Lively?

**Comment by DaividBowie** [comment]
> Usually this happens because you have something else in the foreground, do you use any desktop modification tool besides Lively?

The only tool i use besides lively is Translucent TB, i uninstalled it and it didn't work. I always used both together actually, never been a problem.
I'll keep trying to solve this, make some adjusts and look at some system settings, could be my fault after changing the OS.

**Comment by rocksdanister** [comment]
Can you try toggling desktop icons (rightclick desktop views -> show desktop icons.)

**Comment by DaividBowie** [comment]
just tried, but no success.

**Comment by DaividBowie** [comment]
Well, i must have tried everything by now, so it picked my curiosity if any other engine would have the same issue and it didn't, which made my head blow, doesn't make sense at all, i vaguely remember it working in a day and then stopped.

Guess i'll wait the next update so i test once more, even if another engine works, lively is my favorite, you have been doing a great job, so it would be a shame giving up.
Thx for your time anyways.
