### ISSUE TITLE
Bug Report: Fullscreen Issue with Animated Wallpaper on Lively Wallpaper v2.1.0.8

### ISSUE THREAD

**Issue by ErassyJR** [rocksdanister/lively#2451]
Dear Lively Wallpaper Support Team,

I am experiencing a Fullscreen issue with Lively Wallpaper version 2.1.0.8 while using animated wallpapers. When an animated wallpaper is set, the live wallpaper does not display in Fullscreen mode. However, if I toggle off the animated wallpaper option, it goes Fullscreen, but this results in losing the animation feature.

Here are my system details for reference:

Device Name: ASUS
Processor: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz, 2.59 GHz
RAM: 8.00 GB (7.84 GB usable)
System Type: 64-bit operating system, x64-based processor
Pen and Touch: No pen or touch input available
Edition: Windows 11 Pro for Workstations
Version: 24H2
Installed On: Tue, 22/10/2024
OS Build: 26100.2161
Experience Pack: Windows Feature Experience Pack 1000.26100.32.0

It seems the issue may specifically relate to the use of mpv.exe to render the wallpaper. Any guidance or troubleshooting steps would be greatly appreciated, as well as any updates on a fix for this issue. Log report files are attached.

Thank you for your attention to this matter.

[lively_log_20241031_020754.zip](https://github.com/user-attachments/files/17580319/lively_log_20241031_020754.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2074#issuecomment-2146541025
dup: https://github.com/rocksdanister/lively/issues/2415
