### ISSUE TITLE
Win11 24H2   开机重启背景不会铺满全屏

### ISSUE THREAD

**Issue by xiaoyaoguangshijie** [rocksdanister/lively#2453]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/2415
