### ISSUE TITLE
Cannot use webview2 - plugin not found

### ISSUE THREAD

**Issue by pcefulpolarbear** [rocksdanister/lively#2454]
**Describe the bug**
Cannot change renderer from CefSharp to WebView2. Lively states plugin is not found.

**To Reproduce**
Go to Settings>Wallpaper>Web Browser and choose webview2 instead of CefSharp

**Expected behavior**
Lively will use WebView2 instead of CefSharp

**Screenshots/Video**
![image](https://github.com/user-attachments/assets/b5ebc5ac-8682-4ae0-b895-c4c5c4a8cb50)

**Desktop (please complete the following information):**
 - OS: Windows 11 Education 24H2
- Rain wallpaper selected

**Additional context**
Does not work with any of the wallpapers. Running the install for WebView2 tells me it is already installed.

**Log file (Important)**
attached
[lively_log_20241101_222858.zip](https://github.com/user-attachments/files/17605684/lively_log_20241101_222858.zip)

**Comment by rocksdanister** [comment]
WebView2 is bundled as a separate program and needs to be installed:
https://github.com/rocksdanister/lively/wiki/Web-Player#webview2-microsoft-edge

**Comment by pcefulpolarbear** [comment]
Okay, I missed step 1 and 2 in the documentation that was linked, sorry, thanks
