### ISSUE TITLE
video wallpaper fullscreen scale not kept through wallpaper changes

### ISSUE THREAD

**Issue by vermi5** [rocksdanister/lively#2462]
**Describe the bug**
On first run, video is correctly adjusted to all display edges, but on subsequent video wallpaper changes during runtime, a black bar is introduced on the top.

**To Reproduce**
1 - Run Lively, last active video wallpaper will play
2 - Either in the Library or by systray icon context menu, change wallpaper.

**Expected behavior**
For MPV to retain scale through file loads

**Screenshots/Video**

https://github.com/user-attachments/assets/bef1faf4-d5f9-4b64-9b27-25e919b46f5c

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2 26100.2161
 - Any video wallpaper

**Aditional Info**
Adding `fs` to mpv.conf seems to solve the issue
None of the scaling options in-app solved it.

**Log file (Important)**
Doesn't seem to show anything relevant but here you go:

[20241103_210626.txt](https://github.com/user-attachments/files/17611914/20241103_210626.txt)

**Comment by rocksdanister** [comment]
Don't run fs, window size should be managed by Lively.

duplicate: https://github.com/rocksdanister/lively/issues/2415
