### ISSUE TITLE
Unable to install screensaver plugin

### ISSUE THREAD

**Issue by SammySircle** [rocksdanister/lively#2468]
I am unable to install the screensaver plugin for my Lively app. The app is downloaded direct from "rockdanister" website. When I open the app and go to manage my desktops, I am able to upload desktops no problem. But when I click on the "screensaver" tab all the options are greyed out and there's a message at the top of the window saying "Plugin Required. One time set up is required to run screensaver". So I click on the link that brings me to this site. I assume I have downloaded and am running the latest version of the Lively app and so I click the plugin download link 2.1. It downloads fairly quickly. I extract the files, like the instructions say, but here is where I find my problem. I'm fairly certain I am misunderstanding some instruction as my PC is pretty new and about mid-range (so should not be a problem with my system). The instructions say to copy the newly extracted file to "C:\Windows\Lively.scr". First, I didn't have access to these folders and had to go through the process of changing permissions for Windows folders. Next, it seemed the path just did not exist. I finally - FINALLY - found it and copied my newly extracted file. nothing happens, I assume everything is fine. It is not. I go on to the next step (right click - "install"), it then opens my PC's screensaver settings. the drop down menu already has "Lively" selected. I click apply. I assume NOW it has worked. once again, I am wrong. I open the lively app, go to the screensaver tab in the manage wallpapers section of the app.... and everything is still greyed out, with a message saying "Plugin Required. One time set up is required to run screensaver". It's literally been an endless cycle of torture for me. I just want cool wallpapers and screensavers. Any and all help would be super appreciated! and on that note, I've already said I am pretty sure this is my own error, if you know what I have done wrong, please just tell me kindly. I am not very learned in PC operations. I'm new to this!!

**Comment by SammySircle** [comment]
![PXL_20241108_083158028 MP](https://github.com/user-attachments/assets/753e139d-4f0c-420a-ae83-0f642279ceb0)
![PXL_20241108_083216178 MP](https://github.com/user-attachments/assets/801bf6d4-3bc1-4c9e-bcbd-efcd7d3d70e5)
![PXL_20241108_083253733 MP](https://github.com/user-attachments/assets/58c83647-7a1c-4df7-a13b-036ee1c46ce4)
![PXL_20241108_083305611 MP](https://github.com/user-attachments/assets/09317254-3060-451d-a855-bd0a0cfaac81)
![PXL_20241108_083329262 MP](https://github.com/user-attachments/assets/ac66562c-1239-48f6-b3c1-fb8b795899a0)
![PXL_20241108_083514040 MP](https://github.com/user-attachments/assets/9d70aa30-bc60-4921-a098-9ea1d2edc624)
![PXL_20241108_083652375 MP](https://github.com/user-attachments/assets/bd987c58-479e-44f3-a0f3-40c8609d5a8d)
![PXL_20241108_083816257 MP](https://github.com/user-attachments/assets/5e648e77-9386-43ab-9190-6dd172679f36)
![PXL_20241108_083931683 MP](https://github.com/user-attachments/assets/8e51d778-0800-4999-9a9c-918d93e0e779)
![PXL_20241108_084015013 MP](https://github.com/user-attachments/assets/8d36cea8-fe3a-4006-8a70-576faa755ee0)
![PXL_20241108_085658865 MP](https://github.com/user-attachments/assets/4f74b35f-5349-492b-badf-c797dd8ac1dc)
![PXL_20241108_085713713 MP](https://github.com/user-attachments/assets/90abf1bb-b1e0-4ee6-bda9-b4accb6b0f08)
![PXL_20241108_085801278 MP](https://github.com/user-attachments/assets/9f58d047-93b3-4196-a312-3862b13292a1)

**Comment by SammySircle** [comment]
I have provided screenshots, hopefully they help describe what I'm doing (and what I'm doing wrong)

**Comment by rocksdanister** [comment]
The instructions says to copy the Lively.scr file to the Windows folder.. I don't think you did that.

**Comment by SammySircle** [comment]
I did actually. Even had to change my permissions just to be able to view the windows folders.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rocksdanister** [comment]
K. Might be permission related after all. I'll add the option to remove the message in future update.

**Comment by Ab-Tx** [comment]
I faced this issue. The 'Install' option does not show, neither does 'open with'.

This is what worked for me:

- Move the .scr file to:

>  C:\Windows\

- (Click “Continue” if asked for admin rights)
- Open the classic Screen Saver Settings:
- Press Win + R, type:

> control desk.cpl,,1

- Press Enter
- In the Screen saver dropdown, look for your .scr file name.
- If found, select it, then click Apply > OK
