### ISSUE TITLE
 after I want to turn on the wallpaper it starts to turn on and off quickly

### ISSUE THREAD

**Issue by geninrasta** [rocksdanister/lively#2469]
[lively_log_20241108_113831.zip](https://github.com/user-attachments/files/17676431/lively_log_20241108_113831.zip)

**Comment by str8shooteresquire** [comment]
I reported this, too, and my report was closed as being resolved. I am still having this issue and really want to use Lively.

**Comment by rocksdanister** [comment]
No, your report is closed as duplicate: https://github.com/rocksdanister/lively/issues/2486

As explained in the linked discussion, Windows 24H2 has problems with live wallpaper that will be resolved in future Windows update.

**Comment by str8shooteresquire** [comment]
I read #2464 as being a different issue. Hopefully the issue gets resolved with the next Windows update.

Thanks.
