### ISSUE TITLE
[Windows N - codec missing] Wallpaper in mp4 format is grayed out

### ISSUE THREAD

**Issue by AgustinCo** [rocksdanister/lively#247]
Hello

When I want to set the Eternal Light background (mp4 format) the background is completely gray. With the other funds that are in html format I have no problems. I am attaching a screenshot of my problem.

Regards.

![image](https://user-images.githubusercontent.com/76414260/102730770-8e418e80-4314-11eb-91e5-f826dae7fb58.png)

**Comment by rocksdanister** [comment]
I'm guessing you have Windows N, install the codec:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by AgustinCo** [comment]
It was my problem. Thanks a lot!
