### ISSUE TITLE
Wallpaper doesn't load after reboot with desktop icons disabled

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#2477]
**Describe the bug**
When booting into a system without desktop icons enabled the wallpaper doesn't load, only after enabling desktop icons

**To Reproduce**
1. Enable lively wallpaper, I had the rain one 
2. Disable show desktop icons 
3. Reboot
4. Wallpaper doesn't load 

**Expected behavior**
The Wallpaper would be applied 

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2
 
**Log file (Important)**
[lively_log_20241117_184356.zip](https://github.com/user-attachments/files/17791746/lively_log_20241117_184356.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/discussions/2464
