### ISSUE TITLE
设置自带壁纸失败 错误:ERROR|livelywpf.NLogger|failed to set parent, HRESULT:1400

### ISSUE THREAD

**Issue by TaiPiao** [rocksdanister/lively#248]
日志信息：[20201222_091710.txt](https://github.com/rocksdanister/lively/files/5727424/20201222_091710.txt)
系统版本win10 1909

**Comment by rocksdanister** [comment]
Have you tried restarting Windows?

**Comment by TaiPiao** [comment]
重启过

**Comment by TaiPiao** [comment]
.net重启后不需要运行吧，或者桌面会冲突吗？

**Comment by TaiPiao** [comment]
我重新安装了插件重启后执行不报错了，但是桌面不显示

**Comment by TaiPiao** [comment]
I reinstalled the plugin and the restart did not report an error, but the desktop did not show

**Comment by TaiPiao** [comment]
Okay, it's covered up by another desktop application

**Comment by rocksdanister** [comment]
Which application? https://github.com/rocksdanister/lively/issues/173 ?
HRESULT:1400 here means its not allowed, some other process is running on desktop.

**Comment by TaiPiao** [comment]
(电脑管家的一个桌面整理启动整理就会覆盖)A desktop tidbit of the computer steward will be overwritten when the tidbit is activated
