### ISSUE TITLE
Problem After Windows 24H2 Update

### ISSUE THREAD

**Issue by str8shooteresquire** [rocksdanister/lively#2486]
After updating to Windows 24H2, the wallpaper loaded by Lively flashes on and off while the stock Windows wallpaper remains.  The Taskbar flashes, too.

[lively_log_20241123_130231.zip](https://github.com/user-attachments/files/17882104/lively_log_20241123_130231.zip)
[lively_log_20241123_131012.zip](https://github.com/user-attachments/files/17882105/lively_log_20241123_131012.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/discussions/2464

**Comment by str8shooteresquire** [comment]
This issue has not been resolved. Any progress?

**Comment by str8shooteresquire** [comment]
Never mind. I found the solution on #2464 about turning off animation.
