### ISSUE TITLE
the wallpaper doesn't show or it instantly crashes

### ISSUE THREAD

**Issue by Strifr** [rocksdanister/lively#2487]
when i try to use lively there are 2 this it does.

1 when I select a wallpaper it turn on and off in the menu but doesn't show as actual windows wallpaper, and it keeps doing that until you close it. 

2. when i select a wallpaper it instantly freezes and doesn't go away even if i delete the application and restart the pc

lively_log_20241123_195445.zip

**Comment by Amrith-H-N** [comment]
same issue I guess

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/discussions/2464
