### ISSUE TITLE
More "performance" options, including (FPS slider).

### ISSUE THREAD

**Issue by RTXonFPSoff** [rocksdanister/lively#249]
**Is your feature request related to a problem? Please describe.**
Some laptops are not very powerful and some people with good laptops might prefer longer battery life or silent fan speeds. 

**Describe the solution you'd like**
The famous (Wallpaper Engine) in Steam has an FPS slider. I found out that lowering the FPS of the playback significantly affects the overall speed and power consumption of the system. Most of the time, having it lowered all the way down to 15 fps doesn't "ruin" the perceived overall quality of the playback. **However**, Lowering the FPS playback from 30 fps to 15 fps can be the difference between " I like this app but it is not worth it" and "This app changed how my pc looks and now I can never imagine using a pc without it".

**Describe alternatives you've considered**
Having more "performance" options also means that we can add move features like Post-processing and anti-aliasing effects.

**Additional context**
These features might be difficult to implement on "web-contents/ YouTube/Video steaming sources". But at least it could be implemented for local content.

**Comment by rocksdanister** [comment]
Web browsers don't have a standard way to control framerate, so this won't be possible for webpage wallpapers.
Currently Lively does not have its own format and all the things you mentioned about wpe only applies to their own "scene" format.

Closing this for now, feature discussion for Lively's own wallpaper system will come later.

**Comment by NutchapolSal** [comment]
for controlling FPS of web wallpapers, maybe look into controlling how often the callback in `requestAnimationFrame(callback)` is called? it wouldn't work on web wallpapers doing its own thing with `setInterval` or others but the rest of the internet also has this same problem so IMO there's not much we can do about it. if we're doing this, it should also be documented that using `requestAnimationFrame` is preferred over other methods and the reasons why.
