### ISSUE TITLE
none of the wallpapers are working

### ISSUE THREAD

**Issue by GeorgeDrettakis** [rocksdanister/lively#2490]
### **when i choose a wallpaper it tries to show it but it doesn't this happened after the latest Windows 11 update**

**Video**: https://github.com/user-attachments/assets/f3857363-89ab-4224-a346-d148a72ad1bd

**OS**: Windows 11
**Which** wallpaper was running at the: The Hill

**Report Log File**: [lively_log_20241128_172943.zip](https://github.com/user-attachments/files/17950023/lively_log_20241128_172943.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/discussions/2464
