### ISSUE TITLE
Lively wallpaper not working at all both on the microsoft store and off the official website

### ISSUE THREAD

**Issue by Sn1perzOnYT** [rocksdanister/lively#2494]
When Ever I Try To Run A Wallpaper Nothing Happens It Doesn't Try To Load It I've Installed It Over 20 Times Over And Over Again But Nothing Even Setting It To Make The Live Wallpaper To A Still Background Wont Do Anything I've Tried Installing It In Different Places But Nothing Works In Running Windows 11 Pro Version 24H2 I See When Ever I Go Into Setting My Default  wallpaper Is Just Black Which Is Really annoying This Is A Brand New Pc Build Specs Will Be Located At The Bottom On Rare Occasions It Crashes

I Was Running Many Different Wallpapers

[lively_log_20241129_203041.zip](https://github.com/user-attachments/files/17962837/lively_log_20241129_203041.zip)

**Comment by Sn1perzOnYT** [comment]
![image](https://github.com/user-attachments/assets/e4d32b4e-8b4a-47f5-8027-89d7bc9306ab)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/discussions/2464
