### ISSUE TITLE
Display disconnect behavior change.

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#25]
Currently wallpaper is removed from the list if the display in which its running is disconnected.
https://github.com/rocksdanister/lively/blob/8ab700f1207838fac8012692c6e1efaf5c5a5a55/src/livelywpf/livelywpf/MainWindow.xaml.cs#L424

I think its better to retain the settings, and restore in the event display is reconnected.
Screen class Devicename is very unreliable and will not generate same name for same display always, so will need to extract further information to ensure its the same display; also show greyed out display image in display layout window.

**Comment by DaBesFish** [comment]
Coming from #257. Is there a way I can alter the settings for this to apply to my subjective monitor preferences and boot up the wallpaper automatically when I start Windows? (My bad if I sound like a peasant n00b, I took one programming class back in 2012 for java and forgot basically everything)

**Comment by rocksdanister** [comment]
This will require quite a few changes and not something that can be done on your end.
The real problem is there is no easy way to uniquely identify display device so for safety reasons and to avoid duplicate hidden wallpapers I remove the wallpaper when disconnect is detected.
