### ISSUE TITLE
Newly added live wallpaper scaling/placement issue 

### ISSUE THREAD

**Issue by bishalqx980** [rocksdanister/lively#2506]
**Describe the bug**
Newly added live wallpaper scaling/placement issue.
As you can see on my screenshot that the top, right and left side are not filled up with lice wallpaper
If I go to Display settings then change it to screen or duplicate, it fixes the problem then again when I open a fullscreen game and come back to desktop I see the problem again

## And I THINK it's because of the new Windows 11 update? 
- I used the same version of this app on **Windows 11 22H2** and after installing **24H2** I faced this problem
- I tried it on my friends win11 22H2 and its works perfect, SO problem because of  **24H2** ??

**To Reproduce**
- [ **Maybe it's only for Windows 11 24H2** ]
1. Chose any default live wallpaper that comes with the app
2. click on the newly installed 3rd party live wallpaper

**Expected behavior**
Expected to work as usual, Normal

![Desktop Screenshot 2024 12 02 - 21 27 38 19](https://github.com/user-attachments/assets/01d3a2e2-75d9-44a8-bff5-ef9e1ebd8ae2)

**Desktop (please complete the following information):**
 - OS: WINDOWS 11 24H2 26100.2454
- You can see this on the screenshot

**Log file (Important)**
[lively_log_20241202_214456.zip](https://github.com/user-attachments/files/17980399/lively_log_20241202_214456.zip)

Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415
