### ISSUE TITLE
Black Boarders

### ISSUE THREAD

**Issue by ImMineOS** [rocksdanister/lively#2507]
Hello! Thanks for your app!
I have a Problem
When I'm using Videos as wallpaper, Video doesn't fill the screen (I have a 1080p monitor)

![image](https://github.com/user-attachments/assets/48bcf906-aa8a-4f71-821a-63f79921a389)

I'm learning English if I have mistaken, sorry 

System information:
Windows 11 24H2
build 26100
CPU: Intel i5 10400F
GPU: AMD RX580
Motherboard: Gigabyte B460M DS3H V2
Ram: 16GB

**Comment by bapstein** [comment]
I have the same issue since I updated to Windows 11 24H2. Turning on and off GPU codec in Wallpaper settings fixes the issue temporarily though.

**Comment by rocksdanister** [comment]
This is the permanent fix with GPU codec ON: https://github.com/rocksdanister/lively/issues/2415
