### ISSUE TITLE
Restart btn

### ISSUE THREAD

**Issue by MDReal32** [rocksdanister/lively#2508]
**Is your feature request related to a problem? Please describe.**
Sometimes (when u reinstall gpu driver) creating issue when white screen.

**Describe the solution you'd like**
A "restart" button in context menu which restarts software backgroundly.

**Describe alternatives you've considered**
Exit and re-open application

**Comment by rocksdanister** [comment]
There is a reload command: https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#set-wallpaper

You can create a shortcut icon.
