### ISSUE TITLE
Lively Wallpaper not working on Windows Arm64

### ISSUE THREAD

**Issue by dinosaur890123** [rocksdanister/lively#2513]
When I click on a wallpaper on an Arm64 device, it does nothing. I have tried all wallpapers and they dont work.
Log file: [lively_log_20241207_110929.zip](https://github.com/user-attachments/files/18045234/lively_log_20241207_110929.zip)

![image](https://github.com/user-attachments/assets/d72860d7-cf3e-4857-be38-ac981ac5057c)

**Comment by rocksdanister** [comment]
Its running the x86 build using emulation, waste of resource.

I was waiting for new snapdragon release to start working on arm build, will look into it.

Moving discussion to https://github.com/rocksdanister/lively/issues/1198
