### ISSUE TITLE
Stripes on the sides of the screen

### ISSUE THREAD

**Issue by waitgraphix** [rocksdanister/lively#2517]
**Describe the bug**
After updating Windows, I had a problem with displaying the wallpaper. Transparent stripes appeared along the edge of the screen

**To Reproduce**
1. Start Windows
2. Got transparent stripes appeared along the edge of the screen

**Expected behavior**
normal animated wallpaper display

**Screenshots/Video**
![Снимок экрана 2024-12-07 081242](https://github.com/user-attachments/assets/46de36c4-f8bf-4160-a989-1ca21f2b54d9)

**Desktop (please complete the following information):**
 - OS: [Windows 11 pro 64 (10.0 assembly 26100)]
- Which wallpaper was running at the time if any: 1052111

**Log file (Important)**
[lively_log_20241207_075840.zip](https://github.com/user-attachments/files/18046349/lively_log_20241207_075840.zip)

**Comment by rocksdanister** [comment]
Hard to tell from the screenshot, I think its https://github.com/rocksdanister/lively/issues/2415 issue.

Try the workarounds mentioned (mpv.conf file or downgrade mpv player.)

**Comment by waitgraphix** [comment]
I tried to setup vlc player, but its play video wallpapers without loop. 

I decided to reinstall Lively Wallpapers app, so this solved the problem. Issue not actual 👍
