### ISSUE TITLE
Wallpapers don't cover the whole screen

### ISSUE THREAD

**Issue by LarryEtte** [rocksdanister/lively#2523]
**Describe the bug**
When I boot my computer, the wallpapers don't apply on the whole screens, their size seem reduced. They worked perfectly well before.

**To Reproduce**
1. Boot the computer

**Expected behavior**
The wallpaper should cover the whole screen
**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2 26100.2314
- Which wallpaper was running at the time if any. : Official Valorant wallpapers animated (too big)

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20241209_004019.zip](https://github.com/user-attachments/files/18054562/lively_log_20241209_004019.zip)

**Comment by hollyjacobson** [comment]
Having same issue.
Updated my computer, rebooted, and now none of my wallpapers that previously fit will fill the screen. It's off on the top and sides by 1 or 2 cm. Not really sure what happened or how to fix, every wallpaper I download or try to apply has the same issue.

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415

**Comment by resex0** [comment]
> Having same issue. Updated my computer, rebooted, and now none of my wallpapers that previously fit will fill the screen. It's off on the top and sides by 1 or 2 cm. Not really sure what happened or how to fix, every wallpaper I download or try to apply has the same issue.

Same me too, I am also having that problem and haven't found any fix for it yet.

**Comment by rocksdanister** [comment]
> dup: [#2415](https://github.com/rocksdanister/lively/issues/2415)

Follow the link.
