### ISSUE TITLE
Low resolution with some youtube channels

### ISSUE THREAD

**Issue by Leucaruth** [rocksdanister/lively#2524]
Trying to use some videos on youtube sets quality as 360p instead an higher resolution, like, for example, this one:
https://www.youtube.com/watch?v=MrBRgVtJydY

Other videos work fine, like this one for example:
https://www.youtube.com/watch?v=VUwcMswIdR4

Can't find any option to change this behaviour, is there any way to set it from options?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper
