### ISSUE TITLE
Missing .SCR file in downloaded zip file for screensaver plugin.

### ISSUE THREAD

**Issue by kademer** [rocksdanister/lively#2526]
I downloaded the Lively Screensaver file, but it seems to be missing the .scr or .exe file. (see attached screenshot). Where can I get the plugin?

![Screenshot 2024-12-12 080749](https://github.com/user-attachments/assets/8012f825-b8c0-4aaf-bd94-8a70e9b9f2a6)

**Comment by rocksdanister** [comment]
`Lively` is the file, your system has extension (.scr) hidden by default.
