### ISSUE TITLE
The wallpaper cannot be displayed in full screen completely, and there is a border at the top of the screen.

### ISSUE THREAD

**Issue by xzd223** [rocksdanister/lively#2527]
The wallpaper cannot be displayed in full screen completely, and there is a border at the top of the screen.
The screen resolution of my device is 3200*2000, and the operating system version is Windows 11 24H2. 

![QQ图片20241212235805](https://github.com/user-attachments/assets/58fda714-db71-42bf-828e-3277e7dc2083)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415
