### ISSUE TITLE
Live wallpaper can't fill in screen after update Window

### ISSUE THREAD

**Issue by Lavi729** [rocksdanister/lively#2528]
After update window, the wallpaper can't fill in screen, the display in window setting still 1920 x 1080 and the live wallpaper also in 1920 x 1080.
![2](https://github.com/user-attachments/assets/de53f6f1-abf1-4cc6-a942-5ab87c216058)
![3](https://github.com/user-attachments/assets/b1c6f79f-2c49-41ce-8ff7-7904d69cd84f)
![4](https://github.com/user-attachments/assets/2b5976e9-b64a-4fd5-bcc1-45f2b406ca6e)
[lively_log_20241213_005033.zip](https://github.com/user-attachments/files/18114872/lively_log_20241213_005033.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415
