### ISSUE TITLE
Video Misalignment

### ISSUE THREAD

**Issue by dev-hd11** [rocksdanister/lively#2533]
**Describe the bug**
Whenever I add a custom video as the wallpaper it gets randomly misaligned.

**To Reproduce**
1. I add the video
2. Sometimes it is already misaligned, sometimes not
3. If I use it for sometime or change desktops, it again happens.

**Expected behavior**
It should remain in the middle and cover the whole screen.

**Screenshots/Video**
![Screenshot (11)](https://github.com/user-attachments/assets/a9953c1b-5460-4375-a764-8f40ef69b543)

**Desktop (please complete the following information):**
 - OS: Windows 11
- Custom Video

**Log file (Important)**

[lively_log_20241214_130810.zip](https://github.com/user-attachments/files/18134974/lively_log_20241214_130810.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415
