### ISSUE TITLE
scalling bug 

### ISSUE THREAD

**Issue by Mvkweb** [rocksdanister/lively#2535]
**Describe the bug**

**To Reproduce**
add any wallpaper 
thats it.

**Expected behavior**
It should definetely not look like this, seems like the scalling is wrong.

**Screenshots/Video**
![image](https://github.com/user-attachments/assets/50aca118-7b67-4f1f-883e-b28a977cb0ba)

**Desktop (please complete the following information):**
 - OS: Windows 11 24h2 Latest update

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415
