### ISSUE TITLE
MP4/GIF flashing

### ISSUE THREAD

**Issue by ayaangrover** [rocksdanister/lively#2537]
**Describe the bug**

Choosing a video or gif makes the wallpaper seem to burst into playback and then suddenly fade out. This repeats multiple times with ~2 second intervals. I've attached a screenshot of the dev log.

**To Reproduce**
1. Go to Lively Wallpaper App
2. Click on the plus button
3. Upload an mp4 or gif
4. See the video flash on and off in bursts.

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![Screenshot 2024-12-17 184014](https://github.com/user-attachments/assets/0f17aad4-9d95-4046-8c5e-fce612067a6f)

https://github.com/user-attachments/assets/0ee0a8d6-8f70-4473-b4b0-d24c94407d09

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
Windows 11 24H2 (OS Build 26120.2702)
- Which wallpaper was running at the time if any.
Custom gif, custom mp4(tried both)

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[20241217_184543.txt](https://github.com/user-attachments/files/18174044/20241217_184543.txt)

**Comment by eythaann** [comment]
I have this same issue, but this never happened before, I think is a windows' thing on recently insiders builds.

**Comment by PGoyal-06** [comment]
I am having the same issue. The wallpaper keeps flashing instead of being applied properly.

**Comment by rocksdanister** [comment]
Enable `Show desktop icons` in Windows and restart Lively.

dup: https://github.com/rocksdanister/lively/discussions/2464
