### ISSUE TITLE
Default Wallpaper visible around the edges

### ISSUE THREAD

**Issue by tj0vtj0v** [rocksdanister/lively#2538]
**Describe the bug**
When setting the background to an image i uploaded, the image gets scaled down, and i can see the default background around the edges. This happens on both of my displays and with uploaded videos and fotos.

**To Reproduce**
1. Drop Content into the 'add wallpaper' menu
2. Click ok
3. Select wallpaper
4. Done or select it as background of the other monitor too
5. Definitely done

**Expected behavior**
Image on at least one display shrinks, and reveals the default wallpaper around the edges

**Screenshots/Video**
![grafik](https://github.com/user-attachments/assets/8f519682-d1c1-42e1-9773-566605ab100c)

**Desktop (please complete the following information):**
 - OS: Windows 11
- Wallpaper: One of my own uploaded Images

**Additional context**
no resolution problem ig
Isn't working since 1 or 2 weeks but im not sure

**Log file (Important)**
[lively_log_20241218_103013.zip](https://github.com/user-attachments/files/18178213/lively_log_20241218_103013.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/issues/2415
