### ISSUE TITLE
App no longer projects wallpapers to any of my screens

### ISSUE THREAD

**Issue by chungus-one** [rocksdanister/lively#2544]
**Describe the bug**
Since today my Lively Wallpaper app does not post up a wallpaper no matter what

**To Reproduce**
1. Onen lively
2. click a wallpaper
3. nothing appears

**Expected behavior**
I expected a wallpaper to appear

**Desktop (please complete the following information):**
 - OS: Most recent version of Windows 11

**Additional context**
I installed the screensaver thing yesterday afternoon before shutting down my computer, I dont know if this is relevant 
**Log file (Important)**
[lively_log_20241221_184125.zip](https://github.com/user-attachments/files/18217712/lively_log_20241221_184125.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/discussions/2464
