### ISSUE TITLE
Custom Wallpapper Will Not Fill On Second Monitor

### ISSUE THREAD

**Issue by bobbix06** [rocksdanister/lively#2548]
**Describe the bug**
It Hapends When I Apply An Custom Wallpapper, It Will Fill The First One But The Second One Do Not Fill in

**To Reproduce**
1. Apply Wallpapper '(The Custom Wallpapper)'.

**Expected behavior**
It Should Fill In Both Screens With The Same Wallpapper

**Screenshots/Video**
https://github.com/user-attachments/assets/cfaef741-7c42-4aff-b2e9-7bfc613878c2
**Desktop (please complete the following information):**
 - OS: Windows 11 Home 24H2
- Which wallpaper was running at the time if any.
- (Custom Made One)

**Additional context**
It Maybe Hapend When I Was Upgradeing To Windows 11 24H2 Home

**Log file (Important)**
[lively_log_20241223_095732.zip](https://github.com/user-attachments/files/18227682/lively_log_20241223_095732.zip)

**Comment by bobbix06** [comment]
and now both of the screens's wallpapper isn't autofilled...

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/2415

**Comment by bobbix06** [comment]
ok...

**Comment by bobbix06** [comment]
its a mp4 file -_-

**Comment by rocksdanister** [comment]
The solution is listed in the linked issue.
