### ISSUE TITLE
WebView2模式交互和调试问题

### ISSUE THREAD

**Issue by aliofwind** [rocksdanister/lively#255]
目前CEF模式可以在桌面交互和通过端口进行调试，但是切换到WebView2模式下都无法使用

系统版本：Windows 10 Version 2004
Edge版本：Beta 88.0.705.29
Lively版本：1.1.7.0

**Comment by rocksdanister** [comment]
WebView2 is still under development and there are many critical bugs. 
Stick to using CEF and please avoid creating new issues related to WebView2.

In-order to switch to WebView2: Currently require `Edge Canary` build to be installed in the host system:
https://www.microsoftedgeinsider.com/en-us/download
This will change in final release.

**Comment by aliofwind** [comment]
内置的CEF并不支持H.264和H.265编码，而国内直播网站的流都是使用H.264编码，使用WebView2是被迫的而不是主动选择

**Comment by rocksdanister** [comment]
Officially youtube-dl and mpv player is used for bilibili and youtube streams and it should support more stream if I whitelist it.

**Comment by rocksdanister** [comment]
Lively auto detects some links and calls youtube-dl.

You can manually test this (there is no user interface):
1. Export the wallpaper .zip
2. Open LivelyInfo.json
2. Change `Type` to 10 and save.
3. Update the zip file and drag'and'drop into Lively window.
4. If done correctly in About page it should say Wallpaper Type as `Online Stream`.
5. Now try playing the wallpaper.

**Comment by aliofwind** [comment]
遗憾的是youtube-dl没有支持哔哩哔哩直播，平时用的是streamlink来解析

**Comment by rocksdanister** [comment]
That's unfortunate.

If you install the Edge canary build WebView2 should work.
It is still incomplete:
1. Mouse forwarding/input is buggy.
2. New Lively hardware api is not ready.
3. Many local webpages won't work because of cross-origin request.
4. Its not a separate program like the current CEF so stability can be a problem - can cause main Lively UI to crash.

**Comment by rocksdanister** [comment]
Edge Webview is semi-ready for online webpages on latest beta of Lively; does not require Edge canary to be installed.

Beta build link:
https://github.com/rocksdanister/lively-beta

Install Webview runtime if missing:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
