### ISSUE TITLE
Video wallpaper doesn't show up until I plug any USB storage device in...?

### ISSUE THREAD

**Issue by cryptoica** [rocksdanister/lively#2550]
> Installed lively from the Microsoft store.
> Selected the wallpaper, customized & applied it.
> Wallpaper doesn't show up (lively is still taking up memory when checked on Task Manager).
> Tried troubleshooting, nothing worked.
> Inserts HDD to transfer data.
> Wallpaper shows up.
> Tries again with pen drive.
> Happens again.
> Any USB storage device seems to work(tried with a mouse and it didn't work)

Drive link of a video of reproducing the error:
https://drive.google.com/file/d/1jh67Z_KcBd05NgRcPJ4M7p0FNd_U7t07/view?usp=drivesdk

**Comment by rocksdanister** [comment]
Does it show up when desktop icons are enabled in Windows?

**Comment by cryptoica** [comment]
Nope. It seems to work fine when desktop icons are enabled. Though it does take a sec to load in the wallpaper at startup

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/discussions/2464

Should be resolved in future Windows update.
