### ISSUE TITLE
Wallpaper not restoring after system restart. 

### ISSUE THREAD

**Issue by DaBesFish** [rocksdanister/lively#257]
I restart my computer at the beginning of every day, so it would be grea for Lively to automatically apply itself to the background when booting up. Plus it would be very useful to be able to save our wallpaper settings so that it boots up the exact wallpapers we had on pur monitor(s) as before.

Much love

**Comment by rocksdanister** [comment]
This is already a feature, you dont have start with windows enabled?

**Comment by DaBesFish** [comment]
I do but all it does is have it tucked in the taskbar. It doesn't start with the wallpapers automatically, i have to open Lively up manually. And also, it doesnt save my wallpaper settings. So i have to manually apply each individual wallpaper to 3 different monitors.

**Comment by rocksdanister** [comment]
Share the logfiles:

https://github.com/rocksdanister/lively/wiki/Common-Problems

**Comment by DaBesFish** [comment]
[logs.zip](https://github.com/rocksdanister/lively/files/5756565/logs.zip)

**Comment by rocksdanister** [comment]
I see multiple display disconnect and size change events being fired.
1. What is your display setup, how many monitor?
2. Share a screenshot of Windows Display settings page.
3. What display connectors each monitor use?

**Comment by DaBesFish** [comment]
Monitor 2 & 1 are both connected from a VGA to DisplayPort adapter which then plugs into the DisplayPort on my graphics card. Monitor 3 plus into the same graphics card with an HDMI.
![Screenshot 2020-12-31 104358](https://user-images.githubusercontent.com/76801569/103416542-3ba67480-4b55-11eb-8741-0b6d193179dc.png)
![Screenshot 2020-12-31 104452](https://user-images.githubusercontent.com/76801569/103416543-3c3f0b00-4b55-11eb-93d4-c5d8c43fa137.png)
![Screenshot 2020-12-31 104425](https://user-images.githubusercontent.com/76801569/103416544-3c3f0b00-4b55-11eb-9b42-4b86bdfca92b.png)

**Comment by rocksdanister** [comment]
This looks like the display port issue https://github.com/rocksdanister/lively/issues/234 which should resolve after https://github.com/rocksdanister/lively/issues/25

**Comment by jayagami** [comment]
save with me.

besides, seems not properly displayed on duals display.
the left is 1080p and the right is 2k.
and 1080P is the main screen .

![ATrvpkfJZC](https://user-images.githubusercontent.com/40586590/103863376-b34b4500-50fb-11eb-8946-2909480569d8.png)

you have to reset wallpaper on 2k display .

**Comment by rocksdanister** [comment]
The matrix webpage does not have resize event coded which is the cause of that particular issue.
You can verify it by resizing the Preview wallpaper window.

**Comment by jayagami** [comment]
> The matrix webpage does not have to resize event coded, which is the cause of that particular issue.
> You can verify it by resizing the Preview wallpaper window.

Thanks for replying.
I tried, and you are right.

But matrix webpage works fine on selected screen separately, 
it is just not properly working when I launch a new lively instance every time.
I have to reset the wallpaper on each display again.
I think this could be solved.

Thanks anyway. Maybe I should switch to other wallpapers instead of matrix webpage.

**Comment by rocksdanister** [comment]
Either this is related to this https://github.com/rocksdanister/lively/issues/246

Or there is a race condition in the startup code.

You can verify by trying the parallax.js wallpaper.
