### ISSUE TITLE
Unity game won't set as wallpaper

### ISSUE THREAD

**Issue by thomas-chernaik** [rocksdanister/lively#259]
when trying to set a program as a wallpaper ( a .exe file that works when run normally, and made in unity), either through the browse file method or by dragging it into the library, a black/dark grey box appears, the same size and shape as the customize box is. When clicking windows tab the window is called "library". While this window is open the lively application does not respond, and if I close this window from the taskbar it begins responding again and the program disappears from the library. At no point during this does the wallpaper get set as the program

**Comment by rocksdanister** [comment]
The unity program is trying to enter fullscreen by itself, ignoring Lively's resize request.
Make sure to disable fullscreen mode and enable run in background in build settings.

Docs:
https://github.com/rocksdanister/lively/wiki/Application-Wallpaper

**Comment by thomas-chernaik** [comment]
> 
> 
> The unity program is trying to enter fullscreen by itself, ignoring Lively's resize request.
> Make sure to disable fullscreen mode and enable run in background in build settings.
> 
> Docs:
> https://github.com/rocksdanister/lively/wiki/Application-Wallpaper

thank you very much :)
