### ISSUE TITLE
Automatic Mute or Mute by Keyboard Shortcut

### ISSUE THREAD

**Issue by turyunus** [rocksdanister/lively#261]
Hi,

I really like the project. Thanks for everything.
I need the some feature and I think it can be an important feature.
Can you add an option to mute wallpaper sound automatically when another app plays sound or can you add customizable keyboard shortcuts to mute wallpaper sound speedly?

Thanks for everything.

**Comment by rocksdanister** [comment]
I can do mute system-tray menu and settings option https://github.com/rocksdanister/lively/issues/262 for next update.

Detecting audio will require some work, shortcut is possible but that will require some heavy ui work for customizing key combo etc.. will require time, saving it for when complete overhaul of the audio manager takes place.

**Comment by rocksdanister** [comment]
This can be done now using command line control - you can create a batch script and run it/use it with autohotkey/keyboard macro programs.

Documentation:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls

**Comment by rocksdanister** [comment]
Here is a autohotkey script to toggle volume between 0 and 75 by pressing `Win + Z` key
```
toggle:= false
; hotkeys - winkey-z
#z::
toggle := !toggle
If toggle
{
  Run cmd.exe /c livelycu.exe app --volume 0,,hide 
}
else
{
  Run cmd.exe /c livelycu.exe app --volume 75,,hide 
}
```

**Comment by turyunus** [comment]
Awesome, thank you very much
