### ISSUE TITLE
Automatic disable when switching to battery mode

### ISSUE THREAD

**Issue by jayagami** [rocksdanister/lively#263]
**Is your feature request related to a problem? Please describe.**

For laptops, when switching to battery model, automatically disable lively wallpaper to save power.

**Describe the solution you'd like**

Using a static image as the background, and when the charger is connected, switch to lively wallpaper

**Comment by rocksdanister** [comment]
Lively can already pause the wallpaper when on battery power:
![Screenshot 2021-01-04 084143](https://user-images.githubusercontent.com/17554161/103497838-c0043a80-4e68-11eb-9633-031e881f573d.png)

**When paused:**
For video wallpapers, paused frame is shown.
For webpage wallpapers it will be blackscreen, this will be resolved when https://github.com/rocksdanister/lively/issues/20 is closed.
>Using a static image as the background, and when the charger is connected, switch to lively wallpaper

I think the above case is adequate for most users, anything more could maybe be done with playlist https://github.com/rocksdanister/lively/issues/137 by the user and does not require separate settings option in the app.
