### ISSUE TITLE
livelyAudioListener not being called

### ISSUE THREAD

**Issue by pathakhimanshucs** [rocksdanister/lively#266]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki 
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
The function `livelyAudioListener` is not being called in web based wallpapers. When running the sample audio bars visualization the error persists (just a black screen). I am trying to create a wallpaper based on the sample project.
 
**To Reproduce**
1. Run audio visualization sample project

**Expected behavior**
livelyAudioListener function to be called multiple times per second.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Same issue on both github version and ms store.

**Additional context**

**Log file**
Share the log file(s) from Local Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

2021-01-06 12:38:11.4469|INFO|livelywpf.SetupDesktop|Core: Setting Wallpaper=>index.html C:\Users\<user>\Desktop\TestWallpaper\index.html
2021-01-06 12:38:11.8529|INFO|livelywpf.Core.WebProcess|CEF:HWND394176
2021-01-06 12:38:11.8591|INFO|livelywpf.SetupDesktop|Sending wallpaper(Per Screen)=>\\.\DISPLAY1 {X=0,Y=0,Width=1920,Height=1080}
2021-01-06 12:38:11.8849|DEBUG|livelywpf.SetupDesktop|Relative Coordinates of WP=>0 1920 1920 1080
2021-01-06 12:38:11.8928|DEBUG|livelywpf.SetupDesktop|Coordinate wrt to screen=>0 0 1920 1080
2021-01-06 12:38:12.1350|INFO|livelywpf.Core.WebProcess|CEF:audioReact

**Comment by rocksdanister** [comment]
Share the logfile as attachment.

**Comment by pathakhimanshucs** [comment]
[20210106_124434.txt](https://github.com/rocksdanister/lively/files/5775561/20210106_124434.txt)

**Comment by rocksdanister** [comment]
`CEF:audioReact`
I'm not sure why this message is cut off.
Does the included `Fluid v2` wallpaper react with music?

**Comment by pathakhimanshucs** [comment]
> `CEF:audioReact`
> I'm not sure why this message is cut off.

This is a message that I am logging. Otherwise there are no errors. When music is playing, nothing is logged to console in dev tools. 

> Does the included `Fluid v2` wallpaper react with music?

Yes, however the visualizer sample project does not.

```
function livelyAudioListener(audioArray) {
    console.log(audioArray);
}
```

**Comment by rocksdanister** [comment]
Did you open the html as `Website Audio(*.html)` in file dropdown?
Create Lively .zip from context menu and share the project here.

**Comment by pathakhimanshucs** [comment]
No why would I be doing that. 😆

**Comment by rocksdanister** [comment]
...

**Comment by pathakhimanshucs** [comment]
Now that I look again at the json files of other wallpapers I see the type field -.-
