### ISSUE TITLE
Add option to disable cursor/touch reaction in Fluids v2

### ISSUE THREAD

**Issue by ANotThrowawayKonto** [rocksdanister/lively#267]
**Is your feature request related to a problem? Please describe.**
Add option to disable cursor or touch reaction in Fluids v2.
This enables audio visualizer to work without cursor or touch interference, and save resources.

**Describe the solution you'd like**
Add checkbox option to disable addEventListener() method for cursor and mouse if possible, or other workarounds.

**Describe alternatives you've considered**
None

**Additional context**
![ega](https://user-images.githubusercontent.com/65613497/103863568-68acd700-50c1-11eb-89e3-141cae9e3217.png)

PS : using performance.now() instead of Date.now() seems to improve the responsiveness of the visualizer (or it may be simply my placebo) :)
Reference : https://developers.google.com/web/updates/2012/08/When-milliseconds-are-not-enough-performance-now

**Comment by rocksdanister** [comment]
Only software related issues please.
