### ISSUE TITLE
Ability to disable features

### ISSUE THREAD

**Issue by SpooderMaan** [rocksdanister/lively#268]
I cannot find any option to disable the interaction menu that pops up while hovering with the mouse on the left border of the display. It restricts my acces to many of my applications and would be easy to integrate.

**Comment by rocksdanister** [comment]
Can you show a screenshot?

**Comment by SpooderMaan** [comment]
![Screenshot (89)](https://user-images.githubusercontent.com/77028501/103953971-799e2c80-5143-11eb-95f0-16c56b896ea3.png)
Sure !

**Comment by rocksdanister** [comment]
That is part of the webpage/wallpaper, not Lively software itself.
You will have to edit that webpage code to remove it.
or you can also download the version with it disabled from: 
https://www.deviantart.com/livelywallpaper/gallery/71626595/web-wallpapers

**Comment by SpooderMaan** [comment]
I'm noticing that my cursor is not being displayed. It was placed around the middle (width) of the bar and then started the hover interaction.
