### ISSUE TITLE
Lively Lock Mode Support

### ISSUE THREAD

**Issue by DemonRem** [rocksdanister/lively#269]
hey @rocksdanister 

i have an idea for a cool feature , as we all know windows 10 have a lock screen too before
windows startup depend if it have password anyway while the computer on the lock mode
will be great if this software can play on lock mode if you know what i mean

**Comment by rocksdanister** [comment]
I doubt this will be possible due to security reasons (user login area.)

**Comment by DemonRem** [comment]
thanks anyway ;)
