### ISSUE TITLE
Pause wallpaper when there is a windows is maximized 

### ISSUE THREAD

**Issue by tedomi2705** [rocksdanister/lively#270]
**Describe the solution you'd like**
When a windows is maximized, you cant see the wallpaper so it is wasting resource

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by rocksdanister** [comment]
This is already a feature:
![Screenshot 2021-01-08 211442](https://user-images.githubusercontent.com/17554161/104034170-8e87c800-51f6-11eb-84ef-e04b5eab58a1.png)

**Comment by tedomi2705** [comment]
that is fullscreen not maximized

**Comment by rocksdanister** [comment]
Its covering both cases:
https://github.com/rocksdanister/lively/blob/eb2f7f044dbd0e2f7396da8b886d5ad29e40aa37/src/livelywpf/livelywpf/Core/Playback/Playback.cs#L231-L242

Doc:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iszoomed
