### ISSUE TITLE
Built-in scheduler for pausing and/or changing wallpapers

### ISSUE THREAD

**Issue by profucius** [rocksdanister/lively#274]
I propose a feature request within the application, a Scheduler for pausing/resuming, or changing the wallpaper, based on a time frame set.

Example: Between midnight and 8am, any current wallpaper is paused.
Example: Between 8am and 12pm, a morning oriented wallpaper is set.
Example: Between 6pm and 10pm, an evening/relaxing wallpaper is set.

An alternative to the pausing that I could do now but do not wish to do, is to use Task Scheduler to run a .BAT file to kill Lively Wallpaper at certain times. However this is not a solution for the changing of wallpapers.

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/137
