### ISSUE TITLE
Wallpaper *always* mutes when another window is focused.

### ISSUE THREAD

**Issue by INSTRUMXNTAL** [rocksdanister/lively#275]
I've recently updated to the latest version (v1.1.8.0) and now, regardless of my settings, whenever any window that isn't the desktop is in focus, the audio stream (it's a 24/7 youtube stream) stops. It will then immediately continue playing once the desktop is back in focus.

I had/have it set so that it should do nothing when different applications go fullscreen or become focused and just keep playing constantly.
I have pasted logs, but they don't give errors of any sort and are really short, so I'm unsure if it's helpful or not.
https://pastebin.com/WQzVbJ2Y

**Comment by rocksdanister** [comment]
The new audio setting is under Audio:
![Screenshot 2021-01-13 181045](https://user-images.githubusercontent.com/17554161/104453600-ac747480-55ca-11eb-814b-4a64694cb4ae.png)

**Comment by INSTRUMXNTAL** [comment]
Cheers man, my bad. I didn't realise it had changed. I was checking all the performance settings, but couldn't open my goddamn eyes (.﹒︣︿﹒︣.)
