### ISSUE TITLE
Audio Visualizer not working with other playback devices

### ISSUE THREAD

**Issue by AdrianArroyoC** [rocksdanister/lively#276]
**Describe the bug**
The Audio Visualizer doesn't show any response using another playback device, even I change the app output in the App volume an device preferences.

**To Reproduce**
1. Connect a new audio playback device to the computer.
2. Go to the audio icon next to the languages options in the task bar and click it.
3. Change the playback device (example: I'm using a Logitech G560 Gaming Speakers).
4. See error on the wallpaper.

**Expected behavior**
I Expected it works the same as with de default laptop spekaers

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- Audio Visualizer wallpaper

**Comment by rocksdanister** [comment]
Yeah, the audio device initialization is done at startup only.
One possible workaround you could try is to virtualize all the audio output devices to a single one using some third party software.

**Comment by Aragur** [comment]
I am using a GoXLR which has different outputs, it would be nice if I could choose on which playback device the audio visualizer will listen to.
![image](https://user-images.githubusercontent.com/11004008/109813388-916acc00-7c2d-11eb-930e-d6e108ad1eac.png)

**Comment by snoowfall** [comment]
Hi, you seemed to have closed my issue. Doesn't matter.

Just wanted to ask, is there any way to make Lively initialize devices about every 15 seconds or so?
+there is workaround, just right-click on the tray icon, hit "exit" and open Lively again. Of course, it takes time and it really isn't the best method, but it is what it is. 

But this was the question I was asking for:
_Just wanted to ask, is there any way to make Lively initialize devices about every 15 seconds or so?_

**Comment by rocksdanister** [comment]
@Aragur 
Should be possible by implementing the configuration settings into a file, will look into it.

@COMHack20 
>Hi, you seemed to have closed my issue. Doesn't matter.

Yes its same as this issue, will be fixed when this issue is closed.

If its working after restart then one solution would be to re-initialize when audio device change event fires, will look into it.

**Comment by snoowfall** [comment]
I am sorry, im still learning to code, so.
I can't do it myself. It would be awesome if I could help. 
Im learning C, Python, JavaScript and sometimes others but yeah.

**Comment by COMHack20** [comment]
(As this is open-source project)

**Comment by jtag83** [comment]
Hello,

i have the same issue as AdrianArroyoC with my logitech g935.

audio vizualiser on fluid v2 not working.

:(

thanks
