### ISSUE TITLE
Manually enabling/disabling Lively with remote desktop 

### ISSUE THREAD

**Issue by MatthAddax** [rocksdanister/lively#277]
After update [v1.1.6.0](https://github.com/rocksdanister/lively/releases/tag/v1.1.6.0) when in remote desktop the wallpapers pauses automatically
**Describe the solution you'd like**
Is it possible to add a switch to enable/disable remote desktop pause?

Thank you,
Matth

**Comment by rocksdanister** [comment]
I wont be adding UI element, just add/edit `Settings.json` files `DetectRemoteDesktop` variable to `false`.

Reason for auto-pause https://github.com/rocksdanister/lively/issues/207

**Comment by My-Name-Is-Adam** [comment]
Sorry to reopen this but I changed the settings file to enable this when in a remote desktop session. As it lags I'd like to revert the change but can no longer find the file. 
Not sure if I'm looking in the wrong place or something. 
I'd appreciate your guidance. 

Thank you.

**Comment by My-Name-Is-Adam** [comment]
@rocksdanister

**Comment by rocksdanister** [comment]
For installer:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper`
Replace `<UserName>` with your username.

For store app in Windows Run enter this:
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper`
