### ISSUE TITLE
[Windows N] No me permite añadir videos como fondo de pantalla

### ISSUE THREAD

**Issue by JJuanjo19** [rocksdanister/lively#278]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki 
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
Cuando añado un video, me lo añade al lively pero me aparece en negro y no se añade correctamente, no se por qué

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file**
Share the log file(s) from Local Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Install the codec:
https://github.com/rocksdanister/lively/wiki/Video-Guide

If that does not work, share the logfile.

**Comment by JJuanjo19** [comment]
eternal_light_v2_4K.mp4
<https://drive.google.com/file/d/1NxvObC-nA5oIBLh6K3C8-7JKCQ2GCp1i/view?usp=drive_web>

**Comment by JJuanjo19** [comment]
Is not working, Idk why??

**Comment by rocksdanister** [comment]
Do not reply through email!

I want you to attach the text logfile in github itself:
https://github.com/rocksdanister/lively/wiki/Common-Problems

**Comment by JJuanjo19** [comment]
Mi versión de Windows es 2004 (compilación de SO 19041.746. Windows 10 Pro N.
![Captura](https://user-images.githubusercontent.com/47836416/104637743-7a841080-56a5-11eb-908f-2f773d4c659f.PNG)
![Captura](https://user-images.githubusercontent.com/47836416/104637791-8c65b380-56a5-11eb-9902-bba889467240.PNG)
Tengo instalado el codec adicional también, no sé que error puede ocurrir

**Comment by rocksdanister** [comment]
libVLCPlayer player is not the codec, delete that folder.

Please read regarding Windows N system:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by dabjulmaros** [comment]
Tienes que descargar y installar los codecs the windows media player, dado a que no vienen con los sistemas windows N o K.
https://www.microsoft.com/en-us/software-download/mediafeaturepack

**Comment by JJuanjo19** [comment]
> Tienes que descargar e instalar los códecs del reproductor multimedia de Windows, dado que no vienen con los sistemas Windows N o K.
> https://www.microsoft.com/en-us/software-download/mediafeaturepack

No me permite instalarlo, al descargarme este archivo:Windows_MediaFeaturePack_x64_1903_V1
procedo a ejecutarlo y me da el error de que la actualización no es aplicable al equipo

**Comment by rocksdanister** [comment]
From the video guide:
https://www.codecguide.com/windows_media_codecs.htm
``` 
You can acquire the package through Windows settings:
Start > Settings > Apps > Apps & Features > Optional Features > Add a feature > Media Feature Pack
```

**Comment by JJuanjo19** [comment]
Muchisimas gracias, lo he conseguido al final siguiendo esto: Start > Settings > Apps > Apps & Features > Optional Features > Add a feature > Media Feature Pack
Lo raro es que ese pack ya deberia de estar instalado
De todos modos muchas gracias.

**Comment by rocksdanister** [comment]
**Windows N** does not come with it and every time Microsoft releases a major update to Windows 10, you must install the media feature pack again.
