### ISSUE TITLE
Feature Request: A way to convert wallpapers made for wallpaper engine to Lively

### ISSUE THREAD

**Issue by Shorono** [rocksdanister/lively#280]
Most people who are into animated/reactive wallpapers will most likely have used wallpaper engine. And many probably have made some wallpapers for wallpaper engine using the wallpaper editor there. While pictures and videos are easy to port, but stuff made using the editor that has added stuff like parralax will be have to be completely remade using web technologies. Causing many to not bother. I am not sure how feasible this is but it would definitley increase the amount of availible wallpapers by a lot.

**Comment by rocksdanister** [comment]
This is not the direction I wish to take lively, moreover the scene format used by wpe is likely copyrighted.

To elaborate reverse engineering and playing catch up to wpe is not lively's goal. 

I will be looking into making my own opensource wallpaper animation system in the future once things settle down a bit.
