### ISSUE TITLE
Wallpaper wrong size on startup 

### ISSUE THREAD

**Issue by EmP-Y** [rocksdanister/lively#283]
Describe the bug
For some reason, some times when I open my pc the wallpaper appears like this:
![unknown](https://user-images.githubusercontent.com/43647417/105577688-d58fc480-5d83-11eb-9748-cef4b368d04c.png)
I can repair it by just switching to another wallpaper then switching back.

**To Reproduce**
It only happens when I reopen the PC.
It also doesn't happen every time. 
 UPDATE: Restarting does cause the issue and changing the wallpaper scaling algorithm seems to trigger it most of the time

**Desktop (please complete the following information):**
 - OS: Windows 10
- Which wallpaper was running at the time if any. (Blade Runner City Lights 4K Live Wallpaper)

**Log file**
[20210123_133840.txt](https://github.com/rocksdanister/lively/files/5860211/20210123_133840.txt)
[20210121_071935.txt](https://github.com/rocksdanister/lively/files/5860212/20210121_071935.txt)
[20210121_122138.txt](https://github.com/rocksdanister/lively/files/5860213/20210121_122138.txt)
[20210121_224814.txt](https://github.com/rocksdanister/lively/files/5860214/20210121_224814.txt)
[20210122_075504.txt](https://github.com/rocksdanister/lively/files/5860215/20210122_075504.txt)
[20210123_003336.txt](https://github.com/rocksdanister/lively/files/5860216/20210123_003336.txt)

**Comment by rocksdanister** [comment]
Looks like this is a race condition.
Default window size of the video player is 800x450:
https://github.com/rocksdanister/lively/blob/c5886f659f5dbb72a6983461fa0a4cadea3ffdb1/src/livelywpf/libMPVPlayer/MainWindow.xaml#L11
Examining the multiple screenshot I received that's the size of the wallpaper in them.
I'm adjusting the window size through the main program using setwindowpos after receiving the window handle from the video player via Window_Loaded event.

Solution would be to send the initial window size as commandline argument even before window init.

I didn't check the logfile yet, need to verify if its also related to this https://github.com/rocksdanister/lively/issues/246

**Comment by EmP-Y** [comment]
how do I do that?

**Comment by rocksdanister** [comment]
You can't on your side, this will be a new update fix for lively.

**Comment by EmP-Y** [comment]
aww cool, it doesn't bother me a lot but it would be nice if it could get fixed so tnks
