### ISSUE TITLE
Fluid v2 Audio Visualizer not working

### ISSUE THREAD

**Issue by michaelangelo0727** [rocksdanister/lively#284]
Whenever I play music with the Fluid v2 wallpaper the audio visualization doesn't seem to work, regardless of the playback device, while everything else works perfectly. I would like to know if there is a fix to this or if there is nothing I can do.
Best regards and keep up the great work!

**Comment by rocksdanister** [comment]
Does the most recent logfile show any error?
https://github.com/rocksdanister/lively/wiki/Common-Problems
If you have any virtual surround audio software and windows sound enhancement, try turning it off.
