### ISSUE TITLE
Keyboard Input Option Greyed Out

### ISSUE THREAD

**Issue by vodkya** [rocksdanister/lively#285]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki 
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
I'm not sure if this is a bug or it hasn't been implemented yet, but when going to Settings > Wallpaper > Interaction, the Keyboard option is greyed out.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Wallpaper'
3. Click on the selection field for 'Wallpaper Input'.
4. See error (Keyboard greyed out.)

**Expected behavior**
Keyboard not being greyed out.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/56273352/105769990-e1ae8a00-5f1b-11eb-8bad-180899797a5a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Which wallpaper was running at the time if any.
Hungry Knight (an adobe flash projector running the game)

**Additional context**
I guess I just wanna play hungry Knight on my desktop. This probably isn't a very important thing.

**Log file**
[20210125_140419.txt](https://github.com/rocksdanister/lively/files/5869885/20210125_140419.txt)
[20210125_140435.txt](https://github.com/rocksdanister/lively/files/5869887/20210125_140435.txt)
[20210125_142848.txt](https://github.com/rocksdanister/lively/files/5869888/20210125_142848.txt)

**Comment by rocksdanister** [comment]
Its not out yet, next [update](https://github.com/rocksdanister/lively-beta/releases) will have it.
