### ISSUE TITLE
Lively Wallpaper wont launch

### ISSUE THREAD

**Issue by TechnoFynch** [rocksdanister/lively#286]
Okay, so I know there is already an issue mentioned on GitHub regarding this issue which was dated Jun 2020. But, unfortunately, I am a bit lost about what I need to do, even after reading the entire issue.
So the problem is that I am not able to launch lively wallpaper on my Windows 10. No matter what I do, I tried reinstalling but it still wont launch. I think it has something to do with Visual Studio 2019. Before I installed VS 2019, lively was working properly, but now it wont launch.

System Config:
I checked the system requirements and my laptop meets them all.
OS: Windows 10, version 20H2
.NET Core: 3.1.405 and 5.0.102
Miscrosoft Visual C++ 2015-2019 Redistributable (x86) version 14.24.28127
RAM: 16 gb
Processor: Intel i7 3rd gen
Graphics: AMD Radeon 8750

**Comment by rocksdanister** [comment]
Which old issue exactly?
Probably xaml island related..
1. Is new logfile being created? if so what does it say.
2. Did you try the Windows store version of Lively?

**Comment by TechnoFynch** [comment]
Umm, if the location of the logfile should be Documents/Lively then I cannot find any folder named lively in my documents folder.
I will try the windows store version and get back to you, and I think the related issue would be #39

**Comment by rocksdanister** [comment]
Location of logfile:
https://github.com/rocksdanister/lively/wiki/Common-Problems

The windows store version should work, its a more traditional wpf application.

**Comment by TechnoFynch** [comment]
Okay thanks! The windows store version works! Im closing this issue!
