### ISSUE TITLE
Stutter when playing youtube video

### ISSUE THREAD

**Issue by Spruce8913** [rocksdanister/lively#287]
I checked the wiki for common problems, but couldn't find my problem.
I used a youtube video as wallpaper, and everytime when the video ends, there's a small pause before he start the video again.

This is not a problem for some videos, but for pleasing videos like underneath, it's very annoying.

I run Windows 10 on a laptop from 2017.
I used the video from https://www.youtube.com/watch?v=a9_MOt4PW_Q.
When you play the wallpaper at 3 times speed, the pause is very clear.

Is it because the video is being accessed online every time it restarts, and needs time to reload?
Would it be possible to implement it, so that the beginning of the video is already being loaded in while you're reaching the end?
Or is it just better as a workaround that I download the youtubevideo and use the local file?

This is just a hypothesis for the reason.
**Additional context**

**Comment by Spruce8913** [comment]
The problem persists when I download the youtube video, and drop it into lively as an mp4.

**Comment by rocksdanister** [comment]
Yes, there will be a small delay before loop.
Things you can try:
1. Extend the clip length by repeating the clip in editing software so as to not make it visible always (the clip length is too short currently.)
2. Use the web browser to play the video, it will be smooth loop.
Guide:
https://github.com/rocksdanister/lively/wiki/Web-Guide-VI-:-Webpage-Video-Support
Or you can use this existing wallpaper and just add the webm file to it, the panel can be disabled in properties:
https://www.deviantart.com/rocksdanister/art/Simple-Weather-Video-843514449
3. Contribute by adding support for a new video player plugin:
https://github.com/rocksdanister/lively/wiki/Building

Regarding (3), I will try to do it myself at some point.. but not anytime soon.

**Comment by Spruce8913** [comment]
Thank you for your thorough explanation!

**Comment by Spruce8913** [comment]
I followed your 2. explanation, however there's still a stutter when it ends.

[Mandelbulb.zip](https://github.com/rocksdanister/lively/files/5897762/Mandelbulb.zip)

I will try to extend the clip in editing software

**Comment by Spruce8913** [comment]
Okay, I just found out the original clip I was using didn't even match its own ending perfectly, so yeah.
Will close this issue, since you're already aware of the stuttering
