### ISSUE TITLE
Set application as wallpaper.

### ISSUE THREAD

**Issue by E14Dev** [rocksdanister/lively#288]
Hey, Sorry to list this as an issue, since there is no fault with your software. I was just wondering whether you could help me understand how your software works, I wanted to combine 2 lots of software (lively and Snip) to make my desktop play the music video of the song that I am currently listening to on Spotify, however I have no idea how you play the video on the desktop, any help would be greatly appreciated and you could potentially add this concept as a feature to your software.

**Comment by rocksdanister** [comment]
Lively already supports application wallpapers!

The docs should help:
https://github.com/rocksdanister/lively/wiki/Application-Wallpaper

Just drag'and'drop the gui application .exe file into Lively library.

https://user-images.githubusercontent.com/17554161/106388905-8d694580-6406-11eb-8b6d-c983f639f292.mp4

**Comment by E14Dev** [comment]
Thank you @rocksdanister
