### ISSUE TITLE
Background cycling feature request

### ISSUE THREAD

**Issue by D3MZ** [rocksdanister/lively#290]
**Is your feature request related to a problem? Please describe.**
Desktop backgrounds get stale

**Describe the solution you'd like**
Would like Desktop backgrounds to be automatically rotated after X period of Y time (seconds, minutes, days... opens) 

**Describe alternatives you've considered**
I have to manually switch videos

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/137
