### ISSUE TITLE
mpv player support

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#292]
**Is your feature request related to a problem? Please describe.**
libMPV (Ext) video player exhibits issues in rare cases on some systems.

**Describe the solution you'd like**
Implement [IWallpaper](https://github.com/rocksdanister/lively/blob/dev-v1.0-fluent-netcore/src/livelywpf/livelywpf/Core/Interface/Wallpaper.cs) interface for official mpv player.
Using official player might resolve some of the issues with the wrapper library.
For communication, mpv player supports pipes in windows:
[Documentation](https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst)

**Additional context**
[LivelyProperties](https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction), [conf file](https://github.com/rocksdanister/lively/wiki/Video-Guide) and [youtube-dl](https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper) should be supported.

**Comment by rocksdanister** [comment]
@hooke007 Can you verify if everything works normally, mpv is the new default player:
https://github.com/rocksdanister/lively-beta/releases

I could not find a commandline arg to set custom config file(?) 
Since its the official player, you can add the mpv.conf file in the folder itself and should work.

**Comment by hooke007** [comment]
Yes, I've used for a while. No obvious bug I have ever met until now.

**Comment by rocksdanister** [comment]
No, what I mean is from now onwards Lively will be using the official mpv player build and not this custom libmpv wrapper:
https://github.com/rocksdanister/lively/tree/dev-v1.0-fluent-netcore/src/livelywpf/libMPVPlayer

![Untitled](https://user-images.githubusercontent.com/17554161/107150141-594fd080-6982-11eb-866f-e3b4bb96979d.png)

**Comment by hooke007** [comment]
Lively still uses the hardware decoding even if I set the `hwdec=no`
But I open the mpv.exe to run with the same options, it works well.

**Comment by rocksdanister** [comment]
`I could not find a commandline arg to set custom config file(?)
Since its the official player, you can add the mpv.conf file in the folder itself and should work.`

`plugins\mpv` folder or the PATH folder for mpv?

**Comment by hooke007** [comment]
`hwdec=no` is written in the `mpv.conf`
\portable_config\mpv.conf

other options can be read correctly like
`icc-profile-auto`

**Comment by rocksdanister** [comment]
but where did you create the file?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/blob/d13276da1e9ee8ea6b78c813d922021eb0320166/src/livelywpf/livelywpf/Core/Wallpapers/VideoMpvPlayer.cs#L86-L106

Weird, I have not told it to ignore the file.

**Comment by hooke007** [comment]
Try to delete the line 93-94? mpv use the software-decoding as the default option.

**Comment by rocksdanister** [comment]
Can't do that, I want hw acceleration.
So the config file wont override that hmm..

**Comment by hooke007** [comment]
> Can't do that, I want hw acceleration.

you can add the portable mpv.conf (with `hwdec=auto`) into the mpv folder. So it still run by the hwaccel as the default profile.
And users won't feel the change.

**Comment by rocksdanister** [comment]
>you can add the portable mpv.conf (with hwdec=auto) into the mpv folder. So it still run by the hwaccel as the default profile.

That's a good idea!

**Comment by hooke007** [comment]
<s>Have you set the other changes? I do not know why lively try to change the hue, saturation etc....</s>
```
[   1.027][v][cplayer] Set property: hue="0" -> 1
[   1.027][v][ipc_1] Client disconnected
[   1.027][d][ipc_1] Exiting...
[   1.027][v][cplayer] Set property: saturation="0" -> 1
[   1.027][v][ipc_0] Client disconnected
[   1.027][d][ipc_0] Exiting...
[   1.027][v][cplayer] Set property: contrast="0" -> 1
[   1.027][v][ipc_3] Client disconnected
[   1.027][d][ipc_3] Exiting...
[   1.027][v][cplayer] Set property: brightness="0" -> 1
[   1.027][v][ipc_2] Client disconnected
[   1.027][d][ipc_2] Exiting...
[   1.027][v][cplayer] Set property: gamma="0" -> 1
```

Sry, I misunderstood the log message.

**Comment by rocksdanister** [comment]
Lively Properties Api
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction
You can write your own `LivelyProperties.json` file to create custom controls in `customize wallpaper` menu
![Screenshot 2021-02-07 212158](https://user-images.githubusercontent.com/17554161/107151799-87d1a980-698a-11eb-9c4f-1677cf9f93a4.png)
