### ISSUE TITLE
Glitching chrome, office program when Lively is running / 使用谷歌浏览器以及系统自带的浏览器和office2019系列应用会出现闪屏，已确认是此软件造成的

### ISSUE THREAD

**Issue by nanjimao** [rocksdanister/lively#295]
所有相关驱动系统版本全部是最新的

**Comment by rocksdanister** [comment]
Can you show a screenshot of the problem?

**Comment by nanjimao** [comment]
https://user-images.githubusercontent.com/78645687/107117843-feea3d80-68b7-11eb-820a-92a1399237a1.mp4

**Comment by rocksdanister** [comment]
Looks like a graphics card glitch?
Try the following:
1. Navigate to Lively settings folder (installer version.)
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\`
(Alternatively open Lively settings page and press the button to the right-side of Wallpaper Directory to open this folder.)
2. Create a file `mpv.conf`
3. Open the file with notepad add the following line: `hwdec=no`
4. Save the file and re-apply the wallpaper.
5. See if the problem remains?

**Comment by nanjimao** [comment]
还存在，然后我尝试截图，但是截出来的图是好的，我不能把问题截出来，只能录像

**Comment by rocksdanister** [comment]
Can you share taskmanager screenshot of `libMPVPlayer` with `GPU Engine` column shown:
![Untitled](https://user-images.githubusercontent.com/17554161/107118547-b4f95b80-68a7-11eb-8b3a-f4eaffe27c54.png)

**Comment by nanjimao** [comment]
这个吗?我看不到你发的图片，不理解什么是libMPVPlayer

---原始邮件---
发件人: "Dani John"<notifications@github.com&gt;
发送时间: 2021年2月6日(周六) 晚上8:49
收件人: "rocksdanister/lively"<lively@noreply.github.com&gt;;
抄送: "nanjimao"<2805444863@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [rocksdanister/lively] 使用谷歌浏览器以及系统自带的浏览器和office2019系列应用会出现闪屏，已确认是此软件造成的 (#295)




 
Can you share taskmanager screenshot of libMPVPlayer with GPU Engine column shown:

**Comment by rocksdanister** [comment]
Can you try the beta build:
https://github.com/rocksdanister/lively-beta/releases
