### ISSUE TITLE
Auto change wallpaper feature. and bing daily 

### ISSUE THREAD

**Issue by sfn101** [rocksdanister/lively#297]
First, your work is amazing But it will be better if we can shuffle between the wallpaper randomly after a sitting time.

And if we can get a Bing daily wallpaper It will be awesome. I don't think it is a hard task since it is HTML page but you need to take the search and the navigation away

**Comment by udaylunawat** [comment]
Maybe like a folder of wallpapers in the Library section which can shuffle after a certain time

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/137

Regarding bing, that is more of a custom wallpaper than Lively software feature.
You can design a scrapper program/webpage and retrieve the original image.
