### ISSUE TITLE
Video stuttering/choppiness

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#3]
Noticed micro stuttering/frame skipping(?) for some video files.

How to reproduce:
Playback of [jellyfish-3-mbps-hd-h264.mkv ](http://jell.yfish.us/) using Media Foundation/Mediakit.

Attempts to fix the issue:

- Made a separate binary build of videoplayer: **No Success.**
- Re-encoded the video file to x264 vbr 30/60fps: **No success.**
- Tried playing it using external mpv video player: **Success**
- Tried without adding the video window as workerw childwindow: **No Success.**
- Tried adding load to gpu to verify whether its downclocking issue: **No Success.**
- Tried turning off HW Accel for wpf: **No Success.**

I think this problem is due to some wpf feature like variable framerate?, needs further testing.

Looks like I was right lol, found this ancient article: https://rhnatiuk.wordpress.com/2008/12/21/wpf-video-playback-problems/

**Comment by TheBestPessimist** [comment]
Total brainfart here: would V-Sync help with fixing this?

**Comment by rocksdanister** [comment]
vsync is on; problem is wpf is varying the framerate(?), could not find any settings to fix the frame rate.
It should be possible to fix this somehow, this project is using wpf and it has no issue: https://github.com/stax76/mpv.net

**Comment by rocksdanister** [comment]
Switch to UWP mediaelement class in v1.0 using xaml island:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaelement?view=winrt-19041

**Comment by rocksdanister** [comment]
Has some difficulty implementing it, switching mpv library instead.
Problem seems to be resolved when using libmpv -  v1.0 release should resolve this.
