### ISSUE TITLE
Microsoft Edge flickering when Lively active

### ISSUE THREAD

**Issue by mlazzarotto** [rocksdanister/lively#300]
**Describe the bug**
When using Microsoft Edge with Lively active, Edge is flickering

**To Reproduce**
1. Install Lively
2. Enable the "Ripple" or "Triangles & Light" wallpaper
3. Open Edge
4. While hovering the mouse over a link or some object or writing with the keyboard, the flicker happens. It also happens if I left the mouse on a text box and the cursor is blinking.
5. As soon as I pause the wallpaper, the flicker stops

**Expected behavior**
No flicker

**Screenshots/Video**
I had to record the screen with my smartphone, because recording my screen within Windows wasn't showing the flicker.
`https://youtu.be/lx_ens8dlLk`

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- Which wallpaper: Ripple
- Edge version: 88.0.705.63
- Monitor MSI, 144hz, 1920x1080, FreeSync On

**Additional context**

**Log file**
Share the log file(s) from Local Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[20210210_090931.txt](https://github.com/rocksdanister/lively/files/5957007/20210210_090931.txt)

**Comment by rocksdanister** [comment]
Does it happen with FreeSync Off?

**Comment by mlazzarotto** [comment]
Yes, it does

**Comment by rocksdanister** [comment]
Can you try a [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) driver reinstall?

**Comment by mlazzarotto** [comment]
> Can you try a [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) driver reinstall?

I would prefer to not mess up with my graphic card driver.

**Comment by rocksdanister** [comment]
DDU is mostly used to clean existing driver installs, its widely used... I asked because this is likely a driver issue.
Lively does not make any system modification, both the web browser and video player is set to use hardware acceleration whenever possible so the likely culprit is driver/hardware related.

I'm closing this for now since there is not much I can do from my end at the moment.
