### ISSUE TITLE
Network not working temporarily when Wallpaper pause is disabled.

### ISSUE THREAD

**Issue by Ravencentric** [rocksdanister/lively#306]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki 
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
The bug seems to affect my internet connection (I use a TP-Link T4E network card and an ARCHER C60 router both working on 5Ghz) and I discovered it while playing games when Lively was running in the background and set to "DO NOTHING" while "APPLICATION FULLSCREEN". I pinned the bug down by using 1 app at a time and found it was only when Lively was active when my PC's connection would randomly drop for a second and this was so bad that I couldn't download a 4.7 MB app called Battle.net which is Blizzard's Client.

**To Reproduce**
Nothing, it just needs to be running in the background with the settings "DO NOTHING" while "APPLICATION FULLSCREEN".

**Expected behavior**
Internet (client-side) would drop for less than a second causing the browser to give "Download Failed-Network Error" (tried on 3 different browsers (Chrome, Edge, Opera GX) with a fresh install but the same error happened.

**Screenshots/Video**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 19042.804
- Lively Rain v2 (default settings)

**Logfile**
Share the log file(s) from Local Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
No such folder was present. Using the latest Lively from Microsoft Store

**Comment by rocksdanister** [comment]
Rain v2 requires decent system with gpu - in this case Likely putting the system under load causing trouble with talking to network.
The **recommended** default is to Pause wallpaper when Application Fullscreen.

Further read about performance:
https://github.com/rocksdanister/lively/wiki/Performance

**Comment by Ravencentric** [comment]
My system is more than capable of handling that plus it Lively is very well optimized using only 2% of my CPU and 4% of my GPU and <100MB of RAM, so I do believe its not my system  From: Dani JohnSent: 13 February 2021 03:51 AMTo: rocksdanister/livelyCc: Raventhicc; AuthorSubject: Re: [rocksdanister/lively] Lively interferes with my Internet connection and causes it to disconnect for small time period usually 1 second or less (#306) Rain v2 requires decent system with gpu - Likely putting the system under load causing trouble with talking to network.The recommended default is to Pause wallpaper when Application Fullscreen.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rocksdanister** [comment]
Still seeing how this only happens during game session with the wallpaper already running (fullscreen pause disabled.) I'm inclined to believe this is a system resource issue.. moreover the rain v2 is fully offline webpage and does not require network.
