### ISSUE TITLE
.Net Core required.

### ISSUE THREAD

**Issue by allwomansrqueens** [rocksdanister/lively#307]
so, once i opened it up, and it started saying I need the .net core app. so I downloaded it and contuined, when I opened it up again. it still said the exact same thing.

**Comment by rocksdanister** [comment]
The installer bundles with the correct runtime and should prompt during install.

Lively is a x86 app, so run time required is x86:
https://github.com/rocksdanister/lively/wiki/Common-Problems

If you still have trouble then use the store version of Lively.
