### ISSUE TITLE
Improve app updater (installer version.)

### ISSUE THREAD

**Issue by clicktodev** [rocksdanister/lively#308]
**Describe the solution you'd like**
I'm not sure if the program does this automatically because I just installed it today but there's no option to check and update directly from the settings. It would be great if this was possible since It's very convenient and we wouldn't have to manually install the updated package from github and this way we would get updates as soon as they're released through a notification displayed by Lively.

**Describe alternatives you've considered**
Another project called PowerToys on github has a feature like this and works quite well.
https://github.com/microsoft/PowerToys
This is the link to the project if you wanna to take a look at their implementation.

**Comment by rocksdanister** [comment]
Lively does support auto-update.
During startup after 45seconds Lively check github for update -> If update found you can access it through tray-menu/the update window will also auto open the next time Lively window is opened.
There is no manual button to check for update though.
![Screenshot 2021-02-13 065444](https://user-images.githubusercontent.com/17554161/107837768-8eb44e00-6dc8-11eb-8133-2addb056a16f.png)
![Screenshot 2021-02-13 065455](https://user-images.githubusercontent.com/17554161/107837774-9542c580-6dc8-11eb-82b1-b3f1e5e8715e.png)
![Screenshot 2021-02-13 065504](https://user-images.githubusercontent.com/17554161/107837779-9d9b0080-6dc8-11eb-9aef-4ce03dff4d2c.png)
![Screenshot 2021-02-13 065527](https://user-images.githubusercontent.com/17554161/107837782-9ffd5a80-6dc8-11eb-996d-0ae4292672d2.png)
![Screenshot 2021-02-13 065801](https://user-images.githubusercontent.com/17554161/107837833-d935ca80-6dc8-11eb-9dde-4d8aee90e15d.png)

**Comment by clicktodev** [comment]
Thank you! I can't believe I missed that. But adding the ability to manually check for updates would be great. For example If my computer is left running for multiple days and since Lively only checks once after It's launched then I won't receive the update notification unless I restart the program. Because what I understood from what you told me is that Lively only checks for updates once when It's launched and the only way to check again is by restarting the program.

**Comment by rocksdanister** [comment]
Yeah that is true, manual update checking and automatic periodic update checking would be useful.

**Comment by clicktodev** [comment]
Offtopic but can you please tell me what the Lite user interface changes exactly because I can't see any changes between Normal and Lite.

**Comment by rocksdanister** [comment]
1. Disables animated gif in Library, uses thumbnail picture instead.
2. During wallpaper import before screen capturing to create animated gif the already running wallpaper is quit based on wallpaper arrangement selected (all wallpapers are quit if duplicated/span, the currently selected screen wallpaper is quit if per-sceen.)
