### ISSUE TITLE
No pause on full screen with dual monitor

### ISSUE THREAD

**Issue by Syycorax** [rocksdanister/lively#310]
**Before proceeding**

**Describe the bug***
With dual monitor, and two apps on full screen, the non focused screen don't pause the animated wallpaper which can cause performance problems

**To Reproduce**
1. Set a wallpaper on two screens
2. open an app on full screen on both screen

**Expected behavior**
Both wallpapers stop

**Desktop (please complete the following information):**
- OS: Windows 10 pro 19041
- Fluids wallpaper 

**Additional context**
Requires tasbkarX with transparent taskbar mode to see

**Comment by rocksdanister** [comment]
Performance -> Display Pause Rule -> All Screen

**Comment by Syycorax** [comment]
Commenting because I think there should be a way to this without having to have a blank wallpaper while one screen is on desktop and the other on an app (don't know if I am understandable)

**Comment by rocksdanister** [comment]
This is working as intended for _Foreground_ pause algorithm as there can only be one program in the foreground at the same time.

_All process_ algorithm will address this when finished.

**Comment by Syycorax** [comment]
I in fact expected _Full screen_ pause algorithm to work as I described
