### ISSUE TITLE
Random Slideshow and/or Keyboard Shortcuts

### ISSUE THREAD

**Issue by d2produce** [rocksdanister/lively#315]
Right now there's no way to change the background other than to stop what ur doing and open lively wait for it to load cuz i got hundreds of live backgrounds and scroll through hundreds of backgrounds to finally select one.

Takes too long.

Need random background selection every X minutes the exact way windows has been doing it for years, I don't know why anyone would think because backgrounds are Live this feature shouldn't be needed?

Or some sort of Keyboard shortcut when the background is in the foreground to self change it to the next random selection.  I read something about "keyboard support" in the last update yet the Lively website has no mention of it nor does it provide a list of keys or functions not even in the Wiki.....?

So ya lots of work to be done, so far it's the best free program I could find, but without these 2 very important key features it's very lackluster and most of the time I just keep it off why waste my CPU power to stare at the same background that's been playing for 3 days because I don't have the time energy or willpower to go through all the steps it takes to change it?

**Comment by rocksdanister** [comment]
Your tone is very rude and entitled.. I don't owe you anything and honestly I didn't want to answer at all.
I will answer anyway..

>Need random background selection every X minutes

If you bothered checking properly - its been discussed https://github.com/rocksdanister/lively/issues/137

>the exact way windows has been doing it for years, I don't know why anyone would think because backgrounds are Live this feature shouldn't be needed?
>
Unnecessary comparisons aside, Lively only has one contributor

https://github.com/rocksdanister/lively/graphs/contributors

And I am doing this for free as a fun project.. and who said this feature is not needed? should I only release Lively once I satisfy all the features you need? features don't just get magically added If I just flip a button.

> "keyboard support" in the last update yet the Lively website has no mention of it nor does it provide a list of keys or functions not even in the Wiki.....?

The patch note, settings menu and release trailer are very clear what the keyboard input mode does and moreover the wiki does have examples of switching wallpaper using Autohotkey and command line controls.

>So ya lots of work to be done, so far it's the best free program I could find, but without these 2 very important key features it's very lackluster and most of the time I just keep it off why waste my CPU power to stare at the same background that's been playing for 3 days because I don't have the time energy or willpower to go through all the steps it takes to change it?

All the steps:
1. Open Lively
2. Click on a wallpaper

Honestly I prefer such entitled users don't use Lively.
