### ISSUE TITLE
Cannot set wallpaper with type "Web Audio Reactive"

### ISSUE THREAD

**Issue by ayatkyo** [rocksdanister/lively#32]
Currently i can't set wallpaper with type "Web Audio Reactive", set from Library (Fluids), from Lively .zip wallpaper (Fluids v2) or using wallpaper creation in "Type" tab -> Audio Visualizer -> HTML, still not working just show default windows wallpaper.

But drag html file or use "Type" tab -> Web -> HTML will show wallpaper creation dialog and i can set wallpaper, but without Audio Visualizer.

Trying both Installer and portable version, same problem.

Lively version: v0.9.5.0
Windows version: Windows 10 1909 10.0.18363

Here is log file, look like lively not find Cefsharp Handle.
[logfile.txt](https://github.com/rocksdanister/lively/files/4398794/logfile.txt)

**Comment by rocksdanister** [comment]
Does it work if you change the LivelyInfo.json file of Fluid's "type" to "1" & restart lively.

**Comment by ayatkyo** [comment]
Yes it work and type is change to Web instead of Web Audio Reactive, but it same as manual create html wallpaper, wallpaper not react to audio.

**Comment by rocksdanister** [comment]
Launch a web audio reactive wallpaper, exit lively.
Share the file: `Documents/Lively Wallpaper/external/cef/debug.log`

**Comment by ayatkyo** [comment]
Log Fluids v2 with type = 1
[debug.log](https://github.com/rocksdanister/lively/files/4400175/debug.log)

Log Fluid v2 with type = 2
no log in `Documents/Lively Wallpaper/external/cef/debug.log`

More info, if i set type = 1 (Web) in task manager show like this
![lively-web](https://user-images.githubusercontent.com/2143364/77864779-41d19280-725d-11ea-9bf0-be6fdc90c3b6.png)

but if i set type = 2 (Web Audio Reactive) task manager show this
![lively-web-audio](https://user-images.githubusercontent.com/2143364/77864793-5f066100-725d-11ea-9e84-6c0f8edb9481.png)
in detail :
- livelywpf (32 bit) process show
  - Lively
  - livelySubProcess (32 bit)
- Click set as wallpaper
- livelywpf (32 bit) process show
  - Lively
  - LivelyCefSharp (32 bit)
  - livelySubProcess (32 bit)
- then some seconds
  - Lively
  - LivelyCefSharp (32 bit)
  - livelySubProcess (32 bit)
  - Windows Problem Reporting
- then livelywpf (32 bit) process back to
  - Lively
  - livelySubProcess (32 bit)

look like `LivelyCefSharp (32 bit)` is crash

**Comment by rocksdanister** [comment]
Is it possible for you to try this sample cscore project with debugging:
https://github.com/filoe/cscore/tree/master/Samples/WinformsVisualization

**Comment by ayatkyo** [comment]
Sure, here screenshot with debugging
![cscore](https://user-images.githubusercontent.com/2143364/77896061-3eb0c380-72aa-11ea-941d-f6bd13fba5c9.png)

if i click "From Default Device", it stop there
![ss-error](https://user-images.githubusercontent.com/2143364/77896393-cac2eb00-72aa-11ea-8e02-bba0e46c3295.png)

**Comment by ayatkyo** [comment]
I think I found the problem, after following [this](https://github.com/filoe/cscore/issues/322#issuecomment-367269821) finally Web Audio Reactive can be set as wallpaper.

So to fix this problem :
- Open sound output properties
- Open **Advanced** tab
- In Signal Enhancements, uncheck **Enable audio enhancements**

Thanks for time, great app :)

**Comment by rocksdanister** [comment]
Thanks.
Added info on [wiki](https://github.com/rocksdanister/lively/wiki/Common-Problems)
Will add proper debugging for browser component in future update.
