### ISSUE TITLE
Command Prompt commands not working

### ISSUE THREAD

**Issue by iothemighty** [rocksdanister/lively#320]
**Describe the bug**
Tried using the open app command in command prompt, didn't work, even as administrator. 

**To Reproduce**
1. Go to Command prompt
2. type "livelywpf.exe app --showApp true" (w/o quotes)

**Expected behavior**
I expected the app to open
**Screenshots/Video**

![image](https://user-images.githubusercontent.com/58013861/108398639-3d042d00-71e7-11eb-8947-dff785414114.png)
![image](https://user-images.githubusercontent.com/58013861/108403781-1a751280-71ed-11eb-83b0-273999d5c311.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1909
- At the time I had stopped all Lively processes, doesn't work with them on either (just read that Lively is supposed to be running)

**Additional context**
I was attempting to do the wallpaper playlist thing, I just wanted to make sure that the commands work. I know you said you were working on it but I am too excited so I wanted to try my hand at it myself. I'm using the version from Windows Store btw. I also tried use PowerShell in administrator and used the file path of the livelywpf process in task manager

**Log file**
[logs.zip](https://github.com/rocksdanister/lively/files/6004943/logs.zip)
Please look at the one for today, 2/18/21.

I really love this app, this isn't really a dealbreaker at all, even if this didn't end up working I would still use the app, but if you could help me get this to work, that would be fantastic! Have a lovely/LIVELY day! 😉hahahahahahaaaaa.... I'll go away now lol.

**Comment by rocksdanister** [comment]
You need to enter the fullpath of the executable or ideally download the command utility and add it to PATH variable then call livelycu.exe from anywhere.

> I'm using the version from Windows Store btw. I also tried use PowerShell in administrator and used the file path of the livelywpf process in task manager

In one of the logfile I can see the `showApp --true` message was received, but it is part of `app` commands so it should be 
`app --showApp true`

Documentation:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls

Video tutorial:
https://www.youtube.com/watch?v=iEb5DVMz3Ds
