### ISSUE TITLE
Windows eventually freezing after a long period of usage.

### ISSUE THREAD

**Issue by miou-gh** [rocksdanister/lively#323]
**Describe the bug**
I started using Lively a few days ago, along with a friend of mine. We both have separate machines, but not long after using Lively his entire system froze for several minutes. It was very strange behaviour for him but eventually it resolved itself. A day later, I encountered the same thing and had to do a hard restart. Fast forward to now, I experienced system freezing every 2 seconds or so, but enough to move my mouse and try to see what was causing it.

I killed the Lively process and it continued to lag. I checked the status of every metric I could, very little disk activity, very little network activity, very little CPU and GPU usage. GPU temperature fine, plenty of free memory. Not a ton of page faults encountered, nothing unusual.

I did a quick search to see if anyone had the same issue, and this one gave me a thought.
![msedge_e9oFMA6bWd](https://user-images.githubusercontent.com/2405874/108680006-5218de80-74bb-11eb-87ba-b0962d0169df.png)

I had changed my desktop to a solid black colour yesterday, to minimize seeing a temporary picture of my previous wallpaper before Lively starts up. I changed back to an image desktop wallpaper and the lag went away immediately.

I think this is certainly a problem in Windows, and not Lively. But, it probably wouldn't hurt to avoid this problem altogether by giving a warning or something if they are using a solid color as their Windows desktop wallpaper. It is a tricky one to reproduce because it can take many, many hours for the problems to occur.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (19041.685)
- Wallpaper: A custom MP4.
CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
GPU: Radeon RX 580 Series
Display: 1920x1080

**Log file**
I checked the log files, nothing relevant to the issue at hand.

**Comment by rocksdanister** [comment]
Looks like Windows changed something recently, Lively used to refuse to work with solid colors in the past.
