### ISSUE TITLE
Loop Eternal light??

### ISSUE THREAD

**Issue by Dipanshu6** [rocksdanister/lively#324]
**Is your feature request related to a problem? Please describe.**
it is not actally a "problem" but i just find it frustrating that the eternal light wallpaper doesnt loop correctly and i see it switch frames every few seconds

**Describe the solution you'd like**
loop the wallpaper correctly i guess, or add a transitions or something to make it less infuriating?

**Describe alternatives you've considered**
if this is not possible from your side, then requesting the dev of the wallpaper or giving me the proper instructions/way to contact them

**Additional context**
i think none

**Comment by rocksdanister** [comment]
Rightclick the wallpaper tile -> About 
This should provide the author's information.
Do keep in mind the author is not affiliated with Lively so its best not to cause too much trouble.
