### ISSUE TITLE
Broken after windows explorer restarted

### ISSUE THREAD

**Issue by Dipanshu6** [rocksdanister/lively#327]
**Describe the bug**
my pc froze and the windows explorer restarted, and broke wallpapers closing wallpaper/changing it didnt work had to restart lively

**To Reproduce**
1. Open Taskmanager
2. find Windows Explorer
3. restart it
4. see wallpaper

**Expected behavior**
The wallpaper should not break or get fixed after changing it

**Screenshots/Video**
[

](url)

**Desktop (please complete the following information):**
 - OS: Windows 20h2
- Parrallax.js

**Additional context**

**Log file**
[20210223_103704.txt](https://github.com/rocksdanister/lively/files/6026965/20210223_103704.txt)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/203
