### ISSUE TITLE
Executables are incorrectly placed when having a monitor in portrait mode.

### ISSUE THREAD

**Issue by BasicallyWiz** [rocksdanister/lively#328]
**Describe the bug**
When you set a wallpaper to an exe while one of your monitors are in portrait mode, the new wallpaper on the non-portrait monitor is placed too high, and a large part of it is clipping off frame.

**To Reproduce**
1. Take a second monitor and set it to portrait mode in Windows' display settings.
2. Set an executable as your wallpaper. (In my case I'm trying to apply Sebastian Lague's atmosphere experiment.)
4. Wallpaper is placed to what seems the right size, but places the top of the wallpaper to where the top would be on the portrait monitor.

**Expected behavior**
The executable is placed in the correct position, and fills both monitors properly.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/48531736/108918172-cd76af00-75e5-11eb-9b70-98074cf4a354.png)
In this screenshot, it's also seen that the portrait monitor isn't completely filled, but I chalked that off to: aspect ratio limits baked into Unity.

**Desktop:**
 - OS: Windows 10 Enterprise  10.0.19041 Build 19041
- Exe wallpaper; exe obtainable at https://sebastian.itch.io/atmosphere-experiment

**Log file**
[20210223_133548.txt](https://github.com/rocksdanister/lively/files/6032215/20210223_133548.txt)

**Comment by rocksdanister** [comment]
This is not Lively specific bug, executables can have their own sizing and position code.. Lively is setting the position and size correctly.. its just the app is changing that itself afterwards.

In this unity game case it is set to go fullscreen mode, if you recompile it to show player dialog - things should work correctly.

Further read:
https://github.com/rocksdanister/lively/wiki/Application-Wallpaper
