### ISSUE TITLE
Some wallpaper using too much cpu

### ISSUE THREAD

**Issue by Dipanshu6** [rocksdanister/lively#329]
**Describe the bug**
opening a interactive wallpaer makes lively use a so much cpu .

**To Reproduce**
1. change wallpaer to a interactive/animated one
2. check cpu/gpu usage

**Expected behavior**
lively should not use like 50-70%% of the cpu 20% is enough

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/75921868/108953888-f05e9d00-7691-11eb-9b1e-9c3e2234f0ad.png)

**Desktop (please complete the following information):**
 - OS: windows 10 20h2 intel i3 1005g 10th gen   gpu- intel uhd integrated 
 -
- fluids v2/ 25th hour
.

**Log file**
[20210224_103156.txt](https://github.com/rocksdanister/lively/files/6033650/20210224_103156.txt)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance
