### ISSUE TITLE
Toolbar options

### ISSUE THREAD

**Issue by adfhsakfhas** [rocksdanister/lively#330]
What I believe is the toolbar, the thing with the windows icon cortana and time typically at the bottom of the screen. I have a video where the bottom of the screen is important but my toolbar blocks it and ik there are ways to solve this. But, I believe you can make options for the toolbar such as rainbow or something like that. I understand this would be a huge change and update to lively but I think it could really, if well advertised and executed, could really help make lively more customizable.

**Comment by rocksdanister** [comment]
There are other programs:
https://github.com/TranslucentTB/TranslucentTB
