### ISSUE TITLE
Control panel button needs to be larger to fit the translate text

### ISSUE THREAD

**Issue by westor7** [rocksdanister/lively#332]
Hello,

This button under https://github.com/rocksdanister/lively-translations/blob/master/v1.0/English/Resources.resx#L258-L260 needs to be a little more wide in order to fit the translation, i tried to find an alternative but i can't , if you can make it a little bit larger to fit right because now it cuts down some text.

Example Image:

![Image](https://i.imgur.com/FEFCHJu.png)

- Thanks!

**Comment by rocksdanister** [comment]
moved: https://github.com/rocksdanister/lively/issues/1227
