### ISSUE TITLE
Video wallpapers not working.

### ISSUE THREAD

**Issue by iBSHA** [rocksdanister/lively#335]
mp4 and eternal lights not working 

**To Reproduce**

1. Go to the plus icon 
2. Click on link or select file 
3. Scroll down to ok and press
4. See error wallpaper not working 

**Expected behavior**
i expected the eternal light not to works because my specs are kinda low but the mp4 files and yt links arent working too

 - OS: windows 10 (1909)

**Additional context**
mp4 , eternal light , and links not working i tried downloading the extra app but i cant find it in windows as the link said + i uninstalled msi afterburner and rtss

**Log file**
[20210223_123417.txt](https://github.com/rocksdanister/lively/files/6059840/20210223_123417.txt)
[20210224_225314.txt](https://github.com/rocksdanister/lively/files/6059841/20210224_225314.txt)
[20210227_173355.txt](https://github.com/rocksdanister/lively/files/6059842/20210227_173355.txt)
[20210228_094127.txt](https://github.com/rocksdanister/lively/files/6059843/20210228_094127.txt)
[20210228_100212.txt](https://github.com/rocksdanister/lively/files/6059844/20210228_100212.txt)
[20210301_103323.txt](https://github.com/rocksdanister/lively/files/6059845/20210301_103323.txt)

**Comment by rocksdanister** [comment]
Eternal light is mp4 video, so rest of the included wallpapers work?
On first look I don't see any particular errors in the log.

**Comment by iBSHA** [comment]
> Eternal light is mp4 video, so rest of the included wallpapers work?
> 
> On first look I don't see any particular errors in the log.

the rest works fine (the included ones)

**Comment by rocksdanister** [comment]
Strange, I am just using the official [mpv player](https://mpv.io/installation/) for video files.

Try turning off gpu acceleration:
1. Exit Lively from system-tray and then goto Lively data folder (one below the logs folder.)
2. Open Settings.json using notepad
3. Edit  `"VideoPlayerHwAccel": true,` to   `"VideoPlayerHwAccel": false,` and save.
4. Re-open Lively and try again.

**Comment by iBSHA** [comment]
still didn't work, i tried uninstalling and reinstalling but still

**Comment by rocksdanister** [comment]
Are you able to play the same video files using this player:
https://mpv.io/installation/

**Comment by iBSHA** [comment]
by the way i downloaded it from microsoft store

**Comment by iBSHA** [comment]
i downloaded it, opened CMD then said done 

do i need to do anything else to download the player because when i select open with i dont see the player

**Comment by iBSHA** [comment]
no, no i cant play my file with the MPV player if i dragged it.

**Comment by rocksdanister** [comment]
You can try looking at mpv player log by running it with this command (change the path of the video file to yours):
`.\mpv.exe .\test\mandel.mp4 --log-file="log.txt"`

**Comment by iBSHA** [comment]
so i can't actually fix the error ? or can i download another player ?

**Comment by rocksdanister** [comment]
Share the file, if its anything obvious I can take a look.
Otherwise you will have to make a bug report directly to mpv team:
https://github.com/mpv-player/mpv

**Comment by iBSHA** [comment]
i actually solved the eternal light problem by changing the players from mpv to the other one from lively setting , thank you kind sir for your help
