### ISSUE TITLE
Ripples refuses location and API  input

### ISSUE THREAD

**Issue by heavyoak** [rocksdanister/lively#336]
I was trying to set up ripples and it refused the api key from openweather and refused my city, country.

**Comment by rocksdanister** [comment]
The api key takes time to activate openweathermap server, try after sometime.

**Comment by apmfiit** [comment]
I added my city in this format :'Yakutsk, RU' and API Key. Pressed "Refresh". Nothing happened. Should I wait? I got my API Key just now from their website.

**Comment by rocksdanister** [comment]
> Should I wait?

Yes, try after a day or two.
