### ISSUE TITLE
"About" Wallpaper properties loses colon and port number if custom ports are used in URL.

### ISSUE THREAD

**Issue by JamminR** [rocksdanister/lively#338]
**Describe the bug**
"About" web wallpaper properties view removes colon and custom port numbers from display URL

**To Reproduce**
(Below instructions are using Windows 10 20H2)
1. Open Lively Wallpaper - Show
2. Click on '+ Add Wallpaper'
3. Enter URL that contains a colon ':' and custom port number e.g. 'http://blah**:80**'
4. Select OK.
5. Right-click Wallpaper tile in Lively Library and choose "About"

**Expected behavior**
Custom port numbers and colons should be in the displayed URL.
(This does not seem to affect the actual stored json URL - I checked and it still contains the 'correct' information)

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

Below image should be http://192.168.1.4**:32400**/......
![image](https://user-images.githubusercontent.com/3392170/110041079-bdf81400-7d11-11eb-841a-a4d442b0913d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2

**Additional context**
I'm attempting to have Plex Media Server "dashboard" display as a wallpaper, but not having any luck.
During my troubleshooting, I thought (and hoped) that the removal of the port Plex uses was the root issue, but I determined that the json keeps the proper URL and port. For now, found this 'about' display issue
Line wrap of long URLs would be nice feature too.

**Log file**
Share the log file(s) from Local Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[logs.zip](https://github.com/rocksdanister/lively/files/6087129/logs.zip)

**Comment by rocksdanister** [comment]
A very unusual use case.. I get surprised everyday with new things people try to do with Lively 😅

The logs show you drag'n'dropped the url:
https://github.com/rocksdanister/lively/blob/d13276da1e9ee8ea6b78c813d922021eb0320166/src/livelywpf/livelywpf/Views/Main/LibraryView.xaml.cs#L182-L202

The uri class sanitizes the input.

I think the problem is you are using remote desktop, Lively auto pauses wallpapers by default https://github.com/rocksdanister/lively/issues/277

If plex has a client app (.exe) its probably easier to just run it as app wallpaper.

**Comment by JamminR** [comment]
I've attempted both drag/drop and manual input (may not have included enough logs, apologies) - neither loaded. I'll try console access with both direct input and drag/drop and get a few new logs if it fails.
Plex has no other PC client application other than a playback app - the server itself runs as a background application, and 99+% settings/back-end actions (including dashboard) are browser based. 
Though I understand needing to clean input (never trust us end users to not accidentally or maliciously break things!), but not every web service uses standard ports.

**Comment by rocksdanister** [comment]
Can you show a screenshot of the web browser(wallpaper) error message?

**Comment by JamminR** [comment]
Ok. Tried again for about half hour today. Tried both 127.0.0.1 and 192.168.1.4 (ip of machine)
If preview is enabled while adding new wallpaper to library, the applications stops responding. I disabled preview before a restart and managed to get screenshot below during a 'preview' on real console before it locked up again. It's either this error, or a spin circle with the Plex grey/yellow dispersed background (visible somewhat in attached screenshot) 
![Lively_error2](https://user-images.githubusercontent.com/3392170/110228415-f42ec280-7ece-11eb-8ca8-e6eb33d64f36.PNG)
Now, even when local network is configured for admin with no authentication, the server is (apparently) reliant on being able to grab some source from plex.tv. When viewing in a 'real' browser, the page loads up with the URL I'm testing.
Lively 'stops responding', both figuratively, and literally according to Windows. I have to close the program to get any access.
New logs attached.
Let me know any/what other info you may want.
[logs.zip](https://github.com/rocksdanister/lively/files/6096523/logs.zip)

Though I know you won't be able to access my dashboard, I've included the current lively zip too.
[PlexDashboardLively.zip](https://github.com/rocksdanister/lively/files/6096527/PlexDashboardLively.zip)

**Comment by rocksdanister** [comment]
While not ideal.. You can try to use chrome as application wallpaper.
Create `LivelyInfo.json` file pointing to chrome executable with argument field telling chrome to load the page -> zip it then drag'n'drop to Lively library.

Example:
```json
{
  "AppVersion": "1.2.0.2",
  "Title": "title",
  "Thumbnail": null,
  "Preview": null,
  "Desc": null,
  "Author": null,
  "License": null,
  "Contact": null,
  "Type": 0,
  "FileName": "<Path to chrome>",
  "Arguments": null,
  "IsAbsolutePath": true
}
```

**Comment by JamminR** [comment]
For grins/giggles and more troubleshooting, added /plugins/LivelyCEFsharp.exe to win firewall pub and private allowed.

Also see this many times in Windows event application log at crash time.
```Log Name:      Application
Source:        Application Hang
Date:          3/6/2021 11:24:06 PM
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Vault
Description:
The program livelywpf.exe version 1.2.0.1 stopped interacting with Windows and was closed. To see if more information 
about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 11fc
 Start Time: 01d71309200d09d2
 Termination Time: 5
 Application Path: C:\Program Files (x86)\Lively Wallpaper\livelywpf.exe
 Report Id: 0d501e5e-49c4-40ac-9abf-05f083fea77e
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Cross-process

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-03-07T04:24:06.1197896Z" />
    <EventRecordID>3893</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Vault</Computer>
    <Security />
  </System>
  <EventData>
    <Data>livelywpf.exe</Data>
    <Data>1.2.0.1</Data>
    <Data>11fc</Data>
    <Data>01d71309200d09d2</Data>
    <Data>5</Data>
    <Data>C:\Program Files (x86)\Lively Wallpaper\livelywpf.exe</Data>
    <Data>0d501e5e-49c4-40ac-9abf-05f083fea77e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>Cross-process</Data>
    <Binary>430072006F00730073002D00700072006F00630065007300730000000000</Binary>
  </EventData>
</Event>```

I don't and won't install Chrome on machine.(sorry, anti-Chrome) 
I'll try Firefox.

**Comment by JamminR** [comment]
Giving up for today - (after midnight, early Sun morning, my time)
Attached are my current zip file with example json you provided filled in with Firefox instead of Chrome, and log of it trying to be input. Though it is in the Library GUI, Firefox opens directly in it's own window if I preview or set as wallpaper after getting this pop-up. (Firefox DOES open the dashboard though, so that's good :P )
(Log
 of this occurring attached)
Error pop.
![image](https://user-images.githubusercontent.com/3392170/110230085-6e197880-7edc-11eb-995f-01cbfda82d49.png)

Log (Yes, i'm trying this rdp again - standing at the rack in the closet isn't comfortable - the wallpapers you include work remotely)
[20210307_002701.txt](https://github.com/rocksdanister/lively/files/6096596/20210307_002701.txt)

**Comment by rocksdanister** [comment]
Working chrome example:
```json
{
  "AppVersion": "1.2.0.2",
  "Title": "title",
  "Thumbnail": null,
  "Preview": null,
  "Desc": null,
  "Author": null,
  "License": null,
  "Contact": null,
  "Type": 0,
  "FileName": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
  "Arguments": " --incognito --kiosk --no-default-browser-check https://www.google.com/",
  "IsAbsolutePath": true
}
```

**Comment by JamminR** [comment]
Thanks for all the assistance - I've decided to discontinue current aim of using Plex dashboard as wallpaper (after wallpaper, i was actually aiming for screensaver from lock screen). The 'server' is in a closet that I rarely physically access the hardware - just thought Plex info on screen would be a quick/nice idea until i realized Tautulli remote is quicker.

I'm leaving this original UI bug open (removal of :port# in property display). 
I may post another bug that when running firefox as application, errors/popup/separate app open as indicated [here](https://github.com/rocksdanister/lively/issues/338#issuecomment-792221126) occur, even when on console login directly.
