### ISSUE TITLE
No input on screen savers (.exe)

### ISSUE THREAD

**Issue by 1n23** [rocksdanister/lively#339]
I know it is possible to have input in screen savers (demonstrated in the Nintendo Screen saver).
I would really appreciate a fix.
Thanks.

**Comment by rocksdanister** [comment]
I don't think there is a good way to do this, currently I am only checking for mouse movement to cancel screensaver mode.
Application screensavers can have their own implementation but there is no way for me to check what it is from my side (Lively is more like a screensaver manager than screensaver itself so I can't control what other apps decide to do.)
