### ISSUE TITLE
Is it possible to support M3U8 livestream?

### ISSUE THREAD

**Issue by xinmingliunicky** [rocksdanister/lively#341]
**Is your feature request related to a problem? Please describe.**
The program is working great with YouTube videos, yet I believe setting a m3u8 livestream as wallpaper is not currently supported.

**Describe the solution you'd like**
I enjoy watching live cams from around the world where those streams are usually in m3u8 format. I think it would be great if Lively could support it.

**Describe alternatives you've considered**
I am enjoying the Plash app on macOS which support m3u8 wallpapers perfectly. Interactions with the wallpaper can be disabled to avoid pausing the playback, and there is also a global hotkey available for me to refresh the livestream whenever it gets stuck. I do hope Lively could be the alternative for Windows. Thank you!

**Comment by rocksdanister** [comment]
Create `LivelyInfo.json` file, change the FileName with the m3u8 link:
```json
{
  "AppVersion": "1.2.0.2",
  "Title": "title",
  "Thumbnail": null,
  "Preview": null,
  "Desc": "desc",
  "Author": "unknown",
  "License": null,
  "Contact": "https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8",
  "Type": 10,
  "FileName": "https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8",
  "Arguments": null,
  "IsAbsolutePath": false
}
```

Create a zip archive with the file in root location, drag'n'drop the zip file into Lively.

Sample:
[m3u8_test.zip](https://github.com/rocksdanister/lively/files/6096521/m3u8_test.zip)

**Comment by xinmingliunicky** [comment]
> Create `LivelyInfo.json` file, change the FileName with the m3u8 link:
> 
> ```json
> {
>   "AppVersion": "1.2.0.2",
>   "Title": "title",
>   "Thumbnail": null,
>   "Preview": null,
>   "Desc": "desc",
>   "Author": "unknown",
>   "License": null,
>   "Contact": "https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8",
>   "Type": 10,
>   "FileName": "https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8",
>   "Arguments": null,
>   "IsAbsolutePath": false
> }
> ```
> 
> Create a zip archive with the file in root location, drag'n'drop the zip file into Lively.
> 
> Sample:
> [m3u8_test.zip](https://github.com/rocksdanister/lively/files/6096521/m3u8_test.zip)

Working great! Thank you!

**Comment by xinmingliunicky** [comment]
I think this solution is not working with the latest version, even though I have modified the "AppVersion" in LivelyInfo.json. When I drop the zip archive into Lively it says "No lively wallpaper file".

**Comment by rocksdanister** [comment]
The LivelyInfo.json file needs to be in the root directory of the zip.

**Comment by cbxk1xg** [comment]
I wanted to use a URL with a **m3u8** as well. I can't drag and drop the zip file. Is this a bug?
