### ISSUE TITLE
Improvement to inno setup installer

### ISSUE THREAD

**Issue by shawnwick** [rocksdanister/lively#346]
Just a thought for you, but you can install the redistributables silently like this in inno setup, so when you install no one will have to click next on those. 

Filename: {app}\PLX\InstallStuff\Prerequisite\vcredist_2019_x64.exe; Parameters: /quiet /norestart; Flags: runascurrentuser runhidden;

Also add some nice pictures to the wizard instead of the default computer icon:

WizardImageFile=C:\Install_Setup\installer1.bmp
WizardSmallImageFile=C:\Install_Setup\installer2.bmp

**Comment by rocksdanister** [comment]
Good idea, few doubts:
1. This guide shows the following parameters:
`VC_redist.x86.exe /install /quiet /norestart`
is `/install` required?
https://silentinstallhq.com/visual-c-redistributable-silent-install-master-list/
2. Regarding `runhidden` inno flag - when I tried without it, everything worked fine, Is it required when `/quiet` is present?
3. Looks like welcomepage by default is no longer shown so WizardImageFile won't be visible unless `DisableWelcomePage=no` is set
https://jrsoftware.org/files/is5.5-whatsnew.htm#5.5.7

**Comment by rocksdanister** [comment]
Decided to just use Parameters `/install /quiet /norestart` without any inno Flags for both .netcore and visual c++ setups, on my testing things worked fine.

Enabled welcome page and added art.
