### ISSUE TITLE
Wallpaper not setting anymore

### ISSUE THREAD

**Issue by Jak2k** [rocksdanister/lively#349]
It was working. Now not.
![image](https://user-images.githubusercontent.com/76660118/110964394-6da53580-8353-11eb-9ad1-14abcdb1c761.png)

**Comment by rocksdanister** [comment]
Share the logfile:
https://github.com/rocksdanister/lively/wiki/Common-Problems

**Comment by Jak2k** [comment]
It's able to reproduce. I have it ver often. I think it's a windows error.
