### ISSUE TITLE
Keyboard interaction

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#35]
Keybord input support, similar to mouse interaction: https://github.com/rocksdanister/lively/issues/30
Warning will be shown before enabling this feature.

**Comment by ghost** [comment]
how can i enable keyboard interaction in lively release v1.0.7.0?

(pls help)

**Comment by rocksdanister** [comment]
Its not implemented, this issue is still open.

**Comment by ghost** [comment]
ok np

**Comment by ViratX** [comment]
I use Google Spreadsheets (using shared link; so no login required) as my wallpaper to track my daily progress. Doing keyboard input through the "Preview Wallpaper" option every time is very cumbersome. How can I enable keyboard interaction directly on the applied wallpaper.

**Comment by rocksdanister** [comment]
No code is written currently, so unfortunately no way to enable it from users side.

**Comment by rocksdanister** [comment]
https://user-images.githubusercontent.com/17554161/104942567-a15e8180-59da-11eb-9dab-44d95a360994.mp4

Keyboard input test.
