### ISSUE TITLE
Lock screen static picture wallpaper

### ISSUE THREAD

**Issue by dreaddr** [rocksdanister/lively#354]
**Is your feature request related to a problem? Please describe.**
This app is amazing, but other competing Wallpaper apps are able to change the Lock Screen wallpaper as well, so that it is seamless, and I do miss the automatic switching that occurs when a wallpaper is selected.

**Describe the solution you'd like**
I do know that there are restrictions in the lock screen area of Windows (#269) and would be unable to show a live wallpaper feed, however what can be done is an active frame (one frame) of the current live wallpaper can be set as a lock screen wallpaper instead. Basically, it will take one frame from the active wallpaper on the desktop and set it as the lock screen wallpaper.

**Describe alternatives you've considered**
Right now, I manually take a frame and change the lock screen to it, I believe the app can do a much better job at this automatically. 

**Additional context**
I can't seem to get a screenshot from within the lock screen but if it is possible in some way, I'll be sure to attach one.

**Comment by rocksdanister** [comment]
Without resolving https://github.com/rocksdanister/lively/issues/150 this won't be possible.

**Comment by dreaddr** [comment]
Oh I see it's already being worked on for the desktop wallpaper, then the lock screen one won't be far off if that works out I assume.

**Comment by rocksdanister** [comment]
@dreaddr 😇

https://user-images.githubusercontent.com/17554161/116691372-5a6c2900-a9d8-11eb-83c3-627f7b704677.mp4

**Comment by dreaddr** [comment]
Oh, hell yeah.

**Comment by bathtimethiago** [comment]
I downloaded it from the microsoft store but I didn't get the lock screen option

**Comment by rocksdanister** [comment]
Its removed for the time being due to https://github.com/rocksdanister/lively/issues/537
