### ISSUE TITLE
Different resolution multiple monitors screen saver not working correctly.

### ISSUE THREAD

**Issue by Ucef27** [rocksdanister/lively#357]
Hi,

I have a 1440p monitor (the middle monitor) and 2 1080p monitors. Lively wallpaper works fine but when I turn on the screen saver the 2 1080p monitors screen savers do not line up. Is this an issue on my end?

OS Build: 19042.867

Thanks in advance.

![Scree saver](https://user-images.githubusercontent.com/51302795/111401397-9c971080-869f-11eb-93b1-93cc32473cf4.png)

Log:
[lively_log_20210316_214302.zip](https://github.com/rocksdanister/lively/files/6153138/lively_log_20210316_214302.zip)

**Comment by rocksdanister** [comment]
1. Is any of the display scaling higher than 100%?
2. Can you try to recreate this bug using 2 displays and describes the steps so that I can try myself 
(I only have 2 displays with me.)

**Comment by Ucef27** [comment]
1. Yes, the middle monitor is at the recommended 125% scale.
2. If you change the scale of one of the monitors to 125% scale you should get the same result.
Also it seems that if I make the displays the same scale as the middle monitor it works properly (I don't want to do this though because everything is either to small or to big).

Thanks for your quick response.

**Comment by rocksdanister** [comment]
With two monitors I have a similar setup, not happening for me :/
(Make sure you restart Lively before testing with 2 monitors.)

**Comment by Ucef27** [comment]
I did restart lively and have the same issue. Did you change the scale?

![screen save 2 monitors](https://user-images.githubusercontent.com/51302795/111480205-1a8f0200-8708-11eb-9f40-8787f3320104.png)

**Comment by rocksdanister** [comment]
>Did you change the scale

Yes, so far I can't recreate this error.

Does the same issue happen when you try `screensaver --show true` using commandline control:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#screen-saver

**Comment by Ucef27** [comment]
Yes, the same issue does occur with the command line. I have also tried upscaling one of the wallpapers on the 100% scale monitor and still no luck.

**Comment by thadude3** [comment]
I am seeing this issue also, however it only happens after restarting my computer. I am able to work around it by re selecting a different wallpaper. Then its fine until I reboot again.

Steps to Reproduce
1440p monitor 125% scale (Primary display)
1080p monitor 100% scale (Secondary display)
Reboot computer with lively set to auto start.

**Comment by Ucef27** [comment]
When you say re-select, what exactly do you do, and is it for both monitors or just 1080p one?

**Comment by thadude3** [comment]
> When you say re-select, what exactly do you do, and is it for both monitors or just 1080p one?

To workaround it,  I change the background to something else. If I go back to the original background it works as expected. It only happens on the 1440p monitor, the one that’s scaled

**Comment by thadude3** [comment]
to add to this, I just saw it randomly after my screen was off for a bit.

I noticed this in the logs which is probably wrong.
2021-05-03 19:38:23.2639|INFO|livelywpf.SetupDesktop|System parameters changed: Screen Event=>
2021-05-03 19:38:23.2639|INFO|livelywpf.SetupDesktop|\\.\DISPLAY1 {X=2560,Y=0,Width=1920,Height=1080}
2021-05-03 19:38:23.2639|INFO|livelywpf.SetupDesktop|\\.\DISPLAY2 {X=0,Y=0,Width=2560,Height=1440}

I have attached the full logs and a sceenshot. Also this time my second monitor is displaying the original wallpaper.
[20210503_145520.txt](https://github.com/rocksdanister/lively/files/6418383/20210503_145520.txt)
![example](https://user-images.githubusercontent.com/5332378/116946512-49295380-ac48-11eb-9319-ab225350fadd.jpg)
