### ISSUE TITLE
Webpage wallpapers not working

### ISSUE THREAD

**Issue by jeasing** [rocksdanister/lively#358]
I'm having this problem in which some default live wallpapers are unable to select. And I attach a screenshot with my logs file for what went wrong. Thanks for any response.
![image](https://user-images.githubusercontent.com/46968759/111407074-6e5d1380-8727-11eb-9a2c-445336de4172.png)
[lively_log_20210317_134521.zip](https://github.com/rocksdanister/lively/files/6153401/lively_log_20210317_134521.zip)

**Comment by rocksdanister** [comment]
Most likely your third party antivirus software deleted some of the Lively files (web browser) based on heuristics/behavior
```
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at livelywpf.Core.WebProcess.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebProcess.cs:line 207
```
I only verify with windows defender and malwarebytes.

**Comment by jeasing** [comment]
Then what should I do then? I've tried to re-install and add exceptions to antivirus software, yet still not working.

**Comment by rocksdanister** [comment]
I don't know how antivirus software works.. did you try re-installing with av software turned off?

Many third party av software are very aggressive and this results in false positives; I recommend not using them to be honest.. stick to windows defender that comes with windows.

If you still wish to use then make a false report claim to the AV vendor:
https://www.autohotkey.com/boards/viewtopic.php?t=62266
