### ISSUE TITLE
Can't set wallpapers the only one that i can is the Eternal Light

### ISSUE THREAD

**Issue by Sanpaguar** [rocksdanister/lively#359]
When i entered my api key in the costumize options of the wallpaper "Ripples" my lively started senting a error pop-up everytime i try to set a wallpaper. But for some really odd reason only the wallpaper "Eternal Light" works. I tried to dowload isual C++ Redistributable but it still doesn't work, i also tried to dowload media fetuare pack but it also doesn't work. Here is a screenshot of the error. Also I have my logs attached to this post.
[lively_log_20210317_093115.zip](https://github.com/rocksdanister/lively/files/6155355/lively_log_20210317_093115.zip)
 Well... sorry if my english isn't that good. Thanks in advance!

**Comment by rocksdanister** [comment]
```
 O sistema não conseguiu localizar o ficheiro especificado.
```
File not found, something deleted Lively files.

Likely duplicate: https://github.com/rocksdanister/lively/issues/358

**Comment by Sanpaguar** [comment]
oh I checked my antivuris and the file was there. Thank you so much! It works now.
