### ISSUE TITLE
When computer powers on, Lively does not automatically put my wallpaper up / DeviceId: DISPLAY#REMOTEDISPLAY#

### ISSUE THREAD

**Issue by aaronshahriari** [rocksdanister/lively#360]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
I have the start with windows checked, so I assumed that it would automatically change my background to the Lively one. But it is not doing that and I have to manually click the wallpaper I want every time I turn on my computer.

**To Reproduce**
1. Go to 'Setting'
2. Click on 'General'
3. Scroll down to 'Start with Windows'
4. See that it is checked, but will not make that wallpaper when I start up my computer.

**Expected behavior**
I expect to start my computer up and have the live wallpaper automatically up.

**Screenshots/Video**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
- I have the rain wallpaper on, but when I start up my computer some random old one appears.

**Additional context**

**Log file (Important)**
[lively_log_20210317_163704.zip](https://github.com/rocksdanister/lively/files/6159561/lively_log_20210317_163704.zip)

**Comment by rocksdanister** [comment]
1. Is Lively starting by itself when system is restarted / Is the Lively icon visible in system-tray?
2. One of the Lively config files got corrupted: 
  `Core: Failed to restore wallpaper=>System.ArgumentNullException: Value cannot be null. (Parameter 'json null/corrupt')`
  This usually means something went wrong and Lively did not close properly, did you run any Windows optimization scripts or 
  software that may have modified the Windows shutdown wait timeout to 0.
3. One of the display id is `DISPLAY#REMOTEDISPLAY` which is strange, is there anything unusual about your desktop hardware setup? if so can you describe it.

**Comment by aaronshahriari** [comment]
No I have not run anything. It does show up in the tray it just does not automatically make my screensaver the one I chose. what should I do? Any ideas?

**Comment by rocksdanister** [comment]
3. One of the display id is DISPLAY#REMOTEDISPLAY which is strange, is there anything unusual about your desktop hardware setup? if so can you describe it.

If trayicon is visible then Lively did start but something went bad - either monitor is not identifiable anymore or the files got corrupt.
