### ISSUE TITLE
Lively will not attempt an install for Windows Server 2019 1809 (LTSC)

### ISSUE THREAD

**Issue by mr-gr1mm** [rocksdanister/lively#361]
Hey - this might be a long shot, but wanted to float it up anyway since there probably aren't many users attempting to install this app on a server OS. I have been looking for a wallpaper app just like this and was excited to install this on my machine, which is running Windows Server 2019 1809 (LTSC) for "reasons". Anyway the installer just bails out with the following message: "This program does not support the version of Windows your computer is running". I feel that this is likely just a canned message meaning: "I checked registry for X and saw Y", and not necessarily a true compatibility issue. From my experience, 99.99% of the programs designed for desktop Windows 10 are compatible with this OS - so I would appreciate it if you could dig in and see if would be possible to run this on a machine like mine. FYI - I did see the install notes about earlier versions of Windows being compatible with the app store version - however the app store download does not work on my machine (possibly by design, I am not 100% sure), but clicking the "get" button there does nothing - which is normal behavior from my experience on this setup. I've attached a screenshot of my system details if that helps - let me know if there is anything else I can do to help out!

![image](https://user-images.githubusercontent.com/56169215/111555887-b566fb00-875f-11eb-995e-375f2563fb42.png)

-Cheers

**Comment by rocksdanister** [comment]
Installer version of Lively is using some of the latest Windows 10 features and therefore require 1903 or above.
You could try installing the store msix file [directly.](https://store.rg-adguard.net/)
If that does not work, there is no easy way to do this.

**Comment by B1kku** [comment]
Just for the record I can confirm using the microsoft store version works on Windows 10 LTSC 1809, worked for me directly from the store.
![imagen](https://user-images.githubusercontent.com/77858854/118373801-effedf80-b5b8-11eb-9a8e-cec2c1b41a8c.png)

**Comment by rocksdanister** [comment]
Can you check if latest beta is working in 1809:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.9.4.6

**Comment by B1kku** [comment]
Just tried it, it opens on the background and shows up on the system tray, however I was not able to get it open, tried installing for both user only and system-wide, also tried opening as administrator and got some weird issues.

![lively](https://user-images.githubusercontent.com/77858854/158850597-50a21046-80a1-469a-8e6b-f038ae9d0aee.png)

**Comment by rocksdanister** [comment]
Admin mode is not supported by WindowsAppSDK currently https://github.com/rocksdanister/lively/issues/1060#issuecomment-1045055080 so UI won't work.

That access denied exception is probably because you started as Admin and now trying to communicate to it as non-admin user :
https://github.com/rocksdanister/lively/blob/f967e6e6712b122f61703a820769e22859aae715/src/Lively/Lively/App.xaml.cs#L64-L75

What error message did you get before running as admin and trying to open from traymenu?

**Comment by B1kku** [comment]
I did not getting any error when not running as admin, it simply didn't open at all.

**Comment by rocksdanister** [comment]
@B1kku Can you check for update for windows store version? 
I just pushed 2.0 with 1809 support to store.. tested working on my virtual machine using powershell install.
~(Reading the docs looks like WinUI 3 Unpackaged (installer) will require Windows 10 1909 minimum.)~

**Comment by rocksdanister** [comment]
**Powershell install instructions for v1.0.106 (if you don't have store or package manger)**

Download from https://store.rg-adguard.net/ the following packages:
`Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x86__8wekyb3d8bbwe.Appx`
`Microsoft.WindowsAppRuntime.1.0_1.440.209.0_x86__8wekyb3d8bbwe.Msix`
`Lively.UI.WinUI_1.0.106.0_x86.msixbundle`

Install the packages using powershell in this order:
`Add-AppxPackage -Path .\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x86__8wekyb3d8bbwe.Appx`
`Add-AppxPackage -Path .\Microsoft.WindowsAppRuntime.1.0_1.440.209.0_x86__8wekyb3d8bbwe.Msix`
`Add-AppxPackage -Path .\12030rocksdanister.LivelyWallpaper_2022.318.435.0_neutral___97hta09mmv6hy.Msixbundle`

**Comment by B1kku** [comment]
Version 2.0 store is working fine for me on 1809, installed directly from the store, not with powershell.
![image](https://user-images.githubusercontent.com/77858854/159061527-ce70462e-1c57-48d0-a954-fc797a9ad5ae.png)
