### ISSUE TITLE
Crashed again?

### ISSUE THREAD

**Issue by unforgiving85** [rocksdanister/lively#364]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
[lively_log_20210318_152454.zip](https://github.com/rocksdanister/lively/files/6164807/lively_log_20210318_152454.zip)

and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Please don't open new issues for the same problem, comment in the original https://github.com/rocksdanister/lively/issues/362 instead.
