### ISSUE TITLE
The wallpaper is crushed

### ISSUE THREAD

**Issue by alexspeed8888** [rocksdanister/lively#366]
The wallpaper is crushed when using diferent aspect ratios.
I have a 5/4 monitor (1024*1080) and all 16/9 and 19/10 wallpapers suck ass when I try to put them on my screen.
I would like and option to cut the extra width so it looks good.
Please don't just add black bars up and down.

**Comment by rocksdanister** [comment]
Change the scaling settings:
`Lively Settings -> Wallpaper -> Choose a fit`

**Comment by alexspeed8888** [comment]
Thanks!
