### ISSUE TITLE
Fluids v2 wallpaper not working.

### ISSUE THREAD

**Issue by contiii** [rocksdanister/lively#367]
The wallpaper doesn't work like the other wallpaper preinstallated

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
1. Describe the problem in detail
2. Share logfile `Open Lively settings (Gear icon) -> Misc. -> Log File`
