### ISSUE TITLE
slight blink on mp4 loops

### ISSUE THREAD

**Issue by jpetermans** [rocksdanister/lively#37]
When I use any mp4 file, it has a slight blink when the video loops. I've converted the same mp4s to gif and the blink goes away, so it seems to be related to mp4 files.  Codec is H.264/MPEG-4 AVC on all these files.

**Comment by rocksdanister** [comment]
Switch to Mediakit for seamless loop: https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by jpetermans** [comment]
Switching to LAV did the trick. Too bad the built-in media foundation doesn't work. Thanks for the help.
