### ISSUE TITLE
Webpage wallpapers not working

### ISSUE THREAD

**Issue by ethanwins** [rocksdanister/lively#372]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs
[20210319_190110.txt](https://github.com/rocksdanister/lively/files/6174561/20210319_190110.txt)
[20210319_190110.txt](https://github.com/rocksdanister/lively/files/6174563/20210319_190110.txt)

`

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/358
