### ISSUE TITLE
sync wallpaper settings across monitors

### ISSUE THREAD

**Issue by Armin2208** [rocksdanister/lively#373]
I use the Rain V2 wallpaper and I fine tuned some settings. Sometimes I use only one monitor and sometimes I use both. Sadly all my customizations are only applied for one monitor. The second still has the default settings. I can't apply my settings to the other monitor. I've enabled "duplicate same wallpaper".

Spanning one wallpaper across screens works, but for some wallpaper it would be better to have them duplicatet but with same settings.

A better multi monitor implementation in lively wallpapers would be nice :)

thanks.

**Comment by rocksdanister** [comment]
Each screen has its own [Lively Properties](https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#lively-properties)

Currently https://github.com/rocksdanister/lively/issues/264 is an issue with duplicate mode.

So workaround would be to set the wallpaper on the 2nd screen in per-screen mode and customize it.

Will be resolved along with original issue.

**Comment by rocksdanister** [comment]
Beta build is up with this feature:
https://github.com/rocksdanister/lively-beta/releases
