### ISSUE TITLE
Insufficient system resources

### ISSUE THREAD

**Issue by liam8000** [rocksdanister/lively#377]
[lively_log_20210320_163721.zip](https://github.com/rocksdanister/lively/files/6176020/lively_log_20210320_163721.zip)

**Comment by liam8000** [comment]
When i open the app and click on a wallpaper i want it comes up with an oops message something has gone wrong...
Ive had lively for a good while now and everything has been fine up untill this new recent update. 
Upon further testing it is happening on every wallpaper i click except for the Eternal Light wallpaper which is working absolutely fine.. 
Any advice would be appreciated.

**Comment by rocksdanister** [comment]
```
System.ComponentModel.Win32Exception (1450): Insufficient system resources exist to complete the requested service.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at livelywpf.Core.WebProcess.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebProcess.cs:line 207
```

1. What's your ram and pagefile size?
2. Have you tried restarting windows?
3. Have you tried reinstalling Lively?

**Comment by liam8000** [comment]
my ram is 16 gb ddr4 corsair (dont know how to know my pagefile size)
i have tried restarting windows 
i also have unistalled and re installed lively to see if that works...no luck :( 
i am running most recent version of windows 10. 
it has never been a problem before new update 1.2.04...all wallpapers worked flawlessly.

**Comment by evgenyYE** [comment]
Same problem. Also, my antivirus (McAfee) puts "LivelyCefSharp.exe" into quarantine. And somehow I cannot restore it from quarantine even with the administrator permissions.
1) 16gb ram
2) I restarted the windows several times.
3) Reinstalled the Lively, also several times.

[lively_log_20210320_204528.zip](https://github.com/rocksdanister/lively/files/6176223/lively_log_20210320_204528.zip)
![Anti virus report2](https://user-images.githubusercontent.com/72341690/111882618-2bb56880-89bf-11eb-93fa-7cc27366b734.JPG)
![Error msg](https://user-images.githubusercontent.com/72341690/111882622-2c4dff00-89bf-11eb-9ede-c55f50ada78b.JPG)
![Anti virus report](https://user-images.githubusercontent.com/72341690/111882624-2ce69580-89bf-11eb-8191-c36cde418458.JPG)

**Comment by rocksdanister** [comment]
@evgenyYE Your issue is different https://github.com/rocksdanister/lively/issues/358

**Comment by liam8000** [comment]
Mine av also does this (mcafee) 
The pictures @evgenyYE  posted are identical to what was happening on my pc

**Comment by rocksdanister** [comment]
That makes sense.. I did come across articles about mcafee causing insuffient memory error:
https://stackoverflow.com/questions/49772938/insufficient-system-resources-exist-to-complete-the-requested-service-visual-stu
https://appuals.com/fix-insufficient-system-resources-exist-to-complete-the-requested-service/

I am closing this as duplicate https://github.com/rocksdanister/lively/issues/358
