### ISSUE TITLE
Wallpaper turns black while "pause" when window maximized 

### ISSUE THREAD

**Issue by StrikeSNC** [rocksdanister/lively#38]
As title, Can I make the wallpaper being static instead?

**Comment by rocksdanister** [comment]
Its a current limitation of web type wallpapers: https://github.com/rocksdanister/lively/issues/20

**Comment by StrikeSNC** [comment]
![image](https://user-images.githubusercontent.com/40461728/78635658-50611f00-78d9-11ea-9233-c2c7ea6c6ef9.png)
Thanks for quick reply, but it's also have a high GPU usage, it is because I am using a intergrated GPU?

**Comment by rocksdanister** [comment]
System usage depends on the wallpaper, some of the ones I included are all shaders based so fully running on gpu.

Taskmanager usage can be misleading: https://github.com/rocksdanister/lively/wiki/Performance
If you have igpu and dgpu, then make sure to set dgpu for cefsharp: https://github.com/rocksdanister/lively/wiki/Common-Problems

Also the default foreground algorithm is based on foreground app size.
