### ISSUE TITLE
When switching wallpaper foreground application focus is changed

### ISSUE THREAD

**Issue by Ucef27** [rocksdanister/lively#380]
**Describe the bug**
I have an auto hotkey that switches my mp4 wallpaper when I press ctrl + z. When I do this in a game running at full screen, it alt-tabs me out of the game.

**To Reproduce**
1. Create an autohotkey script to switch between mp4 wallpapers.
2. Open up a game in fullscreen
3. Use the hotkey

I expect for the game not to alt-tab me out and to just change the wallpaper. 

**Desktop (please complete the following information):**
OS: 19042.867

**Log file (Important)**
[lively_log_20210321_205124.zip](https://github.com/rocksdanister/lively/files/6178757/lively_log_20210321_205124.zip)

**Comment by snoowfall** [comment]
CTRL-Z is a hotkey in Windows, it means 'undo'.
You should try to change the hotkey to something like CTRL-J, or CTRL-Alt-E.

That should do the job. Please inform us if the issue persists.

**Comment by rocksdanister** [comment]
When a new application(wallpaper plugin) is started in Windows it steals focus by default, there is no way to change this behavior in c# process class.

Will require writing win32 wrapper functions to achieve this effect.. have to wait for the time being.

**Edit: This is resolved in latest version.**

**Comment by Ucef27** [comment]
Thank you for your help. Also ctrl + j didn't work either.
