### ISSUE TITLE
Desktop icons hidden when keyboard input enabled.

### ISSUE THREAD

**Issue by Kenji09** [rocksdanister/lively#381]
The Display App doesn't show in my desktop I even restart my PC to see if the bug will be fix and it didn't.

1. Lively Wallpaper 
2. Click on a live wallpaper
3. Go to Setting and click Wallpaper
4. Wallpaper Interaction or Input then switch it to keyboard
5. Exit the app and you see the Desktop App are gone

**Comment by rocksdanister** [comment]
Icons are automatically hidden when keyboard input is enabled (otherwise typing on desktop leads to icons being selected.)

To re-enable icons switch to mouse.

or in Windows rightclick desktop -> View -> Desktop Icons.

**Comment by Kenji09** [comment]
I did re-enable icons switch to mouse it didn't work

**Comment by rocksdanister** [comment]
Its only restored based on initial Windows setting when Lively is started.

>I did re-enable icons switch to mouse it didn't work

or in Windows rightclick desktop -> View -> Desktop Icons.

**Comment by Kenji09** [comment]
Yep, thank you about that I can see my desktop apps now, I appreciate it.
