### ISSUE TITLE
Lively wallpaper working hidden by windows static wallpaper

### ISSUE THREAD

**Issue by KristianMellina** [rocksdanister/lively#384]
Lively Wallpaper seems to work fine but I can't see the actual wallpaper as it seems to be hidden behind the static wallpaper I chose a long time ago when personalizing Windows.
When I connect with Teamviewer from a different pc it actually shows me the lively wallpaper working fine but when I close Teamviewer it reverts back to my solid wallpaper.
When restarting pc or turning it on it shows me the solid wallpaper because it has yet to open Lively, once it opened lively the wallpaper works fine and I can see it but only for a minute or so as when it finishes loading everything it just puts the solid wallpaper as background.
Thanks for your help, I really wish to fix this as I like lively a lot more than wallpaper engine and it's way lighter for my pc.
I searched a lot to resolve my issue but couldn't work it out.
[lively_log_20210324_142944.zip](https://github.com/rocksdanister/lively/files/6197667/lively_log_20210324_142944.zip)

**Comment by rocksdanister** [comment]
Does this issue happen with video wallpapers?

**Comment by KristianMellina** [comment]
Yeah it happens with video wallpaper, I'm trying to download a screen recorder to be able to show the problem

Edited: I tried recording multiple times but I can't get the video to be less than 10 mb.

**Comment by KristianMellina** [comment]
I currently fixed the problem by going in ease of access settings and toggling off the 'show desktop background'. This fixes the issue just partly since when I'm turning off the lively wallpaper 'cause I'm not on my pc I have to go back in the setting to turn it on again.
