### ISSUE TITLE
Live wallpaper not starting on one screen of 2 monitor setup

### ISSUE THREAD

**Issue by Til-g-pock** [rocksdanister/lively#385]
I have a 2 monitor setup and when I start my PC sometimes it makes a black wallpaper on my main monitor and Rain v2 (The wallpaper I've selected)
I don't know if the causes any problems but I have Rainmeter running with a few widgets on my 2nd monitor.

[lively_log_20210324_144718.zip](https://github.com/rocksdanister/lively/files/6197781/lively_log_20210324_144718.zip)

**Comment by rocksdanister** [comment]
How often does this happen.. can it be reliably reproduced?

**Comment by Til-g-pock** [comment]
maby 8 times out of 10
and idk if it's just a problem on my end or if it can be reproduced.
I'll whitelist it in the norton maybe that fixes it.

**Comment by Til-g-pock** [comment]
no, whitelisting it doesn't help

**Comment by whege** [comment]
I'm having a similar issue where when I select any display option other than "Span across screens", the wallpaper only displays on one of my two monitors. The other monitor shows the background I had previously set in Windows.

**Comment by catmountainking** [comment]
I have the exact same problem as OP. only my secondary monitor will have the wallpaper running at boot up. I can reproduce it every single time I shut down and turn my PC back on, needing me to manually close and open my wallpapers again. noticed the problem does not happen on system restarts though, only on shutdown and turning back on. i have a few rainmeter widgets on my main monitor, none on my 2nd. could be due to the display priority of the GPU, as mine, unfortunately, prioritises my 2nd monitor first (bios splash screen shows on 2nd monitor)

**Comment by rocksdanister** [comment]
@whegedusich @catmountainking 
The error you are experiencing is different, the original error of blackscreen means the wallpaper did apply properly but something else failed.
If nothing happens then Lively is not applying the wallpaper, likely related to display configuration change/detection.
Next time it happens sharing the full log file might help diagnose this:
 `Lively settings -> Misc -> Log file`

**Comment by catmountainking** [comment]
I have somewhat figured out how to avoid my issue. Normally I would turn my PC on before the 2 monitors. But when I turned my monitors on before my pc, lively works fine on both monitors. Thanks for the tip about display detection! Anyway here is the log file:
[lively_log_20210530_174532.zip](https://github.com/rocksdanister/lively/files/6566004/lively_log_20210530_174532.zip)

**Comment by rocksdanister** [comment]
That makes sense, during first time run I'm just skipping wallpapers whose screen is missing; I'm only adding wallpapers to the disconnected monitor list during runtime.

https://github.com/rocksdanister/lively/blob/89b50d1778d3a3e6a21924fade7f89ed51616dae/src/livelywpf/livelywpf/Core/SetupDesktop.cs#L913-L921

This should fix it:
```cs
var libraryItem = Program.LibraryVM.LibraryItems.FirstOrDefault(x => x.LivelyInfoFolderPath.Equals(layout.LivelyInfoPath));
var screen = ScreenHelper.GetScreen(layout.LivelyScreen.DeviceId, layout.LivelyScreen.DeviceName,
    layout.LivelyScreen.Bounds, layout.LivelyScreen.WorkingArea, DisplayIdentificationMode.deviceId);
if (libraryItem != null)
{
    if (screen != null)
    {
        Logger.Info("Restoring Wallpaper: {0} {1}", libraryItem.Title, libraryItem.LivelyInfoFolderPath);
        SetupDesktop.SetWallpaper(libraryItem, screen);
        restoredLayoutes.Add(layout);
    }
    else
    {
        Logger.Info("Restoring Wallpaper: wallpaper queued to disconnected list {0} {1}.", layout.LivelyInfoPath, layout.LivelyScreen.DeviceName);
        wallpapersDisconnected.Add(new WallpaperLayoutModel(layout.LivelyScreen, libraryItem.LivelyInfoFolderPath));
    }
}
else
{
    Logger.Info("Wallpaper missing in library, skipping restoration of {0}.", layout.LivelyInfoPath);
}
```
@catmountainking are you able to reliably recreate the error? if so I can release a beta build for you to test.

**Comment by catmountainking** [comment]
yes i can. i'll try it out

**Comment by rocksdanister** [comment]
Ok.. I will post in a few days, need to test some things.

**Comment by rocksdanister** [comment]
@catmountainking 
You can try it here:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.5.1.5

After checking if its working properly also share logfile.zip so that I can take a look.

**Comment by catmountainking** [comment]
It worked! I've tried to make it NOT work by turning display 2 on before display 1 but looks like it recognizes each display within seconds after turning on. Thanks for the fix! Really appreciate it. [lively_log_20210531_220738.zip](https://github.com/rocksdanister/lively/files/6570770/lively_log_20210531_220738.zip)
