### ISSUE TITLE
Wont open at all or on startup

### ISSUE THREAD

**Issue by MatrixMasterpeice** [rocksdanister/lively#39]
I have tried multiple times i tried reinstalling nothing works at all please help.

**Comment by rocksdanister** [comment]
Judging by the title I'm guessing lively is not opening after install and not just windows startup ?

Do you have any anti-virus software installed? It might be messing with it.

**Comment by R4ver** [comment]
I've noticed this happening as well after recent windows update.
Tried to update to the latest version of Lively to see if that fixed the issue, but we still got no luck sadly. Seems like our boi Windows is not too happy with something 

Version: 1909
OS Build: 18363.720

**Comment by rocksdanister** [comment]
I'll try updating and check, I'm currently on 1903.

**Comment by rocksdanister** [comment]
Working fine for me on 1909 build 18363.720.
What does the logfile say?

**Comment by R4ver** [comment]
Fun thing, no error logs written? Last error log I have is from the 7th
[20200408_180817.txt](https://github.com/rocksdanister/lively/files/4468962/20200408_180817.txt)

The process starts, but shortly after it dies without anything popping up

**Comment by rocksdanister** [comment]
Error log is a copy of logfile.txt when lively is crashed.
Open lively, set a wallpaper, close lively.
Navigate to Documents/Lively Wallpaper/
Share the logfile.txt file.

**Comment by rocksdanister** [comment]
Maybe this issue is related: https://github.com/rocksdanister/lively/issues/42

**Comment by R4ver** [comment]
Hi! Sorry for the late answer!

I've checked again to see if anything has been updated in the logfile.txt when trying to launch Lively, but nothing new is added eg. for this day.

Last entries are from 2020-04-10
[logfile.txt](https://github.com/rocksdanister/lively/files/4494866/logfile.txt)

**Comment by rocksdanister** [comment]
Can you verify the checksum of all files and compare it with a fresh one?

**Comment by R4ver** [comment]
So I think I've narrowed down the problem! I reinstalled and removed everything in the documents/Lively folder where the config n stuff i saved and apparently my config file before the reinstall was empty.

Upon trying to remove everything from the newly created config file, it stopped working again and behaved as the issue we've had. So I guess somehow the config just died?

**Comment by rocksdanister** [comment]
Looks like that's it!
I emptied the file & its crashing when trying to set the application language to null!

The config file is becoming null, Json.NET is not throwing an error and simply setting the configuration variable as null.

Adding this line fixed it, default value fro contructor is loaded:
`if(config == null)
  config = new ConfigFile();`
https://github.com/rocksdanister/lively/blob/47ba8685fc11cbbe140a4d035aa2bdc33e671912/src/livelywpf/livelywpf/save/SaveData.cs#L723

As to why the config file is getting corrupted/empty? I'm not sure.
I'll rewrite the data loading/writing code and try to push the update ASAP! .. as a quick fix I'll just load the default value if config is corrupt/empty.

**Comment by rocksdanister** [comment]
Added some mitigation in latest release v0.9.5.5

There is a backup save file, if main file is corrupt switches to it; if backup also corrupted then revert to default values.

I suspect the issue is windows not listening to shutdown delay command sent by lively (lively writes to save file on exit to indicate whether its is closed properly. )

**Comment by TechnoFynch** [comment]
I think this problem may also arise if you updated your .Net core. Like, before I updated my core to the latest release lively was working properly, but now it wont launch. I think during installing lively requests the install of a specific version of .Net core.

**Comment by erkhesiin** [comment]
Sorry to post on a dead thread lol

I'm on 1909 (build 18363.1556) on W10 pro. After several reinstallations and restarting my computer, Lively just refuses to open on my desktop. It's on my taskbar and everything but pressing Open Lively doesn't open anything at all, nor does any other button. 

![image](https://user-images.githubusercontent.com/101955380/159142722-257f6163-a501-44e9-ac5b-e632bfac3c1a.png)

I installed on 2.0.0.0 of lively so the config file shouldn't be the issue, but I don't know about anything about the .Net core that Comik-Storm mentioned. If the .Net core is the problem, can someone please tell me how I would solve it?

EDIT: here are the logs in a paste bin https://pastebin.com/imJddL16. It does say taskbar x is the issue, but after unloading it on rainmeter, it still doesn't work. Exiting rainmeter completely also does not work.

**Comment by rocksdanister** [comment]
@kevintamir try the Windows store version:
https://www.microsoft.com/store/apps/9NTM2QC6QWS7

**Comment by erkhesiin** [comment]
Yep, the store version works. Thanks
