### ISSUE TITLE
Setting a wallpaper brings the wallpaper to foreground while covering desktop icons

### ISSUE THREAD

**Issue by jai-ganesh-sankar** [rocksdanister/lively#390]
When I try to set a live wallpaper, the wallpaper opens seperately in the foreground, covering my entire desktop icons.

**Comment by rocksdanister** [comment]
Try restarting windows.

**Comment by jai-ganesh-sankar** [comment]
I restarted and it says "oops something went wrong" and wanted me to submit a log file. So here is the log file
[lively_log_20210326_020730.zip](https://github.com/rocksdanister/lively/files/6207726/lively_log_20210326_020730.zip)

**Comment by rocksdanister** [comment]
The latest one is a video stream wallpaper error, it could have been the case where your internet was not ready at the time windows started... try the included Eternal Light video wallpaper?
