### ISSUE TITLE
this error keeps popping up whenever I try a new wallpaper

### ISSUE THREAD

**Issue by Aaronstcodes** [rocksdanister/lively#392]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
this error keeps popping up whenever I try a new wallpaper

**To Reproduce**
1. Go to 'lively wallpaper'
2. Click on 'any wallpaper except for the first one'
4. See an error

**Expected behavior**
an error will pop up

**Screenshots/Video**
If applicable, add screenshots/videos to help explain your problem.
![Lively Wallpaper 3_26_2021 1_14_49 PM](https://user-images.githubusercontent.com/69480215/112599104-7870c780-8e35-11eb-8ad5-f722885a6c64.png)

**Desktop (please complete the following information):**
 - Windows10
- a pic of a car

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/358
