### ISSUE TITLE
Screen Saver works only in Preview (Microsoft Store version)

### ISSUE THREAD

**Issue by ApeirosPerfection** [rocksdanister/lively#395]
I set the "Screen saver" as "Lively" with "Wait: 1 minutes" and checked "On resume, display logon screen".
After 1 minute I saw the Screen Saver work for a split second, and the "logon screen" was skipped.
Tested 3 times and did the same 3 times.

I clicked preview and the Screen Saver worked good (my Lively Wallpaper kept playing until I pressed something).

**Comment by rocksdanister** [comment]
Alternatively as a workaround you can make an autohotkey script and trigger the screensaver manually:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#instruction

I plan to integrate screensaver settings within Lively itself in the future.
