### ISSUE TITLE
Scrolling down Lively Settings while a drop-down menu is open shows the drop-down menu off the window

### ISSUE THREAD

**Issue by ApeirosPerfection** [rocksdanister/lively#396]
This happened 2 of 2 times with Lively Wallpaper Web version (from https://rocksdanister.github.io/lively/).

This does not happen with Lively Wallpaper Microsoft Store version (there scrolling down is disabled while a drop-down menu is open).

Note: tested on Settings > Wallpaper with a reduced-in-height window of Lively Wallpaper.

**Comment by rocksdanister** [comment]
closing since XAML island related issue.
