### ISSUE TITLE
Screen Saver doesn't work on Lively Wallpaper (Web version)

### ISSUE THREAD

**Issue by ApeirosPerfection** [rocksdanister/lively#397]
The Web version of Lively Wallpaper (from https://rocksdanister.github.io/lively/) didn't display the Screen Saver:

1. No window opened after clicking Settings;
2. No Screen Saver preview displayed after clicking Preview;
3. Didn't show this icon:

![Screenshot 2021-03-27 003917](https://user-images.githubusercontent.com/69816568/112702745-e13b5c80-8e94-11eb-8c3f-f9fcfdb022cc.png)

...it displayed a black screen, and if pressing Settings or Preview, the black screen would show for a split second a capture of my Monitor.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Screen-Saver
