### ISSUE TITLE
Equalize Web and Microsoft Store versions of Lively Wallpaper's "Add Wallpaper" screen?

### ISSUE THREAD

**Issue by ApeirosPerfection** [rocksdanister/lively#399]
Microsoft Store version looks like this:

![Screenshot 2021-03-27 010054](https://user-images.githubusercontent.com/69816568/112703618-e4841780-8e97-11eb-82d6-6c63f03cad36.png)

Web version looks better (contains an animation).

**Comment by rocksdanister** [comment]
wpf framework has no native gif player, don't want to use third party library just for one gif.
The store and github version will always be different:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions
