### ISSUE TITLE
Mute button stops music from wallpaper only on 1 screen (2 screen setup)

### ISSUE THREAD

**Issue by kulichXD** [rocksdanister/lively#403]
**Describe the bug**
Muting the wallpaper in duplicate mode only muted a half of the sound (it was a bit quieter but still loud). 

**To Reproduce**
1. no idea

**Desktop (please complete the following information):**
 - OS: Windows 10
- Which wallpaper was running at the time if any:
[Flamingo_o_o_ouoh.zip](https://github.com/rocksdanister/lively/files/6225370/Flamingo_o_o_ouoh.zip)

**Additional context**
Fixxed the issue by individually selecting both screens and muting the wallpaper on each screen. Restarting my pc did not fix it. I am running 2 screen setup with different resolutions. Same issue happened when i tried different wallpapers with sound.

**Log file (Important)**
[lively_log_20210330_023121.zip](https://github.com/rocksdanister/lively/files/6225357/lively_log_20210330_023121.zip)

**Comment by rocksdanister** [comment]
Intended behavior in its current implementation, its using LivelyProperties api:
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#lively-properties

If you want to globally set the volume of all wallpapers:
 `Lively settings -> Audio -> Master Volume`

This duplicate behavior will change after https://github.com/rocksdanister/lively/issues/264 is resolved.
