### ISSUE TITLE
The youtube wallpaper does not start automatically when the PC starts.

### ISSUE THREAD

**Issue by gizibear** [rocksdanister/lively#404]
[lively_log_20210330_101645.zip](https://github.com/rocksdanister/lively/files/6225734/lively_log_20210330_101645.zip)

**Comment by rocksdanister** [comment]
Its because your network was not connected at the time, likely modem still initializing.
Only solution is to download the video using third party tools/website and load the video directly into Lively.

**Comment by gizibear** [comment]
so it need internet connection to start. Thanks. But can you tell me the tutorial on how to use offline video as wallpaper?

**Comment by rocksdanister** [comment]
Just drag'n'drop the file or in `+` page click on `Browse`
![main_dragdrop](https://user-images.githubusercontent.com/17554161/112924507-e535db80-912d-11eb-8525-f9d2d5a3e5b2.gif)

If you mean how to download the file, just google it...
