### ISSUE TITLE
Lively erroring when trying to start wallpaper

### ISSUE THREAD

**Issue by XilefTech** [rocksdanister/lively#406]
**Describe the bug**
When I installed lively yesterday, everything worked fine, but since I have put my pc to sleep mode and afterwards also restarting it, now lively always errors when I try to either preview a wallpaper or actually set a wallpaper as background

**To Reproduce**
Steps to reproduce the behavior (did not try how well it is reproducible):
1. Install lively
2. put PC to sleep mode
3. after waking up, restart computer

**Expected behavior**
Everything should work normally and the wallpaper should start correctly

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- Fluids v2 was running before putting computer to sleep mode. I think it was still running when restarting the computer but I didn't look closely

**Log file**
[lively_log_20210330_100236.zip](https://github.com/rocksdanister/lively/files/6227480/lively_log_20210330_100236.zip)

**Comment by rocksdanister** [comment]
Looks like it might be driver/hardware related, the gtx 460 gpu is very old.. I seen similar issues from users with that gpu.
Other than trying the windows store version of Lively, I can't think of anything else.
