### ISSUE TITLE
Wallpapers simply stop working after pressing win+d

### ISSUE THREAD

**Issue by Phmnatic** [rocksdanister/lively#407]
After viewing my desktop with win+d the interactive Wallpaper disappeared and I got the blue default windows wallpaper instead. Other customizable / interactive Wallpapers don't work either. 

The only thing that is kind of working are the video Wallpapers that i got from other websites, however they are not really a wallpaper but kind of a fullscreen video that is on top of my desktop. When pressin win+ d it also closes.

https://user-images.githubusercontent.com/70912269/112968048-2e952380-914c-11eb-88cc-4a02801a268d.mp4

**Comment by rocksdanister** [comment]
Have you tried restarting windows? this looks like the workerw crashed.

**Comment by Phmnatic** [comment]
> Have you tried restarting windows? this looks like the workerw crashed.

Thanks for the fast response. Yes I did and it worked, however this happened multiple times already.  Is there anything I can do to prevent this from happening?

**Comment by rocksdanister** [comment]
Share the logfile:
https://github.com/rocksdanister/lively/wiki/Common-Problems

Also tell me a bit about your system, do you have any software/launcher running that modify the desktop/windows..
