### ISSUE TITLE
Wallpaper doesnt show up

### ISSUE THREAD

**Issue by FlamersdayX7s** [rocksdanister/lively#414]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by FlamersdayX7s** [comment]
wallpaper doesnt show up at any ways(no preview, no background, still the old one.), i tried already restarting my pc and reinstallign the program. but i still get a error message.
it says: "Oops something went wrong. in order to better understand this issue and fix the issue, share the log file with the Developer"
hereby i also send the log file.
[lively_log_20210331_153927.zip](https://github.com/rocksdanister/lively/files/6237045/lively_log_20210331_153927.zip)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/358
