### ISSUE TITLE
Wallpapers dont work, gives error every time.

### ISSUE THREAD

**Issue by FlamersdayX7s** [rocksdanister/lively#415]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
None of the wallpapers show up, it gives only a error message every time
only the Eternal Light wallpaper works. the others and Own input are giving a error like:
Oops Something went wrong. to better understand and fix the problem go to: (link to the github page)

**To Reproduce**
1. open the Lively app
2. Click on any of the wallpapers (not Eternal Light)
3. See the error

**Expected behavior**
just like it used to work, being a cool working wallpaper.

**Screenshots/Video**
![Screenshot (4)](https://user-images.githubusercontent.com/81695109/113268984-4a2d3500-92d8-11eb-8c69-1e02845e2ed0.png)

**Desktop (please complete the following information):**
 - OS: Windows Home 10

**Additional context**
Earlier the Program was functioning as normal but now somehow not.
I tried to delete and reinstall the app from the store and the setup, but it still didnt work

**Log file (Important)**
hereby my Log File.
[lively_log_20210401_105431.zip](https://github.com/rocksdanister/lively/files/6242306/lively_log_20210401_105431.zip)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/358
