### ISSUE TITLE
My lively wallpaper is not allowing me to add a wallpaper to my computer and i do not know why

### ISSUE THREAD

**Issue by H0pE21** [rocksdanister/lively#417]
A few weeks back i got lively wallpaper and it doesnt let me use a wallpaper
![image](https://user-images.githubusercontent.com/81788792/113374782-e9cfdf00-933b-11eb-82ff-2c786fe48b5b.png)
That is what keeps on showing up and i do not know what to do to share log files or how to fix the issue. Please help

**Comment by rocksdanister** [comment]
There is a instruction link in that message to follow..
anyways, probably this issue https://github.com/rocksdanister/lively/issues/358
