### ISSUE TITLE
Certain links on youtube can't be added

### ISSUE THREAD

**Issue by Esphysion** [rocksdanister/lively#422]
Certain links on youtube dont work for the app. For example 

https://www.youtube.com/watch?v=kbZ1Y44vfRY 
doesn't work but
https://www.youtube.com/watch?v=Avhzj6TcGOI&t=16s
works perfectly fine

**Comment by rocksdanister** [comment]
Working fine for me, when you say don't work what exactly does it mean? got any error message?
(Follow the issue template..)

**Comment by Esphysion** [comment]
It says "error" then something like share the log files to devs and then
the github link.
Theres some videos that work but theres also some that doesnt, i have no
idea why

**Comment by rocksdanister** [comment]
Why not share the logfile then :/
https://github.com/rocksdanister/lively/wiki/Common-Problems

I have nothing to work with here.. don't know anything about your setup.

**Comment by Esphysion** [comment]
i have no idea how to

**Comment by rocksdanister** [comment]
Follow the instructions:
https://github.com/rocksdanister/lively/wiki/Common-Problems

**Comment by rocksdanister** [comment]
Looks like its because youtube-dl is outdated https://github.com/rocksdanister/lively/issues/430

Next update will fix this.

**Comment by Esphysion** [comment]
Ok thanks
