### ISSUE TITLE
Stream Video wallpaper not loading

### ISSUE THREAD

**Issue by NilsDriezen** [rocksdanister/lively#428]
Hi i am trying to load a wallpaper and then it gives an error. It also gives the error when i delete the wallpaper and try to add it into lively. Can you help me?

Wallpaper: 
[Removed link]
[20210404_112515.txt](https://github.com/rocksdanister/lively/files/6254278/20210404_112515.txt)

**Comment by rocksdanister** [comment]
1. Navigate to Lively install location.
For non-admin install:
      `C:\Users\<UserName>\AppData\Local\Programs\Lively Wallpaper\`
     For admin install:
     `C:\Program Files (x86)\Lively Wallpaper\`

2. Open the video player `plugins\mpv` folder
3. Try playing the same file using mpv.exe player and see if it works.

If the video did not play using mpv player:
1. Open powershell there(hold shift, rightclick -> Open powershell)
2. Try opening mpv with logging enabled.
Example:
`.\mpv.exe -v --log-file=mpv.log "M:\Data WD\4k Videos\Final.mkv"`
3. Share the mpv.log file.

**Comment by DLarisa** [comment]
Hello! Problem fixed with this new version. Thank you for your time!

**Comment by Emy67150** [comment]
Hello! I have exactly the same problem but given that I am not at all good in computers I did not understand the manip to be done. (Sorry for my English i'm French ^^')
[lively_log_20210405_211141.zip](https://github.com/rocksdanister/lively/files/6260227/lively_log_20210405_211141.zip)

**Comment by rocksdanister** [comment]
Its because one of the software used for fetching online video is outdated.
You can manually update it by following these instructions:
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper
or you can wait 1~2 days for the next Lively update.

**Comment by Emy67150** [comment]
Thank you very much! ^^

**Comment by DLarisa** [comment]
Well.... I updated the app and it worked just fine. Today, I see the same issue happening again. Whaaaa? :((((

**Comment by rocksdanister** [comment]
Share the lively logfile.

**Comment by DLarisa** [comment]
Here it is. And I have everything up to date and all the packages installed. I already checked a few days ago because I encountered the same issue.
[lively_log_20210408_200006.zip](https://github.com/rocksdanister/lively/files/6280266/lively_log_20210408_200006.zip)

**Comment by rocksdanister** [comment]
```
2021-04-08 19:50:47.4824|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0:[ffmpeg] tcp: Failed to resolve hostname www.youtube.com: The name does not resolve for the supplied parameters
2021-04-08 19:50:47.4842|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0:Failed to open https://www.youtube.com/watch?v=q3e...
2021-04-08 19:50:56.2647|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0:[ytdl_hook] ERROR: Unable to download API page: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),)) 
2021-04-08 19:50:56.2647|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0:[ytdl_hook] youtube-dl failed: unexpected error occurred 
2021-04-08 19:50:56.2647|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0:Exiting... (Errors when loading file)
```
Its a network issue, your internet connection was not ready when Lively tried loading the stream.
In such cases its better to just download the video yourself and load it into Lively, direct stream url support in Lively is mostly intended for live streams and simple clips and require network connection.

You can use [youtube-dl](https://youtube-dl.org/) or similar software to [download](https://askubuntu.com/questions/486297/how-to-select-video-quality-from-youtube-dl) .. maybe in the future I will integrate download functionality within Lively itself.
