### ISSUE TITLE
Online video wallpaper not working

### ISSUE THREAD

**Issue by DLarisa** [rocksdanister/lively#430]
Hello! Sorry to bother you. I receive this error each time I try to put a video as a Desktop Wallpaper: 
![image](https://user-images.githubusercontent.com/56414737/113560959-892af580-960c-11eb-8561-943904d631f4.png)

Can you help me, please? I am having this issues for about 5 days (I think?).

**Comment by KAIYOHUGO** [comment]
log file?

**Comment by DLarisa** [comment]
How do I do that?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems

**Comment by DLarisa** [comment]
[lively_log_20210405_133730.zip](https://github.com/rocksdanister/lively/files/6257742/lively_log_20210405_133730.zip)
 
It's ok like this?

**Comment by rocksdanister** [comment]
`Windows N/KN systems require installation of additional codecs for video playback.`

Intructions:
https://github.com/rocksdanister/lively/wiki/Video-Guide

If that does not work, follow the instructions https://github.com/rocksdanister/lively/issues/428

**Comment by DLarisa** [comment]
I did follow the instructions. I already have Media Feature Pack on my Windows and mpv works just fine. I don't understand what I am missing.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/428#issuecomment-813007054

The way Lively works is, different wallpaper types have different programs that handle them.. video files use mpv player, webpages use cef etc..

Your going to have to share the mpv logfile in this case.

**Comment by DLarisa** [comment]
[mpv.log](https://github.com/rocksdanister/lively/files/6258054/mpv.log)
This one?

**Comment by rocksdanister** [comment]
Try the latest beta:
https://github.com/rocksdanister/lively-beta/releases/tag/v1.2.1.3
and share Lively's logfile.

Lets continue the discussions on https://github.com/rocksdanister/lively/issues/428 since it is a similar issue.
