### ISSUE TITLE
Wallpaper turns black when fullscreen apps run

### ISSUE THREAD

**Issue by daxton256** [rocksdanister/lively#431]
Lively Wallpaper Turns Black When Google Chrome Is Open But Not When Edge Is. Please Fix This I Want To Use Lively But I Dont Want To Use Edge.

**Comment by rocksdanister** [comment]
Its pausing the wallpaper https://github.com/rocksdanister/lively/issues/20

Can be turned off by:
`Settings -> Performance -> Application Fullscreen -> Nothing`
