### ISSUE TITLE
Adding new wallpapers through a command...

### ISSUE THREAD

**Issue by E14Dev** [rocksdanister/lively#433]
A good idea would be to add a command that allows you to add a new wallpaper to your lively library, it would just need the arguments that the GUI does: path, title, description, author, website... hope this is considered!

**Comment by rocksdanister** [comment]
Its planned 😀https://github.com/rocksdanister/lively/blob/22e4e2c83270a16d8b2e81b679bc5ec5c0335e7b/src/livelywpf/livelywpf/Cmd/CommandHandler.cs#L177-L189

**Comment by rocksdanister** [comment]
Demo https://github.com/rocksdanister/lively/issues/273#issuecomment-817077466
