### ISSUE TITLE
Seeking to a position of the wallpaper not working..

### ISSUE THREAD

**Issue by E14Dev** [rocksdanister/lively#435]
I don't know If I'm being stupid but I just can't get the seekwp command to work. Here is the log..
![image](https://user-images.githubusercontent.com/77849687/113722046-f3649880-96e7-11eb-85dd-5aab56832ac5.png)

**Comment by rocksdanister** [comment]
Its a recent addition, next main update will support it:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#seek-wallpaper
`Require Lively v1.2.6 or above.`

Only beta build currently supports it:
https://github.com/rocksdanister/lively-beta/releases
