### ISSUE TITLE
Only eternal light wallpaper working

### ISSUE THREAD

**Issue by Avrage58** [rocksdanister/lively#437]
Hello. I am new to the technology scene but I know a few things. I have checked the issues and tried to troubleshoot them but I haven't had any luck.
**Describe the bug**
I am not sure as I am not a creator or anything, I just love to learn new things and tinker around on my computer. I found this cool lively wallpaper app and wanted to try it on my new Lenovo C940. I have checked the prerequisites for this app in order to insure compatibility but I keep getting an error message. I don't know what I did but I recently got only one of the wallpapers to work but only one. Every other one I still get that error message. Please help. Thanks

**Expected behavior**
I have removed any antivirus software and have removed and reinstalled everything as well as restart my computer. At first the opened screen was frozen but now it shows movement, but I am still not being allowed to activate or use any of the wallpapers except the sunset one. 

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 (OS Build: 18363.693)
- Wallpaper currently running: "Eternal Light"

**Log file (Important)**
[lively_log_20210406_124800.zip](https://github.com/rocksdanister/lively/files/6266314/lively_log_20210406_124800.zip)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/358
