### ISSUE TITLE
Automatic replay for youtube videos in wallpapers

### ISSUE THREAD

**Issue by Stui** [rocksdanister/lively#441]
After the Youtube video that is used as a wallpaper runs out of time it stops. Could there be a auto-replay option somewhere to reload the wallpaper after it runs out of time.

**Comment by rocksdanister** [comment]
It should start playing the video from beginning again automatically
https://github.com/rocksdanister/lively/blob/2164b041d5be14f0ee74c503b3f44d7974aa5c70/src/livelywpf/livelywpf/Core/Wallpapers/VideoMpvPlayer.cs#L103-L104
Tested working on my system.

**Comment by Stui** [comment]
Any idea what I can try to fix this one my device? Or could this problem be because of the video itself? I added the wallpaper using Enter URL function.
EDIT: Tested with 1min video and it really does restart it.. Sorry to bother you with this :)
