### ISSUE TITLE
When I have Microsoft edge focused screensaver does not show

### ISSUE THREAD

**Issue by Ucef27** [rocksdanister/lively#445]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
When I have Microsoft edge focused the screensaver does not show. It flashes once and then returns to focusing on Edge.

**To Reproduce**
Focus a webpage on Microsoft edge. Wait for the screen saver to automatically come on

**Expected behavior**
I excepted the screen saver to show properly

**Desktop (please complete the following information):**
 - OS: Windows 10 19042.867
- an mp4 was running

**Log file (Important)**
[lively_log_20210409_152204.zip](https://github.com/rocksdanister/lively/files/6288007/lively_log_20210409_152204.zip)

**Comment by rocksdanister** [comment]
Screensavers are not natively supported by ms anymore, I will be making my own screensaver setter UI inside Lively..
Duplicate: https://github.com/rocksdanister/lively/issues/395

**Comment by Ucef27** [comment]
Ok thank you
