### ISSUE TITLE
Pop-up error messages

### ISSUE THREAD

**Issue by robbely** [rocksdanister/lively#446]
When using a video stream as a background, if the stream is available Lively runs fine, but if it isn't Lively pops up an error message "Oops... Looks like something went wrong"

Is it possible to set Lively to fail quietly as this pop-up will interrupt any other work taking place on the PC which isn't always convenient, and (in my case) isn't due to a bug but simply a stream that has temporarily failed?

**Comment by rocksdanister** [comment]
headless mode will cover this when made available.

**Comment by robbely** [comment]
Is the upcoming headless mode for CEF only or does it cover youtube and m3u8 streams? I'm having the issue with the latter.

**Comment by rocksdanister** [comment]
headless mode will be for the whole Lively application.

**Comment by robbely** [comment]
Many thanks for the quick replies :)
Do you have a viewable roadmap of upcoming new features such as headless?

**Comment by rocksdanister** [comment]
I haven't made an issue for it yet, I mostly just work on features that interest me.. so there is no date/roadmap for any features.

**Comment by robbely** [comment]
That makes sense. Many thanks for the replies.

**Comment by rocksdanister** [comment]
I disabled the messagebox if Lively window is not open
https://github.com/rocksdanister/lively/blob/d6bc1919741417bbd5159fb6bf9bd62e1b1dabf8/src/livelywpf/livelywpf/Core/SetupDesktop.cs#L394-L397

**Comment by robbely** [comment]
That's brilliant! Many thanks :)
