### ISSUE TITLE
Butterchurn/Milkdrop module or Allow mic input for webpage

### ISSUE THREAD

**Issue by Dr-Flay** [rocksdanister/lively#447]
**Is your feature request related to a problem? Please describe.**
The web version of Butterchurn (butterchurnviz.com) mostly works but does not allow selecting the mic as source for audio.
(CEF engine used)

**Describe the solution you'd like**
Add a native Milkdrop/Butterchurn module.
https://github.com/jberg/butterchurn

**Describe alternatives you've considered**
projectM, but Butter Churn is written in JScript and WebGL

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by rocksdanister** [comment]
Lively already has API for system audio analysis:
https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data

**Comment by Dr-Flay** [comment]
Yeah I know it already supports audio as it works fine when using files for playback.
The mic input does not ask for permission when first used like it does in a browser.
If mic permissions are supposed to be on by default it is not functioning with this site for some reason.

**Comment by rocksdanister** [comment]
>Yeah I know it already supports audio as it works fine when using files for playback.

This has nothing to do with lively audio api, its just javascript function.

>The mic input does not ask for permission when first used like it does in a browser

Mic permission is disabled by default.

What I meant to say is rewrite the page to use Lively audio api.

Regarding allowing mic input, at the moment I don't have any plans.. maybe when I make cef config into external file will look into it.
