### ISSUE TITLE
Windowed application opened over Maximized application flashing/reloading bug 

### ISSUE THREAD

**Issue by morgan-swd** [rocksdanister/lively#449]
When I have a **windowed** application opened _over_ a **maximized** application, the applications flash and in some cases the GUI flashes (disappearing and reappearing rapidly) - in MS word for example. I attached a 5-sec video to show an example. I couldn't capture it with recording software for some reason so I had to use my phone. 

https://user-images.githubusercontent.com/82469492/114601519-9460cf80-9c63-11eb-8093-5ecfe0339b7d.MOV

**Comment by rocksdanister** [comment]
This is likely a driver related bug, try setting Lively settings -> Performance -> Application Focused -> Pause
Other than that I don't think I can help much here.
