### ISSUE TITLE
youtube video can be dragged

### ISSUE THREAD

**Issue by gg4924** [rocksdanister/lively#45]
When I use mpv to play youtube video, I found that the video can be dragged by the mouse
![Snipaste_2020-04-23_08-50-28](https://user-images.githubusercontent.com/21310130/80047405-e9ca3b00-853f-11ea-84d7-3e89cb92c267.png)

**Comment by gg4924** [comment]
I turned off mouse interaction, it works fine!

**Comment by rocksdanister** [comment]
Hmm should add an exception to video_stream type wallpaper.

**Comment by rocksdanister** [comment]
Fixed v0.9.5.5
You can keep mouse enabled.
