### ISSUE TITLE
Problems with youtube videos

### ISSUE THREAD

**Issue by periodicguy** [rocksdanister/lively#451]
[lively_log_20210414_122618.zip](https://github.com/rocksdanister/lively/files/6310173/lively_log_20210414_122618.zip)

I just want to report problem with importing video from youtube. In attacment is log file. If you have any fruther instructions for me please answer.

Best Regards

Ivan

**Comment by rocksdanister** [comment]
Update lively to [v1.3](https://github.com/rocksdanister/lively/releases/tag/v1.3.0.0)
Duplicate https://github.com/rocksdanister/lively/issues/422
