### ISSUE TITLE
Ribbon Wallpaper with Rainbow effect stops doing rainbow effect after a minute and stops at yellow

### ISSUE THREAD

**Issue by DecliningShip** [rocksdanister/lively#457]
Windows 10 Pro 20H2
[lively_log_20210420_233709.zip](https://github.com/rocksdanister/lively/files/6348583/lively_log_20210420_233709.zip)

**Comment by rocksdanister** [comment]
Duplicate https://github.com/rocksdanister/lively/issues/444
