### ISSUE TITLE
help with translation TO dutchand a bad attempt at frensh.

### ISSUE THREAD

**Issue by NicTanghe** [rocksdanister/lively#46]
U said plz contact me in release notes dunno how so i post here.

**Comment by rocksdanister** [comment]
I got french, I moved translations to a separate repo: https://github.com/rocksdanister/lively-translations

You can get started by using the English file, instructions are provided in the file: https://github.com/rocksdanister/lively-translations/tree/master/Lively%20UI/English

Send a pull request to that respository or just mail me.
