### ISSUE TITLE
Can't Download from Windows Store and Website (0xC0020036)

### ISSUE THREAD

**Issue by Greathed** [rocksdanister/lively#462]
It started like any day I open up my PC and open lively but it won't open. So I tried reinstalling and running as admin and nothing worked, so I reinstalled and I did and it said error I have space also using Normal Windows Defender and, I want to have lively again searched the web on how to fix but none avail so please fix this @rocksdanister btw 2019 user so yeah first time using github to report my problems than YouTube so please fix.

![178873638_1166010880518891_8983135146693185626_n](https://user-images.githubusercontent.com/83323399/116336602-6d7dce00-a80b-11eb-9ca6-161374a4b679.png)

**Comment by rocksdanister** [comment]
What does it say when you press `See details`

**Comment by Greathed** [comment]
> What does it say when you press `See details`

its just says error or something imma check again later

**Comment by Greathed** [comment]
![Uploading image.png…]()

**Comment by Greathed** [comment]
![image](https://user-images.githubusercontent.com/83323399/117099937-0cbf3a00-ada5-11eb-98bd-d4e2f515ff0e.png)
There

**Comment by rocksdanister** [comment]
Try searching that error code `0xC0020036 store error`, this looks like a windows/system issue and not related to Lively.

Most of the search results say to restore/scan system for errors.

or just download the installer version of Lively.
