### ISSUE TITLE
Option to turn off audio reactiveness

### ISSUE THREAD

**Issue by Dhruv00000** [rocksdanister/lively#463]
**Is your feature request related to a problem? Please describe.**
Whenever I am in a meeting, the wallpapers react to the audio and make my pc lag a lot because there is so much audio and its moving a lot.

**Describe the solution you'd like**
I really want an option to stop the wallpaper from reacting to audio

**Describe alternatives you've considered**
I tried setting the quality to low but its not as good looking

**Additional context**
The wallpaper im using is fluids

**Comment by rocksdanister** [comment]
![Screenshot 2021-04-28 123211](https://user-images.githubusercontent.com/17554161/116360742-d8d09b80-a81d-11eb-8124-01e8ffe5b72b.png)
