### ISSUE TITLE
Mpv player AUDCLNT_E_DEVICE_IN_USE / Voicemeeter causing video wallpaper to stop working.

### ISSUE THREAD

**Issue by saenpak-929U** [rocksdanister/lively#465]
I had recently installed Voicemeeter so that I could split my audio and now Lively is unable to run the video wallpapers.  I reinstalled Lively to see if a reinstall would fix the issue but it didn't fix the issue.

[210428 error log chunk.txt](https://github.com/rocksdanister/lively/files/6394538/210428.error.log.chunk.txt)

**Comment by rocksdanister** [comment]
Report it directly to mpv player devs:
https://github.com/mpv-player/mpv

Steps for producing mpv logfile:
https://github.com/rocksdanister/lively/issues/439#issuecomment-815315672

Alternatively you can try vlc video player:
https://youtu.be/8vgrsoBGoHI?t=88
(Its not tested and auto play/pause is not implemented.)

**Comment by saenpak-929U** [comment]
VLC worked, thanks
