### ISSUE TITLE
Application not starting (Installer version)

### ISSUE THREAD

**Issue by wang526125649** [rocksdanister/lively#466]
Windows 21H1 (19043.928)
There's no response to opening it.
There's no taskbar.
I think this is a compact version.
But. Net is installed.

**Comment by rocksdanister** [comment]
Which version of Lively are you using?
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions

Microsoft store or Installer?

**Comment by wang526125649** [comment]
> Which version of Lively are you using?
> https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions
> 
> Microsoft store or Installer?

1.4.0.0 Installer

**Comment by rocksdanister** [comment]
Duplicate https://github.com/rocksdanister/lively/issues/458
