### ISSUE TITLE
Bugged thumbnails when importing multiple videos

### ISSUE THREAD

**Issue by someretical** [rocksdanister/lively#468]
**Describe the bug**
Animated wallpaper thumbnails have this weird overlay over them when you try and import a bunch of them at once with the create previews option enabled

**To Reproduce**
1. Select a bunch of files you want to import
2. Drag them all into the lively wallpaper library window
3. Import all of them
4. Look at the thumbnails that are generated

**Expected behavior**
I don't think the overlay is meant to appear (when I import them one at a time it works fine)
![image](https://user-images.githubusercontent.com/29365738/116798048-4129c080-ab2f-11eb-9415-4de97866e077.png)

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/29365738/116798027-1a6b8a00-ab2f-11eb-8e5c-5a216d248e64.png)

![image](https://user-images.githubusercontent.com/29365738/116798036-26efe280-ab2f-11eb-9474-6497c2e6d40c.png)

![image](https://user-images.githubusercontent.com/29365738/116798042-32dba480-ab2f-11eb-8a32-716a068580bc.png)

**Desktop (please complete the following information):**
- Edition: Microsoft Windows 10 Pro 10.0.19042
- I was not running any of the wallpapers with scuffed thumbnails

**Log file (Important)**
[lively_log_20210502_102101.zip](https://github.com/rocksdanister/lively/files/6410560/lively_log_20210502_102101.zip)

**Comment by rocksdanister** [comment]
This does not happen when create preview is unchecked?
A bit confused.. you are using lite gui mode which uses thumbnails instead of preview gifs for library tile, why enable create preview in such a case?

**Comment by someretical** [comment]
I just checked and it happens whether or not create preview is enabled. Still using lite GUI mode though.

**Comment by rocksdanister** [comment]
Try the latest beta to see if its fixed:
https://github.com/rocksdanister/lively-beta/releases

**Comment by someretical** [comment]
Just tested and it's fixed now. Thanks for the fast fix 😄
