### ISSUE TITLE
How to use an openframeworks or processing ap as background.

### ISSUE THREAD

**Issue by NicTanghe** [rocksdanister/lively#47]
Bit of a noob here.
But since web is a terrible environment for motion design i was wondering how one whould go about running an openframeworks app or processing ap instead and how you whould format the files in the zip.

THX for making this,
U my hero.

**Comment by rocksdanister** [comment]
If it can be build (.exe) and has its own window, can be made wallpaper.
Just open it as "Other" in "Type" page.

Lively .zip is only for sharing, if you want it - after adding the wallpaper to library just right click it and select "Export Lively .zip"
