### ISSUE TITLE
taskbar black when google chrome is focused

### ISSUE THREAD

**Issue by AakashMandyam** [rocksdanister/lively#471]
Hi, I don't really know much abt code but I figure this is the best way to contact you. 
so whenever I have google chrome in focus, like I'm on that application the taskbar goes black but the second I alt tab it goes into the red I have of the background. Image down below

![image](https://user-images.githubusercontent.com/64557165/116807863-73fd9580-aaea-11eb-8bbf-eea1fc49b5e5.png) 

But whenever I alt tab into something else like discord it goes back to red. image below

![image](https://user-images.githubusercontent.com/64557165/116807901-90013700-aaea-11eb-9092-ff2d4e98b54a.png)

In both images, u can see I'm on google when its black and discord when red. I know its a really small problem but its nice to have a fix. Im using Waves one of the defaults downloaded when you install Lively and I just made it into a red color. I also have taskbarX for the taskbar centering and Transluecent TaskBar for making it clear. my normal taskbar I have on windows is black which might have something to do with it.

**Comment by rocksdanister** [comment]
Its because of the current way webpage wallpapers are paused when fullscreen apps/games are run.
Duplicate: https://github.com/rocksdanister/lively/issues/20
