### ISSUE TITLE
Pause when focusing on application issue (span mode)

### ISSUE THREAD

**Issue by Kurineko** [rocksdanister/lively#472]
I realized that when i focus on some any window on my second screen, the video will lag and jitter but not fully pause, when i focus on the main screen it pauses without an issue, my settings are all default except i have setting for video to be extended on both screens

**Comment by rocksdanister** [comment]
> i have setting for video to be extended on both screens

Span or duplicate? which one

**Comment by Kurineko** [comment]
Span

**Comment by Kurineko** [comment]
https://photos.app.goo.gl/A6SpJxF3EZCH8q9Q7  a video showing the issue, tell me if you need anything else

**Comment by rocksdanister** [comment]
Change `Display pause rule -> All display`

**Comment by Kurineko** [comment]
Thanks alot for the answer, but now it only pauses when i have applications windowed, but when its full screen in any of both, it won't pause https://photos.app.goo.gl/bhhKa75XHCi2zxqAA , sorry if its me doing something wrong lol

**Comment by rocksdanister** [comment]
Yeah I will have a look at it later, I think the issue is on my end.

**Comment by Kurineko** [comment]
I appreciate it! You have definitely earned a donation from me!
