### ISSUE TITLE
Perf & player video not working

### ISSUE THREAD

**Issue by FractalMimz** [rocksdanister/lively#473]
Hi,

A video is better than 1000 words :

https://user-images.githubusercontent.com/83668238/117067927-e8bf1280-ad2a-11eb-8d88-3e81e75e9dc2.mp4

Changing the player video do not apply. 
I have a very good computer but the app don't care totally.
When I accelerate the speed of a wallpaper it stutter.
And applying wallpaper is slow too.

Regards

**Comment by rocksdanister** [comment]
Only mpv player is bundled and recommended, rest is optional.

**Comment by FractalMimz** [comment]
OK so...

1. [20210504_223531.txt](https://github.com/rocksdanister/lively/files/6423988/20210504_223531.txt)
2. "**Describe the bug**" It is already done under the video.
3. "T**o Reproduce**" With the video and text under the video you can normally clearly identificate the steps.
4. "**Expected behavior**" Same above.
5. "**Screenshots/Video**" Same above.
6. OS: Windows 10 pro 20H2
7. Resume of issue : 
Problem 1 : Changing the player video setting do not apply. I want to try other because I have performances problems (I have a high end computer).
Problem 2 : When I accelerate the speed of a wallpaper it stutter.
Problem 3 : Applying wallpaper is slow too.
Problem 4 : When diaporama of wallpaper is setup behind Lively , at each time the wallpaper change, the Lively one stop 2-3s.

Regards

**Comment by FractalMimz** [comment]
To illustrate the problem mentioned :

It takes 48s to load this (BugLively2). And it use half near all decoder unit of my 2080ti

https://user-images.githubusercontent.com/83668238/117079255-b36ef080-ad3b-11eb-95a9-2e82a6bd053d.mp4


Why no use offline videos? or at least make an option.


https://user-images.githubusercontent.com/83668238/117080182-9e935c80-ad3d-11eb-9a4e-31935bf6b445.mp4

**Comment by rocksdanister** [comment]
>It takes 48s to load this (BugLively2).

Stream wallpaper's main purpose is for live streams.

> And it use half near all decoder unit of my 2080ti

Reduce the stream resolution.
>Why no use offline videos? or at least make an option.

Planning to, there is only one person working on Lively so things take time.. and I mostly work on things that interest me personally.

**Comment by FractalMimz** [comment]
Thank you and good work ;)
