### ISSUE TITLE
Changing tab while a list is opened leaves it open

### ISSUE THREAD

**Issue by DawidIzydor** [rocksdanister/lively#475]
**Describe the bug**
When a list is open (ie. the language selection list) and the tab is changed, the list stays open.

**To Reproduce**
1. Go to settings
2. Click on language list to expand it
3. Without selecting any language change tab to Library
4. The expanded language list stays open (bug)

**Expected behavior**
After changing tab all extended lists automatically close without chaning any setting

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/30767613/117348359-665d5c80-aeaa-11eb-9d6e-706e7b89fc8a.png)
**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- Which wallpaper was running at the time if any: Fluids

**Comment by rocksdanister** [comment]
Duplicate https://github.com/rocksdanister/lively/issues/396
