### ISSUE TITLE
Lively Wallpaper Icon blurry on device

### ISSUE THREAD

**Issue by Tech72** [rocksdanister/lively#476]
Hi

I have a QHD screen with a 16:10 ratio. This comes with some issues itself hence why I also have the windows scale resolution at 150%. Unfortunately this causes issue such as an unrecognisable icon for the Lively Wallpaper. Photo bellow.

Thanks
![image](https://user-images.githubusercontent.com/70978388/117377760-191fd000-af28-11eb-8713-6c087aeaa39e.png)

**Comment by rocksdanister** [comment]
![Screenshot 2021-05-07 090446](https://user-images.githubusercontent.com/17554161/117394194-55950100-af13-11eb-8a70-88cede69e9aa.png)

Tried upto 175% scaling in 1440p display.. I can't recreate this issue on my system.

**Comment by rocksdanister** [comment]
Have you tried restarting Windows?
