### ISSUE TITLE
Live Wallpaper disappears once active on a window

### ISSUE THREAD

**Issue by TheTallGiraffe04** [rocksdanister/lively#480]
Once I set the wallpaper and continue with my work I see that the wallpaper either freezes or turns the whole wallpaper black then you have to do some clicking around to make it work again I really enjoy actually seeing my wallpaper working behind my taskbar but I don't get to experience that so please people over at Lively Wallpaper please fix this

**Comment by rocksdanister** [comment]
Settings -> Performance -> When applications fullscreen -> Nothing.

**Comment by rocksdanister** [comment]
Yes...

**Comment by TheTallGiraffe04** [comment]
Thanks a lot

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
