### ISSUE TITLE
Update the windows wallpaper with currently still of lively wallpaper

### ISSUE THREAD

**Issue by thadude3** [rocksdanister/lively#483]
**Is your feature request related to a problem? Please describe.**
During windows UAC prompt, I see the original background. There is other times as well.

**Describe the solution you'd like**
The windows background should be set to a still of the lively background. This way you wont be able to tell the difference.
It will also keep it updated with your current lively background without having to constantly swap.

**Describe alternatives you've considered**
manually taking a screenshot and setting it, every time you change lively wallpapers.

**Additional context**
none

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/150
