### ISSUE TITLE
Automatic titles for youtube videos

### ISSUE THREAD

**Issue by tellmewhy12** [rocksdanister/lively#487]
**Is your feature request related to a problem? Please describe.**
when adding a new wallpaper from youtube you have to manually add the title and description, or else everything looks like this:
![image](https://user-images.githubusercontent.com/71931749/118035384-6efed880-b36b-11eb-9684-c3bad53ba362.png)

What it could look like instead:
![image](https://user-images.githubusercontent.com/71931749/118035419-76be7d00-b36b-11eb-9516-b129024c71e8.png)

**Describe the solution you'd like**
Automatically fetch the video title and description from YouTube (maybe also channel name as author field) when adding a video website and add it into the corresponding fields.
Alternatively it would maybe also look clean if instead of the description the author was displayed in the bottom text like here in the demo
![image](https://user-images.githubusercontent.com/71931749/118105887-47e0ef00-b3dd-11eb-91f5-b6ea3c3f073b.png)

**Describe alternatives you've considered**
Removing the automatic "watch" title and removing the whole transparent black label for unlabeled wallpapers

**Additional context**
See above

**Comment by rocksdanister** [comment]
Currently online videos are just directly streamed via youtube-dl and mpv player.
Adding a downloader and fetching metadata is a possibility..
For example:
https://github.com/Bluegrams/YoutubeDLSharp
Problem is since audio/video are separate streams it requires tools like ffmpeg (~60mb size increase) to create the final clip.

>Alternatively it would maybe also look clean if instead of the description the author was displayed in the bottom text like here in the demo

True, if description is missing this can be alternative.

**Comment by tellmewhy12** [comment]
Oh, interesting I didn't realize the videos aren't downloaded, could be a nice feature for offline usage

**Comment by tellmewhy12** [comment]
Or maybe a setting for just disabling the labels would also make it more clean for people that don't like to caption everything 
![image](https://user-images.githubusercontent.com/71931749/118547429-997cd700-b759-11eb-9871-3a35bbe7e262.png)

**Comment by rocksdanister** [comment]
>Or maybe a setting for just disabling the labels would also make it more clean for people that don't like to caption everything

No, I won't be doing that; I'd like to avoid adding too many settings for small cases like this.

**Comment by rocksdanister** [comment]
So been playing around with mpv player and youtube-dl.
The video and title information can be downloaded using youtube-dl and then ~muxed~ re-encoded using:
`.\mpv.exe input.mp4 -audio-file="audio.m4a" -o output.mkv`
**Edit:**
Looks like mpv can stream and record sametime:
https://mpv.io/manual/stable/#options-stream-record

**Comment by tellmewhy12** [comment]
not sure if helpful but (commandline) youtube-dl can also get description to a .description (text) file with
`youtube-dl https://www.youtube.com/watch?v=4o0r9unT4L4 --write-description --skip-download --youtube-skip-dash-manifest`

and add channel name and title to the name of the output file with
`youtube-dl -o '%(channel)s - %(title)s.%(ext)s' https://www.youtube.com/watch?v=4o0r9unT4L4`

https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template

**Comment by rocksdanister** [comment]
https://user-images.githubusercontent.com/17554161/119674455-d6cc1d80-be59-11eb-8d84-5b0c25c8d8e9.mp4

Video description is pretty ugly/useless 😂

**Comment by tellmewhy12** [comment]
@rocksdanister almost expected this 😂 but awesome that it works! maybe the channel name is a better idea? even though sometimes videos just get uploaded by random people that didn't create the video themselves, but not sure what better thing to put there
