### ISSUE TITLE
CEF crash

### ISSUE THREAD

**Issue by KAIYOHUGO** [rocksdanister/lively#489]
**Describe the bug**
CEF will crash when load a "large" website

**To Reproduce**
1. add [google santatracker](https://santatracker.google.com/intl/en-US/) as wallpaper (CEF) 
2. See error

**Expected behavior**
CEF will crash after 10~20 min

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/41114603/118127976-e5afda80-b42c-11eb-910e-19ce7bfa6ab7.png)

 - OS: [Windows 10 20h2 19042.928]
- wallpaper: [google santatracker](https://santatracker.google.com/intl/en-US/)

**Additional context**
this bug has been happened long time ago

**Log file (Important)**
there is no usefull log¯\\\_(ツ)\_/¯,nothing log when it crash

**Comment by rocksdanister** [comment]
Did you try testing with latest version of Lively v1.5? 
There should be a browser log in appdata:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Cef`
(although it gets deleted everytime you start a new cef instance..)

**Comment by KAIYOHUGO** [comment]
yes i just updated before i test yesterday

i will check my CEF log file later

**Comment by KAIYOHUGO** [comment]
i check my CEF log file, but just some js error.(it also happened in google chrome).
i have no idea why CEF crash. maybe ram limit?i guess.

**Comment by rocksdanister** [comment]
Yeah memory leaks in webpage code can also crash chrome..

**Comment by KAIYOHUGO** [comment]
idk.4G of ram is not enough for a web page?🤔
