### ISSUE TITLE
McAfee show Lively Wallpaper as Ransomware

### ISSUE THREAD

**Issue by jnthnz** [rocksdanister/lively#49]
Hi,

When I go to apply a wallpaper (the rain one), McAfee gives me a popup and says it is ransomware. Now, I'm sure this is a false positive, but it would be great if you could find a way to reach out and get it removed.

https://i.imgur.com/frh4KQw.png -- Image of popup.

**Comment by rocksdanister** [comment]
Heuristic algorithms can pick up things for any number of reasons, I'm not going out of my way to submit lively to every single av software out there... 

Only windows defender is considered.
