### ISSUE TITLE
Error when switching/adding wallpapers

### ISSUE THREAD

**Issue by yungNATE** [rocksdanister/lively#490]
**Hi everyone,**

Since I updated to the last version, everything seems broken. I installed v1.5 from v1.4, was great until then.
In v1.5, whenever I try switching wp, I've got a popup saying there was an error blabla... nothing particular here but no switching happens. The only working wp was Eternal light (?? idk why, quite weird). 

Therefore, I tried installing back v1.4, which was fine at the time. Now, almost everything's back to normal, except I can't add my own custom videos back. Same as in v1.5 when I tried switching wp, I get a generic error popup not saying anything especially useful.

I checked the log files to see if I could do anything on my own. It happens lively can't find a file "Setting.json" (I also checked the breadcrumb, and the link to this file was ok). I also tried stopping AVG as it may prevent apps from reading/writing on any files. Nothing changed.

Note that I did install/uninstall/restart my computer multiple times. 
Any idea on what could be happening? Thanks!
[lively_log_20210513_190208.zip](https://github.com/rocksdanister/lively/files/6474060/lively_log_20210513_190208.zip)

**Comment by rocksdanister** [comment]
>I've got a popup saying there was an error blabla..

Mind your language.

I only provide support for latest version of Lively, that is v1.5

Use v1.5 and create a new issue and follow the full issue template.

**Comment by yungNATE** [comment]
> 
> 
> > I've got a popup saying there was an error blabla..
> 
> Mind your language.
> 
> I only provide support for latest version of Lively, that is v1.5
> 
> Use v1.5 and create a new issue and follow the full issue template.

Hey, 

I did not mean to be disrespectful in any way. 
Did the "blabla.." bothered you? I'm sorry then, but I only pointed the fact the error was generic and not much of an help in this case.
No need to be aggressive here. Especially as I am a huge fan of the app and did NOT make any criticize. Only seeking for help.

By the way, I CAN'T use v1.5. As I said, lively refuses to set wallpapers in this version. Using v1.4 is only a workaround.

**Comment by rocksdanister** [comment]
>As I said, lively refuses to set wallpapers in this version.

Thats not what you said:

>In v1.5, whenever I try switching wp, I've got a popup saying there was an error blabla... nothing particular here but no switching happens. The only working wp was Eternal light (?? idk why, quite weird).

Different wallpaper types use different wallpaper player plugin, eternal light is video and rest are webpages so different plugin.

Like I said use v1.5, share the error logs.. my bet is AVG is messing with the files.
