### ISSUE TITLE
Error while switching wallpapers 

### ISSUE THREAD

**Issue by yungNATE** [rocksdanister/lively#491]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
Since I updated to the last version, everything seems broken. I installed v1.5 from v1.4, was great until then.
In v1.5, whenever I try switching wp, I've got a popup saying there was an error blabla... nothing particular here but no switching happens. The only working wp was Eternal light (?? idk why, quite weird).

Therefore, I tried installing back v1.4 (as a workaround), which was fine at the time. Now, almost everything's back to normal, except I can't add my own custom videos back. Same as in v1.5 when I tried switching wp, I get a generic error popup not saying anything especially useful.

I checked the log files to see if I could do anything on my own. It happens lively can't find a file "Setting.json" (I also checked the breadcrumb, and the link to this file was ok). I also tried stopping AVG as it may prevent apps from reading/writing on any files. Nothing changed.

Note that I did install/uninstall/restart my computer multiple times.

**To Reproduce**
1. Set any wallpapers except from Eternal Light

**Expected behavior**
-> A popup saying there was an error.

**Screenshots/Video**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `[20210513_190059.txt](https://github.com/rocksdanister/lively/files/6474185/20210513_190059.txt)logs`

**Comment by rocksdanister** [comment]
This is just copy paste of the previous issue https://github.com/rocksdanister/lively/issues/490 :/
In case I was not clear, this is what I am asking you to do:
1. Updated Lively to v1.5 (latest.)
2. Click on Eternal light and other wallpapers.. If error pops up then press Ok, continue clicking.
3. Share the logfile by navigating to `Lively settings -> Misc -> Log file`

**Comment by yungNATE** [comment]
Oops!

Thought this was the right log file, must have deleted the wrong one. Here's what you're looking for, my bad.
Update : After installing the latest version I've been able to switch from wallpaper a couple of times (3-4 maybe?) until the same error gets back.
[lively_log_20210513_202338.zip](https://github.com/rocksdanister/lively/files/6474344/lively_log_20210513_202338.zip)

**Comment by rocksdanister** [comment]
`Le fichier spécifié est introuvable`
Avg deleted the browser.
Duplicate: https://github.com/rocksdanister/lively/issues/358

**Comment by yungNATE** [comment]
I checked the #358, and turning off AVG indeed helped for the pre-integrated wallpapers. 
Still, I can't add custom wallpapers. Anyway, thanks a lot for your time!

**Comment by rocksdanister** [comment]
Switch to vlc player:
https://youtu.be/8vgrsoBGoHI?t=88

or you can try downgrading mpv player to older version `mpv-i686-20210404-git-dd86f19.7z`:
https://sourceforge.net/projects/mpv-player-windows/files/32bit/
(Extract the files to the `plugins/mpv` folder.)
