### ISSUE TITLE
Change workspace by stipulating the time for the next live wallpaper 

### ISSUE THREAD

**Issue by Cnshark** [rocksdanister/lively#492]
261 / 5000
Translation results
it would be really cool to change the live wallpaper in a specific selection time, as in the windows panel itself.
It would also be very cool to put the livewalpaper on the lock screen, this is not possible, even if you have the option in the program, but Windows does not allow it.

**Comment by rocksdanister** [comment]
>it would be really cool to change the live wallpaper in a specific selection time, as in the windows panel itself.

Duplicate: https://github.com/rocksdanister/lively/issues/137

>It would also be very cool to put the livewalpaper on the lock screen, this is not possible, even if you have the option in the program, but Windows does not allow it.

Not possible, currently only picture lockscreen wallpaper.
