### ISSUE TITLE
add option for centered taskbar icons

### ISSUE THREAD

**Issue by Chaosdave34** [rocksdanister/lively#494]
**Is your feature request related to a problem? Please describe.**
Not Related to Problem.

**Describe the solution you'd like**
An option, which allows to center the icons in the taskbar (similar to taskbarx)

**Comment by rocksdanister** [comment]
Definitely outside the scope of Lively.. but taskbar theme is also that haha..
will look into it, not a priority at the moment.

**Comment by rocksdanister** [comment]
Based on leaks, next version of Windows will have this feature built in.
