### ISSUE TITLE
Lively not launching

### ISSUE THREAD

**Issue by Sicario19** [rocksdanister/lively#495]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
I have been unable to launch Lively at all since downloading and installing.

**To Reproduce**

**Expected behavior**
App to Launch.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- Which wallpaper was running at the time if any. None

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

No Logs to attach

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/458
