### ISSUE TITLE
Lively Wallpaper starts slowly when booting up！

### ISSUE THREAD

**Issue by Louis209** [rocksdanister/lively#499]
Wallpaper Engine does not have this problem

**Comment by rocksdanister** [comment]
Early start is disabled for stability reasons; Lively starts as regular windows program.

**Comment by Louis209** [comment]
I really need to start it in advance, how to start it manually？

**Comment by rocksdanister** [comment]
This is not officially supported, you are on your own:
https://github.com/sylveon/EarlyStart

**Comment by sylveon** [comment]
![Works on my machine](https://user-images.githubusercontent.com/6440374/118594531-a01a4700-b777-11eb-861a-97f3e2732d08.png)
