### ISSUE TITLE
Lively keeps crashing

### ISSUE THREAD

**Issue by 21OutWorld** [rocksdanister/lively#50]
idk why but lively keeps crashing before i get to do anything

**Comment by 21OutWorld** [comment]
[20200429_120057.txt](https://github.com/rocksdanister/lively/files/4552855/20200429_120057.txt)

**Comment by rocksdanister** [comment]
Nothing is being logged, is there any other external software that is interfering with lively?

**Comment by rocksdanister** [comment]
Not enough information.
