### ISSUE TITLE
failed to set parent, HRESULT:1400 / not working.

### ISSUE THREAD

**Issue by Umang2802** [rocksdanister/lively#503]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by Umang2802** [comment]
[20210519_210244.txt](https://github.com/rocksdanister/lively/files/6510614/20210519_210244.txt)
[20210519_203641.txt](https://github.com/rocksdanister/lively/files/6510615/20210519_203641.txt)
Here are the logs files.

**Comment by rocksdanister** [comment]
`failed to set parent, HRESULT:1400`
Restart system.
