### ISSUE TITLE
Wallpaper does not want to open / The system cannot find the file specified.

### ISSUE THREAD

**Issue by Livelyuse** [rocksdanister/lively#504]
![Photos](https://user-images.githubusercontent.com/84496551/118935192-8a5d7b00-b94b-11eb-843e-dba8581ddc76.png)

**Describe the bug**
Wallpaper doesnt start

**Expected behavior**
I click on a button like i did before and it just started happening yesterday, it just gives me an error and doesnt open the wallpaper.

**Desktop**
 - OS: Win 10 Enterprise 
- Which wallpaper was running at the time if any. Cant open it

**Log file**
Core: Failed to launch wallpaper=>Failed to start process.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at livelywpf.Core.WebProcess.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebProcess.cs:line 206

**Comment by rocksdanister** [comment]
Duplicate https://github.com/rocksdanister/lively/issues/358
