### ISSUE TITLE
Taskbar not working in monitor 2

### ISSUE THREAD

**Issue by Yug1900** [rocksdanister/lively#511]
**Taskbar not working in monitor 2**
for some reason **clear** taskbar is not workin correctly, in my first monitor it´s ok but in my second it isn´t

**first monitor**
![image](https://user-images.githubusercontent.com/84157407/119243431-a1ab8c80-bb34-11eb-9e85-5bf7bbcb894d.png)
**second monitor**
![image](https://user-images.githubusercontent.com/84157407/119243439-bb4cd400-bb34-11eb-8983-32e668461409.png)

**Comment by rocksdanister** [comment]
That's unusual, its tested with upto 4 monitors.. can you install:

https://www.autohotkey.com/

and use Windows Spy and click on the taskbar which the theme is not working and share the screenshot.
