### ISSUE TITLE
Problems changing the wallpaper

### ISSUE THREAD

**Issue by Shadow1003** [rocksdanister/lively#513]
**Problems changing the wallpaper**
It does not let me change to the default wallpaper and when I do this I get this:

![image](https://user-images.githubusercontent.com/84686181/119277347-b6475d80-bbe4-11eb-8d46-f0e954efabb6.png)
[lively_log_20210523_162225.zip](https://github.com/rocksdanister/lively/files/6528956/lively_log_20210523_162225.zip)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/358
