### ISSUE TITLE
Feature Request: Automatically change wallpaper based on weather and sunrise/sunset times

### ISSUE THREAD

**Issue by JpTiger** [rocksdanister/lively#52]
Hi there, thanks for all your work on what looks like a great app! I found your work via [an old reddit post of yours about having wallpaper change depending on time of day and weather](https://www.reddit.com/r/Rainmeter/comments/g3qko1/not_a_rainmeter_skin_but_i_made_a_custom_script/). It looked like that got spun off into RePaper, but when I went to to download it,[ it suggested getting this project instead](https://rocksdanister.github.io/rePaper/#contact). I did so assuming it had the same features, but it looks like that's not the case (unless I'm misreading settings somewhere). I tried rePaper but it looks like instead of selecting a wallpaper, it does some (pretty impressive) weather overlay effects instead. I personally don't need you to replicate those into Lively, I can see they're two distinct products. But it would be great if you could add the original concept to Lively. 

Just to give a concrete example, I've got a number of photos I use for desktop photos that were taken at different times of day and in different weather. I'd be happy to set them each manually to "day-clear," "night-clear," "night-rain," etc. and I'd love for Lively to choose my wallpaper corresponding to the actual weather and day/night time where I am now. Any chance that feature could be added?

Thanks again!

**Comment by rocksdanister** [comment]
Wallpapers and Lively are two separate things: https://github.com/rocksdanister/lively#features 

What you are saying can be done by creating a webpage that cycles through images by fetching weather data and doing some basic checks; then setting that webpage as lively wallpaper.

I will not be adding full weather fetching code ontop of lively just for this feature, you are better off looking for a different software(as it seems you just want to cycle some static images, don't care about animation..lively is not optimal for this use) or making the webage like I mentioned.

**Comment by JpTiger** [comment]
Got it. That's disappointing but understandable. I'll keep an eye out for other software or simpler scripts that do [what you described with swapping wallpapers on reddit](https://www.reddit.com/r/Rainmeter/comments/g3qko1/not_a_rainmeter_skin_but_i_made_a_custom_script/). If you know of any I'd be grateful to hear about it, but totally understand that knowing about other software is not your responsibility.

**Comment by rocksdanister** [comment]
You are confused, no need to host website.
You can create a .html file and load it from the disk.

See the subreddit for some of the web wallpapers I shared: https://www.reddit.com/r/LivelyWallpaper/

**Comment by JpTiger** [comment]
That would be great, thank you! The part I'm missing is how you would get an html file on your computer to ping a weather server regularly and process the results.

**Comment by rocksdanister** [comment]
You just request it: https://medium.com/swlh/a-simple-javascript-weather-application-and-json-parsing-abd21ff0ea9a

**Comment by rocksdanister** [comment]
Its up: https://github.com/rocksdanister/weather-fetch-wallpaper
