### ISSUE TITLE
Video wallpaper playback paused

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#524]
**Describe the bug**
I used to use the microsoft store version of lively with custom wallpapers added by link until one day I noticed that (obviously) if I turned on my pc without wifi the wallpaper wouldn't load; so I decided to add a custom wallpaper by downloading the video file (a .mp4 file from youtube). From that point on every wallpaper that I would add to lively that hadn't come already installed with it would show as the static first frame of the video, even if I tried to add it with a link. I decided to install lively from here (github) since it maybe was a bug of that version, and at first it worked without problems, than it gave the same problem again and I don't know what causes this or how to fix it

**To Reproduce**
I'm not sure how to reproduce it, I noticed it stopped working after I finished playing terraria, but it could've stopped when I turned on the pc for the first time after installing lively and shutting the pc off. I thought it maybe just stopped because terraria was reproducing in full screen and somehow it didn't start playing back the wallpaper after closing it, but closing and reopening lively multiple times or even deleting and re-adding the wallpapers either as a file or a link didn't work

**Expected behavior**
The wallpaper plays normally on the desktop after I add it to lively, and not as a static image of the first frame of the video I chose

**Screenshots/Video**
https://drive.google.com/file/d/1CkvG6_PjcOouZReSHFJ7oFLs6lUl3wBU/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home 20H2 19042.985]
- The wallpapers were the ones in the video (the video looks laggy but the actual wallpapers played smoothly)

**Log file (Important)**
[lively_log_20210526_234352.zip](https://github.com/rocksdanister/lively/files/6549775/lively_log_20210526_234352.zip)

**Comment by rocksdanister** [comment]
I don't see anything unusal in the logfiles.
Could be the old gpu, try turning off `GPU Decode` under `Settings -> Wallpaper -> Video` and try.

**Comment by ghost** [comment]
In the meanwhile I uninstalled and reinstalled lively. Unchecked `GPU Decode` as said, still got the same issue. Could there be something that stops the wallpaper from playing since meybe it's using too much resources for a GPU as bad as mine? Though it's weird because it worked at first, and also it still works with default wallpapers.

**Comment by ghost** [comment]
Is there a max size/length for the wallpaper video? Because by clicking on preview on this wallpaper 

 >https://drive.google.com/file/d/1CkvG6_PjcOouZReSHFJ7oFLs6lUl3wBU/view?usp=sharing

 and making a <2 seconds short video it worked I don't know why; and also by going on the preview of the original video it didn't automatically starts, maybe it's related to the preview or the video itself

**Comment by ghost** [comment]
Ok so I think the problem was in the videos themselves since I solved it by deleting them and redownloading them from another source, but I still don't know what was the problem (since they were a supported file format) and why it didn't let me add wallpapers even from links. Anyways that's it, I'll leave the case open if anyone wants to investigate but @rocksdanister feel free to close it, sorry for causing trouble.

**Comment by rocksdanister** [comment]
Different player handles corrupted file differently I guess..
Lively is using mpv player by default:
https://github.com/mpv-player/mpv
