### ISSUE TITLE
Unable to use floats as slider step in LivelyProperties.json

### ISSUE THREAD

**Issue by eliasfloreteng** [rocksdanister/lively#525]
**Describe the bug**
When setting the step value for a slider to a floating point number in LivelyProperties.json, it is received as the number but without the decimal. Example 4.5 gets received as 45. This does only happen when changing the value, it does not occur when first reloading the wallpaper.

**To Reproduce**
1. Download [my project file](https://github.com/rocksdanister/lively/files/6553198/Circle-Audio-Visualizer.zip)
2. Add and apply it in lively
3. Change Background blur customization option (used as an example)
4. See the received value in the upper left of the wallpaper as text

**Expected behavior**
A decimal number should be received as such.

**Screenshots/Video**
https://user-images.githubusercontent.com/18127101/119812593-97004700-bee8-11eb-8463-1400001e9b61.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- Wallpaper: [my project file](https://github.com/rocksdanister/lively/files/6553198/Circle-Audio-Visualizer.zip)
- Lively version: 1.5.0.0

**Log file**
[lively_log_20210527_123302.zip](https://github.com/rocksdanister/lively/files/6553282/lively_log_20210527_123302.zip)

**Comment by rocksdanister** [comment]
Not happening for me.. I think the copy file of properties is not getting updated.
Few things to try:
1. Restore defaults
2. Can you try exporting the project .zip, deleting and adding it again.

**Comment by eliasfloreteng** [comment]
Tried both the tings you said with no success. The problem remains even after deleting and adding the wallpaper and restoring defaults. The issue may be in my installation but how can I fix it?

**Comment by rocksdanister** [comment]
Share the folder with the same name as the problem wallpaper folder from the data location:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\wpdata`

**Comment by eliasfloreteng** [comment]
From: C:\Users\Elias\AppData\Local\Lively Wallpaper\Library\SaveData
[wpdata.zip](https://github.com/rocksdanister/lively/files/6561732/wpdata.zip)

**Comment by rocksdanister** [comment]
I need the foldername of your audio visualiser wallpaper.

**Comment by eliasfloreteng** [comment]
Latest one is `2ndhq03m.he3` after I reinstalled the wallpaper. Before that it was `gfesoybw.ydw`

**Comment by rocksdanister** [comment]
The span configuration in `gfesoybw.ydw` is old copy:
```json
  "bgBlur": {
    "max": 10,
    "min": 0,
    "tick": 25,
    "step": 1,
    "text": "Background image blur",
    "type": "slider",
    "value": 0
  },
  ```
Rest looks fine, the file of reinstalled wallpaper looks updated.
Just for good measure can you try deleting the `wpdata` folder and restarting Lively.

**Comment by eliasfloreteng** [comment]
Ok, will try that.

**Comment by eliasfloreteng** [comment]
Tried it and it still doesn't work 😞 

The duplicate `LivelyProperties.json` in new wpdata folder contains:
```
[...]
"bgBlur": {
    "max": 10,
    "min": 0,
    "step": 0.5,
    "text": "Background image blur",
    "type": "slider",
    "value": 2.5
  },
[...]
```

**Comment by rocksdanister** [comment]
Yeah I figured it out, its your regional format - English (Sweden)
Fractions are separated by comma; Lively application is region aware but browser program is set to invariant culture.

**Comment by eliasfloreteng** [comment]
Ah! A miracle that you figured it out. I wouldn't have thought of that. Looking forward to a fix in the next update 😄! And yes, it is because Sweden uses comma for decimal separation.

**Comment by rocksdanister** [comment]
Try the latest beta build to see if its fixed:
https://github.com/rocksdanister/lively-beta/releases

**Comment by eliasfloreteng** [comment]
It works now! Thanks!

Just want to say I love the lively app and this community. Thanks for listening and fixing things for us end users!
