### ISSUE TITLE
Lively stays in Taskbar after Windows Start

### ISSUE THREAD

**Issue by CREEATION** [rocksdanister/lively#527]
**Description**
Upon Windows start, Lively starts automatically and is working as it should. However, it kinda stays "open" in the taskbar.
You can hover over Lively in the taskbar and see an empty Lively window in the preview, but Lively won't open when clicking on it, only the active window focus changes (to essentially "none" in this case).

**To Reproduce**
1. Start Windows
2. See Desktop loading
3. Lively works as expected
4. ... but doesn't close in the taskbar

**Expected behavior**
Lively starts and runs in the background upon Windows start.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/3277769/120112285-7a2c7380-c175-11eb-8527-f59453bf087e.png)
(the preview showing the empty Lively window on mouse-over)

**Desktop:**
 - OS: Microsoft Windows 10 Pro 10.0.19042
- Wallpaper: Ribbon (but this happened with any other wallpaper, too)

**Additional context**
When opening Lively from the info section next to the system clock in the taskbar, and then closing it again, everything works as expected.

**Log file**
https://gist.github.com/CREEATION/12230d53195d13bcf53a1f8a0bcb0fdc

**Comment by rocksdanister** [comment]
I wonder if its related to https://github.com/rocksdanister/lively/issues/70

Can you try the beta version of Lively:
https://github.com/rocksdanister/lively-beta/releases

**Comment by CREEATION** [comment]
Thanks for the quick response! It does seem to work properly now. If it happens again for some reason I'll report back here. 💚🐢
