### ISSUE TITLE
Update via installer removes all other startup items

### ISSUE THREAD

**Issue by TLCFEM** [rocksdanister/lively#529]
https://github.com/rocksdanister/lively/blob/11d88d692219a6a99a533388c9307aa1014c4aeb/src/installer/Script.iss#L69

This line potentially would remove all other startup items for current user. Not affecting first time installation.

The flag used has the following documentation from Inno:

```text
uninsdeletekey
When the program is uninstalled, delete the entire key, including all values and subkeys in it. It obviously wouldn't be a good idea to use this on a key that is used by Windows itself. You should only use this on keys private to your application.

To prevent disasters, this flag is ignored during installation if Subkey is blank or contains only backslashes.
```

So the key `Software\Microsoft\Windows\CurrentVersion\Run` is deleted during uninstallation stage.

Maybe `uninsdeletevalue` shall be used.

**Comment by TLCFEM** [comment]
The new version still removes all other values. May need to investigate more about Inno settings and test in a virtual env.

**Comment by TLCFEM** [comment]
Probably needs to reopen this issue.

**Comment by rocksdanister** [comment]
When you update the application, there is custom script to uninstall existing install first before installing new version:
https://github.com/rocksdanister/lively/blob/942a9ca8f20dce4c0d30cd0e964ab3e8dcf61afa/src/installer/Script.iss#L152-L163

So its running the existing uninstaller for that; next update onwards this issue will not be present.

**Comment by TLCFEM** [comment]
Understand. I did not realise that the old one was used for uninstallation. Thanks.
