### ISSUE TITLE
The Lively Window is transparent when I do open lively

### ISSUE THREAD

**Issue by HyperCodec** [rocksdanister/lively#539]
The buttons and stuff work, but I can't see it because it's transparent. It worked before, but when I right-clicked the taskbar thingy (in the right corner of the screen) and clicked open it did that.
![livelyglitch](https://user-images.githubusercontent.com/72839119/120893030-078d1f00-c5df-11eb-9dc2-328a7198789b.png)

**Comment by HyperCodec** [comment]
I think I found out what happened. Basically, if I click any of the buttons on the left side, the window freezes, and then whenever the Lively window is reopened, it is transparent. If I exit the Lively process and then reopen it, the window will work, but clicking any of the left-side buttons will break it again. Does anyone have a fix?

**Comment by rocksdanister** [comment]
**Fill the issue template:**
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

also Avast will delete part of Lively after sometime https://github.com/rocksdanister/lively/issues/358

**Comment by HyperCodec** [comment]
There is no log file, I went to the appdata\local but there is no lively wallpaper folder. Also, the settings button won't work because any of those buttons on the left side freeze/crash it. My OS is Windows 10 (idk what year) and it doesn't matter which wallpaper I'm using, it always does it. Also, what do you mean by go to ... click on .... etc.?

**Comment by rocksdanister** [comment]
This is likely a graphics driver/hardware issue, I cant do much from my end.
In the meantime you can try the installer version of Lively instead of Store version to see if that fixes the issue.

Will reopen if its more common.

**Comment by HyperCodec** [comment]
Where do I download the installer version? There's no installer in the Github and I can't find a website or anything

**Comment by HyperCodec** [comment]
nvm i found it on the github.io

**Comment by HyperCodec** [comment]
yep it works with the installer version. btw how do I use dark mode? the installer only has the light theme and it said it adapts to windows's theme, but my windows theme is already dark

**Comment by rocksdanister** [comment]
Thats odd.. did you try switching windows theme from dark -> light -> dark.

**Comment by HyperCodec** [comment]
yep

**Comment by onyx-nxt** [comment]
I have the same issue.

**Comment by HyperCodec** [comment]
> I have the same issue.

With the theme or transparent window?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/540#issuecomment-861459152
