### ISSUE TITLE
Some videos don't work / Appear correctly

### ISSUE THREAD

**Issue by Sinon434** [rocksdanister/lively#54]
I've made my own animated background. However when trying to apply it as a background, it's just a black image. This has happened specifically when I exported my video as a .mov, using the H.264 codec, with lossless compression, bringing the file size to 110 MB.

With some lossy compression, bringing the file size to around 8 MB, it finally shows an image, however it now appears brighter then it should except for the last frame.
![Snipaste_2020-05-08_16-04-52](https://user-images.githubusercontent.com/64239856/81444796-c01b3180-9145-11ea-86ce-54e5939354f5.png)

I've tried switching the video player from Media Foundation to DirectShow, but with the exact same results.
One other thing I've noticed is when I downloading a animated background online with the same format, it displayed on lively exactly the way it should. So kinda lost on what is causing the problem.

**Comment by rocksdanister** [comment]
In LAV Video settings set Hardware Decoder to None.
or try to make sure LAV RGB Output levels is set to PC (0-255)
or try adjust video color settings in your gpu driver control panel (make sure decoder is set to DXVA2)
or try with mpv player.

Also use lossy videos to avoid using too much gpu memory.

**Comment by Sinon434** [comment]
Alright, I fixed it. Turns out I had odd "Image Enhancement" settings enabled in intel graphics control panel. Thanks for your help.
