### ISSUE TITLE
Lively becomes unstable after trying to access settings (windows store ver)

### ISSUE THREAD

**Issue by gaiking-uk** [rocksdanister/lively#540]
**Description**

The app seems fine (app starts, wallpaper loads, double-clicking Lively loads the main screen, etc) however when clicking the ⚙ / settings icon, the main screen stops responding properly... The wallpaper (e.g. Ribbon) continues to render, however can  the main screen no longer responds to user input, and can only be closed from the taskbar. Tray Icon is still responsive, however "Open Lively" will not re-open the main screen any more. `livelywpf.exe` needs to be stopped and re-started.

**To Reproduce**
1. Run Lively, open the main screen
2. (optional) select the Ribbon desktop
3. Select the ⚙ icon

**Expected behaviour**

Settings menu should open, but does not

**Technical information**
 - OS: Windows 10 Pro
 - Version: 21H1 (Windows Insider Build)
 - Build Info: OS 19043.1023 | Feat. Exp. Pack 120.2212.3740.0
 - CPU + RAM: Intel i7 9750H | 32GB
 - Graphics: Intel UHD 630 | NVidia GTX 1660 Ti
 - Package/Install method: Windows store

**Log file (unavailable)**
 - No logs present in expected directory
 - No "Lively" folder found in AppData or LocalAppData, possibly due to store-based install(?)
 - Unable to check log location in settings, due to issue
 
 **Next steps**
 - Will uninstall store app and try .exe-based installer

**Comment by rocksdanister** [comment]
For store app in Windows Run enter this:
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper`

**Comment by Alcheri-zz** [comment]
Same issue. This started yesterday.

Technical information

1. OS: 64 bit Windows 10 Professional (Version 10.0 2009 Build 19043.1023)
2. Version 21H1
2. CPU: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz   4.10 GHz
3. RAM: 32.0 GB (31.8 GB usable)
3. Graphics: Intel(R) UHD Graphics 630 1024 MB
4. Package/Install method: Windows store

Logfile:
[20210607_071654.txt](https://github.com/rocksdanister/lively/files/6604956/20210607_071654.txt)

**Comment by rocksdanister** [comment]
Can you show a video of the issue? and does it happen when no wallpaper is running?
Also try checking for update, there is a new v1.6.0.4 build.

**Comment by hawadallah** [comment]
same problem,,, any solution ?

**Comment by rocksdanister** [comment]
I pushed a new update v1.6.0.6 (should show up in show after few hours); see if it still happens after updating.

If it still hangs then share the logfile:
For store app in Windows Run enter this:
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\logs`

**Comment by ziplineslowdown** [comment]
i have the same problem and on the store there are no updates.
but its for all tabs not only the setting tab.
its just hangs and if i close and open it than it goes invisible.

**Comment by ziplineslowdown** [comment]
but its for all tabs not only the setting tab

**Comment by ziplineslowdown** [comment]
its just hangs and if i close and open it than it goes invisible

**Comment by ziplineslowdown** [comment]
The microsoft store updated it and it still happens.

**Comment by rocksdanister** [comment]
Try turning off input: 
`Lively settings -> Wallpaper -> Interaction -> Wallpaper Input -> OFF`
and see if the issue still happens.

**Comment by rocksdanister** [comment]
For the time being I downgraded the store version of Lively to old v1.5; If you already updated I don't think there is a straightforward way to downgrade - you will have to uninstall and then install from store again (make sure to backup the wallpapers folder.)

If you want the latest version of Lively with all the features and bugfixes then get the installer version:
https://github.com/rocksdanister/lively/releases

**Comment by Mervin-Abraham** [comment]
I have the same issue but the only solution to resolve this for me is by "Pause Wallpapers" --> "Close Wallpapers" --> "Exit" --> then restart the application and do the necessary changes to wallpaper or to the settings. (NOTE:- Do not left-click on the wallpaper at any point of time after the restart of the application. Activate the wallpaper towards the end and if you want to do any changes to the wallpaper after doing it then do the same steps again. )

Also there is a bug when the browser engine is selected "MS Edge" it shows "File not found" but when reverted to "CEF" it works fine. I dont understand what's the reason behind that and that too its an issue only to the default wallpapers. 

I have noticed that when the crash occurs more on animated wallpapers but not for wallpapers pulled from YouTube or videos of such kind. Hope these information's are useful to the devs.

**Comment by rocksdanister** [comment]
@JohnWickwastaken
1. Lively version number?
2. Is it Microsoft store version?

Edge is under development, next update (for installer version) will ship the working build.

**Comment by Mervin-Abraham** [comment]
@rocksdanister 

1. 1.0.44.0
2. Yes its the same as Microsoft store version 

Will try with the installer version in some time and see if the issue still occurs with me.

**Comment by rocksdanister** [comment]
Yeah that's the latest, I downgraded store to 1.0.38.0 (v1.5) which does not have this issue.. store does not downgrade automatically for existing users though.

Installer is fine based on reports.

If you want to try Edge webview:
https://github.com/rocksdanister/lively-beta
https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef#webview2-microsoft-edge

**Comment by Mervin-Abraham** [comment]
I believe that the issue lies here because I feel it runs smoother with MS Edge. The animations are more minorly smoother or maybe I am getting more frames or something on my Intel UHD 630. I dont know how to make NVIDIA GeForce GTX 1650 as the default graphic card for this application, maybe thats the issue.

If I run any animated wallpaper, the GPU utilization of Intel 630 sky rockets up to 99% and the CPU to 60-80%. It was not like this before, I could open up GTA V or n number of tabs open and no lag at all.

**Comment by rocksdanister** [comment]
@JohnWickwastaken @gaiking-uk 
I have an internal build with a possible fix, if anyone is interested in helping me test this send an email at awoo.git@gmail.com with title:
`Lively store beta participation request`
(The email needs to be the one used in Windows store.)

**Comment by rocksdanister** [comment]
New v1.7.0.4 update should be available in store now, hopefully its resolved.

**Comment by Mervin-Abraham** [comment]
Yeah, just got the update. Will look into it ✌🏼....
