### ISSUE TITLE
Unexpected theme difference between .exe and store-based installs

### ISSUE THREAD

**Issue by gaiking-uk** [rocksdanister/lively#541]
**Description**
 - Store-installed version uses dark dark (I assume following the 'system' setting)
 - .exe-Installed version uses light theme (I assume following the 'default app' setting)

**To Reproduce**
1. Go to `ms-settings:colors`
2. Set "choose your colour": `Custom`
3. Set "default Windows mode": `Dark`
4. Set "default App mode": `Light`
5. Install store-based version - it will appear dark
6. Install exe-based version - it will appear light

**Expected behavior**
Expected app to use the same theme logic (and install method should not impact/override this)

**Technical information**
 - OS: Windows 10 Pro
 - Version: 21H1 (Windows Insider Build)
 - Build Info: OS 19043.1023 | Feat. Exp. Pack 120.2212.3740.0
 - Windows mode (theme): Dark
 - Default app mode (theme): Light

**Comment by rocksdanister** [comment]
Store and installer are completely different implementations.. there will be differences between them; no need to make issues for it unless its a bug.
![Screenshot 2021-06-06 064927](https://user-images.githubusercontent.com/17554161/120909511-690ec580-c693-11eb-91fd-dc62b2ef323f.png)
![Screenshot 2021-06-06 064949](https://user-images.githubusercontent.com/17554161/120909590-15e94280-c694-11eb-82ef-aeddb8def151.png)

**Wiki:**
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions
**Installer src:**
https://github.com/rocksdanister/lively/tree/dev-v1.0-fluent-netcore/src
**Store src:**
https://github.com/rocksdanister/lively/tree/ms-store/src
