### ISSUE TITLE
When going into a full screen change the taskbar

### ISSUE THREAD

**Issue by J3fftw1** [rocksdanister/lively#542]
**Is your feature request related to a problem? Please describe.**
When going to a full screen or border less window have a way to automatically change the taskbar to blur or what ever is specified within the settings. This looks really weird when you are using clear and that would make it 10x better for visuals

**Describe the solution you'd like**
Have a setting within lively settings that you can have a setting to change this what I described above.

**Describe alternatives you've considered**
N/A
Would love to have a discussion with other users to come up with an alternative.

**Additional context**
N/A

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/507
