### ISSUE TITLE
Dual monitor problems with background usage

### ISSUE THREAD

**Issue by Carbon-Monoxide** [rocksdanister/lively#55]
I've noticed an issue, if you use more than one monitor, even though both monitors are in use, the program only stops the background on one screen. You can see this if you peek the at the desktop using the bottom right "peek at desktop feature". One screen turns black and the other keeps animating, and this thus eats resources to an in use screen.

**Comment by Carbon-Monoxide** [comment]
![lively bug thing](https://user-images.githubusercontent.com/38110094/81447555-7715ae00-9142-11ea-9fb1-6dceda847750.png)

**Comment by rocksdanister** [comment]
Settings - > Performance - > Display pause rule - > All Display(s)
