### ISSUE TITLE
lifely wallpaper doesn't respond o music anymore

### ISSUE THREAD

**Issue by KannNixOfficial** [rocksdanister/lively#550]
After i restart my pc the fluids v2 doesn'tt respond to music anymore. Try to close it and reopen it, bbut it change nothing. 
[lively_log_20210610_100429.zip](https://github.com/rocksdanister/lively/files/6629491/lively_log_20210610_100429.zip)

Hope you guys can help me:)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/276
