### ISSUE TITLE
MPV player opened in Windows bar

### ISSUE THREAD

**Issue by allanbrito90** [rocksdanister/lively#551]
**Describe the bug**
The MPV player is opened all time in Windows Taskbar loading like I'm transfering something.
I know that is the video status but it has some way to hide it?

**To Reproduce**
1. Just turn on the computer.

**Expected behavior**
I just want to hide the MPV Player

**Screenshots/Video**
![mpvplayerstatus](https://user-images.githubusercontent.com/15832221/121586745-605b1e00-ca0a-11eb-8fa8-ee96a3fbc7e4.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- Which wallpaper was running at the time if any: Ethernal Light

**Comment by rocksdanister** [comment]
1. Share the logfile.
2. Do you have any desktop/taskbar modification software running?

**Comment by allanbrito90** [comment]
[20210609_100635.txt](https://github.com/rocksdanister/lively/files/6634088/20210609_100635.txt)
[20210609_145203.txt](https://github.com/rocksdanister/lively/files/6634089/20210609_145203.txt)

Here are they. Thanks.

**Comment by allanbrito90** [comment]
Sorry, I didn't read the second question. Yes, I do. I have TaskbarX running, should I uninstall it?

**Comment by rocksdanister** [comment]
You can try quitting taskbarx and check if the problem happens still.

**Comment by allanbrito90** [comment]
Uninstalled and MPV still open.

**Comment by rocksdanister** [comment]
I can't reproduce this behavior. ~one unusual thing I see is your Windows is 32bit which might be the issue here.~

If its simple video file you can try switching to wpf video player in settings.

or alternatively try the alternative vlc video player:
https://youtu.be/8vgrsoBGoHI?t=88
(early, untested.)

**Comment by allanbrito90** [comment]
I changed to VLC Video Player, and the icon disappeared, but the video just plays once. 


![wallpaper_stopping](https://user-images.githubusercontent.com/15832221/121761037-13f40900-cb04-11eb-9d91-4d33d9f9e64e.gif)


After that, I changed again to MPV Player and the icon suddenly disappeared too. So, my problem is solved. Thank you very much for your time. These wallpapers are amazing.

**Comment by rocksdanister** [comment]
Windows is weird man :/
