### ISSUE TITLE
Can't Add more than 4 of local GIFs, and after try adding it crashs , you can't reopen the program

### ISSUE THREAD

**Issue by Reda-ELOUAHABI** [rocksdanister/lively#559]
**Describe the bug**
Can't Add more than 5 of local GIFs, and after try adding it crashs , you can't reopen the program normaly

**To Reproduce**
1. Go to '+ (add images/videos)'
2. Click on 'Browse'
3. Add 4 GIFs images separately
4. Try adding More , You can't 
5. close it and reopen the program , you can't  see anything 

**Expected behavior**
you can add images as much as you can , or simply it won't crash ,, just makes you feel you add too much for exemple

**Desktop (please complete the following information):**
 - OS:  Windows 10 

**Log file (Important)**
No Log file , I didn't find the directory !

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#having-a-problem-how-do-i-get-help--how-to-retrieve-log-files

**Comment by rocksdanister** [comment]
Duplicate https://github.com/rocksdanister/lively/issues/540
