### ISSUE TITLE
Incorrectly labeled file names in "add wallpaper"

### ISSUE THREAD

**Issue by jumpsplat120** [rocksdanister/lively#563]
If you go to the system audio section of the wiki (https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data#--system-audio), it says that you have to "Open as Website Audio (*.html) wallpaper in add wallpaper page to enable this feature." If you actually go to the add wallpaper option and look at what's available, there's two "Website (*.html)" listings, but no "Website Audio" listing.
![image](https://user-images.githubusercontent.com/8318935/121795494-51b96600-cbc6-11eb-87d8-a2582d2aa729.png)

**Comment by rocksdanister** [comment]
Yes I'm aware, its because there is plan to transition to adding arguments for audio instead of dropdown.
The 2nd one is website audio.
