### ISSUE TITLE
Lively keeps crashing

### ISSUE THREAD

**Issue by Volieb** [rocksdanister/lively#564]
Once my computer boots up, after about 5 minutes or so my screens will go black then come back on, but the lively wallpaper is gone. It comes back when I restart my PC but then the same thing happens.
[20210613_144138.txt](https://github.com/rocksdanister/lively/files/6644473/20210613_144138.txt)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/540
