### ISSUE TITLE
Auto-update Youtube-DL when present

### ISSUE THREAD

**Issue by jb95x** [rocksdanister/lively#57]
If the youtube-dl executable is present on the Documents\Lively Wallpaper\external\mpv\ folder, maybe youtube-dl could be run at Lively startup with the "-U" flag. This flag replaces the current executable with the new updated version.

EDIT: Maybe not at each startup, because of startup time, but atleast once a day.

**Comment by rocksdanister** [comment]
great idea.
It will be even better if I integrate it more into lively so that video information like title and description can be automatically added to wallpaper metadata.

**Comment by jb95x** [comment]
Futhermore, youtube-dl latest version executable can be obtained with this andy link https://youtube-dl.org/downloads/latest/youtube-dl.exe . There could be a button for the user to enable this feauture and automatically download it to that folder. The user would have to download mpv anyway, but is one less step.

**Comment by jb95x** [comment]
Ok. I just discovered the easiest way to do this, and it is on mpv :)
The zip of mpv comes with the folder **installer**, inside it there is a **updater.ps1** file, a powershell script!
If you copy it to a folder and execute it, it installs and updates mpv and youtube-dl in that folder. The script prompts for actions but my idea would be to modify it a bit and Lively could call this any time it's needed and update behind the scenes.

Attached is the script running on an empty folder.
![Capture](https://user-images.githubusercontent.com/22318240/82521737-4dd02700-9b1f-11ea-959c-e4254fe0613b.PNG)

**Comment by rocksdanister** [comment]
Going forward lively will be using libvlc for streams https://github.com/rocksdanister/lively/commit/7cf6b88c1c240968e75f2e600cbb726b3050a961

Its very quicker at fetching the video and since libvlc will be default library for localfiles it is included with the software, not sure if its possible to extract title etc.. will have to look into it.

Closing this issue for now.
