### ISSUE TITLE
Transparent window

### ISSUE THREAD

**Issue by arjunshindx8801** [rocksdanister/lively#570]
i cant see the window of lively wallpaper app although there is a border and the window works it changes wallpaper but i cant see its ists transparent
![Capturel](https://user-images.githubusercontent.com/86257073/122807993-e409ea00-d2e9-11eb-910c-585547c1691c.JPG)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/540#issuecomment-861459152
