### ISSUE TITLE
Stream custom start time

### ISSUE THREAD

**Issue by gunnahafta** [rocksdanister/lively#574]
When using a YouTube link with a start time to start playback e.g. 1 minute from the start, it doesn't seem to honor the time and just starts the stream from zero.

**Comment by rocksdanister** [comment]
This is not supported for streams.

**Comment by mukuzz** [comment]
Any update on this. I want to synchronize the live stream to my time zone. For example to play a live cam stream at a delay of 2.5 hrs.
