### ISSUE TITLE
Interactive wallpapers are not interactive when Web browser engine is MS Edge (WebView2)

### ISSUE THREAD

**Issue by leevalverde** [rocksdanister/lively#576]
**Describe the bug**
Interactivity on wallpapers (like in the Periodic Table or Waves) is not working if the Web browser engine is set to MS Edge (WebView2).

**To Reproduce**
1. Go to 'Settings'
2. Go to 'Wallpaper'
3. Select 'MS Edge' for Web Browser engine
4. Choose an interactive wallpaper (e.g. Periodic Table or Waves)
5. See error

**Expected behavior**
Interactive wallpapers should be interactive like in CEF engine.

**Screenshots/Video**
[2021-06-25 17-55-44.mp4](https://user-images.githubusercontent.com/73706919/123407819-ea26f180-d59b-11eb-8bf7-9fba42430dde.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 (OS Build 19042.1052)
- Periodic Table (also applies to any interactive wallpaper)

**Additional context**
N/A

**Log file (Important)**
[lively_log_20210625_180045.zip](https://github.com/rocksdanister/lively/files/6715402/lively_log_20210625_180045.zip)

**Comment by rocksdanister** [comment]
Stable v1.7 onwards will support this or try latest beta:
https://github.com/rocksdanister/lively-beta
