### ISSUE TITLE
Rainmeter compatibility

### ISSUE THREAD

**Issue by SmoochyPaws** [rocksdanister/lively#58]
Rainmeter docks and widgets are a perfect compliment to Lively wallpaper, but often with most Rainmeter skins, when interacted with, the lively wallpaper cuts to a black screen. The picture and  animation don't return until the wallpaper is clicked on. I assume this code was intentional to optimize computer performance in other applications, but for Rainmeter, it would be nice to leave wallpaper animations running while interacting with widgets. Is there a way to make Rainmeter more compatible with Lively Wallpaper?
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/65487980/82141261-4694da80-97fa-11ea-8306-297016443ca6.gif)

**Comment by rocksdanister** [comment]
Aa long as you have Pause when other apps in focus is turned in settings it shouldn't do that unless the skin dimension is close to monitor resolution or some overlay is running?

Can you name some of the skins causing the issue, I don't have this issue personally with rainmeter.

**Comment by SmoochyPaws** [comment]
Changing the wallpaper playback setting for "other application fullscreen" to nothing fixed the issue, and i am satisfied. For an application that truly is in fullscreen, however, I did enjoy the slight optimization. If there is no current work around where I can keep the setting on pause without the black screen issue, then these results are fine with me. 

If still relevant, the skin providing me with the most notable issue was "Windows 10 Style Tab for Rainmeter" 
https://www.deviantart.com/yorgash/art/Windows-10-Style-Tab-for-Rainmeter-594490097

Thank you for the quick assistance

**Comment by rocksdanister** [comment]
Your welcome.

You can add an exception for Rainmeter widgets by:
Performance -> Application Rules -> Add Rainmeter.exe (not the shortcut) -> Ignore

Its possible to check for the class of the foreground app, it should be under some rainmeter name.
Will add an explicit exception in future update.

**Comment by rocksdanister** [comment]
Updated latest release: https://github.com/rocksdanister/lively/releases/tag/v0.9.6.0
