### ISSUE TITLE
Shrinks the video in width. Video 16x9, monitor 5x4

### ISSUE THREAD

**Issue by wwwstalkerwww** [rocksdanister/lively#585]
**Describe the bug**
Shrinks the video in width. Video 16x9, monitor 5x4 (1280x1024)

**Screenshots/Video**
https://imgur.com/a/lMWFZuK

**Comment by rocksdanister** [comment]
![Screenshot 2021-06-28 065811](https://user-images.githubusercontent.com/17554161/123566798-395c6480-d7de-11eb-82c7-5eaff27669d5.png)
