### ISSUE TITLE
Different screensaver from running wallpaper

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#587]
**Is your feature request related to a problem? Please describe.**
Currently running live wallpapers are converted into screensaver; It would be nice to have an option to add wallpapers different from that to run as screensaver.

**Describe alternatives you've considered**
Using [Commandline control](https://github.com/rocksdanister/lively/wiki/Command-Line-Controls) script.

**Additional context**
Should the existing live wallpapers be terminated during screensaver operation to reduce resource usage.. or just pausing is enough?

![original](https://user-images.githubusercontent.com/17554161/191567713-4644d242-1769-4903-920a-155c8ec19130.jpg)

**Comment by Lomacar** [comment]
Actually, I am looking for a screensaver that can play videos in a loop and resume the video where it left off last time. So I am interested in having Lively only as a screensaver, not for live wallpaper. It seems like this currently cannot be done? So it would be nice if you could indeed select different options for wallpaper and screensaver, including None for wallpaper.

**Comment by TesterEU** [comment]
My topic  [#1554](https://github.com/rocksdanister/lively/issues/1554) was closed as a double so I'll list 2 important features for the above application:
+ ability to decide looping video playback.
+ the ability to decide to set sleep state of the screen (protects OLED displays) & the device (protects notebook's batteries), e.g. after a time or a playback loop.

**Comment by HyperCriSiS** [comment]
Is this a beta version or how can I get the possibility to choose a different screensaver than the wallpaper?

**Comment by rocksdanister** [comment]
**Different screensaver selector design early look**
There will be layout menu on the side, so each layout (span, duplicate and perscreen) will have separate screensaver saved. 


https://github.com/rocksdanister/lively/assets/17554161/c184e880-52e3-458a-bd9c-20efc9a40e4c

**Comment by Savisthorv** [comment]
Really looking forward to this feature, I currently am running displayfusion to achieve this, and that is using way more resources than it needs to just to do what this would do. It would be nice to be able to get rid of another program if this will accomplish different live wallpapers per monitor, and different screensavers per monitor without them having to be the same as current wallpapers.

**Comment by robaczek1** [comment]
yes, please! I enjoy the wallpaper I selected but would like to use an entirely different one for the screensaver! Is there any timeline for when this feature might get implemented, please? From your video it looks like something you have been actively working on, so please share some rough idea when you may offer this, even in an early sneak peak version ;-)

**Comment by rocksdanister** [comment]
If things go according to plan next update (this month.)

**Comment by robaczek1** [comment]
> If things go according to plan next update (this month.)

oh I can't wait!!! :-)

**Comment by rocksdanister** [comment]
Took an extra month, its completed:

https://github.com/rocksdanister/lively/assets/17554161/109e44db-473e-45ea-a9d5-4e533bd056f1

Screensavers can now also work without having to run Lively in the background.

Coming on May update.

**Comment by robaczek1** [comment]
hello :-) Just wanted to ask if the next update is still on track to be released in May? ;-)

**Comment by robaczek1** [comment]
hohoho! Xmas came early this year! Fantastic! Thank you for your excellent work!

Quick question, just in case I missed it, I presume all available live wallpapers / screensavers are stored locally on my computer, correct?

**Comment by rocksdanister** [comment]
Yes, lively just remembers the location unless its lively .zip file then its installed to appdata folder.
