### ISSUE TITLE
youtube video: failed to catch application window

### ISSUE THREAD

**Issue by aeneas01** [rocksdanister/lively#59]
error: failed to catch application window. the wallpaper (application) is taking too long to start...

**Comment by rocksdanister** [comment]
What application did you try to load as wallpaper?

**Comment by aeneas01** [comment]
i'm trying to drag a youtube vid )earth views: earth from space seen from the iss) to the lively console when i get the error... have mpv and youtube-dl.exe installed.

![01](https://user-images.githubusercontent.com/17071068/82172817-27d92700-9880-11ea-9907-48fa7ead20f8.png)

**Comment by rocksdanister** [comment]
Something changed in mpv latest version https://github.com/rocksdanister/lively/issues/13, currently will only work with the version of mpv listed in the wiki: https://github.com/rocksdanister/lively/wiki/Youtube-Wallpaper

**Comment by aeneas01** [comment]
yes, that's the mpv player i installed... well actually i didn't "install" it (didn't use the mpv install bat), instead i copied the extracted zip contents to c:\users\name\documents\lively wallpaper\external\mpv per the instructions, and that's where i also copied the youtube-dl.exe file as well.... i also tried to install mv c+ 2010 but got an error saying a new newer version had already been installed.

**Comment by rocksdanister** [comment]
1. To verify if youtube-dl is working properly: open mpv.exe and drag and drop the youtube link into it, see if that is loading.

2. Is your internet slow? Try closing lively from tray then open `SaveData\lively_config.json` using notepad and edit the `WallpaperWaitTime` value, its in milliseconds (Default is 30sec)

**Comment by aeneas01** [comment]
mpv crashes when i drag a youtube vid to it, just closes out... my internet speed is fast.

**Comment by aeneas01** [comment]
btw, thanks very much for your help, very much appreciated.... also, i get the error message after about 5 secs even tho message is saying that it's taking longer than 30 secs...

**Comment by rocksdanister** [comment]
Your welcome.
> get the error message after about 5
Yes, meaning the application/mpv already exited.

This looks like a [youtube-dl](https://github.com/ytdl-org/youtube-dl) issue to me, I tried with the latest version of youtube-dl and working on my end.

Also to see whats happening with mpv, do the same as above but add -log-file

> https://www.youtube.com/watch?v=ojhjBrzmNjo --force-window=yes --loop-file --keep-open --hwdec=yes --ytdl-format bestvideo[height<=720]+bestaudio/best[height<=720] -log-file log.txt

the file log.txt will be saved in mpv folder.

**Comment by iggySeawolf** [comment]
@aeneas01 Check if youtube-dl.exe is working properly. Use the command prompt and download a youtube video. If it succeeds, you can manually add the youtube video to Lively from the "Type" tab from application.

This is what I did since my drag and drop feature also caused the "Failed to catch.." error.

**Comment by aeneas01** [comment]
@iggySeawolf 

yes, that works fine, as does downloading video wallpaper and dragging it to lively, just can't seem to drag vids straight from youtube to lively, no big deal really....

a couple of questions tho:

1. in settings > video > video player it was set to "media foundation", i changed it to mpv but i don't notice any difference, should i?

2. are there recommended settings in the settings tab, beyond the default settings?

3. is lively known to interfere with other applications such as photoshop, or another video player using madvr video processor? i was recently using photoshop and my keyboard went on the fritz, couldn't use it photoshop or in any other application, my mouse began acting unpredictably... i was forced to reboot my system and everything returned to normal, but this was without lively loaded... then again i'm wondering if the issues could have been caused by the recently installed winstep nexus dock or rainmeter? on reboot i disabled all of these (lively, nexus and lively) and haven't had a problem since, haven't had a chance to load each one by one to see if any are causing the keyboard / mouse issues...

**Comment by rocksdanister** [comment]
1. https://github.com/rocksdanister/lively/wiki/Video-Guide
2. Default should be good enough.
3. Not likely, if you want you can disable mouse input in Settings Interaction -> Off

As this is a youtube-dl/mpv issue I can't recreate on my end and not directly related to lively I'm closing it for now.
