### ISSUE TITLE
Video wallpaper not working (Windows N)

### ISSUE THREAD

**Issue by L0bodomy** [rocksdanister/lively#592]
**Describe the bug**
I'm getting an error that a file could not be found, prompting me to ask for help. The strange thing is that the name of the file that it does not find does not appear again, but it cannot be executed and says to contact me. The same happens when I try to upload a Wallpaper

**To Reproduce**
1. Go to Lively aplicattion
2. Click on Eternal Light or Add Wallpaper and select Browse 
3. See error

**Expected behavior**
There should appear the wallpaper that I chose or upload the file that I chose

**Screenshots/Video**
![imagen_2021-07-04_122133](https://user-images.githubusercontent.com/86921793/124390511-5e5f4480-dcc2-11eb-961e-b2d0efc6a044.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro N
- wallpaper: Eternal Light

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20210704_113909.zip](https://github.com/rocksdanister/lively/files/6760118/lively_log_20210704_113909.zip)

**Comment by rocksdanister** [comment]
The initial setup wizard should have suggested.. Windows N require additional codec installation:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by L0bodomy** [comment]
but, I installed all that and I put it as it was requested. Now the file that cannot be found reappeared
![imagen_2021-07-05_100443](https://user-images.githubusercontent.com/86921793/124475721-6bd70600-dd78-11eb-92ed-4e86b9ba530f.png)
I also reinstalled everything and it didn't work

**Comment by rocksdanister** [comment]
This looks like a Windows issue.
Search for "How to fix MFPLAT.DLL" online.
You are on your own, I don't have Windows N and this issue is unrelated to Lively.

or alternatively try the alternative vlc video player (installer version of Lively):
https://youtu.be/8vgrsoBGoHI?t=88
(early, untested.)
