### ISSUE TITLE
Rain v2 Crash 

### ISSUE THREAD

**Issue by xtrax-ya3** [rocksdanister/lively#593]
I was trying the new update where you can customize the "Rain v2" wallpaper, and as I was playing around with the sliders, the wallpaper just stopped working and closed. I tried to click on it again but it would give me this error message:

![image](https://user-images.githubusercontent.com/55789427/124435498-bad36a00-dd7d-11eb-8036-0e8e735638a7.png)

1. Go to Lively Wallpaper
2. Click on "Rain v2"
3. Right Click on the Lively icon in the taskbar
4. Click on "Customize Wallpaper"
5. Play around with the sliders until it crashes

 - OS: Windows 10* 64-bit

Log File:
[lively_log_20210705_103234.zip](https://github.com/rocksdanister/lively/files/6762562/lively_log_20210705_103234.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/358
