### ISSUE TITLE
Lively command line utility giving StartIndex error

### ISSUE THREAD

**Issue by Ucef27** [rocksdanister/lively#596]
**Describe the bug**
When I try to use livelycu it gives me "Error: StartIndex cannot be less than zero. (Parameter 'startIndex')"
I have put it into a path location and using the livelywpf.exe works fine

**To Reproduce**
Use latest version of command line utility and put it in a PATH folder.
run livelycu in command prompt

**Expected behavior**
it should not give me an eror

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/51302795/124530856-4a5b3600-dddb-11eb-8d68-37fb0523c01c.png)

**Desktop (please complete the following information):**
windows 10 21H1
mp4 wallpapers

**Log file (Important)**
[lively_log_20210705_215018.zip](https://github.com/rocksdanister/lively/files/6766778/lively_log_20210705_215018.zip)

**Comment by rocksdanister** [comment]
Why don't you give any command?
`livelycu --help`
`livelycu app --showApp true`

**Comment by Ucef27** [comment]
lol Thanks a lot.
