### ISSUE TITLE
Volume Sliders for Audio Output

### ISSUE THREAD

**Issue by jb95x** [rocksdanister/lively#60]
Currently it's possible to Enable or Disable audio on Video, Browser, Streams and Aplications used as a wallpaper, but would be really nice to have sliders to control volume! 
Imagine booting up the computer and having as wallpaper that nice Chill Music Stream art with some nice quite music on the background from the stream :)

**Comment by rocksdanister** [comment]
The audio controls are in need of multiple changes:

- [ ]  Single "Audio" section in settings with all the controls listed.

- [ ] Per Wallpaper mute/audio slider.

- [ ] Enable audio in multiple monitor systems with additional options such as Play audio based on: Wallpaper running screen, which screen foreground app is on, which screen Cursor is at.
