### ISSUE TITLE
Taskbar goes white whenever i open terraria/tmodloader or some other programs

### ISSUE THREAD

**Issue by Saki177013** [rocksdanister/lively#602]
i have the taskbar theme set to wallpaper and sometimes when i open or swich to terraria, tmodloader, or sometimes minecraft, or other programs in fullscreen the taskbar goes white and i have to go to the taskbar settings in lively and set it to another theme and then set it back to wallpaper

**Comment by rocksdanister** [comment]
possibly duplicate: https://github.com/rocksdanister/lively/issues/538
