### ISSUE TITLE
Trouble adding video wallpaper / Mpv player crash

### ISSUE THREAD

**Issue by lefabmoonface** [rocksdanister/lively#603]
**Describe the bug**
Unable to Add Lively Wallpaper with MP4 file via the '+' icon and also when manually dragged the file to the Library.
Also was unable to set one of the default wallpaper named 'Eternal Light' which was already in the Library upon installation.
Have uninstalled Lively Wallpaper app and reinstalled for multiple times however same error kept prompting.

**To Reproduce**
1. Go to '+' icon to Add Wallpaper
2. Click on 'Browse' to select file
3. Select MP4 file on desktop Pictures
4. Click 'Open' 
5. See error

**Expected behavior**
Click on '+' icon to add desired MP4 file or manually drag the desired MP4 file to Library.
Library to process and load MP4 file and will appear upon completing upload.
Click on desired MP4 file and Desktop will automatically set to the MP4 Lively Wallpaper.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![Screenshot 2021-07-11 020542](https://user-images.githubusercontent.com/87242606/125172518-c8a94500-e1ec-11eb-869d-b5d6e74136d3.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
- Version	21H1
- Installed on ‎2/‎12/‎2020
- OS build 19043.1083
- Experience Windows Feature Experience Pack 120.2212.3530.0
- Processor AMD Ryzen 3 3100 4-Core Processor, 3600 Mhz, 4 Core(s), 8 Logical Processor(s)

**Log file (Important)**
Share the diagnostic files by:
[20210711_014509.txt](https://github.com/rocksdanister/lively/files/6795751/20210711_014509.txt)

**Comment by rocksdanister** [comment]
Looks like mpv videoplayer is crashing (not leaving any log.. weird.)
Can you try playing the file included mpv player directly to check?
For non-admin install:

`C:\Users\<UserName>\AppData\Local\Programs\Lively Wallpaper\plugins\mpv\`

For admin install:

`C:\Program Files (x86)\Lively Wallpaper\plugins\mpv\`

**Comment by rocksdanister** [comment]
Although not ideal, temporarily you can just switch to wmf videoplayer:
`Lively settings -> Wallpaper -> Video -> Video Player`

**Comment by lefabmoonface** [comment]
> Although not ideal, temporarily you can just switch to wmf videoplayer:
> `Lively settings -> Wallpaper -> Video -> Video Player`

Ahh, I see.. I've tried it and it works! Thanks so much for your help :)
