### ISSUE TITLE
Double click to open anything in desktop in Win11 is not working

### ISSUE THREAD

**Issue by thekingstallion** [rocksdanister/lively#604]
Double click to open anything in desktop in Win11 is not working, while to open it from right click menu is working fine.

Did not face this issue in Windows10 though.

**Comment by rocksdanister** [comment]
I don't understand, better description would help.
What is anything - desktop icons?

**Comment by thekingstallion** [comment]
Yes any desktop icons and /files on desktop

**Comment by rocksdanister** [comment]
Working fine for me.
1. Do you have any third party overlay/desktop modification software installed?
2. What is your Windows 11 version including build number?
3. Try turning off wallpaper input: Lively settings -> Wallpaper -> Interaction -> Wallpaper Input -> OFF and check again?

**Comment by thekingstallion** [comment]
1. No
2. Windows 11 Home Single Language | OS Build: 22000.65
3. It's working now. Will update if problem persist
