### ISSUE TITLE
I can't add another wallpaper to the lively app

### ISSUE THREAD

**Issue by UniversalEnd** [rocksdanister/lively#608]
My cousin told me that he wasn't able to add another wallpaper to the app and kept getting a error saying "Oops... Looks like something went wrong :(
In order to better understand this error and fix the issue, share the log file with the developer.
Instructions for sharing log file:
https://github.com/rocksdanister/lively/wiki"

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#having-a-problem-how-do-i-get-help--how-to-retrieve-log-files
