### ISSUE TITLE
I can't upload any video wallpapers / Windows N

### ISSUE THREAD

**Issue by UniversalEnd** [rocksdanister/lively#609]
[20210712_011458.txt](https://github.com/rocksdanister/lively/files/6797726/20210712_011458.txt)

(tell me if this works or not, I just drag dropped it here)

**Comment by rocksdanister** [comment]
>OS: Microsoft Windows 10 Enterprise N 10.0.19042

The initial setup wizard should have suggested.. Windows N require additional codec installation:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by WORLDWIDEKAI** [comment]
I don't think I have windows n and it does not work even after downloading codec

**Comment by rocksdanister** [comment]
>I don't think I have windows n

From the logs https://github.com/rocksdanister/lively/issues/632#issue-948915834

```
2021-07-12 01:15:04.9329|INFO|livelywpf.NLogger|
Lively v1.7.0.2 x64 desktop-native en-PK
OS: Microsoft Windows 10 Enterprise N 10.0.19042
CPU: Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
GPU: Intel(R) HD Graphics 4000
```

**Comment by WORLDWIDEKAI** [comment]
Yeah that's my fault i just checked but I'm not sure which file I'm supposed to download

**Comment by rocksdanister** [comment]
https://www.codecguide.com/windows_media_codecs.htm
**Windows 10 version 1909/2004/2009**
You can acquire the package through Windows settings:
`Start > Settings > Apps > Apps & Features > Optional Features > Add a feature > Media Feature Pack`
