### ISSUE TITLE
Commandline support - Method to automate choosing between desktops.

### ISSUE THREAD

**Issue by Geektoolkit** [rocksdanister/lively#61]
I think it would be handy to have a way to change visualizations through some sort of automatable system.  It could be:
Rest API
Command line parameter
shortcut keystroke
etc.

I think that would allow for some interesting 'home automation' scenarios..for instance I could then work to integrate it with home assistant, and then tell alexa 'set halo scene' and have my desktop change to a halo background....  

This could also enable stuff like 'if I detect netflix on the tv, change background to a movie poster' scenarios. 

Right now I am not sure if there is a way to do this or not.

**Comment by rocksdanister** [comment]
Both commandline mode and keyboard shortcuts are planned, will take time to implement new features as I'm currently in the process of rewriting things and changing the UI completely.

I can't give you a concrete answer on how it will be implemented since I have not looked into it right now, will update it here.

**Comment by Geektoolkit** [comment]
Thankyou that's exciting! I'm not particular on how it's implemented, as long as there is a form of external control that'll allow for some really cool scenarios (and in a way external control can become it's own features that you wont have to build in...for instance I could do a simple task manager script using the command line to change my background from 'work mode' to 'off work' mode. Playlists based on time of year, etc. by just controlling it externally and plugging it into other systems.  I could even do a 'while 3d printer is printing stream the camera, otherwise use this background' type stuff

**Comment by BruceLee569** [comment]
+1
@rocksdanister 
Is there a way to modify the current dynamic wallpaper? From the command line, specify the wallpaper path, or some other hack method. ☺

**Comment by rocksdanister** [comment]
By modify dynamic wallpaper you mean change the current running wallpaper without opening lively? answer is no.

This require a server of sort to be implemented, something like gRPC and I haven't done that yet.

**Comment by BruceLee569** [comment]
> By modify dynamic wallpaper you mean change the current running wallpaper without opening lively? answer is no.
> 
> This require a server of sort to be implemented, something like gRPC and I haven't done that yet.

like this is great: https://wallpaper-engine.fandom.com/wiki/Command_Line

**Comment by rocksdanister** [comment]
Its mostly done, should be able to push it next update:

https://user-images.githubusercontent.com/17554161/105576082-5eaff700-5d96-11eb-995d-1563c5d8cb5f.mp4

Documentation:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls
