### ISSUE TITLE
Mpv crash - Stream wallpaper [AUDCLNT_E_UNSUPPORTED_FORMAT]

### ISSUE THREAD

**Issue by KushandMetal69** [rocksdanister/lively#610]
Every time I try to add a new wallpaper from Youtube, it always pops up with an error message. I downloaded lively and was able to set one of the default wallpapers, but it fails every time I try to add a youtube video.
[lively_log_20210711_173504.zip](https://github.com/rocksdanister/lively/files/6797795/lively_log_20210711_173504.zip)

Desktop OS:
Windows version 21H1 (OS Build 19043.1083)

**Comment by rocksdanister** [comment]
> [ao/wasapi] Error finding shared mode format: AUDCLNT_E_UNSUPPORTED_FORMAT (0x88890008)

Can you try dropping the video link directly into mpv player?
For non-admin install:

`C:\Users\<UserName>\AppData\Local\Programs\Lively Wallpaper\plugins\mpv\`

For admin install:

`C:\Program Files (x86)\Lively Wallpaper\plugins\mpv\`
