### ISSUE TITLE
Improvements/Enhancements Request (Ideas)

### ISSUE THREAD

**Issue by drosestudios** [rocksdanister/lively#616]
Hi.. How are you? So i have some ideas for this project that maybe could be added to it!, I really like Lively Wallpaper is the best, So here's the ideas list, Check it out:

Centered Taskbar Icons
- I really want a new option that add this to lively, In the update "v1.5" was added the option for make it fluent and other styles to the taskbar and i really miss a option to centered my icons in the center of the taskbar.

Steam Wallpapers Support
- I don't know much about this, i want support for the steam wallpapers with the extensions "Json & Pkg" if this could be achieve, I will be really glad to have this on lively.

Themes And Improvements
- Ok so a new "Themes" Option could be really good implementation, A Light and Dark Theme, Customization in some aspects maybe, Without have to use the sync with system and I want a new Option in "Tiles Size", Like a "Super Smaller" option that makes the tiles more smaller for have more wallpapers in view and this other improvement is only my opinion, i think that the "Help" Button in main menu could be a submenu in Settings Like a "Credits" Tab only for that stuff.

**Comment by CEbbinghaus** [comment]
@FrozByteOfficial For Centered Icons you can use [TaskbarX](https://github.com/ChrisAnd1998/TaskbarX) It also lets you set the background to Fluent. just turn off any taskbar settings in Lively

**Comment by FrozByteOfficial** [comment]
> @FrozByteOfficial For Centered Icons you can use [TaskbarX](https://github.com/ChrisAnd1998/TaskbarX) It also lets you set the background to Fluent. just turn off any taskbar settings in Lively

**Comment by drosestudios** [comment]
> @FrozByteOfficial For Centered Icons you can use [TaskbarX](https://github.com/ChrisAnd1998/TaskbarX) It also lets you set the background to Fluent. just turn off any taskbar settings in Lively

Yep Thanks! ^^

**Comment by rocksdanister** [comment]
>Centered Taskbar Icons

https://github.com/rocksdanister/lively/issues/494

>Steam Wallpapers Support

https://github.com/rocksdanister/lively/issues/208

Please don't group multiple suggestions into one issue with a general title.

Closing this, make a new issue for the theme improvements.
