### ISSUE TITLE
Taskbar stops being clear when I enter a fullscreen game

### ISSUE THREAD

**Issue by Swishe241** [rocksdanister/lively#624]
Whenever i want to play a game in fullscreen, my taskbar goes from being clear to being blue. (none of the links i sent are viruses, so don't worry)

To Reproduce
1. Go to any game that has fullscreen (e.g Minecraft)
2. Turn on the fullscreen
3. Alt+Tab or minimize the game and go to the desktop
4. See that the taskbar is now solid, not clear.

Expected behavior
I always expect it to go like this since i started using lively (1 day ago)

before going into a fullscreen game
https://cdn.discordapp.com/attachments/843860718402797640/865670241320435762/unknown.png

after going into a fullscreen game
https://cdn.discordapp.com/attachments/756481291679170622/866118895085027328/unknown.png

Desktop 
 - OS: Windows 10 Pro
 - https://mylivewallpapers.com/games/minecraft-animated-wallpaper-2/
(link to the wallpaper i'm using)

Additional context
Also, when this issue happens i always have to go to my windows taskbar settings, color, and activate/deactivate transparency effects. This way, it returns to being clear. When i asked my friend, who also uses lively at the same settings as i do, if this issue also happened to him, and he said that it didn't.

Log files (i didn't know which one to send so i sent all 3 of them, if you copy and paste the link into your URL, it'll download a notepad file.)
https://github.com/rocksdanister/lively/files/6835494/20210717_121442.txt
https://github.com/rocksdanister/lively/files/6835497/20210716_204948.txt
https://github.com/rocksdanister/lively/files/6835499/20210716_153628.txt

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/538
