### ISSUE TITLE
Wallpapers are missing when resuming from standby/sleep

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#628]
**Note : I did do all these above. No hit on the keyword "sleep" and nothing of use in the Wiki.**

**Describe the bug**
When I wake my computer from sleep, the "Rain" wallpaper is not the one shown. My default wallpapers are shown.

**To Reproduce**

1. Use lively and your computer as usual.
2. At an ungodly hour, go to sleep and put your computer to sleep. It deserves the rest.
3. The next morning, wake up energized. Brew some coffee.
4. Wake the computer from sleep by impatiently hitting the spacebar over and over.
5. Input your password. Of course, hit a wrong key. Input your password correctly.
6. Lively wallpapers are supposed to be there. They're not. Cry a bit.
7. Close the lively software that is running in the taskbar and open it again.
8. Be happy.

**Expected behavior**
I expect the lively wallpapers to be displayed when my computer wakes from sleep and lively is running.

**Screenshots/Video**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 (20H2 -- 19042.1110)
- Rain V2, but it was not running which is the bug.

**Additional context**
I like the program very much. :) Which is why I want it to run all the time. :)

**Log file (Important)**
Sir, yes sir!
[lively_log_20210718_093205.zip](https://github.com/rocksdanister/lively/files/6836352/lively_log_20210718_093205.zip)

**Comment by rocksdanister** [comment]
`2021-07-16 07:18:05.2750|ERROR|livelywpf.NLogger|failed to set parent, HRESULT:14001`

Does this happen often, can the bug be reproduced after system restart?

**Comment by ghost** [comment]
It happens every time I wake my computer from sleep. Let me check if I restart right now and check when I come back home tonight.

**Comment by ghost** [comment]
Hello! Over the last 4 days, came out multiple time from sleep without Lively working correctly. I only put my computer to sleep at night. I think it worked once after reboot, then did not work the following 3 attempts. Can confirm the bug can be reproduced.

**Comment by rocksdanister** [comment]
Share the logfile everytime it happens, I want to verify if the error is same.
(don't have to share everything, just the latest logfile after logging in from sleep.)

**Comment by rocksdanister** [comment]
Do you have Windows slideshow feature enabled? possibly related https://github.com/rocksdanister/lively/issues/639

**Comment by ghost** [comment]
You know what, I was indeed using the feature. I since disabled the feature and changed to a solid black background. Will report back if it stopped. 

UNRELATED ISSUE : the raindrop background becomes "corrupted" after a couple of days. The individual rain drops flicker and go black and are generally "garbled". I changed from Rain V2 to the ribbon one. If this issue goes away, I will try to get the rain v2 back and see if it's related.

**Comment by rocksdanister** [comment]
>UNRELATED ISSUE : the raindrop background becomes "corrupted" after a couple of days. The individual rain drops flicker and go black and are generally "garbled". I changed from Rain V2 to the ribbon one. If this issue goes away, I will try to get the rain v2 back and see if it's related.

Nah.. I am aware of this, that issue is specific to the rain shader code and not lively application itself.. likely a variable is overflowing.

>u know what, I was indeed using the feature. I since disabled the feature and changed to a solid black background. Will report back if it stopped.

I think picture background would be a better choice, all testing is done in that mode.

**Comment by rocksdanister** [comment]
moved : https://github.com/rocksdanister/lively/issues/802

**Comment by luckymurari** [comment]
> Do you have Windows slideshow feature enabled? possibly related #639

This worked for me. Disabling the slideshow helped
