### ISSUE TITLE
Wallpapers don't work at all

### ISSUE THREAD

**Issue by KoikDaisy** [rocksdanister/lively#638]
**Describe the bug**
Despite being selected, wallpapers don't show up at all.

**To Reproduce**
1. Go to Lively's library menu
2. Click on any wallpaper

**Expected behavior**
Wallpaper becomes enabled

**Screenshots/Video**
https://gyazo.com/ecbc0b45d333420843ff363b6657a635

**Desktop:**
 - OS: Windows 10 Pro 1909
- Video wallpaper

**Additional context**
I installed the latest version, reinstalled it, turned off my PC, and even tried uninstalling it and installing an earlier version, with no success.

**Log file**
[lively_log_20210724_000049.zip](https://github.com/rocksdanister/lively/files/6871871/lively_log_20210724_000049.zip)

**Comment by rocksdanister** [comment]
What all software do you have running on your system?

**Comment by KoikDaisy** [comment]
Rainmeter, Fences, f.lux

**Comment by rocksdanister** [comment]
Its Fences.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/109

**Comment by rocksdanister** [comment]
https://www.reddit.com/r/Rainmeter/comments/opul05/stardock_fences_update_completely_incompatible/
