### ISSUE TITLE
Animating wallpaper disappears after opening pc from lock screen / Windows slideshow breaks lively

### ISSUE THREAD

**Issue by nishit15sharma** [rocksdanister/lively#639]
**Describe the bug:**
Lively App stops animating wallpaper after opening Windows account through lock screen

**To Reproduce:**
1) Before installing _Lively Wallpaper_:
  a) Go to _Windows Settings_ by pressing _Win+I_
  b) Go to _Personalization_
  c) Select _Slideshow_ under _Background_ drop-box
  d) Select _Browse_ under _Choose albums for your slideshow_
  e) Select 1 or more images from your folders.
2) a) Install _Lively Wallpaper_
    b) Go to _Start_ by pressing _Win_
    c) Type in _Lively_ and select _Open_ under _Lively Wallpaper_
    d) Right-Click on any animation and click on _Set as Wallpaper_
    e) In Side-bar on the left, click on the Gear Button to go to _Settings_
    f) Go to _System_ tab and under _Taskbar Theme_ drop-box, select _Clear_
    g) Your Wallpaper should be animated now and your taskbar should be transparent to show the wallpaper
3) a) Go to _Start_ by pressing _Win_
    b) Select _Power_ and then select _Hibernate_
    c) In a few minutes, turn your laptop back on
    d) Now log in to your Windows Account by entering your password on the lock screen
4) You will now notice that although the taskbar is transparent and the flower icon of Lively in the taskbar is colourful (indicating it is running), the wallpaper will not be animated but instead your default image will be shown.
5) a) Right-Click on the Flower icon of Lively Wallpaper in the taskbar
    b) Press _Exit_
    c) Open Lively Wallpaper through Start Search
    d) Lively should work properly and your wallpaper will now be animated

**Expected Behaviour:**
It is expected that after the account is opened through the lock-screen, Lively works perfectly and the wallpaper is animated.

**Laptop:**
 •OS: Windows 10 64-bit

**Video:**
https://user-images.githubusercontent.com/72212168/126860255-a4b91ca9-207f-46dd-b95f-c7546cfc97ff.mp4

**Log File:**
[lively_log_20210724_122746.zip](https://github.com/rocksdanister/lively/files/6872030/lively_log_20210724_122746.zip)

**Comment by rocksdanister** [comment]
1. Does this still happen when Slideshow feature is turned off?
2. Logs don't say much in this case because everytime you are exiting the app after logging in.. it would be useful if you try setting a new wallpaper after logging in when this issue is found.

**Comment by nishit15sharma** [comment]
1) No, it does not. However, I do not want to not use the slideshow feature.
2) Sorry but I didn't understand the advice?

Regards,
Nishit Sharma

**Comment by rocksdanister** [comment]
>1) No, it does not. However, I do not want to not use the slideshow feature.

Windows does not natively supports live wallpapers.. what lively is doing is workarounds to achieve this feature.. so there will be compatibility issues with some windows functions - in this case I am guessing the slideshow feature is destroying the workerw lively is using.

Creating workarounds for every little thing is time consuming and I feel that time is better spend elsewhere especially in this case if you are already using live wallpaper I don't see the reason to use Windows slideshow feature alongside.

As a general fix I will verify the workerw state after resuming from sleep, but keep in mind this is not a proper fix for slideshow and there maybe other underlying problems using that feature with lively.. so it is advised to turn off slideshow.

**Comment by rocksdanister** [comment]
moved: https://github.com/rocksdanister/lively/issues/802
