### ISSUE TITLE
This program does not support the version of Windows your computer is running.

### ISSUE THREAD

**Issue by itZvignesZ** [rocksdanister/lively#650]
IDK Why Im Getting This Error My Windows Specs

Windows 7 Professional Service Pack 1
32bit

I hope my problem would be solved 
![image](https://user-images.githubusercontent.com/87363298/127521681-8e30a0e7-4576-4cb0-a374-bfeeec8f1f77.png)

**Comment by rocksdanister** [comment]
>System Requirement
OS: Windows 10 1903 or above (Installer version.)
...

https://github.com/rocksdanister/lively/wiki/Getting-Started
