### ISSUE TITLE
Desktop icons not opening 

### ISSUE THREAD

**Issue by AakashGiri12** [rocksdanister/lively#652]
OS: Windows 11
Currently running a live wallpaper The HILL shader generated Hill, double-clicking the desktop icons is not opening them nor it selects the icons. This issue not happening only with pre-given live wallpapers but also with the wallpapers downloaded from other sites. It's ruining the mood of live wallpaper. 
Hope you will solve the issue asap.
I have shared my Log File as well.
[lively_log_20210730_101656.zip](https://github.com/rocksdanister/lively/files/6905142/lively_log_20210730_101656.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/174
