### ISSUE TITLE
Lively not working / stardock fences incompatibility.

### ISSUE THREAD

**Issue by NexRX** [rocksdanister/lively#653]
**Describe the bug**
Wallpapers do not appear on the desktop when updated to the latest Windows 10 version (& lively).
Previews will work fine and wallpapers with audio are still audible but nevertheless invisible still. 

**To Reproduce**
1. Install/use the latest Windows 10 update (21H1)
2. Use either Latest GitHub Release or MS Store Release of Lively
3. Attempt to set a wallpaper.

**Expected behavior**
For wallpapers to appear on the desktop.

**Screenshots/Video**
Not applicable. There is just an absence of wallpaper with typical use.

**Desktop (please complete the following information):**
 - OS: Version	10.0.19043 Build 19043 (21H1)
- Any and all of the default ones, included imported videos.

**Additional context**
I tested this on my laptop which had lively working fine! Then to make sure it was a windows update breaking something, I updated my laptop and after the win update I had the same bug regardless of Git release or MS Store Release.

**Log file (Important)**
[20210729_231819.txt](https://github.com/rocksdanister/lively/files/6906044/20210729_231819.txt)

**Comment by rocksdanister** [comment]
Working fine, I personally use Windows 10 21H1.
Maybe its something simple.. have you tried restarting Windows?

**Comment by NexRX** [comment]
Yeah, I have tried that many times. Its weird because i was actually able to reproduce this issue on a second device. I can actually try on a third Laptop I have that's not updated yet. I'm going to see if I can reproduce it again. :)

**Comment by rocksdanister** [comment]
Do you perhaps have utilities that modify desktop like Stardock Fences?

**Comment by NexRX** [comment]
> Do you perhaps have utilities that modify desktop like Stardock Fences?

I do actually have fences, by chance. But I already tested with fences disabled. I guess it could still be interfering.
The windows update itself is what triggered it to stop working, still. But it could be a conflict between fences and lively.

**Comment by rocksdanister** [comment]
https://www.reddit.com/r/Rainmeter/comments/opul05/stardock_fences_update_completely_incompatible/

duplicate: https://github.com/rocksdanister/lively/issues/109

**Comment by NexRX** [comment]
Ahh, yeah rolling back to [Fences 3.09](https://cdn.stardock.us/support/uploads/Fences_3.09_setup_sd.exe) fixed it... That's so weird . It only broke it _after_ updating Windows 10. Unless it automatically updated Fences on my Laptop after restart from the Win update.
