### ISSUE TITLE
Wallpaper is paused when starting system

### ISSUE THREAD

**Issue by chilau1** [rocksdanister/lively#655]
**Describe the bug**
It's paused when computer restarts. It isn't sometimes and then it goes back to being paused also at times. I have to click on a different wallpaper then back to original one I want for it not to pause.

**To Reproduce**
Restart Computer

**Expected behavior**
Lively should never ever pause.

**Desktop (please complete the following information):**
 - OS: Windows 10
- Fluid V2

**Comment by rocksdanister** [comment]
1. Fill the rest of the issue template:

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File

2. What do you mean by paused? How are you able to tell wallpaper is paused?
