### ISSUE TITLE
Wallpaper files cannot be added if the pathname contains special symbols

### ISSUE THREAD

**Issue by dnknn** [rocksdanister/lively#658]
<details><summary>Details</summary>

```
// path
D:\_↓test↓_

// file
D:\_↓test↓_\xxx.html
```

Because it contains special symbols `↓` , 
I guess if it contains Emoji, it should be the same problem.

Unicode encoding is not supported?

</details>

**Comment by rocksdanister** [comment]
Works fine..

https://user-images.githubusercontent.com/17554161/127978656-291d0f70-bf46-4712-932f-79336022cc10.mp4

Share the logfile, its some other error.

**Comment by dnknn** [comment]
@rocksdanister You should continue to the next step and save. Maybe the problem can be reproduced. [image](https://user-images.githubusercontent.com/10995302/127991753-6c98b772-cec4-4b07-87c6-26f8d8374369.png)

> I looked at several log files, but I don’t know which one.

My operation process is : 

- use [SingleFile](https://github.com/gildas-lormeau/SingleFile) extension to save `https://louie.co.nz/25th_hour/` `.html` file (and I removed the left control bar of the page and the audio). 

- Then add it to LivelyWallpaper. At first, it was as normal as the video you recorded. When it was finally saved, it was found that there was a problem.

- Finally, move the file to the path name without special symbols, and the result is successful!

**Comment by rocksdanister** [comment]
>You should continue to the next step and save. Maybe the problem can be reproduced.

Still works.

Show a video reproducing the error (from adding the wallpaper till the error pops up.)
