### ISSUE TITLE
Icons disappearing after wallpaper is applied

### ISSUE THREAD

**Issue by Lunacharskytho** [rocksdanister/lively#659]
When any wallpaper is applied all of my desktop icons disappear, leaving only the task bar. I am remote connected to a friends PC where this is occurring.
![Screenshot 2021-08-03 193555](https://user-images.githubusercontent.com/88375838/127993806-cdd734c3-aa8f-4cac-927e-07cc97c12c92.png)
![Screenshot 2021-08-03 193622](https://user-images.githubusercontent.com/88375838/127993812-11b14d83-dfda-4c24-84d1-6099ec33f04a.png)

**Comment by rocksdanister** [comment]
Restart system.
Also Lively pauses when remote session is running.

**Comment by Lunacharskytho** [comment]
Disregard, problem solved with application restart.

**Comment by Lunacharskytho** [comment]
thx man
