### ISSUE TITLE
Add desktop mouse-event for fast switching desktop icons (show/hide) !

### ISSUE THREAD

**Issue by dnknn** [rocksdanister/lively#663]
> Obviously, this is a feature option. just throw out an idea.
> But I think if it does not affect performance or other, it is very worth having! because it is really convenient!

---------------------------------------------------------------------

- Desktop software, have ever thought about how to fast **hide/show** desktop icons most directly/conveniently ?
	* The penetrating native method  is  : 	①) `Right-click` on the desktop. ②) Press `V` ⥅ Press `D`
	* However, displaying/hiding icons by pure mouse operation cannot be done in one step.
　　　

## So, LivelyWallpaper can integrate this feature ? 

- Expected feature behavior (when in the empty space on the desktop) : 
	`Double-clicking` : fast switching desktop icons (show/hide) !
	> Because double-clicking is already very straightforward, so there is no need to hide it automatically, otherwise it will be more inconvenient.

> 💥Tips: the only potential problem is that our desktop wallpaper also has mouse events (maybe some wallpapers also have mouse double-click events), so how to deal with the same events of the two at this time?

---------------------------------------------------------------------
　　　

- - > Software/tools similar to this feature: ↴
	
- [AutoHideDesktopIcons ⤤](http://www.softwareok.com/?seite=Microsoft/AutoHideDesktopIcons/) 	　	　[imageScreenshot](https://user-images.githubusercontent.com/10995302/128505596-428b96a5-f848-4286-af7d-5c679b78907e.png)
	> It seems to meet the demand, but in fact, there are three shortcomings:
	1). `Double-click` is not supported 
	2). The mouse event is not a switch type of `checkbox`, but a binding type.
	3). It uses a listening timer to realize automatic hiding, which feels that it affects performance.

- [7-Taskbar-Tweaker　⤤](https://github.com/m417z/7-Taskbar-Tweaker)	　	　[imageScreenshot](https://user-images.githubusercontent.com/10995302/128506838-ad57ff11-4420-48f1-93b2-85750fd265a9.png)	
	> `Double-click` an empty place in the taskbar === `Win+D` , I personally feel very practical.
	Not only double-click, but also checkbox switch type.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#desktop-icon
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#autohotkey

**Comment by dnknn** [comment]
> [rocksdanister/lively/wiki/Command-Line-Controls#desktop-icon](https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#desktop-icon)
> [rocksdanister/lively/wiki/Command-Line-Controls#autohotkey](https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#autohotkey)

@rocksdanister 

`app --showIcons <state>`  ,this is just a command line, it represents a status result, not a real-time event of the user.
But it is true that AutoHotkey can use hotkeys to execute the command line.

- But here comes the problem, 
	① not most users know how to use AutoHotkey (of course I don't know how to use it ^_^)
	② AutoHotkey seems to only use the keyboard, it can't use mouse events, right?

- So the conclusion is that want to **`double-click`** to switch the desktop icon, 
	It is impossible to do this through external methods.

> I personally think that it is a very efficient/convenient/fast function to switch desktop icons by the  mouse `double-clicking` .
when you don't need to use the desktop icon, we can double-click to hide the icon, so that the desktop is very simple, and you can also enjoy the desktop wallpaper.
When the desktop icon is needed, we double-click the desktop again! This is straightforward/convenient!

---------------------------------------------------------------------
　　　

So, you decide, if you think that double-clicking to switch the desktop icon does not make much sense, you can close this issue directly, if you think it makes sense, then consider it ^_^

**Comment by rocksdanister** [comment]
>So the conclusion is that want to double-click to switch the desktop icon.

I am closing this, don't think many users want this feature and hence not worth the effort to implement and maintain.

>not most users know how to use AutoHotkey 

As for built-in keyboard shortcuts supports for basic actions - it is planned for future release.

**Comment by rocksdanister** [comment]
>① not most users know how to use AutoHotkey (of course I don't know how to use it ^_^)

```ahk
toggle:= false
; hotkeys - winkey-z
#z::
toggle := !toggle
If toggle
{
  Run cmd.exe /c livelycu.exe app --showIcons true,,hide 
}
else
{
  Run cmd.exe /c livelycu.exe app --showIcons false,,hide 
}
```

Just save this file as .ahk and run it with livelycu.exe in the same folder; Windows + Z key to toggle icon visibility.

**Comment by dnknn** [comment]
> Just save this file as .ahk and run it with livelycu.exe in the same folder; Windows + Z key to toggle icon visibility.

Thank you very much for your enthusiastic reply and help. AutoHotkey is indeed a very powerful tool, but I don’t want to use AutoHotkey, because to use AutoHotkey means the cost of learning.

It is only used to display/hide desktop icons, it feels meaningless, and the efficiency is not high.
Because the native hotkey method is sufficient, I have always operated like this: `Right-click ⥅ V ⥅  D` 
I just want to realize whether the `double-click` can achieve this effect, if not, then forget it, small question.

Finally, thank you again for your enthusiastic reply!

**Comment by dnknn** [comment]
✋Hi, @rocksdanister 

I found a small program that was exactly the same as the requirement.
https://github.com/hexandcube/desktop-icon-toggle 
> quickly toggle the visibility of desktop icons by double-clicking the blank space on the desktop.


I also saw another small tool related to desktop icons by the way
https://github.com/dczychon/WindowsIconSpacing

**Comment by rocksdanister** [comment]
>I found a small program that was exactly the same as the requirement.

and its using AutoHotKey that which you dislike..

Its also hiding the icons window:
https://github.com/hexandcube/desktop-icon-toggle/blob/5b9480b80a54375d293be158fb85272929284c99/DesktopIconToggle.ahk#L42-L51

Where as Lively is using native windows command to hide/show icons:
https://github.com/rocksdanister/lively/blob/cbc35c570ed39ba1d33b487fdfd3c98c1d8ed7bb/src/livelywpf/livelywpf/Helpers/Shell/DesktopUtil.cs#L35

If you are going to use it I recommend to change it to use this method instead as this updates windows contextmenu.
