### ISSUE TITLE
Setting picture backgrounds in windows will overlay/cover live wallpaper / Fences incompatibility

### ISSUE THREAD

**Issue by catmountainking** [rocksdanister/lively#668]
Not sure when this issue started exactly but it was almost a month ago. Lively was working fine till one day I noticed that my background was not animating no matter which wallpaper I selected. Went to disable Desktop Picture setting (the one where it sets a picture of the animated wallpaper as the desktop wallpaper), then selected black solid colour in windows background settings and managed to get animated wallpapers working again. Selecting a picture background will cause it to overlay Lively's wallpaper.

![Livelybug](https://user-images.githubusercontent.com/84104175/129256725-02137fde-c5db-4ae0-a8bc-c862d5f9998f.jpg)
Lively's background is still animated (as can be seen from the sides) but it's covered by Windows' picture background, which is set to fit to illustrate this issue. Selecting fill or stretch would cover Lively's wallpaper entirely.

![Livelybugsolidblack](https://user-images.githubusercontent.com/84104175/129256880-0cd22d87-d0bf-49c3-87a5-2f6f0010d4a8.jpg)
Selecting black solid colour background works around this issue. I've been using Lively like this since I've found this workaround.

![Livelybugdisabledbackground](https://user-images.githubusercontent.com/84104175/129262041-f3446d21-8e65-4196-b354-012e35e8412f.jpg)
Disabling windows' background through ease-of-access settings will also workaround this issue.

![Livelybugsolidyellow](https://user-images.githubusercontent.com/84104175/129257249-cc652b5e-0ec5-40f1-a4df-d05e8d77c5c2.jpg)
Selecting any other colour other than black will cause Lively's background to be tinted by that colour.

I've tried reinstalling, clearing my configuration and settings but nothing I've tried fixed this issue. Was hoping it would go away on its own or through a cumulative windows update, but it hasn't as of yet. Currently on 20H2. Have yet to try updating to 21H1.
Hope I explained this issue well enough to be understood! 🙏 
[lively_log_20210813_035010.zip](https://github.com/rocksdanister/lively/files/6978186/lively_log_20210813_035010.zip)

**Comment by rocksdanister** [comment]
Do you have any software that modify/add features to the desktop like Fences etc?

**Comment by catmountainking** [comment]
Just tried disabling fences and it fixed the issue! Disabled rainmeter previously but that didn't fix it. Didn't think fences would affect Lively in this way since I've been using Lively with fences from the very beginning and had no issue till now. Thanks a lot! Is there a way to fix this issue with a software update, or is it on fences end?

**Comment by rocksdanister** [comment]
Recent update to Fences is causing issue:
https://www.reddit.com/r/Rainmeter/comments/opul05/stardock_fences_update_completely_incompatible/

Closing as duplicate: https://github.com/rocksdanister/lively/issues/653

**Comment by catmountainking** [comment]
I've seemed to have fixed the issue with just a simple reinstall of fences. much thanks for pointing me in the right direction!
