### ISSUE TITLE
BB transparent Button Does not work in fluids V2

### ISSUE THREAD

**Issue by Ezeren76** [rocksdanister/lively#671]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
The transparent button just adds a checkered background, it does not show the desktop background if that was what you were expecting.

**Comment by rocksdanister** [comment]
This release supports background image:
https://github.com/rocksdanister/WebGL-Fluid-Simulation/releases
