### ISSUE TITLE
Fit settings are not working for webpage wallpapers

### ISSUE THREAD

**Issue by arasuludag** [rocksdanister/lively#672]
**Describe the bug**
I have two monitors. One vertical and one horizontal. When I put a wallpaper onto the vertical monitor, the wallpaper gets squeezed, its not properly fitted and "Fit" settings doesn't do anything. When I put a smaller(than 2K) wallpaper to my 2K screen, it's also not zoomed and fitted. It gets leaned left bottom.

**Comment by rocksdanister** [comment]
If I am understanding you right - the fit settings only have effect for video wallpapers, webpage wallpapers handle scaling on their own.

Answering these questions will help further understand the problem:
1. What are the wallpapers you are referring to here.
2. Share a screenshot.
3. Share the logfile: `Settings -> Misc -> Logfile`

**Comment by arasuludag** [comment]
Ah. That makes sense. 

Background photo is squeezed on a vertical monitor. https://ibb.co/nkQQvF4

And this is not scaled well. https://ibb.co/rQdGkj7

**Comment by rocksdanister** [comment]
Ah yeah, you will have to edit the webpage code individually.

For the weather cards in weather.js:
` 
 document.getElementById('bg').style.backgroundSize = "100% 100%";
`
will need changes:
https://www.w3schools.com/cssref/css3_pr_background-size.asp
