### ISSUE TITLE
Better pause algorithm

### ISSUE THREAD

**Issue by Experienced-Butter** [rocksdanister/lively#674]
I have a suggestion. 
When there is a Full-screen window under a Half-screen window.the user can't see the desktop,but the video will work.This will consumes a lot of CPU time and make my CPU hot a lot.

**Comment by Experienced-Butter** [comment]
I want the video can stop when there is a full-screem window open,any time.

**Comment by rocksdanister** [comment]
There can only be one foreground program at a time, so this won't be possible.
Alternatively you can set it to pause when any program is in foreground.

All process algorithm when ready will handle the exact scenario you mentioned:
https://github.com/rocksdanister/lively/wiki/Performance#pause-algorithms

I did have an idea in the past https://github.com/rocksdanister/lively/issues/474 .. will try that also at some point.
