### ISSUE TITLE
Memory Leak with dwm.exe...

### ISSUE THREAD

**Issue by DesktopMasters** [rocksdanister/lively#679]
**Describe the bug**
Causes DWM.exe to use a LOT of memory in private bytes.  As much as 30gb.
This has been going on for a long time.  I only recently figured out it was coming from Lively.
After about a week my computer would crash doing strange things.

**To Reproduce**
1. Setup a bunch of virtual desktops (I have 12)
2. Do not reboot computer for a week.
3. Note: I also run a duel screen.. or basically a Laptop with a built in screen and external screen.

**Expected behavior**
DWM.exe should only be a few MB not GB.
Problem stops happening as soon as I exit the Lively App

**Screenshots/Video**
![Example](https://user-images.githubusercontent.com/58863524/130298542-a4e77f01-1b03-4cec-9863-e99a895fce08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1 19043.1165
- Lively version 1.7.0.4

**Additional context**
Wallpapers are "Moon Over Water Video" and "Phoenix Fire Bird" on the second screen.

**Log file (Important)**
[lively_log_20210820_152306.zip](https://github.com/rocksdanister/lively/files/7024322/lively_log_20210820_152306.zip)

**Comment by rocksdanister** [comment]
This could be a driver related issue, I saw several discussions related to it such as:
https://www.reddit.com/r/Windows10/comments/k25yfj/memory_leak_in_dwmexe/

https://www.reddit.com/r/Windows10/comments/ptc6u0/comment/hdw8gtq/?utm_source=share&utm_medium=web2x&context=3

As recommended there I would try reinstall of the graphics drivers..
Then test Lively with and without wallpaper plugins set to use dgpu:
https://github.com/rocksdanister/lively/wiki/Common-Problems#laptopssystems-with-multiple-gpu
Turning off gpu decode for the mpv videoplayer is another thing you could try.

I use Lively on my main system and this has not personally happened with me.
