### ISSUE TITLE
Won't start for the first time; requires ".NET Framework"

### ISSUE THREAD

**Issue by kaiden-mccready** [rocksdanister/lively#68]
After installing, when I try to open the program for the first time, I get this [error message](https://pasteboard.co/JavXVT1.png). When I try to install the .net framework, it seems that my computer doesn't match the requirements. Is this normal? Can my computer just not use it? 

Because it never launched, there is no ErrorLogs folder.

Thanks.

**Comment by kaiden-mccready** [comment]
Error message when attempting to install .NET thing:
![Capture](https://user-images.githubusercontent.com/40643546/83194663-ff1a2280-a106-11ea-809c-3747b66da484.PNG)
Running Windows 10 
Specifics:
![Capture](https://user-images.githubusercontent.com/40643546/83194829-46a0ae80-a107-11ea-9e75-88fab5ed7666.PNG)

**Comment by rocksdanister** [comment]
Its because your windows 10 is too old: 
https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

Windows 10 October 2018 Update (version 1809) comes preinstalled with 4.7.2
Windows 10 May 2019 Update (version 1903) comes preinstalled with 4.8
