### ISSUE TITLE
Can not change from mpv to vlc video player

### ISSUE THREAD

**Issue by GHRTB** [rocksdanister/lively#680]
So I want to set an mp4 video as my wallpaper but this file is vlc type. I went to the seeting menu in the app and changed from mpv to vlc media player for video wallpaper only to get the same error as before. When i checked again it has returned to mpv as soon as i open the library. If i set it to wmf file it stays but it resets the vlc to mpv every time. Thanks in advance!

**Comment by rocksdanister** [comment]
>So I want to set an mp4 video as my wallpaper but this file is vlc type.

What file extension?.. vlc and mpv are just video players.. they support all video/audio formats, there is no special vlc format unless you are talking about playlist file or something?

> I went to the seeting menu in the app and changed from mpv to vlc media player for video wallpaper only to get the same error as before. When i checked again it has returned to mpv as soon as i open the library. If i set it to wmf file it stays but it resets the vlc to mpv every time. 

Only mpv and wmf plugins are included by default, others require separate download.
https://youtu.be/8vgrsoBGoHI?t=88

I recommend mpv player for regular use, its tested and support all of Lively features.
