### ISSUE TITLE
Lively GitHub version doesn't doesn't start even tho I have .NET Core 3!!

### ISSUE THREAD

**Issue by VYRUS1** [rocksdanister/lively#681]
Hello!! When I install the Lively Wallpaper from the official website, it says to install .NET core 3 for runtime. So, I clicked on "Yes" and proceeded with the website. I downloaded the .NET Core Desktop Runtime x64 as my PC is a 64 bit architectured! But, after downloading .NET core, I was still receiving the same popup error! So, I decided to restart and reinstall Lively and so I did. But, it was still the same! So, instead of choosing "Install for everyone" I choose "Install for only me" as it was recommended and I presumed that maybe this would be a bug and convinced myself! But, the result was still the same!! I also tried to install .NET Core Runtime for Console apps and still got stuck with the same issue. Also, I didn't have the Microsoft Store app on my machine so there isn't any chance of getting a mix match. 

![image](https://user-images.githubusercontent.com/73092448/130309070-063b2770-3d3c-43f2-a8bc-38a4537b8788.png)

Please Help!!!

**Comment by rocksdanister** [comment]
That's weird, the setup should have handled this.

Anyway.. you need the x86 runtime because Lively is x86 application.

**Comment by VYRUS1** [comment]
> That's weird, the setup should have handled this.
> 
> Anyway.. you need the x86 runtime because Lively is x86 application.

Yes I also tried with an x86 Runtime but turns out the same!!

**Comment by rocksdanister** [comment]
1. Did you do any modification to system like changing windows program install directory etc?
2. Have you tried restarting system after installing runtime?
3. https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-3.1.18-windows-x86-installer is what you need to install, can you check again?

**Comment by VYRUS1** [comment]
> 1. Did you do any modification to system like changing windows program install directory etc?
> 2. Have you tried restarting system after installing runtime?
> 3. https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-3.1.18-windows-x86-installer is what you need to install, can you check again?

No, I installed it in a default location as the installer suggested, and also AS I WROTE DOWN IN THE ISSUE, I frequently restarted after installing runtime and even tried reinstalling Lively with .NET present in the computer!!
