### ISSUE TITLE
Cannot click desktop icons when using HTML wallpapers

### ISSUE THREAD

**Issue by sigmondkukla** [rocksdanister/lively#683]
HTML-based wallpapers, such as the ParallaxJS demo, do not transmit clicks to desktop, resulting in the inability to open applications by clicking desktop shortcuts, or to select items using a drag box.

1. Install and select the ParallaxJS demo wallpaper
2. Go to the desktop
3. Click on desktop icons / drag a box
4. Icons are highlighted on hover but not clicked

These steps should result in the desktop functioning normally.

https://user-images.githubusercontent.com/50522829/130367790-50188232-e59a-4315-b19c-ca29560950fd.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
- ParallaxJS

**Additional context**
This occurs on any HTML based wallpaper, as far as I can tell. It also occurs whether *Mouse interaction when application focused* is on or not.

**Log file**
[lively_log_20210822_152955.zip](https://github.com/rocksdanister/lively/files/7028011/lively_log_20210822_152955.zip)

**Comment by rocksdanister** [comment]
Possibly duplicate https://github.com/rocksdanister/lively/issues/174

Although its weird nothing is working for you.. in my system sometimes clicks don't work.

**Comment by rocksdanister** [comment]
`This occurs on any HTML based wallpaper, as far as I can tell. It also occurs whether Mouse interaction when application focused is on or not.`

That does not make any sense..
Do you have any other program that modify desktop?

**Comment by rocksdanister** [comment]
Does it still happen when Wallpaper Input is off?

**Comment by sigmondkukla** [comment]
> Does it still happen when Wallpaper Input is off?

No, it works fine then. It also seems to be fine when it is set to Keyboard, but all the icons disappear.

**Comment by Lomacar** [comment]
Oh yes, turning off mouse interaction solves the clicking problem.

For me, I am able to select icons on the first attempt, but after that I cannot until I select another window, then I can select or click on icons one more time again.

**Comment by rocksdanister** [comment]
I managed to fix this, update coming up in beta channel in a few days.

**Comment by rocksdanister** [comment]
The fix is available for testing in beta branch v1.7.1.7b

You can switch to beta-branch by going to `Lively settings -> Misc -> Switch to beta`

**Comment by sigmondkukla** [comment]
Thank you so much! All your hard work put into this awesome application is greatly appreciated.
