### ISSUE TITLE
Custom slideshow with wallpapers YouTube videos gifs etc..

### ISSUE THREAD

**Issue by odysseasss** [rocksdanister/lively#688]
I would like there to be a way when a wallpaper of a YouTube video or a website ends one of the other wallpapers starts, so that there is a rotation with the music videos or the animated banners. Like a custom slideshow with  ours wallpapers and gifs.

                                                                                                                                                                                Sorry for my English :)

**Comment by rocksdanister** [comment]
Hi,
This feature is being discussed here https://github.com/rocksdanister/lively/issues/137 and planned for v1.8 release of Lively.
