### ISSUE TITLE
Wallpaper being applied even after user cancelling the operation

### ISSUE THREAD

**Issue by woollymilkcap** [rocksdanister/lively#69]
**Describe the bug**
Wallpaper is being applied even after cancelling the operation, but doesn't add an entry to library list

**To Reproduce**
1. Open Library tab in Lively
2. Drag and drop a media ( html in my case ) into library
3. Press the close button on the preview window
4. Preview window closes but applies the wallpaper

**Expected behavior**
preview window closes with no change

**Screenshots/Video**
https://drive.google.com/file/d/12-6aJezINVfMxWyzQQhfsbyUNCZ3UXmv/view?usp=sharing

**Desktop (please complete the following information):**
- OS : Win7
- Lively version : v0.9.5.5 Portable
- Wallpaper : html

**Comment by rocksdanister** [comment]
This is intentional behavior, closing the window will resize and add wallpaper to desktop skipping library import.

A "cancel" button will be nice to have, will implement it in the future.
