### ISSUE TITLE
Webpage wallpapers don't work when using Edge plugin

### ISSUE THREAD

**Issue by ctl-loc** [rocksdanister/lively#690]
**Describe the bug**
When I am in the app, if I double click on some of the preload wallpaper they doesn't work ans I have an error message 

**To Reproduce**
1. Go to the app
2. Click on some wallpaper (like periodic table or The Hill)
3. See error
(doesn't work after rebooting my pc)

**Expected behavior**
I wanted to have the periodic table in my wallpaper

**Screenshots/Video**
![Capture](https://user-images.githubusercontent.com/89453807/130597063-5fcdc4b7-22da-4fdd-abe8-66f8790dd1d3.PNG)

**Desktop (please complete the following information):**
 - OS: windows10
- I was using an imported wallpaper (gif).

**Additional context**
my taskbar is clear i don't know if it change anything

**Log file (Important)**
[lively_log_20210824_113756.zip](https://github.com/rocksdanister/lively/files/7038314/lively_log_20210824_113756.zip)

**Comment by rocksdanister** [comment]
Looks like you changed the web browser to Edge:
`
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
`

Which require separate installation:
https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef#webview2-microsoft-edge

Better to just change it back to cefsharp:
`Settings -> Wallpaper -> Web Browser -> Engine -> CEFSharp`
