### ISSUE TITLE
Audio stops when window is open

### ISSUE THREAD

**Issue by Bruno1680** [rocksdanister/lively#707]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [When I try to switch to another window, and the music of the video stops]

**Describe the solution you'd like**
I have a problem, when I put a video with sound, it sounds great, but when I open another window, it stops sounding, I would like there to be a way to mute it or activate it while using another window, and not just be on the desktop
**Describe alternatives you've considered**

a button to help mute it, if desired,

**Additional context**
...

**Comment by rocksdanister** [comment]
>When I try to switch to another window, and the music of the video stops

![Screenshot 2021-09-03 030126](https://user-images.githubusercontent.com/17554161/131919057-74f4c579-98ca-457c-ba2b-b97989fe1502.png)
