### ISSUE TITLE
Unable to load a video file

### ISSUE THREAD

**Issue by PukeBottom** [rocksdanister/lively#709]
[lively_log_20210904_133354.zip](https://github.com/rocksdanister/lively/files/7110547/lively_log_20210904_133354.zip)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Change videoplayer to wmf.
