### ISSUE TITLE
Oops... Looks like something went wrong :(

### ISSUE THREAD

**Issue by Bamiuu** [rocksdanister/lively#710]
Hey!
![image](https://user-images.githubusercontent.com/90155873/132139902-78e86482-cd4b-4f09-831a-3fedd01e7855.png)
If i click on any wallpaper it writing this... so here's my log file, hope you can help!
[lively_log_20210905_215420.zip](https://github.com/rocksdanister/lively/files/7112271/lively_log_20210905_215420.zip)

**Comment by rocksdanister** [comment]
Change videoplayer to wmf and browser to CefSharp.
