### ISSUE TITLE
Use shortcut keys to enable screen saver

### ISSUE THREAD

**Issue by kimliss** [rocksdanister/lively#715]
**Describe the solution you'd like**

I want to lock the screen and preview the screensaver immediately

**Additional context**

**Comment by rocksdanister** [comment]
Currently can be done using AutoHotkey + Commandline controls:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls

Built-in shortcut support will come soon.. closing as duplicate https://github.com/rocksdanister/lively/issues/665
