### ISSUE TITLE
Taskbar Blur lags File Explorer on Windows 11

### ISSUE THREAD

**Issue by chriseilander** [rocksdanister/lively#718]
**Describe the bug**
When Taskbar Theme is set to blur, it lags the File Explorer window when dragging it, and only the File Explorer window. Other windows/programs seem to be fine. Setting the Taskbar Theme to clear or another option and the lag won't happen.

**To Reproduce**
1. Use Windows 11.
2. Set Taskbar Theme to blur in Lively
3. Drag around a File Explorer window.

**Expected behavior**
A smooth window dragging experience

**Screenshots/Video**
[https://www.youtube.com/watch?v=FChvIeRR6PM](https://www.youtube.com/watch?v=FChvIeRR6PM)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Build 22000.184
 - Wallpaper: Ribbon

**Additional context**
There is a known problem window dragging lag with Windows 11 transparency effects and having File Explorer open. I do not know if this bug is fixed, but recreating the setup for that (enabling transparency effects, Lively is closed) and dragging windows then didn't create lag for me. Also reports indicate that this bug also affects other windows besides File Explorer while the Taskbar Blur setting in Lively only seems to lag File Explorer for me.

The transparency setting in the Personalization and Accessability settings in Windows 11 don't seem to affect this problem. Lively's Taskbar Theme might be overwriting this setting?

I've used both the stable and beta versions of Lively.

**Log file (Important)**
[lively_log_20210910_081518.zip](https://github.com/rocksdanister/lively/files/7141736/lively_log_20210910_081518.zip)

**Comment by rocksdanister** [comment]
Its a Windows bug https://github.com/TranslucentTB/TranslucentTB/issues/405

**Comment by chriseilander** [comment]
So it isn't directly tied to the Windows 11 Transparency effects, but just using the blur effect on Windows 11 on the taskbar?

**Comment by rocksdanister** [comment]
From the discussion posted above:
> Ok I reproduced it. It happens with any app using this effect, eg Radeon Settings will reproduce it (even when TTB isn't running), so it's a Windows 11 bug.

I think it will be best to turn it off for the time being on Windows 11.

**Comment by rocksdanister** [comment]
>the bug has been fixed with update KB5006746.
