### ISSUE TITLE
Нету панели задач / Wallpaper covering everything.

### ISSUE THREAD

**Issue by maksspion228** [rocksdanister/lively#719]
При запуске обоев пропадает панель задач

https://user-images.githubusercontent.com/87656990/132820070-8fde4f42-5c32-4d6e-a282-d9d0a593cbff.mp4
За качество простите иначе ролик будет много весить

Раньше обои работали 

[lively_log_20210910_145806.zip](https://github.com/rocksdanister/lively/files/7142206/lively_log_20210910_145806.zip)
Вот логи

Что мне делать? Это я что-то нажал или это баг?
Программа была загружена с Microsoft Store

**Comment by rocksdanister** [comment]
Try restarting Windows.

**Comment by maksspion228** [comment]
> Попробуйте перезапустить Windows.

Могу сказать одно: Я тупой кусок, тупого говна потому что не додумался до этого🤦(какой же я тупой....)

**Comment by maksspion228** [comment]
Я впервые на этом сайте как закрыть жалобу?

**Comment by rocksdanister** [comment]
I'll close it.
Let me know if this happens again in the future.

**Comment by maksspion228** [comment]
> Я закрою.
> Сообщите мне, если это повторится в будущем.

Спасибо!
