### ISSUE TITLE
Layer Bug

### ISSUE THREAD

**Issue by CloserToTheCosmos** [rocksdanister/lively#720]
**Describe the bug**
After downloading a video from YouTube (bundled with the audio) for setting it as a live wallpaper. The link (https://www.youtube.com/watch?v=XLHJpBW8Bh4&list=PLk6n5YKD7kakme_X3SjKHTl9AlKYrd78z&index=16)
The bug with this is that you cannot interact with your computer. Which means the wallpaper becomes non-responsive and only playsback. Which also means you cannot right click on the screen or cannot use drag for selecting items.

**To Reproduce**
1. Go to 'https://www.youtube.com/watch?v=XLHJpBW8Bh4&list=PLk6n5YKD7kakme_X3SjKHTl9AlKYrd78z&index=16'
2. Click on 'download and set it as your live wallpaper through the app'
3. Right Click/ Drag the mouse while holding left mouse button 'to see nothing happens'
4. It acts as a second layer over my default wallpaper. This can be seen more clearly when using split screen function on the display.

**Expected behavior**
Expected it to work as other wallpapers. 

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
![Screenshot (28)](https://user-images.githubusercontent.com/87476028/132839802-f1b57694-6d07-4717-ae57-1a859086868a.png)
Notice how the taskbar has the live wallpaper and my default wallpaper shows up using split screen mode.
But the main issue is that I am not able to use my mouse (note: I am able to scroll my mouse and see it move) but I am not able to interact ie: Left click and right click to access certain features that the mouse has.

**Desktop (please complete the following information):**
 - OS: [ Windows 10 Home 19043.1165]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
Is this the same issue as https://github.com/rocksdanister/lively/issues/719 ?

I don't quite get the screenshot.. also logfile is missing.
