### ISSUE TITLE
Wallpaper Stopped after Sleep

### ISSUE THREAD

**Issue by Laiswk** [rocksdanister/lively#724]
I am using lively wallpaper for few days, it is really awesome. But there is a bug, when I sleep my computer and start it again, the live wallpaper has gone and it does not start the live wallpaper automatically and unable to open or modify it through the application. To deal with this problem, I quit the application and open it again. Finally, it works fine.

**Comment by rocksdanister** [comment]
If you have windows slideshow enabled, disable and see if happens again.

Also follow the issue template/share the logfile.

**Comment by mpop** [comment]
Having the same issue. I'm not using windows slideshow. Every time I wake my computer from hibernation I have to turn of lively and then turn it on again before it syncs to the audio(Fluids v2).
[lively_log_20210927_162926.zip](https://github.com/rocksdanister/lively/files/7237032/lively_log_20210927_162926.zip)
s.

**Comment by rocksdanister** [comment]
>I have to turn of lively and then turn it on again before it syncs to the audio(Fluids v2).

I don't understand completely, so the wallpaper stopped/disappeared or the fluid wallpaper stopped working with audio?

**Comment by mpop** [comment]
Wallpaper still on. If I move my mouse it still shows smoke/fluids. But if I turn on music it doesn't sync to the audio.

**Comment by rocksdanister** [comment]
Its a different issue and unrelated to this.
