### ISSUE TITLE
I have to right click the desktop and show desktop icons every time the computer boots up

### ISSUE THREAD

**Issue by diblunkus** [rocksdanister/lively#725]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by diblunkus** [comment]
I literally have to right click the desktop and show desktop icons every time the computer boots up ?

**Comment by diblunkus** [comment]
Running Fluids v2

**Comment by rocksdanister** [comment]
Icons are disabled when keyboard input is enabled in settings (Settings -> Wallpaper -> Interaction) to prevent accidental selection.
