### ISSUE TITLE
visual studio is an exception to pause the wallpaper 

### ISSUE THREAD

**Issue by csc-chicken** [rocksdanister/lively#73]
**Before proceeding**
I am a total newbie in git and github. i  just signed up github account 3 days ago,  and i am now learning push pull request. thanks for your generosity. i want to help but I'm not good at c#.I used to code with arduino.

**Describe the bug**
i found that using visual studio do not pause any wallpaper 

**To Reproduce**
1. use any wallpaper with sound
2. open visual studio

**Expected behavior**
music will be still running

**Desktop (please complete the following information):
windows 10 ver  1909

**Comment by rocksdanister** [comment]
During development I added an exception for Visual studio, should have removed it before release haha.

As a temporary fix, add a process exception to visual studio:

Settings -> Application Rules -> add the following
`Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe`
-> Pause

(Application Rules has the highest priority, even before the custom built in exceptions.)

I will do a permanent fix in the next update, thanks for letting me know.

**Comment by csc-chicken** [comment]
you're welcome. 
have some music
https://www.youtube.com/watch?v=LfI4dMGmjnQ

**Comment by rocksdanister** [comment]
will be resolved in v1.0
