### ISSUE TITLE
"Particulate Medusae" appearing on Windows toolbar 

### ISSUE THREAD

**Issue by lukass11** [rocksdanister/lively#731]
![image](https://user-images.githubusercontent.com/90844900/133614057-e2f170a4-ee1c-4d47-ace3-09f60b3cc2ed.png)

**Comment by rocksdanister** [comment]
Share a bigger screenshot/video..  I am confused how it looks.

Also attach logfile:
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File

**Comment by lukass11** [comment]
OS windows10

![image](https://user-images.githubusercontent.com/90844900/133616777-871d0944-41c7-4ec3-a2f1-eaee5693a319.png)

**Comment by rocksdanister** [comment]
Logfile is required.

**Comment by lukass11** [comment]
I don't know exactly if this is it
![image](https://user-images.githubusercontent.com/90844900/133636986-7dbfa2e8-2e0b-4557-843f-912155ab8fc9.png)

**Comment by rocksdanister** [comment]
![Screenshot 2021-09-16 204229](https://user-images.githubusercontent.com/17554161/133638130-802b771b-be31-4dbf-a7a2-59bd5cb58ab7.png)

**Comment by lukass11** [comment]
[lively_log_20210916_171342.zip](https://github.com/rocksdanister/lively/files/7178991/lively_log_20210916_171342.zip)

**Comment by rocksdanister** [comment]
1. I noticed you are running in duplicate wallpaper layout, does this happen when the wallpaper is run only on one screen?
2. Does something similar happen with other wallpapers?

**Comment by lukass11** [comment]
1.I don't know, just when I turn on lively wallpaper it bugs and I see what I sent.
2. It happening on any wallpaper

**Comment by rocksdanister** [comment]
I'm closing this as duplicate https://github.com/rocksdanister/lively/issues/737 looks like same issue.
