### ISSUE TITLE
Video wallpaper not working / Windows N

### ISSUE THREAD

**Issue by VielleichtJonas** [rocksdanister/lively#734]
Hi, when i try to set an video as an wallpaper livel wallpaper say: Oops... Looks like something went wrong :(  In order to better understand this error and fix the issue, share the log file with the developer. Instruduction for sharing log file: github.com/rocksdanister/lively/wiki

I downloaded this video and it is an mp4 file.
but it doesn't work.
pls can somebody help me what i have to do? 

this is the video: https://pixabay.com/de/videos/blau-abstrakt-futuristisch-27239/

**Comment by rocksdanister** [comment]
Share the logfile from the app here:
![Screenshot 2021-09-16 204229](https://user-images.githubusercontent.com/17554161/133763815-f390ae80-39c2-49b6-92c7-518c9dab520e.png)

**Comment by VielleichtJonas** [comment]
where can i find this point in the app?

**Comment by rocksdanister** [comment]
When you press `Log File` it will generate a zip file, share that file here by dragging & dropping.

**Comment by VielleichtJonas** [comment]
like that?

[lively_log_20210917_133207.zip](https://github.com/rocksdanister/lively/files/7185231/lively_log_20210917_133207.zip)

**Comment by rocksdanister** [comment]
Windows N require additional codec installation:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by VielleichtJonas** [comment]
now i the codec is on my pc what i have to do now?

**Comment by VielleichtJonas** [comment]
it doesn't work 
my video is an mp4 file and lively have the same problem like todays morning. 
the windows media foundation is on my pc but when i try the same like at the start of lively it doesn't work

**Comment by rocksdanister** [comment]
Try restarting system.. if that does not help then try changing videoplayer to wmf (Lively settings -> wallpaper -> video)

If none of the above works, create a new logfile and share that.
