### ISSUE TITLE
Pausing Lively shows a white context menu in the bottom left

### ISSUE THREAD

**Issue by silver-volt4** [rocksdanister/lively#737]
**Describe the bug**
When Lively is paused, this white-blue menu can be seen in the bottom left. It is best seen with the taskbar on the top.
![image](https://user-images.githubusercontent.com/35656715/133783875-a294ce0c-27ec-4c16-93c3-637f4d2609d6.png)
If the taskbar effect is set to blur and is at the bottom, this can also be seen when a window is maximized.
![image](https://user-images.githubusercontent.com/35656715/133783880-837c3889-57c7-4f2b-b969-3cdb17b46cbc.png)

**To Reproduce**
1. Pause Lively or maximize a window

**Expected behavior**
Show nothing in the bottom left

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H1
 - Appears with every wallpaper, I tested matrix, parallax.js and periodic table. 

**Log file (Important)**
[lively_log_20210917_144251.zip](https://github.com/rocksdanister/lively/files/7185693/lively_log_20210917_144251.zip)

**Comment by rocksdanister** [comment]
Looks like its https://github.com/rocksdanister/lively/issues/683 changes that's causing this in some systems.

**Comment by rocksdanister** [comment]
I managed to reproduce it.. looks like it only happens in single display setups.

**Comment by rocksdanister** [comment]
New update is pushed to store with the fix.
