### ISSUE TITLE
Issue working on Second monitor

### ISSUE THREAD

**Issue by QuietCoder1007** [rocksdanister/lively#746]
Whenever I try to have a wallpaper show up on my second monitor, it doesn't work except for when I have it span both monitors. I choose the duplicate option and it only shows up on one monitor, but not the other. Could it be because that they're both different resolutions and framerates? One is a 4k60Hz monitor and the other is a 2k120Hz monitor

[lively_log_20210923_000839.zip](https://github.com/rocksdanister/lively/files/7214965/lively_log_20210923_000839.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/629
