### ISSUE TITLE
请问能不能支持dexpot（Can it support dexpot）

### ISSUE THREAD

**Issue by jingouwangzi** [rocksdanister/lively#749]
我现在在用dexpot多桌面软件，发现此软件设置壁纸对dexpot无效，请问能支持吗？
I am currently using the dexpot multi-desktop software, and found that the wallpaper setting of this software is invalid for dexpot, can you support it?

**Comment by rocksdanister** [comment]
Does it still work if you start Lively first -> set wallpaper and then start dexpot?
