### ISSUE TITLE
Select file which contain relative path

### ISSUE THREAD

**Issue by Eason0729** [rocksdanister/lively#752]
**Is your feature request related to a problem? Please describe.**
When customizing wallpaper with selecting file ("type": "folderDropdown"), I notice that lively copy the selected file into wallpaper folder.
However, the file I selected contain relative paths to other files, and the wallpaper cannot interactive with them.

**Describe the solution you'd like**
When customizing wallpaper, user can select a folder, and lively can provide a list of files within selected folder.

**Describe alternatives you've considered**
Also copy other files under the folder which contain the selected file.

**Comment by rocksdanister** [comment]
Hi, I don't know what relative files means in this context.. If you can provide an example of how to set things up then I can take a look.

**Comment by Eason0729** [comment]
this is the example Live2D model, Rice Glassfield, form live2d website
file tree
```
>ls -R
.:
motions  rice_pro_t03.2048  rice_pro_t03.moc3  rice_pro_t03.model3.json  rice_pro_t03.physics3.json

./motions:
idle.motion3.json  mtn_01.motion3.json  mtn_02.motion3.json  mtn_03.motion3.json

./rice_pro_t03.2048:
texture_00.png  texture_01.png
```
rice_pro_t03.model3.json
```json
{
	"Version": 3,
	"FileReferences": {
		"Moc": "rice_pro_t03.moc3",
		"Textures": [
			"rice_pro_t03.2048/texture_00.png",
			"rice_pro_t03.2048/texture_01.png"
		],
		"Physics": "rice_pro_t03.physics3.json",
		"DisplayInfo": "rice_pro_t03.cdi3.json",
		"Motions": {
			"Idle": [
				{
					"File": "motions/idle.motion3.json"
				}
			],
			"FlickLeft": [
				{
					"File": "motions/mtn_01.motion3.json"
				}
			],
			"Tap@Body": [
				{
					"File": "motions/mtn_02.motion3.json"
				}
			],
			"FlickUp": [
				{
					"File": "motions/mtn_03.motion3.json"
				}
			]
		}
	},
	"Groups": [
		{
			"Target": "Parameter",
			"Name": "EyeBlink",
			"Ids": [
				"ParamEyeLOpen",
				"ParamEyeROpen"
			]
		},
		{
			"Target": "Parameter",
			"Name": "LipSync",
			"Ids": []
		}
	],
	"HitAreas": [
		{
			"Id": "HitAreaBody",
			"Name": ""
		}
	]
}
```

**Comment by rocksdanister** [comment]
This seems impossibly difficult.. because I will have to add custom code to handle each new file format 😕

**Comment by Eason0729** [comment]
That's too bad. By the way, I just found that I forget to close the issue.
