### ISSUE TITLE
Pause don't work.

### ISSUE THREAD

**Issue by AlxSrc** [rocksdanister/lively#759]
The application keeps running if another application is in fullscreen mode or if another application is focused. Even with 2 apps on full screen, I can see the background moving when I move the mouse in the taskbar because the taskbar is invisible.
[lively_log_20210927_082945.zip](https://github.com/rocksdanister/lively/files/7233600/lively_log_20210927_082945.zip)
e.

**Comment by rocksdanister** [comment]
Current algorithm only checks the foreground app:
https://github.com/rocksdanister/lively/wiki/Performance#pause-algorithms
