### ISSUE TITLE
Hope to compatible with Coodesker

### ISSUE THREAD

**Issue by coodesker** [rocksdanister/lively#760]
Lively paused when running coodesker, because it was considered as fullscreen mode,  window class name of coodesker is \_cls\_desk\_. Hope to exclude coodesker from fullscreen, thanks

**Comment by coodesker** [comment]
window class name of coodesker is "_cls_desk_"

**Comment by rocksdanister** [comment]
Forgot about this one.. Is this still a problem? if so is the classname still `_cls_desk_` ?

>because it was considered as fullscreen mode

Is the Coodesker window size same as `SysListView32`?

**Comment by coodesker** [comment]
Yes, the class name is still _cls_desk_.
the windows size of coodesker has 1 pixel offset compared to SysListView32

**Comment by rocksdanister** [comment]
Done, next update will have exception for Coodesker.
