### ISSUE TITLE
Wallpaper not showing after logging back in.

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#761]
When I have Lively Wallpaper running, it works fine. But when I log out by pressing "Win" + "L". And shortly after logging back in, Lively Wallpaper does not show my wallpaper. However it shows the taskbar does show in correct theme.

[lively_log_20210928_192222.zip](https://github.com/rocksdanister/lively/files/7246214/lively_log_20210928_192222.zip)

**Comment by rocksdanister** [comment]
Is Windows slideshow wallpaper function turned ON? if so can you try setting it to Picture mode and retesting.

**Comment by ghost** [comment]
Yes it whas set to slideshow. In picture mode does it work. But I have 2 screens and I want one to slideshow and one animated.

**Comment by ghost** [comment]
A refresh button in the dock item (richt under in the taskbar) would help. That when I press refresh, it reloads the wallpaper.

**Comment by rocksdanister** [comment]
>A refresh button in the dock item (richt under in the taskbar) would help. That when I press refresh, it reloads the wallpaper.

That's not a good solution to the problem.

>Yes it whas set to slideshow. In picture mode does it work. But I have 2 screens and I want one to slideshow and one animated.

Hmm.. what if you can set slideshow on 2nd screen using Lively instead? I plan to disable Windows slideshow when Lively is running.

**Comment by ghost** [comment]
A slideshow using lively seems a good idea. But only if you can manually select a folder where you can add pictures to and lively will just adapt.

**Comment by sukhomoyb** [comment]
I am using TaskbarX along with your lively Wallpaper. But unfortunately, it is making an issue to run side by side. the most significant bug I found while I am logging back to windows after automatic lock. Lively Wallpaper does not show any wallpaper.

**Comment by rocksdanister** [comment]
moved: https://github.com/rocksdanister/lively/issues/802
