### ISSUE TITLE
Music doesn't play when I'm focused on a window (eg. chrome), Even though I enabled that option

### ISSUE THREAD

**Issue by KPKing126** [rocksdanister/lively#765]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
![Screenshot 2021-09-30 214943](https://user-images.githubusercontent.com/17554161/135493998-46ee49be-d028-45f5-ac94-a66bff652bef.png)

Uncheck this.

**Comment by rocksdanister** [comment]
Oh unless you already unchecked it? if the window is fullscreen then wallpaper gets paused and thereby audio also gets paused.. 
You will have to turn off wallpaper pause:
 `Settings -> Perf -> When apps fullscreen -> Nothing`
