### ISSUE TITLE
Video playback fails with MFC and LAV

### ISSUE THREAD

**Issue by takase1121** [rocksdanister/lively#77]
**Describe the bug**
I tried to use lively to play a video as wallpaper, but Media Foundation and LAV just doesn't work; it displays a grey screen. However, mpv does seem to work.

**To Reproduce**
1. Choose a video file
2. Grey screen is shown

**Expected behavior**
Both MFC and LAV should work.

**Screenshots/Video**
With MPV:
![image](https://user-images.githubusercontent.com/20792268/85050878-5de43080-b1c9-11ea-886e-5d1ac9bfd84f.png)

With LAV/MFC:
![image](https://user-images.githubusercontent.com/20792268/85050924-6dfc1000-b1c9-11ea-982f-9cef97809526.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
- Which wallpaper was running at the time if any: my own video, I can send you the video. I have both MP4 (original) and a lossless webm (VP9) that I transcoded

**Log file**
MFC: [logfile.txt](https://github.com/rocksdanister/lively/files/4800082/logfile.txt)
LAV: [logfile.txt](https://github.com/rocksdanister/lively/files/4800089/logfile.txt)

**Comment by rocksdanister** [comment]
Have you tried changing the video decoder gpu in LAV settings? also try None(cpu.)

**Comment by takase1121** [comment]
Nope, it doesn't work. The grey screen is still there.

**Comment by rocksdanister** [comment]
Just so you know, you have to restart the video player to see the effect of the decoder switch; try switching the videoplayer from LAV to MF then back to LAV in Lively to restart.

Share the file.

**Comment by takase1121** [comment]
I did restart the video player. Anyways, here are the files:

https://drive.google.com/file/d/1ydjkG3mWChfDOCMResF8D0Pm-6LqnSp_/view?usp=sharing

**Comment by rocksdanister** [comment]
Working fine on my end :- 

- x264 file works on mpv, mediakit & mediafoundation.
- VP9 works on mpv, mediakit & the browser.

Tested on LAV settings: software, intel quicksync hd4600, dxva & cuvid on gtx 750 ti

**Comment by takase1121** [comment]
I uninstalled and reinstalled the program. Now both MFC and LAV works. My guess is some edge-case config settings but well now it works so I am okay with it. However, both MFC and LAV blinks while looping (like web browser video), probably another issue.

**Comment by rocksdanister** [comment]
MFC will blink as it is old and I do plan on changing it for the new windows 10 control/libvlc.

LAV should be fine, does this happen with every video files?

**Comment by takase1121** [comment]
No, this might actually be issue on my side; the other video played perfectly.

I'll open the video in an editor and see if there are actually black frames.

**Comment by takase1121** [comment]
Yes, it was my fault. The video actually has black frames and I removed it. Thanks! (for this piece of amazing software too)
