### ISSUE TITLE
Pause running when the window is maximized

### ISSUE THREAD

**Issue by peter-liuseu** [rocksdanister/lively#770]
The GPU occupation is still high, if it's possible to stop running when the window is maximized.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/blob/4b73808d01480d8d3a9414619289b3ceb6b90ba4/src/livelywpf/livelywpf/Core/Playback/Playback.cs#L281

Fullscreen settings already checks for windows size and maximise flag.. foreground algorithm is based on foreground app, you probably had taskmgr as the foreground app thats why wallpaper was unpaused.

Also taskmgr readings are unreliable:
https://github.com/rocksdanister/lively/wiki/Performance
