### ISSUE TITLE
Taskbar wallpaper/themes

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#771]
I was bored.. I think its silly but looks kind of cool haha

https://user-images.githubusercontent.com/17554161/135701959-64769cac-b237-41f6-ad25-11a7d82afda0.mp4

_Sometimes My Genius... It's Almost Frightening - Jeremy Clarkson_

**Comment by AchMinn** [comment]
Is this gonna be live someday ?

**Comment by rocksdanister** [comment]
I'm thinking about it, its a bit of work.. but right now there are other bugs with existing taskbar themes that need work 😭

**Comment by DCloud06** [comment]
where can i get this old version, I like this old version than the new one
