### ISSUE TITLE
Original lively wallpapers not working after update (Fluid V2, Ribbon, Ripples, The Hill, etc).

### ISSUE THREAD

**Issue by Darkksun** [rocksdanister/lively#772]
Go to Lively home screen, and just choose any wallpaper that Lively made, not the ones you uploaded.

What's expected to happen, is for the wallpaper to apply, and function normally. Instead, it has an error.
![error](https://user-images.githubusercontent.com/91776837/135708054-efcb76ef-65eb-409a-9cb1-51449339aac7.png)

Here is a log:

[20211002_032527.txt](https://github.com/rocksdanister/lively/files/7271056/20211002_032527.txt)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/358
