### ISSUE TITLE
Video Error When Processing / Windows N

### ISSUE THREAD

**Issue by Stickfan344** [rocksdanister/lively#773]
When i drag a video file over into the app, it gives me an error code and then doesnt process the video?

Edit : Oh yeah, it told me to give the log file aswell

[lively_log_20211003_160802.zip](https://github.com/rocksdanister/lively/files/7273478/lively_log_20211003_160802.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/609
