### ISSUE TITLE
Wallpaper pauses only on 1 monitor

### ISSUE THREAD

**Issue by FerretBoiX** [rocksdanister/lively#775]
**Describe the bug**
The wallpaper pauses only on 1 monitor when an application is focused.

**To Reproduce**
1. Set "Applications Focused" to Pause.
2. Set Placement Method to Duplicate same wallpaper.
3. Focus another application.

**Expected behavior**
The wallpaper should pause on both monitors.

**Desktop:**
 - OS: Windows 10 20H2

**Comment by rocksdanister** [comment]
Set pause rule to `All Screens`

![Screenshot 2021-10-04 131703](https://user-images.githubusercontent.com/17554161/135812918-87ed7c99-9232-4547-9bec-a1e055bda574.png)
