### ISSUE TITLE
Can't add video wallpaper / mpv error while decoding frame.

### ISSUE THREAD

**Issue by dxleak** [rocksdanister/lively#776]
i saw logs, here is the error :

2021-10-05 20:06:45.7393|INFO|livelywpf.Core.VideoMpvPlayer|Mpv1: Error while decoding frame!

**Comment by rocksdanister** [comment]
Change videoplayer to wmf in settings:

![Screenshot 2021-10-06 000638](https://user-images.githubusercontent.com/17554161/136082794-8fb31409-e88e-4170-8f47-124d5133d5d5.png)
.
