### ISSUE TITLE
A suggestion about changing the wallpaper with the theme

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#781]
In the process of using WIN10, when I want to use the transparent taskbar, the experience is a bit bad: especially when I use the automatic switching night mode, the colors of the day and night icons are different. So I suggest that the author add an option so that we can choose the corresponding wallpaper according to day and night

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/137
