### ISSUE TITLE
Google Earth as URL Not Working

### ISSUE THREAD

**Issue by quinxy** [rocksdanister/lively#784]
This was maybe a lot to hope for, but here's what I was trying to achieve...  Google Earth web version running as a background, then if that worked I was going to see if I could attach the selenium web driver to the cef instance (not sure that's possible) so I could command it to pan slowly around the world.  But at any rate I got stopped at the first because Google Earth doesn't load, it just has the loading dialog continually spinning, and the page didn't load properly.

Just curious if anyone knows why it might not work or how I could make it work.

**Comment by rocksdanister** [comment]
If you enable `Debug` in Misc settings, you can read the debug logs:
![Screenshot 2021-10-09 035912](https://user-images.githubusercontent.com/17554161/136631259-cb32fc8b-4043-4d82-913c-0dfc90edc9f4.png)

Looks like this is the culprit:
```SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.```

Why not try the application version of Google Earth?
https://github.com/rocksdanister/lively/wiki/Application-Wallpaper

**Comment by quinxy** [comment]
That's fantastic, I had no idea that feature was part of Lively!  I'd been looking around for just such a thing but had no idea this supported it.  Amazing.  I'll try that route.

**Comment by rocksdanister** [comment]
@quinxy I just checked with Edge webview, its working.. follow these instructions:
https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef#webview2-microsoft-edge

**Comment by quinxy** [comment]
Thanks for checking on the webview.  Before I try that (since scripting it will be complicated) can I ask about the Application-Wallpaper?  I tried to follow your instructions but am running into a few problems:
1) I tried using the link you have me, manually creating the LivelyInfo.json file, populating that, zipping it up in the root of a zip called Lively.zip and when I tried to add it it told me it wasn't a value wallpaper file.  I didn't include in the zip the exe/etc. since it has all its dependencies/etc. I thought maybe it could use what's already on the file system.  I don't know if that was the issue.  I even tried the "IsAbsolutePath" thinking maybe that would use the links I'd given it.  Below is my json file.
2) I then went and used the GUI to see if giving it an EXE would work, and it sort of seemed like it was trying to.  it took the link, tried to run the program, but it doesn't seem like it runs properly.  Even if it did run I would need to modify the arguments it launches with, and I don't see how to modify that.  I checked the default wallpapers location and I don't find this new wallpaper there.  I tried exporting the wallpaper and then re-importing it once i make the LivelyInfo.json change but when I try to add it I get the same error as in 1 that "Not Lively wallpaper file."

```json
{
  "AppVersion": "1.3.0.0",
  "Title": "Google Earth Pro Tour",
  "Thumbnail": null,
  "Preview": null,
  "Desc": null,
  "Author": null,
  "License": null,
  "Contact": null,
  "Type": 0,
  "FileName": "C:\\Program Files\\Google\\Google Earth Pro\\client\\googleearth.exe",
  "Arguments": "C:\\Lively\\world_tour.kml",
  "IsAbsolutePath": true
}
```

Thanks.

**Comment by quinxy** [comment]
Thanks for checking on the webview.  Before I try that (since scripting it will be complicated) can I ask about the Application-Wallpaper?  I tried to follow your instructions but am running into a few problems:
1) I tried using the link you have me, manually creating the LivelyInfo.json file, populating that, zipping it up in the root of a zip called Lively.zip and when I tried to add it it told me it wasn't a value wallpaper file.  I didn't include in the zip the exe/etc. since it has all its dependencies/etc. I thought maybe it could use what's already on the file system.  I don't know if that was the issue.  I even tried the "IsAbsolutePath" thinking maybe that would use the links I'd given it.  Below is my json file.
2) I then went and used the GUI to see if giving it an EXE would work, and it sort of seemed like it was trying to.  it took the link, tried to run the program, but it doesn't seem like it runs properly.  Even if it did run I would need to modify the arguments it launches with, and I don't see how to modify that.  I checked the default wallpapers location and I don't find this new wallpaper there.  I tried exporting the wallpaper and then re-importing it once i make the LivelyInfo.json change but when I try to add it I get the same error as in 1 that "Not Lively wallpaper file."

{
  "AppVersion": "1.3.0.0",
  "Title": "Google Earth Pro Tour",
  "Thumbnail": null,
  "Preview": null,
  "Desc": null,
  "Author": null,
  "License": null,
  "Contact": null,
  "Type": 0,
  "FileName": "C:\\Program Files\\Google\\Google Earth Pro\\client\\googleearth.exe",
  "Arguments": "C:\\Lively\\world_tour.kml",
  "IsAbsolutePath": true
}

Thanks.

**Comment by quinxy** [comment]
In the log when I tried to launch the app by adding its exe I had this in the log:
```
2021-10-09 15:04:22.8113|INFO|livelywpf.SetupDesktop|Setting wallpaper: Google Earth Pro | C:\Program Files\Google\Google Earth Pro\client\googleearth.exe
2021-10-09 15:04:24.0167|ERROR|livelywpf.NLogger|HRESULT: 1400, Failed to set window as parent to framework(1) at
C:\Users\rocks\source\repos\livelywpf\livelywpf\Helpers\WindowOperations.cs (128)
SetProgramToFramework
2021-10-09 15:04:24.0167|ERROR|livelywpf.NLogger|HRESULT: 1400, Failed to set window parent at
C:\Users\rocks\source\repos\livelywpf\livelywpf\Helpers\WindowOperations.cs (148)
SetParentSafe
2021-10-09 15:04:24.0167|ERROR|livelywpf.NLogger|HRESULT: 1400, Failed to set window as parent to framework(2) at
C:\Users\rocks\source\repos\livelywpf\livelywpf\Helpers\WindowOperations.cs (139)
SetProgramToFramework
2021-10-09 15:04:27.3976|ERROR|livelywpf.NLogger|HRESULT: 1400, Failed to set window parent at
C:\Users\rocks\source\repos\livelywpf\livelywpf\Helpers\WindowOperations.cs (148)
SetParentSafe
2021-10-09 15:04:35.4505|INFO|livelywpf.SetupDesktop|Setting wallpaper: Google Earth Pro | C:\Program Files\Google\Google Earth Pro\client\googleearth.exe
2021-10-09 15:04:36.3253|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=3840,Height=2160}
2021-10-09 15:04:36.3253|ERROR|livelywpf.NLogger|HRESULT: 1400, Failed to set perscreen wallpaper(1) at
C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\SetupDesktop.cs (599)
SetWallpaperPerScreen
2021-10-09 15:04:36.3253|ERROR|livelywpf.NLogger|HRESULT: 1400, Failed to set window parent at
C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\SetupDesktop.cs (1201)
SetParentWorkerW
2021-10-09 15:04:36.3447|ERROR|livelywpf.SetupDesktop|Failed processing wallpaper: System.Exception: Failed to set window parent.
   at livelywpf.SetupDesktop.SetParentWorkerW(IntPtr windowHandle) in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\SetupDesktop.cs:line 1202
   at livelywpf.SetupDesktop.SetWallpaperPerScreen(IntPtr handle, LivelyScreen targetDisplay) in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\SetupDesktop.cs:line 603
   at livelywpf.SetupDesktop.SetupDesktop_WallpaperInitialized(Object sender, WindowInitializedArgs e) in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\SetupDesktop.cs:line 402
2021-10-09 15:05:21.9033|INFO|livelywpf.SetupDesktop|Setting wallpaper: Google Earth Pro | C:\Program Files\Google\Google Earth Pro\client\googleearth.exe
2021-10-09 15:05:22.2253|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=3840,Height=2160}
```

I see no log messages relating to it telling me the wallpaper file is not valid.

**Comment by rocksdanister** [comment]
>Even if it did run I would need to modify the arguments it launches with, and I don't see how to modify that.

When you drop the .exe file into Library you should get a dialog to enter commandline arguments:
![Screenshot 2021-10-11 161735](https://user-images.githubusercontent.com/17554161/136778034-48eeaea9-6c71-4a86-bcd0-f7a916a46953.png)
Looks like I did not enable that for the add wallpaper page yet..

>I tried using the link you have me, manually creating the LivelyInfo.json file, populating that, zipping it up in the root of a zip called Lively.zip and when I tried to add it it told me it wasn't a value wallpaper file. 

The "Not Lively wallpaper file." error happens when LivelyInfo.json file is not in root location of zip (not inside any folder.)
https://github.com/rocksdanister/lively/blob/4b73808d01480d8d3a9414619289b3ceb6b90ba4/src/livelywpf/livelywpf/Helpers/Zip/ZipExtract.cs#L27-L30

>I even tried the "IsAbsolutePath" thinking maybe that would use the links I'd given it.

Yes that is what it should do.

>2021-10-09 15:04:24.0167|ERROR|livelywpf.NLogger|HRESULT: 1400, Failed to set window as parent to framework(1) at
C:\Users\rocks\source\repos\livelywpf\livelywpf\Helpers\WindowOperations.cs (128)
SetProgramToFramework

Looks like its failing to add it as wallpaper, have you tried restarting the system/explorer?
