### ISSUE TITLE
Wallpaper freezing

### ISSUE THREAD

**Issue by obesedog123** [rocksdanister/lively#787]
**Describe the bug**
Web stream wallpaper is freezing.

**To Reproduce**

**Expected behavior**
Web stream wallpaper to play without freezing.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by obesedog123** [comment]
![image](https://user-images.githubusercontent.com/84015324/136650008-0024124a-24d9-4be3-83ab-5ff1d7014265.png)
giving this error

**Comment by rocksdanister** [comment]
Download the video and set the file as wallpaper.
