### ISSUE TITLE
 Problem with setting wallpaper

### ISSUE THREAD

**Issue by Fetre** [rocksdanister/lively#80]
When i want to set the wallpaper, they say me this.
Working only first two wp-pers.
What i need to do?

![image](https://user-images.githubusercontent.com/67320291/85396986-f1788100-b57c-11ea-895e-ed2bc3784084.png)

**Comment by rocksdanister** [comment]
Try restarting windows and try again.
Can you also try changing your windows system language to English and try?

**Comment by Fetre** [comment]
I reinstall this, but u see the result. Idk what i'm doing wrong

![image](https://user-images.githubusercontent.com/67320291/85427112-87280680-b5a5-11ea-8773-7d02ee6eadb7.png)

**Comment by rocksdanister** [comment]
>Can you also try changing your windows system language to English and try?

~Windows language settings, not lively.~

I'll upload a different version of the browser that uses mutex checking instead of process checking to identify lively.
(internet is currently slow, will need to wait.)

**Comment by rocksdanister** [comment]
Try using this version:
https://github.com/rocksdanister/lively-cef/releases/tag/v5.0

Extract the contents of the zip to:
`Documents/Lively Wallpaper/cef folder.`

It should be like this order:
`Documents/Lively Wallpaper/cef/LivelyCefSharp.exe`

and try again.

**Comment by Fetre** [comment]
Oh ya, now it works bruh.
Thanks. ♥
