### ISSUE TITLE
After opening laptop after sleep mode

### ISSUE THREAD

**Issue by WingsOfHell01** [rocksdanister/lively#801]
After I open my laptop from Sleep Mode on windows 11, lively wallpaper doesn't display my live wallpaper and the wallpaper is set to the wallpaper assigned by windows despite lively wallpaper running in the background. To get my live wallpaper back i have to relaunch the app. Is there a fix for this issue.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/761#issuecomment-929504484
