### ISSUE TITLE
Stream wallpaper freeze

### ISSUE THREAD

**Issue by szmusic** [rocksdanister/lively#803]
helleo , 
 
me installed this programm and its very nice. i got an i9990K and rtx 3080. the programm worked fine al lot of weeks, but now i got problems. 

loading from videos takes very long time and after set its freeze and run 10 sec and get again freeze. other videos i cant set is loading and nothing happens. 

someone know why ?

best regards

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by ToxicHeadsh0t** [comment]
I've been having this problem alot too... And it's annyoing alot.

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/729

**Comment by szmusic** [comment]
> #729

what is this numnber ?

**Comment by zchrxh** [comment]
It's an issue number. Click it to view the issue of that assigned ID.
