### ISSUE TITLE
wallpapers freezing more than actually playing

### ISSUE THREAD

**Issue by rs-keNa** [rocksdanister/lively#804]
**the bug**
youtube link wallpapers freezing more than playing

**how do i do this lmao**
add a wallpaper
enter a youtube link
thats it

**expected behavior**
for the wallpaper to work like normal

**os and other stuff**
![image](https://user-images.githubusercontent.com/92559710/137422465-5157abfa-a480-4515-a4b7-419c5ca9e664.png)

**more other stuff**
worked fine this morning
i havent changed any settings at all

**logs**
[lively_log_20211014_222144.zip](https://github.com/rocksdanister/lively/files/7350439/lively_log_20211014_222144.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/729
