### ISSUE TITLE
Support Multiple Desktops on Windows 11

### ISSUE THREAD

**Issue by tellmewhy12** [rocksdanister/lively#808]
**Is your feature request related to a problem? Please describe.**
Windows 11 just got the cool multiple desktops wallpaper feature which lets you assign a different background image for every virtual desktop

**Describe the solution you'd like**
- Rightclick on wallpaper -> Set as wallpaper for desktop
- Show a view of all desktops with their names
- Click on the desktop you want to assign the wallpaper to

**Describe alternatives you've considered**
/

**Comment by rocksdanister** [comment]
related https://github.com/rocksdanister/lively/issues/488?
