### ISSUE TITLE
Stream wallpapers show title bar etc and customise menu don't work

### ISSUE THREAD

**Issue by IsamKarroum** [rocksdanister/lively#809]
Whenever I try to upload a webpage wallpaper from youtube, it plays sound over apps even with the option turned off(the option isn't the issue trust me), it also has the title and all the annoying icons from a youtube video. On top of that, trying to upload a stream from youtube just spits out the preview that my browser can't play it. I dont know how to recreate it, It was working fine for like 3 months then randomly wouldn't let me play what I already had in my library (all the preset ones work tho)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
[lively_log_20211016_183924.zip](https://github.com/rocksdanister/lively/files/7358355/lively_log_20211016_183924.zip)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/805
