### ISSUE TITLE
Can Lively call mpv and subsequently youtube-dl executables via PATH?

### ISSUE THREAD

**Issue by Jacosci** [rocksdanister/lively#81]
It would be really useful for people like me who already use mpv+youtube-dl as their media player.

**Comment by rocksdanister** [comment]
I want to do full commandline integration for lively, will look into this then.

New features will have to wait as I'm currently in the process of completely rewriting everything for v1.0 release.

**Comment by rocksdanister** [comment]
Going forward lively will be using libvlc as default videoplayer for streaming https://github.com/rocksdanister/lively/commit/7cf6b88c1c240968e75f2e600cbb726b3050a961

Closing this issue for now.
