### ISSUE TITLE
Hello the bug is that I go to a tab like google and my background music doesn't stop like it used to

### ISSUE THREAD

**Issue by Gamerpro322109** [rocksdanister/lively#810]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/805

**Comment by Gamerpro322109** [comment]
How do i open it again?
