### ISSUE TITLE
Lively HTML5 wallpaper Lost Context

### ISSUE THREAD

**Issue by GhazanfarAteeb** [rocksdanister/lively#811]
I was using Mozilla Firefox and WhatsApp Web when this happened though Lively was working in the background. Attaching log file related to what had happened. If there is any issue on my end let me know to fix it because I personally liked this app.
[20211017_110459.txt](https://github.com/rocksdanister/lively/files/7358995/20211017_110459.txt)
.

**Comment by rocksdanister** [comment]
https://stackoverflow.com/questions/25219352/webgl-scene-doest-render-because-of-lost-context

**Comment by GhazanfarAteeb** [comment]
Thanks it seems it will solve the problem because it is taking too much GPU. Anyways thanks for your help 😄😄

**Comment by rocksdanister** [comment]
Might be a VRAM issue, try using lighter wallpapers.
Hopefully when I implement Kill wallpaper feature in performance settings this won't be a problem.
