### ISSUE TITLE
Stream wallpaper issues / Видео перезагружается постоянно. Каждый раз теряется качество видео , загружаемого с ютуба

### ISSUE THREAD

**Issue by SMaybeS** [rocksdanister/lively#815]
Здравствуйте!
В самом новом обновлении у меня загружаются видео с YouTube, но в маленьком качестве(Интернет-соединение хорошее).
К тому же, видео каждые секунд 30 перезагружается(На секунду появляется чёрный экран и снова обои).
При каждом запуске обоев, сверху высвечивается меню YouTube с названием видео, количеством видео в плейлисте(1/1) и так далее.

Translate on English by Google Translator:

Hello!
In the newest update, I have YouTube videos downloaded, but in low quality (Internet connection is good).
In addition, the video reloads every 30 seconds (For a second, a black screen appears and again the wallpaper).
Each time you launch the wallpaper, the YouTube menu is highlighted at the top with the name of the video, the number of videos in the playlist (1/1), and so on.

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/805
