### ISSUE TITLE
Bug with the new version of the app

### ISSUE THREAD

**Issue by Cormixul** [rocksdanister/lively#822]
**Describe the bug**
When I go on apps that are fullscreen and then back to the desktop I can see for a couple of seconds the youtube "HUD".

**To Reproduce**
1.I go to a fullscreen app (ex: to my browser)
2.I stay on the browser for more than ~5 seconds
3.I go back to desktop

**Expected behavior**
This problem didn't exist and I've been using Lively for atleast 5 months now.

**Screenshots/Video**
Added.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
- "Bouncing DVD Logo Screensaver 4k 60fps"

**Additional context**
None.

**Log file (Important)**
Added.
[lively_log_20211019_070823.zip](https://github.com/rocksdanister/lively/files/7370079/lively_log_20211019_070823.zip)
<img width="960" alt="livelybug" src="https://user-images.githubusercontent.com/92772270/137842519-0e548bfa-424f-40c1-b03f-062e23597919.png">

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/805
