### ISSUE TITLE
Better application pause rules user experience

### ISSUE THREAD

**Issue by daephx** [rocksdanister/lively#829]
**Issue**
Application rules only allow the user to specify a valid executable file: `.exe`

**Solution**
Rather than just an `.exe` file, perhaps this could Provide a list of open processes as they are presented in `Task Manager > Details`. Other applications such as Discord and [Aurora RGB](https://github.com/antonpup/Aurora) have similar functionality regarding this form of app detection.

*Additional Context*
In my case, I using Windows Terminal installed from the Microsoft Store, I have set it to be transparent because it looks real nice! and I'm trying to keep the wallpaper animation enabled when it is in focus/fullscreen.

Trying to punch in: 
`C:\Users\<USER>\AppData\Local\Microsoft\WindowsApps\wt.exe` to the lively's application rules just throws an error. 
![image](https://user-images.githubusercontent.com/36192863/138177956-5514171a-5b4a-47f4-9885-3c24aaade25a.png)

I'm not well versed in how Microsoft Store `.appx`? is handled. But from what I can tell they are somewhat Isolated and don't allow access to the executable. The above enhancement could potentially allow this to work without having to disable `Performance > Fullscreen > Pause` for all other applications.

If you know any workarounds for the time being, I would appreciate the info.

**Comment by rocksdanister** [comment]
>Rather than just an .exe file, perhaps this could Provide a list of open processes as they are presented in Task Manager > Details

Good idea!
>If you know any workarounds for the time being, I would appreciate the info.

For the time being you can edit the config file manually: 
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\AppRules.json`

```json
[
  {
    "AppName": "Discord",
    "Rule": 1
  },
  {
    "AppName": "W3Clock",
    "Rule": 0
  }
]
```
Restart the application for settings to take effect.

**Comment by daephx** [comment]
Manually editing the config works great! Thanks for considering this feature.

**Comment by rocksdanister** [comment]
https://user-images.githubusercontent.com/17554161/184355494-c629f4cf-de75-4873-9b22-6b71e5c66208.mp4


Done! List shows running programs and users can add additional program by browsing.

**Comment by jamescporter** [comment]
This feature doesnt show for me. I cant see the find more applications button

**Comment by rocksdanister** [comment]
1. What's your display resolution and windows scaling?
2. Share a screenshot of the issue.
