### ISSUE TITLE
Error "Your browser can't play this video." in YouTube Live Stream

### ISSUE THREAD

**Issue by sato886** [rocksdanister/lively#830]
**Describe the bug**
Since 14-Oct-2021, Lively Wallpaper failed to play YouTube Live Streams and showed an error "Your browser can't play this video." on wallpapaer

**To Reproduce**
Case 1: Failed to play YouTube Live Stream wallpaper
1. Go to 'Library'
2. Click a 'YouTube Live Stream' wallpaper to play
3. Wallpaper will show "Your browser can't play this video."

Case 2: Failed to add YouTube Live Stream wallpaper
1. Go to 'Add Wallpaper'
2. Enter a YouTube Live Stream URL (e.g. https://www.youtube.com/watch?v=9-sfWSHtJdk)
3. Preview will show "Your browser can't play this video."

**Expected behavior**
Set YouTube Live Stream as lively wallpaper

**Screenshots/Video**
Case 1:
![yt_live_cant_play](https://user-images.githubusercontent.com/8295204/138201444-c94bb017-3808-4f97-ba57-88e575180eb8.png)
Case 2:
![yt_live_cant_play_2](https://user-images.githubusercontent.com/8295204/138201477-7af74d0c-53a6-488e-8e25-613cb4a3d4fe.png)

**Desktop (please complete the following information):**
- Windows 10 Pro 21H1
- Which wallpaper was running at the time if any:
- https://www.youtube.com/watch?v=9-sfWSHtJdk
- https://www.youtube.com/watch?v=Sv9hcJ3k5h4

**Additional context**
None

**Log file (Important)**
[lively_log_20211021_103805.zip](https://github.com/rocksdanister/lively/files/7385609/lively_log_20211021_103805.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#not-working

**Comment by nailimac** [comment]
sa na pas fonctionné pour moi

**Comment by nailimac** [comment]
that not work for me

**Comment by Pleblo** [comment]
I also have the same problem, it wont play live streaming videos

https://www.youtube.com/live/VsN7KWwcPqA?feature=shared

 "Your browser can't play this video."

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/1598#issuecomment-1560201438
