### ISSUE TITLE
Duplicate layout not working for stream wallpaper

### ISSUE THREAD

**Issue by ghost** [rocksdanister/lively#831]
**Describe the bug**
Just upgraded to 1.7.2.4 and the 'Duplicate same wallpaper' option is not working anymore.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1288
- Tried 6-7 diffrent ones.

**Log file (Important)**
[20211021_165946.txt](https://github.com/rocksdanister/lively/files/7390710/20211021_165946.txt)

**Comment by rocksdanister** [comment]
Follow this instruction:
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#not-working

**Edit:**
Fixed in v1.7.2.6 update.
