### ISSUE TITLE
YouTube Videos as Wallpapers don't work anymore

### ISSUE THREAD

**Issue by DLarisa** [rocksdanister/lively#837]
Hello. 
So, I always start my laptop with a video from youtube using lively. I updated the app today because, lately, the video was buffering (no other problem; otherwise I would have not updated at all). I am using lively for maybe a year or so and no other issues have arised.
I updated today and the app is not allowing me to put any video from YT as wallpaper anymore. When I try, the screen gets black and I can only hear the sound; but if I try to pause, mute etc... lively, it has no effect. The only things that works now are the wallpapers that are preinstalled. 
Here is the log file:
[20211022_202353.txt](https://github.com/rocksdanister/lively/files/7400404/20211022_202353.txt)
Can you help me please?

**Comment by rocksdanister** [comment]
Read the stream section of change notes:
https://github.com/rocksdanister/lively/releases/tag/v1.7.2.6

**Comment by DLarisa** [comment]
Is it normal for the videos to still buffer?
I tried both options: with yt-dl and with edge and the videos still buffer.

**Comment by rocksdanister** [comment]
>Is it normal for the videos to still buffer?

https://github.com/rocksdanister/lively/issues/729

**Comment by rocksdanister** [comment]
>I tried both options: with yt-dl and with edge and the videos still buffer.

Edge is just opening the link.. it should not buffer unless something is wrong with your network.
(If you have yt-dl .exe present then Edge won't be used,)

**Comment by DLarisa** [comment]
Well I moved yt-dlp.exe in the plugins\mpv folder instead of the youtube-dl.exe and now it doesn't work at all. :( Sorry to keep bothering you but I don't know what's happening. 
As for the Edge options, I uninstalled it bcs it didn't work better and my connection is working very well

**Comment by rocksdanister** [comment]
Rename dlp to youtube-dl.exe

**Comment by DLarisa** [comment]
OMG!!! Now it's working. Thank you so much <3 <3 <3!!! And I am sorry for troubling you, but now everything is fine. Again, thanks from my heart
