### ISSUE TITLE
issues regarding the web-streamed video wallpapers

### ISSUE THREAD

**Issue by Tired0ogway** [rocksdanister/lively#845]
so I have a youtube video that is being web-streamed as my wallpaper, but I think I updated it recently and I see some bugs.
first of all the video when placed shows youtube UI elements in the background which is weird
then I see that the video when actually played is rendering at 360-480p, which is so bad compared to the previous versions,
also, the customization which are speed, gamma, contrast, brightness, and more are not working for webstream videos.
lastly, even when the video's audio is muted I see the music playing notification in windows 10.
![image](https://user-images.githubusercontent.com/87137686/138601222-7cb3d236-d8b2-4cd0-a5d4-afaede7ef39c.png)
![image](https://user-images.githubusercontent.com/87137686/138601244-2c90d235-52b5-4270-bbba-61bb1fefec14.png)
![image](https://user-images.githubusercontent.com/87137686/138601327-43907a1f-b89f-4ae4-ac05-73c823351179.png)
the last image shows the quality degradation

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/releases/tag/v1.7.2.6
