### ISSUE TITLE
Stream wallpapers doesn't pause after opening another application over the desktop

### ISSUE THREAD

**Issue by SMaybeS** [rocksdanister/lively#846]
**`Hello!`**
After installing a new version, the wallpaper does not turn off after any application in the foreground is turned on.
Added "Suspend" in "Performance" and added to exceptions as a separate application. It didn't help, the wallpaper doesn't stop and the music from the wallpaper continues to play.
There was no such error in older versions of the application.
Please correct.
Have a nice day!

I attach a video with an error to [google drive](https://drive.google.com/file/d/1nr7RCUfwxZ_s3OUEEyyF4hXCiiWAiTEd/view?usp=sharing):

**Comment by rocksdanister** [comment]
Rendering is paused, only audio is played:
https://github.com/rocksdanister/lively/releases/tag/v1.7.2.6
