### ISSUE TITLE
Settings aren't working- Audio playing while on another app

### ISSUE THREAD

**Issue by AmineMo0** [rocksdanister/lively#847]
i noticed that while using a wallpaper from a YouTube video the sounds keeps playing even when i am on fullscreen  on another app. i didn't have this issue before. i tried the "play audio only when desktop is focused" option but didn't work that's when i noticed that other options don't work. like the  Master volume slider doesn't change anything and the Performance section basically doesn't change a thing. i didn't have this issue before too.
i reinstalled the app but still didn't fix it

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/releases/tag/v1.7.2.6
