### ISSUE TITLE
Add Feature request template (new issue button)

### ISSUE THREAD

**Issue by Martin5001** [rocksdanister/lively#85]
This issue is not related to the app itself (nice work btw.) but this GitHub repo:

When I click to open a new issue, github shows me the Report bug button. But not all issues are necessarily bug reports and I think some people might get confused a little when they want to submit a feature request but are presented only with the Bug report button.
So I think it would be good to add a Feature request template (this shows the button then) to provide a more fluent experience when creating an issue.

**Comment by Martin5001** [comment]
Oh, now I see this got labeled as bug too. So this confused me too :D 
(I eventually found that there is a "open blank issue link" but I'm so used from other projects to having the second button, that I haven't noticed the link.)

**Comment by rocksdanister** [comment]
Done!
