### ISSUE TITLE
App crash with some taskbar themes set

### ISSUE THREAD

**Issue by KaiserTialoc** [rocksdanister/lively#850]
**Describe the bug**
Since upgrading to Windows 11 2 weeks ago Lively has stopped working and every time i open it it crashes

i deleted the installed lively and installed the new one from the microsoft store page and the error still keeps happening

i was using a custom wallpaper but tried using one of the stock and the problem still happens

when i click Lively it either doesnt open or it opens then closes straight away with nothing happening

**To Reproduce**
1. click lievly wallpaper app in taskbar
2. app either fails to launch or launches
3. app crashes with no error code showing

**Expected behavior**
i expect lively to launch and run the wallpaper whilst my laptop is active

**Desktop (please complete the following information):**
OS - Windows 11 Pro

Device name	LAPTOP-D3U16OH5
Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	0F1AE8F5-3F25-4186-95E4-C3DB9247DD75
Product ID	00330-51637-95446-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs
[20211026_210851.txt](https://github.com/rocksdanister/lively/files/7421256/20211026_210851.txt)
`
[20211026_210831.txt](https://github.co
[20211026_210450.txt](https://github.com/rocksdanister/lively/files/7421269/20211026_210450.txt)
m/rocksdanister/lively/files/7421261/20211026_210831.txt)
[20211026_210620.txt](https://github.com/rocksdanister/lively/files/7421268/20211026_210620.txt)

**Comment by rocksdanister** [comment]
Looks like its having some issue accessing the file used for calculating taskbar theme color:
```
2021-10-26 21:05:00.9601|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0: Screenshot: 'C:\Users\Connor\AppData\Local\Lively Wallpaper\temp\mpvsocketmabrxbud.jzk.jpg'
2021-10-26 21:05:00.9735|ERROR|livelywpf.App|Unhandled exception in livelywpf v1.7.2.6
System.IO.IOException: The process cannot access the file because it is being used by another process.
```

Reset the store app in settings and then set taskbar theme to Off and see if it crashes.

**Comment by sisonpi** [comment]
i had the same problem i unstalled / install the app is disabled taskbar customization and it works better now , but  computer reboot alone after few minute. thank for your work.

**Comment by omjthakre** [comment]
your lively wallpaper isn't applying mine or your provided wallpaper. It was working when I installed it, it was good for whole day and the next I can't apply its say error and when i got in then app try applying again it is not even applying its own provided ones. Please solve the problem but the app is good I like.

DEVICE - Hp pavilion 
SOFTWARE - Windows 11
