### ISSUE TITLE
Taskbar lively icon / mpv player visible on taskbar

### ISSUE THREAD

**Issue by GreastTT2** [rocksdanister/lively#854]
**Describe the bug**
Taskbar Lively Wallpaper icon shown when lively working in second monitor, if second monitor live wallpaper not working this bug will disappear.

**To Reproduce**
1. Turn on Lively
2. Turn on any wallpaper (That wallpaper should be working in second monitor)
3. See error

**Expected behavior**
Sometimes this bug working sometimes not, usually after loading Windows.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/63648841/139162408-565846a4-1ac1-41c9-a821-c824d3f51382.png)

**Desktop (please complete the following information):**
 - Windows 10 Home 10.0.19041

**Comment by rocksdanister** [comment]
Share the logfile
`Navigate to Lively settings (Gear icon) -> Misc. -> Log File`

**Comment by GreastTT2** [comment]
> 
> 
> Share the logfile `Navigate to Lively settings (Gear icon) -> Misc. -> Log File`
Latest log from that day:
[lively_log_20211027_195611.zip](https://github.com/rocksdanister/lively/files/7449566/lively_log_20211027_195611.zip)
