### ISSUE TITLE
32 Bit edition installed on 64 bit machine.

### ISSUE THREAD

**Issue by ITCMD** [rocksdanister/lively#856]
**Describe the bug**

It appears that all of the application executable files are 32 bit, despite running on a 64 bit machine.
![image](https://user-images.githubusercontent.com/32961763/139459916-8ca6faed-f19f-4088-9826-be04182b0ea5.png)
![image](https://user-images.githubusercontent.com/32961763/139459940-8add7892-2b4f-4683-9f48-94a7f0c55e63.png)

Some of the wallpapers use about 75% of my CPU, and it is likely because it is being emulated in 32 bit on a 64 bit system.

Is there a 64 bit edition or does it support 64 bit only through backwards compatibility?

**Comment by rocksdanister** [comment]
Lively is a 32bit only application.

>Some of the wallpapers use about 75% of my CPU, and it is likely because it is being emulated in 32 bit on a 64 bit system.

This is wrong - there will be no difference in performance , in-fact there is a slight memory reduction when running in 32bit mode:
https://en.wikipedia.org/wiki/WoW64#Performance

The high usage you see can be explained by other reasons:
https://github.com/rocksdanister/lively/wiki/Performance

**Comment by ITCMD** [comment]
> Lively is a 32bit only application.
> 
> > Some of the wallpapers use about 75% of my CPU, and it is likely because it is being emulated in 32 bit on a 64 bit system.
> 
> This is wrong - there will be no difference in performance , in-fact there is a slight memory reduction when running in 32bit mode: https://en.wikipedia.org/wiki/WoW64#Performance
> 
> The high usage you see can be explained by other reasons: https://github.com/rocksdanister/lively/wiki/Performance

Gotchya. Not sure where I learned that. Thanks for the clear explanation and examples! Sorry to have taken up your time.
