### ISSUE TITLE
Stream wallpaper "Video unavailable" error

### ISSUE THREAD

**Issue by CHeaPistaken** [rocksdanister/lively#860]
Sometimes lively wallpaper works for some wallpapers, but sometimes others dont work. https://www.youtube.com/watch?v=KmSNb7gZruw          is the wallpaper i was trying to use but it said video unavaliable. Windows 10 latest [version.]
[lively_log_20211017_122216.zip](https://github.com/rocksdanister/lively/files/7446728/lively_log_20211017_122216.zip)
![image](https://user-images.githubusercontent.com/92684766/139536079-ac9802a3-39a1-4320-937c-17ea2cf21c8b.png)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/releases/tag/v1.7.2.6
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#not-working
