### ISSUE TITLE
Whenever I close my computer, the video becomes unsynced with the computer and uses some other png that I have saved

### ISSUE THREAD

**Issue by hgygwywy** [rocksdanister/lively#864]
The only way to stop this is to redownload the app every time which is really annoying
<img width="72" alt="Screenshot 2021-10-31 165219" src="https://user-images.githubusercontent.com/93485603/139593947-108be305-0e49-48b3-a976-8f48053df676.png">

Also, whenever i click on something that i want to become my wallpaper it just unselects instantly. Hope you can fix!

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/802
