### ISSUE TITLE
4:3 monitor not supported anymore

### ISSUE THREAD

**Issue by tellmewhy12** [rocksdanister/lively#866]
**Describe the bug**
My second monitor looks like this with black bars:
![image](https://user-images.githubusercontent.com/71931749/139704913-93521417-50ca-4266-911f-572b9c1487ab.png)

**To Reproduce**

**Expected behavior**
Fill Methods work for youtube videos

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
- OS: Win11 21H2 22000.194
- youtube wallpaper

**Additional context**

**Log file (Important)**
(https://github.com/rocksdanister/lively/files/7454651/lively_log_20211101_172141.zip)

[lively_log_20211101_172141.zip]

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#not-working
