### ISSUE TITLE
Pausing only works when the focused window is fullscreen, ignores other fullscreen windows.

### ISSUE THREAD

**Issue by Gavin-Williams** [rocksdanister/lively#867]
**Pause is only able to detect fullscreen for the window in focus. Can't detect fullscreen for other apps.**

**How to reproduce:**
1. Makes sure that...
    Settings / Performance / Wallpaper Playback / Applications Fullscreen = Pause
    Settings / Performance / Wallpaper Playback / Applications Focused = Nothing
2. Open Edge and maximize it (fullscreen).
3. Open Task Manager in front of fullscreen Edge.
4. Switch Task Manager between floating and fullscreen, keeping it in focus.

Observe that when Task Manager is fullscreen, Lively processing drops to zero and when it is a floating window, Lively processing jumps up to the typical activity for the active wallpaper.

**Expected behavior**
I expect Lively to remain paused as long as any window is fullscreen and hiding the desktop, not just the window in focus.

**Screenshots/Video**

https://1drv.ms/u/s!AhbcRtciy6_0jctbNqplyxc0bkpdUw?e=E3bsgA

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (21H1) 19043.1320 / 
 - Windows Feature Experience Pack 120.2212.3920.0
- Running wallpaper was an MP4

**Log file**
https://1drv.ms/u/s!AhbcRtciy6_0jctarp0yHci5V03x6A?e=hEUJyB

**Comment by rocksdanister** [comment]
There can only be one foreground app at a time:
https://github.com/rocksdanister/lively/wiki/Performance#foreground-process

duplicate: https://github.com/rocksdanister/lively/issues/474

**Comment by Gavin-Williams** [comment]
The foreground app is irrelevant. To know if the wallpaper is visible, you'll either need to use an API that tells you whether the wallpaper is visible, or else enumerate through all the visible windows on the current desktop, map their regions against the screens size and work out wallpaper visibility from that. Using just the app in focus isn't going to work.

**Comment by rocksdanister** [comment]
and that's exactly what `All Process` algorithm is intended to do when ready?
