### ISSUE TITLE
Add a section to the README  about how to build from source 

### ISSUE THREAD

**Issue by Leftier** [rocksdanister/lively#87]
**Is your feature request related to a problem? Please describe.**
No.
I think It could be a good addition to encourage people to contribute

**Describe the solution you'd like**
- What versions of Windows/.NET Core/Visual Studio are needed
- Clear instructions on how to build from source 

**Describe alternatives you've considered**
-

**Additional context**
Take windows terminal README as and example
https://github.com/microsoft/terminal/blob/master/README.md#developer-guidance

**Comment by Leftier** [comment]
nvm found that information on the wiki
Duplicate of #33

**Comment by rocksdanister** [comment]
Current main dev branch is fluent:
https://github.com/rocksdanister/lively/tree/dev-v1.0-fluent-netcore/src/livelywpf/livelywpf

v1.0 will be a bit of work - requires .net 3.1 sdk, cross-dev support, Universal windows platform development, .Net desktop development,  Windows 10 1903 sdk.
After that, it should be pretty straightforward - open with VS 2019.
