### ISSUE TITLE
Uncaught ReferenceError: livelyPropertyListener is not defined

### ISSUE THREAD

**Issue by feelinpogi** [rocksdanister/lively#875]
**Describe the bug**
Wallpaper functions normally but when run for several hours, it crashes. The log produces the following message "Uncaught ReferenceError: livelyPropertyListener is not defined"

**To Reproduce**
1. Set Youtube video as wallpaper (I use one that is a 2 hour long view of a campfire)
2. Let run on loop for several (~6) hours
3. Experience crash

**Expected behavior**
I expected it to continue to run normally for 12 consecutive hours.

**Screenshots/Video**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.19043
- Which wallpaper was running at the time if any: Any youtube video on loop

**Additional context**
Part of the log mentions "SetupDesktop | Yt-dl not found, using fallback browser instead." I haven't tried chasing this down yet, but it could be a workaround solution for this bug to determine what this primary browser is and figure out how to install it.

**Log file (Important)**
Attached

[lively_log_20211108_143505.zip](https://github.com/rocksdanister/lively/files/7500351/lively_log_20211108_143505.zip)
[20211108_082319.txt](https://github.com/rocksdanister/lively/files/7500340/20211108_082319.txt)

**Comment by rocksdanister** [comment]
>Part of the log mentions "SetupDesktop | Yt-dl not found, using fallback browser instead." I haven't tried chasing this down yet, but it could be a workaround solution for this bug to determine what this primary browser is and figure out how to install it.

https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#not-working
