### ISSUE TITLE
Running with Game Mode Tasker: Doesn't save wallpapers and gives error: "It looks like some settings need to be set to make Lively work:"

### ISSUE THREAD

**Issue by ITCMD** [rocksdanister/lively#876]
**Describe the bug**
I use a game mode tasker which closes programs like Onedrive, Rainmeter, Lively, and more when a game is running to save performance. It then starts them up again once the game is closed.

Whenever it is started again. I provides this message:
![image](https://user-images.githubusercontent.com/32961763/140824876-4b32c94d-a78d-43b4-a735-257553a984b8.png)
The offending setting is set as Lively requests and no number of apply or unticking and reticking fixes the issue.
I notice no issues with Lively other than this one:

Upon Lively launching, be it from startup or from the game mode tasker, one, sometimes both of the displays has no live wallpaper displayed or set in the settings. I have to select each display and set the wallpaper again as if it is the first time setting it up.

**To Reproduce**
1. Set up Lively
2. Close with `taskkill /f /im "CefSharp.BrowserSubprocess.exe"` or `taskkill /f /im "livelywpf.exe"` (appears to make no difference which
3. Launch it via start menu
4. See error, one or more monitors has no wallpaper set.

**Desktop (please complete the following information):**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042

**Wallpaper**
Running Ribbon on vertical left monitor
Running Waves on primary

**Log file (Important)**
[lively_log_20211108_170737.zip](https://github.com/rocksdanister/lively/files/7500438/lively_log_20211108_170737.zip)

**Comment by rocksdanister** [comment]
Sorry, I do not have the time nor interest to develop and maintain support for third party unconventional scripts/optimizer apps that interfere with Lively's working.
