### ISSUE TITLE
Cant close lively except with x button. Doesnt save info on start.

### ISSUE THREAD

**Issue by ITCMD** [rocksdanister/lively#878]
> Sorry, I do not have the time nor interest to develop and maintain support for third party unconventional scripts/optimizer apps that interfere with Lively's working.

_Originally posted by @rocksdanister in https://github.com/rocksdanister/lively/issues/876#issuecomment-963678024_

Wanted to follow up on this, this happens whenever the program is closed by anything other than pressing the "x" and happens on every start. If you want I can resubmit the issue without reference to the game mode tasker.

Game mode tasker also isn't an app, unconventional or not, it's a term for any program that closes programs when a game is launched. In this case it uses "taskkill," a program built into windows to close programs. As stated in my steps to reproduce, you can reproduce this issue just with CMD.

Let me know if there's any other info I can offer you.

**Comment by sylveon** [comment]
Who knew that an app being forcefully killed wouldn't save its configuration right.

**Comment by rocksdanister** [comment]
>Close with taskkill /f /im "CefSharp.BrowserSubprocess.exe" or taskkill /f /im "livelywpf.exe" (appears to make no difference which

Makes a huge difference, livelywpf.exe is the main app that manages all wallpapers and runs a watchdog program alongside it to kill wallpapers in the event of unexpected crash (or kill in this case) and the other is one of the chromium subprocess of LivelyCefSharp.exe browser plugin..

>Upon Lively launching, be it from startup or from the game mode tasker, one, sometimes both of the displays has no live wallpaper displayed or set in the settings. I have to select each display and set the wallpaper again as if it is the first time setting it up.

I don't know what you are expecting me to do here, killing the app not only may cause corruption to the configuration file.. killing the chromium subprocess won't trigger the watchdog program checks and will cause some processes to linger as parent of desktop workerw used for rendering wallpaper.. and this is messing things up and causing Lively to no longer work in subsequent runs (hence the error message.)

For the error message to go away, restart windows/logoff and don't kill things like this.. just because its a tool that comes with windows does not mean its normal to just kill and relaunch a program frequently - especially a program like Lively that makes temporary changes to Windows during its operation.

**Comment by ITCMD** [comment]
> Who knew that an app being forcefully killed wouldn't save its configuration right.

I have never seen a program not save configuration when killed. A task is killed, even when you press "X", it's just expected. That's why most programs save their settings often, not just when they are closed . . .

> I don't know what you are expecting me to do here, killing the app not only may cause corruption to the configuration file.. killing the chromium subprocess won't trigger the watchdog program checks and will cause some processes to linger as parent of desktop workerw used for rendering wallpaper.. and this is messing things up and causing Lively to no longer work in subsequent runs (hence the error message.)

So just to confirm, there's no way to have another program of any type close the program? No API? No command line? No task handling at all? This is far from standard procedure. At the very least handling a non-forced termination requests would work (taskkill without the /f).

I understand if you don't want to add such features, and that's totally your right. However, please understand that since you're software is open source and you take both issues and feature requests on GitHub. This means that people are going to create issues and feature requests, and being able to explain their issues, or turn down requests, without a tone of arrogance and pure bewilderment on the stupidity of mankind will get you much farther than dismissal of everyone and a rude attitude.

I can live with features missing, or a program not working as intended. But honestly after this interaction I'd rather not use any software made by you. That doesn't, and probably shouldn't matter to you, but who knows who you'll talk to in the future, what opportunities they may be able to give you, and what kind of message you're sending to said person.

Have a good day.

**Comment by sylveon** [comment]
Pressing X on a window does not kill the app. It tells the app you would like to close the window and then the app interprets that as a message to exit, allowing it to save data. You wouldn't expect notepad to correctly save your unsaved file when you run `taskkill /f /im notepad.exe`, same applies here.

**Comment by ITCMD** [comment]
> Pressing X on a window does not kill the app. It tells the app you would like to close the window and then the app interprets that as a message to exit, allowing it to save data. You wouldn't expect notepad to correctly save your unsaved file when you run `taskkill /f /im notepad.exe`, same applies here.

But it does. When a task exits by itself, it runs any pre-determined tasks before moving to an end point and killing it's process. The terms might be different on a software level, but on a kernel level and as far as the system is concerned, it's exactly the same.

As I said though, another perfectly good and easy to implement, at least in C, alternative is to accept termination requests. So far, when a termination request is sent to livelywpf, it completely ignores it and does nothing.
