### ISSUE TITLE
Stream wallpapers not working

### ISSUE THREAD

**Issue by etherealkitty** [rocksdanister/lively#879]
Hello! I am new to this website...so... I'm sorry if this isn't the right way to say this.
 
Every time I try to drag in a youtube video to use as a new wallpaper the audio plays but the preview screen is either black or the video is way off to the right side. A few videos have worked before, but in 99% of the videos, the links I enter keep having the same issue. Also, I am unable to customize youtube videos to have muted audio like I can with local files. This isn't the main problem but I thought I'd address it in case that was unaware.

Overall, I have really loved this program as I think it is brilliant and so very convient. 

Thank you for your help. You can reach out to me with further questions if you'd like. Best of luck. 

.

![black screen](https://user-images.githubusercontent.com/93986424/140922555-4e654905-c459-4381-aed8-695821b0a72a.PNG)
**Screenshots/Video**

**Desktop (please complete the following information):**
 -  Windows 10 I'm pretty sure, Legion Gaming Laptop. 
- Which wallpaper was running at the time if any: a different youtube video on my other monitor that worked perfectly. 

**Additional context**
The default wallpapers work including the interactive fluid one. Youtube videos have worked perfectly before, but some falter and have the same issues as mentioned. I just got this program today so I don't have much experience. 

**Log file (Important)**

[lively_log_20211109_041802.zip](https://github.com/rocksdanister/lively/files/7504605/lively_log_20211109_041802.zip)

**Comment by Castang94** [comment]
Same problem here, sometimes the youtube grey screen appears saying that the video can't be played on my browser. Older versions worked perfectly. Thanks for your support!

**Comment by randallkk** [comment]
Same here, but it worked on some videos while not on the others. The videos were uploaded at the same day.
These are two.
Worked on : []
Not worked : []

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/837
