### ISSUE TITLE
Show/Hide system tray icon

### ISSUE THREAD

**Issue by MollyBe** [rocksdanister/lively#88]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when applications clutter the system tray menu.

**Describe the solution you'd like**
On right click of the system tray icon allow the user to toggle show/hide system tray icon. If the user runs livelywpf.exe it should open the client ui and display the system tray icon, as usual, but when the client ui is closed, it should also remove the system tray icon when the toggle is set to hide.

**Describe alternatives you've considered**
There are programs which can hide system tray icons but when you run livelywpf.exe, if it's already running it will not open the client ui, it will display an error: 
![image](https://user-images.githubusercontent.com/51837460/87235941-99e26e00-c3e2-11ea-96fd-066b78e69126.png)

**Additional context**
 v0.9.6.0 portable

**Comment by rocksdanister** [comment]
Lively needs to run in the background to manage the wallpaper windows, pause the wallpaper window when fullscreen apps run etc.

I personally don't think its a good idea to hide the icon on programs running in the background and user should always know its running.

Relaunching the application instance when .exe is clicked is looked into, looks like there is no easy(?) way to do it and I have to setup a local server of sort.

**Comment by MollyBe** [comment]
> I personally don't think its a good idea to hide the icon on programs running in the background and user should always know its running.

I currently have 103 background processes, imagine what your system tray would look like!

I respectfully disagree, it should not give the impression the program isn't running. A user would need to enable hide system tray icon therefor it is unlikely someone confuses this with exiting the program. I believe requiring this to be enabled is enough to mitigate that risk. 

Thank you for considering it.

**Comment by rocksdanister** [comment]
>I currently have 103 background processes, imagine what your system tray would look like!

Eh.. you get what I mean, foreground programs that are minimized to tray and run in background ready to be shown again != background processes.

There is no harm in a toggle hidden deep away in settings I guess, but first will have to get the .exe instance to relaunch to work.

**Comment by MollyBe** [comment]
> There is no harm in a toggle hidden deep away in settings I guess, but first will have to get the .exe instance to relaunch to work.

Thank you! If I was qualified I would take a look.

I doubt it could be as simple as removing the delay and [replacing:](https://github.com/rocksdanister/lively/blob/a801dd9a0c2d0846ae168cd689d9cd20befbeca0/src/livelywpf/livelywpf/Program.cs#L29-L35)

`MessageBox.Show("Already running!");`

 [with:](https://github.com/rocksdanister/lively/blob/6b84b59c6cd10bcbb248c56699b530b921a45673/src/livelywpf/livelywpf/Systray.cs#L35)

`Program.ShowMainWindow();`

**Comment by rocksdanister** [comment]
Nah, both are different process instance.
I think I will have to setup a local server for inter process communication on the first process - then when the second process runs it will sent a ipc message to the already running process to display itself.
