### ISSUE TITLE
Can't open any wallpapers

### ISSUE THREAD

**Issue by notfrye** [rocksdanister/lively#880]
Hi, I have been using Lively Wallpaper for a few months and it was great! Until some problems came up. It won't let me open any wallpapers! Every wallpaper I click on the app it will say there is an issue. Can you please help?

[lively_log_20211110_154623.zip](https://github.com/rocksdanister/lively/files/7510892/lively_log_20211110_154623.zip)

**Comment by rocksdanister** [comment]
>Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)

Switch browser to CefSharp or install webview2 runtime:
https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef#webview2-microsoft-edge
