### ISSUE TITLE
Windows 11 Snap Layouts crash Lively

### ISSUE THREAD

**Issue by Andrew-Geo** [rocksdanister/lively#888]
**Describe the bug**
Any Window Manager that supports Snap Layouts on Windows 11, will eventually crash Lively if the Snap Layouts overlay gets displayed. An error stating that Windows Explorer restarted 2 times, within 30 seconds appears, also notifying about the disabling of the wallpapers.

**To Reproduce**
1. Go to any Snap Layout supporting window
2. Hover the mouse pointer over the "Maximize Window" button
3. Wait for the Snap Layouts overlay to appear

**Expected behavior**
I'd expect no conflict between Snap Layouts and Lively.

**Screenshots/Video**
![Screenshot (93)](https://user-images.githubusercontent.com/94297792/141683711-3c03f667-1c61-4658-8f01-e1bde559f54b.png)

![Screenshot (94)](https://user-images.githubusercontent.com/94297792/141683716-fdc0da90-9407-4923-adc9-14779faa8233.png)

**Desktop:**
 - OS: Windows 11 21H2 22000.318
- Wallpaper: An .mp4 video file @ 1080p.

**Additional context**
I guess the problem occurs because of a conflict with resizing windows and the relative options within Lively, or Microsoft implemented Snap Layouts in a rather hacky way, messing the Windows Explorer itself, and Lively by extension (I doubt this).

**Log file (Important)**
[lively_log_20211114_150628.zip](https://github.com/rocksdanister/lively/files/7533768/lively_log_20211114_150628.zip)

**Comment by rocksdanister** [comment]
I can't reproduce this error on my test Win11 system.
Its using dev branch of Win11, maybe that's why.

Just to be sure:
1. Do you have any third party software that modify desktop or taskbar?
2. Try updating Windows?

Will leave this issue open and see if anyone else have same problem.

**Comment by Andrew-Geo** [comment]
> I can't reproduce this error on my test Win11 system. Its using dev branch of Win11, maybe that's why.
> 
> Just to be sure:
> 
>     1. Do you have any third party software that modify desktop or taskbar?
> 
>     2. Try updating Windows?
> 
> 
> Will leave this issue open and see if anyone else have same problem.

1. I was using TaskbarX on Win10 and did an upgrade from within Windows Update once it became available for my device. Now, it is uninstalled since Win11 centers taskbar icons by default. Other than that, there's no other software modifying the desktop and/or taskbar.*
2. Since posting this bug, the only available updates were security ones (no optional ones either). I did install them, but the problem persists.

*The only other piece of software that might be related is Winaero Tweaker. I'll attach my exported current settings just in case.
[Winaero Tweaker_2021_11_20.zip](https://github.com/rocksdanister/lively/files/7574785/Winaero.Tweaker_2021_11_20.zip)

**Comment by Andrew-Geo** [comment]
This actually is a Windows 11 issue. It has nothing to do with Lively.
Explorer.exe kept crashing whether Lively was running or not. I dug around a bit, and found that this was due to custom scaling not being set to 100%. Although, it still occurs on the preset 25% increments (125% being the recommended scale in my case)
I will mark this thread as closed.
