### ISSUE TITLE
Taskbar Theme stops working when an app asks for permissions on Win11

### ISSUE THREAD

**Issue by Chris6ix** [rocksdanister/lively#889]
When you have set a Taskbar Theme in Windows 11 and the pop-up when a Program requires extra permissions/admin rights comes up, the Taskbar on the Secondary Monitors turns the color you have set as your "Accent Color" in Windows.
This gets only fixed when you re-apply the Theme after the pop-up is gone, but when such a pop-up comes again, then it breaks again.

**Comment by DShader** [comment]
This might be by design as the UAC is a controlled/protected display. The bug is that it doesn't reinitalize after such events.

**Comment by Chris6ix** [comment]
Any updates on this?
The issue is still present in the latest version (v1.7.4.2)

**Comment by Chris6ix** [comment]
Just tested this again with v2.0.3.6 and the issue seems to be gone, so I'm closing this issue.
