### ISSUE TITLE
Shadertoy video render

### ISSUE THREAD

**Issue by bjhemsworth** [rocksdanister/lively#89]
The ability to pull in shaders from shadertoy is amazing and can make for some incredible desktop backgrounds.

Unfortunately a lot of those shaders are very gpu intensive.

An option in Lively to render some of these shaders to file at your desktop resolution for some time period would be great.
This would introduce some looping artefacts, but most shaders I've tried from Shadertoy max out my GPU (GTX 970) so I can’t really use them at all.

**Comment by rocksdanister** [comment]
I had a similar idea in the past, using libvlc should be possible from v1.0 onwards.
Closing this as I made a separate issue covering all wallpaper types: https://github.com/rocksdanister/lively/issues/90
