### ISSUE TITLE
Error while trying to run a video wallpaper / Windows N

### ISSUE THREAD

**Issue by Symasas225** [rocksdanister/lively#902]
I get an error while trying to run a wallpaper from the web. Wallpapers that come with the app are fine
[20211122_152636.txt](https://github.com/rocksdanister/lively/files/7581532/20211122_152636.txt)

**Comment by rocksdanister** [comment]
Windows N require codec installation:
https://github.com/rocksdanister/lively/wiki/Video-Guide
