### ISSUE TITLE
Wallpaper pausing whenever you click on the desktop

### ISSUE THREAD

**Issue by Profility** [rocksdanister/lively#908]
**Describe the bug**
Wallpaper pauses whenever you click on the desktop.

**To Reproduce**
1. Go to Settings > Performance
2. Change Applications Fullscreen setting value to Pause
3. Click on desktop whilst wallpaper is running

**Expected behavior**
Wallpaper running even when desktop is clicked on.

**Screenshots/Video**
Video: https://files.catbox.moe/66al7d.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 Home Insider Preview 22504.1010
- Wallpaper: Any

**Log file (Important)**
[lively_log_20211126_003547.zip](https://github.com/rocksdanister/lively/files/7604427/lively_log_20211126_003547.zip)

**Comment by rocksdanister** [comment]
I did patch this in beta:
https://github.com/rocksdanister/lively-beta/releases

It should only happen if explorer crashes and wallpaper restart.
