### ISSUE TITLE
Decimal slider for LivelyProperties.json slider object

### ISSUE THREAD

**Issue by cppshane** [rocksdanister/lively#91]
Most WebGL demos use the same settings GUI overlay, which has continuous (decimal) sliders. I'm currently just implementing manual scaling since it looks like the current slider only allows minimum ticks increments of 1, but it would be nice to have decimal sliders in version 1.0, so the customization options in Lively can directly match the WebGL animation demos.

**Comment by rocksdanister** [comment]
Currently the slider is just a wrapper around Winform [trackbar](https://github.com/rocksdanister/lively-cef/blob/ca3bd532d57d4a49e50e247231c45b7d72bc3886/src/cefsharptest/Widgets/SettingsWidget.cs#L107) and its being generated by the separate browser [program.](https://github.com/rocksdanister/lively-cef)
Yeah trackbar does not have floating option, scaling is current workaround.

I do plan to integrate it directly into the main program instead, this also means some of the newer [controls](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/) can be used.

**Comment by rocksdanister** [comment]
Slider and combobox are now using uwp controls: https://github.com/rocksdanister/lively/commit/552fc82cc44c371b1748f6cecfc6e20f448dec6a
![Annotation 2020-07-27 124150](https://user-images.githubusercontent.com/17554161/88514329-8270cb00-d007-11ea-9732-a93ab57f4e12.jpg)

Use "step" variable to set the decimal precision once Lively v1.0 releases:
https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#slider
