### ISSUE TITLE
Customize option not working

### ISSUE THREAD

**Issue by California-Gray** [rocksdanister/lively#910]
**Describe the bug**
The Customization menu does not open, even for wallpapers that are customizable, e.g "Eternal Light"

**To Reproduce**
1. Go to Library on the Lively Wallpaper app
2. Click on any wallpaper that can be customized
3. Right-click on the selected wallpaper
4. Click on "Customise" from the menu
5. See error: option does not open

**Expected behavior**
Clicking the "Customize button should open the customization menu 

**Screenshots**
Choosing a wallpaper
![Screenshot (155)](https://user-images.githubusercontent.com/95052401/143498164-9bc77718-d718-41c2-b432-32bd7eca9fba.png)

The wallpaper has been selected (The drawing over is for my privacy
![Screenshot (151)_LI](https://user-images.githubusercontent.com/95052401/143498296-b369c017-3ca3-4fc0-847f-9f0afbe92f24.jpg)

Opening the options menu and choosing "Customize"
![Screenshot (154)](https://user-images.githubusercontent.com/95052401/143498341-f2bc4027-722d-46e1-a6f6-02afed87a6f4.png)

The menu does not open
![Screenshot (155)](https://user-images.githubusercontent.com/95052401/143498553-a34c4238-7472-41f5-84c1-14007ec13e06.png)

**Desktop:**
 - OS: Windows 10 Pro 19044.1387
- Wallaper: Eternal Light

**Additional context**
This bug did not happen until today, 11.25.2021. I downloaded this app on 11.24.2021. I can customize the wallpaper by clicking the "Control Panel" icon in the top right corner. This takes me to a screen to control how the selected wallpaper is projected across more than one connected display. There is a button to customize.

**Log file**
[lively_log_20211125_125006.zip](https://github.com/rocksdanister/lively/files/7605175/lively_log_20211125_125006.zip)

**Comment by rocksdanister** [comment]
Restart the app (exit from tray and start again.) and see if it works?

**Comment by California-Gray** [comment]
> Restart the app (exit from tray and start again.) and see if it works?

It started working again yesterday. I didn't need to restart it or anything. I tried that on the day the issue arrived, but it didn't work.
