### ISSUE TITLE
The desktop wallpaper was not restored when lively exited

### ISSUE THREAD

**Issue by iray1024** [rocksdanister/lively#919]
**Describe the bug**
As the title says, the desktop wallpaper was not restored when lively exited
Often turns black solid wallpaper

**To Reproduce**
1. Start Lively
2. Setup Wallpaper
3. Exit

**Expected behavior**
I want to be able to restore the desktop wallpaper before starting lively when I exit lively, like Wallpaper Engine.

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
- A picture wallpaper.

**Log file (Important)**
No valuable log files

**Comment by rocksdanister** [comment]
Share the logfile

**Comment by iray1024** [comment]
[20211130_212024.txt](https://github.com/rocksdanister/lively/files/7626035/20211130_212024.txt)

I don't think this log file has any effect on this problem

**Comment by rocksdanister** [comment]
>I don't think this log file has any effect on this problem

Just checking the system config, operating system version and settings file.

Please share the full file:
Goto Lively settings (Gear icon) -> Misc. -> Log File

![Screenshot 2021-11-30 190402](https://user-images.githubusercontent.com/17554161/144056777-a7f04c6f-7bac-4521-bd47-7613a6056ab7.png)

**Comment by iray1024** [comment]
[Uploading lively_log_20211130_213520.zip…]()

**Comment by rocksdanister** [comment]
Looks like something went wrong.. try waiting for the file to upload first before pressing comment.

**Comment by iray1024** [comment]
[lively_log_20211130_213520.zip](https://github.com/rocksdanister/lively/files/7626099/lively_log_20211130_213520.zip)

**Comment by rocksdanister** [comment]
You have **Desktop Picture** turned on, it tries to set a snapshot of live wallpaper as desktop picture wallpaper:

![Screenshot 2021-11-30 191058](https://user-images.githubusercontent.com/17554161/144057916-11153bb2-02f9-4277-b2c2-e15eb4d06525.png)

Turn it off, this change is **permanent** meaning you will have to change the picture wallpaper from Windows settings:

![Screenshot 2021-11-30 191258](https://user-images.githubusercontent.com/17554161/144058145-ddd0b837-1510-4379-8f5c-582c913bc5cb.png)
