### ISSUE TITLE
"Customize Wallpaper" settings don't update when switching wallpapers.

### ISSUE THREAD

**Issue by cppshane** [rocksdanister/lively#92]
When you switch from a wallpaper with customizable settings to a new wallpaper with customizable settings, and open the settings window, the old settings remain there. You have to click "Restore Default" in order to reload the new wallpaper settings.

**Comment by rocksdanister** [comment]
The original settings is copied into a separate folder starting with monitor index as foldername and the modifications are done on the copy; the original only being used for settings restore.

One way to fix this would be to calculate and save the checksum or last day written of the original file and if it changes replace the copy with the new original file.

Will have to look into it.

**Comment by cppshane** [comment]
I think you misunderstand me.

1. Open web wallpaper 1 and open its "customize" window
2. Close web wallpaper 1
3. Open web wallpaper 2

If you then open the "customize" window with web wallpaper 2 running, the "customize" window will show the settings for web wallpaper 1.

**Comment by rocksdanister** [comment]
Are you using the latest version of lively? I thought I fixed that bug. 
Wonder if its related https://github.com/rocksdanister/lively/issues/21

**Comment by rocksdanister** [comment]
I get whats happening, lively properties is meant to be used with installed wallpaper not reference type.

You are using it on html file outside of Documents/lively wallpapers/wallpaper folder right?

To resolve it either install the wallpaper buy Exporting to lively .zip or rename the html folder with a unique name.
