### ISSUE TITLE
Audio gets muted even when fullscreen pause is Nothing

### ISSUE THREAD

**Issue by Harry-Tidey** [rocksdanister/lively#925]
**Describe the bug**

**To Reproduce**
1. Go to 'settings'
2. Click on 'performance'
3. Scroll down to 'applications fullscreen and select Nothing'

**Expected behavior**
I expected this setting to continue the live background when my apps were in fullscreen mode.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]  windows 10-21H2    
- a youtube video was playing: https://youtu.be/dh01eSOn9_E?list=TLGG1aXtQzeXb4QwMTEyMjAyMQ

**Additional context**
when I am on the lively app it works fine but on anything else it stops the video when  I'm not on the desktop 

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs` 
!!!   I DO NOT HAVE THOSE FILES   !!!

**Comment by rocksdanister** [comment]
It is working, its just audio gets muted by default.. turn off this option:

![Screenshot 2021-12-01 202115](https://user-images.githubusercontent.com/17554161/144256512-41da7212-af6a-47c9-9ec6-c0c9997cd813.png)

**Comment by Harry-Tidey** [comment]
OMG thank you sorry to bother you!
