### ISSUE TITLE
Error issues "Oops something went wrong..."

### ISSUE THREAD

**Issue by ibramsbr** [rocksdanister/lively#926]
Hy ~
I just installed and finish set up Lively Wallpaper, and when I was try to set a wallpaper in the software I found this problem. It says to drop the log files here to know what is the sollution.

Here's the error description :
"Oops... Looks like something went wrong :(
In order to better understand this error and fix the issue, share the log file with the developer........"

Then, here's the log files
[20211202_145525.txt](https://github.com/rocksdanister/lively/files/7640189/20211202_145525.txt)

**Comment by rocksdanister** [comment]
>Windows Education..

Windows N/Education require additional codec package to be installed:
https://github.com/rocksdanister/lively/wiki/Video-Guide
