### ISSUE TITLE
Live wallpaper disappears a few minutes after implementing it

### ISSUE THREAD

**Issue by asterblaster** [rocksdanister/lively#928]
I shut down and restarted my computer and go straight to lively wallpapers to choose the live wallpaper that I want, and the live wallpaper shows up. However, after a few minutes, the live wallpaper disappears to show the original wallpaper that the computer came with. I will go back to the lively wallpaper app to choose another wallpaper, but nothing happens when I click the wallpaper. 

Do you know why this is the case?

I'm on Windows 11 and on a gaming laptop, thanks!

**Comment by rocksdanister** [comment]
With the limited information its likely this issue https://github.com/rocksdanister/lively/issues/358
