### ISSUE TITLE
Not working with Windows picture slideshow

### ISSUE THREAD

**Issue by Generalmadnit** [rocksdanister/lively#931]
The app is unable to work when there is a slideshow of the wallpapers _( When the group of pictures are set as wallpaper )_. At first I thought it might be a small issue and might get fixed after restarting but it didn't even start after doing this.

Is there any possibility to have multiple wallpapers with the lively™ or should ought to have only one wallpaper

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/802
