### ISSUE TITLE
Switch Audio Output - audio visualizer stops working

### ISSUE THREAD

**Issue by IlCarlettoDiTurno** [rocksdanister/lively#932]
**Describe the bug**
Once Lively is on and you're playing some audio the fluidsV2 wallpaper has no problem, but if you switch the output audio source (speaker -> headphones) it stops working and has to be rebooted in order to start working on the new output.

**To Reproduce**
1. Turn on FluidsV2 wallpaper
2. reproduce audio
3. switch audio output

**Expected behavior**
continuing the animation synced with audio

**Desktop (please complete the following information):**
 - OS: Windows 11 home 2200
- Fluids v2

[lively_log_20211208_213255.zip](https://github.com/rocksdanister/lively/files/7678772/lively_log_20211208_213255.zip)

**Comment by ghost** [comment]
I have the exact same Issue. Please fix this
