### ISSUE TITLE
Desktop background

### ISSUE THREAD

**Issue by AzazelHD** [rocksdanister/lively#938]
Hi. I have noticed (as expected) that since lively wallpaper starts after windows, before it starts up your older windows desktop background appears. Until lively is running.

Could be too much asking to make lively choose the first fotogram (or whatever u want) as a static background too? Like, instead of manually changing the windows background, when chosing a background with lively, make lively change windows background too, with a fotogram of the video chosen for lively

**Comment by rocksdanister** [comment]
This feature already exists :)

![Screenshot 2021-12-18 171753](https://user-images.githubusercontent.com/17554161/146639852-54165062-3743-4353-bfba-a643db42cff7.png)
