### ISSUE TITLE
taskbar's effect  states disable when system wakeup

### ISSUE THREAD

**Issue by Vash90** [rocksdanister/lively#942]
**Describe the bug**
first, i set the taskbar is Clear.  It's OK
and, sleep the notePC.
when i wakeup my PC， the taskbar’s effect are not Clear.
the taskbar change to normal BLUE.

**To Reproduce**
as the Describe 

**Expected behavior**
nothing.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/6929525/146667862-1ca497e2-28d7-4201-b9f7-89c8f722bb1b.png)

**Desktop (please complete the following information):**
 - OS: windows 10 21H2  19044.1415
- Which wallpaper was running at the time if any.
JUST a simple website.
https://codepen.io/juliangarnier/pen/idhuG

**Additional context**
use a submonitor 14" 4K by HDMI

**Log file (Important)**

**Comment by ankurchavda** [comment]
Facing the same issue on Windows 11. Is there a fix in the plan for this?

**Comment by rocksdanister** [comment]
For now I recommend using third party software such as:
https://github.com/TranslucentTB/TranslucentTB
