### ISSUE TITLE
Desktop icons disappearing permanently

### ISSUE THREAD

**Issue by Erallie** [rocksdanister/lively#946]
**Describe the bug**
Everything on my desktop is no longer showing up on top of the wallpaper. Nothing I do is able to bring my desktop icons back.

**To Reproduce**
I'm not exactly sure what caused this, but I'm thinking that it was probably when I clicked a link inside the wallpaper that would normally open the destination in a new window or tab in your browser. Before my desktop icons disappeared, I noticed that if you clicked a link in the wallpaper, it would open it up inside of the wallpaper, but I don't think my icons disappeared when doing this previously, or if they did, they always came back when I switched out of the wallpaper and back into it again.

**Expected behavior**
Well, it would be nice if clicking links inside the wallpaper would open the destination in your browser, instead of inside the wallpaper.

**Screenshots/Video**
Here's a screenshot of how none of the icons on my desktop are showing up:
![Screenshot 2021-12-21 18 45 57](https://user-images.githubusercontent.com/31375589/147021057-6132e7fb-35cc-48ac-a8c6-a0570f691f91.png)

**Desktop**
 - OS: Windows 11 Home
- I was running the app I made as my wallpaper. It's being hosted on this website: [http://thecrawlingladybug.great-site.net/](http://thecrawlingladybug.great-site.net/)

**Additional context**
I have removed the function that I think made my desktop icons disappear, so you might not be able to reproduce the issue. I'm just hoping that I can get my desktop icons back.

**Log file**
[lively_log_20211221_184258.zip](https://github.com/rocksdanister/lively/files/7759354/lively_log_20211221_184258.zip)

**Comment by rocksdanister** [comment]
I don't see anything unusual in the previous 5 logfiles, did you perhaps turned on Keyboard input? icons are disabled to avoid selection when its on.

**Comment by Erallie** [comment]
I did for a second, but now it's off again. My icons still don't reappear when I quit lively completely.

**Comment by rocksdanister** [comment]
Its easy to check.. see if you enable it this way:

![Screenshot 2021-12-22 073340](https://user-images.githubusercontent.com/17554161/147022555-9308a978-b3fe-47e1-90fd-471767633d9e.png)

**Comment by Erallie** [comment]
Ahh okay yeah. I must have pressed a button that hid my desktop icons. I'm relatively new to windows, so I don't know all the functions, and now with my new keyboard, accidental presses are causing all kinds of weird stuff to happen that I don't know how to fix. Thanks though! Sorry for the false alarm.
