### ISSUE TITLE
Customising not working with YouTube links

### ISSUE THREAD

**Issue by KalHYDRA** [rocksdanister/lively#950]
Hi, I recently tried to add a video I liked as my Wallpaper with lively, I got the link from the URL box, pressed create wallpaper, and pasted it in, it began to process and after it processed, i tried to mute it (Since it had loud music), and it came up with this message when I selected customize wallpaper.

![image](https://user-images.githubusercontent.com/96523271/147072995-9ffacd45-79a5-4d54-a8b2-66590ed03b43.png)

Note: I have MPV player installed on my laptop, and working, and am currently using the Microsoft store version

the wallpaper I tried to use: _ _ _

Help appreciated since this has left me stumped lol

**Comment by rocksdanister** [comment]
Customisation is only supported for local video files.

You can globally mute wallpaper volume by Settings -> Audio -> Master Volume -> 0
