### ISSUE TITLE
Pause Wallpaper on screensaver

### ISSUE THREAD

**Issue by Erallie** [rocksdanister/lively#952]
**Is your feature request related to a problem? Please describe.**
Although there is an option to use the wallpaper you select as a screensaver, I don't use this option, as I have another screensaver that I prefer to use instead. Whenever I exit the screensaver, I see that my wallpaper has been running this entire time, and because of the way the wallpaper was created, that makes the wallpaper itself very laggy when I log back in every morning.

**Describe the solution you'd like**
It would be nice if there was an option to pause the wallpaper when your screensaver starts. This would lower memory usage as well, and improve ratings.

**Describe alternatives you've considered**
I was also trying to see if pausing the wallpaper when other applications are focused would eliminate the issue, however, when I enable that option, the wallpaper isn't automatically unpaused when I close or minimize all my windows, so I have to click on the wallpaper again in order to unpause it, which wasn't worth it in my opinion.

**Additional context**
I realize that part of the problem might be the way I designed the wallpaper, however as of now, I do not know any other way to fix it on my end.

**Comment by rocksdanister** [comment]
Wallpapers will get paused when fullscreen/>90% covering screen application is detected.. there is no reason for Lively to not detect screensaver as a fullscreen application unless the problem is on screensavers side.
