### ISSUE TITLE
UWP apps not pausing wallpaper

### ISSUE THREAD

**Issue by my-tech-group** [rocksdanister/lively#959]
When Lively is configured to pause the wallpaper on another window being in focused, this does not currently apply to UWP apps (such as Microsoft Store, Settings etc.).

This means that if you are using a UWP app, either just in the foreground or maximised, the wallpaper will continue playing regardless of the settings selected.

**Comment by rocksdanister** [comment]
Working fine on my system, can you describe steps by steps the things you did to test this?

**Comment by my-tech-group** [comment]
Hi,

I set the taskbar to clear so that I could see the wallpaper behind it and then maximised the Lively UWP app (from Windows Store) - I could then still see the wallpaper moving behind the taskbar and the GPU showing a high usage in Task Manager.

I then tried it with other UWP apps doing the same.

I hope this helps.

**Comment by rocksdanister** [comment]
>maximised the Lively UWP app (from Windows Store) 

Lively UI is exempted from those performance settings.

>I could then still see the wallpaper moving behind the taskbar and the GPU showing a high usage in Task Manager.

Foreground pause algorithm only takes the foreground app into account, in this case the taskmanager.. if you maximise taskmanager you will see wallpaper pause.

I am guessing that's what happened here.
