### ISSUE TITLE
Can support for "Wallpaper Engine" packages (.pkg files) be added?

### ISSUE THREAD

**Issue by CherryOak** [rocksdanister/lively#96]
It would be great if you could support package files from Wallpaper Engine so I could use it on Lively as well.

I don't know if there's a specific way to code Lively wallpapers to support the package files from Wallpaper Engine because I unpacked it using a program "Wallpaper-Engine-Pkg-To-Zip" and tried placing it in Lively folders but it doesn't work.

Wallpaper-Engine-Pkg-To-Zip: https://github.com/TheRioMiner/Wallpaper-Engine-Pkg-to-Zip
Wallpaper Engine Website: https://www.wallpaperengine.io/
sample_wallpaper.pkg unpacked: https://drive.google.com/drive/folders/1b88MjBM8nqMIZ-fWgcZOpLMj_VO0enTT?usp=sharing
Wallpaper folder: https://drive.google.com/drive/folders/1K74DzHNe6KYmoNW-rxS3kJ_4fKjCLs1J?usp=sharing

**Comment by rocksdanister** [comment]
I have no plants to do that.
