### ISSUE TITLE
Streaming Resolution Freezing Error

### ISSUE THREAD

**Issue by CHeaPistaken** [rocksdanister/lively#960]
**Describe the bug**
The bug occurs when the streaming resolution is above 480 pixels for me. My laptop is fairly new, and runs most fps games like Valorant quite easily at one hundred frames per second. However, when I select a resolution 480p or above, the wallpaper freezes at random times.

**To Reproduce**
1. Go to 'Lively Settings'
2. Click on 'Wallpaper'
3. Scroll down to 'Stream and Video Quality'
4. Select 1080 or 1080 plus.

**Expected behavior**
For the wallpaper to run without random freezing at a decent resolution.

**Desktop (please complete the following information):**
windows 10 latest version

[20211227_152820.txt](https://github.com/rocksdanister/lively/files/7781796/20211227_152820.txt)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/837
