### ISSUE TITLE
On opening my laptop lively wallpaper wont display the wallpaper *I have a video to help fix this*

### ISSUE THREAD

**Issue by nahor-25** [rocksdanister/lively#961]
Once I open my laptop my wallpaper is set to the default wallpaper I have I noticed this so i clicked on lively wallpaper to change it to the fluids v2 however it doesn't work imparintly lively wallpaper I don't know why if I go to the choose display it shows i have 2 screens my laptop screen and my second monitor so i dont know why it wont display the wallpaper

Here's a video if this helps
https://youtu.be/ljlmkjUeKMg

**Comment by nahor-25** [comment]
Another thing this happened right after I downloaded lively wallpaper and closed my laptop after finishing my stuff

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/802
