### ISSUE TITLE
Second monitor does not work well with lively wallpaper

### ISSUE THREAD

**Issue by quangtu2607** [rocksdanister/lively#964]
**Describe the bug**
Lively wallpaper cannot capture second monitor after restarting or returning from sleep.

**Desktop (please complete the following information):**
 - Windows 10
![image](https://user-images.githubusercontent.com/64002785/147627949-275cdc83-00f1-4eb0-9fcd-da046015d393.png)

**Log file (Important)**
[lively_log_20211229_113428.zip](https://github.com/rocksdanister/lively/files/7787337/lively_log_20211229_113428.zip)

**Comment by rocksdanister** [comment]
Is it https://github.com/rocksdanister/lively/issues/802 ?

**Comment by aaf-mike** [comment]
I'm having the same issue too.  I have two monitors, both different sizes and resolutions.  I've attached my log file also
[lively_log_20220125_142819.zip](https://github.com/rocksdanister/lively/files/7936605/lively_log_20220125_142819.zip).

**Comment by RacerXx** [comment]
so whats the deal with this bug?

**Comment by sourabhburse** [comment]
and screensaver also doesn't work well with second monitor.
In my case I am using laptop with monitor. Screensaver size on the monitor is same as laptop.
