### ISSUE TITLE
Lively 2.0 - UI/UX Redesign

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#969]
![Light and Dark Mode Shadow 100](https://user-images.githubusercontent.com/17554161/153703891-38a3d80b-5c7c-47a1-b6a2-13b58dbca60d.png)
(First release final result)

**Is your feature request related to a problem? Please describe.**
Update Lively UI to match Windows 11 design language with improvements to user experience.

**Additional context**
Currently Lively is tightly coupled to wpf, so the core will be made [separate](https://github.com/rocksdanister/lively/tree/core-separation) then WinUI or AvaloniaUI would be used for main UI.

**Early look:**
https://www.youtube.com/watch?v=2DEgioIRUHI

**Beta builds are up:**
https://github.com/rocksdanister/lively-beta/releases

Special thanks @zeealeid ♥

**Comment by rocksdanister** [comment]
**Mockup v1**
![Desktop_-_8](https://user-images.githubusercontent.com/17554161/147410151-0a693faf-4aeb-4214-bc20-0f9eb39c9836.png)
![IMG_6253](https://user-images.githubusercontent.com/17554161/147410116-07937d69-f793-4893-83c4-a3a6705262f8.png)
![IMG_6254](https://user-images.githubusercontent.com/17554161/147410117-cc270b1e-2e8b-472d-9e3a-c7c412a81ab0.jpeg)
![IMG_6256](https://user-images.githubusercontent.com/17554161/147410122-4dc383db-0e89-48a8-a94a-c03297ebc0bb.jpeg)
![IMG_6255](https://user-images.githubusercontent.com/17554161/147410141-b4dbc488-c9ce-4393-8da3-882d1ba1a3d3.jpeg)

**Mockup v2**
![IMG_6272](https://user-images.githubusercontent.com/17554161/147802802-0b97d1bd-f1f2-47d8-8b55-d2484568b662.jpeg)
![IMG_6266](https://user-images.githubusercontent.com/17554161/147802837-59de2406-10b4-4a0b-95c9-d458fde9e0a3.jpeg)
![IMG_6269](https://user-images.githubusercontent.com/17554161/147802838-45abf135-6e47-45c0-a46c-61b50a855a37.jpeg)

**Comment by rocksdanister** [comment]
**Mockup v3**
![Desktop_-_11](https://user-images.githubusercontent.com/17554161/148388482-53caf442-aac5-4a63-9034-6f29ac1bd030.png)
![Desktop_-_12](https://user-images.githubusercontent.com/17554161/148388489-4b76652e-d8be-45cc-b6c6-b3bc2ddb8fb9.png)

**Comment by rocksdanister** [comment]
**Idea**

https://user-images.githubusercontent.com/17554161/151307979-aee759e3-713f-41b6-bb36-84fdb7d93d1a.mp4

Live wallpaper based UI theme:
https://www.reddit.com/r/Windows11/comments/sbpztn/extensive_wallpaperbased_fluent_design_theming_on/
https://www.figma.com/community/file/1067659543344043831/Fluent-Palette

Can use thumbnail image for color calculation or even better capture a snapshot realtime!

**Comment by tellmewhy12** [comment]
Integration into Lively
![Playlist in UI](https://user-images.githubusercontent.com/71931749/151589450-de68c6ca-4945-4953-b30a-397cd6359b6a.png)

Simple user setup with menus
![Simple User Setup with Buttons](https://user-images.githubusercontent.com/71931749/151662575-b62a2d8c-4ad5-424e-9e70-b3fa7d087e42.png)

Complex user setup
![Complex User Setup](https://user-images.githubusercontent.com/71931749/151662572-6725774d-7174-48c8-b340-2e3b22c33c04.png)

Wallpaper Playlist UI/UX ideas

(Maybe making a special case functionality out of things like a "Startup Wallpaper", or introducing an advanced mode would be a good idea to not overwhelm the user here too)

**Comment by rocksdanister** [comment]
Apart from titlebar customisation(bugs), most of the design is complete.

Early video demo:
https://www.youtube.com/watch?v=2DEgioIRUHI

![Screenshot 2022-02-02 160858](https://user-images.githubusercontent.com/17554161/152154111-6f4bbf62-6f12-4862-bf0c-bc6d9a8a6be2.png)

![Screenshot 2022-01-31 170452](https://user-images.githubusercontent.com/17554161/152154142-14469452-d0fa-4e54-a3ed-9fd8cd50ea0e.png)

![Screenshot 2022-02-01 111935](https://user-images.githubusercontent.com/17554161/152154152-4c517b85-32ab-4a31-9f17-c24a054cdb90.png)

**Comment by rocksdanister** [comment]
Acrylic looks real nice~

![Screenshot 2022-02-03 033235](https://user-images.githubusercontent.com/17554161/152254645-5f2fd806-605b-4107-883c-8762baad35ec.png)

**Comment by rocksdanister** [comment]
New color picker

https://user-images.githubusercontent.com/17554161/152379407-c60f46e9-e7c5-4029-8b04-5a9b9c33f9ac.mp4

**Comment by rocksdanister** [comment]
Promo materials for first release:
![Light and Dark Mode Shadow 100](https://user-images.githubusercontent.com/17554161/153703827-fe2e0fdb-7f10-477c-a00d-8156ddab5db2.png)
![Screenshot 2022-02-11 220352](https://user-images.githubusercontent.com/17554161/153703840-e54085ed-04dd-4106-b18f-9a0460fd84ca.jpg)
![Screenshot 2022-02-11 220407](https://user-images.githubusercontent.com/17554161/153703842-105824c0-dfae-43fb-9432-7d21be8eb0a7.jpg)
![Screenshot 2022-02-11 220435](https://user-images.githubusercontent.com/17554161/153703843-bc4c33b9-8ce0-4528-8125-9ad030bd933c.jpg)
![Screenshot 2022-02-11 220458](https://user-images.githubusercontent.com/17554161/153703847-91059dab-dcb6-49e7-84f1-478f89ab190e.jpg)
![Screenshot 2022-02-11 220520](https://user-images.githubusercontent.com/17554161/153703848-065c1642-c90e-4ece-98ff-46a45c7beac8.jpg)
![Screenshot 2022-02-11 220542](https://user-images.githubusercontent.com/17554161/153703850-c472ffe4-609a-4937-b275-f80527f33bbb.jpg)
![Screenshot 2022-02-11 220610](https://user-images.githubusercontent.com/17554161/153703852-32d238c1-0387-430f-a2b0-06129468e9b4.jpg)
![Screenshot 2022-02-11 220659](https://user-images.githubusercontent.com/17554161/153703853-6a23936d-1af3-4b74-98e8-32edd5cc1a57.jpg)
![Screenshot 2022-02-11 220821](https://user-images.githubusercontent.com/17554161/153703854-e6f4d1d4-0624-44a0-8419-0f701cb7f8b8.jpg)
![Screenshot 2022-02-11 221116](https://user-images.githubusercontent.com/17554161/153703856-cd5e235d-288f-4e53-9ad9-3e248f3acb04.jpg)
![Screenshot 2022-02-11 221144](https://user-images.githubusercontent.com/17554161/153703858-a26fdeee-948a-4bee-aa9b-f101bf47a3ef.jpg)
![Screenshot 2022-02-11 215346](https://user-images.githubusercontent.com/17554161/153703865-adb133b8-85d5-44ba-a9b3-e07df2610f64.jpg)
![Screenshot 2022-02-11 215823](https://user-images.githubusercontent.com/17554161/153703866-a25e7d40-ce45-43f2-aa43-9ca4134bfd32.jpg)
![Screenshot 2022-02-11 220011](https://user-images.githubusercontent.com/17554161/153703869-6b4e40b3-dd4d-4e41-8a6f-67e0a3660848.jpg)
![Screenshot 2022-02-11 220242](https://user-images.githubusercontent.com/17554161/153703871-673c5d1e-4b68-4844-8285-6631d8082dc6.jpg)

**Comment by rocksdanister** [comment]
Beta builds are up!
https://github.com/rocksdanister/lively-beta/releases

**Comment by rocksdanister** [comment]
Release discussion moved to https://github.com/rocksdanister/lively/issues/1080

**Comment by rocksdanister** [comment]
Promo material:
![Lively Banner HiQ With Drop Shadow](https://user-images.githubusercontent.com/17554161/158042653-29e11688-1f26-4b4a-b09c-7f99fa495b70.png)
![Lively Banner HiQ Square](https://user-images.githubusercontent.com/17554161/158042659-f0c9185b-e427-47a4-b93f-e867de869c89.png)

**Comment by Westlin67** [comment]
sunset gone why ?
