### ISSUE TITLE
Translation help (v1.0)

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#97]
New localization files added for upcoming lively [v1.0](https://github.com/rocksdanister/lively/issues/74) release.

You can get started if your language is available, otherwise use the English file:
https://github.com/rocksdanister/lively-translations

![Annotation 2020-08-06 114507](https://user-images.githubusercontent.com/17554161/89500057-a9d15000-d7de-11ea-80d9-d7c3a1f3ec04.jpg)

**Comment by LuciusMercier** [comment]
You can change the language with the first dropdown menu that appears.

**Comment by rocksdanister** [comment]
I do not understand, what do you mean?

**Comment by LuciusMercier** [comment]
Oh, wait, nvm

**Comment by rocksdanister** [comment]
😂
