### ISSUE TITLE
Wallpaper unpausing when foreground application not fullscreen

### ISSUE THREAD

**Issue by Adri874** [rocksdanister/lively#970]
**Describe the bug**
This program stops the playback of the wallpaper when you are using an application that covers all of the screen so the desktop is not visible, this is correct and perfect. When a program you are using doesn't covers the full screen so that a part of the desktop is visible, then the program plays the wallpaper, this is correct for sure. The problem comes here: If you use 2 programs, 1 covering all of the screen like Google Chrome, but you are focusing another window like task manager (doesn't cover the full screen) then the program will still play the wallpaper although you are not seeing the desktop actually, behind task manager window, there is Google Chrome blocking the view of the desktop, so it should know this and don't start playing the wallpaper.

**To Reproduce**
1. Hide any windows first, only look at your desktop,
2. Open Task Manager, mark the option Always on Top, search for the process mvp.exe and watch the GPU usage, while the wallpaper is playing then you will see the GPU usage there.
3.  Now open Google Chrome maximized and click once in any part of Google Chrome, you will see that mvp.exe stops using the GPU because it stopped playing the wallpaper.
4. Keep the Chrome window like that, and then click once in any part of task manager window, you will see how mvp.exe GPU usage rises while you are not seeing the desktop actually. 

**Expected behavior**
The program shouldn't play the wallpaper if the desktop is not visible. This glitch happens because the program only checks the window you are focusing but not the other windows opened, it should consider there might be another window/s not allowing the view of the desktop and don't start to play the wallpaper in that case. 
To solve this, you can make the program do the following, if the window focused doesn't cover all the screen, then instead of start to play the wallpaper instantly, run 1 more verification, check if there is any other window behind and if there is another then check if it's covering all the screen, if the other window is not covering the screen, then check again if there is other window (like a loop and you can make it exit the loop after 6 verifications for example, to avoid the program stuck) and after that, play wallpaper, if there is found a window opened that covers the screen then: do nothing.
There is 1 more bug that could happen with this solution, if you open 4 windows not maximized and you arrange them in a way that the windows combined covers all of the screen (although they are not maximized), then it will play the wallpaper even in that moment, because the 4 windows are covering your view, but none of them alone covers the whole screen, so to avoid that you could make the program verify which pixels are covered by each window shown and calculate if it covers all the screen in the end blocking the desktop view or not, but this might be more complicated and I know that might take time you don't have, I think adding another verification(as I told you above) to make sure there is not any other window covering the screen before starting to play the wallpaper, it's a good solution and enough for most of the situations.

**Screenshots/Video**
Here is a video I made: https://youtu.be/5cC9sPqH32A

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro 19044.1415  Version 21H2 
- Got the wallpaper from here, it's just a mp4, I added it to the program as normal: ---

**Additional context**
I play a game that uses 2 windows, 1 the launcher covers all of the screen, and 2 the lobby is smaller and it's airlobby by Flash Player, it's not a full window but it's into the 1st window (launcher), with this glitch if I'm using the game my wallpaper will always run because the program thinks I'm using a window that allows me to see the desktop but actually there is 1 more window behind(launcher) that is covering the screen, so it shouldn't play the wallpaper in this situation, this is just 1 example of many:  Having Google Chrome opened maximized, Discord, and then opening Windows Explorer Window, as windows explorer window is not maximized normally, it will also play the wallpaper in this situation even though I can't see the desktop in that moment actually.

**Log file (Important)**
There is not log file for this issue, because it's not a glitch or bug actually, it's just a little detail you missed while creating the resource saving part.
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/474
