### ISSUE TITLE
Pause status

### ISSUE THREAD

**Issue by Ziggizag** [rocksdanister/lively#974]
Hi,

I read that when Lively wallpaper is "paused" - for instance due to high-priority application being used in the foreground - actually its internal browser window is minimized, so it can be traced through "visibilitychange" event in the Javascript.

So, I observe, that it is very unreliable!

I can see for instance, javascript intervals processing their function code regardless the following escape condition:

```
	setInterval(function() {
		if (document.hidden) {
			return;
		}
```

or even like that:

```
	setInterval(function() {
		if (document.visibilityState !== "visible") {
			return;
		}
```
The result is accumulation of inerval-related events what are then "fired" as soon as the focus is returned to wallpaper (in my case - a plethora of ripples after half an hour reading something in Firefox).

Is there any better way to pass "paused" condition to javascript?

**Comment by rocksdanister** [comment]
>its internal browser window is minimized.

This is no longer true: https://github.com/rocksdanister/lively/issues/20#issuecomment-973789080

>Is there any better way to pass "paused" condition to javascript?

I was thinking of doing a custom Lively JavaScript event similar to [these.](https://github.com/rocksdanister/lively/wiki/Web-Guide-V-:-System-Data)

```js
function livelyWallpaperPlaybackChanged(data)
{
   var obj = JSON.parse(data);
   console.log(obj.State); //true = paused, false = unpaused.
}
```

**Comment by Ziggizag** [comment]
Hmm - so, is there any working solution in Javascript to let it know rendering is paused?

**Comment by Ziggizag** [comment]
That would be very handy!
Is this idea already "processed" in your Code Studio or this is for some future version but not really quickly?

**Comment by rocksdanister** [comment]
Not done.

Its just a matter of adding the relevant code here:
https://github.com/rocksdanister/lively-cef/blob/0d67ad422686e352fc8004e353c6cd59def05e57/src/LivelyCefSharp/Form1.cs#L210-L215

**Comment by Ziggizag** [comment]
Any idea concerning time frame for this implementation?

**Comment by rocksdanister** [comment]
Don't have a release date in mind at the moment, added it to v1.8 milestone.

**Comment by Ziggizag** [comment]
@rocksdanister Hello,

So how is the status now? I can't see any progress at the moment :-(

**Comment by rocksdanister** [comment]
I moved this to v2.1 milestone so will take time.

Which version of Lively are you using, Windows store or github installer?

If its installer then I can provide a browser build with the support:
https://github.com/rocksdanister/lively-cef/releases

**Comment by Ziggizag** [comment]
@rocksdanister I can you whatever version - it does not matter. I believe it's a regular installer (not Windows Store) anyway, so custom build would be fine. Please!

**Comment by Ziggizag** [comment]
@rocksdanister What kind of release is it? I double click Lively.PlayerCefSharp.exe and nothing happens :-(

**Comment by rocksdanister** [comment]
Oh I have not made it yet 😅
Yeah installer works!

**Comment by Ziggizag** [comment]
??? Sorry, I am not a C programmer - cannot cope :-/

**Comment by rocksdanister** [comment]
Sorry, I mean I was just asking.. I did not implement the feature yet.

**Comment by Ziggizag** [comment]
OK - Please, you promised it already time ago :-(

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively-cef/releases/tag/v1.5.0.0

Replace the contents of the Cef install folder with this release.

* For non-admin install:

  `C:\Users\<UserName>\AppData\Local\Programs\Lively Wallpaper\Plugins\Cef`

* For admin install:

  `C:\Program Files (x86)\Lively Wallpaper\Plugins\Cef`

To enable the event per wallpaper, edit `LivelyInfo.json` in wallpaper folder:
```json
  "Arguments": "--pause-event true",
```
and in javascript:
```js
function livelyWallpaperPlaybackChanged(data)
{
 var obj = JSON.parse(data);
 console.log(obj.IsPaused);
}
```

**Comment by Ziggizag** [comment]
Wow,

Thank You so much!
This is working as expected - congratulation - problem solved 👍 Finally my PC don't get stacked with thousands of rings being fired while returning to desktop after being out of focus for some longer time.

Best regards!

**Comment by rocksdanister** [comment]
That's good👍
Can you share the modifications made to ripple page to support pausing so that I can update it later.

**Comment by Ziggizag** [comment]
![desktop](https://user-images.githubusercontent.com/2280036/172846650-0d997408-c08b-4f9b-8085-8dc6c05f1568.png)

OK - here you are, but please - I have modified it for minimalistic look and double-monitor system. Weather forecast is now placed in the middle of primary screen. I have also updated the background image to fit my taste :)


[removed]

**Comment by rocksdanister** [comment]
Oh yeah I removed the upload due to copyright reasons(kind of an unwritten rule to not have file uploads here).. 
Originally just asking for the pausing js code for ripple 😅

**Comment by Ziggizag** [comment]
@rocksdanister Thank you for a clue :-D

Anyway - thank you once again for your kindly help!

ZS

**Comment by rocksdanister** [comment]
Next update the browser will have support for this.
