### ISSUE TITLE
.NET Core missing, Lively never boots

### ISSUE THREAD

**Issue by ivo-hr** [rocksdanister/lively#978]
**Describe the bug**
.NET Core not detected, won't start the application

**To Reproduce**
1. Open lively
2. On the error message detailing the .net core isn't installed, select "yes"
3. Download  .NET Core 3.1 Desktop Runtime (v3.1.22) - Windows x64 (from the [link](https://dotnet.microsoft.com/en-us/download/dotnet/3.1/runtime) the application redirects to)
4. Restart the PC
5. Open lively again, same issue

**Expected behavior**
The application should open

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/81875802/147890520-d2b82e36-e88e-43ae-bcf1-aa8fa235a490.png)
![image](https://user-images.githubusercontent.com/81875802/147890538-d569be47-b0af-4fb8-94ce-0c50acff4ac5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2 (os build 19044.1415)
 
**Additional context**
It did work in another PC where I didn't install anything

**Log file (Important)**
No log files nor folders due to it not really ever loading

**Comment by rocksdanister** [comment]
I am guessing you downloaded from WinGet? otherwise installer will take care of runtime installation.

Lively is a x86 application so you need x86 runtime and VC++ redistribuatle:
https://github.com/rocksdanister/lively/wiki/Getting-Started#setup

**Comment by ivo-hr** [comment]
No, I installed it with the installer. Just now fixed it by reinstalling, I don't know what was happening before but now it works.
Anyways, thanks for the fast response and for the amazing wallpapers!

**Comment by rocksdanister** [comment]
During the installer did you get a .Net Core runtime installing message and Windows admin prompt?

**Comment by ivo-hr** [comment]
I did both times, don't know what may have happened the first. Maybe it was Visual Studo that was installing at the same time?

**Comment by rocksdanister** [comment]
You don't need the SDK for running Lively - it can be removed.
