### ISSUE TITLE
Windows 8.1 bug: Wallpaper loses mouse focus on desktop

### ISSUE THREAD

**Issue by Rexmine** [rocksdanister/lively#98]
**Describe the bug**
The wallpaper loses focus of the mouse when I go to the desktop

**Screenshots/Video**
https://youtu.be/Yppk1h48DZc

**Desktop (please complete the following information):**
 - OS: Windows 8.1
- The wallpapers are:
https://www.deviantart.com/rocksdanister/art/Fizzy-Sparks-837554620
and
https://www.deviantart.com/rocksdanister/art/Periodic-Table-843931913

**Comment by rocksdanister** [comment]
Yeah this is a windows 8.1 bug due to some difference in the way cef/windows input is working.
Unfortunately, I can't fix this unless I get access to win 8.1 system myself.

**Comment by Rexmine** [comment]
Ok, guess I'll use only non-interactive ones

**Comment by rocksdanister** [comment]
Closing this since Windows 8.1 is no longer supported from v1.0 onwards.
