### ISSUE TITLE
wallpaper disappear after screen turns off

### ISSUE THREAD

**Issue by hanzeroo** [rocksdanister/lively#983]
when the screen is turned off the wallpaper disappears and when you try to re choose it from lively app it bufffers and shows the wallpaper is up but the screen shows the default windows theme  

 its on windows 11
- Which wallpaper was running at the time if any.

well i got a kind of way to solve the issue
first click
. ctrl+sift+esc ; it opens task manager
. then find lively app 
. right click on it
. end task
and re open the lively app it solves the problem but it has to be done every time you turn off screen

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/802
