### ISSUE TITLE
Wallpaper does not pause when opening two or more applications in split screen view

### ISSUE THREAD

**Issue by MrLoersn** [rocksdanister/lively#987]
If you open two or more applications in split screen view, the wallpaper does not pause, although it should, as the whole screen is covered by the applications. You can recognize this by either choosing the taskbar theme "Wallpaper" or by looking at the workload of the graphics card in the task manager. This problem occurs with every wallpaper.
I have Windows version 10.0.19044.

**Comment by rocksdanister** [comment]
duplicate: #474
