### ISSUE TITLE
Add auto-refresh

### ISSUE THREAD

**Issue by xmha97** [rocksdanister/lively#988]
On my desktop is the Google calendar website.
Please add the auto-refresh feature.
![image](https://user-images.githubusercontent.com/23485114/148469232-141574a2-5bb4-4516-89bb-59445f15e130.png)

**Comment by rocksdanister** [comment]
This command can reload the page:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#seek-wallpaper

You can write a script that runs it frequently.

**Comment by xmha97** [comment]
> This command can reload the page: https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#seek-wallpaper
> 
> You can write a script that runs it frequently.

I installed Lively Wallpaper from Microsoft Store.
Can I run the app with the command line?
You should set an app execution alias
![image](https://user-images.githubusercontent.com/23485114/148520819-09bff82b-5e85-4b03-aa07-804beb2e914d.png)
![image](https://user-images.githubusercontent.com/23485114/148521224-433b3b00-2e4e-49e7-9958-3df170bf563a.png)

**Comment by rocksdanister** [comment]
>I installed Lively Wallpaper from Microsoft Store.
Can I run the app with the command line?

Yes, just need to use the  commandline-utility and also install the runtime for the utility:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#instruction

>You should set an app execution alias

Will look into it in the future, right now its recommended to just use commandline-utility.
