### ISSUE TITLE
Not Showing Wallpapers in Library

### ISSUE THREAD

**Issue by Dustir** [rocksdanister/lively#989]
Hi,

Whenever I open up the app, the Library appears to be empty. I just updated to the v1.7.4.2 (don't know if that helps or not)

**Expected behavior**
I expected to open the app and the wallpapers to be there

**Screenshots/Video**
![Screenshot 2022-01-07 001347](https://user-images.githubusercontent.com/97275205/148500465-eca435ee-abcc-4bdf-bdce-db3b83164c99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Which wallpaper was running at the time if any.
The Mountain rain one

**Log file**
[lively_log_20220107_001223.zip](https://github.com/rocksdanister/lively/files/7826879/lively_log_20220107_001223.zip)

**Comment by Dustir** [comment]
It also has the Logo doing this 
![Screenshot 2022-01-07 001745](https://user-images.githubusercontent.com/97275205/148500840-46feee82-da8e-4843-af58-45bea6a52003.png)

**Comment by rocksdanister** [comment]
duplicate: https://github.com/rocksdanister/lively/issues/927

**Comment by rocksdanister** [comment]
Regarding the empty library, log says there are no files (can you verify this?).. if the folder is indeed empty you can just delete `C:\Users\<UserName>\AppData\Local\Lively Wallpaper` folder and restart the app to run the setup wizard from the beginning.
