### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by xmha97** [rocksdanister/lively#991]
Dear Dani,
Please support `Custom CSS` like [OBS Studio](https://github.com/obsproject/obs-studio).

![image](https://user-images.githubusercontent.com/23485114/148617892-21e1f9d8-878c-40db-a35b-7c6629d43c54.png)

Thanks.

**Comment by xmha97** [comment]
This sounds like a duplicate of #711

**Comment by gdhy2193-bit** [comment]
![Image](https://github.com/user-attachments/assets/d65fc8d3-9059-4827-b798-8421a21eb14f)
