### ISSUE TITLE
File not found ERROR for video files

### ISSUE THREAD

**Issue by shanen23** [rocksdanister/lively#999]
**Describe the bug
whenever i turnoff my PC and turn it back on lively shows an error (FILE NOT FOUND) this problem is only with the wallpapers i add at first they work fine but whenever i restart my PC the wallpaper doesn't work 

**To Reproduce**

**Expected behavior**
I was expecting it work just fine even when i turn off my PC and turn it on again 

**Desktop (please complete the following information):**
 - OS: [windows 10 Pro]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
_
[lively_log_20220109_195008.zip](https://github.com/rocksdanister/lively/files/7835233/lively_log_20220109_195008.zip)
![Screenshot 2022-01-09 195343](https://user-images.githubusercontent.com/97394439/148686469-885f3b0e-fd20-481c-b428-f2cad34a114a.png)
_

**Comment by shanen23** [comment]
pls help someone ???

**Comment by rocksdanister** [comment]
When you add video files into Lively only the location of the file is stored - the file is not copied to Lively folder.
The files are in your downloads folder, most likely deleted automatically by Windows cleanup or by accident.

If you wish to copy the file into Lively's data folder then:
`Rightclick the item -> Extract .zip -> delete the item -> Install the created .zip file by dropping it into Library.`
